### ISSUE TITLE
Mapping entire struct to DynamoDB

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#100]
```
~$ go version ; git -C ~/go/src/github.com/aws/aws-sdk-go-v2 describe --all
go version go1.9.2 linux/amd64
tags/v2.0.0-preview.2

```
### What issue did you see?

I find it cumbersome to maintain a mapping between my struct and dynamodb with `expression.Set`. Is there a way to map/marshal the whole struct to dynamodb? I can't see how that's done with https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb/expression

<img src=https://s.natalian.org/2018-01-17/1516158428_2548x1398.png>

**Comment by xibz** [comment]
Hello @kaihendry, thank you for reaching out to us. If you are just looking to just upload a whole structure, then using the [`dynamodbattribute` package](https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/dynamodbattribute/) is the best approach. The `expressions` package was meant for ease of use for expressions. Please let us know if you have anymore questions regarding this.

**Comment by jasdel** [comment]
Hi @kaihendry let us know if you're still running into this issue, or have additional questions about the dynamodbattribute package.
