### ISSUE TITLE
v.0.31.0 has an issue with module upgrade

### ISSUE THREAD

**Issue by gowrisankar22** [aws/aws-sdk-go-v2#1009]
Hello All,

I am unable to upgrade to `v.0.31.0` 
```
go fmt ./...
go vet ./...
# github.com/aws/aws-sdk-go-v2/ec2imds
../../../go/pkg/mod/github.com/aws/aws-sdk-go-v2/ec2imds@v0.1.5/api_client.go:56:29: cannot use "github.com/aws/aws-sdk-go-v2/aws/middleware".AddUserAgentKey("ec2imds") (type func(*"github.com/aws/smithy-go/middleware".Stack) error) as type func(*"github.com/awslabs/smithy-go/middleware".Stack) error in append
../../../go/pkg/mod/github.com/aws/aws-sdk-go-v2/ec2imds@v0.1.5/api_client.go:102:21: cannot use cfg.APIOptions (type []func(*"github.com/aws/smithy-go/middleware".Stack) error) as type []func(*"github.com/awslabs/smithy-go/middleware".Stack) error in append
../../../go/pkg/mod/github.com/aws/aws-sdk-go-v2/ec2imds@v0.1.5/request_middleware.go:48:48: cannot use stack (type *"github.com/awslabs/smithy-go/middleware".Stack) as type *"github.com/aws/smithy-go/middleware".Stack in argument to "github.com/aws/aws-sdk-go-v2/aws/middleware".AddUserAgentKey(ServiceID)
../../../go/pkg/mod/github.com/aws/aws-sdk-go-v2/ec2imds@v0.1.5/request_middleware.go:87:34: cannot use stack (type *"github.com/awslabs/smithy-go/middleware".Stack) as type *"github.com/aws/smithy-go/middleware".Stack in argument to retry.AddRetryMiddlewares
make: *** [vet] Error 2
```

```
go get -u github.com/aws/aws-sdk-go-v2/ec2imds                                                                      8s
go: github.com/aws/aws-sdk-go-v2 upgrade => v0.31.0
go: github.com/awslabs/smithy-go upgrade => v0.5.0
go get: github.com/awslabs/smithy-go@v0.4.0 updating to
	github.com/awslabs/smithy-go@v0.5.0: parsing go.mod:
	module declares its path as: github.com/aws/smithy-go
	        but was required as: github.com/awslabs/smithy-go
```

**Comment by gowrisankar22** [comment]
Fixed..

**Comment by shogo82148** [comment]
A memo for who have same issue.

it is a breaking change of https://github.com/aws/aws-sdk-go-v2/releases/tag/v0.31.0

> The module ec2imds moved to feature/ec2/imds path (#984)

So, I needed to change the import path.

```diff
-import "github.com/aws/aws-sdk-go-v2/ec2imds"
+import "github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
```

**Comment by stevefchambers** [comment]
**Upgraded to 0.31.0 from 0.30.0, ran into the following issue, not seen in 0.30.0**

`Can't run linter goanalysis_metalinter: bodyclose: 
failed prerequisites: 
analysis skipped: 

could not import github.com/aws/aws-sdk-go-v2/config (/Users/user/go/pkg/mod/github.com/aws/aws-sdk-go-v2/config@v0.3.0/provider.go:9:2: could not import github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds (/Users/user/go/pkg/mod/github.com/aws/aws-sdk-go-v2/credentials@v0.1.5/ec2rolecreds/provider.go:13:2: 
could not import github.com/aws/aws-sdk-go-v2/ec2imds (/Users/user/go/pkg/mod/github.com/aws/aws-sdk-go-v2/ec2imds@v0.1.5/api_client.go:57:3: cannot use awsmiddleware.AddUserAgentKey(\"ec2imds\") (value of type func(*\"github.com/aws/smithy-go/middleware\".Stack) error) as func(*\"github.com/awslabs/smithy-go/middleware\".Stack) error value in argument to append)))]]"

failed to load package ec2imds: could not load export data: no export data for \"github.com/aws/aws-sdk-go-v2/ec2imds\""
failed to load package ec2imds: could not load export data: no export data for \"github.com/aws/aws-sdk-go-v2/ec2imds\""
`
