### ISSUE TITLE
Credentials Setup 

### ISSUE THREAD

**Issue by gowrisankar22** [aws/aws-sdk-go-v2#1010]
Confirm by changing [ ] to [x] below:
- [ x] I've gone through the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

aws go SDK v1, we have an option during the session creation to pass the required credentials(read from k8s secrets) instead of reading from environmental variables. 

with aws go SDK v2 I didn't see the option to pass the credentials on my own reading from k8s secrets.

Migration guide dint tells the option. https://aws.github.io/aws-sdk-go-v2/docs/migrating/

```
// Gets the aws session
func GetAwsSession(region string, awsAccessKeyID string, awsSecretAccessKey string) (*session.Session, error) {
	if awsAccessKeyID == "" || awsSecretAccessKey == "" {
		config := aws.Config{
			Region:     aws.String(region),
			MaxRetries: aws.Int(awsSdkMaxRetries),
		}

		sess, err := session.NewSessionWithOptions(session.Options{
			Config:            config,
			SharedConfigState: session.SharedConfigEnable,
		})

		if err != nil {
			return nil, err
		}

		return sess, nil
	}

	sess, err := session.NewSession(&aws.Config{
		Region:      aws.String(region),
		Credentials: credentials.NewStaticCredentials(awsAccessKeyID, awsSecretAccessKey, ""),
	})

	if err != nil {
		return nil, err
	}

	return sess, nil
}
```

I am gonna handle multiple AWS accounts. Instead of reading from environmental variables, I want to read it from Kubernetes secrets and just want to pass it for the session.

Can you suggest better approach in this to handle secrets securely?

**Comment by skotambkar** [comment]
Thanks for reaching out. If the requirement here is to be able to pass in static credentials while initializing config, you can use `config.WithCredentialsProvider`  helper which would take in credential values via the `credentials.StaticCredentialsProvider`

Here's the documented example on how to use static credentials provider. 
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config#example-WithCredentialsProvider

**Comment by gowrisankar22** [comment]
@skotambkar Thanks 👍
