### ISSUE TITLE
GetObjectAcl of S3 always returns an empty grantee type

### ISSUE THREAD

**Issue by shogo82148** [aws/aws-sdk-go-v2#1013]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

[GetObjectAcl](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#Client.GetObjectAcl) of S3 always returns an empty grantee type.

**Version of AWS SDK for Go?**

```
module main

go 1.15

require (
	github.com/aws/aws-sdk-go v1.36.20
	github.com/aws/aws-sdk-go-v2 v0.31.0
	github.com/aws/aws-sdk-go-v2/config v0.4.0
	github.com/aws/aws-sdk-go-v2/service/s3 v0.31.0
	github.com/kr/pretty v0.2.1
)
```

**Version of Go (`go version`)?**

```
go version go1.15.6 darwin/amd64
```

**To Reproduce**

```go
package main

import (
	"context"
	"log"
	"strings"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"

	awsv2 "github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	s3v2 "github.com/aws/aws-sdk-go-v2/service/s3"

	"github.com/kr/pretty"
)

func main() {
	const bucket = "shogo82148-test"
	const key = "debug.txt"
	const region = "ap-northeast-1" // the region of shogo82148-test bucket

	sess := session.Must(session.NewSession(&aws.Config{
		Region: aws.String(region),
	}))

	ctx := context.Background()
	v1 := s3.New(sess)
	_, err := v1.PutObjectWithContext(ctx, &s3.PutObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
		Body:   strings.NewReader("foobar"),
	})
	if err != nil {
		log.Fatal(err)
	}

	// AWS SDK v1
	respv1, err := v1.GetObjectAclWithContext(ctx, &s3.GetObjectAclInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	})
	if err != nil {
		log.Fatal(err)
	}
	pretty.Log(respv1.Grants)

	// AWS SDK v2
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		log.Fatal(err)
	}
	v2 := s3v2.NewFromConfig(cfg)
	respv2, err := v2.GetObjectAcl(ctx, &s3v2.GetObjectAclInput{
		Bucket: awsv2.String(bucket),
		Key:    awsv2.String(key),
	})
	if err != nil {
		log.Fatal(err)
	}
	pretty.Log(respv2.Grants)
}
```

result:

```
% go run main.go
2021/01/05 16:53:42 []*s3.Grant{
    &s3.Grant{
        _:       struct {}{},
        Grantee: &s3.Grantee{
            _:            struct {}{},
            DisplayName:  &"shogo82148",
            EmailAddress: (*string)(nil),
            ID:           &"51915c5bd71c959533019b53a63318b74bf3f85d6cbe9708d564187d200649c7",
            Type:         &"CanonicalUser",
            URI:          (*string)(nil),
        },
        Permission: &"FULL_CONTROL",
    },
}
2021/01/05 16:53:42 []types.Grant{
    {
        Grantee: &types.Grantee{
            Type:         "",
            DisplayName:  &"shogo82148",
            EmailAddress: (*string)(nil),
            ID:           &"51915c5bd71c959533019b53a63318b74bf3f85d6cbe9708d564187d200649c7",
            URI:          (*string)(nil),
        },
        Permission: "FULL_CONTROL",
    },
}
```

**Expected behavior**

I want to get "CanonicalUser" grantee type.

```
2021/01/05 16:53:42 []types.Grant{
    {
        Grantee: &types.Grantee{
            Type:         "CanonicalUser", // I got ""
            DisplayName:  &"shogo82148",
            EmailAddress: (*string)(nil),
            ID:           &"51915c5bd71c959533019b53a63318b74bf3f85d6cbe9708d564187d200649c7",
            URI:          (*string)(nil),
        },
        Permission: "FULL_CONTROL",
    },
}
```

AWS SDK v1 returns my expected result, but v2 doesn't.

**Additional context**

Is `types.TypeCanonicaluser` intended name? it should be `types.TypeCanonicalUser` ?

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3/types#Type

**Comment by jasdel** [comment]
Thanks for reporting this issue @shogo82148. The SDK's behavior of not being able to deserialize the Grantee type is definitely a bug in the SDK. This most likely is related to the SDK's handling of XML attributes with namespaces. There was a similar bug in the v1 SDK few years ago, https://github.com/aws/aws-sdk-go/pull/975 and https://github.com/aws/aws-sdk-go/issues/916.


Also thanks for pointing out the unexpected enum name casing. I've corrected the enum casing in #1020.

**Comment by JordonPhillips** [comment]
This does seem to be related to namespaces. For example, the actual XML returned looks something like this:

```xml
<Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser">
    <ID>foo</ID>
    <DisplayName>bar</DisplayName>
</Grantee>
```

We try to decode this right around [here](https://github.com/aws/aws-sdk-go-v2/blob/main/service/s3/deserializers.go#L13925). The parsed values of the attrs look something like this:

```
[]xml.Attr{
    {
        Name:  xml.Name{Space:"xmlns", Local:"xsi"},
        Value: "http://www.w3.org/2001/XMLSchema-instance",
    },
    {
        Name:  xml.Name{Space:"http://www.w3.org/2001/XMLSchema-instance", Local:"type"},
        Value: "CanonicalUser",
    },
}
```

We're checking `Local` for `xsi:type` on each of these, but it would never equal that both because the namespace is separate and because it appears fully resolved.

**Comment by JordonPhillips** [comment]
And this does appear to be exactly the same issue referenced above
