### ISSUE TITLE
types.AttributeValueMemberS doesnt seem to work

### ISSUE THREAD

**Issue by jedzme** [aws/aws-sdk-go-v2#1018]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [ X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
The types.AttributeValueMemberS doesnt seem to work, please code snippet below.
I always get this error:
"_operation error DynamoDB: GetItem, https response error StatusCode: 400, RequestID: 2T1IRD6RD348V9MPU8JSPNNCD7VV4KQNSO5AEMVJF66Q9ASUAAJG, api error ValidationException: The provided key element does not match the schema_"

**Version of AWS SDK for Go?**
	*github.com/aws/aws-sdk-go-v2 v0.31.0
	*github.com/aws/aws-sdk-go-v2/config v0.4.0
	*github.com/aws/aws-sdk-go-v2/credentials v0.2.0
	*github.com/aws/aws-sdk-go-v2/service/dynamodb v0.31.0

**Version of Go (`go version`)?**
1.15

**To Reproduce (observed behavior)**
*Create a table in DynamoDB with the primary key as string
* Use this code snippet:
Note: myDynamoDBClient was successfully instantiated as *dynamodb.Client
`	result, err := myDynamoDBClient.GetItem(ctx, &dynamodb.GetItemInput{
		Key: map[string]types.AttributeValue{
			"myprimarykey": &types.AttributeValueMemberS{Value: key},
		},
		TableName:                aws.String(myTableName),
	})`

**Expected behavior**
Should be able to return the DDB record/item

**Additional context**
And also, the aws go SDK v2 doesn't provide a libray to unmarshal the returned result, not like in v1 where we can call:
` import "github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute"
 dynamodbattribute.UnmarshalMap(result.Item, &data)`

**Comment by jedzme** [comment]
please disregard the problem above, everything seems working now. i just missed to add the sort key in GetItemInput.

I just have one question, is there a way to unMarshal or decode the result Item which is of type map[string]types.AttributeValue to a specific business model?

**Comment by skmcgrail** [comment]
@jedzme https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue package provides utilities for mapping to and from custom Go types.

**Comment by jedzme** [comment]
> @jedzme https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue package provides utilities for mapping to and from custom Go types for DynamDB items.

thanks Sean! @skmcgrail
