### ISSUE TITLE
CloudWatch DisableAlarmActions fails to deserialize success response 

### ISSUE THREAD

**Issue by aayush-plivo** [aws/aws-sdk-go-v2#1053]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Running 

**Version of AWS SDK for Go?**
0.31.0

**Version of Go (`go version`)?**
1.15.2

**To Reproduce (observed behavior)**

Calling the DisableAlarmActions method fails during deserialization of the response as it seems to be expecting `DisableAlarmActionsResult` when it should be expecting `DisableAlarmActionsOutput`. This happens even when the status code returned from the API is 200 (success).

```
operation error CloudWatch: DisableAlarmActions, https response error StatusCode: 200, RequestID: <SomeRequestID>,
deserialization failed, failed to decode response body, DisableAlarmActionsResult node not found
```

**Expected behavior**
There shouldn't be any deserialization error.

**Additional context**
NA

**Comment by jasdel** [comment]
Thanks for reporting this issue @aayush-plivo this has been fixed in https://github.com/aws/aws-sdk-go-v2/pull/1050 and is now included in the SDK's latest release, v1.0.0.

let us know if you run into other issues.
