### ISSUE TITLE
Developer Guide (Website security issue)

### ISSUE THREAD

**Issue by lpmi-13** [aws/aws-sdk-go-v2#1060]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
N/A

### Version of Go (`go version`)?
N/A

### What issue did you see?

vulnerable version of bootstrap used in the website. Please upgrade the version used.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5070516/105152190-c4825180-5afe-11eb-89d9-b968271881e3.png)

**Comment by skmcgrail** [comment]
Thank you for bringing this to our attention @lpmi-13, this issue has now been addressed.
