### ISSUE TITLE
Unable to identify the error type when calling cloudformation.DescribeStacks

### ISSUE THREAD

**Issue by jchanam** [aws/aws-sdk-go-v2#1061]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When calling with the cloudformation client to `DescribeStacks` with a `StackName` that does not exist, an error is returned.
I'm unable to properly identify the kind of error to check if the issue is that the stack does not exist or another issue has happened.
The documentation says that a "ValidationError" can be returned, but I can't find that kind of error inside the code.

**Version of AWS SDK for Go?**
v0.29.0

**Version of Go (`go version`)?**
go1.15.3

**To Reproduce (observed behavior)**
Example from my code:
```
func (c client) stackExists(name string) (bool, error) {
	desc, err := c.cloudformationClient.DescribeStacks(c.ctx, &cloudformation.DescribeStacksInput{
		StackName: aws.String(name),
	})
	if err != nil {
		var re *awshttp.ResponseError
		if errors.As(err, &re) {
			c.printer.Error(fmt.Sprintf("requestID: %s, error: %v", re.ServiceRequestID(), re.Unwrap()))
		}
		var ae smithy.APIError
		if errors.As(err, &ae) {
			c.printer.Error(fmt.Sprintf("code: %s, message: %s, fault: %s", ae.ErrorCode(), ae.ErrorMessage(), ae.ErrorFault().String()))
		}
		var oe *smithy.OperationError
		if errors.As(err, &oe) {
			c.printer.Error(fmt.Sprintf("failed to call service: %s, operation: %s, error: %v", oe.Service(), oe.Operation(), oe.Unwrap()))
		}
		return false, NewErrConnection(fmt.Sprintf("error when checking if stack '%s' exists", name), err.Error())
	}
	if len(desc.Stacks) == 0 {
		return false, nil
	}
	return true, nil
}
```
I print this:
```
ERROR: requestID: 002aae37-8595-4224-9be7-67e6d43154f4, error: api error ValidationError: Stack with id stack-non-existent-test does not exist
ERROR: error building stack: [IACConnectionFailure] error when checking if stack 'stack-non-existent-test' exists: operation error CloudFormation: DescribeStacks, https response error StatusCode: 400, RequestID: 002aae37-8595-4224-9be7-67e6d43154f4, api error ValidationError: Stack with id stack-non-existent-test does not exist
```
**Expected behavior**
To have a proper error if the stack does not exist.

**Additional context**

**Comment by jasdel** [comment]
Thanks for reaching out @jchanam. It looks like the reason you're not seeing a specific error kind returned, is because the API does not model the error types for this operation. This means that all errors that are received by the SDK are going to be of the type `smithy.APIError`. This means that in order to write code to test against a specific error code you'll need to call the `Code` method of the `smithy.APIError` type.

```go
desc, err := c.cloudformationClient.DescribeStacks(c.ctx, &cloudformation.DescribeStacksInput{
	StackName: aws.String(name),
})
if err != nil {
    var apiErr smtihy.APIError
    if errors.As(err, &apiErr) {
         switch apiErr.Code() {
         case "ValidationError":
              return false, fmt.Errorf("failed because of validation, %w", err)
         }
    }
    return false, err
}
```

The AWS Cloud Formation team owns the models that the SDK uses to create the API clients. I'll upstream this request to them, as well.
