### ISSUE TITLE
cloudsearchdomain: not clear how to customize domain-specific endpoints

### ISSUE THREAD

**Issue by artyom** [aws/aws-sdk-go-v2#1062]
Confirm by changing [ ] to [x] below:

- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

[cloudsearchdomain package documentation](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudsearchdomain@v1.0.0#section-documentation) states:

> The endpoints for submitting UploadDocuments, Search, and Suggest requests are domain-specific and require the --endpoint-url option. To get the endpoints for your domain, use the Amazon CloudSearch configuration service DescribeDomains action. [...] You submit suggest requests to the search endpoint.

There are no examples in this package, and it is not clear from API documentation on how one can configure this endpoint.

Documentation mentions `--endpoint-url` option, which I suspect only applies to aws cli and is not relevant to this SDK.

**Comment by jasdel** [comment]
Thanks for reaching out @artyom. Looks like that documentation is centered around the `AWS CLI`'s configuration options. The SDK's [Configuring Client Endpoints](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/) guide has details how you can configure the client for a specific endpoint, using the module's [EndpointResolverFromURL](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudsearchdomain#EndpointResolverFromURL)

```go
cfg, err := config.LoadDefaultConfig(context.TODO())
if err != nil {
	log.Fatalf("unable to load config, %v", err)
}


client := cloudsearchdomain.NewFromConfig(cfg, 
    cloudsearchdomain.WithEndpointResolver(cloudsearchdomain.EndpointResolverFromURL(
         "https://customEndpoint",
    )),
)
```

**Comment by artyom** [comment]
Thank you!

Before package got its `EndpointResolverFromURL` function (github.com/aws/aws-sdk-go-v2/service/cloudsearchdomain@v1.0.0), I used the following helper function:

```go
// optFuncUseEndpoint is a helper function that returns a closure that modifies
// cloudsearchdomain.Client calls to use domain-specific endpoint.
func optFuncUseEndpoint(url string) func(*cloudsearchdomain.Options) {
	return func(o *cloudsearchdomain.Options) {
		fn := func(region string, opts cloudsearchdomain.EndpointResolverOptions) (aws.Endpoint, error) {
			return aws.Endpoint{URL: url, SigningRegion: region}, nil
		}
		o.EndpointResolver = cloudsearchdomain.EndpointResolverFunc(fn)
	}
}
```

which was then used by the client like this:

```go
res, err := client.Search(ctx, &cloudsearchdomain.SearchInput{...}, optFuncUseEndpoint(searchURL))

...

_, err := client.UploadDocuments(ctx, &cloudsearchdomain.UploadDocumentsInput{...}, optFuncUseEndpoint(indexURL))
```


With the recent introduction of `EndpointResolverFromURL` my helper function can be changed to:

```go
func optFuncUseEndpoint(url string) func(*cloudsearchdomain.Options) {
	return func(o *cloudsearchdomain.Options) {
		o.EndpointResolver = cloudsearchdomain.EndpointResolverFromURL(url)
	}
}
```

**Comment by jasdel** [comment]
Looks like this is on the right path. Let us know if you run into additional issues, or have feedback.
