### ISSUE TITLE
Code generated ... DO NOT EDIT leaking into package documentation

### ISSUE THREAD

**Issue by artyom** [aws/aws-sdk-go-v2#1065]
Confirm by changing [ ] to [x] below to ensure that it's a bug:

- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

Some `Code generated by ... DO NOT EDIT.` comments leak into documentation because of the lack of newlines between comment and package name declaration.

**Version of AWS SDK for Go?**

v1.0.0

**Version of Go (`go version`)?**

N/A

**To Reproduce (observed behavior)**

Go to <https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v1.0.0/aws>, see documentation.

Notice the following lines:

```
Code generated by aws/generate.go DO NOT EDIT.

Code generated by aws/logging_generate.go DO NOT EDIT.

Code generated by aws/generate.go DO NOT EDIT.
```

**Expected behavior**

`Code generated by ... DO NOT EDIT.` lines do not leak into documentation.

**Additional context**

One example: <https://github.com/aws/aws-sdk-go-v2/blob/0d3a3475168d8ca33961eccfc6230c0f0fe381b2/aws/from_ptr.go#L1-L2>

Because the comment is immediately followed by package declaration, comment is treated as part of the package documentation. There should be a blank line between  `// Code generated ...` comment and package declaraction.

**Comment by skotambkar** [comment]
Thanks for reporting. We have merged the fix.
