### ISSUE TITLE
DisableSSL v1 -> v2

### ISSUE THREAD

**Issue by milosgajdos** [aws/aws-sdk-go-v2#1067]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

V1 SDK used to have an option to disable SSL. It seems this has been removed in V2 rather than replaced, unless I'm missing something? I went through [config docs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config) and few other modules but couldn't find anything that disables TLS/SSL

**Comment by jasdel** [comment]
Thanks for reaching out @milosgajdos. The best way to disable TLS in the v2 SDK is in the API client's EndpointResolver configuration, [WithEndpointResolver](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#WithEndpointResolver), and defining a custom endpoint resolver to disable HTTPs.

```go
        // Get the default endpoint resolver to be used.
	defaultEndpointResolver := s3.NewDefaultEndpointResolver()

        // Create an endpoint resolver that will specify disable HTTPS, and delegate to default resolver.
	disableSSLEndpointResolver := s3.EndpointResolverFunc(
		func(region string, opts s3.EndpointResolverOptions) (aws.Endpoint, error) {
			opts.DisableHTTPS = true
			return defaultEndpointResolver.ResolveEndpoint(region, opts)
		})

        // Configure the client with the custom endpoint resolver.
	client := s3.NewFromConfig(cfg,
		s3.WithEndpointResolver(disableSSLEndpointResolver),
	)
```

**Comment by kisscelia** [comment]
I found the switcher to disable https, it may be useful.
```
client = s3.NewFromConfig(
		cfg, func(o *s3.Options) {
			o.UsePathStyle = true
			o.EndpointOptions.DisableHTTPS = true    // <---- here
 		},
	)
```

**Comment by kisscelia** [comment]
> Thanks for reaching out @milosgajdos. The best way to disable TLS in the v2 SDK is in the API client's EndpointResolver configuration, [WithEndpointResolver](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#WithEndpointResolver), and defining a custom endpoint resolver to disable HTTPs.
> 
> ```go
>         // Get the default endpoint resolver to be used.
> 	defaultEndpointResolver := s3.NewDefaultEndpointResolver()
> 
>         // Create an endpoint resolver that will specify disable HTTPS, and delegate to default resolver.
> 	disableSSLEndpointResolver := s3.EndpointResolverFunc(
> 		func(region string, opts s3.EndpointResolverOptions) (aws.Endpoint, error) {
> 			opts.DisableHTTPS = true
> 			return defaultEndpointResolver.ResolveEndpoint(region, opts)
> 		})
> 
>         // Configure the client with the custom endpoint resolver.
> 	client := s3.NewFromConfig(cfg,
> 		s3.WithEndpointResolver(disableSSLEndpointResolver),
> 	)
> ```

Hi, I got an error, when i sent a request to our local storage.
And the error is :  **x509: certificate signed by unknown authority.**

and code like this:

```
cfg, err = config.LoadDefaultConfig(
	context.TODO(),
	config.WithSharedConfigProfile("foo"),
)
//1. Get the default endpoint resolver to be used.
//defaultEndpointResolver := s3.NewDefaultEndpointResolver() ---- i changed it. next line.
**defaultEndpointResolver := s3.EndpointResolverFromURL("https://172.xx.xx.194:9xxx")**  <--- i used EndpointResolverFromURL
//2. Create an endpoint resolver that will specify disable HTTPS, and delegate to default resolver.
disableSSLEndpointResolver := s3.EndpointResolverFunc(
	func(region string, opts s3.EndpointResolverOptions) (aws.Endpoint, error) {
		opts.DisableHTTPS = true
		return defaultEndpointResolver.ResolveEndpoint(region, opts)
	})

client :=  s3.NewFromConfig(
	cfg,
	s3.WithEndpointResolver(disableSSLEndpointResolver),
)
client.ListBuckets(.....)
```
Can you help me? 
Thank you very much.

**Comment by kisscelia** [comment]
> > Thanks for reaching out @milosgajdos. The best way to disable TLS in the v2 SDK is in the API client's EndpointResolver configuration, [WithEndpointResolver](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#WithEndpointResolver), and defining a custom endpoint resolver to disable HTTPs.
> > ```go
> >         // Get the default endpoint resolver to be used.
> > 	defaultEndpointResolver := s3.NewDefaultEndpointResolver()
> > 
> >         // Create an endpoint resolver that will specify disable HTTPS, and delegate to default resolver.
> > 	disableSSLEndpointResolver := s3.EndpointResolverFunc(
> > 		func(region string, opts s3.EndpointResolverOptions) (aws.Endpoint, error) {
> > 			opts.DisableHTTPS = true
> > 			return defaultEndpointResolver.ResolveEndpoint(region, opts)
> > 		})
> > 
> >         // Configure the client with the custom endpoint resolver.
> > 	client := s3.NewFromConfig(cfg,
> > 		s3.WithEndpointResolver(disableSSLEndpointResolver),
> > 	)
> > ```
> 
> Hi, I got an error, when i sent a request to our local storage.
> And the error is : **x509: certificate signed by unknown authority.**
> 
> and code like this:
> 
> ```
> cfg, err = config.LoadDefaultConfig(
> 	context.TODO(),
> 	config.WithSharedConfigProfile("foo"),
> )
> //1. Get the default endpoint resolver to be used.
> //defaultEndpointResolver := s3.NewDefaultEndpointResolver() ---- i changed it. next line.
> defaultEndpointResolver := s3.EndpointResolverFromURL("https://172.xx.xx.194:9xxx")  <--- i used EndpointResolverFromURL
> //2. Create an endpoint resolver that will specify disable HTTPS, and delegate to default resolver.
> disableSSLEndpointResolver := s3.EndpointResolverFunc(
> 	func(region string, opts s3.EndpointResolverOptions) (aws.Endpoint, error) {
> 		opts.DisableHTTPS = true
> 		return defaultEndpointResolver.ResolveEndpoint(region, opts)
> 	})
> 
> client :=  s3.NewFromConfig(
> 	cfg,
> 	s3.WithEndpointResolver(disableSSLEndpointResolver),
> )
> client.ListBuckets(.....)
> ```
> 
> @jasdel Can you help me?
> Thank you very much.

I add HTTPClient config, it's useful.

```
cfg, err = config.LoadDefaultConfig(
	context.TODO(),
	config.WithSharedConfigProfile(co.Profile),
	config.WithHTTPClient(&http.Client{Transport: &http.Transport{  // <---- here
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}}),
	config.WithEndpointResolver(
		aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
			return aws.Endpoint{URL: co.Endpoint}, nil
		})),
```

**Comment by quynguyenxuan** [comment]
I'm use this 
`s3Client := s3.NewFromConfig(cfg, func (o *s3.Options) {
        o.BaseEndpoint = aws.String(endpoint)
		o.UsePathStyle = true
		o.EndpointOptions.DisableHTTPS = !useSSL
    })`
