### ISSUE TITLE
Add PresignHeadObject to S3 PresignClient

### ISSUE THREAD

**Issue by milosgajdos** [aws/aws-sdk-go-v2#1076]
**Is your feature request related to a problem? Please describe.**
We'd like to have the possibility to generate resigned URLs for S3 `HEAD` requsets. This is already provided by v2 SDK for `GET` and `PUT` requests, but `HEAD` support is missing.

**Describe the solution you'd like**
The solution should be simple: autogenerate `PresignHeadObject` for `HEAD` requests the same way it's done for the `GET` and `PUT`

**Describe alternatives you've considered**
None. I feel this should be pretty straightforward and I've personally tried, but first I didn't notice this code is autogenerated and on the second attempt I gave up after an hour fighting getting `java` runtime and `gradle` working on my laptop.

**Comment by shvc** [comment]
+ DeleteObject
and other Bucket Operations

**Comment by jasdel** [comment]
Looks like the SDK has added support for [PresignedHeadObject](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#PresignClient.PresignHeadObject)

We'll take a look at adding `DeleteObject` presign support.
