### ISSUE TITLE
Inconsistent output from GetBucketVersioning ( empty string instead of const )

### ISSUE THREAD

**Issue by bwoznicki** [aws/aws-sdk-go-v2#1077]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Inconsistent output from GetBucketVersioning

**Version of AWS SDK for Go?**
1.0.0

**Version of Go (`go version`)?**
1.15.1

**To Reproduce (observed behavior)**
```GO
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {

	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("eu-west-2"))
	if err != nil {
		log.Fatalln(err)
	}

	client := s3.NewFromConfig(cfg)

	input := &s3.ListBucketsInput{}

	out, err := client.ListBuckets(context.TODO(), input)
	if err != nil {
		log.Println(err)
	}

	for _, b := range out.Buckets {

		fmt.Println("Versioning for bucket:", *b.Name)

		li := &s3.GetBucketLocationInput{
			Bucket: b.Name,
		}

		r, err := client.GetBucketLocation(context.TODO(), li)
		if err != nil {
			log.Fatalln(err)
		}
		region := string(r.LocationConstraint)
		if region == "" {
			region = "us-east-1"
		}

		fmt.Println("Bucket region:", region)

		// bucket versioning
		cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion(region))
		if err != nil {
			log.Fatalln(err)
		}

		client := s3.NewFromConfig(cfg)

		vi := &s3.GetBucketVersioningInput{
			Bucket: b.Name,
		}

		v, err := client.GetBucketVersioning(context.TODO(), vi)
		if err != nil {
			continue
		}

		i, err := json.MarshalIndent(v, "", "  ")
		if err != nil {
			fmt.Println(err)
			continue
		}

		fmt.Println(string(i))

	}
}
```

**Expected behavior**
MFADelete / Status fields of GetBucketVersioningOutput type should return "Enabled" / "Disabled" / "Suspended" but sometimes they return empty string, while in the aws console they are always set to either "Enabled" / "Disabled" etc.

Not sure if this is a bug or expected behaviour, if its expected then empty string is an indication of which state ?

**Comment by bwoznicki** [comment]
Looking at the documentation for "GetBucketAccelerateConfiguration" it states:
"A GET accelerate request does not return a state value for a bucket that has no transfer acceleration state. A bucket has no Transfer Acceleration state if a state has never been set on the bucket."

Does the same apply for Versioning ? Should that be updated in documentation.

**Comment by jasdel** [comment]
Thanks for reaching out @bwoznicki. Could you capture a wire log of the issue that you're seeing. Seeing the HTTP response message as it comes back would help investigate this issue.

Also on a side note, your application probably does not need to call `LoadDefaultConfig` for each bucket region. Instead you can configure the individual operation calls for the region they should be made to. This will remove the need to call LoadDefaultConfig, and creating a new client for each region.

```go
v, err := client.GetBucketVersioning(context.TODO(), vi,
    func(o *s3.Options) { // Add functional option, for per operation configuration.
         o.Region = region // Specify region for bucket.

         o.ClientLogMode = aws.LogResponseWithBody, // Log response HTTP message.
    },
)
```

**Comment by bwoznicki** [comment]
Hi @jasdel this is what I get from Versioning, sometimes both MFADelete and Status return empty but mostly MFADelete comes back empty.
```
SDK 2021/03/04 20:56:30 DEBUG Response
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Thu, 04 Mar 2021 20:56:31 GMT
Server: AmazonS3
X-Amz-Id-2: gzAe2xF60mQm+FdkSFMO3mO+bwMtZ9lr7+xmYVO1oTclfi+anzLMZ2fJaKUhvXjFu31lbgwByoM=
X-Amz-Request-Id: 33C1647C2AFE5D6B

71
<?xml version="1.0" encoding="UTF-8"?>
<VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
0

(types.MFADeleteStatus) ""
(types.BucketVersioningStatus) ""
```
this is brand new bucket created via console, versioning or mfa has never been set explicitly basically bucket created with all default values.

**Comment by jasdel** [comment]
Thanks for the update @bwoznicki This looks to be an issue with the S3 API response it self. It looks like these fields are only included in the response if MFADelete has been configured for the bucket. 

* https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketVersioning.html#API_GetBucketVersioning_ResponseSyntax

> MFADelete - Specifies whether MFA delete is enabled in the bucket versioning configuration. This element is only returned if the bucket has been configured with MFA delete. If the bucket has never been so configured, this element is not returned.

While not documented this way, it looks like `BucketVersioningStatus` (aka `Status` in API doc) is the same way. Where if never configured, it will not be included in response.

**Comment by bwoznicki** [comment]
Hi, yes that's what I thought but its not mentioned in the doc's perhaps should be updated just like the wording in "GetBucketAccelerateConfiguration" where its clear that if not explicitly set it will not be returned. Thank you for looking into it.
