### ISSUE TITLE
Failed running smithy-generate codegen

### ISSUE THREAD

**Issue by milosgajdos** [aws/aws-sdk-go-v2#1079]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When trying to run `codegen` I get the following error:
```console
$ make smithy-generate
cd codegen && ./gradlew clean build -Plog-tests && ./gradlew clean
/Users/milosgajdos/go/src/github.com/aws/aws-sdk-go-v2/codegen

> Configure project :protocol-test-codegen
(scanned and found a Smithy CLI version 1.5.1. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Configure project :sdk-codegen
(scanned and found a Smithy CLI version 1.5.1. You will need to add an explicit dependency on smithy-model if publishing a JAR)

> Task :smithy-aws-go-codegen:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smithy-aws-go-codegen:compileJava'.
> Could not resolve all files for configuration ':smithy-aws-go-codegen:compileClasspath'.
   > Could not find software.amazon.smithy:smithy-go-codegen:0.1.0.
     Searched in the following locations:
       - file:/Users/milosgajdos/.m2/repository/software/amazon/smithy/smithy-go-codegen/0.1.0/smithy-go-codegen-0.1.0.pom
       - https://repo.maven.apache.org/maven2/software/amazon/smithy/smithy-go-codegen/0.1.0/smithy-go-codegen-0.1.0.pom
     Required by:
         project :smithy-aws-go-codegen

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
4 actionable tasks: 1 executed, 3 up-to-date
make: *** [smithy-generate] Error 1
```

**Version of AWS SDK for Go?**
v1.0.0

**Version of Go (`go version`)?**
```console
$ go version
go version go1.15.7 darwin/amd64
```

**To Reproduce (observed behavior)**
1. clone the repo
2. cd into repo dir
3.  `make smithy-generate`

**Expected behavior**
Go code generation succeeds without any problems

**Additional context**
I suspect the reason for this is because AWS haven't published the Go codegen jar in [maven repo](https://mvnrepository.com/artifact/software.amazon.smithy)?

I can see in the [travis instructions](https://github.com/aws/aws-sdk-go-v2/blob/main/.travis.yml#L55-L58) that [smithy-go](https://github.com/aws/smithy-go) is explicitly cloned and then the built jar is published to local maven repo?

I'm only speculating here as I'm not a `java` developer and there are no instructions about how to get started on this so I'm having to do a bit of digging.

**Comment by jasdel** [comment]
Thanks for reaching out @milosgajdos. You're probably missing the `smithy-go` repo locally. It is not published to  the public maven repo, and needs to be built locally and imported into your local maven.

```bash
git clone github.com/aws/smithy-go
cd smithy-go
make smithy-publish-local
```

Then you'll be able to run `make smithy-generate`. Though I suggest using `make generate` as it will run the SDK's full generation process.
