### ISSUE TITLE
SQS Receive Message overwrites all messages with the last message of the response when more than one message is received in a request

### ISSUE THREAD

**Issue by qhenkart** [aws/aws-sdk-go-v2#1091]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x ] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [ x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [ x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I have been in the process of migrating an sqs library to the aws sdk 2. The library is an internal version of https://github.com/qhenkart/gosqs.

The library was easy to migrate, well done on that. However, I noticed a major bug that will keep me from being able to apply the migration. It took me some time to narrow it down, but applying a MaxMessages value seems to ignore visibility timeouts

**Version of AWS SDK for Go?**
Example: v1.0

**Version of Go (`go version`)?**
1.15

**To Reproduce (observed behavior)**

I interact with the API like this
```
output, err := c.sqs.ReceiveMessage(context.Background(), &sqs.ReceiveMessageInput{
			QueueUrl:              &c.QueueURL,
			MessageAttributeNames: []string{all},
			MaxMessages: int32(10),
		})
```
Messages received are all over the place, sometimes duplicates, sometimes triplicates. My assumption is that if I do not delete the message fast enough, it comes in the bulk request. I tried adding the visibility timeout directly to the request (the queue itself has the visibility timeout set to 30)

```
output, err := c.sqs.ReceiveMessage(context.Background(), &sqs.ReceiveMessageInput{
			QueueUrl:              &c.QueueURL,
			MessageAttributeNames: []string{all},
			MaxMessages: int32(10),
                       VisibilityTimeout: int32(30),
		})
```

I was sure that would fix the problem but it had no affect. Finally I removed MaxMessages so I have 
```
output, err := c.sqs.ReceiveMessage(context.Background(), &sqs.ReceiveMessageInput{
			QueueUrl:              &c.QueueURL,
			MessageAttributeNames: []string{all},
			VisibilityTimeout: int32(30),
		})
```
This works as expected. I get one receipt per message. However it has no slowed down my library by a large amount as well as would increase the running costs by 10x

Because this library has been in production for some time with sdk v1, I was able to set up a side by side comparison. V1 simply has 
```
output, err := c.sqs.ReceiveMessage(&sqs.ReceiveMessageInput{
			QueueUrl:              &c.QueueURL,
			MessageAttributeNames: []*string{&all},
			MaxMessages: int64(10),
                  
		})
```

and it gets one receipt per message with the exact same queue, message and set up

This is perplexing to me because like I said, our visibility timeout is set on the queue dashboard, I wasn't aware that could be affected by the nature of the API call. I will dig deeper into the way the sdk is making the API call tomorrow and see if I can figure out what exactly is going on. But I wanted to let you guys know and also make an issue to let others know to look out for this. 

**Expected behavior**
While understanding that a non FIFO queue will sometimes give duplicate messages, I expect the performance of receipts per message to be similiar to that of v1 and that the visibility timeout to be respected even when receiving 10 messages per request

**Additional context**

**Comment by qhenkart** [comment]
upon further investigation, I have found that if I also include the WaitTimeSeconds field, it seems to perform better despite the queue already having this setting. I thought that the new sdk might be setting the field to some default if it is not explicitly set upon each request, but I checked the serializer and that is not the case.

Just to showcase the difference between including maxmessages and removing it. This is a screenshot of the route names of each event from a single, controlled action as part of my testing suite for this

With Max Messages removed. (the request with max messages on the v1 sdk is like this as well)
![image](https://user-images.githubusercontent.com/5798752/106305141-8d582280-6219-11eb-9501-8b0d61c9566a.png)

With Max Messages set to 10, notice triplicates for almost each message and one of the messages is even missing, it is missing because it's listed as a message in flight, it must have been received by the request but dropped before it got to the output.Messages, probably as a result of the duplicates/triplicates being generated by the library and maxing out the list. As a result, the queue stats show it as "in flight", but the message is never consumed. The missing message will come after the visibility timeout has expired (30 seconds in this case)
![image](https://user-images.githubusercontent.com/5798752/106305192-9e089880-6219-11eb-8a71-2b157acd3a90.png)

Like I said, explicitly including the WaitTimeSeconds field to 20(despite it being set to 20 on the dashboard) seems to make the triplicates/duplicates less consistent, but it still happens 50% of the time (vs 90% of the time without it). And the dropped messages getting stuck in "in flight" without ever being received and then coming in 30 seconds later still occurs.

**Comment by skotambkar** [comment]
Thanks for reaching out @qhenkart . To help us better understand the issue, you could provide us with the request and response logs. 

You can enable logging as follows:

```
c.sqs.ReceiveMessage(context.Background(), input, func(o *Options) {
		    o.ClientLogMode = aws.LogRequestWithBody | aws. LogResponseWithBody
})

```

**Comment by qhenkart** [comment]
@skotambkar **Very good! ** I wish I had seen that client log mode. It looks like we are getting to the bottom of the issue

nothing interesting in the request, but I am including it so you can verify my version and params etc, the response is where it is interesting
```}
SDK 2021/01/29 21:33:16 DEBUG Request
card-wrk_1            | [00] POST / HTTP/1.1
card-wrk_1            | [00] Host: sqs.us-west-2.amazonaws.com
card-wrk_1            | [00] User-Agent: aws-sdk-go-v2/1.0.0
card-wrk_1            | [00] Content-Length: 171
card-wrk_1            | [00] Amz-Sdk-Invocation-Id: **readacted**
card-wrk_1            | [00] Amz-Sdk-Request: attempt=1; max=10
card-wrk_1            | [00] Authorization: AWS4-HMAC-SHA256 Credential=**redacted**us-west-2/sqs/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-user-agent, Signature=**redacted**
card-wrk_1            | [00] Content-Type: application/x-www-form-urlencoded
card-wrk_1            | [00] X-Amz-Date: 20210129T213316Z
card-wrk_1            | [00] X-Amz-User-Agent: aws-sdk-go-v2/1.0.0 os/linux lang/go/1.15.7 md/GOOS/linux md/GOARCH/amd64
card-wrk_1            | [00] Accept-Encoding: gzip
card-wrk_1            | [00]
card-wrk_1            | [00] Action=ReceiveMessage&MaxNumberOfMessages=10&MessageAttributeName.1=All&QueueUrl=https%3A%2F%2Fsqs.us-west-2.amazonaws.com.**redacted**&Version=2012-11-05
```

```
SDK 2021/01/29 21:33:16 DEBUG Response
card-wrk_1            | [00] HTTP/1.1 200 OK
card-wrk_1            | [00] Content-Length: 2282
card-wrk_1            | [00] Content-Type: text/xml
card-wrk_1            | [00] Date: Fri, 29 Jan 2021 21:33:16 GMT
card-wrk_1            | [00] X-Amzn-Requestid: -
card-wrk_1            | [00]
card-wrk_1            | [00] <?xml version="1.0"?><ReceiveMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><ReceiveMessageResult><Message><MessageId>ae69fa46-4dea-4e17-849e-58574d132ecc</MessageId><ReceiptHandle>AQEBXfSzEtUohIRQWXSfT2S4DUNcMHeJpHgBE7OakPt+lDbjGBX5KI1gSBVfDgvyUdxDMvVF93ynI/j/QglBUMRJi67z14U7StjOJqMo5EiN1nsZ/Pxw0FEZmtS1MUrNqPzni7r5Q4IJbTXEtCazQIh4c2CDHAqz4i6/E8JeNc18ttsiW6SDhGE5L/J4RIkoakuvwljU8t1gmE1CWrEof71QRdQTJGKDS91hGhmndESlIOn4puPFIry2smDc42EbX9tHW7Sb8ZsbCQzMOxpWe/6DQ9DzbVYg8KPRZExxwIne3WZZix7nkbxn4HWVpAMFaueS46UGJT1+G2B/1R4LC9xIRoUidkGSVebVgrYPaC9vAhddT7PrkJQk8XBp0ZJ0UwhWPAhHWDAW0aYP4q9oUGwNAQ==</ReceiptHandle><MD5OfBody>828bcef8763c1bc616e25a06be4b90ff</MD5OfBody><MD5OfMessageAttributes>884bea55543a0a320be9174bd073a38f</MD5OfMessageAttributes><Body>{&quot;test&quot;:&quot;test&quot;}</Body><MessageAttribute><Name>correlationId</Name><Value><StringValue>1aeaa6e9-bddd-473e-9c3c-da0bc025d222</StringValue><DataType>String</DataType></Value></MessageAttribute><MessageAttribute><Name>route</Name><Value><StringValue>card_created</StringValue><DataType>String</DataType></Value></MessageAttribute></Message><Message><MessageId>af38f657-c88d-4cab-8253-211217ff3b0a</MessageId><ReceiptHandle>AQEBASjp4DNxHHfqFefcEGnJYhh3+JaAFScnj2B05b+xbXBUyWDA/uQSiWRXDno3gSnUjq8CXEgLVgvJmeQj75U4rhQ7NysEcperSN49CjrO/XoYPobfI9w2spi1VjwZWbU1uBtQMK7L7c3zJaOFYUaNUp/k+brGonzx8IvQYJ2eJbtN0lbGfLN5Wrph8T0H4SOCb8CEUUd0k7puoEBIRrgSWQkESDEKn18qqXPkuAkFU33oHcqwowxUzsbxjWRIkhar0+s8zmWAEIP88gabeEewK3QXsQvvWPXbSka/1kZ64/KtLxxTRq5BWqOSTsjsqaAIbQpZe42KYL3+XaZSRGYaIqvlzV73XtctJBxFWcI9K+mmLvJaMbf3SOjIGWfWDX/pNpuIL1oFzS+8spQHX0a7TA==</ReceiptHandle><MD5OfBody>828bcef8763c1bc616e25a06be4b90ff</MD5OfBody><MD5OfMessageAttributes>1041183602904b893bf9f62d66368adb</MD5OfMessageAttributes><Body>{&quot;test&quot;:&quot;test&quot;}</Body><MessageAttribute><Name>correlationId</Name><Value><StringValue>1aeaa6e9-bddd-473e-9c3c-da0bc025d222</StringValue><DataType>String</DataType></Value></MessageAttribute><MessageAttribute><Name>route</Name><Value><StringValue>member_created</StringValue><DataType>String</DataType></Value></MessageAttribute></Message></ReceiveMessageResult><ResponseMetadata><RequestId>35d48ae4-73ca-54a8-a611-d26af29d0ab7</RequestId></ResponseMetadata></ReceiveMessageResponse>

 | [00] member_created
 | [00] member_created

```

The above request included 2 messages. I attach a route field to the messageattributes and this is how I can identify the message. You can see the first message, the route is card_created. The second message is member_created. However when I check the routes of each message immediately from the response here https://github.com/qhenkart/gosqs/blob/master/consumer.go#L159, they both show up as member_created. This also explains why the messages are showing up as "in-flight" even though they are never received.

The aws-sdk IS receiving all of the messages as normal, however it is mixing up the attributes and meta data. This is also why it worked as expected without Max Messages, because if it only pulls a single message per request, there is nothing to confuse the attributes with

Upon further testing, the last message replaces all of the information of the previous messages. Including the body, receipt handle and route. I looked through the way the sdk deserializes the messages and everything looked good there so it must be in a level higher in the middleware

**Comment by qhenkart** [comment]
Oh I am very embarrassed to say that this was due to an application error and not the sdk. Because the messages are no longer pointers, my loop was changing the value of the variable after I passed it to the worker replacing all of the messages with the last message like I mentioned. So sorry
