### ISSUE TITLE
S3 Hostname incorrect when using single case string as bucket name

### ISSUE THREAD

**Issue by townsymush** [aws/aws-sdk-go-v2#1092]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When creating a bucket with a single case name, the client host is changed.

**Version of AWS SDK for Go?**
 v1.37.0

**Version of Go (`go version`)?**
v1.15.6
**To Reproduce (observed behavior)**
```
func main() {
        customResolver := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
		if service == s3.ServiceID {
			return aws.Endpoint{
				PartitionID:   "aws",
				URL:           "http://localhost:4566",
				SigningRegion: "eu-west-1",
			}, nil
		}
		// returning EndpointNotFoundError will allow the service to fallback to it's default resolution
		return aws.Endpoint{}, &aws.EndpointNotFoundError{}
	})

	config, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("eu-west-1"), config.WithEndpointResolver(customResolver))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := s3.NewFromConfig(config)

	bucketName := "dave"
	input := s3.CreateBucketInput{
		Bucket: &bucketName,
	}
	r, err := client.CreateBucket(ctx, &input)

	fmt.Println(r)
	if err != nil {
		panic(err)
	}
}
```

Unexpected error
`request send failed, Put "http://dave.localhost:4566/"`

**Expected behavior**
I expect the bucket to be created at the endpoint `http://localhost:4566/s3/dave`

**Additional context**
If bucket name is "daveBucket" it works as expected

**Comment by townsymush** [comment]
So after digging, this happens in `moveBucketNameToHost(req.URL, bucket)` 
https://github.com/aws/aws-sdk-go-v2/blob/main/service/s3/internal/customizations/update_endpoint.go#L225

I believe this is being done for backwards compatibility with the host name urls?

The way around this is to set `HostnameImmutable: true,` when returning the endpoint from a custom resolver
```
customResolver := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
	if service == s3.ServiceID {
		return aws.Endpoint{
			PartitionID:   "aws",
			URL:           "http://localhost:4566",
			SigningRegion: "eu-west-1",
			HostnameImmutable: true, // stops hostname being modified
		}, nil
	}
	// returning EndpointNotFoundError will allow the service to fallback to it's default resolution
	return aws.Endpoint{}, &aws.EndpointNotFoundError{}
})

```

**Comment by skotambkar** [comment]
Thanks for reaching out. 

By default, S3 uses [virtual host path style](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html) to address buckets. This is the reason the host-name is mutated to be `dave.localhost:4566`. 

S3 has few [requirements for a valid bucket name](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html).  Accordingly, `daveBucket ` is an invalid bucket name as per the requirements, and thus SDK falls back to path-style urls. Thus host-name is not mutated and you see `localhost:4566/daveBucket`.


Coming to your workaround, If `HostnameImmutable` property is set to true, the SDK API clients will not modify the hostname of the URL. This may cause the API client not to function correctly if the API requires the operation specific hostname values to be used by the client.

A better solution in your case would be to enable `UsePathStyle` option on S3 options directly

```
result, err :=  client.CreateBucket(ctx, &input, func(o *s3.Options) {
		o.UsePathStyle = true
	})
 ```
 
 Let us know if you have any other questions or concerns.

**Comment by townsymush** [comment]
Thanks for the reply. That makes sense and thanks for the clarity
