### ISSUE TITLE
Missing x-amz-upload-availability in mediastoredata

### ISSUE THREAD

**Issue by fsouza** [aws/aws-sdk-go-v2#1094]
**Is your feature request related to a problem? Please describe.**

I'd like to leverage MediaStore's support for lower latency streaming, and that requires sertting UploadAvailability. It's [available in aws-sdk-go](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.37.1/service/mediastoredata#PutObjectInput), but not in aws-sdk-go-v2 (or perhaps I'm looking at the wrong place? heh)

**Describe the solution you'd like**

I'd like to be able to define the value of the header `x-amz-upload-availability` when uploading objects to  mediastore.

**Describe alternatives you've considered**

Migrating back to aws-sdk-go? 🙈

**Comment by fsouza** [comment]
I imagine we need something similar to how StorageClass is [defined here](https://github.com/aws/aws-sdk-go-v2/blob/af489c33fe60dd0b21b8ab9ffc700b9204dd4bab/codegen/sdk-codegen/aws-models/mediastoredata.2017-09-01.json#L690-L704) and [used here](https://github.com/aws/aws-sdk-go-v2/blob/af489c33fe60dd0b21b8ab9ffc700b9204dd4bab/codegen/sdk-codegen/aws-models/mediastoredata.2017-09-01.json#L629-L635) (and in the response too). The contributing guide discourages changes in that file, so I can't help (unless yall are hiring 😬)

**Comment by jasdel** [comment]
Thanks for reaching out @fsouza. The v2 SDK's supported APIs are trailing those of the other AWS SDKs. We're working to resolve this and get the SDK supported APIs up to date. We can use this GitHub issue to track the API update for AWS Elemental MediaStore Data Plane service.

**Comment by fsouza** [comment]
@jasdel no problem, definitely understand it. Let me know if there's anything I can do to help.

**Comment by jasdel** [comment]
This API model as been updated, and is now available in the latest version, [mediastoredata/types.UploadAvailability](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/mediastoredata/types#UploadAvailability).

```sh
go get -d github.com/aws/aws-sdk-go-v2/service/mediastoredata@v1.2.0
```
