### ISSUE TITLE
Docs: "Migrating to the AWS SDK for Go V2" contains bad import paths

### ISSUE THREAD

**Issue by stefansundin** [aws/aws-sdk-go-v2#1095]
### What issue did you see?

The documentation page [Migrating to the AWS SDK for Go V2](https://aws.github.io/aws-sdk-go-v2/docs/migrating/) has a lot of references to `github.coma` instead of `github.com`.

Example:

```go
import "github.coma/aws/aws-sdk-go-v2/aws"
import "github.coma/aws/aws-sdk-go-v2/credentials/processcreds"
```

Should be an easy fix.

**Comment by skotambkar** [comment]
Thanks for letting us know @stefansundin . We have merged a PR to fix the issue, and change will be deployed to reflect in public documentation soon.
