### ISSUE TITLE
Docs: "Getting Started with the AWS SDK for Go V2" shadows the config module with a variable of the same name

### ISSUE THREAD

**Issue by stefansundin** [aws/aws-sdk-go-v2#1096]
### What issue did you see?

The code sample on [Getting Started with the AWS SDK for Go V2](https://aws.github.io/aws-sdk-go-v2/docs/getting-started/#invoke-an-operation) shadows the `config` module name with a variable of the same name. I think this situation should generally be avoided, so it would be nice if the variable name could be changed.

I think the `config` variable should be named `cfg` instead. That is how it is named on other documentation pages ([like here](https://aws.github.io/aws-sdk-go-v2/docs/migrating/)). Renaming it would make code samples more consistent and easier to copy-paste multiple samples together.

```go
package main

import (
	"context"
	"log"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	// Load the Shared AWS Configuration (~/.aws/config)
	config, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Fatal(err)
	}

	// Create an Amazon S3 service client
	client := s3.NewFromConfig(config)

	// Get the first page of results for ListObjectsV2 for a bucket
	output, err := client.ListObjectsV2(context.TODO(), &s3.ListObjectsV2Input{
		Bucket: aws.String("my-bucket"),
	})
	if err != nil {
		log.Fatal(err)
	}

	log.Println("first page results:")
	for _, object := range output.Contents {
		log.Printf("key=%s size=%d", aws.ToString(object.Key), object.Size)
	}
}
```

**Comment by stefansundin** [comment]
A tiny bit related, [this blog post](https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/) has code snippets with "fancy" quotes that are very unhelpful when trying to copy-paste the code and actually run it.

```go
return fmt.Errorf(“failed to get a page, %w”, err)
```

results in:
```
./main.go:132:24: invalid character U+201C '“' in identifier
./main.go:132:34: syntax error: unexpected to, expecting comma or )
./main.go:132:51: invalid character U+201D '”' in identifier
```

Would be great if this could also be fixed.

**Comment by Doug-AWS** [comment]
I've created a PR. The next build should have the update.

**Comment by Doug-AWS** [comment]
I've filed a ticket against the blog post.

**Comment by skotambkar** [comment]
Thanks for reaching out. We have updated the blog post, and the code sample mentioned in this issue.
