### ISSUE TITLE
route53: ListResourceRecordSets paginator

### ISSUE THREAD

**Issue by flood4life** [aws/aws-sdk-go-v2#1097]
**Is your feature request related to a problem? Please describe.**
SDK v1 provides `ListResourceRecordSetsPagesWithContext` which is a convenient API to process all the records in a hosted zone. I'm currently upgrading to SDK v2 and would love to keep not having to worry about handling pagination.

**Describe the solution you'd like**
SDK provides a `NewListListResourceRecordSetsPaginator` (akin to other paginators, e.g. `NewListHostedZonesPaginator`)

**Describe alternatives you've considered**
Implementing that specific paginator in my application code.

**Additional context**
I feel like providing a new paginator should be quite straightforward if the existing paginators are used as reference. If you think that the proposed solution is the way to go, I could take a stab at contributing and implementing it.

**Comment by skyzyx** [comment]
Hah. I just went to file this exact same ticket. 👍🏻

**Comment by meshuga** [comment]
Lack of this paginator led to incorrect implementation and a bug https://github.com/GoogleCloudPlatform/terraformer/issues/874
