### ISSUE TITLE
Cost explorer 

### ISSUE THREAD

**Issue by jSherz** [aws/aws-sdk-go-v2#1101]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

The costexplorer package contains some enums that are handy for building up API requests, specifically the [Expression](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/costexplorer@v1.1.0/types#Expression) and [TagValues](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/costexplorer@v1.1.0/types#TagValues) types. The [MatchOption type](https://github.com/aws/aws-sdk-go-v2/blob/main/service/costexplorer/types/enums.go#L265) however does not contain an enum for "ABSENT", which is supported by [the API](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_TagValues.html).

**Version of AWS SDK for Go?**
1.1.0

**Version of Go (`go version`)?**
```
go version go1.15.7 darwin/amd64
```

**To Reproduce (observed behavior)**
N/A see above

**Expected behavior**
All API supported values to be present in the enums.

**Additional context**
N/A

**Comment by skotambkar** [comment]
Thanks for reaching out, and letting us know. We will take a look .

**Comment by jasdel** [comment]
The v2 SDK's supported APIs are trailing those of the other AWS SDKs. We're working to resolve this and get the SDK supported APIs up to date. We can use this GitHub issue to track the API update for AWS Cost Explorer.

**Comment by jasdel** [comment]
This API model as been updated, and is now available in the latest version, [costexplorer/types.MatchOption](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/costexplorer/types#MatchOption).

```sh
go get -d github.com/aws/aws-sdk-go-v2/service/costexplorer@v1.2.0
```
