### ISSUE TITLE
[service/acm] NewListCertificatesPaginator should perform nil check before params use

### ISSUE THREAD

**Issue by jylitalo** [aws/aws-sdk-go-v2#1104]
**Describe the bug**

**Version of AWS SDK for Go?**
v1.1.0

**Version of Go (`go version`)?**
1.15

**To Reproduce (observed behavior)**

If you use:
>	paginator := acm.NewListCertificatesPaginator(client.sdk, nil)

it will crash on https://github.com/aws/aws-sdk-go-v2/blob/e5e313fb7be626d2437e4e7cf14349be7eb045db/service/acm/api_op_ListCertificates.go#L160

**Expected behavior**

Work in similar fashion as:
>	paginator := acm.NewListCertificatesPaginator(client.sdk, &acm.ListCertificatesInput{})

**Additional context**
Possible fix in diff at https://github.com/jylitalo/aws-sdk-go-v2/commit/ff13de6238f1ad3f4b50864320c75575f762291d

**Comment by jasdel** [comment]
Thanks for reporting this issue @jylitalo. Yes the SDK's paginators should be updated to set the `params` to a default value if the provided value was nil.

**Comment by skmcgrail** [comment]
There is a similar PR attempting to address this: https://github.com/aws/aws-sdk-go-v2/pull/1160

We will need to make a code change to our generation framework to fix this. We can have this included in our next release.
