### ISSUE TITLE
service/ec2: ModifyNetworkInterfaceAttribute fails when Value: false but works when Value: true

### ISSUE THREAD

**Issue by tylux** [aws/aws-sdk-go-v2#1107]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

Using v1.1.0 of the sdk, I am unable to disable SourceDestCheck on ENIs with the following code

```
		input := &ec2.ModifyNetworkInterfaceAttributeInput{
			NetworkInterfaceId: aws.String(eni),
			SourceDestCheck: &types.AttributeBooleanValue{
				Value: false,
			},
		}

		_, err := client.ModifyNetworkInterfaceAttribute(context.Background(), input)
```

This returns...

`operation error EC2: ModifyNetworkInterfaceAttribute, https response error StatusCode: 400, RequestID: 947bd2b9-...-8e276816081c, api error InvalidParameterCombination: No attributes specified.`

However when I change Value to true (enable SourceDestCheck) the code works just fine and will enable SourceDestCheck if it isn't already enabled on the ENI

I feel like this is a bug but I could be wrong.

**Comment by tylux** [comment]
I also tried downgrading to 0.31.0 and got same result

**Comment by skotambkar** [comment]
Thanks for reaching out @tylux .  To help us better understand the issue, could you provide us with the request wire log?

You can enable logging as follows:
```
response, err := client. ModifyNetworkInterfaceAttribute(context.Background(), input, func(o *ec2.Options) {
		    o.ClientLogMode = aws.LogRequestWithBody
})
```

**Comment by tylux** [comment]
Here it is 

`
SDK 2021/02/04 14:42:08 DEBUG Request
POST / HTTP/1.1
Host: ec2.us-east-1.amazonaws.com
User-Agent: aws-sdk-go-v2/1.1.0
Content-Length: 98
Amz-Sdk-Invocation-Id: 3364613e-865c-4d6b-8b7a-9c634ca6e3f0
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-user-agent, Signature=<redacted>
Content-Type: application/x-www-form-urlencoded
X-Amz-Date: 20210204T144208Z
X-Amz-Security-Token: <redacted>
X-Amz-User-Agent: aws-sdk-go-v2/1.1.0 os/linux lang/go/1.15.7 md/GOOS/linux md/GOARCH/amd64
Accept-Encoding: gzip

Action=ModifyNetworkInterfaceAttribute&NetworkInterfaceId=eni-<redacted>&Version=2016-11-15
2021/02/04 14:42:08 Got an error
2021/02/04 14:42:08 operation error EC2: ModifyNetworkInterfaceAttribute, https response error StatusCode: 400, RequestID: 793b09da-302a-47dd-b293-df08c875ef57, api error InvalidParameterCombination: No attributes specified.`

**Comment by jasdel** [comment]
Thanks for reporting this issue. This is an issue with how the SDK is treating modeled modeled boolean members. I'm thinking this member should be decorated as `required` since the API is expecting the value to be present. But will reach out to the Amazon EC2 team for guidance on how this API model should be updated to handle this use case.
