### ISSUE TITLE
EC2 DescribeAvailabilityZones ignores AllAvailabilityZones

### ISSUE THREAD

**Issue by csandanov** [aws/aws-sdk-go-v2#1109]
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
EC2 client's method to list availability zones ignores `AllAvailabilityZones` param and always returns availability zone from the current opt-in region.

**Version of AWS SDK for Go?**
1.1.0

**Version of Go (`go version`)?**
1.15.7

**To Reproduce (observed behavior)**
```go
cfg := aws.NewConfig()
cfg.Credentials = credentials.NewStaticCredentialsProvider(accessKey, secretKey, "")
cfg.Region = "us-east-1"
client := ec2.NewFromConfig(cfg)
out, _ := client.DescribeAvailabilityZones(ctx, &ec2.DescribeAvailabilityZonesInput{AllAvailabilityZones: true})
// results contains AZ only for us-east-1
```

**Expected behavior**
Results should include AZs from all regions when `AllAvailabilityZones` param specified to `true`

**Additional context**
It actually doesn't work in CLI also, so I guess it's an API bug or something.

**Comment by KaibaLopez** [comment]
Hi @csandanov ,
I think you're a bit confused on the behavior of this function. If that's not the case and I misunderstood your report let me know though.

`DescribeAvailabilityZones` will only return the zones within the specified region, not all the zones for all the regions. Here's [more info](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-availability-zones) on how that is divided.
You may be looking for `DescribeRegions` which also should have the AllRegions parameter for opt-in regions.
Or a combination, but that would be on you to write, (connect on each of the available regions and check it's available zones).
Anyways hope this helps and again if I misunderstood something please let me know.

**Comment by csandanov** [comment]
Thanks for the feedback, I confused region opt-in with the current region in the config
