### ISSUE TITLE
What's the best way to handle not found error?

### ISSUE THREAD

**Issue by csandanov** [aws/aws-sdk-go-v2#1110]
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

I found the following example in [CHANGELOG](https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md#error-handling):
```go
// To get a specific API error
var notFoundErr *types.ResourceNotFoundException
if errors.As(err, &notFoundErr) {
    log.Printf("scan failed because the table was not found, %v", notFoundErr.ErrorMessage())
}
```

So I tried this with RDS:
```go
_, err := client.DescribeDBInstances(ctx, &rds.DescribeDBInstancesInput{
    DBInstanceIdentifier: aws.String(identifier),
})
if err != nil {
    var notFoundErr *types.DBInstanceNotFoundFault
    // Doesn't work.
    // I also tried using types.ResourceNotFoundFault.
    if errors.As(err, &notFoundErr) {
         // 
    }
}
```

This works:
```go
var apiErr smithy.APIError
if errors.As(err, &apiErr) {
     //
}
```

Does this work as intended? Should I get 404 from response status code if I want to identify not found error?

**Comment by csandanov** [comment]
I ended up using this:
```go
if opErr, ok := err.(*smithy.OperationError); ok {
	if httpErr, ok := opErr.Err.(*awsHttp.ResponseError); ok {
		if httpErr.HTTPStatusCode() == http.StatusNotFound {
			// 
		}
	}
}
```

**Comment by KaibaLopez** [comment]
Hi @csandanov sorry, I'm not clear on what it is you were asking for but it looks like you were able to find your answer or is there another question you've got?

**Comment by skotambkar** [comment]
Hi @csandanov, thanks for reaching out! 

From your provided sample code, I think the problem is use of `&apiErr`,  instead of `&notFoundErr` when using errors.As.

```
    var notFoundErr *types.DBInstanceNotFoundFault
    if errors.As(err, &notFoundErr) {
         // 
    }
 
 ```

Let us know if that solves the issue.

**Comment by csandanov** [comment]
@skotambkar I'm sorry that's just a typo in the example I wrote here, it doesn't work.

@KaibaLopez I was just looking for a simple way to handle not found errors, I saw example in the CHANGELOG and thought this was really neat but in the end it didn't work, I thought maybe there's another correct way to handle it since there's a `types.DBInstanceNotFoundFault`. Right now I check error for `smithy.OperationError`, fetch http error from operation error and check its code for 404, it works but it doesn't feel right

**Comment by jasdel** [comment]
Hi @csandanov could you provide log output of the error message your application receiving that you want to capture?  Also log the error value returned by the operation method.

```go
// Add logging for a operation to stdout
resp, err := client.client.DescribeDBInstances(ctx, &rds.DescribeDBInstancesInput{
    DBInstanceIdentifier: aws.String(identifier),
    func (o *dynamodb.Options) {
         o.ClientLogMode: aws.LogResponseBody
    }
})

// Log error in detail
log.Printf("DescribeDBInstances error, %#v", err)
```

**Comment by csandanov** [comment]
I got a similar issue with IAM, that's what the print gave me:
```
operation error IAM: GetRole, https response error StatusCode: 404,
```

**Comment by d122y** [comment]
First of all, a huge shout out to @csandanov for posting solution! I know it's a closed issue but because it's one of the top google results for how to handle errors in aws-sdk-go-v2, and I think @csandanov enquiry was very valid due to lack of official documentation (not counting [this](https://aws.github.io/aws-sdk-go-v2/docs/handling-errors/), as it's somewhat incomplete), this is what I came up with... If anyone has a better way to implement switch for actual error cause please let me know, as I'm not quite happy with complexity of this solution. 

```
if err != nil {
	if opErr, ok := err.(*smithy.OperationError); ok {
		if httpErr, ok := opErr.Err.(*awshttp.ResponseError); ok {
			switch httpErr.Err.(type) {
			case *types.ProvisionedThroughputExceededException:
			...
			case *types.RequestLimitExceeded:
			...
			}
		}
	}
}
```

**Comment by petitout** [comment]
Beware this code snippet won't work for S3 errors ...
you have to do something like to make sure it will work in any case:

```
if err != nil {
	if opErr, ok := err.(*smithy.OperationError); ok {
                var httpErr *awshttp.ResponseError
		if errors.As(err, &httpErr) {
			switch httpErr.Err.(type) {
			case *types.ProvisionedThroughputExceededException:
			...
			case *types.RequestLimitExceeded:
			...
			}
		}
	}
}
```

**Comment by jasdel** [comment]
Thanks for posting the example. Another way you could identify the underlying API error would be to use `errors.As` on [smithy-go.APIError](https://pkg.go.dev/github.com/aws/smithy-go#APIError) type. Since all API error types generated by the SDK will match this interface.

```go
if err != nil {
	var apiErr smithy.APIError
	if errors.As(err, &apiErr) {
		switch apiErr.(type) {
		case *types.ProvisionedThroughputExceededException:
		...
		case *types.RequestLimitExceeded:
		...
		}
	}
}
```

Generally the SDK will layer API response error for operation calls in the following pattern:
* smithy.OperationError - provides metadata about the operation call and client
* if s3 or s3control, a ResponseError type with a `ServiceHostID() string` method.
* awshttp.ResponseError - provides metadata about the HTTP response, adds `RequestID`
    * smithyhttp.ResponseError - embedded within `awshttp.ResponseError`
* type implementing `smithy.APIError` interface - concrete API response error values.

Each one of these layers can be searched for via the top level via the `errors.As`.

```go
var apiErr smithy.APIError
if errors.As(err, &apiErr) {
      fmt.Println("APIError:", apiErr.ErrorCode())
}

var httpResponseErr *awshttp.ResponseError
if errors.As(err, &httpResponseErr) {
     fmt.Println("HTTP Response error requestID:", httpResponseErr.ServiceRequestID())
     fmt.Println("HTTP Response error status code: ", httpResponseErr.HTTPStatusCode())
}
```

**Comment by esdandreu** [comment]
Just for the reference, in order to use @jasdel [example](https://github.com/aws/aws-sdk-go-v2/issues/1110#issuecomment-1054643716):
> ```golang
> var httpResponseErr *awshttp.ResponseError
> ```
Assumes 
```golang
import awshttp "github.com/aws/aws-sdk-go-v2/aws/transport/http"
```

**Comment by Schachte** [comment]
I'm curious why you regressed in terms of clarity from V1 SDK for error handling. 

- V1: Very clear response code delineation
- V2: Complex abstractions

**Comment by aajtodd** [comment]
@Schachte 

Your code can be simplified to look more like v1 as pointed out [above](https://github.com/aws/aws-sdk-go-v2/issues/1110#issuecomment-1054643716).

```go
	var apiErr smithy.APIError
	if errors.As(err, &apiErr) {
		switch apiErr.(type) {
		case *s3types.NoSuchBucket:
			log.Fatalf("no such bucket: %v\n", err)
		default:
			log.Fatalf("unknown error: %v\n", err)
		}
	}
```

Unwrapping the error looks nearly identical as branching on error code but has the advantage of getting a concrete error type and access to any specific fields of that error. You also don't need to know specific error codes. Hope that helps.

**Comment by Schachte** [comment]
@aajtodd Looks much cleaner, cheers!

**Comment by milosgajdos** [comment]
As far as I can see in my code, I can't switch type `smithy.APIError` into either of `*s3types.NoSuchKey, *s3types.NotFound` when using `HeadObject`:

```Go
		_, err := s3Client.HeadObject(ctx, keyPath)
		if err != nil {
			logger.Errorf("%T", err) // *smithy.OperationError

			var apiErr smithy.APIError
			if errors.As(err, &apiErr) {
				logger.Errorf("S3 error: %T", apiErr) //  *smithy.GenericAPIError

				switch apiErr.(type) {
				case *s3types.NoSuchKey, *s3types.NotFound:
                                        logger.Errorf("%T", err) // NEVER GETS LOGGED
				default:
					logger.Errorf("%T", err) // *smithy.OperationError
				}
		}
```
