### ISSUE TITLE
Where is awstesting?

### ISSUE THREAD

**Issue by saada** [aws/aws-sdk-go-v2#1114]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
In v1 we would use awstesting in tests. There is no migration steps from moving away from awstesting to something else?

**To Reproduce (observed behavior)**
Try importing the v2 awstesting package and find out it doesn't exist.

**Expected behavior**
The awstesting package should exist and have documentation alongside it.

**Comment by jasdel** [comment]
Thanks for reaching out @saada. the `awstesting` package was made an internal component of the v2 SDK as it was not intended to be publicly used, and will have breaking changes added to it. What were some of the components you used in the the v1 SDK's `awstesting` package?

**Comment by saada** [comment]
Hey @jasdel , I use it mostly for mocking Cloudformation function calls and responses.
For example...

```go
describeInput := &cfn.DescribeStacksInput{StackName": "test-stack"}
describeOutputCreated := &cfn.DescribeStacksOutput{Stacks: []*cfn.Stack{{StackName: "test-stack", StackStatus: aws.String(cfn.StackStatusCreateComplete)}}}
reqStackCreated := awstesting.NewClient(nil).NewRequest(&request.Operation{Name: "Operation"}, nil, describeOutputCreated)
...
cf.On("DescribeStacksRequest", describeInput).Return(reqStackCreated, describeOutputCreated)
```

Is there a way to rewrite such a test once the Mocks are fully supported again? https://github.com/aws/aws-sdk-go-v2/issues/786

**Comment by jasdel** [comment]
The `awstesting.NewClient` was one of the utilities removed from v2 all together because it allowed implementation details of the SDK to be duplicated or handed by application tests. In V2 SDK the best way to create mock/stubs for Clients is type define a type that implements an interface for the API client. The Interface would be defined by the application. This allows the mock tests to be specific to their use case.

```go
type CfnDescribeStacksAPI interface{
    DescribeStacks(context.Context, *cfn.DescribeStacksInput, ...func(*cfn.Options)) (*cfn.DescribeStacksOutput, error)
}
```

Applications would use these interfaces as their input parameters, and not depend directly on the API client type.
```go
type LambdaHandler struct {
    cfnClient CfnDescribeStacksAPI // Add additional interfaces as needed
}

func (h LambdaHandler) HandleEvent(ctx context.Conext, cfn.Event) (error) {
     resp, err := cfn.DescribeStacks(ctx, params)

     return nil
}

func main() {
    cfg, err := config.LoadDefaultConfig(context.TODO())
    
    h := LambdaHandler{
         cfnClient: cloudformation.NewFromConfig(cfg),
    }

    lambda.Start(h.HandleEvent)
}
```

Then unit tests would define mock clients.
```go
type MockDescribeStacks struct {}

func (m *MockDescribeStacks) DescribeStacks(ctx context.Context, in *cfn.DescribeStacksInput, optFns ...func(*cfn.Options)) (*cfn.DescribeStacksOutput, error) {
    // TODO implement mock behavior.
}
```

**Comment by saada** [comment]
Thanks. Will try this out. This would be helpful to add in the docs. What would really help is having the interfaces added somewhere so that we can generate mocks using mock generators like https://github.com/vektra/mockery.

**Comment by jasdel** [comment]
Thanks @saada lets use https://github.com/aws/aws-sdk-go-v2/issues/786 for tracking mocking and interface features in the v2 SDK.
