### ISSUE TITLE
service/s3/s3manager: Add support for resuming multipart upload between applications sessions.

### ISSUE THREAD

**Issue by jocot** [aws/aws-sdk-go-v2#113]
It seems that there is no facility to resume multipart uploads via the aws-sdk-go-v2 api once a session has ended or been disconnected.

**Comment by jasdel** [comment]
Hi @jpeddicord Thanks for reaching out to use. The SDK's S3 Upload manager does not currently support resuming multipart uploads between application sessions. We did not have any direct plans to support this, but I can add this as a feature request so it can be considered added the the SDK's backlog.

As a workaround If you're application uses the S3 APIs directly it will have the capabilities to perform multipart upload resuming between application sessions.

**Comment by jviney** [comment]
I have implemented a rough version of this feature if anyone is interested.

https://github.com/jviney/aws-sdk-go-v2/commit/925a73cc85d50382a2ddf456b1a3e762ab185797

**Comment by microyahoo** [comment]
We also need it, do you have plans to support it? @jasdel

**Comment by vbmithr** [comment]
I need this too.

**Comment by nickajacks1** [comment]
This would be relatively straightforward to implement on your own if `Upload` somehow exposed the UploadId returned from `CreateMultipartUpload` before the actual upload starts.  Maybe add a callback?
A workaround is to use a middleware, e.g.:
```go
	var uploadId string
	mw := middleware.InitializeMiddlewareFunc("extractUploadID", func(ctx context.Context, ii middleware.InitializeInput, ih middleware.InitializeHandler) (middleware.InitializeOutput, middleware.Metadata, error) {
		switch v := ii.Parameters.(type) {
		case *s3.UploadPartInput:
			if uploadId == "" {
				uploadId = *v.UploadId
			}
		}
		return ih.HandleInitialize(ctx, ii)
	})
```
