### ISSUE TITLE
"failed to parse response Date header value" warning when using `PutObject`

### ISSUE THREAD

**Issue by ditrytus** [aws/aws-sdk-go-v2#1131]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I am getting lot's of warnings in application log
```
failed to parse response Date header value, got [unknown time format: parsing time "Thu, 11 Feb 21 11:04:03 GMT" as "Mon Jan _2 15:04:05 2006": cannot parse ", 11 Feb 21 11:04:03 GMT" as " "]
```
when using `PutObject` function from `github.com/aws/aws-sdk-go-v2/service/s3`.

I tracked it down to this dependency in `smithy-go`:
https://github.com/aws/smithy-go/blob/main/transport/http/time.go

And in fact they are not handling this particular date correctly:
https://play.golang.org/p/lhRhdgl6fVm

**Version of AWS SDK for Go?**
1.2.0

**Version of Go (`go version`)?**
```
go1.15.5 darwin/amd64
```
**To Reproduce (observed behavior)**
I believe it's not an issue with particular usage of SDK but it's interaction with S3 service.

**Expected behavior**
Not get those warning at all.

**Additional context**
My buckets are in `eu-central-1` region.

**Comment by skmcgrail** [comment]
Thanks for reporting this bug, it would appear S3's PutObject response is returning a timestamp which contains a shortened 2-digit year compared to the expected format. We can add this variant to the formats supported by smithy-go.

**Comment by jasdel** [comment]
Thanks for reporting this issue @ditrytus The SDK has merged in a fix to address this, and the fix will be included in the SDK's next release.
