### ISSUE TITLE
ecs NewTasksRunningWaiter fails with expected []string value got []interface

### ISSUE THREAD

**Issue by Chanonry** [aws/aws-sdk-go-v2#1132]
### Version of AWS SDK for Go?

0.31.0.

### Version of Go (`go version`)?

1.15

### What issue did you see?

ecs NewTasksRunningWaiter errors with:
Waiter failed with error:  waiter comparator expected []string value got []interface {}

### Steps to reproduce

I am writing a smoke test to start a Fargate Task

Code snippets:

Running a task

```

input := ecs.RunTaskInput{
		Cluster:    aws.String(cluster),
		Count:      aws.Int32(1),
		LaunchType: types.LaunchTypeFargate,
		NetworkConfiguration: &types.NetworkConfiguration{
			AwsvpcConfiguration: &types.AwsVpcConfiguration{
				AssignPublicIp: types.AssignPublicIpEnabled,
				Subnets:        []string{subnet},
			},
		},
		PlatformVersion: aws.String("LATEST"),
		StartedBy:       aws.String("smoke test"),
		TaskDefinition:  aws.String(family),
	}
runTaskOutput, err = client.RunTask(ctx, &input)
```

this works, so set up DescribeTasksInput, create a RunningWaiter then Wait:

```
taskARN := *runTaskOutput.Tasks[0].TaskArn
taskDescription := &ecs.DescribeTasksInput{
		Cluster: aws.String(cluster),
		Tasks:   []string{taskARN},
	}
RunningWaiter := ecs.NewTasksRunningWaiter(client)
if err = RunningWaiter.Wait(context.TODO(), taskDescription, maxWaitTime); err != nil {
		log.Println("Waiter failed with error: ", err)
		return
	}
```
cluster is the cluster name maxWaitTime is time.Duration = 180 seconds

Output is : Waiter failed with error:  waiter comparator expected []string value got []interface {}

**Comment by skotambkar** [comment]
Thanks for reaching out. This issue should be fixed in https://github.com/aws/aws-sdk-go-v2/pull/1083 . Could you update your SDK to the latest version ? 

Let us know if you still face the issue.

**Comment by Chanonry** [comment]
Sorted. Thanks
