### ISSUE TITLE
Describing aws service across region inconsistencies and issues

### ISSUE THREAD

**Issue by Chandrian** [aws/aws-sdk-go-v2#1139]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

Describing resources of different AWS services have been tricky in the aws-sdk-go-v2 as it looks inconsistent or impossible at time. 

For example:
1) AWS EC2: you can use DescribeRegions method to get all the regions ec2 is available, which is really nice
2) AWS RDS: you can use DescribeSourceRegionsPaginator, pretty close, but not the same, still, it works
3) AWS Redshift: well, I'm still looking, as there's really no ways to find out in which region it's enabled...

Am I missing something? Is there a unique way to get this information across services? How do you do it for Redshift?

**Comment by jasdel** [comment]
Thanks for reaching out @Chandrian. We suggest using the Amazon EC2's `DescribeRegions` operation in most cases to describe the AWS Regions that are available. There is no API to describe regions specific services are in though. The best method to determine which services are available in a given region is the [AWS Service Endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html) page.
