### ISSUE TITLE
Cross account DynamoDB table access

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#114]
It's not clear to me from https://godoc.org/github.com/aws/aws-sdk-go-v2/aws/external#LoadDefaultAWSConfig how I would access a DynamoDB table from another account.

Say I deploy my Golang function in a lambda running in the account 1111111111. How do I access the table in account 2222222222, e.g. arn:aws:dynamodb:ap-southeast-1:222222222:table/channels  ?

Furthermore the Inputs don't seem to facilitate specifying a cross account Arn for the TableName: https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb#ScanInput

Unless I'm missing something?

**Comment by Doug-AWS** [comment]
This isn't so much as a Go issue or even a DynamoDB issue, but an IAM issue. I would start with their tutorial https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

**Comment by kaihendry** [comment]
So IIUC, I need to switch roles and then I will be able to access the correct table?

Do you mind please pointing out the appropriate function for doing that? https://godoc.org/github.com/aws/aws-sdk-go-v2

I did find https://godoc.org/github.com/aws/aws-sdk-go-v2/aws/external#AssumeRoleConfig but I don't understand how it works. So I'd be grateful for any guidance here. Thank you,

**Comment by jasdel** [comment]
This issue is fairly old. We're working on developer guides for the v2 SDK over at, https://github.com/aws/aws-sdk-go-v2/tree/documentation/content/en/docs . Specifically, https://github.com/aws/aws-sdk-go-v2/blob/documentation/content/en/docs/configuring-sdk/_index.md Please reach out if you're still having issues with this.

**Comment by TheGUNNER13** [comment]
@kaihendry did it work for you? If yes, can you give me there code snippet?
