### ISSUE TITLE
ListPartsPaginator paginates forever

### ISSUE THREAD

**Issue by morsecodist** [aws/aws-sdk-go-v2#1140]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When paginating through pages of multipart upload parts with `ListPartsPaginator` the iterator loops forever.

**Version of AWS SDK for Go?**
`1.2.0`

**Version of Go (`go version`)?**

`go version go1.16 linux/amd64`

```
paginator := s3.NewListPartsPaginator(client, params)
for paginator.HasMorePages() {
	parts, err := paginator.NextPage(context.TODO())
	if err != nil {
		return nil, err
	}
}
```

**Expected behavior**
I expect `HasMorePages` to return `false` when the last page has been fetched and the iterator to stop.

**Additional context**
This is happening because the `nextToken` is `&"0"` on the last page and not `nil`. The paginator seems to expect `nil`.

I don't really understand how the auto-generated stuff works or I would fix it myself. I fixed this temporarily in my fork by making the following change to `service/s3/api_op_ListParts.go`:

```go
// NextPage retrieves the next ListParts page.
func (p *ListPartsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*ListPartsOutput, error) {
	if !p.HasMorePages() {
		return nil, fmt.Errorf("no more pages available")
	}

	params := *p.params
	params.PartNumberMarker = p.nextToken

	params.MaxParts = p.options.Limit

	result, err := p.client.ListParts(ctx, &params, optFns...)
	if err != nil {
		return nil, err
	}
	p.firstPage = false

	prevToken := p.nextToken
	p.nextToken = result.NextPartNumberMarker

	if p.options.StopOnDuplicateToken && prevToken != nil && p.nextToken != nil && *prevToken == *p.nextToken {
		p.nextToken = nil
	}

	// start of fix
	if p.nextToken != nil && *p.nextToken == "0" {
		p.nextToken = nil
	}
	// end of fix

	return result, nil
}
```

It's possible that this isn't the best fix because the issue may be caused by thing lower-level expecting a number then mapping the `nil` case to `0` then to a string.

**Comment by skmcgrail** [comment]
A workaround for this is to configure the paginators `StopOnDuplicateToken` option which would avoid the endless loop.

```go
paginator := s3.NewListPartsPaginator(client, params, func(o *s3.ListPartsPaginatorOptions) {
    o.StopOnDuplicateToken = true
})
```

@stefansundin put together a PR that originally brought this issue to our attention: https://github.com/aws/aws-sdk-go-v2/pull/1100

Since this is a code generated though I will need to put together an alternative solution. Likely we can add some additional metadata properties to indicate that there is an explicit member that can be checked for some s3 operations to determine if the result is no longer truncated.

**Comment by morsecodist** [comment]
@skmcgrail thanks for the quick reply! I tried using `StopOnDuplicateToken` but since the pages cycle it doesn't help in every case. For example, it goes: `nil`, `1000`, `1500`, `0`, `1000`, `1500`, `0` so no two identical tokens are ever called one after another.
