### ISSUE TITLE
Add CSM Support

### ISSUE THREAD

**Issue by iann0036** [aws/aws-sdk-go-v2#1142]
Port the v1 SDK's client side metric (CSM) client support for reporting metrics.

aws/csm
aws/aws-sdk-go#2677
aws/aws-sdk-go#2678

**Comment by securisec** [comment]
Bump on this

**Comment by jasdel** [comment]
Thanks for reaching out @iann0036, it would be great to hear your use case for the CSM feature, and more details about how you are using the feature within your application's stack.

**Comment by securisec** [comment]
@jasdel , I can share my use case here. From a security perspective, CSM helps me understand what an application is trying to do during dev and testing (which leads to better IAM policies), instead of relying on api call log parsing post deployment.

**Comment by iann0036** [comment]
@jasdel It relates to CSM usage within https://github.com/iann0036/iamlive

**Comment by danpilch** [comment]
+1 for CSM, we use it for figuring out what permissions are required whilst in development.

**Comment by lucix-aws** [comment]
> It would also be nice if the code were written with a pluggable metrics sink

This is the route we intend to go leveraging https://github.com/aws/smithy-go/issues/470.

#1744 covers this more generally, going to close this one and cross-link.
