### ISSUE TITLE
[MWAA - Airflow] How to deal with MWAA from aws-sdk-go-v2?

### ISSUE THREAD

**Issue by alessiosavi** [aws/aws-sdk-go-v2#1143]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

It's possible to interact with MWAA (Airflow) using the aws-sdk-go-v2?

**Comment by jasdel** [comment]
Thanks for reaching out @alessiosavi From this post [Introducing Amazon Managed Workflows for Apache Airflow (MWAA)](https://aws.amazon.com/blogs/aws/introducing-amazon-managed-workflows-for-apache-airflow-mwaa/) It looks like the API is available applications to use the AWS SDKs to interact with.

With that said though the v2 SDK's APIs are not yet up to date. We're working on getting the API model updated, and can use this GitHub issue to track the v2 SDK's support for Amazon Managed Workflows for Apache Airflow.

**Comment by skotambkar** [comment]
MWAA service is now available with AWS SDK for Go V2. Please review our [api reference docs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/mwaa) to look up usage of this service.

Let us know if you have any questions or concerns.
