### ISSUE TITLE
dynamodb/attributevalue: Consider changing default behavior for empty maps and slices

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#115]
aws/aws-sdk-go#682 raised an issue that the SDK's dynamodbattribute.Marshal methods will marshal empty slices and maps as `NULL`. This makes is cumbersome to intentionally have the values marshaled as empty list or map.

Consider if it makes sense to change the logic, so that a non-nil slice/map will marshal to a empty list `av.L = []dynamodb.AttributeValue{}` or map. `av.M = map[string]dynamodb.AttributeValue{}`. `nil` maps or slices would still be marshaled as `av.NULL = true`.

Issue identified in [gitter](https://gitter.im/aws/aws-sdk-go?at=5a723b66b3c4a0d376c52384) where using an empty list with the `expressions` Update caused unexpected errors.

**Comment by jasdel** [comment]
Example of current workaround, https://play.golang.org/p/RQtGrPP8ee6

**Comment by MatejBalantic** [comment]
+1 for this request. I would like to store empty arrays as such

**Comment by famartinez80** [comment]
+1 for this request. I would like to store empty arrays as such
