### ISSUE TITLE
What is the difference between ses & sesv2 ?

### ISSUE THREAD

**Issue by amankaur27** [aws/aws-sdk-go-v2#1150]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

Hi,

I checked out the source code for aws sdk for go v2. It contains two folder for ses service: ses & sesv2. I can see that both folders were updated few hours ago with commit id: 153000a.

What is the difference between these two ? Which syntax should I use to build my email service using ses ?

**Comment by skotambkar** [comment]
Thanks for reaching out. All service modules were updated in the recent release as the core dependency of the module was updated. 

Recommend looking at out [changelog](https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md) to see if a service had updates. 

Here's the guide for [sesV2](https://docs.aws.amazon.com/ses/latest/APIReference-V2/Welcome.html) and [ses](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/Welcome.html)dev guide to find out more information on what's changed.

**Comment by amankaur27** [comment]
Thanks for your reply. But the links you provided did not tell me which api should I use ? ses or sesv2 ?

**Comment by amankaur27** [comment]
@jasdel  can this issue be reopened ?

**Comment by skotambkar** [comment]
@amankaur27 Go SDK builds on top of models provided by service teams, and does not have a way to provide guidance on which service to use for your use-case. The available service docs I linked above are the best possible resource to understand the differences between the two service clients. 

That said, I would suggest reaching out to AWS Support or use [AWS Developer forum](forums.aws.amazon.com), as they would be able to better assist with this question.

**Comment by nightpool** [comment]
Okay but... what is the difference between SES and SESv2? Why can nobody seemingly answer this simple question? Why are there two different versions?

**Comment by lucix-aws** [comment]
> Okay but... what is the difference between SES and SESv2?

After digging into this - **the only information I could find on the difference between the two was this [blog post](https://aws.amazon.com/blogs/messaging-and-targeting/upgrade-your-email-tech-stack-with-amazon-sesv2-api/) which is only a month old**. The _entire_ corpus of SES documentation has absolutely _zero_ mention of the differences between the two that I could find. Their [FAQ](https://aws.amazon.com/ses/faqs/) is equally void of such information.

I want to expound on this previous comment a bit:

> Go SDK builds on top of models provided by service teams and does not have a way to provide guidance on which service to use for your use-case

(this engineer is no longer on the Go SDK team)

Sure, yes, this is true. As SDK engineers we are not really subject matter experts on AWS services or what their APIs do (though as you can imagine, we use some ourselves and are familiar with the more ubiquitous ones like S3, SQS, etc.).

Services updates and releases are automated across SDKs and occur largely without our intervention or awareness. So from our perspective, `service/sesv2` simply popped into existence one day in our SDK on the date at which the service team elected to release it.

**BUT - these models are chock full of documentation, which we include in the generated SDK.** You would think that the documentation for SES would include blurb about "v1 vs v2" or something of that nature to the SeSv2 API model, or _somewhere_, such that it might appear [here](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sesv2#pkg-overview). For reasons entirely unknown to me, that is not the case.

**Comment by bschulz87** [comment]
Researching this very question brought me here. I found this blog article ["Upgrade Your Email Tech Stack with Amazon SESv2 API"](https://aws.amazon.com/blogs/messaging-and-targeting/upgrade-your-email-tech-stack-with-amazon-sesv2-api/) with some details and explanations.

> Leveraging insights from current SES customers, the SESv2 API includes several new actions related to list and subscription management, the creation and management of dedicated IP pools, and updates to unsubscribe that address recent industry requirements.

> The SESv2 API offers an enhanced experience compared to the original SESv1 API. Compared to the SESv1 API, the SESv2 API provides a more modern interface and flexible options that make building scalable, high-volume email applications easier and more efficient.

**Comment by umarbutler** [comment]
So... what is the difference?

**Comment by billfeng** [comment]
This blog post by AWS themselves seem to go into a lot of details. I didn't read it myself but maybe it'll be helpful for those of you looking for an answer: https://aws.amazon.com/blogs/messaging-and-targeting/upgrade-your-email-tech-stack-with-amazon-sesv2-api/

**Comment by Dragas** [comment]
Sadly, v2 does not cover entire functionality of v1, where there is no equivalent action to create receipt rules, so you're stuck with mish mash of v2 and v1 apis.
