### ISSUE TITLE
Error: Does not contain package "github.com/aws/aws-sdk-go-v2/aws/session"

### ISSUE THREAD

**Issue by dhirajgidde** [aws/aws-sdk-go-v2#1156]
-  I've gone though the API reference
-  I've checked AWS Forums and StackOverflow for answers

But I have unable to find "github.com/aws/aws-sdk-go-v2/aws/session" package.

Regards,
Dhiraj Gidde

**Comment by dhirajgidde** [comment]
- I've gone though the API reference

-  I've checked AWS Forums and StackOverflow for answers.

**Comment by shogo82148** [comment]
Read the migration guide https://aws.github.io/aws-sdk-go-v2/docs/migrating/
https://github.com/aws/aws-sdk-go has the `session` package, but aws-sdk-go-v2 doesn't.
I guess you need to import the `github.com/aws/aws-sdk-go-v2/config` package. https://aws.github.io/aws-sdk-go-v2/docs/migrating/#configuration-loading

I recommend you to post a new question to AWS Forums or StackOverflow in next time.

The README says:

> https://github.com/aws/aws-sdk-go-v2#getting-help
> Please use these community resources for getting help. We use the GitHub issues for tracking bugs and feature requests.

Your question is not a bug report neither a feature request.

**Comment by jasdel** [comment]
Thanks for reaching out @shogo82148 as @shogo82148 mentioned the V2 saw significant refactor between v0.24  and v1.0. Check out the  [migrating guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/) for more details on that change, it covers these changes and how to update your application for them.
