### ISSUE TITLE
middleware.GetRequestIDMetadata returns nothing even though RequestID is present in the response object

### ISSUE THREAD

**Issue by eugene-manuilov** [aws/aws-sdk-go-v2#1177]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
The `middleware.GetRequestIDMetadata` function returns `"", false` even though I see the appropriate `X-Amzn-Requestid` header in the response.

**Version of AWS SDK for Go?**
`1.2.1`

**Version of Go (`go version`)?**
`go version go1.15.5 linux/amd64`

**To Reproduce (observed behavior)**
```go
import (
    "fmt"
    "github.com/aws/aws-sdk-go-v2/aws"
    "github.com/aws/aws-sdk-go-v2/aws/middleware"
    "github.com/aws/aws-sdk-go-v2/service/cloudformation"
)

args := cloudformation.DeleteStackInput{
    StackName:          aws.String("xxxxx"),
    ClientRequestToken: aws.String("yyyy"),
}

ctx := ...
cf := cloudformation.NewFromConfig(...)
response, err := api.cf.DeleteStack(ctx, &args)
if err == nil {
    fmt.Println(middleware.GetRequestIDMetadata(response.ResultMetadata))
    // Outputs: "", false
}
```

**Expected behavior**
The `middleware.GetRequestIDMetadata` function should return the correct RequestID from the response header.

**Additional context**
<details>
<summary>Request log</summary>

```
SDK 2021/03/17 12:45:26 DEBUG Request
POST / HTTP/1.1
Host: cloudformation.us-east-1.amazonaws.com
User-Agent: aws-sdk-go-v2/1.2.1
Content-Length: 222
Amz-Sdk-Invocation-Id: 772e8976-e1eb-49b4-8fd8-be86ccbc1690
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxx/xxxxxxx/us-east-1/cloudformation/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-user-agent, Signature=xxxxxxxxxxxxxxxxxxx
Content-Type: application/x-www-form-urlencoded
X-Amz-Date: 20210317T104526Z
X-Amz-User-Agent: aws-sdk-go-v2/1.2.1 os/linux lang/go/1.15.5 md/GOOS/linux md/GOARCH/amd64
Accept-Encoding: gzip
```

</details>
<details>
<summary>Response log</summary>

```
SDK 2021/03/17 12:45:26 DEBUG Response
HTTP/1.1 200 OK
Content-Length: 212
Content-Type: text/xml
Date: Wed, 17 Mar 2021 10:45:25 GMT
X-Amzn-Requestid: ae52b0f3-29f6-4967-923c-4df3d928a9ab

<DeleteStackResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <ResponseMetadata>
    <RequestId>ae52b0f3-29f6-4967-923c-4df3d928a9ab</RequestId>
  </ResponseMetadata>
</DeleteStackResponse>
```

</details>

**Comment by eugene-manuilov** [comment]
Looks like `SetRequestIDMetadata` and `GetRequestIDMetadata` function retrieve different metadata instances... :thinking: 

If I add `fmt.Printf("%v\n", metadata)` to the `SetRequestIDMetadata` function, I'll get the following:
```
&{map[{}:-1857169721 {}:3063bae8-1a2c-442b-b95a-eb6890ebcb3c {}:{13838715517144620857 1363959148 0xf734a0} {}:{0 63751682371 <nil>}]}
```

If I add the same print to the `GetRequestIDMetadata`, it will output this:
```
{map[{}:{[{<nil> false false {map[{}:-1857169721 {}:0xc00028c010 {}:3063bae8-1a2c-442b-b95a-eb6890ebcb3c {}:{13838715517144620857 1363959148 0xf734a0} {}:{0 63751682371 <nil>}]}}]}]}
```
Seems like the metadata object is wrapped into another metadata object, or not? :confused:

**Comment by skmcgrail** [comment]
I believe this is a symptom of the following issue: https://github.com/aws/aws-sdk-go-v2/issues/1154

We will look at getting this prioritized and fixed before our next release.

**Comment by skmcgrail** [comment]
Fixed in latest release https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-08-04
