### ISSUE TITLE
too many open files with FIPS S3 operations on Linux

### ISSUE THREAD

**Issue by saedx1** [aws/aws-sdk-go-v2#1179]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When deleting/putting into S3 through a FIPS endpoint on a Linux Operating System, a "too many open files" error is produced. This doesn't happen on Mac OS or Windows, and it doesn't happen on any OS without the FIPS endpoint.

Error:
```
operation error S3: DeleteObject, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Delete
 "https://BUCKET.s3-fips.dualstack.us-west-2.amazonaws.com/KEY?x-id=DeleteObject": dial tcp:
lookup BUCKET.s3-fips.dualstack.us-west-2.amazonaws.com: too many open files
```

**Version of AWS SDK for Go?**
`v1.2.1`

**Version of Go (`go version`)?**
`go version go1.16.2 linux/amd64`

**To Reproduce (observed behavior)**
This breaks on Linux only. If you don't set the FIPS `EndpointResolver` then it works fine. This applies to both deletion and put.
```go
cfg, _ := config.LoadDefaultConfig(context.TODO())
s3cfg := cfg.Copy()
s3cfg.EndpointResolver = aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
    return aws.Endpoint{
	    URL:           s3FIPSEndpoint,
	    SigningRegion: region,
    }, nil
})
svc := s3.NewFromConfig(s3cfg)
uploader := s3manager.NewUploader(svc)
_, err = uploader.Upload(...
```

**Expected behavior**
Object being deleted or put into S3.

**Additional context**
I tried adjusting the file descriptor limit and that didn't help. I even checked how many are being used, and the most I got was 8.

**Comment by jasdel** [comment]
@saedx1 are you still running into this issue? We've not been able to reproduce this issue with the latest version of the SDK. When using the SDK to upload multiple files to Amazon S3, your application will need to ensure that it closes the files after upload completes. This is especially important if the uploads are done in a loop without closing open files.

**Comment by saedx1** [comment]
> @saedx1 are you still running into this issue? We've not been able to reproduce this issue with the latest version of the SDK. When using the SDK to upload multiple files to Amazon S3, your application will need to ensure that it closes the files after upload completes. This is especially important if the uploads are done in a loop without closing open files.

Hi,
Yes, we reported this issue to AWS professional support at the time, and it got fixed a couple of weeks ago.

To clarify, if other people stumble across this, it wasn't a Go issue, it was a Linux-wide issue, no SDK (neither Go, the CLI or anything else) was able to perform any operation with FIPS on any Linux distro until this was fixed (even Amazon Linux). So, if you get into this issue, make sure you update the version of the SDK you're using, even if it's not golang's.
