### ISSUE TITLE
Route53 Create - Invalid Input Error

### ISSUE THREAD

**Issue by undeadops** [aws/aws-sdk-go-v2#118]
Please fill out the sections below to help us address your issue.

### What issue did you see?
Unable to get a valid Route53 ResourceRecord updated/created

### Steps to reproduce

running main.go file from Gist: `go run main.go`

Simplified Runnable Gist: https://gist.github.com/undeadops/c7e7e6a8d044bbbc985791514027dbe6

Which produces the following output:

```
INPUT ---------------------------------------------------

{
  ChangeBatch: {
    Changes: [{
        Action: CREATE,
        ResourceRecordSet: {
          Failover: ,
          Name: "sweethost.sub.example.com.",
          Region: ,
          ResourceRecords: [{
              Value: "sweetalias.ec2.internal"
            }],
          Type: CNAME
        }
      }],
    Comment: "CNAME upserts for zone Run by DNS-SYNC"
  },
  HostedZoneId: "-------ZONEID-HERE--------"
}

------------------------------------------------------

InvalidInput InvalidInput: Invalid request
	status code: 400, request id: c96c28ae-0b83-11e8-8731-091632d7a4a7
Res: <nil>
```

**Comment by undeadops** [comment]
Ah... TTL is required in this case...  Adding TTL made it work.

**Comment by c100k** [comment]
I've just got the same error with https://github.com/aws/aws-sdk-js-v3 and an `A` record. Indeed, providing the TTL fixes it. Documentation should probably be updated. Or at least, the error should contain some kind of `reasons`.
