### ISSUE TITLE
Tagging VPC -> SecurityGroups with AWS SDK for Go

### ISSUE THREAD

**Issue by cupakob** [aws/aws-sdk-go-v2#1181]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

Is there any way to tag SecurityGroups (under VPC) with the AWS SDK for Go?

**Comment by skotambkar** [comment]
Thanks for reaching out. You can create tags using [Ec2 clients - CreateTags operation](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.CreateTags).
