### ISSUE TITLE
private/protocol/rest: URL builder makes incorrect assumptions about content

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#120]
The SDK's protocol rest marshaler makes assumptions about the content of the URL that are not always valid. Specifically in its ability to clean the path elements of the URL.

The V1 SDK provided a `DisableRestProtocolURICleaning` option to disable this cleaning functionality, but arguably the SDK shouldn't of been cleaning anything to start with. 

aws/aws-sdk-go#1769
aws/aws-sdk-go#1425
aws/aws-sdk-go#970
aws/aws-sdk-go#935
aws/aws-sdk-go#920

**Comment by jasdel** [comment]
This issue may not be relevant to the v2 SDK. The SDK does not perform any clean nor join with URLs. There may be unexpected other issues with this such as "dirty" urls with duplicate  slashes.

**Comment by trevorrowe** [comment]
Issue no longer relevant.
