### ISSUE TITLE
panic when missing credentials

### ISSUE THREAD

**Issue by amznpurple** [aws/aws-sdk-go-v2#1200]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

Panic with this code:

```
package main
import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)
const region = "ca-central-1"
func main() {
	fmt.Printf("hello s3\n")
	options := s3.Options{
		// The region to send requests to. (Required)
		Region: region,
	}
	client := s3.New(options)
	fmt.Printf("list buckets\n")
	output, err := client.ListBuckets(context.TODO(), &s3.ListBucketsInput{}) // XXX: panics here!
	if err != nil {
return
	}
	fmt.Printf("Bucket owner: %+v\n", output.Owner) // *DisplayName or *ID
	for _, bucket := range output.Buckets {
		fmt.Printf("Bucket: %+v\n", bucket.Name)
	}
}
```

**Version of AWS SDK for Go?**
Example: v1.29.22
* get SDK version by printing the output of `aws.SDKVersion` in your code after importing `"github.com/aws/aws-sdk-go-v2/aws"`

`git master/main`

**Version of Go (`go version`)?**
1.16

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

Run code.
It should not panic. It does.
```
Panic: runtime error: index out of range [1024] with length 1024
 
goroutine 1 [running]:
github.com/aws/smithy-go/io.(*RingBuffer).Read(0xc000486060, 0xc0000ae000, 0x200, 0x200, 0x4, 0xc000500780, 0x7f6a80365638)
	/home/purple/go/pkg/mod/github.com/aws/smithy-go@v1.2.0/io/ringbuffer.go:63 +0xb6
bytes.(*Buffer).ReadFrom(0xc000486c90, 0x79b200, 0xc000486060, 0x7f6a80365638, 0xc000486c90, 0x1)
	/usr/lib/go-1.16/src/bytes/buffer.go:204 +0xbe
io.copyBuffer(0x79ae60, 0xc000486c90, 0x79b200, 0xc000486060, 0x0, 0x0, 0x0, 0x1, 0x1, 0x79af40)
	/usr/lib/go-1.16/src/io/io.go:409 +0x357
io.Copy(...)
	/usr/lib/go-1.16/src/io/io.go:382
```

**Expected behavior**

Should not panic.

**Additional context**

When you pass in credentials, then it doesn't panic. But it's a bug that a user could ever cause a panic.

**Comment by skmcgrail** [comment]
Can reproduce the panic with the following code, a very subtle bug that can only happen on certain data sizes that are a multiple of 1024.
```
package main

import (
	"bytes"
	"fmt"
	smithyio "github.com/aws/smithy-go/io"
	"io"
	"io/ioutil"
	"math/rand"
)

func main() {
	var data [100]byte

	_, err := rand.Read(data[:])
	if err != nil {
		panic(err)
	}

	dataReader := bytes.NewReader(data[:])

	var stack [10]byte
	ringBuffer := smithyio.NewRingBuffer(stack[:])

	reader := io.TeeReader(dataReader, ringBuffer)

	_, err = ioutil.ReadAll(reader)
	if err != nil {
		panic(err)
	}

	var buffer bytes.Buffer

	_, err = io.Copy(&buffer, ringBuffer)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%x\n", buffer.String())
}
```
