### ISSUE TITLE
Bad stop condition on generated `HasMorePages`  function on all paginators

### ISSUE THREAD

**Issue by draeron** [aws/aws-sdk-go-v2#1201]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
```go
func (p *GetResourcesPaginator) HasMorePages() bool {
	return p.firstPage || p.nextToken != nil
}
````

The condition should check for empty token `*p.nextToken != ""`

```go
func (p *GetResourcesPaginator) HasMorePages() bool {
	return p.firstPage || (p.nextToken != nil && *p.nextToken != "")
}
```

Or scrap the whole `firstPage` boolean and assume an nil `nextToken` to be the first page and an empty one to be the last page.

**Version of AWS SDK for Go?**
v1.3.0

**To Reproduce (observed behavior)**

If `StopOnDuplicateToken` is not set to true, it will loop endlessly. The whole point of using paginator is not having to ask yourself when you need to stop the loop.

If all result fit the first page, it'll pass through the `StopOnDuplicateToken` since `nil` ain't an empty string. The end result will to refetch the first page and doubling the data.

**Expected behavior**
Function should return false and stop looping if there are no need to it.

**Additional context**
Since this is generated code, this is true for all paginators in the SDK.

**Comment by techotron** [comment]
I've been trying to get it working all night until I found this. If there's anyone else out there who finds this before it's fixed, this is how I worked around the problem. Hopefully it'll help someone:

```
	for paginator.HasMorePages() {
		i++
		resources, err := paginator.NextPage(context.TODO())
		if err != nil {
			log.Errorf("Failed to list resources for: %s. Error: %s", team, err)
			return nil, err
		}
	
		for _, resource := range resources.ResourceTagMappingList {
			al := ResourcesRow{ResourceARN: *resource.ResourceARN}
			allResources = append(allResources, al)
		}

		if *resources.PaginationToken == "" {
			break
		}
		log.Infof("Processed %s pages", strconv.Itoa(i))
	}
```
