### ISSUE TITLE
Re-enable access to endpoints

### ISSUE THREAD

**Issue by Cyberax** [aws/aws-sdk-go-v2#1205]
**Is your feature request related to a problem? Please describe.**
Yes, the old SDK provided access to the list of AWS endpoints. This is necessary to build generic UI that allows selection of an arbitrary region.

**Describe the solution you'd like**
Move `aws-sdk-go-v2/internal/endpoints/endpoints.go` out of the `internal` package. This would also allow to remove duplicated `endpoints.Partitions` generated code from all the SDKs.

**Describe alternatives you've considered**
There is no other clear way to obtain a list of all regions. It has to be hard-coded in the application and maintained as AWS adds new regions.

**Comment by aajtodd** [comment]
This isn't something we plan to expose in v2. Region support is actually service specific (e.g. some services only launch in a few regions and over time are made available in more/all regions). 

Region enumeration is something your own application will have to maintain going forward.
