### ISSUE TITLE
Unsure how to mock out API interfaces for testing purposes

### ISSUE THREAD

**Issue by johnw188** [aws/aws-sdk-go-v2#121]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2.0.0-preview.2

### Version of Go (`go version`)?
go version go1.9.3 darwin/amd64

### What issue did you see?
I'm having an issue mocking out responses for some tests I'm writing. In my application source I have:

```go
	keyID := "alias/" + k.KMSKeyName
	keySpec := kms.DataKeySpec("AES_256")
	dataKeyInput := kms.GenerateDataKeyInput{KeyId: &keyID, KeySpec: keySpec}
	dataKeyRequest := k.Client.GenerateDataKeyRequest(&dataKeyInput)

	dataKeyOutput, err := dataKeyRequest.Send()
	if err == nil { // dataKeyOutput is now filled
		fmt.Println(dataKeyOutput)
	} else {
		fmt.Println("error: ", err)
	}

	fmt.Println("CiphertextBlob: ", dataKeyOutput.CiphertextBlob)
	fmt.Println("PlaintextKey: ", dataKeyOutput.Plaintext)
```

I'm calling `GenerateDataKeyRequest`, then firing `dataKeyRequest.Send()` to execute the request. This works great in the app.

In my tests I want to mock the response so that I can have consistent ciphertext on all test executions. I updated the type of `k.Client` from `kms.KMS` to `kmsiface.KMSAPI` and then used [https://github.com/stretchr/testify](testify) to create mocks for the interface.

In my test setup I build the mock responses as so:

```go
func (s *KMSCodecTestSuite) SetupTest() {
	ciphertextBlob := []byte{1, 2, 3, 0, 120, 178, 12, 44, ...}
	plaintextKey := []byte{27, 169, 42, 47, 42, 238, ...}
	mockAPI := &mocks.KMSAPI{}
	mockDataKeySender := mocks.DataKeySender{}
	mockDecryptSender := mocks.DecryptSender{}
	mockAPI.On("GenerateDataKeyRequest", mock.Anything).Return(mockDataKeySender)
	mockAPI.On("DecryptRequest", mock.Anything).Return(mockDecryptSender)
	mockDataKeySender.On("Send", mock.Anything).Return(kms.GenerateDataKeyOutput{CiphertextBlob: ciphertextBlob, Plaintext: plaintextKey}, nil)
	mockDecryptSender.On("Send", mock.Anything).Return(kms.DecryptOutput{Plaintext: plaintextKey}, nil)

	s.Codec = &KMSCodec{"testkey", mockAPI}
	s.MockKMSAPI = mockAPI
}
```

The problem is that `GenerateDataKeyRequest` returns a `kms.GenerateDataKeyRequest` which is then called with `Send()`. This isn't an interface, and when I created a `DataKeySender` interface

```go
type dataKeySender interface {
	Send() (*kms.GenerateDataKeyOutput, error)
}
```

and mock out the responses I get a type mismatch panic when executing my tests:

```
panic: interface conversion: interface {} is mocks.DataKeySender, not kms.GenerateDataKeyRequest [recovered]
	panic: interface conversion: interface {} is mocks.DataKeySender, not kms.GenerateDataKeyRequest
```

The `aws.Request` that's making the call isn't an interface either, so I don't see how I could create a `kms.GenerateDataKeyRequest` with a mock that would return the correct data.

Does anyone have any advice on how to setup these tests? I feel like I'm really close but missing something obvious. Thanks for any help you can give!

**Comment by xibz** [comment]
Hello @johnw188, thank you for reaching out to us. We have an [example](https://github.com/aws/aws-sdk-go-v2/blob/master/example/service/sqs/mockingClientsForTests/ifaceExample_test.go) that illustrates how to mock tests. Please let us know if you have any additional questions.

**Comment by johnw188** [comment]
Thank you for the example! It took me a bit to grok what was going on but I think I figured it out. For those who might come across this question in the future, the missing piece for me was that if you manually set the `Data` field of an `aws.Request`, the `Send()` method simply returns the value of the `Data` field instead of actually executing a request.

In my example above, the solution was to manually set the `Request` field of the `GenerateDataKeyRequest` and include a pointer to object I want returned in the `Data` field of that Request.

```go
func (s *KMSCodecTestSuite) SetupTest() {
	ciphertextBlob := []byte{1, 2, 3, 0, 120, 178, 12, 44, 176, ...}
	plaintextKey := []byte{27, 169, 42, 47, 42, 238, ...}
	mockAPI := &mocks.KMSAPI{}
	mockAPI.On("GenerateDataKeyRequest", mock.Anything).Return(kms.GenerateDataKeyRequest{
		Request: &aws.Request{
			Data: &kms.GenerateDataKeyOutput{CiphertextBlob: ciphertextBlob, Plaintext: plaintextKey},
		},
	})
	mockAPI.On("DecryptRequest", mock.Anything).Return(kms.DecryptRequest{
		Request: &aws.Request{
			Data: &kms.DecryptOutput{Plaintext: plaintextKey},
		},
	})

	s.Codec = &KMSCodec{"testkey", mockAPI}
	s.MockKMSAPI = mockAPI
}
```

Using this pattern with [testify](https://github.com/stretchr/testify) and [mockery](https://github.com/vektra/mockery) for generating the mock interfaces makes it super easy to have your mock api return different responses for various inputs, by replacing the `mock.Anything` parameter with a different filter. For example, if I wanted to return a different CiphertextBlob for different KMS key names, I could use a `mock.MatchedBy` filter

```go
mock.MatchedBy(func(input *kms.DataKeyInput) bool {
	return input.KeyId != nil && *input.KeyId == "alias/testkey"
})
```

which would leave my test looking like this:

```go
func (s *KMSCodecTestSuite) SetupTest() {
	ciphertextBlob := []byte{1, 2, 3, 0, 120, 178, 12, 44, 176, ...}
	ciphertextBlob2 := []byte{1, 2, 3, 0, 242, 35, 26, 47, ...}
	plaintextKey := []byte{27, 169, 42, 47, 42, 238, ...}
	mockAPI := &mocks.KMSAPI{}
	mockAPI.On("GenerateDataKeyRequest", mock.MatchedBy(func(input *kms.GenerateDataKeyInput) bool { return input.KeyId != nil && *input.KeyId == "alias/testkey" })).Return(kms.GenerateDataKeyRequest{
		Request: &aws.Request{
			Data: &kms.GenerateDataKeyOutput{CiphertextBlob: ciphertextBlob, Plaintext: plaintextKey},
		},
	})
	mockAPI.On("GenerateDataKeyRequest", mock.MatchedBy(func(input *kms.GenerateDataKeyInput) bool { return input.KeyId != nil && *input.KeyId == "alias/testkey2" })).Return(kms.GenerateDataKeyRequest{
		Request: &aws.Request{
			Data: &kms.GenerateDataKeyOutput{CiphertextBlob: ciphertextBlob2, Plaintext: plaintextKey},
		},
	})
	mockAPI.On("DecryptRequest", mock.Anything).Return(kms.DecryptRequest{
		Request: &aws.Request{
			Data: &kms.DecryptOutput{Plaintext: plaintextKey},
		},
	})

	s.Codec = &KMSCodec{"testkey", mockAPI}
	s.MockKMSAPI = mockAPI
}
```

**Comment by apexskier** [comment]
Does anyone have an updated link to an example test?

**Comment by kristianjaeger** [comment]
Seems like https://github.com/matryer/moq might be another option if you setup your own interface with the methods to test. The docs on moq seem a bit sparse but seems like a useful option.
