### ISSUE TITLE
Document how to migrate from defaults.RemoteCredProvider

### ISSUE THREAD

**Issue by kevinburke1** [aws/aws-sdk-go-v2#1216]
The way credentials are currently loaded in our source code involves checking a few different places in turn, via a ChainProvider. 

I currently use `defaults.RemoteCredProvider` to load credentials. Reading the code, it looks like that function looks in a few different places. The "Migrating" guide has no information on how to replace the use of this function, or really anything that's currently in the v1 defaults package.

**Comment by kevinburkemeter** [comment]
A naive person attempting to replace c

**Comment by kevinburkemeter** [comment]
I didn't mean to close this, sorry, reopening.

**Comment by kevinburkemeter** [comment]
Hi, I see you're shipping lots of new features, we'd love to use them but we're still sort of blocked on being able to upgrade our AWS SDK until there are better instructions available for migrating from V1.
