### ISSUE TITLE
ec2rolecreds documentation contains references to "imds"

### ISSUE THREAD

**Issue by kevinburke1** [aws/aws-sdk-go-v2#1217]
The "Migrating" doc asks me to look at ec2rolecreds to replace the v1 ec2rolecreds. I was previously using the defaults.RemoteCredProvider, which there is no documentation for. I took a stab and guessed that the RemoteCredProvider was using ec2rolecreds, so started trying to read the documentation for ec2rolecreds.

See for example https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials@v1.1.4/ec2rolecreds#New. None of the code samples in the package documentation reference "ec2rolecreds"; all of them reference some package named "imds". I have no idea what imds is.

**Comment by skmcgrail** [comment]
The documentation can certainly be cleaned up to make this more clear, the `imds` package being referred by this code is found in this module https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/ec2/imds
