### ISSUE TITLE
pinpoint.SMSMessage struct is missing OriginationNumber

### ISSUE THREAD

**Issue by lukec** [aws/aws-sdk-go-v2#122]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

latest

### Version of Go (`go version`)?

n/a

### What issue did you see?

The pinpoint.SMSMessage struct does not match the REST API docs:
https://docs.aws.amazon.com/pinpoint/latest/apireference/rest-api-messages.html#rest-api-messages-attributes-smsmessage-table

Specifically, OriginationNumber is not present.

### Steps to reproduce

I should be able to set the pinpoint.SMSMessage.OriginationNumber to a *string.

I'm not sure if this is something that is very quick to fix for a core project developer, or if I should be learning this project and submitting a pull request.

Please advise.

**Comment by xibz** [comment]
Hello @lukec, thank you for reaching out to us. There are two issues here. The first one being that this SDK may not have the most up to date models. However, it looks like V1 also does not have this field. I would reach out to the service team and see why this hasn't been released in the SDKs yet. Please contact them [here](https://forums.aws.amazon.com/forum.jspa?forumID=225).

**Comment by lukec** [comment]
I have created a thread in that forum: https://forums.aws.amazon.com/thread.jspa?threadID=273900

**Comment by jasdel** [comment]
Thanks for the update @lukec, I'm going to go ahead and close this issue since the forum will be the best place to voice this issue. Let us know if you have additional issues, or feedback.

**Comment by lukec** [comment]
Wait! This is still very much an issue! Is it necessary to close it?

I have heard nothing from the forum. :(

I am reaching out to other contacts to try to get the SDK updated.  As soon as I make any progress on that, I will be here again to move this forward.

**Comment by jasdel** [comment]
Thanks for the clarification @lukec. I've reached out to the service also asking why the OriginationNumber field isn't included in the service's API in the SDKs. Hopefully this will help the Pinpoint service team see the issue with their API. Once the service releases support for this parameter the AWS SDKs will automatically pick it up.

The SDKs are based on models provided by the services. In this case it looks like the service has not modeled this API parameter. This probably means they accidentally left out that parameter in their model, or incorrectly documented support for that parameter in the documentation. The service will need to provide the SDKs with the model for this parameter before the SDKs are able to support it.

**Comment by lukec** [comment]
@jasdel I believe the SDKs have been updated by the service team.  What needs to happen to update this library?

**Comment by jasdel** [comment]
Hi @lukec thanks for the update, i'm not finding any update for this service. Do you have to link another SDK has been updated for this operation?

**Comment by lukec** [comment]
Hi sorry for jumping the gun. I heard that it got updated last night, for real this time.

**Comment by jasdel** [comment]
Hi @lukec sorry for the delay, this feature was just [released today](https://github.com/aws/aws-sdk-go/blob/v1.13.15/service/pinpoint/api.go#L14481-L14501) in our v1 SDK's model, I'll pull over the model for the v2 SDK.

**Comment by jasdel** [comment]
@lukec #151 will bring the V2 SDK up to date with v1, adding support for the missing pinpoint fields.

**Comment by lukec** [comment]
![high five](http://gifs.luk.ec/high-five/it-crowd-high-five.gif)
