### ISSUE TITLE
Replacement for ecs.WaitUntilServicesStable

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-go-v2#1220]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

Migrating a project from v0.24.0 → v1.3.2. For ECS, there were 4 waiters (services running/stopped, tasks running/stopped), but the latest release only has 3 of those waiters. The one missing is for services running.

Here is the doc link for the waiter that no longer exists: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecs@v0.24.0#Client.WaitUntilServicesStable

**Version of AWS SDK for Go?**

```bash
$ cat go.mod | grep "github.com/aws"
	github.com/aws/aws-sdk-go-v2 v1.3.2
	github.com/aws/aws-sdk-go-v2/config v1.1.5
	github.com/aws/aws-sdk-go-v2/credentials v1.1.5
	github.com/aws/aws-sdk-go-v2/service/ecs v1.2.2
	github.com/aws/aws-sdk-go-v2/service/sts v1.2.2
```

**Version of Go (`go version`)?**

```bash
$ go version
go version go1.16.2 darwin/amd64
```

**Additional context:**

It's the same as this in the AWS CLI v2:

```bash
aws ecs wait services-stable --cluster {cluster} --services {list-of-services}
```

**Comment by skyzyx** [comment]
Ping. Just a friendly 7½ month check-in.

**Comment by RanVaknin** [comment]
Hi @skyzyx , Im so sorry for the late reply. 

I see that ecs client version 1.18.9 has that waiter added back.

Closing the issue. If you need any future help please @ me and I'll do my best to respond in a timely manner.

Thank you!
Ran~
