### ISSUE TITLE
AWS SSO Login through SDK - Lack of documentation

### ISSUE THREAD

**Issue by vishaltak** [aws/aws-sdk-go-v2#1222]
**Describe the issue with documentation**
Currently, all documentations and blogs describe the aws sso login process as - 

1. Setup config manually - start url, role name, etc
2. Use AWS CLI to perform login using AWS SSO
3. Load SSO Credentials in Go SDK

https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/
https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#aws-single-sign-on-credentials
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials@v1.1.5/ssocreds

The Go SDK also lacks examples to perform a login purely through the SDK.
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssooidc
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sso

There is no blog, article, documentation on how to trigger the login flow, what are the acceptable values for certain parameters like `Scopes` in `ssooidc.RegisterClientInput` or `GrantType` in `ssooidc.CreateTokenInput`. The usage of 2 services `ssooidc` and `sso` to actually get the access keys further complicates it without any example.

**Expected behavior**
An example should be documented and the sdk docs should be improved to add more description about the possible values for a field.

**Additional context**
After having spent a day to try to login purely through Go SDK, I've managed to get this working and would like to add it to the repository for other people to refer and use. I would like to know if the owners would like this to be added to the go package as example file. If yes, I would appreciate some guidance on where should I be making changes in the repo as this involves 2 services (sso and ssooidc).

The below links were useful for me while figuring things out - 

https://github.com/aws/aws-sdk-ruby/issues/2196
https://github.com/boto/botocore/pull/1878/files#diff-d5dc8bb337890042943977b62e8bb2e7db71415d35bb17a41ad4bf4780fb3617R1396

**Things to further add in the example script**

1. Export the credentials to aws credentials file as profile
2. Connect to a service by loading the above exported profile

**Actual Script**

Usage
`go run ./sso-login.go --account-id "123" --role-name "abc" --start-url "https://XXX.awsapps.com/start"`

```
package main

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/sso"
	"github.com/aws/aws-sdk-go-v2/service/ssooidc"
	"github.com/pkg/browser"
)

var (
	startURL  string
	accountID string
	roleName  string
)

func main() {
	flag.StringVar(&startURL, "start-url", "", "AWS SSO Start URL")
	flag.StringVar(&accountID, "account-id", "", "AWS Account ID to fetch credentials for")
	flag.StringVar(&roleName, "role-name", "", "Role Name to assume while fetching credentials")
	flag.Parse()
	if startURL == "" || accountID == "" || roleName == "" {
		flag.Usage()
		os.Exit(1)
	}
	// load default aws config
	cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		fmt.Println(err)
	}
	// create sso oidc client to trigger login flow
	ssooidcClient := ssooidc.NewFromConfig(cfg)
	if err != nil {
		fmt.Println(err)
	}
	// register your client which is triggering the login flow
	register, err := ssooidcClient.RegisterClient(context.TODO(), &ssooidc.RegisterClientInput{
		ClientName: aws.String("sample-client-name"),
		ClientType: aws.String("public"),
		Scopes:     []string{"sso-portal:*"},
	})
	if err != nil {
		fmt.Println(err)
	}
	// authorize your device using the client registration response
	deviceAuth, err := ssooidcClient.StartDeviceAuthorization(context.TODO(), &ssooidc.StartDeviceAuthorizationInput{
		ClientId:     register.ClientId,
		ClientSecret: register.ClientSecret,
		StartUrl:     aws.String(startURL),
	})
	if err != nil {
		fmt.Println(err)
	}
	// trigger OIDC login. open browser to login. close tab once login is done. press enter to continue
	url := aws.ToString(deviceAuth.VerificationUriComplete)
	fmt.Printf("If browser is not opened automatically, please open link:\n%v\n", url)
	err = browser.OpenURL(url)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("Press ENTER key once login is done")
	_ = bufio.NewScanner(os.Stdin).Scan()
	// generate sso token
	token, err := ssooidcClient.CreateToken(context.TODO(), &ssooidc.CreateTokenInput{
		ClientId:     register.ClientId,
		ClientSecret: register.ClientSecret,
		DeviceCode:   deviceAuth.DeviceCode,
		GrantType:    aws.String("urn:ietf:params:oauth:grant-type:device_code"),
	})
	if err != nil {
		fmt.Println(err)
	}
	// create sso client
	ssoClient := sso.NewFromConfig(cfg)
	// list accounts [ONLY provided for better example coverage]
	fmt.Println("Fetching list of all accounts for user\n")
	accountPaginator := sso.NewListAccountsPaginator(ssoClient, &sso.ListAccountsInput{
		AccessToken: token.AccessToken,
	})
	for accountPaginator.HasMorePages() {
		x, err := accountPaginator.NextPage(context.TODO())
		if err != nil {
			fmt.Println(err)
		}
		for _, y := range x.AccountList {
			fmt.Println("-------------------------------------------------------")
			fmt.Printf("\nAccount ID: %v Name: %v Email: %v\n", aws.ToString(y.AccountId), aws.ToString(y.AccountName), aws.ToString(y.EmailAddress))

			// list roles for a given account [ONLY provided for better example coverage]
			fmt.Printf("\n\nFetching roles of account %v for user\n", aws.ToString(y.AccountId))
			rolePaginator := sso.NewListAccountRolesPaginator(ssoClient, &sso.ListAccountRolesInput{
				AccessToken: token.AccessToken,
				AccountId:   y.AccountId,
			})
			for rolePaginator.HasMorePages() {
				z, err := rolePaginator.NextPage(context.TODO())
				if err != nil {
					fmt.Println(err)
				}
				for _, p := range z.RoleList {
					fmt.Printf("Account ID: %v Role Name: %v\n", aws.ToString(p.AccountId), aws.ToString(p.RoleName))
				}
			}

		}
	}
	fmt.Println("-------------------------------------------------------")
	// exchange token received during oidc flow to fetch actual aws access keys
	fmt.Printf("\n\nFetching credentails for role %v of account %v for user\n", roleName, accountID)
	credentials, err := ssoClient.GetRoleCredentials(context.TODO(), &sso.GetRoleCredentialsInput{
		AccessToken: token.AccessToken,
		AccountId:   aws.String(accountID),
		RoleName:    aws.String(roleName),
	})
	if err != nil {
		fmt.Println(err)
	}
	// printing access key to show how they are accessed
	fmt.Printf("\n\nPriting aws access keysz")
	fmt.Println("Access key id: ", aws.ToString(credentials.RoleCredentials.AccessKeyId))
	fmt.Println("Secret access key: ", aws.ToString(credentials.RoleCredentials.SecretAccessKey))
	fmt.Println("Expiration: ", aws.ToInt64(&credentials.RoleCredentials.Expiration))
	fmt.Println("Session token: ", aws.ToString(credentials.RoleCredentials.SessionToken))
}
```

**Comment by Sonlis** [comment]
When running this code, I land on the page where you have to authorize the access. But when pressing `Allow`, I get this error: 
```
invalid_grant

Invalid grant provided
```
Any idea why?

**Comment by eberkund** [comment]
Is there some documentation on the file structure of the `~/.aws` directory if I wanted to cache the credentials to disk the same way the CLI does it?

**Comment by johnjeffers** [comment]
I'll second the request for better (or any) documentation for doing SSO stuff with the v2 SDK. Right now I'm just using `os/exec` to run the `aws sso login` command, which is clunky, but it works.

```
import (
	"os"
	"os/exec"
)

func PerformSSOLogin(profile string, homeDir string) error {
	// Verify that the "aws" command is installed.
	_, err := exec.LookPath("aws")
	if err != nil {
		return err
	}

	shellcmd := exec.Command("aws", "sso", "login", "--profile", profile)
	shellcmd.Stdout = os.Stdout

	if err := shellcmd.Run(); err != nil {
		return err
	}

	return nil
}
```

**Comment by aajtodd** [comment]
NOTE: if you follow the CLI (or manually edit your profile) to use the [updated profile configuration ](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html) to make use of a token provider the SDK will handle token refresh on your behalf. 

e.g.

```ini
[profile my-dev-profile]
sso_session = my-sso
sso_account_id = 123456789011
sso_role_name = readOnly
region = us-west-2
output = json

[sso-session my-sso]
sso_region = us-east-1
sso_start_url = https://my-sso-portal.awsapps.com/start
# NOTE: registration_scopes is required for ssooidc to return a refresh token
sso_registration_scopes = sso:account:access

```
This allows you to login once with the CLI and then the SDK will handle refreshing tokens.

-----

Implementing the equivalent OIDC login flow as the CLI (e.g. `aws --profile my-dev-profile sso login`) or as documented in the ticket description is probably beyond the scope of the developer guide. 

I agree that the developer guide needs updated to make use of the `sso-session` based configuration file format though so we'll take a look at that.

**Comment by aajtodd** [comment]
closing this as we've updated the developer guide and `ssocreds` package documentation.

**Comment by PeterSchuhmannNetflow** [comment]
since this comments really helped a lot with my sso implementation i wanted to share my final implementation. It might not be the best code but since the code above is good for a start but not for a full service access someone might find the missing parts here. It also includes storing the credentials in ~/.aws/nfdev and checking if the loaded credentials are still valid. If not a prompt to open the browser to reauthenticate will appear. 

Please keep in mind that we are using a shared config with a custom sso url and role thats why there is a check for that. 

`package aws

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/sso"
	"github.com/aws/aws-sdk-go-v2/service/ssooidc"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"github.com/pkg/browser"
)

func GetConfig(debug bool) (*aws.Config, error) {

	cfg, err := config.LoadDefaultConfig(
		context.TODO(),
		config.WithSharedConfigProfile("nfdev"),
	)
	if err != nil {
		return nil, err
	}

	sharedConfig := getSharedConfig(&cfg)
	validateSharedConfig(sharedConfig)

	reauthenticate := false

	staticCredentials, err := loadExistingCredentials()
	if err != nil {
		reauthenticate = true
	}

	if !reauthenticate {
		credsProvider := credentials.StaticCredentialsProvider{
			Value: staticCredentials,
		}

		cfg.Credentials = credsProvider

		if !checkExistingCredentials(&cfg) {
			reauthenticate = true
		}
	}

	if reauthenticate {
		err = reloginWorkflow(&cfg, debug)
		if err != nil {
			fmt.Println(err)
			os.Exit(1)
		}
	}

	return &cfg, nil

}

func checkExistingCredentials(cfg *aws.Config) bool {
	client := sts.NewFromConfig(*cfg)

	_, err := client.GetCallerIdentity(
		context.TODO(),
		&sts.GetCallerIdentityInput{},
	)
	if err != nil {
		return false
	}

	return true
}

func loadExistingCredentials() (aws.Credentials, error) {
	var staticCredentials aws.Credentials

	dirname, err := os.UserHomeDir()
	if err != nil {
		log.Fatal(err)
	}

	credentialsRaw, err := os.ReadFile(dirname + "/.aws/nfdev")
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return staticCredentials, err
		} else {
			log.Fatal(err)
			return staticCredentials, err
		}
	} else {
		err = json.Unmarshal(credentialsRaw, &staticCredentials)
		return staticCredentials, err
	}
}

func getSharedConfig(cfg *aws.Config) (sharedConfig config.SharedConfig) {
	cfgSources := cfg.ConfigSources
	for _, cfgSource := range cfgSources {
		foundSharedConfig, ok := cfgSource.(config.SharedConfig)
		if ok {
			sharedConfig = foundSharedConfig
		}
	}

	return sharedConfig
}

func validateSharedConfig(sharedConfig config.SharedConfig) {
	if sharedConfig.SSOStartURL == "" {
		fmt.Println("ERROR: SSOStartURL not found or empty")
		os.Exit(1)
	}

	if sharedConfig.SSOAccountID == "" {
		fmt.Println("ERROR: SSOAccountID not found or empty")
		os.Exit(1)
	}

	if sharedConfig.SSORoleName == "" {
		fmt.Println("ERROR: SSORoleName not found or empty")
		os.Exit(1)
	}
}

func reloginWorkflow(cfg *aws.Config, debug bool) error {
	// create sso oidc client to trigger login flow
	ssooidcClient := ssooidc.NewFromConfig(*cfg)

	// register your client which is triggering the login flow
	register, err := ssooidcClient.RegisterClient(context.TODO(), &ssooidc.RegisterClientInput{
		ClientName: aws.String("sample-client-name"),
		ClientType: aws.String("public"),
		Scopes:     []string{"sso-portal:*"},
	})
	if err != nil {
		return err
	}

	sharedConfig := getSharedConfig(cfg)

	// authorize your device using the client registration response
	deviceAuth, err := ssooidcClient.StartDeviceAuthorization(context.TODO(), &ssooidc.StartDeviceAuthorizationInput{
		ClientId:     register.ClientId,
		ClientSecret: register.ClientSecret,
		StartUrl:     &sharedConfig.SSOStartURL,
	})
	if err != nil {
		return err
	}
	// trigger OIDC login. open browser to login. close tab once login is done. press enter to continue
	url := aws.ToString(deviceAuth.VerificationUriComplete)
	fmt.Printf("If browser is not opened automatically, please open link:\n%v\n", url)
	err = browser.OpenURL(url)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Println("Press ENTER key once login is done")
	_ = bufio.NewScanner(os.Stdin).Scan()
	// generate sso token
	token, err := ssooidcClient.CreateToken(context.TODO(), &ssooidc.CreateTokenInput{
		ClientId:     register.ClientId,
		ClientSecret: register.ClientSecret,
		DeviceCode:   deviceAuth.DeviceCode,
		GrantType:    aws.String("urn:ietf:params:oauth:grant-type:device_code"),
	})
	if err != nil {
		return err
	}
	// create sso client
	ssoClient := sso.NewFromConfig(*cfg)

	// exchange token received during oidc flow to fetch actual aws access keys
	creds, err := ssoClient.GetRoleCredentials(context.TODO(), &sso.GetRoleCredentialsInput{
		AccessToken: token.AccessToken,
		AccountId:   &sharedConfig.SSOAccountID,
		RoleName:    &sharedConfig.SSORoleName,
	})
	if err != nil {
		return err
	}

	if debug {
		// printing access key to show how they are accessed
		fmt.Printf("\n\nPriting aws access keysz")
		fmt.Println("Access key id: ", aws.ToString(creds.RoleCredentials.AccessKeyId))
		fmt.Println("Secret access key: ", aws.ToString(creds.RoleCredentials.SecretAccessKey))
		fmt.Println("Expiration: ", aws.ToInt64(&creds.RoleCredentials.Expiration))
		fmt.Println("Session token: ", aws.ToString(creds.RoleCredentials.SessionToken))
		fmt.Printf("\n----------------------------------------------\n\n")
	}

	staticCredentials := aws.Credentials{
		AccessKeyID:     aws.ToString(creds.RoleCredentials.AccessKeyId),
		SecretAccessKey: aws.ToString(creds.RoleCredentials.SecretAccessKey),
		SessionToken:    aws.ToString(creds.RoleCredentials.SessionToken),
		Expires:         time.UnixMilli(aws.ToInt64(&creds.RoleCredentials.Expiration)),
		CanExpire:       true,
	}

	u, err := json.Marshal(staticCredentials)
	if err != nil {
		return err
	}

	dirname, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	err = os.WriteFile(dirname+"/.aws/nfdev", u, 775)
	if err != nil {
		return err
	}

	credsProvider := credentials.StaticCredentialsProvider{
		Value: staticCredentials,
	}

	cfg.Credentials = credsProvider

	return nil
}
`

using this config you can access every service like this:

`
	cfg, err := GetConfig(debug)
	if err != nil {
		return serviceNames, err
	}

	svc := ecs.NewFromConfig(*cfg)
	input := &ecs.ListServicesInput{
		Cluster:    aws.String("Dev"),
		MaxResults: aws.Int32(100),
	}
`

**Comment by peterHoburg** [comment]
> since this comments really helped a lot with my sso implementation i wanted to share my final implementation. It might not be the best code but since the code above is good for a start but not for a full service access someone might find the missing parts here. It also includes storing the credentials in ~/.aws/nfdev and checking if the loaded credentials are still valid. If not a prompt to open the browser to reauthenticate will appear...

I created [this package](https://pkg.go.dev/github.com/peterHoburg/aws-sdk-go-v2-sso-login) to solve this problem for my org. Hopefully, this helps other people out! I know it won't work for everyone, but I am happy to add/change things. Just open a PR/issue.
