### ISSUE TITLE
Slower S3 uploads compared to AWS CLI?

### ISSUE THREAD

**Issue by jviney** [aws/aws-sdk-go-v2#1228]
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

We have a small utility that includes an S3 file upload as one of its functions. Occasionally we find that the upload rate is very slow. During these times, the speed is normal if we perform the upload with the AWS CLI tool (`aws s3 cp file.mp4 s3://my-bucket/file.mp4`).

I saw from `iftop` that the S3 upload destination is different for the two approaches. The Go SDK uploads to `s3-us-west-2-r-w.amazonaws.com`, while the AWS CLI tool uploads to `s3-us-west-2.amazonaws.com`. This seems to be a consistent difference.

Is it possible to use `s3-us-west-2.amazonaws.com` as the S3 upload destination with the SDK? Could there be some other cause for the speed difference?

We are using the `s3manager.Uploader` to perform the upload, with the default concurrency of 5.

**Comment by domino14** [comment]
I have seen very very slow uploads as well, even for tiny files (~10K). I am uploading from within an ECS container. I'm also using `s3manager.Uploader`. Have you found any hints as to what may be happening?

When I upload to the same endpoint from my home computer it is much faster, even though the s3 servers are presumably much further away, and I also get much faster uploads with `aws s3 cp`.

**Comment by jviney** [comment]
No I haven't found the solution yet. Adjusting the concurrency of `s3Manager.Uploader` can improve the situation a bit, but it doesn't make it equivalent to using the CLI. You can still see with `iftop` that the speed of each connection with the SDK is still a lot slower that with the CLI.

I'd like to try uploading to `s3-us-west-2.amazonaws.com` with the SDK - but haven't determined how to achieve thath yet.

**Comment by domino14** [comment]
@jviney are you using ECS by any chance? Where is your code running?

**Comment by jviney** [comment]
> @jviney are you using ECS by any chance? Where is your code running?

No ECS. All the uploads happen from outside AWS on residential/business internet connections. The only region I'm using is us-west-2.

Code runs bare-metal on various Ubuntu flavours (16.04, 18.04, 20.04).

**Comment by KaibaLopez** [comment]
Hi @jviney ,
Sorry for the delayed response, its hard to say what can be done from the info given and this is not really something I can consistently test... 
Also, when you say

> I'd like to try uploading to s3-us-west-2.amazonaws.com with the SDK - but haven't determined how to achieve that yet.

Depending on what you mean by that you can, change your client config, the bucket config or override the s3 endpoint. If you can show me some sample code of how you're doing the upload then I can help more.
