### ISSUE TITLE
Consider putting setters on requests

### ISSUE THREAD

**Issue by j7b** [aws/aws-sdk-go-v2#123]
I read https://github.com/aws/aws-sdk-go-v2/issues/81 after it was closed, personally I never used setters because they didn't save any typing, but they could save a lot with svc returning requests:
```
req := svc.DescribeTableRequest(&dynamodb.DescribeTableInput{
		TableName: aws.String("myTable"),
	})
res, err := req.Send()
```
can become
```res,err := svc.DescribeTableRequest(nil).SetTableName("myTable").Send()```

**Comment by xibz** [comment]
Hello @j7b, thank you for reaching out to us. You can call send in the inline structure example. 
```go
res, err := svc.DescribeTableRequest(&dynamodb.DescribeTableInput{TableName:aws.String("myTable")}).Send()
```

You could break that struct initializing in multiple lines as you would probably do the same with setters. I really don't think the setters bring too much value and additionally clutter the docs. With the example above, does that give you same easy usage?

**Comment by j7b** [comment]
My concern is mostly reducing typing (savings is about 30% for this example), not formatting.

**Comment by xibz** [comment]
@j7b - The main issue here is that it is not idiomatic to Go with the addition of cluttering the docs. With the doc cluttering being the main reason for removal. However, I will keep this issue open. If we get more feedback that we should put them back in, then that's something we can do.
