### ISSUE TITLE
SubscribeToShard method for Kinesis client / consumer.

### ISSUE THREAD

**Issue by mingrammer** [aws/aws-sdk-go-v2#1234]
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

Hi. I want to consume the events from Kinesis streams. By the comment documentation,

```
// Registers a consumer with a Kinesis data stream. When you use this operation,
// the consumer you register can then call SubscribeToShard to receive data from
// the stream using enhanced fan-out, at a rate of up to 2 MiB per second for every
```

So, I was trying to find the `SubscribeToShard` method on the service/kinesis module (both Client, Consumer don't have this method), but I found nothing about it. This method is missing in v2? (there is `SubscribeToShard` operator in the v1 package: https://docs.aws.amazon.com/sdk-for-go/api/service/kinesis/#Kinesis.SubscribeToShard)

**Comment by KaibaLopez** [comment]
Hi @mingrammer ,
Sorry for the delayed response, and yea that operation is dependent on HTTP/2 and _for now_ that isn't supported for the SDK's V2. 
So yea, the best I can recommend is using the V1 for this kind of operations.

**Comment by mingrammer** [comment]
Thanks for the reply!

**Comment by skmcgrail** [comment]
This is now available as of 2021-11-06 release. https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-11-06
