### ISSUE TITLE
Repository details section: minor improvements

### ISSUE THREAD

**Issue by deining** [aws/aws-sdk-go-v2#1237]
In the repository details presented in the top right section of the page I would propose a few minor changes:
- add V2 to project description
- add a URL to the existing project website
- add a few keywords.

Afterwards the section should look like the screenshot given below:   

<img src="https://user-images.githubusercontent.com/18169566/115781154-4c0b8500-a3ba-11eb-8697-feb6b70ab833.png" alt="alt text" width="500px">

**Comment by KaibaLopez** [comment]
Hi @deining ,
Sorry for the delayed response, and thanks for pointing that out.
Yea I'll look into it so that it matches the other SDK's but for now I'll add the keywords at least.
