### ISSUE TITLE
SlowDown: Please reduce your request rate.

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#124]
I'm doing http fetches from S3, but I am hitting **SlowDown: Please reduce your request rate.**

Can I use the SDK to perform unauthenticated fetch requests from S3 I wonder? That are able to backoff automatically to meet the API rate limits?

**Comment by xibz** [comment]
Hello @kaihendry, thank you for reaching out to us. Yes, you can use the `aws.AnonymousCredentials` for unauthenticated requests. Please let us know if that helps.

**Comment by xibz** [comment]
@kaihendry - Depends on what they return. I am assuming they are returning a 5xx exception. What does the response look like?

It is probably best to use `s3manager` for a lot of downloads.

**Comment by kaihendry** [comment]
Yes, a 503.  Ok, I'll have to give s3manager a whirl.

**Comment by jasdel** [comment]
Hi @kaihendry let us know if you're still running into this issue or have additional questions.
