### ISSUE TITLE
accessanalyzer - region not being read?

### ISSUE THREAD

**Issue by akingscote** [aws/aws-sdk-go-v2#1260]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I cannot figure out how to use the `DeleteAnalyzer` action and am leaning towards the issue being a bug.
Ive dont have any problem using the SDK for other resources.

It seems that the region is never passed to the functions so errors out. Ive set it in numerous places, as well as the `AWS_REGION` and `AWS_DEFAULT_REGION` variables.

**Version of AWS SDK for Go?**
Example: v1.29.22
`1.5.0`
**Version of Go (`go version`)?**
`go version go1.16.3 linux/amd64`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```
        name := "myanalyzer"
	cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithSharedConfigProfile(profile),
		config.WithRegion("eu-west-1"),
	)

	if err != nil {
		log.Fatalln("Error loading configuration", err)
	}
        resolver := accessanalyzer.NewDefaultEndpointResolver()

	client := accessanalyzer.NewFromConfig(cfg, func(o *accessanalyzer.Options) {
		o.Region = "eu-west-1"
		o.EndpointOptions = options
		o.EndpointResolver = resolver
	})

	input := &accessanalyzer.DeleteAnalyzerInput{
		AnalyzerName: &name,
	}
	
	result, err := client.DeleteAnalyzer(context.TODO(), input)
```
Results in the following error:
```
failed to call service: AccessAnalyzer, operation: DeleteAnalyzer, error: failed to resolve service endpoint, an AWS region is required, but was not found 
```
Similarly if i dont provide the resolver, i get a similar error.
If i add a resolver URL...

Trying some other stuff...
```
        name := "myanalyzer"
	cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithSharedConfigProfile(profile),
		config.WithRegion("eu-west-1"),
	)

	if err != nil {
		log.Fatalln("Error loading configuration", err)
	}
        resolver := accessanalyzer.EndpointResolverFromURL("https://access-analyzer.eu-west-1.amazonaws.com")

	client := accessanalyzer.NewFromConfig(cfg, func(o *accessanalyzer.Options) {
		o.Region = "eu-west-1"
		o.EndpointOptions = options
		o.EndpointResolver = resolver
	})

	input := &accessanalyzer.DeleteAnalyzerInput{
		AnalyzerName: &name,
	}
	
	result, err := client.DeleteAnalyzer(context.TODO(), input)
```
Which returns the following error:
```
requestID: 85f3d4ca-dc1b-43a4-9272-a05adea0f9d7, error: api error InvalidSignatureException: Credential should be scoped to a valid region, not ''.  
```
```
failed to call service: AccessAnalyzer, operation: DeleteAnalyzer, error: https response error StatusCode: 403, RequestID: 85f3d4ca-dc1b-43a4-9272-a05adea0f9d7, api error InvalidSignatureException: Credential should be scoped to a valid region, not ''.  
```

Ive tried a load of different things but cannot for the life of me delete an access analyzer.
Please provide some insight into what im missing here. The documentation is lacking any examples and I couldnt see any unit tests to reverse engineer.

**Expected behavior**
Id expect the access analyzer to be deleted.

**Comment by roneli** [comment]
I hit the same problem with list analyzers, seems like the region isn't added to the stack i.e in the InvokeOperation in access analyzer functions for example List Analyzer is missing this middleware to be added: 

`func newServiceMetadataMiddleware_opListAnalyzers(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		SigningName:   "access-analyzer",
		OperationName: "ListAnalyzers",
	}
}
`
and then added to the  stack middleware functions

**Comment by skmcgrail** [comment]
Re-opning this until we cut a new release with the merged fix.

**Comment by Skarlso** [comment]
Can I ask when this will be fixed please? This is quite serious as in blocking me from using v2 completely. :/

**Comment by jasdel** [comment]
This issue should be fixed now, and you can updater to the latest version of the SDK to get the correct behavior. Please reopen if this issue if you're still having issues.
