### ISSUE TITLE
SDK Retrier does not distinguish between service and resource throttling

### ISSUE THREAD

**Issue by yevgenypats** [aws/aws-sdk-go-v2#1268]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
AWS SDK is described as go-routine safe and mostly it's true as for each action all the options are copied ([example](https://github.com/aws/aws-sdk-go-v2/blob/main/service/autoscaling/api_client.go#L121)).

One place that doesn't work as expected is the retrier because once you create a new service via `NewFromConfig` function it [resolves](https://github.com/aws/aws-sdk-go-v2/blob/main/service/autoscaling/api_client.go#L171) the function resolver (i.e the client now just points to a modifiable Retryer object instead of a function).

What happens if we use the service in multiple go-routines accessing different api calls or even the same api call in different regions all those calls will share the same retrier even though [throttling](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html) is per region and sometimes even per api call per region. 

**Version of AWS SDK for Go?**
 v1.5.0

**Version of Go (`go version`)?**
1.16

**Expected behavior**
I'd expect to have a fresh retrier for every invoke operation.

**Comment by jasdel** [comment]
Thanks for reaching out @yevgenypats, and taking the time to create a PR for this feature. The behavior that you're experiencing with the retryer being shared across API operation calls of the same API client instance is the intended behavior. 

Then API clients are safe to use concurrently, but the API client will share some state such as retry behavior across the operation calls.

The reasoning behind this design is that errors returned by a service can include both throttling for the service or per resource. Sharing retryer across all operations of a service, ensures that the any temporary outages or service wide resources. With that said the SDK does not have the information to distinguish the difference between service wide throttling and resource specific throttling.

**Comment by yevgenypats** [comment]
Sorry for opening / reopening - I thought I got it but I wanted to follow-up with another question. 

If the SDK doesn't have a way of distinguishing between service wide throttle, region or resource specific then it basically means the best thing would be to create a client per api per region ?

**Comment by yevgenypats** [comment]
Seems we uncovered what was the issue it was client side throttling via bucket algorithm
