### ISSUE TITLE
SES Example: How to send an email with a replyTo address?

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#127]
Sorry this is a usability issue in the example. Not sure where to file it.

https://godoc.org/github.com/aws/aws-sdk-go-v2/service/ses#example-SES-SendEmailRequest-Shared00

It's not clear how to set a field like **replyTo**. I understand the notion of source, but can't a From also be defined that needn't be verified?

**Comment by Doug-AWS** [comment]
I would start with the existing example in the developer guide, https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/ses-example-send-email.html. Then look up the input for the SendEmail method, https://docs.aws.amazon.com/sdk-for-go/api/service/ses/#SendEmailInput, which tells you the input takes a string array for the ReplyToAddresses member. So you need to add something like the following to the existing example:

    ReplyToAddresses: []*string{
        aws.String(ADDRESS),
    },

**Comment by kaihendry** [comment]
Thank, though from a Dev UX POV, I want the example upon https://godoc.org/github.com/aws/aws-sdk-go-v2/service/ses#example-SES-SendEmailRequest-Shared00 to be sane and useful.

Everytime I have a bunch of tabs open to understand one API, it's really quite frustrating. 

Why isn't the struct full for example?

**Comment by xibz** [comment]
@kaihendry - Most of the examples highlight common use cases that users may run into. What issues are you running into that isn't intuitive to use?

**Comment by kaihendry** [comment]
Use case of setting a From address? or Reply-To?
