### ISSUE TITLE
context cancellation semantics, errors, etc..., are incomplete

### ISSUE THREAD

**Issue by necro351** [aws/aws-sdk-go-v2#1272]
**Describe the issue with documentation**
The documentation does not describe how to use contexts with the API. When an API call is interrupted because the caller cancels the context the documentation does not describe which error is returned. The documentation does not describe whether the error is only returned IFF the context which was passed in returns non-nil if you call its Err() method.

**To Reproduce (observed behavior)**
Google search context canceled error with golang sdk v2 and read through sdk's docs and find no information on the topic.

**Expected behavior**
Should find example code showing how to check if an API call failed because its context was canceled. Should find clear rules about the relationship between the `ctx` which was passed in and the error returned by the API, e.g., ctx.Err() != nil IFF the API returns an error that wraps smithy.CanceledError.

**Screenshots**

**Additional context**

**Comment by KaibaLopez** [comment]
Hmmm yea I think this is a reasonable ask, we'll look into adding to our documentation.

**Comment by yerke** [comment]
I think this is still a problem. Is it possible to address it please?

**Comment by RanVaknin** [comment]
Hi there,

We have a section in our developer guide about timeouts and context. https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/#timeouts

Since context is a general and broad Golang concept and not SDK specific Im going to close this issue.

Thanks,
Ran~
