### ISSUE TITLE
stscreds/assume_role_provider usage documentation is incorrect

### ISSUE THREAD

**Issue by brodie-slater** [aws/aws-sdk-go-v2#1273]
**Describe the issue with documentation**
When using the `stscreds.NewAssumeRoleProvider` for the first time, I looked at the examples in the source code which, at time of writing shows:
```go
cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Fatal(err)
	}

stsSvc := sts.NewFromConfig(cfg)
creds := stscreds.NewAssumeRoleProvider(stsSvc, "myRoleArn")

cfg.Credentials = &aws.CredentialsCache{Provider: creds}
}
```

The issue is that, using `cfg.Credentials = &aws.CredentialsCache{Provider: creds}` doesn't compile. `aws.CredentialsCache` doesn't export the field `Provider`. If it once did, it is now a private field used by `aws.NewCredentialsCache`.

**To Reproduce (observed behavior)**
Follow the example code in the source file [here](https://github.com/aws/aws-sdk-go-v2/blob/36390a5d91d4e724cbed82fad2646dfe63487e3c/credentials/stscreds/assume_role_provider.go#L13)

**Expected behavior**
A working example of how to use `stscreds.NewAssumeRoleProvider`

**Additional information**
I was able to get my program  working with:
```go
cfg, err := config.LoadDefaultConfig(context.TODO())
if err != nil {
	log.Fatal(err)
}

stsSvc := sts.NewFromConfig(cfg)
creds := stscreds.NewAssumeRoleProvider(stsSvc, "myRoleArn")

cfg.Credentials = creds << assigning creds directly
```

I didn't want to raise a PR suggesting this as a fix because I'm not sure if this is the best way to do it, or if it's better to use a `CredentialsCache` in some way.

Sorry if this sounds nitpicky. Thanks for all the work on this SDK, I love using it ❤️

**Comment by skmcgrail** [comment]
Thank you for bringing this to our attention @brodie-slater, this is an example we missed updating before we released the SDK for general availability. We will put together a PR to get this example fixed up.
