### ISSUE TITLE
GeneratePresignedURLv2

### ISSUE THREAD

**Issue by zhangchao6018** [aws/aws-sdk-go-v2#1284]
Hi body

I want to get URL access resources from S3

Through the example code, generated URL, found no access rights

Want to know if the URL signature is wrong

If yes, does the signature need to be obtained dynamically?

How to solve it

**Comment by KaibaLopez** [comment]
Hi @zhangchao6018,
So this might be related permissions on your s3 bucket or lists, see here for more [details on presigning urls](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html).
Also, could you link me to the sample you are using?
