### ISSUE TITLE
README badges are not searchable with ctrl + F

### ISSUE THREAD

**Issue by rittneje** [aws/aws-sdk-go-v2#1293]
If I do ctrl + F on the landing page (https://github.com/aws/aws-sdk-go-v2) and search for "migration" it doesn't find the badge in the results, because the badge is an image not text. This makes it hard to find the migration guide unless you already know it's a badge (so in essence #1289 isn't truly resolved).

**Comment by KaibaLopez** [comment]
Hi @rittneje...
Is there something we can co about that? I don't really know, but if you know a trick I'd be happy to implement that.

**Comment by rittneje** [comment]
I don't know much about badges, but you could always just make it normal text (like a Markdown section with a prose link) instead of a image.
