### ISSUE TITLE
How to use DisableHTTPS && UsePathStyle at the same time?

### ISSUE THREAD

**Issue by kisscelia** [aws/aws-sdk-go-v2#1295]
Confirm by changing [ ] to [x] below:
- [√] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [√] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**
Hi，my code as below:

```
defaultEndpointResolver := s3.NewDefaultEndpointResolver()
	//2. Create an endpoint resolver that will specify disable HTTPS, and delegate to default resolver.
	disableSSLEndpointResolver := s3.EndpointResolverFunc(
		func(region string, opts s3.EndpointResolverOptions) (aws.Endpoint, error) {
			opts.DisableHTTPS = true
			return defaultEndpointResolver.ResolveEndpoint(region, opts)
		})

	return s3.NewFromConfig(
		cfg,
		func(o *s3.Options) {
			o.UsePathStyle = true //  <---- here
		//o.EndpointOptions.DisableHTTPS = true
		}, 
		// 3. Disable SSL: https://github.com/aws/aws-sdk-go-v2/issues/1067
		s3.WithEndpointResolver(disableSSLEndpointResolver), // <----- here
	)

```
i got an error :
```
exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , Hos
tID: , request send failed, Get "http://s3.us-east-01.amazonaws.com/": dial tcp: lookup s3.us-east-01.amazonaws.com: no such host
exit status 1
```

my question is:
request did not use the right endpoint, i don't know why.

pls help me, thank you.

**Comment by skmcgrail** [comment]
It looks like your region is incorrect configured to `us-east-01`, but it should be `us-east-1`. This is likely an error in your `~/.aws/config` profile, `AWS_REGION` environment variable, or if you are configuring the SDK's `aws.Config` type programmatically.

**Comment by kisscelia** [comment]
Hi, @skmcgrail
my config profile is:
```
[30194]
region = us-east-1
output = json
```

and credentials is:
```
[30194]
aws_access_key_id = zVbxxxxxxxxHYi7Y
aws_secret_access_key = rNqxxxxxxQd0uJ
```
**BTW, the S3 service is a local storage.** 

Here are the config code:
```
cfg, err = config.LoadDefaultConfig(
			context.TODO(),
			config.WithSharedConfigProfile(co.Profile),
			config.WithEndpointResolver(
				aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
					return aws.Endpoint{URL: co.Endpoint}, nil // <--- co.Endpoint is http://IP:port which i sent, ①
				})),
			//config.WithRegion("us-east-1"),
		)
```

response is :
https response error StatusCode: 403, RequestID: 6PA7916RDVAVHXYY, HostID: vVNimW3XvZs+WThE+lv5sHhmbzLcqMp/GKj1GAp+fJ6HT+DWEeDjpXNdy/vzA7lCkh84NwQolWc=,
api error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

**The root cause: Maybe the endpoint is not the one which i set (①)**

Thank you very much.

**Comment by kisscelia** [comment]
And another question is......

If I want to disable verify ssl and set UsePathStyle to true, code as follows should be useful?

```
func(o *s3.Options) {
			o.UsePathStyle = true
			o.EndpointOptions.DisableHTTPS = true // <-- here!
		},
```
Thank you.

**Comment by kisscelia** [comment]
> And another question is......
> 
> If I want to disable verify ssl and set UsePathStyle to true, code as follows should be useful?
> 
> ```
> cfg, err = config.LoadDefaultConfig(
> 			context.TODO(),
> 			config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(co.AccessKey, co.SecretKey, "")),
> 			config.WithEndpointResolver(
> 				aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
> 					return aws.Endpoint{URL: co.Endpoint}, nil
> 				})),
> 			//config.WithRegion("us-east-1"),
> 		)
> 
> s3.NewFromConfig(
> 		cfg,
> 		func(o *s3.Options) {
> 			o.UsePathStyle = true
> 			//o.EndpointOptions.DisableHTTPS = true // <-- here!
> 		}, 
> 	)
> ```
> 
> Thank you.

**I got an error: x509: certificate signed by unknown authority.**
It seems the config not useful.

**Comment by kisscelia** [comment]
I add code like this. It's useful.
```
cfg, err = config.LoadDefaultConfig(
	context.TODO(),
	config.WithSharedConfigProfile(co.Profile),
	config.WithHTTPClient(&http.Client{Transport: &http.Transport{ // <--- here
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}}),
	config.WithEndpointResolver(
		aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
			return aws.Endpoint{URL: co.Endpoint}, nil
		})),
```

**Comment by KaibaLopez** [comment]
Hi @kisscelia ,
Just checking in, would you say your issue is solved?

**Comment by kisscelia** [comment]
> Hi @kisscelia ,
> Just checking in, would you say your issue is solved?

Hi，@KaibaLopez
I think... yes.
But, I want to know is there another way to disable SSL without using config.WithHTTPClient.
If not, i will close this issue.
Thanks.

**Comment by KaibaLopez** [comment]
Hi @kisscelia ,
Not really, that is the way.
