### ISSUE TITLE
config: WithEC2RoleCredentialOptions never honoured

### ISSUE THREAD

**Issue by saj** [aws/aws-sdk-go-v2#1296]
The documentation for [`config.LoadDefaultConfig`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config#LoadDefaultConfig) specifies that behaviour may be customised with functions of signature `func(*LoadOptions) error`.  Many of the provided `With*` functions work as documented, however [`WithEC2RoleCredentialOptions`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config#WithEC2RoleCredentialOptions) seems to impart no effect whatsoever.  This function accepts a value of type [`*ec2rolecreds.Options`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds#Options):

```go
type Options struct {
	// The API client that will be used by the provider to make GetMetadata API
	// calls to EC2 IMDS.
	//
	// If nil, the provider will default to the EC2 IMDS client.
	Client GetMetadataAPIClient
}
```

These `Client` values are always ignored by the SDK.

Jumping ahead, I think this bug can be explained by a simple typographical error.  This patch solves the problem:

```diff
--- a/config/resolve_credentials.go
+++ b/config/resolve_credentials.go
@@ -289,7 +289,7 @@ func resolveEC2RoleCredentials(ctx context.Context, cfg *aws.Config, configs con

        optFns = append(optFns, func(o *ec2rolecreds.Options) {
                // Only define a client from config if not already defined.
-               if o.Client != nil {
+               if o.Client == nil {
                        options := imds.Options{
                                HTTPClient: cfg.HTTPClient,
                        }
```

see [`config/resolve_credentials.go`](https://github.com/aws/aws-sdk-go-v2/blob/96600fecf48df6b6a5a18de626cc5010618bd913/config/resolve_credentials.go#L290-L301)

**Version of AWS SDK for Go?**

```
github.com/aws/aws-sdk-go-v2 v1.6.0
github.com/aws/aws-sdk-go-v2/config v1.3.0
```

**Version of Go?**

```
% go version
go version go1.16.4 darwin/amd64
```

**To Reproduce (observed behavior)**

The following sample program overrides the SDK default IMDS client with a widget that should print a message on every IMDS request:

```go
package main

import (
	"context"
	"log"
	"net/http"

	awshttp "github.com/aws/aws-sdk-go-v2/aws/transport/http"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds"
	"github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)

type debugHTTPClient struct{ config.HTTPClient }

func (c debugHTTPClient) Do(req *http.Request) (*http.Response, error) {
	log.Printf("http-> %s %s", req.Method, req.URL)
	return c.HTTPClient.Do(req)
}

func withDebugHTTPClient() func(*imds.Options) {
	return withHTTPClient(debugHTTPClient{awshttp.NewBuildableClient()})
}

func withHTTPClient(c imds.HTTPClient) func(*imds.Options) {
	return func(opts *imds.Options) {
		opts.HTTPClient = c
	}
}

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(),
		// this works:
		config.WithEC2IMDSRegion(),

		// this does not work:
		config.WithEC2RoleCredentialOptions(func(opts *ec2rolecreds.Options) {
			opts.Client = imds.New(imds.Options{}, withDebugHTTPClient())
		}))
	if err != nil {
		log.Fatal(err)
	}

	// Operation is irrelevant.  Trigger credential acquisition.
	c := sts.NewFromConfig(cfg)
	_, err = c.GetCallerIdentity(context.TODO(), nil)
	if err != nil {
		log.Fatal(err)
	}
}
```

The sample program does not emit any output when linked against `config` module version 1.3.0.

**Expected behavior**

After linking against a patched version of the `config` module:

```
go mod edit -replace=github.com/aws/aws-sdk-go-v2/config=/...
```

The sample program behaves as expected:

```
$ ./rolecredtest
2021/06/08 18:57:24 http-> PUT http://169.254.169.254/latest/api/token
2021/06/08 18:57:24 http-> GET http://169.254.169.254/latest/meta-data/iam/security-credentials/
2021/06/08 18:57:24 http-> GET http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACTED
```

**Comment by skmcgrail** [comment]
Apologies, I meant to reference and link this issue to the pull request that resolve this but did not do so. This issue was fixed as part of 2021-07-15 release. Please update to `github.com/aws/aws-sdk-go-v2/config@v1.5.0` to resolve this bug.
