### ISSUE TITLE
S3 SelectObjectContent - How to do this with v2

### ISSUE THREAD

**Issue by bdavid21wnec** [aws/aws-sdk-go-v2#1297]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

Title says its all. In aws-sdk-go:
https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.SelectObjectContent

We currently use this in an application and are converting to v2.
How can the above be accomplished in the version?

https://aws.amazon.com/blogs/developer/introducing-support-for-amazon-s3-select-in-the-aws-sdk-for-go/

**Comment by KaibaLopez** [comment]
Hi @bdavid21wnec ,
Short answer is, we can't yet.
`SelectObjectContent` requires event stream support which we haven't implemented yet on V2.

**Comment by skmcgrail** [comment]
This is now available as of 2021-11-06 release. https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-11-06
