### ISSUE TITLE
imageX with a zero value is dropped in the request to mediaconvert service

### ISSUE THREAD

**Issue by eranbranovate** [aws/aws-sdk-go-v2#1300]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I can not create a job in mediaconvert when using InsertableImage under VideoPreprocessors.ImageInserter when imageX of the image equals to zero (which is a valid value, i created the same job with values of zero in the UI and completed successfully there)
the same code that i wrote works when using imageX = 1 and imageY = 1

**Version of AWS SDK for Go?**

aws-sdk-go-v2/1.6.0
api/mediaconvert/1.5.1

**Version of Go (`go version`)?** 
go1.16.2 linux/amd64

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
when using the following code
`insertableImage := types.InsertableImage{
	ImageX:             0,
	ImageY:             0,
	Layer:              99,
	ImageInserterInput: aws.String(myImageURI),
	Opacity:            100,
	StartTime:          aws.String(00:00:00:00),
}`

I get the following error
`{
  "errorType": "BadRequestException",
  "httpStatus" : 400,
  "requestId" : "",
  "message" : "/outputGroups/1/outputs/0/videoDescription/videoPreprocessors/imageInserter/insertableImages/0: imageX is a required property",
  "settingsValidationErrorsJsonBlob" : "[{\"message\":\"imageX is a required property\",\"dataPath\":[\"/outputGroups/1/outputs/0/videoDescription/videoPreprocessors/imageInserter/insertableImages/0\"]}]"
}
`

using the logger i saw that this is the request that passed by in the end to the servers
`"videoPreprocessors": {
						"imageInserter": {
							"insertableImages": [{
								"imageInserterInput": "s3://dev.truvid.media/overlay/overlay.png",
								"layer": 99,
								"opacity": 100,
								"startTime": "00:00:00:00"
							}]
						}
					},
`
as you can see the sdk drops the imageX and imageY values because their values are zero

**Expected behavior**
the create job request should pass along the zero value of imageX and ImageY and there should be no error from the servers

**Comment by KaibaLopez** [comment]
Thanks for bringing this up to us, we'll look into it.
