### ISSUE TITLE
Maintain Release Notes in single file

### ISSUE THREAD

**Issue by TopherGopher** [aws/aws-sdk-go-v2#1303]
**Describe the issue with documentation**
It's really difficult to view the release notes from one change to the next as each release results in numerous artifacts. e.g. I'm trying to find all breaking changes when upgrading from a v.0 version to the most recent version. I'm actually getting rate limited when I try to click through all the pages. Every 4th or 5th page actually shows the release notes I need, and I can't just grep for "breaking change" to know everything I need to fix.

**Expected behavior**
I was hoping that the release notes could be maintained in a single md file to make the U/X easier for looking at changes. Then link that file to the release itself.

**Comment by KaibaLopez** [comment]
Hi @TopherGopher ,
I may be missing something here but, do you mean something like out [changelog](https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md) file? We also have a [migration guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/) which could be helpful?

**Comment by TopherGopher** [comment]
...Yes 😆 
I apologize @KaibaLopez - just missed it when I was scanning - closing.
