### ISSUE TITLE
Error handling documentation for S3 should reference `s3.ResponseError` instead of inline interface

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#1310]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

Documentation footer says: "Last modified January 15, 2021: updates documentation for fixes and wording (#1046) (418e7ccc4)"

### Version of Go (`go version`)?

N/A, documentation issue.

### What issue did you see?

In the section "Amazon S3 Request Identifiers", the documentation references S3 requests having the additional field `ServiceHostID()` in addition to the standard `ServiceRequestID()`.

The example shows retrieving the value using an inline interface:

```go
import "log"

// ...

if err != nil {
	var re interface {
		ServiceHostID()    string
		ServiceRequestID() string
	}
	if errors.As(err, &re) {
		log.Printf("requestID: %s, hostID: %s request failure", re.ServiceRequestID(), re.ServiceHostID());
	}
	return
}
```

However, the `s3` package defines the interface `s3.ResponseError` which should be used for the example:

```go
import "log"
import "github.com/aws/aws-sdk-go-v2/service/s3"

// ...

if err != nil {
	var re *s3.ResponseError
	if errors.As(err, &re) {
		log.Printf("requestID: %s, hostID: %s request failure", re.ServiceRequestID(), re.ServiceHostID())
    }
    return
}
```

### Steps to reproduce

N/A, documentation issue.

**Comment by KaibaLopez** [comment]
Hi @gdavison ,
Yea thanks for pointing it out, would you like to make a PR with the changes or would you rather I handle it?

**Comment by gdavison** [comment]
I can do it. Thanks!
