### ISSUE TITLE
TCP connection reset for each call to the S3 API

### ISSUE THREAD

**Issue by RyanJarv** [aws/aws-sdk-go-v2#1317]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [*] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [*] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [*] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
By default a new TCP connection is created for each call to s3.GetObjectACL.

**Version of AWS SDK for Go?**
1.7.0

**Version of Go (`go version`)?**
go1.16.5

**To Reproduce (observed behavior)**
While running the code at https://gist.github.com/RyanJarv/03354c9997854772f52c51dc18e7d890 start tcpdump in another terminal with `tcpdump -i any "port 443 and tcp[tcpflags] & (tcp-rst) != 0"`. The object in the example has public readacl so it should work without changes.

For the first 30 calls the client will send a RST packet to S3 closing each connection. The next 30 calls will pool TCP connections, significantly improving performance.

Output from personal testing:
```
SDK Version: 1.7.0
running default GetObjectAcl
Seconds elapsed:  13
running GetObjectAcl with fix
Seconds elapsed:  3
```

**Expected behavior**
TCP connections are reused.

**Additional context**
I haven't tested other S3 commands, unsure if anything else is affected. The TmpFix struct came about from noticing that the issue didn't come up when LogRequestWithBody was set, not really sure why it works.

**Comment by RyanJarv** [comment]
Looks like the same thing is happening with GetObject. Thinking this could be related to #1228 as well.

**Comment by KaibaLopez** [comment]
Hi @RyanJarv ,
It seems like you've reached a conclusion here, but just in case I am misunderstanding, is there anything pending or is it safe to close the issue?

**Comment by RyanJarv** [comment]
Hi @KaibaLopez, so that does seem related to the issue. The problem is that the GetOBjectAcl method doesn't return a ReadCloser.

**Comment by skmcgrail** [comment]
Confirmed this bug behavior on Amazon Linux 2, we will need to investigate adding logic to the [errorCloseResponseBodyMiddleware](https://github.com/aws/smithy-go/blob/main/transport/http/middleware_close_response_body.go#L17) and [closeResponseBody](https://github.com/aws/smithy-go/blob/main/transport/http/middleware_close_response_body.go#L17) middleware in the smithy-go module.
