### ISSUE TITLE
EC2 IMDS Client Does Not Support Logger or ClientLogMode which prevents logging of HTTP Request and Responses

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#1323]
EC2 IMDS Client does not attach the [RequestResponseLogger](https://pkg.go.dev/github.com/aws/smithy-go/transport/http#RequestResponseLogger) deserialize middleware which results in the ClientLogMode options being ignored.

Additionally the IMDS client does not call [AddSetLoggerMiddleware](https://pkg.go.dev/github.com/aws/smithy-go@v1.5.0/middleware#AddSetLoggerMiddleware) to register the clients logger with the stack middleware.

When fixing this issue the Logger and ClientLogMode will also need to support being resolved from `aws.Config` via the `NewFromConfig` constructor.

**Comment by RanVaknin** [comment]
PR #1891 fixes this issue.
