### ISSUE TITLE
HeadObject does not return TagCount as GetObject does

### ISSUE THREAD

**Issue by teimatinimarin** [aws/aws-sdk-go-v2#1331]
HeadObject is supposed to be used to return all the metadata of an object with out the object content itself.

It misses the TagCount property in the response. 

I'm using the following mods:
	github.com/aws/aws-sdk-go-v2 v1.6.0
	github.com/aws/aws-sdk-go-v2/config v1.3.0
	github.com/aws/aws-sdk-go-v2/service/s3 v1.10.0

Wondering if it could be added to this api.

Thanks in advance.

**Comment by KaibaLopez** [comment]
Hi @teimatinimarin ,
This is expected behavior and you can see the API definition of the call [here ](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html). Is there documentation that says that it should? Or are you expecting it as "all metadata" ?

**Comment by jasdel** [comment]
Looks like Amazon S3 HeadObject response includes `X-Amz-Tagging-Count` in its response, but this is not included in the HeadObject API model definition.

```
2021/07/15 14:04:46 ******* HeadObject *******
SDK 2021/07/15 14:04:46 DEBUG Response
HTTP/1.1 200 OK
Content-Length: 32
Accept-Ranges: bytes
Content-Type: text/plain
Date: Thu, 15 Jul 2021 21:04:47 GMT
Etag: "3059d27e16a10b15d305989f13332fa2"
Last-Modified: Thu, 15 Jul 2021 20:49:59 GMT
Server: AmazonS3
X-Amz-Expiration: expiry-date="Wed, 21 Jul 2021 00:00:00 GMT", rule-id="TimeDelayPurge"
X-Amz-Id-2: 6DpnRpYKWCBI1TllpR4xoxSicFAwqRYfTu8Nujj7BevXj6UUEpluxYiau/GUymeXYMCWHMXmF/Y=
X-Amz-Request-Id: 10DH2PTWA6K65211
X-Amz-Tagging-Count: 1
```

**Comment by teimatinimarin** [comment]
Thanks both @KaibaLopez and @jasdel for the response.
I don't this this is the expected behavior. I do think this may a defect in both, implementation and documentation.
I say that based on the idea that the Head operation "retrieves metadata from an object without returning the object itself" as stated [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html). If Head does not return TagCount then the only way to get it is the GetObject... which obviously is not the best way to do it (in both, performance and cost).

In the GetObject [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html) the behavior of x-amz-tagging-count is clearly defined. But yes, not defined/mentioned in HeadObject.

Thanks again for the response,
