### ISSUE TITLE
Documentation for using AssumeRoleWithSAML?

### ISSUE THREAD

**Issue by jh125486** [aws/aws-sdk-go-v2#1332]
**Describe the issue with documentation**
The docs do not state how to use `AssumeRoleWithSAML`.  It outputs a `sts.AssumeRoleWithSAMLOutput` struct, but there is no documentation on how to use that.

It unfortunately does not satisfy the interface `aws.CredentialsProvider`, so it cannot be used in any `Options` struct.

**To Reproduce (observed behavior)**
```go
cfg, err := config.LoadDefaultConfig(context.TODO())
if err != nil {
  panic(err)
}
roleOut, err := sts.NewFromConfig(cfg).AssumeRoleWithSAML(context.TODO(), roleIn)
if err != nil {
  panic(err)
}
// How to use roleOut here?
client := s3.NewFromConfig(cfg, func(o *s3.Options) {
  o.Region = "us-west-2"
})
```

**Expected behavior**
Usage instructions.

**Comment by KaibaLopez** [comment]
Hi @jh125486 ,
Thanks for bringing this up, we'll look into improving our documentation.
