### ISSUE TITLE
Get final output from waiter

### ISSUE THREAD

**Issue by haines** [aws/aws-sdk-go-v2#1338]
**Is your feature request related to a problem? Please describe.**

I want to be able to get the full output from the last API call made by a waiter, to avoid issuing another request.

I'm specifically interested in the `ssm.CommandExecutedWaiter` - I'd like to get the `GetCommandInvocationOutput` so that I can extract the `StandardOutputContent` after the command has finished executing - but I think this would potentially be useful for other waiters, too.

Right now I have to do something like

```go
input := &ssm.GetCommandInvocationInput{...}
ssm.NewCommandExecutedWaiter(client).Wait(ctx, input, 30*time.Second)
output, _ := client.GetCommandInvocation(ctx, input)
```

The code seems a bit unnecessarily verbose, and results in one more API request than necessary.

**Describe the solution you'd like**

Update the signature of the `Wait` methods to return the output of the final API call on success. This is consistent with the waiter behaviour in other SDKs (Ruby and JavaScript, at least).

**Describe alternatives you've considered**

Admittedly, this would be a breaking change to the API (although I imagine most existing code could be pretty easily updated to `_, err := waiter.Wait(...)`). If that's not an option, then adding an additional method which returns both values would be fine too.

**Comment by KaibaLopez** [comment]
Hi @haines ,
Thanks for bringing it up, we don't plan on implementing it any time soon, but it is an applicable idea...
We do take PRs though and that'd be a faster way to get this going.

**Comment by haines** [comment]
I have a PR up over at aws/smithy-go#319, would appreciate a review if anyone has time!

**Comment by haines** [comment]
As of the [2021-11-12 release](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-11-12), waiters support a `WaitForOutput` method that returns the final output.
