### ISSUE TITLE
Unable to use new client with different set of credentials

### ISSUE THREAD

**Issue by bwoznicki** [aws/aws-sdk-go-v2#1355]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Unable to reload client config with new credentials. The first time I create client everything works as expected, but if I change env vars and try creating new client it always fails with "The security token included in the request is invalid"

**Version of AWS SDK for Go?**
v1.7.1

**Version of Go (`go version`)?**
1.16

First time we create client...

    cfg, err := config.LoadDefaultConfig(context.TODO(),
        config.WithCredentialsProvider(credentials.StaticCredentialsProvider{
            Value: aws.Credentials{
		    AccessKeyID:     os.Getenv("AWS_ACCESS_KEY_ID"),
		    SecretAccessKey: os.Getenv("AWS_SECRET_ACCESS_KEY"),
		    Source:          "cred1",
	        },
	}))
    if err != nil {
	    fmt.Println(err.Error())
    }
    client := iam.NewFromConfig(cfg)
    keys, err := listAccessKeys(client)
    // do something with keys ...

So far everything ok, but then we reload the env vars ( different credential needs to be used for the second call )

    os.Setenv("AWS_ACCESS_KEY_ID", *accessKey.AccessKeyId)
    os.Setenv("AWS_SECRET_ACCESS_KEY", *accessKey.SecretAccessKey)

    cfg, err := config.LoadDefaultConfig(context.TODO(),
	config.WithCredentialsProvider(credentials.StaticCredentialsProvider{
		Value: aws.Credentials{
			AccessKeyID:     os.Getenv("AWS_ACCESS_KEY_ID"),
			SecretAccessKey: os.Getenv("AWS_SECRET_ACCESS_KEY"),
			Source:          "cred2",
		},
	}))
    if err != nil {
	    fmt.Println(err.Error())
    }
    client2 := iam.NewFromConfig(cfg)
    keys, err := listAccessKeys(client2)
    // fails with "The security token included in the request is invalid"

**Expected behavior**
Second time we create the client it should use the new creds and create new token. Do we need to reset credential cache somehow ?

**Comment by bwoznicki** [comment]
Slightly different approach also does not use the second credential:

	cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		fmt.Println(err.Error())
	}
	client := iam.NewFromConfig(cfg)

	input := &iam.ListAccessKeysInput{
		UserName: &userName,
	}
	creds := credentials.NewStaticCredentialsProvider(
		os.Getenv("AWS_ACCESS_KEY_ID"),
		os.Getenv("AWS_SECRET_ACCESS_KEY"),
		"",
	)

	_, err := client.ListAccessKeys(context.TODO(), input, func(o *iam.Options) {
		o.Credentials = creds
		o.ClientLogMode = aws.LogResponseWithBody
	})
        // above works as expected
        // now we reset env vars
	os.Setenv("AWS_ACCESS_KEY_ID", "NEW_KEY")
	os.Setenv("AWS_SECRET_ACCESS_KEY", "NEW_SECRET")
	os.Unsetenv("AWS_SESSION_TOKEN")

	creds2 := credentials.NewStaticCredentialsProvider(
		os.Getenv("AWS_ACCESS_KEY_ID"),
		os.Getenv("AWS_SECRET_ACCESS_KEY"),
		"",
	)

	_, err := client.ListAccessKeys(context.TODO(), input, func(o *iam.Options) {
		o.Credentials = creds2
		o.ClientLogMode = aws.LogResponseWithBody
	})
	// this still uses original credentials and not the newly created creds2

**Comment by skmcgrail** [comment]
I am not able to reproduce the issue that you are seeing. Here is the following snippet I've used to test the various scenarios you've described.

```go
package main

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"log"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.Background(),
		config.WithRegion("us-west-2"),
		config.WithCredentialsProvider(
			credentials.NewStaticCredentialsProvider("KEY1", "SECRET1", "SESS1"),
		))
	if err != nil {
		log.Fatalln(err)
	}

	client := sts.NewFromConfig(cfg, func(o *sts.Options) {
		o.ClientLogMode = aws.LogRequest
	})

	_, _ = client.GetCallerIdentity(context.Background(), &sts.GetCallerIdentityInput{})

	_, _ = client.GetCallerIdentity(context.Background(), &sts.GetCallerIdentityInput{}, func(o *sts.Options) {
		o.Credentials = credentials.NewStaticCredentialsProvider("KEY2", "SECRET2", "SESS2")
	})

	_, _ = client.GetCallerIdentity(context.Background(), &sts.GetCallerIdentityInput{}, func(o *sts.Options) {
		o.Credentials = credentials.NewStaticCredentialsProvider("KEY3", "SECRET3", "SESS3")
	})
}
```

This outputs:
```
SDK 2021/08/02 13:38:36 DEBUG Request
POST / HTTP/1.1
Host: sts.us-west-2.amazonaws.com
User-Agent: aws-sdk-go-v2/1.7.1 os/macos lang/go/1.16.6 md/GOOS/darwin md/GOARCH/amd64 api/sts/1.6.0
Content-Length: 43
Amz-Sdk-Invocation-Id: 03c385a5-0606-4774-8d11-387246a90692
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=KEY1/20210802/us-west-2/sts/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=5e151d50d869f3569593fd0e5403a5dae7f6cbb5831363c403366c79bda52a6c
Content-Type: application/x-www-form-urlencoded
X-Amz-Date: 20210802T203836Z
X-Amz-Security-Token: SESS1
Accept-Encoding: gzip

SDK 2021/08/02 13:38:37 DEBUG Request
POST / HTTP/1.1
Host: sts.us-west-2.amazonaws.com
User-Agent: aws-sdk-go-v2/1.7.1 os/macos lang/go/1.16.6 md/GOOS/darwin md/GOARCH/amd64 api/sts/1.6.0
Content-Length: 43
Amz-Sdk-Invocation-Id: c44c3cd0-456d-4d1b-a084-97f2808c45ac
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=KEY2/20210802/us-west-2/sts/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=b437429e4931e0ddef9253c32604f28410c227176882e8cd23b85ed3a9fbc324
Content-Type: application/x-www-form-urlencoded
X-Amz-Date: 20210802T203837Z
X-Amz-Security-Token: SESS2
Accept-Encoding: gzip

SDK 2021/08/02 13:38:37 DEBUG Request
POST / HTTP/1.1
Host: sts.us-west-2.amazonaws.com
User-Agent: aws-sdk-go-v2/1.7.1 os/macos lang/go/1.16.6 md/GOOS/darwin md/GOARCH/amd64 api/sts/1.6.0
Content-Length: 43
Amz-Sdk-Invocation-Id: ce736f88-2a40-4a20-8d41-90158291c866
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=KEY3/20210802/us-west-2/sts/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=29b30a2ef40de2db1880a38050695c46d2709e2997fc5e6727c614da75c7428e
Content-Type: application/x-www-form-urlencoded
X-Amz-Date: 20210802T203837Z
X-Amz-Security-Token: SESS3
Accept-Encoding: gzip
```

Note the `Authorization` and `X-Amz-Security-Token` contain the expected access key and session token respectively. Can you enable `LogRequest` client log mode to confirm whether the expecting credentials for the access and session token are being included in each request?
