### ISSUE TITLE
Endpoint for network-firewall within gov partition is incorrect

### ISSUE THREAD

**Issue by jlegate** [aws/aws-sdk-go-v2#1360]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When attempting to use the networkfirewall package within the GovCloud partition, the endpoint is configured incorrectly as `network-firewall.{region}.amazonaws.com`, where https://docs.aws.amazon.com/general/latest/gr/network-firewall.html defines the endpoints in govcloud as `network-firewall-fips.{region}.amazonaws.com`

**Version of AWS SDK for Go?**
v1.38.40

**Version of Go (`go version`)?**
v1.14.3

**To Reproduce (observed behavior)**
```
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/networkfirewall"
)

func main() {
	region := "us-gov-west-1"
	awscreds := &credentials.Credentials{REDACTED}
	firewall := networkfirewall.New(session.Must(session.NewSession(&aws.Config{
		Region:      &region,
		Credentials: awscreds,
	})))
	_, err := firewall.ListFirewalls(&networkfirewall.ListFirewallsInput{})
	fmt.Println(err)
}
```
yields:
```
RequestError: send request failed
caused by: Post "https://network-firewall.us-gov-west-1.amazonaws.com/": dial tcp: lookup network-firewall.us-gov-west-1.amazonaws.com: no such host
```

**Expected behavior**
Endpoint should be set to the documented values published by AWS: https://docs.aws.amazon.com/general/latest/gr/network-firewall.html

**Additional context**

**Comment by jlegate** [comment]
I don't have a full stack here to be able to generate `service/networkfirewall/internal/endpoints/endpoints.go`, but after digging around a little in https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json, I think this can be addressed by adding:

```
      "network-firewall" : {
        "endpoints" : {
          "fips-us-gov-east-1" : {
            "credentialScope" : {
              "region" : "us-gov-east-1"
            },
            "hostname" : "network-firewall-fips.us-gov-east-1.amazonaws.com"
          },
          "fips-us-gov-west-1" : {
            "credentialScope" : {
              "region" : "us-gov-west-1"
            },
            "hostname" : "network-firewall-fips.us-gov-west-1.amazonaws.com"
          },
          "us-gov-east-1" : { },
          "us-gov-west-1" : { }
        }
      },
```

under the `aws-us-gov` partition definition

**Comment by jlegate** [comment]
*oops*. I found this bug in -v2, but we are still using v1. I'll correctly repro this bug in v2 here. I've created a local branch and will test it. Will do same in v1. Sorry about the crossed streams

**Comment by jasdel** [comment]
Thanks for reporting this issue @jlegate  Was the endpoints you suggested copied from another SDK?  I'm not seeing `network-firewall` modeled in the v1 Go SDK's endpoints.json file.
