### ISSUE TITLE
feature/dynamodb/attributevalue: omitempty struct tag annotation doesn't work with time.Time

### ISSUE THREAD

**Issue by otterley** [aws/aws-sdk-go-v2#1363]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When encoding structs for DynamoDB AttributeValues, zero `time.Time` values are not skipped if `omitempty` is included in the struct tag.

Example:

```go
type TaskCheck struct {
	LastCheckTime time.Time `json:"lastCheckTime" dynamodbav:",omitempty"`
}
```

Even if `time.IsZero()` is true for the value in this struct, the attribute will be created with a value of `0001-01-01T00:00:00Z`.

Should be a pretty easy fix.

**Comment by skmcgrail** [comment]
To have this value excluded by `omitempty` you will need to model the type as a `*time.Time`. The existing behavior of `omitempty` for a non-pointer `time.Time` type is inline and consistent with the `encoding/json` standard library.

```go
package main

import (
	"encoding/json"
	"fmt"
	"time"
)

func main() {
	type t struct {
		T time.Time `json:",omitempty"`
	}

	var x t

	marshal, err := json.Marshal(&x)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s\n", marshal)
}
```

Outputs:
```
{"T":"0001-01-01T00:00:00Z"}
```

**Comment by otterley** [comment]
Oh, that's a good tip. Thanks! I'll close this issue.
