### ISSUE TITLE
High memory usage on publishing to a SNS topic at a high concurrency

### ISSUE THREAD

**Issue by agrim123** [aws/aws-sdk-go-v2#1364]
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

We have a service that publishes to two SNS topics at several intervals. At a particular interval we need to publish around 12k messaged to the topics (~6k/topic) concurrently, during which we see a sudden memory spike.

We got the following allocations profile using pprof and it shows large amount of memory allocated under SNS. 

![Screenshot 2021-08-04 at 12 50 30 AM](https://user-images.githubusercontent.com/16553016/128073615-6043ea8e-506d-4e7a-8e6f-9cb675871a23.png)

We are initializing the SNS client as follows:
```golang
httpClient := &http.Client{
    Timeout: 5 * time.Second,
    Transport: &http.Transport{
        TLSClientConfig: &tls.Config{
            InsecureSkipVerify: true,
        },
        DialContext: (&net.Dialer{
            Timeout:   10 * time.Second,
            KeepAlive: 30 * time.Second,
        }).DialContext,
        DisableKeepAlives:   false,
        MaxIdleConns:        500,
        IdleConnTimeout:     90 * time.Second,
        MaxConnsPerHost:     500,
        MaxIdleConnsPerHost: 500,
        TLSHandshakeTimeout: 5 * time.Second,
    },
}

cfg, err := config.LoadDefaultConfig(
	ctx,
	config.WithRegion("us-east-2"),
	config.WithHTTPClient(httpClient),
)

client := sns.NewFromConfig(cfg)
```

We have a single SNS client which all the goroutines use to push the messages.

We sometimes also receive another error from SNS library
```bash
operation error SNS: Publish, retry quota exceeded, 0 available, 5 requested
```

Is there something that we are doing wrong or are we missing something?

**Comment by skmcgrail** [comment]
Can you provide further information about the average sizes of these messages during this period of time. There will be a fixed cost to serialize and deserialize each request and responses message to the SMS service, and that can also very by the size of the `MessageBody` you are providing. Would it be possible for you to provide the whole pprof capture?

**Comment by agrim123** [comment]
Hey @skmcgrail ,

- Average message size id ~150bytes.
- We have *lambda* subscription on SNS topic.
- We are using https://github.com/json-iterator/go for marshalling message.

Sharing the CPU and heap profile

Heap (with -alloc_objects):
<img width="1383" alt="Screenshot 2021-08-07 at 1 25 13 AM" src="https://user-images.githubusercontent.com/16553016/128564766-b8b923a8-b87a-44f9-8552-529534fc58d9.png">

The generator func in the above profile is the one that is called ~8k times during peak hours which and which in turns spawns a new goroutine to push to SNS

CPU

<img width="1772" alt="Screenshot 2021-08-07 at 1 21 13 AM" src="https://user-images.githubusercontent.com/16553016/128564211-0ba574bf-38e3-429b-85dc-ecee8f9db8b8.png">

Let me know if any more info is needed!
Cheers!

**Comment by yuseferi** [comment]
Hey @agrim123 , what was the result of it? I'm just wondering how did you resolve it?

**Comment by pyaesone17** [comment]
Yeah we are also facing the same issue @agrim123 let me know how did you resolve it.
