### ISSUE TITLE
service/s3/s3manager: GetBucketRegion fallback to Config.Region

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#137]
Port the aws/aws-sdk-go#1804 change to v2 allowing GetBucketRegion to fallback to the Config's Region if provided.

**Comment by kaihendry** [comment]
I'm keen to be able to guess the Bucket's region effectively. Looking for a https://godoc.org/github.com/aws/aws-sdk-go-v2/service/s3/s3manager#GetBucketRegion example, especially that demonstrates the ctx bit. Thanks!

**Comment by jasdel** [comment]
Thanks for the feedback @kaihendry, could you describe more about what you're looking for in an example? Any confusing areas, or unclear in your linked example we should target?

**Comment by kaihendry** [comment]
Complete example of how to guess the Bucket's region would be great.
