### ISSUE TITLE
Enable S3TA From Client

### ISSUE THREAD

**Issue by zhoub** [aws/aws-sdk-go-v2#1372]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

How to enable S3TA to generate pre-signed URL ?

The document says
```
	// Set this to `true` to enable S3 Accelerate feature. For all operations
	// compatible with S3 Accelerate will use the accelerate endpoint for
	// requests. Requests not compatible will fall back to normal S3 requests.
	//
	// The bucket must be enable for accelerate to be used with S3 client with
	// accelerate enabled. If the bucket is not enabled for accelerate an error
	// will be returned. The bucket name must be DNS compatible to also work
	// with accelerate.
```

but nowhere mentions what kind of operations are compatible for S3TA.

Here is the code used to create the client
```go
	cli := s3.New(sess, &aws.Config{
		S3UseAccelerate: aws.Bool(true),
	})
```
But this didn't work, and program would be timeout. The bucket had enabled TA. How to use S3TA from the Go code ?

Thanks in advance !

**Comment by skmcgrail** [comment]
@zhoub can you please provide us the dependency versions in your application's `go.mod` file? Want to verify that you are using the AWS SDK for Go V2 and at what version. The code example you have provided in this issue is for the AWS SDK for Go (V1).
