### ISSUE TITLE
Need function for `update-kubeconfig`

### ISSUE THREAD

**Issue by ghostsquad** [aws/aws-sdk-go-v2#1378]
**Is your feature request related to a problem? Please describe.**
No function part of the `eks` service that is equivalent to the aws cli `update-kubeconfig` subcommand

**Describe the solution you'd like**
Please add the `aws` cli equivalent of `update-kubeconfig`

**Describe alternatives you've considered**
shelling out to the AWS CLI instead

**Additional context**
n/a

**Comment by KaibaLopez** [comment]
Hi @ghostsquad ,
Sorry but this is out of scope for the SDK.
