### ISSUE TITLE
Better AssumeRole example

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#1382]
**Is your feature request related to a problem? Please describe.**

On the cli, it's
aws sts assume-role --role-arn "arn:aws:iam::XYZ:role/ViewLogsPlease" --role-session-name ViewOne

And then you awkwardly need to setup AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN, however it's less awkward than wading through wierd non-sensical documentation like https://aws.github.io/aws-sdk-go-v2/docs/code-examples/sts/assumerole/

**Describe the solution you'd like**

Clear working instructions like
```
   creds := stscreds.NewAssumeRoleProvider(stsclient, "arn:aws:iam::XYZ:role/ViewLogsPlease", func(p *stscreds.AssumeRoleOpti  ons) {
          p.RoleSessionName = "ViewLogsPlease"
      })
      // Magic sauce to get the current role
      cfg.Credentials = aws.NewCredentialsCache(creds)
```

**Describe alternatives you've considered**
Maybe I should go back to v1, because v2 hasn't made the cfg any easier!

**Additional context**

Additionally I went down the rabbit hole of assuming that something like:

```
  cfg, err := config.LoadDefaultConfig(context.TODO(),
          config.WithSharedConfigProfile("mine"),
          config.WithAssumeRoleCredentialOptions(func(o *stscreds.AssumeRoleOptions) {
           o.RoleARN = "arn:aws:iam::XYZ:role/ViewLogsPlease"
           }),
      )
```
It doesn't work, and I have no idea why. github.com/aws/aws-sdk-go-v2 v1.8.0

**Comment by skotambkar** [comment]
Thanks for reaching out @kaihendry . To help clarify the issue, could you provide if your `SharedConfigProfile` in this example has assume role configured in it?

As documented at https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config#WithAssumeRoleCredentialOptions 

> WithAssumeRoleCredentialOptions is a helper function to construct functional options that sets a function to use stscreds.AssumeRoleOptions on config's LoadOptions. If assume role credentials options is set to nil, the assume role credentials value will be ignored. If multiple WithAssumeRoleCredentialOptions calls are made, the last call overrides the previous call values.


The `WithAssumeRoleCredentialOptions` works similar to how you are configuring `p.RoleSessionName = "ViewLogsPlease"` in your first code snippet. 

In your example - if no assume role was present in "mine" shared config profile, the `WithAssumeRoleCredentialOptions` will not be invoked.  

We will update our example docs to reflect this requirement.

**Comment by petitout** [comment]
this example is very good : https://flowerinthenight.com/blog/2021/04/30/authenticate-aws-sdk-golang-v2

**Comment by petitout** [comment]
`ctx := context.Background()
assumecnf, _ := config.LoadDefaultConfig(
	ctx, config.WithRegion("{aws-region}"),
	config.WithCredentialsProvider(aws.NewCredentialsCache(
		credentials.NewStaticCredentialsProvider(
			"{aws-assume-role-key}",
			"{aws-assume-role-secret}", "",
		)),
	),
)

stsclient := sts.NewFromConfig(assumecnf)
cnf, _ := config.LoadDefaultConfig(
	ctx, config.WithRegion("{aws-region}"),
	config.WithCredentialsProvider(aws.NewCredentialsCache(
		stscredsv2.NewAssumeRoleProvider(
			stsclient,
			"{rolearn-to-assume}",
		)),
	),
)

client := s3.NewFromConfig(cnf)
res, _ := client.GetObject(ctx, &s3.GetObjectInput{
	Bucket: awsv2.String("{some-bucket}"),
	Key:    awsv2.String("{some-key}"),
})`

**Comment by rayterrill** [comment]
Came here to post a similar issue - I think the docs could be improved in this case (specifically this one: https://aws.github.io/aws-sdk-go-v2/docs/code-examples/sts/assumerole/) to show the use of the AssumeRole credentials as opposed to stopping at getting the role assumed. I also stumbled across the example above and that seems to work, but it would be good to see a working example with best practice code from AWS itself.

**Comment by rayterrill** [comment]
This seems like the best, simplest example I've seen for AssumeRole: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds#hdr-Assume_Role

**Comment by nckrse** [comment]
Assuming role without 'stscreds' (only using 'sts' and 'sts/types') and static credentials:

```go
import (
    "context"
    "strconv"
    "time"
    "math/rand"
    "github.com/aws/aws-sdk-go-v2/aws"
    "github.com/aws/aws-sdk-go-v2/config"
    "github.com/aws/aws-sdk-go-v2/credentials"
    "github.com/aws/aws-sdk-go-v2/ec2"
    "github.com/aws/aws-sdk-go-v2/sts"
    stsTypes "github.com/aws/aws-sdk-go-v2/sts/types"


// Create config & sts client with source account
cfg, err := config.LoadDefaultConfig (ctx, config.WithRegion(region), config.WithSharedConfigProfile(profileName))
if err != nil {
    log.Fatalf("unable to load shared profile for sts client config, %v", err)
}
sourceAccount := sts.NewFromConfig(cfg)

// Assume target role and store credentials
rand.Seed(time.Now().UnixNano())
response, err := sourceAccount.AssumeRole(ctx, &sts.AssumeRoleInput{
    RoleArn: aws.String("arn:aws:iam::ACCOUNT_NUM:role/ROLE_NAME),
    RoleSessionName: aws.String("some-identifier-" + strconv.Itoa(10000 + rand.Intn(25000))),
}
var assumedRoleCreds = *stsTypes.Credentials

// Create config with target service client, using assumed role
cfg, err = config.LoadDefaultConfig(ctx, config.WithRegion(region), config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(*assumedRoleCreds.AccessKeyId, *assumedRoleCreds.SecretAccessKey, *assumedRoleCreds.SessionToken)))
if err != nil {
    log.Fatalf("unable to load static credentials for service client config, %v", err)
}

// Use it 
ec2.NewFromConfig(cfg)
```

reference: https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#static-credentials

**Comment by RanVaknin** [comment]
Since I see many comments here with good examples I feel confident we can close this issue.
If this is not sufficient please open a new issue.

Thanks,
Ran~
