### ISSUE TITLE
AssumeRoleOptions does not have TokenCode member

### ISSUE THREAD

**Issue by NukaCody** [aws/aws-sdk-go-v2#1384]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

[AssumeRoleOptions does not have a TokenCode member](https://github.com/aws/aws-sdk-go-v2/blob/credentials/v1.3.0/credentials/stscreds/assume_role_provider.go#L154) despite [documentation using it as an example for static MFA token](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds#hdr-Assume_Role_with_static_MFA_Token)

**Version of AWS SDK for Go?**

1.8.0

**Version of Go (`go version`)?**

go version go1.16.6 darwin/amd64

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```go
	tokenCode, _ = stscreds.StdinTokenProvider()

    // Below would be in goroutine
	creds := stscreds.NewAssumeRoleProvider(stsc, role, func(aro *stscreds.AssumeRoleOptions) {
		aro.SerialNumber = aws.String("arn:aws:iam::*:mfa/user")
		aro.TokenCode = aws.String(tokenCode)
	})
```

**Expected behavior**

Get MFA token at the entry point of the app, then spin up hundreds of goroutines that assume roles into different accounts that have MFA required using the static token code. Moving StdinTokenProvider inside of the goroutine won't be goroutine safe nor scalable

**Comment by skmcgrail** [comment]
Thanks for raising this documentation issue, the correct structure field to use is `TokenProvider` which takes a `func() (string, error)` that returns a token to be used.

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds#hdr-Assume_Role_with_MFA_Token_Provider has a correct example usage for this.

We will work on getting this addressed and updated.

**Comment by NukaCody** [comment]
I'm not sure if it's purely documentation. There's still a strong use case for static TokenCode.

It looks like TokenProvider opens up STDIN to read a token, but if you were to run this is thousands of go routines at least till that MFA code expire. It wouldn't be a scalable method.
