### ISSUE TITLE
Documentation around S3 Head Object

### ISSUE THREAD

**Issue by sandakith** [aws/aws-sdk-go-v2#1392]
Referring to https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#Client.HeadObject

Is there any documentation around how to call head object using go sdk v2? 

I found this but after spending lot of unnecessary time : 
https://stackoverflow.com/questions/57697095/how-i-can-safely-check-if-file-exists-in-s3-bucket-using-go-in-lambda

**Comment by jasdel** [comment]
The S3 HeadObject API calling is done using a similar pattern across the SDK. Checkout the SDK's [getting started](https://aws.github.io/aws-sdk-go-v2/docs/getting-started/) guide for information on loading the SDK's configuration, creating API clients, and making API calls.
