### ISSUE TITLE
Disabling EC2 IMDS Client in `config.LoadDefaultConfig()` does not disable EC2 IMDS Client

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#1398]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Setting the `EC2IMDSClientEnableState` to `imds.ClientDisabled` does not disable the EC2 IMDS Client when resolving configuration using `config.LoadDefaultConfig()`.

Setting `AWS_EC2_METADATA_DISABLED = true` does correctly disable the EC2 IMDS Client.

**Version of AWS SDK for Go v2?**

* github.com/aws/aws-sdk-go-v2 v1.9.0
* github.com/aws/aws-sdk-go-v2/config v1.7.0
* github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.5.0

**Version of Go (`go version`)?**

go1.16 darwin/amd64

**To Reproduce (observed behavior)**

The following code

```go
imdsEnableState := imds.ClientDefaultEnableState
if c.SkipMetadataApiCheck {
	imdsEnableState = imds.ClientDisabled
}

...

cfg, err := config.LoadDefaultConfig(ctx,
	...
	config.WithEC2IMDSClientEnableState(imdsEnableState),
)

_, err = cfg.Credentials.Retrieve(ctx)
if err != nil {
	return cfg, fmt.Errorf("retrieving credentials: %w", err)
}
```

returns the following error

> retrieving credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded

If the environment variable `AWS_EC2_METADATA_DISABLED` is set as follows

```go
imdsEnableState := imds.ClientDefaultEnableState
if c.SkipMetadataApiCheck {
	imdsEnableState = imds.ClientDisabled
	os.Setenv("AWS_EC2_METADATA_DISABLED", "true")
}
```

the following is returned

> retrieving credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, access disabled to EC2 IMDS via client option, or "AWS_EC2_METADATA_DISABLED" environment variable

**Expected behavior**

The EC2 IMDS Client should not be called when `config.WithEC2IMDSClientEnableState(imds.ClientDisabled)` is set.

**Comment by skmcgrail** [comment]
This appears to be an issue due to the the `aws.Config#CredentialSources` not being populated when the EC2 client is constructed and provided to the provider. This is populated AFTER all config resolvers are ran, which is likely not the right behavior. [These lines of code](https://github.com/aws/aws-sdk-go-v2/blob/b7d8e15425d2f86a0596e8d7db2e33bf382a21dd/config/config.go#L132-L136) would need to be moved above the resolver loop to handle this correctly.

**Comment by gdavison** [comment]
@skmcgrail, I've done some more investigation on this issue. The basic problem is that the `awsConfigResolver` functions take the parameters `(ctx context.Context, cfg *aws.Config, configs configs)` where `cfg` has no `ConfigSources` set, and the config providers are passed in `configs`.

This works until the resolvers need to create a service client, such as `imds.Client`. The clients are created using their `NewFromConfig` function. The `aws.Config` with zero `ConfigSources` is then passed in, ignoring the config providers in `configs`.

I haven't validated if the other clients used in the resolvers, `sso` and `sts`, are affected by this.

If the lines referenced above that set the `ConfigSources` are moved ahead of the resolvers, the first resolver, `resolveDefaultAWSConfig` will reset them to an empty slice. If the `ConfigSources` are set on the `aws.Config` at the beginning, the `awsConfigResolver` functions would no longer need to accept the `configs` parameter.

Another option is to call the `resolveCredentials` resolver after setting the `ConfigSources` on the `aws.Config`.

**Comment by gdavison** [comment]
@skmcgrail, I've created #1682 as a fix to this issue. As I note in the PR, deeper changes could be made, but the PR does work as-is
