### ISSUE TITLE
Does the "Uploader.Upload" have an asynchronous interface

### ISSUE THREAD

**Issue by SktingGenius** [aws/aws-sdk-go-v2#1408]
Does the _"Uploader.Upload"_ have an asynchronous interface?
Want faster transmission efficiency.

**Comment by skmcgrail** [comment]
The S3 Uploader transfer manager can safely be called concurrently by your Go application. You easily spin-off one or more goroutines in your calling application that each handle calling the `Upload.Upload` to upload an object.
