### ISSUE TITLE
AccessKeyId should be AccessKeyID

### ISSUE THREAD

**Issue by andig** [aws/aws-sdk-go-v2#1410]
**Is your feature request related to a problem? Please describe.**
`cognitoidentity.Credentials.AccessKeyID` has been renamed to `types.AccessKeyId`. The go way is to have `ID` in capitals. Other IDs in this module are spelled in upper case, too.

**Describe the solution you'd like**
Revert the spelling change and make spelling consistent across the module.

**Describe alternatives you've considered**
Leave as-is which makes migration painful

**Comment by jasdel** [comment]
Thanks for reaching out @andig Was this rename when migrating from the v1 Go SDK to the v2 SDK? Or did you experience this issue with the v2 SDK it self. If so what version of the v2 SDK did you experience this issue with?

[From what i can tell](https://github.com/aws/aws-sdk-go-v2/blame/a1be7274d533f8612217a3facc79c0b1a902612c/service/cognitoidentity/types/types.go#L35) this field has always been `AccessKeyID` in the v2 SDK.

With regard to `ID` vs `Id` the v2 SDK relies solely on the API's model to specify the  naming of the API's operations, types, and members. The v1 SDK originally made some attempts to coerce the modeled names into idiomatic Go's preferred styling. But, this was not sustainable. The coercion of the names was stopped in the v1 SDK for new names, and was not included in the v2 SDK at all.

**Comment by andig** [comment]
> Thanks for reaching out @andig Was this rename when migrating from the v1 Go SDK to the v2 SDK?

Correct. It used to be `AccessKeyID`

> With regard to ID vs Id the v2 SDK relies solely on the API's model to specify the naming of the API's operations, types, and members. 

Understood.

> The v1 SDK originally made some attempts to coerce the modeled names into idiomatic Go's preferred styling. But, this was not sustainable. 

Understood. Under the hood, the APIs themselves are inconsistent then with both `Id` and `ID` appearing. Seems as if- at this stage- that is something to accept.

Much appreciated!

**Comment by andig** [comment]
Funny. I've closed with the comment. The warning is not warranted here...
