### ISSUE TITLE
Add a compatibility function for signing v4 requests

### ISSUE THREAD

**Issue by andig** [aws/aws-sdk-go-v2#1411]
**Is your feature request related to a problem? Please describe.**
Signing requests used to be simple using `signer.Sign`. `signer.SignHTTP` is much more complicated as it needs a sha value special-cased for empty body.

**Describe the solution you'd like**
Provide a helper function to calculate the sha.

**Describe alternatives you've considered**
Expose the empty string sha from the v4internal package.

**Comment by KaibaLopez** [comment]
@andig,
Sorry but yea it is a well known and documented constant, with plenty of options for it. The intention of the interface design is to remove computation of the body hash for the signer.
Not something we are planning on changing, thanks and sorry
