### ISSUE TITLE
Unmarshal map[string]DynamoDBAttributeValue into a struct

### ISSUE THREAD

**Issue by AndreaM16** [aws/aws-sdk-go-v2#142]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

github.com/aws/aws-sdk-go-v2

### Version of Go (`go version`)?

go1.10 linux/amd64

### What issue did you see?

I'm trying to set-up an AWS-lambda using [aws-sdk-go][1] that is triggered whenever a new `user` is added to a certain [dynamodb][2] table.

Everything is working just fine but I can't find a way to unmarshal a map `map[string]DynamoDBAttributeValue` like:

```
"name": {
  "S" : "John"
},
residence_address": {
    "M": {
           "address": {
               "S": "some place"
           }
    }
}
```

To a given struct, for instance, a `User` struct. [Here][3] is shown an example of unsmarhaling a `map[string]*dynamodb.AttributeValue` into a given interface, but I can't find a way to do the same thing with `map[string]DynamoDBAttributeValue` even though these types seem to fit the same purposes.

`map[string]DynamoDBAttributeValue` is returned by a `events.DynamoDBEvents` from package `github.com/aws/aws-lambda-go/events`. This is my code:
```
    package handler
    
    import (
        "context"
        "github.com/aws/aws-lambda-go/events"
        "github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbattribute"
    	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
    )

    func HandleDynamoDBRequest(ctx context.Context, e events.DynamoDBEvent) {
    
    	for _, record := range e.Records {
    
    	    if record.EventName == "INSERT" {
    
                // User Struct
    		var dynamoUser model.DynamoDBUser
    
                // Of course this can't be done for incompatible types
    		_ := dynamodbattribute.UnmarshalMap(record.Change.NewImage, &dynamoUser)
    	    }
    
    	}
    
    }
```
Of course, I can marshal `record.Change.NewImage` to JSON and unmarshal it back to a given struct, but then, I would have to manually initialize `dynamoUser` attributes starting from the latter ones.

Or I could even define a function like:

```
    func getAttributeValueMapFromDynamoDBStreamRecord(e events.DynamoDBStreamRecord) map[string]*dynamodb.AttributeValue {
    	image := e.NewImage
    	m := make(map[string]*dynamodb.AttributeValue)
    	for k, v := range image {
    		if v.DataType() == events.DataTypeString {
    			s := v.String()
    			m[k] = &dynamodb.AttributeValue{
    				S : &s,
    			}
    		}
    		if v.DataType() == events.DataTypeBoolean {
    			b := v.Boolean()
    			m[k] = &dynamodb.AttributeValue{
    				BOOL : &b,
    			}
    		}
                // . . .
    		if v.DataType() == events.DataTypeMap {
    			// ?
    		}
    	}
    	return m
    }
```

But on `events.DataTypeMap` it would be quite a tricky process.

**Is there a way through which I can unmarshal a DynamoDB record coming from a `events.DynamoDBEvent` into a struct with a similar method shown for `map[string]*dynamodb.AttributeValue`?**

  [1]: https://github.com/aws/aws-sdk-go
  [2]: https://aws.amazon.com/dynamodb
  [3]: **https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/dynamodbattribute/#example_Unmarshal**

**Comment by xibz** [comment]
Hello @AndreaM16, thank you for reaching out to us. This sounds like a feature request for the [aws-sdk-go](https://github.com/aws/aws-lambda-go) package. I would suggest having them creating a higher level function to convert from their attribute types to Go types. I am going to go ahead and close this, since this doesn't seem to be the right place for the issue. If you have any other issues regarding this, please feel free to reopen.

**Comment by AndreaM16** [comment]
@xibz Should I open such feature request on `aws-sdk-go` and not on this project? I would like trying to implement it and do a pull request.

**Comment by xibz** [comment]
@AndreaM16 - Yes, please open a feature request and we welcome PRs!

**Comment by jedzme** [comment]
@xibz , @andream16 , do you guys already have a solution/library for this?

to unmarshal **map[string]DynamoDBAttributeValue** to a specific interface/struct?

**Comment by devotoare** [comment]
This is a top hit on google when searching for a solution and I would also be interested in one.

**Comment by epitka-sg** [comment]
There is a package that allows conversion ffrom events.DynamoDBAttributeValue to dynamodb.AttributeValue

https://pkg.go.dev/github.com/aereal/go-dynamodb-attribute-conversions/v2

I created func to unmarshal it any interface provided it matches. This made it possible to write unit test

```
func Unmarshal(attribute map[string]events.DynamoDBAttributeValue, out interface{}) error {

	av := ddbconversions.AttributeValueMapFrom(attribute)

	return attributevalue.UnmarshalMap(av, out)
}
```
