### ISSUE TITLE
Why do I need an hour to figure out how to send an email using this sdk ? 

### ISSUE THREAD

**Issue by winteraz** [aws/aws-sdk-go-v2#143]
Can't you provide some sensible defaults (i.e. if no EndpointResolver is provided in aws.Config, use the default one) ???? Can't you provide a  idiomatic Go SDK instead of this generated  mess?

**Comment by xibz** [comment]
Hello @winteraz, thank you for reaching out to us. One of the philosophies we decided to take with V2 is to do a lot less magic and have things be explicit. You can find how to use the SDK [here](https://github.com/aws/aws-sdk-go-v2) for getting started. It's toward the bottom, but shows how to find the defaults.
