### ISSUE TITLE
No NewDBClusterAvailableWaiter available - rds

### ISSUE THREAD

**Issue by thiagosantosleite** [aws/aws-sdk-go-v2#1436]
Aurora serverless does have instances so I can not use NewDBInstanceAvailableWaiter. Please provide a NewDBClusterAvailableWaiter

**Comment by RanVaknin** [comment]
Hi @thiagosantosleite ,

I see this issue is super old and never got addressed. [We do have that waiter now. ](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds@v1.39.0#NewDBClusterAvailableWaiter)

Thanks,
Ran
