### ISSUE TITLE
SES (v1 and v2) Trying to send using "To address" instead of "From address"

### ISSUE THREAD

**Issue by evanlurvey** [aws/aws-sdk-go-v2#1437]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When trying to send an email from an address using the v2 sdk it uses my destination ToAddresses instead of my Source.

**Version of AWS SDK for Go?**
github.com/aws/aws-sdk-go-v2/service/ses v1.6.1
github.com/aws/aws-sdk-go-v2/service/sesv2 v1.5.1
Both fail in the same way

**Version of Go (`go version`)?**
1.17.1

**To Reproduce (observed behavior)**
```go
package main

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ses"
	"github.com/aws/aws-sdk-go-v2/service/ses/types"
)
var FromAddress = "support@mydomainthatsverified.com"

func main() {
	cfg, _ := config.LoadDefaultConfig(context.TODO())
	sesc := ses.NewFromConfig(cfg)

	body := "Please work."
	subject := "Test email"

	r, err := sesc.SendEmail(context.TODO(), &ses.SendEmailInput{
		Destination: &types.Destination{
			ToAddresses: []string{
				"myemail@email.com",
			},
		},
		Source: &FromAddress,
		Message: &types.Message{
			Subject: &types.Content{
				Data: &subject,
			},
			Body: &types.Body{
				Text: &types.Content{
					Data: &body,
				},
			},
		},
	})

	fmt.Print(r, err)
}
```

Response:
```
<nil> operation error SES: SendEmail, https response error StatusCode: 400, RequestID: 3a87d1e2-e9d0-4ba7-8b84-4a9f7da2ed20, MessageRejected: Email address is not verified. The following identities failed the check in region US-EAST-2: myemail@email.com
```
**Expected behavior**
I expect the email to send from the Source address rather than the To address.

**Additional context**
I have tested using ses and sesv2 in the aws-sdk-go-v2

**Comment by evanlurvey** [comment]
This is an operator error / some bad error handling. This was actually due to my account being in sandbox mode.

**Comment by skmcgrail** [comment]
No worries @evanlurvey moving to mark this issue as resolved then.
