### ISSUE TITLE
Documentation issue for S3Uri in InputDataConfig

### ISSUE THREAD

**Issue by ZackMitkin** [aws/aws-sdk-go-v2#1440]
**Describe the issue with documentation**
`InputDataConfig` for `StartEntitiesDetectionJob` documentation states that S3Uri should be prefixed with S3://bucketname/prefix, but when I do that I get a `ValidationException` with this message:
`2 validation errors detected: Value 'S3://mybucket/tmp/nlp/input/3e136ed6-c994-41dc-9258-36b1f16f1f13/interaction-4745004.txt' at 'inputDataConfig.s3Uri' failed to satisfy constraint: Member must satisfy regular expression pattern: s3://[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9](/.*)?; Value 'S3://mybucket/tmp/nlp/output/3e136ed6-c994-41dc-9258-36b1f16f1f13/interaction-4745004.txt' at 'outputDataConfig.s3Uri' failed to satisfy constraint: Member must satisfy regular expression pattern: s3://[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9](/.*)?`

**To Reproduce (observed behavior)**
```
jobResp, err := client.StartEntitiesDetectionJob(context.Background(), &comprehend.StartEntitiesDetectionJobInput{
		DataAccessRoleArn: aws.String("arn:aws:iam::<accountNum>:role/ComprehendDataAccessRole"),
		InputDataConfig: &types.InputDataConfig{
			S3Uri:       aws.String("S3://mybucket/tmp/nlp/output/3e136ed6-c994-41dc-9258-36b1f16f1f13/interaction-4745004.txt"),
			InputFormat: "ONE_DOC_PER_FILE",
		},
		LanguageCode: "en",
		OutputDataConfig: &types.OutputDataConfig{
			S3Uri: aws.String(bucketPrefix + outputFileKey),
		},
	})
```

**Expected behavior**
Docs should be updated or this error should not be returned.

**Screenshots**

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @ZackMitkin ,
Sorry for the slow response, can you provide a link to where exactly in the documentation did you see the typo?
