### ISSUE TITLE
dynamodb: QueryPaginator constructor does not respect the ExclusiveStartKey param

### ISSUE THREAD

**Issue by fedonev** [aws/aws-sdk-go-v2#1452]
The dynamodb `QueryPaginator` ignores `params.ExclusiveStartKey` in the constructor.

I believe a simple change to `NewQueryPaginator` will fix the issue:   need to initialise the `nextToken` attribute.

### Expected
The paginator's  initial `NextPage` call should return items beginning with the record after the `ExclusiveStartKey`.

### Observed
The first `NextPage` call returns items as if no start key had been passed.  (I am using the latest `dynamodb` package v1.5.1 in a lambda function)

### Diagnosis
I believe the root cause is that `nextToken` is not initialised  [in the QueryPaginator constructor](https://github.com/aws/aws-sdk-go-v2/blob/a930583ec3794253f8fb7bc5cc099e3cda8a355f/service/dynamodb/api_op_Query.go#L560-L566).  As such, `nextToken` is always nil on the first call to [NextPage](https://github.com/aws/aws-sdk-go-v2/blob/a930583ec3794253f8fb7bc5cc099e3cda8a355f/service/dynamodb/api_op_Query.go#L573-L580). 

### Fix
I believe the fix is a one-line addition to the constructor to initialise `nextToken` to `params.ExclusiveStartKey`:

```go
// NewQueryPaginator returns a new QueryPaginator
func NewQueryPaginator(client QueryAPIClient, params *QueryInput, optFns ...func(*QueryPaginatorOptions)) *QueryPaginator {
	if params == nil {
		params = &QueryInput{}
	}


	options := QueryPaginatorOptions{}
	if params.Limit != nil {
		options.Limit = *params.Limit
	}


	for _, fn := range optFns {
		fn(&options)
	}


	return &QueryPaginator{
		options:   options,
		client:    client,
		params:    params,
		firstPage: true,
                nextToken: params.ExclusiveStartKey  // <-- add this line to initialise nextToken
	}
}
```

**Comment by marc-ostrow** [comment]
I think it's a matter of perspective.  My impression and current usage is that the QueryPaginator is simply a lightweight [helper](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/#using-paginators), most probably intended to be used to start and walk a query till all data has been consumed, or at least until you find what you're looking for.  If you want the ability to page, end-to-end, just use query, and deal with untokenizing state necessarily to setup ExclusiveStartKey and tokenizing LastEvaluatedKey in state returned from your backend.

**Comment by fedonev** [comment]
@marc-ostrow - fair enough, but if the go SDK ignores `ExclusiveStartKey` by design, it would seem the fix is remove the param from the input type.  Accepting a param that is silently ignored does not seem like the best design.

I still claim the issue is a bug.  Let's look at perspective of the other language SDKs.  I checked the AWS JS SDK and boto3.  Both implement the query paginator with an optional starting token  as the initial starting key, as I have proposed above.

[AWS JS SDK v3 paginateQuery](https://github.com/aws/aws-sdk-js-v3/blob/0dd68ef8b04ea0e96e43b05a9a10221e433fdf86/clients/client-dynamodb/src/pagination/QueryPaginator.ts#L30-L55)
```typescript
// paginateQuery function excerpt
// this line is missing from the current go implementation
let token: typeof input.ExclusiveStartKey | undefined = config.startingToken || undefined;
```

[boto3 v1.19.8](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Paginator.Query)
```python
# paginator documentation excerpt
# paginator = client.get_paginator('query')
# paginator.paginate takes a config arg, like the js:

PaginationConfig={
    'MaxItems': 123,
    'PageSize': 123,
    'StartingToken': 'string' # A token to specify where to start paginating. This is the NextToken from a previous response.
}
```

**Comment by marc-ostrow** [comment]
@fedonev - I agree, it's easy to see that ignoring ExclusiveStartKey when starting out, is an omission on the Paginator's implementation.  I  presumed the intention of this lightweight helper/wrapper was to make it easy to consume an entire query (or scan for that matter), hiding the details of moving LastEvaluatedKey to ExclusiveStartKey, as that's all it really does.

Btw, both the Query and Scan Paginators suffer this omission.  Maybe, why not create a PR with this simple "fix" to both QueryPaginator and ScanPaginator constructors?

**Comment by skmcgrail** [comment]
Marking this issue resolved, a fix was released on [12/21/2021](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-12-21).
