### ISSUE TITLE
KinesisVideoSignaling: GetIceServerConfig method fails to resolve endpoint

### ISSUE THREAD

**Issue by kreddyio** [aws/aws-sdk-go-v2#1456]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I'm facing an issue similar to https://github.com/aws/aws-cli/issues/5857

Comment from user `stobrien89` states the following:
>Apparently, the Golang and JS SDKs have logic which works around the need for a separate API call to retrieve the endpoint url, so I'm looking into how they're handling that as well.

I'm currently testing the same using Golang SDK V2  and I'm having the same issue. I thought maybe it was specific to SDK V2 so I tried Version V1 too.

In either case, I notice that the request is going to `POST https://kinesisvideo.us-west-2.amazonaws.com/v1/get-ice-server-config` without resolving the endpoint correctly.

**Version of AWS SDK for Go?**
`v1.9.1`

**Version of Go (`go version`)?**
`go version go1.15.12 darwin/amd64`

**To Reproduce (observed behavior)**

Relevant snippets:

SDK V2:
```go
        channelARN := "sample_channel"
        cfg, err := awsConfig.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Panic().Err(err).Msg("Unexpected error creating AWS client!")
	}
        
        KVSSignalClient := kinesisvideosignaling.NewFromConfig(cfg)
        getIceConfigOut, err := KVSSignalClient.GetIceServerConfig(
		context.TODO(),
		&kinesisvideosignaling.GetIceServerConfigInput{
			ChannelARN: aws.String(channelARN),
			ClientId:   aws.String("kishan"),
			Service: types2.ServiceTurn,
		},
	)
```

SDK V1:
```go
        sess, err := session.NewSession()
	if err != nil {
		log.Panic().Err(err).Msg("Unexpected error creating AWS client V1!")
	}
        channelARN := "sample_channel"
	KVSSignalClientV1 := kinesisvideosignalingchannels.New(sess)
	getIceConfigOut, err := KVSSignalClientV1.GetIceServerConfig(
		&kinesisvideosignalingchannels.GetIceServerConfigInput{
			ChannelARN: aws.String(channelARN),
			ClientId:   aws.String("kishan"),
			Service: aws.String("TURN"),
		},
	)
```

**Expected behavior**
It is expected that the call works and returns the IceServerConfig for the channel.

**Additional context**
I can confirm this is not a permission issue with the credentials as I've already confirmed it works using AWS CLI.
```
aws kinesisvideo get-signaling-channel-endpoint --channel-arn  <channel_arn> --single-master-channel-endpoint-configuration Protocols=WSS,HTTPS,Role=VIEWER
aws kinesis-video-signaling get-ice-server-config --channel-arn <channel_arn> --endpoint-url <output_from_line_above>
```
In the [AWS documentation](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_AWSAcuitySignalingService_GetIceServerConfig.html) for this call it states the following:
```
Before using this API, you must call the GetSignalingChannelEndpoint API to get an endpoint. You then specify the endpoint and region in your GetIceServerConfig API request.
```
However, there is no provision in the `GetIceServerConfigInput` struct to add the endpoint information as the definition is as follows:
```go
type GetIceServerConfigInput struct {

	// The ARN of the signaling channel to be used for the peer-to-peer connection
	// between configured peers.
	//
	// This member is required.
	ChannelARN *string

	// Unique identifier for the viewer. Must be unique within the signaling channel.
	ClientId *string

	// Specifies the desired service. Currently, TURN is the only valid value.
	Service types.Service

	// An optional user ID to be associated with the credentials.
	Username *string

	noSmithyDocumentSerde
}
```

On another note, I'm noticing the exact same behavior on [GetHLSStreamingSessionURL](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetHLSStreamingSessionURL.html) where the client fails to resolve endpoint properly.

Please advise if there's something to be done before making these calls.

**Comment by KaibaLopez** [comment]
Hi @kreddyio ,
So I think there is a confusion on where the endpoint goes, it is not really meant to go as part of the input, but as a custom endpoint in the client . 
So technically you'd have to do the `get-signaling-channel-endpoint` and then override the KVS client's endpoint using the endpoint you got as a custom endpoint.... 
Something like this should work:
```go
cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		panic(err)
	}

	client := kinesisvideosignaling.NewFromConfig(cfg)

	output, err := client.GetIceServerConfig(context.TODO(), &kinesisvideosignaling.GetIceServerConfigInput{
		// API Parameters
	}, func(options *kinesisvideosignaling.Options) {
		options.EndpointResolver = kinesisvideosignaling.EndpointResolverFromURL("https://signaling-channel-endpoint")
	})
```
Let me know if that works for you.

**Comment by kreddyio** [comment]
@KaibaLopez, thanks for the update! I can confirm this works. Closing this issue.
