### ISSUE TITLE
[SageMaker FeatureStore] BatchGetRecord does not work

### ISSUE THREAD

**Issue by momilo** [aws/aws-sdk-go-v2#1461]
### Describe the bug
There is a major bug in [Sagemaker FeatureStore Client](github.com/aws/aws-sdk-go-v2/service/sagemakerfeaturestoreruntime). When using `BatchGetRecord`, it always returns an empty slice of records and nil error, making the function unusable at all.

###  Bug Analysis
Debugging http response reveals that AWS API returns the following response:
`{"Output":{"__type":"com.amazon.coral.service#UnknownOperationException"},"Version":"1.0"}`

Detailed analysis reveals that:
- Go SDK (`aws-sdk-go-v2`) specifies in the request headers `content-type` as `application/json`; this is in line with the (unfortunately erroneous) [documentation](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_feature_store_BatchGetRecord.html) 
- Python SDK and AWS CLI, which do work on the very same machine, send the request with **no** `content-type` specified, and successfully return the values expected

####  Immediate Fix Recommendation
It can be shown in a replicable manner that by removing/commenting-out [line 47](https://github.com/aws/aws-sdk-go-v2/blob/main/service/sagemakerfeaturestoreruntime/serializers.go#L47) in `service/sagemakerfeaturestoreruntime/serializers.go` , the request succeeds.

It is therefore recommended that the API specification in `aws-sdk-go-v2` is aligned with _the actual_ API.

I am not entirely familiar with _Smithy_, but I would imagine that this could be easily achieved by adding an appropriate override to [awsmodels/sagemakerfeaturestoreruntime2020-07-01.json](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/aws-models/sagemakerfeaturestoreruntime.2020-07-01.json), specifically to [traits of the method](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/aws-models/sagemakerfeaturestoreruntime.2020-07-01.json#L105), and re-generating the code, to ensure that the aforementioned line in `serializers.go` is removed.

####  Long Term Fix Recommendation
After a quick-fix is implemented, it is recommended to start the (most likely longer) process of informing the Sagemaker team about the bug in their api request validation implementation, and to align aws cli and python sdk with the documentation.

###  Misc

Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Version of AWS SDK for Go?**

The most current `master`, `Release (2021-10-11)`, and also a number of previous releases.

**Version of Go (`go version`)?**

1.16, 1.17

**To Reproduce (observed behaviour)**

Simply invoke `BatchGetRecord` method on an existing FeatureStore, with the appropriate region specified upon client initialisation.

```
out, err := client.BatchGetRecord(ctx, &sagemakerfeaturestoreruntime.BatchGetRecordInput{
		Identifiers: []types.BatchGetRecordIdentifier{
			{
				FeatureGroupName:               aws.String("myfancystore"),
				RecordIdentifiersValueAsString: recordIDs,
				FeatureNames:                   nil,
			},
		},
	})
```

**Expected behaviour**
I would expect features to be retrieved or an error to be returned. Instead, I receive an empty slice of records - despite the Feature Store being correctly populated. Debugging reveals as per above.

**Comment by nateprewitt** [comment]
Hi @momilo, this should be fixed with SageMaker FeatureStore now. We've merged and released the changes in the CLI 1.21.0/Boto3 1.19.0 as well. Please let us know if you're still experiencing issues, otherwise, this should be set to resolve.
