### ISSUE TITLE
StaticCredentialsProvider and SessionTokens

### ISSUE THREAD

**Issue by th11** [aws/aws-sdk-go-v2#1462]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

Why does the `NewStaticCredentialsProvider` take a SessionToken if the `StaticCredentialsProvider` is a set of credentials that will never expire? By definition, SessionTokens expire. 

```go
// A StaticCredentialsProvider is a set of credentials which are set, and will
// never expire.
type StaticCredentialsProvider struct {
	Value aws.Credentials
}

// NewStaticCredentialsProvider return a StaticCredentialsProvider initialized with the AWS
// credentials passed in.
func NewStaticCredentialsProvider(key, secret, session string) StaticCredentialsProvider {
	return StaticCredentialsProvider{
		Value: aws.Credentials{
			AccessKeyID:     key,
			SecretAccessKey: secret,
			SessionToken:    session,
		},
	}
}
```
https://github.com/aws/aws-sdk-go-v2/blob/f8d40e3f2986a7e65e515c9c3ae06c07efc7d887/credentials/static_provider.go#L21-L37

**Comment by aajtodd** [comment]
Closing as original question has been answered. A static credential provider is easy to recreate should the one shipped with the SDK not meet your needs.
