### ISSUE TITLE
AWS Cli / V2 Go SDK Read Timeout

### ISSUE THREAD

**Issue by markdienerbf** [aws/aws-sdk-go-v2#1465]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x]  I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When using AWS V2 go SDK in a CI/CD environment with resources like localstack, the SDK will not properly handle lambdas that have a panic/sys.exit() behavior.  

**Version of AWS SDK for Go?**
v1.9.2

**Version of Go (`go version`)?**
v1.17.1

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

You can use any of the following lambdas in a localstack environment:

Python Panic Lambda:

import os

def handler(event, context):
    print('Handler-Panic Lambda Called:',event)
    os._exit(22)

Go Panic Lambda:

package main

import (
	"context"
	"syscall"
	"github.com/aws/aws-lambda-go/lambda"
)

func HandleRequest(ctx context.Context, payload interface{}) (interface{}, error) {
	syscall.Exit(22)
	return payload, nil
}

func main() {
	lambda.Start(HandleRequest)
}

NodeJS Panic Lambda:

exports.handler = async function(event,context) {
	console.log('index-panis.js event')
	process.exit(22)
};

You can load these lambas into localstack on a local dev machine with the following syntax:

ENDPOINT=http://localhost:4566/

aws lambda create-function \
	--endpoint-url ${ENDPOINT} \
  --function-name test-python-lambda-echo \
  --handler index-echo.handler \
  --role whatever \
	--runtime python3.8 \
	--code S3Bucket="__local__",S3Key="${PWD}/python-lambdas"
	
awslocal lambda create-function \
    --handler index-panic.handler \
  	--function-name test-node12-lambda-panic \
    --role whatever \
    --runtime nodejs12.x \
		--code S3Bucket="__local__",S3Key="${PWD}/node-lambdas"		

awslocal lambda create-function \
    --handler index-panic.handler \
  	--function-name test-node14-lambda-panic \
    --role whatever \
    --runtime nodejs14.x \
		--code S3Bucket="__local__",S3Key="${PWD}/node-lambdas"		

aws lambda create-function \
	--endpoint-url ${ENDPOINT} \
  --function-name test-go-lambda-panic \
  --handler go-panic \
  --role whatever \
	--runtime go1.x \
  --zip-file fileb://go-panic.zip 	
	
You can call the lambda from the normal AWS Cli command line utility and the behavior will be the same as AWS V2 go SDK

aws lambda invoke --endpoint-url ${ENDPOINT} --function-name test-go-lambda-panic --payload '{"tag":"golang"}' --cli-binary-format raw-in-base64-out ./out-go-panic.json

aws lambda invoke --endpoint-url ${ENDPOINT} --function-name test-python-lambda-panic --payload '{"tag":"golang"}' --cli-binary-format raw-in-base64-out ./out-python-panic.json

aws lambda invoke --endpoint-url ${ENDPOINT} --function-name test-node12-lambda-panic --payload '{"tag":"golang"}' --cli-binary-format raw-in-base64-out ./out-node12-panic.json

aws lambda invoke --endpoint-url ${ENDPOINT} --function-name test-node14-lambda-panic --payload '{"tag":"golang"}' --cli-binary-format raw-in-base64-out ./out-node14-panic.json

**Expected behavior**
There should be a more controlled timeout mechanism and the library should not fallback to net/http Read timeout which takes several minutes to trigger a read timeout.

If this is happening with localstack, then it can happen with production lambdas since the SDK does not take into account getting ghosted by the lambda invoke( ) call.

**Additional context**
None

**Comment by skmcgrail** [comment]
This repository is for the AWS SDK for Go V2 product, you will need to create an issue at [aws-lambda-go](https://github.com/aws/aws-lambda-go) as this issue is specifically to that product.
