### ISSUE TITLE
Where is NormalizeBucketLocation?

### ISSUE THREAD

**Issue by hirose31** [aws/aws-sdk-go-v2#1473]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

aws-sdk-go-v1 has [NormalizeBucketLocation](https://github.com/aws/aws-sdk-go/blob/f259b6824eacd9b534aab106d5505a0c023a5fde/service/s3/bucket_location.go#L23) but it seems aws-sdk-go-v2 does not have this function.

Where is NormalizeBucketLocation in aws-sdk-go-v2? or how can I do the same thing with NormalizeBucketLocation in aws-sdk-go-v2?

**Comment by KaibaLopez** [comment]
Hi @hirose31 ,
us-east-1 returning empty is the expected behavior for the api call, the same documentation states:
> Buckets in Region us-east-1 have a LocationConstraint of null. 

I could try and go on about why that is the case, but in short it is an artifact left in to keep compatibility with old s3 implementations.

I also just tested the call for a bucket on eu-north-1 as well as eu-central-1 and the returns match so...  is there another specific region you are having problems with?

**Comment by hirose31** [comment]
I couldn't confirm that the `"EU"` was returned, but as described in the API document, I think that normalization processing of `"" -> "us-east-1"` and `"EU" -> "eu-west-1"` is necessary.

So I would like aws-sdk-go v2 to provide NormalizeBucketLocation as well.

**Comment by KaibaLopez** [comment]
So, I don't think we would take this as a feature request, it'd be just too low priority in our backlog.... But, we could take a PR if you'd like to try contributing the code.

**Comment by hirose31** [comment]
Using `manager.GetBucketRegion` instead of `s3.Client.GetBucketLocation` solved my problem.

`manager.GetBucketRegion` uses the `HeadBucket` API instead of `GetBucketLocation` API and returns the region name with reference to its response header `x-amz-bucket-region`. Even for `us-east-1`, `"us-east-1"` was returned instead of `""`.

Thanks for your support.
