### ISSUE TITLE
Considering better error management in s3 manager

### ISSUE THREAD

**Issue by PumpkinSeed** [aws/aws-sdk-go-v2#1476]
**Is your feature request related to a problem? Please describe.**
I wanted to return our own custom errors based on the errors returned by [s3](https://github.com/aws/aws-sdk-go-v2/tree/main/feature/s3/manager) library. I noticed that:

1. The actual errors are all unexported, so there is NO way to check them with Go's built-in tools like `errors.Is` or `errors.As`.
2. All of the errors wrapped into structs and there isn't natural flow of error returning, so it's nearly impossible to discover what the possible error messages what I will get. 

**Describe the solution you'd like**

- Export errors so we can check them with built-in `errors` functionalities.
- Create an errors.go where those errors are collected and easy to access.

**Comment by KaibaLopez** [comment]
Hi @PumpkinSeed ,
Hmmm not sure if this is something we'd be able to do any time soon but... Have you tried any workaround? Like this might not be exactly what you mean but you could potentially get the errors using smithy like:
```go
if err != nil {
	var ae smithy.APIError
	if errors.As(err, &ae) {
		log.Printf("code: %s, message: %s, fault: %s", ae.ErrorCode(), ae.ErrorMessage(), ae.ErrorFault().String())
	}
	log.Fatal(err)
}
```
Would this work for you? If not, why not ? 
Let me know
