### ISSUE TITLE
need find image where i can quickstart

### ISSUE THREAD

**Issue by yoshiakiley** [aws/aws-sdk-go-v2#1482]
like aws console. user can chose image to quickstart
but in sdk, i can't filter quickstart image

**Comment by yoshiakiley** [comment]
when i list image by sdk, it is so many image (about 90000 images ) that i have no idea which image i should chose

**Comment by KaibaLopez** [comment]
Hi @yoshiakiley ,
I... am not sure what you mean here, can you show me the code you are using?
