### ISSUE TITLE
Add export `EventSubscriptionName` for `EventSubscription` response

### ISSUE THREAD

**Issue by chenrui333** [aws/aws-sdk-go-v2#1487]
**Is your feature request related to a problem? Please describe.**
Instead of exporting `EventSubscriptionArn`, I think exporting `EventSubscriptionName` would be better. 

The resource name is also used for resource import in here as well.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_event_subscription

**Describe the solution you'd like**
extract the eventSubscriptionName from `EventSubscription`

**Comment by KaibaLopez** [comment]
Hi @chenrui333 ,
So, these are usually defined by the service models, like if the response from the api call doesn't expose event subscription name there isn't much we can do from the SDK side. But honestly I have no idea what api call for what service (I assume dynamodb ? ) so before I can say for sure this can or can't be done, I need more info.
Preferably, code sample on your use case, or at least a sample that shows what the call does now and what you would want it to do.

**Comment by chenrui333** [comment]
@KaibaLopez The usage case is more on the terraform side (because when I wanted to do the resource import, I need to use the name, right now, I have parse the ARN to get that name), does that make sense? Thanks!
