### ISSUE TITLE
Steps to create `AWS access keys` are not clear

### ISSUE THREAD

**Issue by IAmSurajBobade** [aws/aws-sdk-go-v2#1492]
### Describe the issue with documentation

Hello,

I am new to AWS and am trying [Getting Started with the AWS SDK for Go V2](https://aws.github.io/aws-sdk-go-v2/docs/getting-started/) tutorial.
However, the steps mentioned in the [Get your AWS access keys](https://aws.github.io/aws-sdk-go-v2/docs/getting-started/#to-get-your-access-key-id-and-secret-access-key) are not clear or are not updated.

- On the navigation menu, choose Users.
- Choose your IAM user name (not the check box).
- Open the Security credentials tab, and then choose Create access key.

Issue 1:
When I select Users from the navigation menu, an empty list of users is displayed. Should this be `Create` instead of `Choose`?

Issue 2:
I could not find the `Security credentials tab` mentioned in the last step.

### Suggestion

Update the documentation considering a new user is using it. Thanks.

### AWS Go SDK version used

aws-sdk-go-v2

**Comment by KaibaLopez** [comment]
Hi @IamSuajBobade ,
Yea I guess the instructions assumes that an IAM user has been created before trying to get the credentials.... I think we can add a mention or link for the instruction on how to do that.

As for the security credentials tab... it's one of the tabs shown when you select a user (not the checkbox), along with "Permissions/Groups/Tags/Security credentials/Access Advisor". I'm not sure how else I would describe it, but I'm open to suggestions there.
I'll see about the first thing for now and thanks for the feedback!
