### ISSUE TITLE
Pass KeyTag to dynamo attributevalue marshalling

### ISSUE THREAD

**Issue by radutopala** [aws/aws-sdk-go-v2#1494]
### Describe the feature

As a AWS SDK go v2 user, I want to be able to set a custom `KeyTag` on `attributevalue.MarshalMap`, so I can keep the compatibility with previous v1 SDK.

### Is your Feature Request related to a problem?

Currently the `attributevalue.MarshalMap` doesn't accept the Encoder options, even though it is possible without breaking changes.

By default, `KeyTag` is set to `dynamoav`. Passing the Encoder options will allow setting up a KeyTag like `json`.

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Go SDK version used

v2

### Go version used

1.16

**Comment by jasdel** [comment]
Thanks for taking the time to create this issue, and PR. I left feedback in the PR. Adding a new set of `MarshalWithOptions` and similarly `UnmarshalWithOptions` functions to the package would allow this functionality to be used without breaking the existing function signatures.
