### ISSUE TITLE
ExclusiveStartKey on NewScanPaginator not working

### ISSUE THREAD

**Issue by Zeedinstein** [aws/aws-sdk-go-v2#1503]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

It seems the ExclusiveStartKey on the ScanInput for NewScanPaginator doesn't affect where the can starts. I'm trying to create a simple paginated API but every time I pass the ExclusiveStartKey it returns the same items as the previous request.

### Expected behavior

The ExclusiveStartKey should be used as the start key for the scan.

### Current behavior

The ExclusiveStartKey is ignored 

### Steps to Reproduce

You'll need a local instance of Dynamodb running. I've created a test.go file that shows what is happening. 

```
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

type PaginateID struct {
	ID string `dynamodbav:"id" json:"id"`
}

func main() {
	lastKey := PaginateID{ID: "ae82a99d-486e-11ec-a7a7-0242ac110002"}

	key, err := attributevalue.MarshalMap(lastKey)
	if err != nil {
		fmt.Println(err)
		return
	}

	cfg, err := config.LoadDefaultConfig(context.TODO(), func(o *config.LoadOptions) error {
		o.Region = os.Getenv("REGION")
		return nil
	})
	if err != nil {
		fmt.Println(err)
		return
	}

	svc := dynamodb.NewFromConfig(cfg, func(o *dynamodb.Options) {
		o.EndpointResolver = dynamodb.EndpointResolverFromURL("http://localhost:8000")
	})

	input := &dynamodb.ScanInput{
		TableName:         aws.String("TABLE_NAME"),
		Limit:             aws.Int32(1),
		ExclusiveStartKey: key,
	}

	paginator := dynamodb.NewScanPaginator(svc, input)

	if paginator.HasMorePages() {
		data, err := paginator.NextPage(context.TODO())
		if err != nil {
			fmt.Println(err)
			return
		}

		fmt.Println(data.Items[0]["id"])
		fmt.Println(data.LastEvaluatedKey["id"])
	}
}
```

When I run this test code. I get this output:
```
&{ae82a99d-486e-11ec-a7a7-0242ac110002 {}}
&{ae82a99d-486e-11ec-a7a7-0242ac110002 {}}
```

So the item that is returned is the same Id that I am passing to the ScanInput.ExclusiveStartKey. This means it's not starting from the ExclusiveStartKey. The scan is starting from the beginning every time. 

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2/service/dynamodb v1.8.0

### Compiler and Version used

go version go1.16.6 

### Operating System and version

macOS Big Sur 11.6

**Comment by KaibaLopez** [comment]
Hi @Zeedinstein ,
Thanks for pointing this out to us, we will take a closer look!

**Comment by skmcgrail** [comment]
Marking this issue resolved, a fix was released on [12/21/2021](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-12-21).

**Comment by kkolur** [comment]
@skmcgrail Hi, I was looking through the paginators again and the HasMorePages() method is inconsistent across some of the files. In [api_op_Query.go](https://github.com/aws/aws-sdk-go-v2/blob/release-2021-12-21/service/dynamodb/api_op_Query.go#L571) the current condition is :

`return p.firstPage || p.nextToken != nil`. 

Here we do not check that the length of the nextToken is not 0, but in [api_op_ListContributorInsights.go](https://github.com/aws/aws-sdk-go-v2/blob/release-2021-12-21/service/dynamodb/api_op_ListContributorInsights.go#L181), we do correctly check for the length of the nextToken 

`return p.firstPage || (p.nextToken != nil && len(*p.nextToken) != 0)`

Can we update all of the HasMorePages() to the condition where we check for the length of the nextToken as well?
