### ISSUE TITLE
connect: GetMetricData increase time range

### ISSUE THREAD

**Issue by s2qts** [aws/aws-sdk-go-v2#1508]
### Describe the feature

Increase GetMetricData API time range limit from 24 hours to 30 days.

### Is your Feature Request related to a problem?

Currently, GetMetricData API allows to query metrics only for the last 24 hours. 

According to these [docs](https://github.com/aws/aws-sdk-go-v2/blob/main/service/connect/api_op_GetMetricData.go#L95), "**Historical metrics are available only for 24 hours**". However, this seems to be not true. Historical metrics are available for longer period of time and you can query them for up to 30 days in Amazon Connect Dashboard UI in Historical Metrics tab. 

![image](https://user-images.githubusercontent.com/11569140/142947139-9baf6000-916f-4c4d-9ddb-50462f84644d.png)

Is there a reason why the same limitations cannot be implemented in SDK?

### Describe alternatives you've considered

The only way to get historical metrics though SDK that I can think of would be to develop a cron that would ping every n minutes/hours GetMetricData API and store the data somewhere in a database.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

v1.11.1

### Go version used

go version go1.17 linux/amd64

**Comment by KaibaLopez** [comment]
Hi @s2qts ,
This is not really a feature request we would be able to implement from our side, the go sdk depends on the limitations of the aws service APIs and the [API guide states](https://docs.aws.amazon.com/connect/latest/APIReference/API_GetMetricData.html#API_GetMetricData_RequestSyntax) that it will only keep records of up to 24 hours.
Now your idea of using a cron to store it is something you could do, but not something we could implement as part of the SDK.
