### ISSUE TITLE
aws-sdk-go-v2/service/kinesis 1.9.1 missing `NewFromConfig(cfg aws.Config)`

### ISSUE THREAD

**Issue by SeenYang** [aws/aws-sdk-go-v2#1512]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

in latest version 1.9.1, the kinesis package missing `.NewFromConfig(cfg aws.Config)` method.
Version 1.9.0 seems ok.

### Expected behavior

```go
cfg, err := config.LoadDefaultConfig(
		context.TODO(),
		config.WithRegion(*awsRegion),
		config.WithEndpointResolver(resolver),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider("user", "pass", "token")),
	)
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

var client = kinesis.NewFromConfig(cfg)
```
Above code should not throw error.

### Current behavior

![image](https://user-images.githubusercontent.com/15993720/143972679-6aa9bb30-8788-4ffe-abca-32a288f6f107.png)

### Steps to Reproduce

1. import latest `aws-sdk-go-v2/service/kinesis`
2. load config use `config.LoadDefaultConfig()`
3. Use `client := kinesis.NewFromConfig(cfg)`

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2/service/kinesis v1.9.1

### Compiler and Version used

go 1.17

### Operating System and version

macOS 12.0.1

**Comment by jasdel** [comment]
Thanks for reaching out @SeenYang. Could you provide a sample of the `github.com/aws/aws-sdk-go-v2/service/kinesis` module in your application's `go.mod` file. In addition, what compiler error do you get when you build your application with the above code?

I wasn't able to reproduce the issue with the following sample app. Maybe check and make sure that the V2 SDK's `service/kinesis` is being imported and not the v1 SDK's version. 

```
module jasdel.dev/test

go 1.17

require (
	github.com/aws/aws-sdk-go-v2 v1.11.1 // indirect
	github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.0.0 // indirect
	github.com/aws/aws-sdk-go-v2/config v1.10.3 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.6.3 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.8.1 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.1 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.0.1 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.5.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/kinesis v1.9.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.6.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.11.0 // indirect
	github.com/aws/smithy-go v1.9.0 // indirect
	github.com/jmespath/go-jmespath v0.4.0 // indirect
)
```

```go
package main

import (
	"context"
	"log"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/kinesis"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Fatalf("failed to load config, %v", err)
	}

	_ = kinesis.NewFromConfig(cfg)
}
```

**Comment by SeenYang** [comment]
Hi @jasdel , thanks for reply
As your mention above, I recon it's Goland can't solve it instead of sdk issue.  I will close this issue and thanks for you sample as well..
