### ISSUE TITLE
EndpointResolverWithOptionsFunc is not resolving to endpoint provided but fall back to internal default endpoint

### ISSUE THREAD

**Issue by ArchieY393** [aws/aws-sdk-go-v2#1525]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

```
awsConfig.EndpointResolverWithOptions = aws.EndpointResolverWithOptionsFunc(
          func(service, region string, _ ...interface{}) (aws.Endpoint, error) {
		          return aws.Endpoint{
			          URL:           "http://localhost:8080",
			          SigningRegion: "eu-west-1",
		          }, nil
	          })
```

fallback to "Host: s3.eu-west-1.amazonaws.com" and fails authorisation with error "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records." Instead, it should point to host which is configured as "http://localhost:8080".

PS: The "Host:" log is taken from the setting config.WithClientLogMode(aws.LogRetries|aws.LogRequest)

### Expected behavior

It's expected to use the endpoint provided as host.

Instead, the deprecated version works as expected:

```
awsConfig.EndpointResolver = aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL:           cfg.S3URL,
			SigningRegion: cfg.AWSRegion,
		}, nil
	})
```

Host: localhost:8080

### Current behavior

fallback to "Host: s3.eu-west-1.amazonaws.com" and fails authorisation with error "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records." Instead, it should point to host which is configured "http://localhost:8080"

### Steps to Reproduce

```
awsConfig, err := config.LoadDefaultConfig(
		context.Background(),
		config.WithRegion("eu-west-1"),
		config.WithClientLogMode(aws.LogRetries|aws.LogRequest),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			testAccessKey,
			testSecretKey,
			"",
		)),
)
if err != nil {
	return nil, err
}

awsConfig.EndpointResolverWithOptions = aws.EndpointResolverWithOptionsFunc(func(service, region string, _ ...interface{}) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL:           "http://localhost:8080",
			SigningRegion: "eu-west-1",
		}, nil
})

client := &http.Client{}
client.Timeout = time.Duration(testTimeout) * time.Millisecond

awsConfig.HTTPClient = client

s3Client := s3.NewFromConfig(awsConfig, func(o *s3.Options) {
		o.UsePathStyle = true
})

```
### Possible Solution
It's expected to use the endpoint provided as host.
_No response_

### AWS Go SDK version used

v1.11.2

### Compiler and Version used

o1.17.4

### Operating System and version

Ubuntu 20.10

**Comment by skmcgrail** [comment]
I'm not able to replicate this behavior using this modified snippet:
```
package main

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithRegion("eu-west-1"),
		config.WithClientLogMode(aws.LogRequest|aws.LogRetries),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider("foo", "bar", "")),
	)
	if err != nil {
		panic(err)
	}

	cfg.EndpointResolverWithOptions = aws.EndpointResolverWithOptionsFunc(func(service, region string, options ...interface{}) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL:           "https://localhost:8000",
			SigningRegion: "eu-west-1",
		}, nil
	})

	client := s3.NewFromConfig(cfg)

	_, err = client.GetObject(context.TODO(), &s3.GetObjectInput{
		Bucket: aws.String("somebucket"),
		Key:    aws.String("somekey"),
	}, func(options *s3.Options) {
		options.UsePathStyle = true
	})
	if err != nil {
		panic(err)
	}
}
```

Outputs:
```
SDK 2021/12/09 13:11:08 DEBUG Request
GET /somebucket/somekey?x-id=GetObject HTTP/1.1
Host: localhost:8000
User-Agent: aws-sdk-go-v2/1.11.2 os/macos lang/go/1.17.4 md/GOOS/darwin md/GOARCH/amd64 api/s3/1.21.0
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: a5cbfb1b-1303-469a-bfd0-9fc71de35d9d
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=foo/20211209/eu-west-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=6fa73e3aafb9528c48a23454e875df2258d920bfec0b6aecc36df2a47b505ac6
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211209T211108Z

SDK 2021/12/09 13:11:09 DEBUG retrying request S3/GetObject, attempt 2
SDK 2021/12/09 13:11:09 DEBUG Request
GET /somebucket/somekey?x-id=GetObject HTTP/1.1
Host: localhost:8000
User-Agent: aws-sdk-go-v2/1.11.2 os/macos lang/go/1.17.4 md/GOOS/darwin md/GOARCH/amd64 api/s3/1.21.0
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: a5cbfb1b-1303-469a-bfd0-9fc71de35d9d
Amz-Sdk-Request: attempt=2; max=3
Authorization: AWS4-HMAC-SHA256 Credential=foo/20211209/eu-west-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=2b88f7d1b8c96f60f3be95730a190d83e79726f2d20e1c94134c36aba60fd41b
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211209T211109Z

SDK 2021/12/09 13:11:12 DEBUG retrying request S3/GetObject, attempt 3
SDK 2021/12/09 13:11:12 DEBUG Request
GET /somebucket/somekey?x-id=GetObject HTTP/1.1
Host: localhost:8000
User-Agent: aws-sdk-go-v2/1.11.2 os/macos lang/go/1.17.4 md/GOOS/darwin md/GOARCH/amd64 api/s3/1.21.0
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: a5cbfb1b-1303-469a-bfd0-9fc71de35d9d
Amz-Sdk-Request: attempt=3; max=3
Authorization: AWS4-HMAC-SHA256 Credential=foo/20211209/eu-west-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=c51dd5f8f2afca518f971ced289666378533a8f66895af8b0929df0c5210a4fe
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211209T211112Z

SDK 2021/12/09 13:11:12 DEBUG max retry attempts exhausted, max 3
panic: operation error S3: GetObject, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get "https://localhost:8000/somebucket/somekey?x-id=GetObject": dial tcp [::1]:8000: connect: connection refused
```

The `Host` header indicates the host is getting set as expected.

Can you verify the SDK dependencies in your Go module and provide that here?
```
go mod graph | grep github.com/aws/aws-sdk-go-v2
```

**Comment by ArchanaY** [comment]
github.com/aws/aws-sdk-go-v2@v1.11.2 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2@v1.11.2 github.com/google/go-cmp@v0.5.6
github.com/aws/aws-sdk-go-v2@v1.11.2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/aws/aws-sdk-go-v2/credentials@v1.6.4
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.8.2
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.2
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/aws/aws-sdk-go-v2/service/sso@v1.6.2
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/aws/aws-sdk-go-v2/service/sts@v1.11.1
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2/config@v1.11.0 github.com/google/go-cmp@v0.5.6
github.com/aws/aws-sdk-go-v2/credentials@v1.6.4 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/credentials@v1.6.4 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.8.2
github.com/aws/aws-sdk-go-v2/credentials@v1.6.4 github.com/aws/aws-sdk-go-v2/service/sso@v1.6.2
github.com/aws/aws-sdk-go-v2/credentials@v1.6.4 github.com/aws/aws-sdk-go-v2/service/sts@v1.11.1
github.com/aws/aws-sdk-go-v2/credentials@v1.6.4 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2/credentials@v1.6.4 github.com/google/go-cmp@v0.5.6
github.com/aws/aws-sdk-go-v2/service/s3@v1.6.0 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/service/s3@v1.6.0 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.0.5
github.com/aws/aws-sdk-go-v2/service/s3@v1.6.0 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.0.7
github.com/aws/aws-sdk-go-v2/service/s3@v1.6.0 github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.2.3
github.com/aws/aws-sdk-go-v2/service/s3@v1.6.0 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/service/s3@v1.6.0 github.com/google/go-cmp@v0.5.4
github.com/aws/aws-sdk-go-v2/service/sqs@v1.13.1 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/service/sqs@v1.13.1 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.2
github.com/aws/aws-sdk-go-v2/service/sqs@v1.13.1 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.0.2
github.com/aws/aws-sdk-go-v2/service/sqs@v1.13.1 github.com/aws/smithy-go@v1.9.0
github.com/newrelic/go-agent/v3/integrations/nrawssdk-v2@v1.2.0 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/newrelic/go-agent/v3/integrations/nrawssdk-v2@v1.2.0 github.com/aws/aws-sdk-go-v2/config@v1.1.7
github.com/newrelic/go-agent/v3/integrations/nrawssdk-v2@v1.2.0 github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.2.3
github.com/newrelic/go-agent/v3/integrations/nrawssdk-v2@v1.2.0 github.com/aws/aws-sdk-go-v2/service/lambda@v1.2.3
github.com/newrelic/go-agent/v3/integrations/nrawssdk-v2@v1.2.0 github.com/aws/aws-sdk-go-v2/service/s3@v1.6.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.8.2 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.8.2 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.8.2 github.com/google/go-cmp@v0.5.6
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.2 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.0.2 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.0.2 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.0.2 github.com/google/go-cmp@v0.5.6
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.2 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.5.2 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.5.2 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.5.2 github.com/google/go-cmp@v0.5.6
github.com/aws/aws-sdk-go-v2/service/sso@v1.6.2 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/service/sso@v1.6.2 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.2
github.com/aws/aws-sdk-go-v2/service/sso@v1.6.2 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.0.2
github.com/aws/aws-sdk-go-v2/service/sso@v1.6.2 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.11.1 github.com/aws/aws-sdk-go-v2@v1.11.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.11.1 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.11.1 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.0.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.11.1 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.5.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.11.1 github.com/aws/smithy-go@v1.9.0
github.com/aws/aws-sdk-go-v2@v1.4.0 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2@v1.4.0 github.com/google/go-cmp@v0.5.4
github.com/aws/aws-sdk-go-v2@v1.4.0 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.0.5 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.0.7 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.0.7 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.0.7 github.com/google/go-cmp@v0.5.4
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.2.3 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.2.3 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/aws/aws-sdk-go-v2/credentials@v1.1.7
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.0.7
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/aws/aws-sdk-go-v2/service/sso@v1.1.6
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/aws/aws-sdk-go-v2/service/sts@v1.3.1
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/google/go-cmp@v0.5.4
github.com/aws/aws-sdk-go-v2/config@v1.1.7 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.0.7
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.2.3 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.2.3 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.0.5
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.2.3 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.2.3 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/service/lambda@v1.2.3 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/service/lambda@v1.2.3 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/service/lambda@v1.2.3 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/credentials@v1.1.7 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/credentials@v1.1.7 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.0.7
github.com/aws/aws-sdk-go-v2/credentials@v1.1.7 github.com/aws/aws-sdk-go-v2/service/sso@v1.1.6
github.com/aws/aws-sdk-go-v2/credentials@v1.1.7 github.com/aws/aws-sdk-go-v2/service/sts@v1.3.1
github.com/aws/aws-sdk-go-v2/credentials@v1.1.7 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/credentials@v1.1.7 github.com/google/go-cmp@v0.5.4
github.com/aws/aws-sdk-go-v2/credentials@v1.1.7 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.0.7
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.0.7 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.0.7 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.0.7 github.com/google/go-cmp@v0.5.4
github.com/aws/aws-sdk-go-v2/service/sso@v1.1.6 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/service/sso@v1.1.6 github.com/aws/smithy-go@v1.4.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.3.1 github.com/aws/aws-sdk-go-v2@v1.4.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.3.1 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.0.7
github.com/aws/aws-sdk-go-v2/service/sts@v1.3.1 github.com/aws/smithy-go@v1.4.0

**Comment by ArchieY393** [comment]
I was trying to do basic S3 operations, like GetObject()/ ListBuckets()

**Comment by skmcgrail** [comment]
This issue was fixed in https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-12-02

You can pull in the latest versions using this command in your module:
```
go get -u github.com/aws/aws-sdk-go-v2/...
```

**Comment by ArchieY393** [comment]
Am already on github.com/aws/aws-sdk-go-v2@v1.11.2, pulling to latest version has no effect. Well, I was on github.com/aws/aws-sdk-go-v2@v0.24.0 and updating to latest cropped up this issue. With the latest SDK, using aws.EndpointResolverFunc(), the deprecated version, works perfectly alright.

**Comment by skmcgrail** [comment]
The SDK is now entirely modularized, so you can't just track a single version like `github.com/aws/aws-sdk-go-v2@v1.11.2`. That is only one module, but as the dependency graph indicates you also depend on outdated service clients as well.
