### ISSUE TITLE
API Gateway WebSocket API PostToConnection always times out

### ISSUE THREAD

**Issue by AttilaTheFun** [aws/aws-sdk-go-v2#1534]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

I'm trying to create a set of Golang-container lambda functions to handle websockets from an API Gateway API.

I've been fairly closely following your sample code here:
https://github.com/aws-samples/apigateway-websockets-golang

I'm able to handle the connect and disconnect events correctly, but when I try to post to the connection from my $default route handler, my lambda function always times out. I tried increasing the time limit from 3 seconds to 10 seconds and I'm still getting the same result.

I've provided the source code in the Steps to Reproduce section below.

### Expected behavior

I would expect that the request to API Gateway doesn't time out. If I've configured something incorrectly, it should let me know by throwing an error.

### Current behavior

The request to API Gateway times out without any indication as to what could be wrong.

### Steps to Reproduce

My $default route handler is as follows:
```
package main

import (
	"context"
	"log"
	"net/http"
	"net/url"

	"github.com/attilathefun/utils/awsutils"
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi"
)

// Initialization

func init() {

	// Create the AWS Config
	_ = awsutils.AWSConfig
}

// Handler

// func handleRequest(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
func handleRequest(ctx context.Context, req *events.APIGatewayWebsocketProxyRequest) (events.APIGatewayProxyResponse, error) {

	log.Printf("Handling API Gateway Websocket Proxy Request: %+v", req)
	log.Println()

	// Extract the request information:
	connectionID := req.RequestContext.ConnectionID
	callbackURL := url.URL{
		Scheme: "https",
		Host:   req.RequestContext.DomainName,
		Path:   req.RequestContext.Stage,
	}

	log.Println("Creating API Gateway client for callback URL: ", callbackURL.String())
	apiClient := apigatewaymanagementapi.NewFromConfig(awsutils.AWSConfig, func(o *apigatewaymanagementapi.Options) {
		o.EndpointResolver = apigatewaymanagementapi.EndpointResolverFromURL(callbackURL.String())
	})

	log.Printf("Created API Gateway Client: %+v", apiClient)
	log.Println()

	// Post a message to the connection:
	_, err := apiClient.PostToConnection(context.Background(), &apigatewaymanagementapi.PostToConnectionInput{
		ConnectionId: aws.String(connectionID),
		Data:         []byte("Test Post to Connection"),
	})
	if err != nil {
		log.Println("Short circuiting and returning 500 because failed to post to connection with error: ", err.Error())
		return events.APIGatewayProxyResponse{
			StatusCode: http.StatusInternalServerError,
			Body:       err.Error(),
		}, nil
	}
	log.Println("Posted test message to connection")

	return events.APIGatewayProxyResponse{
		StatusCode: http.StatusOK,
		Body:       "",
	}, nil
}

// Main

func main() {
	lambda.Start(handleRequest)
}
```

The only non-AWS dependency here is my utils package which just handles creating my Default AWS Config from the environment variables. I know that this works because I've used it successfully for other lambda functions.

The logs I've received from CloudWatch are as follows:
```
START RequestId: <REDACTED> Version: $LATEST
--
2021/12/17 04:28:10 Creating AWS Config
2021/12/17 04:28:10 Handling API Gateway Websocket Proxy Request: &{<REDACTED>}
2021/12/17 04:28:10
2021/12/17 04:28:10 Creating API Gateway client for callback URL:  https://<REDACTED>.execute-api.us-west-1.amazonaws.com/production
2021/12/17 04:28:10 Created API Gateway Client: &{options:{APIOptions:[] ClientLogMode:0 Credentials:0xc0000ca800 EndpointOptions:{Logger:<nil> LogDeprecated:false ResolvedRegion: DisableHTTPS:false UseDualStackEndpoint:0 UseFIPSEndpoint:0} EndpointResolver:0x7a7b20 HTTPSignerV4:0xc000074ae0 Logger:0xc0000a8080 Region:us-west-1 Retryer:0xc0001aa000 HTTPClient:0xc000074a80}}
2021/12/17 04:28:10
END RequestId: <REDACTED>
REPORT RequestId: <REDACTED>	
Duration: 10008.16 ms	
Billed Duration: 10470 ms	
Memory Size: 128 MB	
Max Memory Used: 19 MB	
Init Duration: 461.07 ms
2021-12-17T04:28:20.765Z <REDACTED> Task timed out after 10.01 seconds
```
(I tried to redact any potentially sensitive information.)

### Possible Solution

I wasn't sure whether or not I needed to append "/@connections" to the API url so I tried it both ways with the same result.
I also wasn't sure whether I should use the provided context when making the API request or a new one so I tried both, also with the same result.

### AWS Go SDK version used

github.com/aws/aws-lambda-go v1.27.0 	github.com/aws/aws-sdk-go-v2 v1.11.2 	github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi v1.6.2

### Compiler and Version used

go 1.17.3

### Operating System and version

AWS Lambda with an Alpine 3.15 container image + Go binary

**Comment by KaibaLopez** [comment]
Hi @AttilaTheFun ,
While I go and set this up for testing it, could you verify something ?
You mentioned that you tried increasing the timeout from 3 to 10 but I don't see that on the code you provided to reproduce... just to verify, did your attempt look something like this?
```golang
ctx := context.TODO()
client := apigatewaymanagementapi.NewFromConfig(cfg)
ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
defer cancel()
_, err := apiClient.PostToConnection(ctx, &apigatewaymanagementapi.PostToConnectionInput{/*input stuff*/})
```

**Comment by AttilaTheFun** [comment]
Hi @KaibaLopez I finally figured it out - API Gateway doesn't work if you call it from a Lambda function within a VPC. When I removed the VPC configuration from the Lambda, I was able to get it to work with the following client configuration:

```
	apiClient := apigatewaymanagementapi.NewFromConfig(awsutils.AWSConfig, func(o *apigatewaymanagementapi.Options) {
		o.EndpointResolver = apigatewaymanagementapi.EndpointResolverFromURL(callbackURL.String())
	})
```

I really wish that this would have returned an error rather than just timing out as it would have saved a lot of time debugging.
