### ISSUE TITLE
Can't obtain proper credentials within AWS Batch container

### ISSUE THREAD

**Issue by pavel-popov** [aws/aws-sdk-go-v2#154]
### Version of AWS SDK for Go?
```
  name = "github.com/aws/aws-sdk-go-v2"
  revision = "b8e7febd4b80c6517240e473410b54d4e63fed1d"
  version = "v2.0.0-preview.2"
```

### Version of Go (`go version`)?
`go version go1.10 darwin/amd64`

### What issue did you see?
I'm creating AWS Batch job running go app in a container. The app works correctly on my desktop (both in local and in container mode) using `.aws/credentials`, but doesn't work when I run it as AWS Batch job with Role attached.

The configuration is obtained:
```{Region:eu-west-1 Credentials:0xc42012e500 EndpointResolver:0xc420101a00 HTTPClient:0xc42015fce0 Handlers:{Validate:{list:[{Name:core.ValidateEndpointHandler Fn:0x710070} {Name:core.ValidateParametersHandler Fn:0x7101a0}] AfterEachFn:0x6bd200} Build:{list:[{Name:core.SDKVersionUserAgentHandler Fn:0x6c5720}] AfterEachFn:0x6bd200} Sign:{list:[{Name:core.BuildContentLengthHandler Fn:0x70f280}] AfterEachFn:<nil>} Send:{list:[{Name:core.ValidateReqSigHandler Fn:0x70f5c0} {Name:core.SendHandler Fn:0x70f7c0}] AfterEachFn:<nil>} ValidateResponse:{list:[{Name:core.ValidateResponseHandler Fn:0x70fa30}] AfterEachFn:<nil>} Unmarshal:{list:[] AfterEachFn:<nil>} UnmarshalMeta:{list:[] AfterEachFn:<nil>} UnmarshalError:{list:[] AfterEachFn:<nil>} Retry:{list:[] AfterEachFn:<nil>} AfterRetry:{list:[{Name:core.AfterRetryHandler Fn:0x70fba0}] AfterEachFn:<nil>} Complete:{list:[] AfterEachFn:<nil>}} Retryer:<nil> LogLevel:0 Logger:0xc42000c110 EnforceShouldRetryCheck:false DisableRestProtocolURICleaning:false}```
but resources are not available - I tried KMS to decrypt values and reading from S3 bucket.

The error is:
> Decrypt request failed: AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
status code: 400, request id: xxxxxxxxxxxxx

When I switched to `aws-go-sdk` v1 it works. 
```
  name = "github.com/aws/aws-sdk-go"
  revision = "0a302e6abb548c4a4d22cde8eab1693ee498f202"
  version = "v1.13.18"
```

I triple-checked that the Role has access to KMS-key and the region - it works with aws cli as well.

### Steps to reproduce
aws-go-sdk v1 working example - https://play.golang.org/p/OHbhSKNtUB0
aws-go-sdk v2 non-working example - https://play.golang.org/p/2-_GoxxcZ-1

the difference is in `Decrypt` function only.

**Comment by xibz** [comment]
Hello @pavel-popov, thank you for reaching out to us. To understand a little bit of what's going on how are you attaching that role? Is this through the `service/sts` package? Or running your application on Amazon EC2 and relying on that to do the role attaching?

**Comment by pavel-popov** [comment]
I'm running the app as AWS Batch Job in a docker container.
