### ISSUE TITLE
DescribeRegions operation in EC2 service have no interface declared

### ISSUE THREAD

**Issue by MichaelEureka** [aws/aws-sdk-go-v2#1541]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

Under EC2 service there is an operation called DescribeRegions that returns all regions in AWS account.
This operation have no API client, hence generating clean mock is not possible.

### Expected behavior

[Here](https://github.com/aws/aws-sdk-go-v2/blob/main/service/ec2/api_op_DescribeRegions.go) ther eis a need to add an API interface, like in all other service operations.

### Current behavior

No interface declared

### Steps to Reproduce

Run mockery on github.com/aws/aws-sdk-go-v2/service/ec2@v1.25.0

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2/service/ec2: v1.25.0

### Compiler and Version used

1.17.5 

### Operating System and version

ProductName:	macOS ProductVersion:	12.0 BuildVersion:	21A344

**Comment by KaibaLopez** [comment]
Hi @MichaelEureka ,
This is expected, or rather a decision made to not include interfaces on the go v2, you can see more info on this response [here](https://github.com/aws/aws-sdk-go-v2/issues/786#issuecomment-702349450).
Let me know if you have any more questions though.
