### ISSUE TITLE
Example Code Snippet needed for "func (Uploader) Upload"

### ISSUE THREAD

**Issue by enraiha0307** [aws/aws-sdk-go-v2#1543]
### Describe the issue with documentation

Is it possible to add a code snippet for the Upload function in "aws-sdk-go-V2/feature/s3/manager" documentation, just like it has been added for the NewUploader function?  It would be really helpful for newbies like me who get to implement these functions on the first day of their jobs.

![Firefox_Screenshot_2022-01-03T09-08-23 296Z](https://user-images.githubusercontent.com/26249973/147914355-c5d6d2da-f601-4329-9f90-c7c0d3979b99.png)

### Suggestion

```go
// Load AWS Config
cfg, err := config.LoadDefaultConfig(context.TODO())
if err != nil {
	panic(err)
}

// Create an S3 Client with the config
client := s3.NewFromConfig(cfg)

// Create a file reader
file,err := os.Open(fileName)
if err != nil {
fmt.Println("Unable to open file" + fileName)
}
defer file.Close()

// Create an uploader passing it the client
uploader := manager.NewUploader(client)

// Upload the object 
uploadObject,err = uploader.Upload(context.TODO(), &s3.PutObjectInput{
Bucket: aws.String(bucketName),
Key:aws.String(fileName),
Body:file,
})
// handle the error
```

### AWS Go SDK version used

v1.7.5

**Comment by KaibaLopez** [comment]
Hi @enraiha0307 ,
quick question,  is it a lack of samples on this or just that it isn't there? like, have you taken a look [here](https://aws.github.io/aws-sdk-go-v2/docs/sdk-utilities/s3/)? Is this the sample you are looking for? Or is this more of a "too many places to look " problem?

**Comment by enraiha0307** [comment]
Hi @KaibaLopez ,
I was not able to find it when I was searching for its samples in the v2 documentation. However, it is given there, Developer Guide/SDK Utilities/Amazon S3, just as you said. Thanks for the help.
This issue is not needed now.
Should I close this or you will?
