### ISSUE TITLE
dynamodbav key Construct

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#1547]
### Describe the feature

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression#example-Builder.WithUpdate

shows a key being manually constructed:

	Key: map[string]types.AttributeValue{
			"Artist":    &types.AttributeValueMemberS{Value: "Acme Band"},
			"SongTitle": &types.AttributeValueMemberS{Value: "Happy Day"},
		},

### Is your Feature Request related to a problem?

I am frustrated whilst making the key for an update 
https://github.com/kaihendry/dynamodb-expire-non-latest/blob/abd2cff16c9f97d4713f46b7a22936744164bfa5/expire.go#L96-L100

### Proposed Solution

Surely there could be a simpler way maybe? With dynamodbav, but I suppose there could several range keys?

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

    github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.4.5     github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.3.5     github.com/aws/aws-sdk-go-v2/service/dynamodb v1.11.0

### Go version used

1.17.5

**Comment by KaibaLopez** [comment]
Hi @kaihendry ,
So... I'm not sure what is the request here. 
Like I somewhat get that it is a bit of a convoluted process to build and update an item, but it is also to a degree a service limitation... Not to say nothing can be done about it, but we do need more specific cases, something like an example on what you would like the call/function to look  and behave like and the expected use case.
