### ISSUE TITLE
Add `WithIterator` functions to `s3manageriface` types

### ISSUE THREAD

**Issue by aaron0browne** [aws/aws-sdk-go-v2#155]
Simply looking to use `s3manageriface` for testing but cannot because my code uses `DownloadWithIterator`.

**Comment by aaron0browne** [comment]
I just realized that I could also pass a mock S3 client to `NewDownloaderWithClient`. Looking through the source, it seems that the mock client would only need to implement `GetObjectRequest` ([here](https://github.com/aws/aws-sdk-go-v2/blob/master/service/s3/s3manager/download.go#L412)), is that correct?

**Comment by aaron0browne** [comment]
Actually, that strategy seems like it will be difficult since there is no way to stub the functionality of the request returned from the client... So, back to the original hope that we can bring the `s3manageriface` into full parity with the `Downloader` type.

**Comment by jasdel** [comment]
@aaron0browne thanks for putting together the CR. Correct mocking out the Downloader is an option, but it does put a significant amount of onerous on the mocking out code to duplicate some of the SDK's functionality. Mocking out the Downloader via the interface is probably the best option like in your PR.
