### ISSUE TITLE
sts assumeRole examples do not work

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#157]
https://github.com/aws/aws-sdk-go-v2/blob/master/example/service/rds/rdsutils/authentication/iam_authentication.go

https://godoc.org/github.com/aws/aws-sdk-go-v2/aws/stscreds#hdr-Assume_Role

`aws.NewCredentials` for example doesn't exist!

I think it should be something like:

      cfg.Credentials = stscreds.NewAssumeRoleProvider(sts.New(cfg), role)
      s3svc := s3.New(cfg)

Is it possible validate your examples as part of your CI?

**Comment by skyzyx** [comment]
@jasdel: Any chance you could post _any_ examples here?

**Comment by pete911** [comment]
@skyzyx I have added example (I had to follow strange examples convention):
https://github.com/aws/aws-sdk-go-v2/pull/224
