### ISSUE TITLE
DynamoDB add one map AttributeValueMemberMI{ Value map[int64]AttributeValue}

### ISSUE THREAD

**Issue by sun-fight** [aws/aws-sdk-go-v2#1570]
### Describe the feature

```
type AttributeValueMemberMI struct {
	Value map[int64]AttributeValue

	noSmithyDocumentSerde
}
```

### Is your Feature Request related to a problem?

I'm always frustrated when MarshalMap map's key is int type.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

aws-sdk-go-v2/service/dynamodb v1.13.0

### Go version used

go version go1.17.5 darwin/arm64

**Comment by jasdel** [comment]
Thanks for taking the time to create this issue @sun-fight. The SDK cannot add a `AttributeValueMemberMI` member type as these are defined by the Amazon DynamoDB API. With that said there are issue, https://github.com/aws/aws-sdk-go-v2/issues/645 and https://github.com/aws/aws-sdk-go-v2/issues/411 that cover this concept of using non `string` types as keys for AttributeValueMemberM maps.
