### ISSUE TITLE
Recursive link in Documentation; unable to locate method documentation

### ISSUE THREAD

**Issue by iancward** [aws/aws-sdk-go-v2#1571]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

While on the [Using the AWS SDK for Go V2 with AWS Services](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/) page, there is a sentence: 

> For the list of service clients, including their methods and parameters, see the [AWS SDK for Go V2 API Reference](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/)

However, that link goes to the same page and does not take me to a page with a list of methods and parameters.

### Expected behavior

I expect to be taken to a page that has a list of services, the methods available, and the parameters for each, similar to the Boto3 for Python [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/index.html).

### Current behavior

"AWS SDK for Go V2 API Reference" is a link to the same page that I'm currently on.

### Steps to Reproduce

- Navigate to AWS Documentation for Go SDK: https://aws.amazon.com/sdk-for-go/
- Click link for "Developer Guide": https://aws.github.io/aws-sdk-go-v2/docs/
- Clink link for "Using the AWS SDK for Go V2 with AWS Services" https://aws.github.io/aws-sdk-go-v2/docs/making-requests/
- Click link for "AWS SDK for Go V2 API Reference" https://aws.github.io/aws-sdk-go-v2/docs/making-requests/
- Be taken to same page

### AWS Go SDK version used

N/A

### Compiler and Version used

N/A

### Operating System and version

Chrome 97.0.4692.71 on Windows 10

**Comment by KaibaLopez** [comment]
oh yea,  thanks for reporting this.
