### ISSUE TITLE
`aws.Config.Copy()` does not allow overriding config fields, but documentation says it does

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#1573]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

The `aws.Config.Copy()` function documentation says that

> If any additional configurations are provided they will be merged into the new config returned.

https://github.com/aws/aws-sdk-go-v2/blob/14f597921b4e948439857a039f422be0cd9d232e/aws/config.go#L106-L111

However, there is no way to pass additional configurations to the function.

In AWS SDK for Go v1, the equivalent function, `aws.Session.Copy()` does allow passing additional overrides

https://github.com/aws/aws-sdk-go/blob/fdd6541c351239f302bba32b4ca29d7c90c28433/aws/session/session.go#L844-L860

### Expected behavior

The documentation comment does not match the abilities of the function

### Current behavior

`aws.Config.Copy()` does not accept any parameters to allow merging additional configuration

### Steps to Reproduce

N/A

### Possible Solution

Either

1. the documentation comment for `aws.Config.Copy()` should no longer reference merging config
2. `aws.Config.Copy()` should allow merging

### AWS Go SDK version used

v1.13.0

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by vudh1** [comment]
Hi @gdavison thanks for pointing this out. In V2 we are no longer merging config because we have an external configuration loading module that initializes the Config type.  From there functional options are used to override Client specific options as needed in the Client’s New and NewFromConfig Constructors. The documentation comment will be fixed.
