### ISSUE TITLE
Support ca_bundle for config.SharedConfig

### ISSUE THREAD

**Issue by greedy52** [aws/aws-sdk-go-v2#1581]
### Describe the feature

`config.SharedConfig` should support `ca_bundle`, which is supported in [sdk V1](https://github.com/aws/aws-sdk-go/blob/8defc39822c0588ba356f37c9420eb93354a948e/aws/session/shared_config.go#L341) or other aws clients like aws cli, boto3.

### Is your Feature Request related to a problem?

When using `AWS_SHARED_CREDENTIALS_FILE`, `ca_bundle` is ignored. Current workaround is to use an extra `AWS_CA_BUNDLE` as environment variable which is incovenient.

### Proposed Solution

When shared config is parsed, `ca_bundle` should be parsed and loaded properly to `aws.Config`.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

v1.9.0

### Go version used

go1.17.2

**Comment by jasdel** [comment]
Thanks for posting this feature request @greedy52 lets use https://github.com/aws/aws-sdk-go-v2/issues/1589 to track this since these are duplicate feature requests.
