### ISSUE TITLE
Support reading `max_attempts` from shared config files

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#1584]
### Describe the feature

The shared config file parameter `max_attempts` is supported by the AWS CLI. However, this cannot be accessed using the AWS SDK for Go.

Alternatively, a method to access parameters from the set of shared config files, even if the SDK doesn't automatically use them.

### Is your Feature Request related to a problem?

There is no way to programatically access the `max_attempts` setting from the shared config file. This can lead to confusion when applications don't pick up some settings from shared config, but do pick up others.

### Proposed Solution

The `MaxAttempts` parameter should be exposed in some way. Either it should be set automatically on the default retryer, or it should be exposed to developers so they can set it on retryers they create.

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2 v1.13.0

### Go version used

go version go1.17.2 darwin/amd64

**Comment by jasdel** [comment]
Thanks for creating this feature request @gdavison PR #1576 adds this behavior along with the `adaptive` retry mode.
