### ISSUE TITLE
Inconsistent Assume Role duration between SDK and CLI

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#1587]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

The AWS CLI uses a default assume role duration of 1 hour if the `duration_seconds` parameter is not set in the shared configuration file or when calling the `aws sts assume-role` command directly, according to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html and https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html.

The AWS SDK for Go v2 uses a default of 15 minutes when duration is not configured by any mechanism.

### Expected behavior

An application built using the AWS SDK will treat the default the same as the AWS CLI.

Having a different default between the AWS CLI and other applications using the same configuration file will lead to user confusion and frustration.

### Current behavior

Applications using the AWS SDK only assume a role for 15 minutes instead of 1 hour as the CLI does.

### Steps to Reproduce

Authenticate with the AWS SDK and assume a role with the default duration.

### Possible Solution

The default could be made consistent between the AWS CLI and the AWS SDK.

Alternatively, the default could be configurable, along the lines of 

```go
config, err := config.LoadDefaultConfig(ctx, config.WithAssumeRoleDurationDefault(1 * time.Hours))
```

If no configuration source specifies the duration, the configurable duration would be used.

### AWS Go SDK version used

Release 2022-02-18: github.com/aws/aws-sdk-go-v2/credentials v1.8.0

### Compiler and Version used

go version go1.17.6 darwin/amd64

### Operating System and version

N/A

**Comment by vudh1** [comment]
Hi, is this still persisting with the latest version of SDK?

**Comment by gdavison** [comment]
This was a misunderstanding on my part, since the SDK automatically refreshes the credentials after the 15 minutes, while the AWS CLI can't
