### ISSUE TITLE
Support reading `ca_bundle` from shared config files

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#1589]
### Describe the feature

The shared config file parameter `ca_bundle` is supported by the AWS CLI. However, this cannot be accessed using the AWS SDK for Go.

### Is your Feature Request related to a problem?

There is no way to programatically access the `ca_bundle` setting from the shared config file. This can lead to confusion when applications don't pick up some settings from shared config, but do pick up others.

### Proposed Solution

The `CustomCABundle` parameter should be read by the `SharedConfig` resolver

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2 v1.13.0

### Go version used

go version go1.17.2 darwin/amd64

**Comment by jasdel** [comment]
Thanks for taking the time to create this issue @gdavison. I've putout PR #1593 that adds support for the `ca_bundle` shared config parameter.
