### ISSUE TITLE
Default authentication flow should fail if invalid profile name is passed

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#1591]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

When the default authentication flow is used with `config.LoadDefaultConfig()`, providing an invalid profile name, either with `config.WithSharedConfigProfile()` or by setting `AWS_PROFILE`, does not cause an error, but falls back to trying IMDS.

### Expected behavior

In the AWS CLI, I get

```console
$ AWS_PROFILE=no-such-profile aws sts get-caller-identity

The config profile (no-such-profile) could not be found
```

The SDK should fail with a `config.SharedConfigProfileNotExistError` error.

### Current behavior

The AWS SDK falls back to calling IMDS

### Steps to Reproduce

```go
cfg, err := config.LoadDefaultConfig(ctx)
```

and set `AWS_PROFILE` to an invalid profile name

or

```go
cfg, err := config.LoadDefaultConfig(ctx, config.WithSharedConfigProfile("no-such-profile"))
```

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2 v1.13.0, github.com/aws/aws-sdk-go-v2/config v1.13.1

### Compiler and Version used

go version go1.17.2 darwin/amd64

### Operating System and version

N/A

**Comment by vudh1** [comment]
closing since PR is merged.
