### ISSUE TITLE
attribute_not_exists not check normal

### ISSUE THREAD

**Issue by sun-fight** [aws/aws-sdk-go-v2#1594]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

`attribute_not_exists(pk)` not check normal.

1. I have a pk : `user#a1234`
2. put item pk: `user#a1234` sk: `user#a1234`
3. put item again pk: `user#a1234` sk: `user#a1234` is `PutItem failed: Condition check failed for operation.`
4. put item pk: `user#a1234` sk: `user#a12` is put success.  I think pk: `user#a1234` is exists. Put result should be `PutItem failed: Condition check failed for operation.`  with `attribute_not_exists(pk)` 
5. can you tell me why?

### Expected behavior

put item pk: `user#a1234` sk: `user#a12` is `PutItem failed: Condition check failed for operation.`
because `attribute_not_exists(pk)`

### Current behavior

put item pk: `user#a1234` sk: `user#a12` is put success. 

### Steps to Reproduce

this 
![image](https://user-images.githubusercontent.com/22268505/155294066-73ce086f-785e-4998-8f82-ae83b90a0b36.png)

### AWS Go SDK version used

v1.13.0

### Compiler and Version used

1.17

### Operating System and version

Mac 12.1

**Comment by vudh1** [comment]
Hi @sun-fight closing this issue because this is not a SDK issue. Please reopen if you need help from SDK.
