### ISSUE TITLE
Update to github.com/aws/aws-sdk-go-v2/service/s3 v1.25.0: plenty of warnings related to missing checksums

### ISSUE THREAD

**Issue by pommedeterresautee** [aws/aws-sdk-go-v2#1606]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

When I update the `github.com/aws/aws-sdk-go-v2/service/s3` dependency to `v1.25.0` I get plenty of warnings:

```logs
...
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
...
```
In precedent version there is no such things.
There is no easy way to enable / disable checksum check

### Expected behavior

I can download files from S3 bucket without having thousands of warnings.

### Current behavior

When I try to download a file, I have thousands of warnings telling me there is no supported checksums to check.

```logs
...
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
SDK 2022/03/01 13:45:05 WARN Response has no supported checksum. Not validating response payload.
...
```

### Steps to Reproduce

My code to download a file from S3 bucket:

```golang
// ...
		obj := s3.GetObjectInput{
			Bucket: &bucket,
			Key:    &path,
		}
		ctx, cancel := context.WithTimeout(mainContext, requestTimeout)
		defer cancel()
		rawContent, err := client.GetObject(ctx, &obj)
		if err != nil {
			return nil, fmt.Errorf("error during AWS s3 object download: %v", err)
		}
		if ctx.Err() != nil {
			return nil, fmt.Errorf("context error (may be timeout related): %v", ctx.Err())
		}
		buf := new(bytes.Buffer)
		_, err = buf.ReadFrom(rawContent.Body)
		if err != nil {
			return nil, fmt.Errorf("error during AWS s3 object content read: %v", err)
		}
		return buf.Bytes(), nil
```

I tried below code but it didn't change anything:

```golang
		obj := s3.GetObjectInput{
			Bucket: &bucket,
			Key:    &path,
			ChecksumMode: types.ChecksumModeEnabled,
		}
```

### Possible Solution

This is related to PR https://github.com/aws/aws-sdk-go-v2/pull/1600 from 

### AWS Go SDK version used

1.25.0

### Compiler and Version used

Go 1.16

### Operating System and version

Ubuntu 21.04

**Comment by jasdel** [comment]
Thanks for reporting this issue @pommedeterresautee. I was able to reproduce this issue, and put out PR #1607 that addresses this bug in the SDK's handling of automatic validation of response payload checksums.
