### ISSUE TITLE
Not possible to set an endpoint for AWS MediaStoreData

### ISSUE THREAD

**Issue by iliasgal** [aws/aws-sdk-go-v2#162]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2

### Version of Go (`go version`)?
go1.8.3

### What issue did you see?
Not possible to set the endpoint for AWS MediaStoreData
### Steps to reproduce

On service/mediastoredata/service.go there is the `const ServiceName = "data.mediastore"`
As a const, this value cannot change. But it seems that it is impossible to change the endpoint and use the MediaStoreData APIs for an endpoint like: https://sdfdsfsdfsdfsdf.data.mediastore.eu-west-1.amazonaws.com

**Comment by jasdel** [comment]
Hi @iliasgal thanks for reaching out to us with your question. You can set the endpoint that a particular service uses by setting the `aws.Config.EndpointResolver` value when your application calls the service client's `New` function.  The easiest way to define your own [EndpointResolver](https://godoc.org/github.com/aws/aws-sdk-go-v2/aws#EndpointResolver) from a URL is to use the [aws.ResolveWithEndpointURL](https://godoc.org/github.com/aws/aws-sdk-go-v2/aws#ResolveWithEndpointURL) helper.

The following is an example of this.

```go
cfg, err := external.LoadDefaultAWSConfig()
if err != nil {
    panic("failed to load SDK config defaults, " + err.Error())
}

cfg.EndpointResolver = aws.ResolveWithEndpointURL(myMediaStoreDataURL)

src := mediastoredata.New(cfg)
```

You can use [Config.Copy](https://godoc.org/github.com/aws/aws-sdk-go-v2/aws#Config.Copy) helper method if you want to share the same config with multiple service clients without loading the config multiple times.

**Comment by iliasgal** [comment]
Thanks! That worked.

**Comment by jasdel** [comment]
Great, let us know if you run into any additional issues, or have questions/suggests for the SDK.

**Comment by mbadran** [comment]
I also struggled to implement this with DynamoDB Local. I may have missed the references in the docs, but it would be good to emphasise this so others can avoid the pain.
