### ISSUE TITLE
Allow Encode/Decode custom time formats in DynamoDB

### ISSUE THREAD

**Issue by plopezlpz** [aws/aws-sdk-go-v2#1628]
### Describe the feature

When saving `time.Time` fields into dynamo db it defaults to format `time.RFC3339Nano`. It would be helpful to make this configurable via EncodingOptions

### Is your Feature Request related to a problem?

In my use case I'd like to save the time fields formatted with milliseconds keeping the trailing zeroes to keep sorting correct, 

e.g.: I want to save`2022-03-17T09:46:11.100Z` rather than the default `2022-03-17T09:46:11.1Z`.

In Go I could format a time with the following format to achieve that: `"2006-01-02T15:04:05.000Z07:00"` but currently I cannot use `MarshalWithOptions` with my custom format.

### Proposed Solution

https://github.com/aws/aws-sdk-go-v2/pull/1627

### Describe alternatives you've considered

currently I'm doing something like this:
```
itemValues, err := attributevalue.MarshalMap(item)
if err != nil {
   return fmt.Errorf("marshalling item: %w", err)
}
itemValues["createdAt"] = &types.AttributeValueMemberS{Value: item.CreatedAt.Format("2006-01-02T15:04:05.000Z07:00")}
```

### Acknowledge

- [x] I may be able to implement this feature request

### AWS Go SDK version used

v1.43.20

### Go version used

go version go1.18 darwin/amd64

**Comment by jasdel** [comment]
Thanks for creating this feature request and contributing  an implementation. I've updated the PR with feedback.
