### ISSUE TITLE
NoSuchUpload error code from ListParts not matching during error handling

### ISSUE THREAD

**Issue by necro351** [aws/aws-sdk-go-v2#1635]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

I call ListParts with an upload ID that does not exist. AWS reports it is a NoSuchUpload error, but when checking if the err is a types.NoSuchUpload the test fails and my code returns up the wrong error path. The SDK behaves as if err is not a *types.NoSuchUpload even though it should be. This looks like a bug in the SDK.

```
   // Get the existing list of parts to print for debugging:
   path := fmt.Sprintf("%s/%s/%s", awsbe.Default.Prefix, a.Auth.IdentityId(), uniqueId)
   out, err := a.s3cli.ListParts(ctx, &s3.ListPartsInput{
      Bucket:   aws.String(awsbe.Default.Bucket),
      Key:      &path,
      UploadId: &uploadId,
   })
   if err != nil {
      if ctx.Err() != nil {
         return lerr.CANCELLED
      }
      var nsu *s3types.NoSuchUpload
      if errors.As(err, &nsu) {
         return lerr.Set(nil, lerr.NOENT, "could not find the upload ID: %v", err) // <---- my code _should_ return from here
      }
      return lerr.New("get parts aws: %v", err) // <---- but instead my code returns from here
   }
```

This is the response returned from AWS, which convinces me the returned error is in fact a NoSuchUpload error:

```
2022/03/21 04:41:30 Unexpected failure:
	aws.go:487: get parts aws: operation error S3: ListParts, https response error StatusCode: 404, RequestID: EWGREZBRT2TWJ8PN, HostID: buVZY36dO8FMKQYFK06vVeKP9TnuOYT+WMBhP8jh2mCapx8kPie9KgeG3bk5S9WWNBRF9vm6vLw=, api error NoSuchUpload: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
```

FYI 'aws.go' is the line of code determined by using Golang's callstack function and is `return lerr.New("Get parts aws:...`.

### Expected behavior

It should match *types.NoSuchUpload and return through my code's "ENOENT" path.

### Current behavior

The error does not appear to match *types.NoSuchUpload and it returns through my code's generic error path.

### Steps to Reproduce

I uploaded a multi-part upload, then did finish put parts, then listed using the code above. Since the put parts completed, the list parts should fail with NoSuchUpload, which according to the error message, it does.

Next do something like my code above to match the error code and find it does not match.

### Possible Solution

I suspect ListParts is not wrapping *types.NoSuchUpload when the backend returns this error code for some reason, although other APIs may behave correctly.

### AWS Go SDK version used

github.com/aws/aws-sdk-go-v2 v1.11.0
github.com/aws/aws-sdk-go-v2/service/s3 v1.15.1

### Compiler and Version used

go version go1.16.2 darwin/amd64

### Operating System and version

macOS 12.2.1

**Comment by necro351** [comment]
I worked around the issue by doing this:

```
   // Get the existing list of parts to print for debugging:
   path := fmt.Sprintf("%s/%s/%s", awsbe.Default.Prefix, a.Auth.IdentityId(), uniqueId)
   out, err := a.s3cli.ListParts(ctx, &s3.ListPartsInput{
      Bucket:   aws.String(awsbe.Default.Bucket),
      Key:      &path,
      UploadId: &uploadId,
   })
   if err != nil {
      if ctx.Err() != nil {
         return lerr.CANCELLED
      }
      var nsu *s3types.NoSuchUpload
      if errors.As(err, &nsu) {
         return lerr.Set(nil, lerr.NOENT, "could not find the upload ID: %v", err)
      }
      var ae smithy.APIError
      if errors.As(err, &ae) {
         if ae.ErrorCode() == "NoSuchUpload" {
            return lerr.Set(nil, lerr.NOENT, "could not find the upload ID: %v", err)
         } else {
            return lerr.New("get parts aws: code: %s, message: %s, fault: %s", ae.ErrorCode(), ae.ErrorMessage(), ae.ErrorFault().String())
         }
      } else {
         return lerr.New("get parts aws: %v", err)
      }
   }
   log.Println("sync-to-server parts already in AWS:", Parts(out.Parts))
```

...this works. So if I check the ErrorCode() string, it matches "NoSuchUpload", even though the error type does not wrap the *types.NoSuchUpload. So perhaps that extra bit of info helps.

**Comment by necro351** [comment]
I'm actually noticing exactly the same behavior with another different API: TransactWriteItems in "github.com/aws/aws-sdk-go-v2/service/dynamodb". In this case the error code is returning a failure to transaction because of validation failure:

`DynamoDB: TransactWriteItems, https response error StatusCode: 400, RequestID: KBNP6RTN4I7107P2SGRPQIOU17VV4KQNSO5AEMVJF66Q9ASUAAJG, TransactionCanceledException: Transaction cancelled, please refer cancellation reasons for specific reasons [None, ValidationError]`

...however when comparing the error using a type switch:

```
   if err != nil {                                                                                                                                                                   
      switch err.(type) {                                                                                                                                                            
      case *types.TransactionCanceledException:                                                                                                                                      
         log.Printf("Cannot transact on user Id %s condition %s failed: %v", idid, condition, err)                                                                                   
         return lerr.NOENT                                                                                                                                                           
      default:                                                                                                                                                                       
         return lerr.Push(err, "could not put root for id=%s", idid)                                                                                                                 
      }                                                                                                                                                                              
   }
```

...the function returns the error up the `default:` path, so again it appears as though the correct type is not being used. Perhaps the API should simply use `errors.Is` and `%w` to return specific error types like other golang APIs?

**Comment by Acconut** [comment]
I ran into the same issue. While the workaround of casting into an `smithy.APIError` and checking the error code works, it is still non-intuitive as developers expect the a more specific error type to be used if it is available.

I tried to look for the reason of this behavior and it could be that in the [S3 model](https://github.com/aws/aws-sdk-go-v2/blob/2255129f62335d4a7db01f5ecaf1d8c2fa2a15ac/codegen/sdk-codegen/aws-models/s3.json/#L24909-L24910), the `ListParts` operation is missing a reference to the `NoSuchUpload` error. This reference exists for the `AbortMultipartUpload` operation, so it might also be necessary here.

The current model looks like this, where the error should be referenced:

```js
        "com.amazonaws.s3#ListParts": {
            "type": "operation",
            "input": {
                "target": "com.amazonaws.s3#ListPartsRequest"
            },
            "output": {
                "target": "com.amazonaws.s3#ListPartsOutput"
            },

            // This errors property with NoSuchUpload is missing in the model
            // "errors": [
            //    {
            //        "target": "com.amazonaws.s3#NoSuchUpload"
            //    }
            // ],

            "traits": {
                "smithy.api#documentation": "...",
                "smithy.api#http": {
                    "method": "GET",
                    "uri": "/{Bucket}/{Key+}?x-id=ListParts",
                    "code": 200
                },
                "smithy.api#paginated": {
                    "inputToken": "PartNumberMarker",
                    "outputToken": "NextPartNumberMarker",
                    "items": "Parts",
                    "pageSize": "MaxParts"
                }
            }
        },
```

Is there any possibility to get the model adjusted? Or is the source of this bug somewhere else?

**Comment by Acconut** [comment]
It appears like other multipart operations are also missing this reference. In particular, I found not reference for the `CompleteMultipartUpload`, `ListParts`, `UploadPart`, and `UploadPartCopy` operations.
