### ISSUE TITLE
Missing docs on how to migrate from s3crypto

### ISSUE THREAD

**Issue by junedev** [aws/aws-sdk-go-v2#1636]
### Describe the issue with documentation

We currently use the s3crypto package of the v1 Go SDK in our production system. We would like to migrate to the new V2 SDK, however the s3crypto package is not part of the new SDK anymore. The AWS encryption SDK does not exist for Go.

Currently the [migration guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/) does not mention the removal of s3crypto at all although this clearly a breaking change.
It would be great to get some advice whether a replacement in Go will be provided at a later point in time and if not, what is the recommended course of action for customers that currently use s3crypto?

[Same question was asked [here](https://github.com/aws/aws-sdk-go-v2/pull/511#issuecomment-1012395156)]

**Comment by jasdel** [comment]
Thanks for reaching out @junedev. The v2 SDK does not provide an comparable module to the v1 SDK's S3 encryption client provided by v1. How or when feature would be created to be compatible with the v2 SDK is still being evaluated by the SDK team. We can use this GitHub issue to track that feature.

**Comment by jsjain** [comment]
Hi, is there any update on this feature ?

**Comment by pinple** [comment]
@jasdel Hi, is there any update on this feature ?

**Comment by pinple** [comment]
> Thanks for reaching out @junedev. The v2 SDK does not provide an comparable module to the v1 SDK's S3 encryption client provided by v1. How or when feature would be created to be compatible with the v2 SDK is still being evaluated by the SDK team. We can use this GitHub issue to track that feature.

@jasdel  Hi, is there any update on this feature ?

**Comment by pinple** [comment]
> > Thanks for reaching out @junedev. The v2 SDK does not provide an comparable module to the v1 SDK's S3 encryption client provided by v1. How or when feature would be created to be compatible with the v2 SDK is still being evaluated by the SDK team. We can use this GitHub issue to track that feature.
> 
> @jasdel Hi, is there any update on this feature ?

@jasdel and v1 sdk dont support multipart upload with client-side encryption, is there any plan ?

**Comment by jasdel** [comment]
Thanks for reaching out @pinple. Crypto support for v2 SDK is a backlog item that is being investigated. I don't have any updates available to share at the moment for this. With regard to multipart upload, this is a pending backlog item for the SDK team to evaluate.

**Comment by aajtodd** [comment]
There is no update to provide at the moment. This is still a backlog issue that we are actively looking into but no ETA at the moment. Stay tuned.

**Comment by lucix-aws** [comment]
AWS Crypto Tools recently released the 3.x encryption client: https://github.com/aws/amazon-s3-encryption-client-go, which is compatible with the v2 SDK.

I've added a section on migrating in this devguide refresh: #2431.
