### ISSUE TITLE
Add []bytes serializer/deserializer of DynamoDB LastEvaluatedKey

### ISSUE THREAD

**Issue by aanaya-divilo** [aws/aws-sdk-go-v2#1644]
### Describe the feature

Using DynamoDB queries with limit, it would be useful to be able to serialize the LastEvaluatedKey value in bytes to be able to propagate it in an API response. It would also be useful the deserialize operation.

### Is your Feature Request related to a problem?

It is needed to do an extra marshalling to a custom type to be able to serialize the LastEvaluatedKey properly

### Proposed Solution

In the aws-sdk-go-v2/feature/dynamodb/attributevalue package include a `[]bytes` serializer/deserializer

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

1.8.2

### Go version used

go version go1.16.14 linux/amd64

**Comment by wolfeidau** [comment]
I am using something like the following code to implement this.

```go
func parseLastEvaluatedKey(lastEvaluatedKey string, queryInput *dynamodb.QueryInput) error {
	data, err := base64.RawURLEncoding.DecodeString(lastEvaluatedKey)
	if err != nil {
		return err
	}

	m := make(map[string]string)

	err = json.Unmarshal(data, &m)
	if err != nil {
		return errors.Wrap(err, "dynastorev2: failed to unmarshal last evaluated key")
	}

	queryInput.ExclusiveStartKey, err = attributevalue.MarshalMap(&m)
	if err != nil {
		return err
	}
	return nil
}

func encodeLastEvaluatedKey(res *dynamodb.QueryOutput) (string, error) {
	if res.LastEvaluatedKey == nil {
		return "", nil
	}

	m := make(map[string]string)
	err := attributevalue.UnmarshalMap(res.LastEvaluatedKey, &m)
	if err != nil {
		return "", err
	}

	data, err := json.Marshal(&m)
	if err != nil {
		return "", err
	}

	return base64.RawURLEncoding.EncodeToString(data), nil
}
```

**Comment by aanaya-divilo** [comment]
> I am using something like the following code to implement this.
> 
> ```go
> func parseLastEvaluatedKey(lastEvaluatedKey string, queryInput *dynamodb.QueryInput) error {
> 	data, err := base64.RawURLEncoding.DecodeString(lastEvaluatedKey)
> 	if err != nil {
> 		return err
> 	}
> 
> 	m := make(map[string]string)
> 
> 	err = json.Unmarshal(data, &m)
> 	if err != nil {
> 		return errors.Wrap(err, "dynastorev2: failed to unmarshal last evaluated key")
> 	}
> 
> 	queryInput.ExclusiveStartKey, err = attributevalue.MarshalMap(&m)
> 	if err != nil {
> 		return err
> 	}
> 	return nil
> }
> 
> func encodeLastEvaluatedKey(res *dynamodb.QueryOutput) (string, error) {
> 	if res.LastEvaluatedKey == nil {
> 		return "", nil
> 	}
> 
> 	m := make(map[string]string)
> 	err := attributevalue.UnmarshalMap(res.LastEvaluatedKey, &m)
> 	if err != nil {
> 		return "", err
> 	}
> 
> 	data, err := json.Marshal(&m)
> 	if err != nil {
> 		return "", err
> 	}
> 
> 	return base64.RawURLEncoding.EncodeToString(data), nil
> }
> ```

Thank you for your suggestion.

That works when both the partition key and the sort key are string, but the problem is still there if either of them are numeric or bool.

**Comment by vudh1** [comment]
Hi all, I have discussed with the team, and we decided that serializing the LastEvaluatedKey value in bytes in an API response would impact on how the value being retrieved and is not what we consider doing. Therefore, this is not what we would implement.
