### ISSUE TITLE
ECR Enhanced Scanning

### ISSUE THREAD

**Issue by bbernays** [aws/aws-sdk-go-v2#1646]
### Describe the feature

ECR Enhanced Scanning results are missing from Go SDK
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DescribeImageScanFindings.html#API_DescribeImageScanFindings_ResponseSyntax

### Is your Feature Request related to a problem?

I cannot (or I think I cannot) grab all of the data that is supported by the ECR Rest API

### Proposed Solution

Add the missing fields to the `DescribeImageScanFindingsOutput` struct 

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecr#DescribeImageScanFindingsOutput

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Go SDK version used

v1.17.2

### Go version used

1.17

**Comment by vudh1** [comment]
Hi @bbernays can you clarify what Enhanced Scanning values that you are looking for? We have this [enhancedFindings](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_ImageScanFindings.html#ECR-Type-ImageScanFindings-enhancedFindings) but please let us know more if this is not what you request.

**Comment by bbernays** [comment]
@vudh1 - Yes we would like to see an array of [EnhancedImageScanFinding](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_EnhancedImageScanFinding.html) added to the [EnhanchedFindings](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecr@v1.17.3/types#ImageScanFindings) object

**Comment by skmcgrail** [comment]
@bbernays These values are already present on the response for [DescribeImageScanFindingsOutput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecr#DescribeImageScanFindingsOutput). It has a field named `ImageScanFindings` which is a [`types.ImageScanFindings`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecr@v1.17.4/types#ImageScanFindings) which in turn has a field `EnhancedFindings` which is of type [`[]types.EnhancedImageScanFinding`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecr@v1.17.4/types#EnhancedImageScanFinding). It not clear to us how to fulfill this feature request everything that has been asked for is already present and supported.
