### ISSUE TITLE
AWS secrets manager support

### ISSUE THREAD

**Issue by robdefeo** [aws/aws-sdk-go-v2#165]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2

### Version of Go (`go version`)?
1.9

### What issue did you see?
Secrets manager is supported in https://github.com/aws/aws-sdk-go/tree/aca27d26bd47540c95de6312c970f2727bd3e268/models/apis/secretsmanager but not in V2.

**Comment by jasdel** [comment]
Thanks for letting us know about this issue. I think we just need to update #151 with the most recent models and get that merged in.

**Comment by jasdel** [comment]
I've merged in the change which brings the v2 sdk up to speed with the v1. Let us know if you have any issues or feedback.
