### ISSUE TITLE
Constructing a Service Client - New and Overriding Configuration examples

### ISSUE THREAD

**Issue by lzap** [aws/aws-sdk-go-v2#1658]
### Describe the issue

Constructing a Service Client - New and Overriding Configuration examples do not appear to be correct, when I try to compile these with the latest stable SDK:

```
require (
	github.com/aws/aws-sdk-go-v2/credentials v1.11.2
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.34.0
	github.com/aws/smithy-go v1.11.2
)
```

There is the new Provider type and it requires session as the 3rd argument. I was not sure what to provide as documentation does not describe it. This is what documentation shows:

```go
client := s3.New(s3.Options{
	Region:      "us-west-2",
	Credentials: aws.NewCredentialsCache(credentials.NewStaticCredentials(accessKey, secretKey)),
})
```

This is what works for me:

```go
	client := ec2.New(ec2.Options{
		Region: "eu-north-1",
		Credentials: aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider("XXX", "XXX", "")),
	})
```

### Links

https://aws.github.io/aws-sdk-go-v2/docs/making-requests/#new

### AWS Go SDK version used

v1.11.2

**Comment by vudh1** [comment]
Hi @lzap I have reproduced your problem. I will let the team know about this and change the documentation. The error that I got from running just 2 arguments (accessKey, secretKey) is:
`not enough arguments in call to credentials.NewStaticCredentialsProvider
        have (string, string)
        want (string, string, string)`

**Comment by vudh1** [comment]
I have fixed the documentation with this [PR](https://github.com/aws/aws-sdk-go-v2/pull/1727). Closing this issue.
