### ISSUE TITLE
Have sts.AssumeRoleOutput return aws.Credentials instead of types.Credentials

### ISSUE THREAD

**Issue by dwrz** [aws/aws-sdk-go-v2#1668]
### Describe the feature

It would be great if `sts.AssumeRoleOutput` would return `aws.Credentials` instead of `types.Credentials`, or if some functionality was provided to return transform `types.Credentials` into `aws.Credentials`. At the very least, it would be nice to have some documentation on how one can use the `sts.AssumeRoleOutput` to create new AWS service clients.

### Use Case

I am trying to set up a `rekognition` client using a cross account role -- and am running into some frustration because `sts.AssumeRoleOutput` (returned by `Client.AssumeRole`) uses `*types.Credentials` instead of `aws.Credentials`. This means I need to manually convert `*types.Credentials` into `aws.Credentials` for use in `rekognition.Options`.

### Proposed Solution

`sts.AssumeRoleOutput` returns `aws.Credentials` instead of `types.Credentials`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS Go SDK version used

1.16.2

### Go version used

go version go1.18 linux/amd64

**Comment by skmcgrail** [comment]
Hey @dwrz I believe you are looking for [stscreds.NewAssumeRoleProvider](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials@v1.11.2/stscreds#NewAssumeRoleProvider), which given an STS client, Role ARN, and optional override settings will return a credential provider for the SDK. This credentials provider can then be used with other SDK clients. Examples of its usage can be found in the package documentation at the linked page.
