### ISSUE TITLE
api error RequestExpired: Request has expired

### ISSUE THREAD

**Issue by Akash2707** [aws/aws-sdk-go-v2#1674]
### Describe the bug

Recently we moved to SSO for authentication and after that our service seems to fail when I try to Describe EC2 regions. I perform the steps that is mentioned in this URL : https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/

### Expected Behavior

Expected behavior should be to see all the ec2 regions.

### Current Behavior

Getting this error:

```operation error EC2: DescribeRegions, https response error StatusCode: 400, RequestID: a43d7953-edec-4f82-adf4-f23b2b51500a, api error RequestExpired: Request has expired.```

I believe this has to do with the time stamp the creds show in the config output i.e. ```0001-01-01 00:00:00 +0000 UTC```

### Reproduction Steps

```aws sso login --profile dev-profile```
```go run .```

Sample code:
```	
func getAwsRegions() {

	cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithRegion("us-west-2"),
		config.WithSharedConfigProfile("dev-profile"),
	)

	if err != nil {
		fmt.Printf("Unable to load SDK Config, %v\n", err)
		os.Exit(1)
	}		
	log.Info(cfg)

	ec2client := ec2.NewFromConfig(cfg)
	regions, err := ec2client.DescribeRegions(context.TODO(), &ec2.DescribeRegionsInput { Filters: []types.Filter{
						{
							Name: aws.String("opt-in-status"), 
							Values:[]string{"opt-in-not-required","opted-in"},
						},
					},
				})
	if err != nil {
		if aerr, ok := err.(awserr.Error); ok {
			switch aerr.Code() {
			default:
				fmt.Println(aerr.Error())
			}
		} else {
			// Print the error, cast err to awserr.Error to get the Code and
			// Message from an error.
			log.Error(err)
		}
	}
}
```

### AWS Go SDK version used

EC2- v1.35.1, config - v1.15.3

### Compiler and Version used

go1.17.1

### Operating System and version

MacOS 12.3.1

**Comment by skmcgrail** [comment]
If you call `cfg.Credentials.Retrieve(context.TODO())` do you get a credentials object back or an error? If you inspect the returned credentials do they contain an access key, secret key, session token, and expiration time? The timestamp you refer to printing out the `cfg` is just a zero-value uninitialized variable of the credentials cache, as credential loading is lazy and not done until first request. Additionally I would expect for you to have received a 403 error code for invalid / missing credentials versus a 400 expired request. This error code would seem to imply a potential clock skew between your machine and the EC2 service. Can you follow the [logging](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/logging/) developer guide entry and enable `aws.LogRequestWithBody` and `aws.LogResponseWithBody` so we can get a wire-log capture of the signing time and the service response?

**Comment by DirtyMongoose** [comment]
I ran into this same issue using PowerShell (.NET).  It was resolved by assuming a role with the SSO credentials first.
