### ISSUE TITLE
S3 ListObjectsV2 Fails to Deserialize Response

### ISSUE THREAD

**Issue by DomParfitt** [aws/aws-sdk-go-v2#1676]
### Describe the bug

When calling the `S3` `ListObjectsV2` operation, if the objects in the response contain the UTF-8 character `U+0008` (`\b`)  in their key then the response fails to deserialize and returns an error.

### Expected Behavior

The operation succeeds with the response containing the object key containing the UTF-8 character.

### Current Behavior

The response fails to deserialize and returns an error.

### Reproduction Steps

The following code snippet reproduces the issue by uploading a file with the "invalid" character (`\b`) in the name to a given bucket and then immediately attempting to call the `ListObjectsV2` operation (which fails). Calling the `list-objects-v2` operation via the AWS CLI (`aws s3api list-objects-v2 --bucket <BUCKET_NAME>`) after running the below snippet successfully returns the files in the bucket, including the one uploaded with the "invalid" character.

```go
package main

import (
	"bytes"
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	ctx := context.Background()

	s3Client := s3.New(s3.Options{
		Region:      "us-east-1",
		Credentials: credentials.NewStaticCredentialsProvider("<ACCESS_KEY>", "<SECRET_ACCESS_KEY>", ""),
	})

	bucket := "<BUCKET_NAME>"
	key := "fo\bo.txt"
	body := "Hello"
	_, err := s3Client.PutObject(ctx, &s3.PutObjectInput{
		Bucket: &bucket,
		Key:    &key,
		Body:   bytes.NewReader([]byte(body)),
	})

	if err != nil {
		fmt.Println(err)
		return
	}

	resp, err := s3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
		Bucket: &bucket,
	})

	if err != nil {
		fmt.Println(err)
		return
	}

	for _, o := range resp.Contents {
		fmt.Println(*o.Key)
	}

}
```

### AWS Go SDK version used

1.26.5

### Compiler and Version used

go version go1.18.1 darwin/amd64

### Operating System and version

macOS Monterey 12.3.1

**Comment by vudh1** [comment]
Hi @DomParfitt is this still persisting with the latest version of SDK? If so, can you provide us with a sample object that can reproduce the same behavior above?
