### ISSUE TITLE
Fuzzing tests are not run in CI and are invalid.

### ISSUE THREAD

**Issue by aryan9600** [aws/aws-sdk-go-v2#1693]
### Describe the bug

The `internal/ini` package has a [fuzz test](https://github.com/aws/aws-sdk-go-v2/blob/main/internal/ini/fuzz.go), which is invalid. It tests the `Parse` function in `internal/ini/ini.go`, but it [calls the function](https://github.com/aws/aws-sdk-go-v2/blob/main/internal/ini/fuzz.go#L13) incorrectly, not providing the second argument.
Due to the fact that tests in CI aren't failing, and `internal/ini/go.mod` is missing `https://github.com/dvyukov/go-fuzz`, I don't think the test is being actually run in CI.

### Expected Behavior

Fuzzing tests are valid and are executed in CI.

### Current Behavior

Fuzzing tests are invalid and are _not_ executed in CI.

### Reproduction Steps

We have fuzzing tests for our project, which threw an error because of this, ref: https://github.com/fluxcd/kustomize-controller/runs/6239372370?check_suite_focus=true

### AWS Go SDK V2 Module Versions Used

```
github.com/aws/aws-sdk-go-v2 v1.16.3
github.com/aws/aws-sdk-go-v2/config v1.15.4
github.com/aws/aws-sdk-go-v2/credentials v1.12.0
github.com/aws/aws-sdk-go-v2/service/kms v1.17.1
github.com/aws/aws-sdk-go-v2/service/sts v1.16.4
```

### Compiler and Version used

1.17

### Operating System and version

Linux

**Comment by jasdel** [comment]
Thanks for reaching out to us. We have draft PR https://github.com/aws/aws-sdk-go-v2/pull/1291 that is in our backlog to correct this behavior. The old fuzz tests are invalid and should be deleted.  We can delete the old tests, without waiting on the draft Pr work to be picked back up.

**Comment by aryan9600** [comment]
@jasdel would it be possible to get an approximate time until there is a new release with the fuzzing tests removed? 😅
