### ISSUE TITLE
HeadObject-Response: ETag contains additional double quotes

### ISSUE THREAD

**Issue by itinance** [aws/aws-sdk-go-v2#1696]
### Describe the bug

The `ETag`-Property in the Response of `HeadObject` contains double quotes .

### Expected Behavior

Etag should not contain additional double quotes, only the ETag value itself.

### Current Behavior

The ETag-property of the HeadObject returns its value encapsulated with Double Quotes:

ETag: ""e9398e127fe6c962b0e0877f4bc8a20d""

### Reproduction Steps

res, err = s3.HeadObject(bucket, filename)

### AWS Go SDK V2 Module Versions Used

v1.9.3

### Compiler and Version used

go version go1.18 darwin/arm64

### Operating System and version

MacOS v12.2.1

**Comment by itinance** [comment]
<img width="533" alt="Screenshot 2022-05-07 at 18 42 16" src="https://user-images.githubusercontent.com/1758597/167263982-a6ea67a9-c66d-4c80-86ca-84ef9dc7210e.png">

**Comment by skmcgrail** [comment]
This would be intended behavior as the header field for ETag defines the quotes as part of `entity-tag` value. At this point it would a backwards incompatible change for us to change this behavior to auto-strip the quotes. Additionally an ETag could contain a weak validator indicator per using `W/` as a prefix which could also break assumptions about the value always being un-quotable.

https://datatracker.ietf.org/doc/html/rfc2616#section-14.19
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
