### ISSUE TITLE
Create an API Key and add it to the Usage Plan

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#170]
<img src="https://s.natalian.org/2018-04-25/1524646734_2558x1406.png">

I can't figure out how to do this from https://godoc.org/github.com/aws/aws-sdk-go-v2/service/apigateway

i.e. Create a key and add to the Usage plan id. In fact given a key, I don't quite understand how to **Add API Key to Usage Plan** either.

**Comment by kaihendry** [comment]
I think this is what I need https://docs.aws.amazon.com/apigateway/api-reference/link-relation/usageplankey-create/

https://godoc.org/github.com/aws/aws-sdk-go-v2/service/apigateway#APIGateway.CreateUsagePlanKeyRequest

Bit confused by this [Usage plan key](https://docs.aws.amazon.com/apigateway/api-reference/resource/usage-plan-key/) terminology.  I guess it's basically describing the association.

**Comment by xibz** [comment]
Hello @kaihendry, thank you for reaching out to us. You are correct that you need to link a `UsagePlanKey` to a `UsagePlan`. Were you still having issues here?

**Comment by kaihendry** [comment]
Hopefully documented better so when other developers ctrl+f "Add API Key to Usage Plan", they have a chance of finding it?

Also I found the KeyType rather weird. Here's how I ended up using it.

```
apigw.CreateUsagePlanKeyRequest(&apigateway.CreateUsagePlanKeyInput{
               KeyId:       newapikey.Id,
               KeyType:     aws.String("API_KEY"),
               UsagePlanId: aws.String("foobar"),
       })
```
