### ISSUE TITLE
Issue using WithEndpointResolver and SSO

### ISSUE THREAD

**Issue by pcolazurdo** [aws/aws-sdk-go-v2#1703]
### Describe the bug

When trying to use WithEndpointResolver with SSO credentials I get an error saying: 
```
failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, operation error SSO: GetRoleCredentials, https response error StatusCode: 404, RequestID: xxx, deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
```

This seems to be because the client needs to contact portal.sso.<region>.amazonaws.com before contacting the endpoint for the service specified in the WithEndpointResolver.URL

### Expected Behavior

It would be useful to allow the SSO behavior to work with WithEndpointResolver custom settings.

### Current Behavior

Code snippet:
```
cfg, err := config.LoadDefaultConfig(ctx, config.WithRetryer(func() aws.Retryer {
		return retry.AddWithMaxAttempts(retry.NewStandard(), 2)
	}),
		config.WithHTTPClient(httpCustomClient),
		config.WithEndpointResolver(aws.EndpointResolverFunc(
			func(service, region string) (aws.Endpoint, error) {
				return aws.Endpoint{
					URL:               "http://dynamodb.eu-west-1.amazonaws.com",
					HostnameImmutable: false,
					// PartitionID:       "aws",
					// SigningName:       "",
					SigningRegion: "eu-west-1",
					// SigningMethod:     "",
					Source: 0,
				}, nil
			})),
		config.WithClientLogMode(aws.LogResponseWithBody|aws.LogRequestWithBody),
	)
```

Error:
```
failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, operation error SSO: GetRoleCredentials, https response error StatusCode: 404, RequestID: xxx, deserialization failed, failed to decode response body, invalid character '<' looking for beginning of value
```

Request Body
```
SDK 2022/05/14 15:34:52 DEBUG Request
GET /federation/credentials?account_id=123456789012&role_name=AdministratorAccess HTTP/1.1
Host: dynamodb.eu-west-1.amazonaws.com
User-Agent: aws-sdk-go-v2/1.16.2 os/macos lang/go/1.18.2 md/GOOS/darwin md/GOARCH/amd64 api/sso/1.11.3
Amz-Sdk-Invocation-Id: 4831e84d-1b02-4318-b56f-8bf0da54736e
Amz-Sdk-Request: attempt=1; max=2
X-Amz-Sso_bearer_token: Accept-Encoding: gzip
```

Response Body
```
SDK 2022/05/14 15:34:52 DEBUG Response
HTTP/1.1 404 Not Found
Content-Length: 272
Date: Sat, 14 May 2022 14:34:52 GMT
X-Amz-Crc32: 2548615100
X-Amzn-Requestid: 7E68U1OSCTM87JEL87FDJUVMJJVV4KQNSO5AEMVJF66Q9ASUAAJG

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Page Not Found</title>
</head>
<body>Page Not Found</body>
</html>


```

### Reproduction Steps

```
ctx := context.TODO()
cfg, err := config.LoadDefaultConfig(ctx, config.WithRetryer(func() aws.Retryer {
		return retry.AddWithMaxAttempts(retry.NewStandard(), 2)
	}),
		config.WithHTTPClient(httpCustomClient),
		config.WithEndpointResolver(aws.EndpointResolverFunc(
			func(service, region string) (aws.Endpoint, error) {
				return aws.Endpoint{
					URL:               "http://dynamodb.eu-west-1.amazonaws.com",
					HostnameImmutable: false,
					// PartitionID:       "aws",
					// SigningName:       "",
					SigningRegion: "eu-west-1",
					// SigningMethod:     "",
					Source: 0,
				}, nil
			})),
		config.WithClientLogMode(aws.LogResponseWithBody|aws.LogRequestWithBody),
	)
	// cfg, err := config.LoadDefaultConfig(ctx)

	if err != nil {
		log.Printf("unable to load SDK config, %v", err)
	}

	// Enable to test adding middleware steps into the client
	// cfg.APIOptions = append(cfg.APIOptions, func(stack *middleware.Stack) error {
	// 	// Attach the custom middleware to the beginning of the Initialize step
	// 	return stack.Deserialize.Add(customDeserialize, middleware.Before)
	// })
	// svc := dynamodb.NewFromConfig(cfg, dynamodb.WithEndpointResolver(func(o *dynamodb.Options) {
	// 	return o.EndpointResolver.ResolveEndpoint()
	// }))

	svc := dynamodb.NewFromConfig(cfg)
	tableName := d.table

	input := &dynamodb.PutItemInput{
		Item:      av,
		TableName: aws.String(tableName),
	}

	_, err = d.svc.PutItem(ctx, input)
```

Setup an SSO Default Profile and then call svc.PutItem

### Possible Solution

WithEndpointResolver could add an addition URL for the SSO service.

### AWS Go SDK V2 Module Versions Used

github.com/pcolazurdo/hashfile github.com/aws/aws-sdk-go@v1.43.31
github.com/pcolazurdo/hashfile github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/pcolazurdo/hashfile github.com/aws/aws-sdk-go-v2/config@v1.15.3
github.com/pcolazurdo/hashfile github.com/aws/aws-sdk-go-v2/credentials@v1.11.2
github.com/pcolazurdo/hashfile github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.8.4
github.com/pcolazurdo/hashfile github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.5
github.com/pcolazurdo/hashfile github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3
github.com/pcolazurdo/hashfile github.com/aws/smithy-go@v1.11.2
github.com/pcolazurdo/hashfile github.com/davecgh/go-spew@v1.1.1
github.com/pcolazurdo/hashfile github.com/gizak/termui/v3@v3.1.0
github.com/pcolazurdo/hashfile github.com/google/uuid@v1.3.0
github.com/pcolazurdo/hashfile github.com/mattn/go-runewidth@v0.0.13
github.com/pcolazurdo/hashfile github.com/mitchellh/go-wordwrap@v1.0.1
github.com/pcolazurdo/hashfile github.com/nsf/termbox-go@v1.1.1
github.com/pcolazurdo/hashfile github.com/spf13/cobra@v1.4.0
github.com/pcolazurdo/hashfile github.com/stretchr/testify@v1.7.0
github.com/pcolazurdo/hashfile go.uber.org/goleak@v1.1.12
github.com/pcolazurdo/hashfile gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b
github.com/aws/aws-sdk-go@v1.43.31 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go@v1.43.31 github.com/pkg/errors@v0.9.1
github.com/aws/aws-sdk-go@v1.43.31 golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd
github.com/aws/aws-sdk-go-v2@v1.16.2 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2@v1.16.2 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2@v1.16.2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/aws/aws-sdk-go-v2/credentials@v1.11.2
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.3
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.10
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.3
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/config@v1.15.3 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/credentials@v1.11.2 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/credentials@v1.11.2 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.3
github.com/aws/aws-sdk-go-v2/credentials@v1.11.2 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.3
github.com/aws/aws-sdk-go-v2/credentials@v1.11.2 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3
github.com/aws/aws-sdk-go-v2/credentials@v1.11.2 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/credentials@v1.11.2 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.8.4 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.8.4 github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.8.4 github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.13.3
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.8.4 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.8.4 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.5 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.5 github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.8.4
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.5 github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.5 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.9
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.3
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.1
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3 github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.3
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.15.3 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/smithy-go@v1.11.2 github.com/google/go-cmp@v0.5.7
github.com/aws/smithy-go@v1.11.2 github.com/jmespath/go-jmespath@v0.4.0
github.com/gizak/termui/v3@v3.1.0 github.com/mattn/go-runewidth@v0.0.2
github.com/gizak/termui/v3@v3.1.0 github.com/mitchellh/go-wordwrap@v0.0.0-20150314170334-ad45545899c7
github.com/gizak/termui/v3@v3.1.0 github.com/nsf/termbox-go@v0.0.0-20190121233118-02980233997d
github.com/mattn/go-runewidth@v0.0.13 github.com/rivo/uniseg@v0.2.0
github.com/nsf/termbox-go@v1.1.1 github.com/mattn/go-runewidth@v0.0.9
github.com/spf13/cobra@v1.4.0 github.com/cpuguy83/go-md2man/v2@v2.0.1
github.com/spf13/cobra@v1.4.0 github.com/inconshreveable/mousetrap@v1.0.0
github.com/spf13/cobra@v1.4.0 github.com/spf13/pflag@v1.0.5
github.com/spf13/cobra@v1.4.0 gopkg.in/yaml.v2@v2.4.0
github.com/stretchr/testify@v1.7.0 github.com/davecgh/go-spew@v1.1.0
github.com/stretchr/testify@v1.7.0 github.com/pmezard/go-difflib@v1.0.0
github.com/stretchr/testify@v1.7.0 github.com/stretchr/objx@v0.1.0
github.com/stretchr/testify@v1.7.0 gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c
go.uber.org/goleak@v1.1.12 github.com/kr/pretty@v0.1.0
go.uber.org/goleak@v1.1.12 github.com/stretchr/testify@v1.7.0
go.uber.org/goleak@v1.1.12 golang.org/x/lint@v0.0.0-20190930215403-16217165b5de
go.uber.org/goleak@v1.1.12 golang.org/x/tools@v0.1.5
go.uber.org/goleak@v1.1.12 gopkg.in/check.v1@v1.0.0-20180628173108-788fd7840127
gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
github.com/jmespath/go-jmespath@v0.4.0 github.com/jmespath/go-jmespath/internal/testify@v1.5.1
golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd golang.org/x/sys@v0.0.0-20211216021012-1d35b9e2eb4e
golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd golang.org/x/term@v0.0.0-20210927222741-03fcf44c2211
golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd golang.org/x/text@v0.3.7
github.com/google/go-cmp@v0.5.7 golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.3 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.10 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.3 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.9
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.3 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.3
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.9
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.3
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.3
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.13.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.13.3 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.9
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.13.3 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.3
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.13.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.9 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.3 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.1 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.3 github.com/aws/smithy-go@v1.11.2
github.com/cpuguy83/go-md2man/v2@v2.0.1 github.com/russross/blackfriday/v2@v2.1.0
gopkg.in/yaml.v2@v2.4.0 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
github.com/kr/pretty@v0.1.0 github.com/kr/text@v0.1.0
golang.org/x/lint@v0.0.0-20190930215403-16217165b5de golang.org/x/tools@v0.0.0-20190311212946-11955173bddd
golang.org/x/tools@v0.1.5 github.com/yuin/goldmark@v1.3.5
golang.org/x/tools@v0.1.5 golang.org/x/mod@v0.4.2
golang.org/x/tools@v0.1.5 golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4
golang.org/x/tools@v0.1.5 golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c
golang.org/x/tools@v0.1.5 golang.org/x/sys@v0.0.0-20210510120138-977fb7262007
golang.org/x/tools@v0.1.5 golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/davecgh/go-spew@v1.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/pmezard/go-difflib@v1.0.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/stretchr/objx@v0.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 gopkg.in/yaml.v2@v2.2.8
golang.org/x/term@v0.0.0-20210927222741-03fcf44c2211 golang.org/x/sys@v0.0.0-20210615035016-665e8c7367d1
golang.org/x/text@v0.3.7 golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.3 github.com/aws/aws-sdk-go-v2@v1.16.2
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.3 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.3 github.com/google/go-cmp@v0.5.7
github.com/kr/text@v0.1.0 github.com/kr/pty@v1.1.1
golang.org/x/tools@v0.0.0-20190311212946-11955173bddd golang.org/x/net@v0.0.0-20190311183353-d8887717615a
golang.org/x/mod@v0.4.2 golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550
golang.org/x/mod@v0.4.2 golang.org/x/tools@v0.0.0-20191119224855-298f0cb1881e
golang.org/x/mod@v0.4.2 golang.org/x/xerrors@v0.0.0-20191011141410-1b5146add898
golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4 golang.org/x/sys@v0.0.0-20210330210617-4fbd30eecc44
golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4 golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4 golang.org/x/text@v0.3.3
gopkg.in/yaml.v2@v2.2.8 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
golang.org/x/net@v0.0.0-20190311183353-d8887717615a golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2
golang.org/x/net@v0.0.0-20190311183353-d8887717615a golang.org/x/text@v0.3.0
golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550 golang.org/x/net@v0.0.0-20190404232315-eb5bcb51f2a3
golang.org/x/crypto@v0.0.0-20191011191535-87dc89f01550 golang.org/x/sys@v0.0.0-20190412213103-97732733099d
golang.org/x/tools@v0.0.0-20191119224855-298f0cb1881e golang.org/x/net@v0.0.0-20190620200207-3b0461eec859
golang.org/x/tools@v0.0.0-20191119224855-298f0cb1881e golang.org/x/sync@v0.0.0-20190423024810-112230192c58
golang.org/x/tools@v0.0.0-20191119224855-298f0cb1881e golang.org/x/xerrors@v0.0.0-20190717185122-a985d3407aa7
golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1 golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68
golang.org/x/text@v0.3.3 golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e
golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2 golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a
golang.org/x/net@v0.0.0-20190404232315-eb5bcb51f2a3 golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2
golang.org/x/net@v0.0.0-20190404232315-eb5bcb51f2a3 golang.org/x/text@v0.3.0
golang.org/x/net@v0.0.0-20190620200207-3b0461eec859 golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2
golang.org/x/net@v0.0.0-20190620200207-3b0461eec859 golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a
golang.org/x/net@v0.0.0-20190620200207-3b0461eec859 golang.org/x/text@v0.3.0

### Compiler and Version used

go version go1.18.2 darwin/amd64

### Operating System and version

Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

**Comment by skmcgrail** [comment]
```
config.WithEndpointResolver(aws.EndpointResolverFunc(
	func(service, region string) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL:               "http://dynamodb.eu-west-1.amazonaws.com",
			HostnameImmutable: false,
			// PartitionID:       "aws",
			// SigningName:       "",
			SigningRegion: "eu-west-1",
			// SigningMethod:     "",
			Source: 0,
		}, nil
	}))
```

This code you are using here overrides the endpoint provider for every service client constructed using the `aws.Confg` return by `config.LoadDefaultConfig`. You either should be using the service identifier string passed in to the function argument `service` to bifurcate the override for the specific client, or overriding the endpoint provider during the client construction specifically.

See [Overriding Endpoint with Fallback](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/#overriding-endpoint-with-fallback) in the SDK developer guide for more information.

**Comment by erudisch** [comment]
Hello

if somebody is still facing this issue look [here](https://davidagood.com/dynamodb-local-go/) for a solution.
