### ISSUE TITLE
Github link broken pointing to code sample

### ISSUE THREAD

**Issue by codegeek1001** [aws/aws-sdk-go-v2#1705]
### Describe the issue

On this documentation page below

https://aws.github.io/aws-sdk-go-v2/docs/code-examples/ec2/createinstance/

The link to "[complete example in GitHub](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/gov2/ec2/CreateInstance/CreateInstancev2.go)" is broken and returns a 404.

It seems like the correct link to github should be:

https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/gov2/ec2/common/CreateInstancev2.go

### Links

https://aws.github.io/aws-sdk-go-v2/docs/code-examples/ec2/createinstance/

**Comment by codegeek1001** [comment]
Here is a pull request to fix this:

https://github.com/aws/aws-sdk-go-v2/pull/1706

**Comment by jasdel** [comment]
This was fixed in https://github.com/aws/aws-sdk-go-v2/pull/1706 can close.
