### ISSUE TITLE
Missing pagination helper for DynamoDB BatchGetItem operation

### ISSUE THREAD

**Issue by chamila-c** [aws/aws-sdk-go-v2#1707]
### Describe the feature

In the Go SDK v1, there are DynamoDB helper functions for pagination for:
- BatchGetItemPages
- ListContributorInsightsPages
- ListExportsPages
- ListTablesPages
- QueryPages
- ScanPages
> (search for "Pages" in: https://pkg.go.dev/github.com/aws/aws-sdk-go/service/dynamodb)

However in Go SDK v2, there are only corresponding pagination helper functions for:
- ListContributorInsightsPaginator
- ListExportsPaginator
- ListTablesPaginator
- QueryPagintor
- ScanPaginator
> (search for "Paginator" in: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb)

I.e. there is no longer a pagination helper function for `BatchGetItem`, which makes it the only DynamoDB operation for which a pagination helper function was available in Go SDK v1 but _didn't_ get a corresponding pagination helper function in Go SDK v2.

Please add back a pagination helper function (`BatchGetItemPaginator`) for the DynamoDB BatchGetItem operation into Go SDK v2.

### Use Case

1. Codebases using the Go SDK v1 that make use of the (v1) SDK-provided pagination helper function for the `BatchGetItem` DynamoDB operation require additional development effort to implement their own pagination logic/helper functions for that operation if/when being upgraded to use Go SDK v2. This is an avoidable impediment to the upgrade path from v1 to v2 of the Go SDK.

2. Codebases using the Go SDK v2 that wish to implement calls to the DynamoDB `BatchGetItem` operation require additional development effort to implement pagination logic/helper functions due to the absence of an SDK-provided pagination helper function. This is an avoidable overhead for users of the v2 Go SDK.

### Proposed Solution

Please implement the pagination helper function `BatchGetItemPaginator` in alignment with the other DynamoDB pagination helper functions in the Go SDK v2.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

Any version of `aws-sdk-go-v2/service/dynamodb` (https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb?tab=versions) 

### Go version used

Any Go version compatible with use of `aws-sdk-go-v2/service/dynamodb`

**Comment by vudh1** [comment]
Hi @chamila-c thanks for bringing this up. We have discussed and this feature would be a good addition. However, the team has no bandwidth to work on this feature at the moment. We can work on a timeline on feature requests later on, but you are welcome to help us implement the feature.

**Comment by aaronchipper** [comment]
+1 for ScanPages - I love that function.
