### ISSUE TITLE
codecommit make git tag by sdk

### ISSUE THREAD

**Issue by Damien9527** [aws/aws-sdk-go-v2#1716]
### Describe the feature

i want to make git tag by  go sdk ,but  I can found the impelement . 

### Use Case

in my pipeline job ,i want to auto   make tag  by program .

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

codecommit @1.13.5

### Go version used

v1.17

**Comment by vudh1** [comment]
Hi @Damien9527 can you help us understand more about your feature request. Can you clarify what is the current behavior and what is the expected behavior that you want in this new feature?

**Comment by skmcgrail** [comment]
Please review the CodeCommit User Guide on [Working with commits in AWS CodeCommit repositories](https://docs.aws.amazon.com/codecommit/latest/userguide/commits.html) and the service's [API Reference Guides](https://docs.aws.amazon.com/codecommit/latest/APIReference/Welcome.html) to understand the services capabilities provided within the AWS SDKs. If you uncover a bug when attempting to use the SDK, then please cut us a GitHub issue.
