### ISSUE TITLE
ListObjectsV2 returns 'unexpected EOF' on large buckets

### ISSUE THREAD

**Issue by sa7mon** [aws/aws-sdk-go-v2#1717]
### Describe the bug

I have a method which enumerates all the object keys in a bucket using `ListObjectsV2`. When I try this on a bucket with lots of objects (>1 million), the API eventually responds with an 'unexpected EOF' error.

### Expected Behavior

No errors would be returned as I enumerate object keys.

### Current Behavior

After an indeterminate amount of requests (it varies), the SDK throws the following error:

```
https response error StatusCode: 200, RequestID: A9E3MJ2PNNQE261M, HostID: 1pzw76zRTS8heUdSl71v5TM2RtcB6e+UK/hGW4e1jkEEjPUTZJyZ0teRJ6RObW/gJnRcrDFBa+s=, deserialization failed, failed to decode response body, unexpected EOF
```

### Reproduction Steps

```go
var continuationToken *string
continuationToken = nil

for {
	output, err := s3Client.ListObjectsV2(context.TODO(), &s3.ListObjectsV2Input{
		Bucket:            aws.String("my-bucket")
		ContinuationToken: continuationToken,
		EncodingType:      types.EncodingTypeUrl,
	},
	)
	if err != nil {
		return err
	}

	if output.IsTruncated == false {
		break
	}
	continuationToken = output.NextContinuationToken
}

// All objects now enumerated
```

### Additional Information/Context

Example large buckets:

- `12print.it`
- `a360-wp-uploads`

### AWS Go SDK V2 Module Versions Used

```
github.com/aws/aws-sdk-go-v2 v1.16.4
github.com/aws/aws-sdk-go-v2/config v1.15.7
github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.11.12
github.com/aws/aws-sdk-go-v2/service/s3 v1.26.10
```

### Compiler and Version used

1.17

### Operating System and version

Alpine latest

**Comment by RanVaknin** [comment]
Hi @sa7mon ,

I'm sorry for the late response. 

A possible reason you are seeing a status 200 followed by a serialization error is that the S3 server is able to send back a valid response, and before the client is finished reading the body of the successful response, the connection errors out. This can happen for many many reasons and is difficult to pinpoint especially when the pattern is inconsistent like in your case.

It's impossible to know what is happening without the logs. My suggestion to you is to enable logging on the client by doing the following:

```go
	cfg, err := config.LoadDefaultConfig(
		context.Background(),
		config.WithRegion(region),
		config.WithClientLogMode(aws.LogResponseWithBody),
	)
```
With the logs you can see the raw http response the SDK client receives from the s3 server and that might point us in the right direction.
