### ISSUE TITLE
PageSize parameter for dynamodb.Client.Query

### ISSUE THREAD

**Issue by nate-anderson** [aws/aws-sdk-go-v2#1724]
### Describe the feature

The AWS CLI tool for DynamoDB allows specifying a page size (`--page-size`) which is the maximum number of matching items returned by the query. This is different from the `limit` option, which limits the number of items _evaluated_, including those which are not returned to the client.

`dynamodb.QueryInput` should export a `PageSize` property which, when set, limits the number of items returned to the caller, independent of the number of items evaluated.

### Use Case

Pagination with DynamoDB in Go is currently very difficult. Here's an example function

```go
func ListBooks(ctx context.Context, limit int, paginationToken string, paginationKey map[string]types.AttributeValue, client *dynamodb.Client) ([]User, map[string]types.AttributeValue, error) {
	filterExpr := "#active = true"
	result, err := client.Query(ctx, &dynamodb.QueryInput{
		TableName:         &tableName,
		ExclusiveStartKey: paginationKey,
		FilterExpression:  &filterExpr,
		ExpressionAttributeNames: map[string]string{
			"#active": "active",
		},
	})

	if err != nil {
		return []User{}, nil, err
	}

	users := make([]User, len(result.Items))
	err = attributevalue.UnmarshalListOfMaps(result.Items, &users)
	return users, result.LastEvaluatedKey, err
}
```

I see no way to use the `limit` argument without either a) potentially returning more rows than the caller asked for, or b) limiting the returned rows by slicing them off myself and potentially missing them when the caller returns for the next page, because the `LastEvaluatedKey` returned by this query will be past the results I slice off.

### Proposed Solution

A `PageSize` field should be added to the `dynamodb.QueryInput` struct, corresponding to the `--page-size` option used by the AWS CLI.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/credentials@v1.12.4 github.com/aws/aws-sdk-go-v2@v1.16.4
github.com/aws/aws-sdk-go-v2/credentials@v1.12.4 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.5
github.com/aws/aws-sdk-go-v2/credentials@v1.12.4 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.7
github.com/aws/aws-sdk-go-v2/credentials@v1.12.4 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.6
github.com/aws/aws-sdk-go-v2/credentials@v1.12.4 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/credentials@v1.12.4 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.5 github.com/aws/aws-sdk-go-v2@v1.16.4
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.5 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.5 github.com/google/go-cmp@v0.5.7
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.7 github.com/aws/aws-sdk-go-v2@v1.16.4
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.7 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.11
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.7 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.5
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.7 github.com/aws/smithy-go@v1.11.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.6 github.com/aws/aws-sdk-go-v2@v1.16.4
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.6 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.11
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.6 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.5
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.6 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.5

### Go version used

go version go1.18.1 linux/amd64

**Comment by danielkhtse** [comment]
Would it be added soon?

**Comment by aajtodd** [comment]
Both the CLI and AWS SDK for Go work off the same underlying DynamoDB [Query API ](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-Limit)

`--page-size` is mapped to `Limit` in the CLI:




```
> aws dynamodb query --table-name movies --key-condition-expression "#y = :v1" --expression-attribute-values '{":v1":{"N": "2013"}}' --expression-attribute-names  "#y = year"  --page-size 210 --debug

...
2023-02-21 11:48:41,078 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=Query) with params: {'url_path': '/', 'query_string': '', 'method': 'P
OST', 'headers': {'X-Amz-Target': 'DynamoDB_20120810.Query', 'Content-Type': 'application/x-amz-json-1.0', 'User-Agent': 'aws-cli/2.9.21 Python/3.11.1 Darwin/22.3.0 source/x86_
64 prompt/off command/dynamodb.query'}, 'body': b'{"TableName": "movies", "KeyConditionExpression": "#y = :v1", "ExpressionAttributeNames": {"#y": "year"}, "ExpressionAttribute
Values": {":v1": {"N": "2013"}}, "Limit": 210}', 'url': 'https://dynamodb.us-west-2.amazonaws.com/', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config
.Config object at 0x110c53190>, 'has_streaming_input': False, 'auth_type': None}}   

...
```

NOTE: The `Limit: 210` in the request body that was mapped from the `--page-size` CLI argument.

I'd recommend using the provided [Query paginator](https://github.com/aws/aws-sdk-go-v2/blob/main/service/dynamodb/api_op_Query.go#L548). DDB will never process more items than the `Limit` so the number of matching results will be <= the limit.

Closing.
