### ISSUE TITLE
VpcEndpointState's first char is lower case

### ISSUE THREAD

**Issue by liubog2008** [aws/aws-sdk-go-v2#1730]
### Describe the bug

I find the DescribeVpcEndpointConnectionsOutput.VpcEndpointState can't match the consts defined in [enums.go](https://github.com/aws/aws-sdk-go-v2/blob/main/service/ec2/types/enums.go)

The reponse is `pendingAcceptance` but the const in [enums.go](https://github.com/aws/aws-sdk-go-v2/blob/main/service/ec2/types/enums.go#L5739) is `PendingAcceptance`.

### Expected Behavior

They are matched.

### Current Behavior

Not matched.

### Reproduction Steps

..

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/ec2@v1.21.0

### Compiler and Version used

1.18

### Operating System and version

..

**Comment by skmcgrail** [comment]
Thank you for reporting this issue @lloydchang , I have confirmed this behavior and have reached out to the service team internally.

**Comment by liubog2008** [comment]
> Thank you for reporting this issue @lloydchang , I have confirmed this behavior and have reached out to the service team internally.

How about this issue?

**Comment by aajtodd** [comment]
Closing in favor of cross-sdk issue https://github.com/aws/aws-sdk/issues/360, follow any updates there
