### ISSUE TITLE
[shared defaults]: unable to locate files when environment variables are not set

### ISSUE THREAD

**Issue by grrtrr** [aws/aws-sdk-go-v2#1731]
### Describe the bug

This is a replicate of https://github.com/aws/aws-sdk-go/issues/4444, as it is using the same code.

The defaults for `SharedCredentialsFilename()` and `SharedConfigFilename()` in `internal/shareddefaults/shared_config.go` rely on `UserHomeDir()` to return the home directory of the current user:
```go
// internal/shareddefaults/shared_config.go
func UserHomeDir() string {
    if runtime.GOOS == "windows" { // Windows
        return os.Getenv("USERPROFILE")
    }

    // *nix
    return os.Getenv("HOME")
}
```

Not sure if the above code is used, in any way, the _same problem_ also appears in `config/shared_config.go`:
```go
// config/shared_config.go
func DefaultSharedCredentialsFilename() string {
    return filepath.Join(userHomeDir(), ".aws", "credentials")
}

func DefaultSharedConfigFilename() string {
    return filepath.Join(userHomeDir(), ".aws", "config")
}

func userHomeDir() string {
    // Ignore errors since we only care about Windows and *nix.
    homedir, _ := os.UserHomeDir()
    return homedir
}
```

### Expected Behavior

Please see https://github.com/aws/aws-sdk-go/issues/4444

### Current Behavior

Please see https://github.com/aws/aws-sdk-go/issues/4444

### Reproduction Steps

Same as in https://github.com/aws/aws-sdk-go/issues/4444, either of these will cause the problem:
1. `unset HOME`
2. run the compiled program  with a cleared environment: `env -i /path/to/golang/binary`.

### Possible Solution

Use `os/user`, `user.Current().HomeDir` instead of relying on `$HOME`.

### AWS Go SDK V2 Module Versions Used

Problem is independent of modules loaded.

### Compiler and Version used

Problem is independent of Go version.

### Operating System and version

Problem seen/reproduced on Linux, but also present on Windows.

**Comment by RanVaknin** [comment]
Hi @grrtrr ,

I have created a fix [pushed a fix](https://github.com/aws/aws-sdk-go-v2/pull/1794) to address your concern.

Let me know if this works for you.
Cheers~
Ran
