### ISSUE TITLE
Width for code: please increase

### ISSUE THREAD

**Issue by vitaly-zdanevich** [aws/aws-sdk-go-v2#1734]
![image](https://user-images.githubusercontent.com/3514015/174598537-1ca4b357-4164-4d0b-9187-e06212806207.png)

https://aws.github.io/aws-sdk-go-v2/docs/code-examples/s3/generatepresignedurl/

**Comment by jasdel** [comment]
Looks like this width is coming from the following selector set to 80%. Its resonable to either remove this max-width or set it to 100% i think.

```
.td-max-width-on-larger-screens, .td-content > pre, .td-content > .highlight, .td-content > .lead, .td-content > h1, .td-content > h2, .td-content > ul, .td-content > ol, .td-content > p, .td-content > blockquote, .td-content > dl dd, .td-content .footnotes, .td-content > .alert {
    max-width: 80%;
}
```
