### ISSUE TITLE
Support S3 Select API

### ISSUE THREAD

**Issue by blaines** [aws/aws-sdk-go-v2#174]
It seems the S3 Select APIs are available in this SDK but the response handling functionality is missing!

**Comment by jasdel** [comment]
Thanks for reporting this issue @blaines S3 Select API is a feature that the SDK will support. We're working on the V1 SDK's implementation right now. Once v1 SDK's implementation is complete we can port it to V2. The current S3 Select API in the V2 SDK isn't usable and was intended to be suppressed with #160 until support was added.

I created #175 which removes the non-functioning SelectContent API until the EventStream support is available in the V2 SDK. Sorry for the confusion this caused.

**Comment by shvc** [comment]
any update?

**Comment by roganov** [comment]
Not that v2 SDK is generally available, could we have this please?

**Comment by tomasbartkus** [comment]
any update?

**Comment by skmcgrail** [comment]
This is now available as of 2021-11-06 release. https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-11-06
