### ISSUE TITLE
ECS service platform family not available

### ISSUE THREAD

**Issue by ianeal** [aws/aws-sdk-go-v2#1758]
### Describe the bug

Data which is available in SDK v1 is not exposed in SDK v2.  

Confirmed the data is available in the HTTP response in v2 but it is not exposed/populated into the ECS "Service" struct

![image](https://user-images.githubusercontent.com/18007517/178055468-fe00f98b-99f8-48f1-9fb8-d57e36612e92.png)

![image](https://user-images.githubusercontent.com/18007517/178056651-617ba251-4926-4eac-a282-b89dc633c6d8.png)

### Expected Behavior

Expect the data available in AWS SDK v1 to be available in SDK v2 so I can complete the migration.

Expect ecsserviceobj.PlatformFamily to report the expected data.

### Current Behavior

Platform family is not available.

### Reproduction Steps

s.PlatformFamily on SDK v2 reports an error

### Possible Solution

Expose the data and set into the struct

### AWS Go SDK V2 Module Versions Used

        github.com/aws/aws-sdk-go-v2 v1.16.7
        github.com/aws/aws-sdk-go-v2/config v1.15.13
        github.com/aws/aws-sdk-go-v2/service/autoscaling v1.12.2
        github.com/aws/aws-sdk-go-v2/service/cloudformation v1.10.2
        github.com/aws/aws-sdk-go-v2/service/cloudwatch v1.8.2
        github.com/aws/aws-sdk-go-v2/service/ec2 v1.19.0
        github.com/aws/aws-sdk-go-v2/service/ecs v1.9.2
        github.com/aws/aws-sdk-go-v2/service/eks v1.10.2
        github.com/aws/aws-sdk-go-v2/service/elasticache v1.11.2
        github.com/aws/aws-sdk-go-v2/service/iam v1.10.1
        github.com/aws/aws-sdk-go-v2/service/organizations v1.6.2
        github.com/aws/aws-sdk-go-v2/service/rds v1.9.1
        github.com/aws/aws-sdk-go-v2/service/savingsplans v1.5.2

### Compiler and Version used

go 1.18.3

### Operating System and version

Linux Mint 20.3 (Una)

**Comment by RanVaknin** [comment]
Hi @ianeal,

In order to confirm the issue you are having, I have to reproduce it. Please provide a code sample / minimal repo that I could reproduce the issue with (please do not use images as those are difficult to work with).

Once I get clearer repro steps from you, we can move forward with addressing the bug, if it is one.

**Comment by ianeal** [comment]
Closing ticket, the version of ecs services I was using was very old.

With the latest SDK it's fine (ie  github.com/aws/aws-sdk-go-v2/service/ecs v1.18.11)
