### ISSUE TITLE
STS AssumeRoleWithSAML undefined

### ISSUE THREAD

**Issue by ericofusco** [aws/aws-sdk-go-v2#176]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2

### Version of Go (`go version`)?
go version go1.10.2 darwin/amd64

### What issue did you see?
sts.AssumeRoleWithSAML undefined

You can check at api.go, function doesn't exist.
https://github.com/aws/aws-sdk-go-v2/blob/master/service/sts/api.go

Getting error below:
`svc.AssumeRoleWithSAML undefined (type *sts.STS has no field or method AssumeRoleWithSAML)
`
### Steps to reproduce
```
input := &sts.AssumeRoleWithSAMLInput{
    DurationSeconds: aws.Int64(3600),
    PrincipalArn:    aws.String("arn:aws:iam::11111:saml-provider/idp"),
    RoleArn:         aws.String("arn:aws:iam::11111:role/idp-role"),
    SAMLAssertion:   aws.String(saml),
}

cfg, err := external.LoadDefaultAWSConfig()
svc := sts.New(cfg)
output, err := svc.AssumeRoleWithSAML(input)
```

**Comment by jasdel** [comment]
Thanks for reaching out to us @ericofusco. I think the issue you're running into is that the pattern of how an API call is made changed with the V2 SDK. Instead of calling `AssumeRoleWithSAML` to make an API request your application will use the method `AssumeRoleWithSAMLRequest` to build an API request. With the request you can call `Send` method to send the API request.

```go
svc := sts.New(cfg)

req := svc.AssumeRoleWithSAMLRequest(input)
output, err := req.Send()
```

Check out this [doc](https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#api-request-methods) for more information on why the calling style was changed.

**Comment by ericofusco** [comment]
Hi @jasdel, thanks a lot for the clarification.

Since there are methods that were removed from the previous version I suggest to have a new doc only for v2, or update the documentation saying these methods are not available on v2 (https://docs.aws.amazon.com/sdk-for-go/api/service/sts/#STS.AssumeRoleWithSAML)

**Comment by jh125486** [comment]
> Thanks for reaching out to us @ericofusco. I think the issue you're running into is that the pattern of how an API call is made changed with the V2 SDK. Instead of calling `AssumeRoleWithSAML` to make an API request your application will use the method `AssumeRoleWithSAMLRequest` to build an API request. With the request you can call `Send` method to send the API request.
> 
> ```go
> svc := sts.New(cfg)
> 
> req := svc.AssumeRoleWithSAMLRequest(input)
> req.SetContext(ctx) // Modify the request, like setting a context.
> output, err := req.Send()
> 
> // Or
> output, err := svc.AssumeRoleWithSAMLRequest(input).Send()
> ```
> 
> Check out this [doc](https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#api-request-methods) for more information on why the calling style was changed.

Is there any updated documentation on this?  (AssumeRoleWithSAMLRequest does not exist as far as I can tell)
