### ISSUE TITLE
DAX support

### ISSUE THREAD

**Issue by yasensim** [aws/aws-sdk-go-v2#1763]
### Describe the feature

We use V2 for dynamodb and import V1 just for DAX. Please add DAX support.
There is a lot of demand for it: https://github.com/aws/aws-dax-go/issues/2

### Use Case

use DAX as cashing for dynamoDB

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

v1.16.5

### Go version used

go version go1.18.3 darwin/amd64

**Comment by vudh1** [comment]
Hi @yasensim the link above: https://github.com/aws/aws-dax-go/issues/2 is not SDK. Hence, we cannot implement this feature. Please track this issue from that link since we are closing this issue.
