### ISSUE TITLE
DynamoDB: SerializationException for map keys with escaped double quotes

### ISSUE THREAD

**Issue by xorxsan** [aws/aws-sdk-go-v2#1764]
### Describe the bug

Maps whose keys contain escaped double quotes (`\"`) throw a `SerializationException: UnknownError` when trying to add them to dynamodb using `PutItem` or `BatchWriteItem` operations.

### Expected Behavior

No error thrown by the API.

### Current Behavior

I'm getting the following error:

```
operation error DynamoDB: PutItem, https response error StatusCode: 400, RequestID: <request id>, api error SerializationException: UnknownError
```

### Reproduction Steps

```go
package main

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

type Wrong struct {
	Values map[string]string
}

func main() {
	cfg, err := config.LoadDefaultConfig(
		context.Background(),
		config.WithRegion("eu-west-1"),
	)
	if err != nil {
		panic(fmt.Sprintf("Error configuring AWS: %s", err))
	}
	
	db := dynamodb.NewFromConfig(cfg)

	item, err := attributevalue.MarshalMap(Wrong{
		Values: map[string]string{
			"wrong value\"": "right value \"",
		},
	})
	if err != nil {
		fmt.Println(err)
	}

	putItemInput := dynamodb.PutItemInput{
		TableName: aws.String("my-table"),
		Item:      item,
	}

	putItemOutput, err := db.PutItem(context.Background(), &putItemInput)
	if err != nil {
		panic(fmt.Sprintf("Error putting item into table: %s", err))
	}

	fmt.Printf("%v\n", putItemOutput)
}

```

### AWS Go SDK V2 Module Versions Used

```
go 1.18

require (
	github.com/aws/aws-sdk-go-v2 v1.16.7
	github.com/aws/aws-sdk-go-v2/config v1.15.14
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.9.6
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.15.9
)

require (
	github.com/aws/aws-sdk-go-v2/credentials v1.12.9 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.14 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.15 // indirect
	github.com/aws/aws-sdk-go-v2/service/dynamodbstreams v1.13.9 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.9.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.7.8 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.8 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.11.12 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.9 // indirect
	github.com/aws/smithy-go v1.12.0 // indirect
	github.com/jmespath/go-jmespath v0.4.0 // indirect
)
```

### Compiler and Version used

go version go1.18.3 windows/amd64

### Operating System and version

Windows 10 x64

**Comment by RanVaknin** [comment]
Hi @xorxsan ,

I see two things that are wrong here. First this specific error you are seeing is coming from the DDB Service API, not from the SDK. Based on[ this article ](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html) you can see that the Dynamo API does not support names with a quotes in them.

> The following are the naming rules for DynamoDB:
> 
> All names must be encoded using UTF-8, and are case-sensitive.
> 
> Table names and index names must be between 3 and 255 characters long, and can contain only the following characters:
> 
> - a-z
> - A-Z
> - 0-9
> - _ (underscore)
> -  -(dash)
> - . (dot)

Moreover, even if you fixed your entry with a format that is supported by the API, you are still missing a primary key in your `Wrong` struct. I _think_ you will end up with this error:

```console
panic: Error putting item into table: operation error DynamoDB: PutItem, https response error StatusCode: 400, RequestID: SOME_REQUEST_ID , api error ValidationException: One or more parameter values were invalid: Missing the key <primary_key> in the item
```

To solve that, add the primary key to your Wrong struct

```go
type Wrong struct {
    ID int     // your primary key
    // Foo int  (optional) your sort key if you have one
    Values map[string]string

}
```

And when you are going marshaling into DDB types dont forget to pass in that primary key value:
```go
item, err := attributevalue.MarshalMap(&Wrong{
	ID: 4,
	Values: map[string]string{
		"foo": "bar",
	},
})
```

Let me know if this answers your question.

Cheers~
Ran

**Comment by xorxsan** [comment]
Hi @RanVaknin,

   it's not clear to me that the naming rules you quoted apply to maps' keys, as the article only mentions table names and indexes. I'm saying this because we finally managed to circumvent this issue by escaping the `\` with more `\` like so:
```
		Values: map[string]string{
			"wrong value\\\"": "right value \"",
		},
```
But I'd expect the API to take care of that escaping if possible.

As for the lack of primary key you are right. I did not think about it when I created this example.

Thanks!

**Comment by RanVaknin** [comment]
Hi @xorxsan ,

Thanks for bringing this to my attention.

I have [fixed the escaping issue](https://github.com/aws/smithy-go/pull/375). Please update your project with the latest version of the SDK by running:
```
go get github.com/aws/aws-sdk-go-v2/…@latest
```

If this persist, feel free to re-open the issue or cut a new one and I will address it. 

Cheers~
Ran
