### ISSUE TITLE
Contradictory documentation on usage of ec2/imds GetRegion

### ISSUE THREAD

**Issue by tuxpower** [aws/aws-sdk-go-v2#1765]
https://aws.github.io/aws-sdk-go-v2/docs/sdk-utilities/ec2-imds/#retrieving-an-instances-region

The function returns a value of type `*GetRegionOutput`.

https://aws.github.io/aws-sdk-go-v2/docs/sdk-utilities/ec2-imds/

includes the following example snippet:
```go
region, err := client.GetRegion(context.TODO(), &imds.GetRegionInput{})
if err != nil {
    log.Printf("Unable to retrieve the region from the EC2 instance %v\n", err)
}

fmt.Printf("region: %v\n", region)
```

However, this example will not produce the expected result:
```
region: &{eu-central-1 {map[{}:{[{<nil> false false {map[]}}]}]}}
```

Here is an example that works:

```go
package main

import (
        "context"
        "fmt"
        "log"

        "github.com/aws/aws-sdk-go-v2/config"
        "github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
)

func main() {
        cfg, err := config.LoadDefaultConfig(context.TODO())
        if err != nil {
                log.Fatalf("failed to load SDK configuration, %v", err)
        }

        client := imds.NewFromConfig(cfg)

        resp, err := client.GetRegion(context.TODO(), &imds.GetRegionInput{})
        if err != nil {
                log.Printf("Unable to retrieve the region from the EC2 instance %v\n", err)
        }

        fmt.Printf("region: %v\n", resp.Region)
}
```

### Links

https://aws.github.io/aws-sdk-go-v2/docs/sdk-utilities/ec2-imds/

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/config v1.15.14
github.com/aws/aws-sdk-go-v2/ec2imds v0.1.5

**Comment by RanVaknin** [comment]
Hi @tuxpower ,

Thanks for letting us know. Sorry this took so long. 
I have submitted a fix and is pending.

Thank you for being an active member in the community!

All the best,
Ran
