### ISSUE TITLE
config.LoadDefaultConfig not erroring when it should ?

### ISSUE THREAD

**Issue by udf2457** [aws/aws-sdk-go-v2#1767]
### Describe the bug

Given the following code:

```go
func AssumeRoleWithStsUsingProfile(profile string, roleARN string) (aws.Config, error) {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithSharedConfigProfile(profile))
	if err != nil {
		return aws.Config{}, err
	}
	stsSvc := sts.NewFromConfig(cfg)
	creds := stscreds.NewAssumeRoleProvider(stsSvc, roleARN)
	cfg.Credentials = aws.NewCredentialsCache(creds)
	return cfg, nil
}
```

and the following test (i.e. profile `foobar` and arn `foobar` do not exist):

```go
func TestAssumeRoleWithStsUsingProfile(t *testing.T) {
	t.Parallel()
	_, err := AssumeRoleWithStsUsingProfile("foobar", "foobar")
	if err != nil {
		t.Error(err)
	}
}
```

I would expect this to error ?

But instead `err == nil` and the test passes

### Expected Behavior

`err != nil`

### Current Behavior

`err == nil`

### Reproduction Steps

See code in original description

### AWS Go SDK V2 Module Versions Used

From go.mod:

require github.com/aws/aws-sdk-go-v2/config v1.15.14

require (
	github.com/aws/aws-sdk-go-v2 v1.16.7 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.12.9 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.14 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.15 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.8 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.11.12 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.9 // indirect
	github.com/aws/smithy-go v1.12.0 // indirect
)

### Compiler and Version used

go version go1.18.3 darwin/amd64

### Operating System and version

OS X Monterey 12.4

**Comment by RanVaknin** [comment]
Hi @udf2457 ,

The SDKs credential providers are implementing use a "lazy" retrieve method. Meaning that until an API request is made, that `provider.Retrieve()` method is not called.

If you want to make an "eager" implementation of fetching credentials, you can do this:
```go
func AssumeRoleWithStsUsingProfile(profile string, roleARN string) (aws.Config, error) {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithSharedConfigProfile(profile), config.WithRegion("us-east-1"))
	if err != nil {
		return aws.Config{}, err
	}
	stsSvc := sts.NewFromConfig(cfg)
	provider := stscreds.NewAssumeRoleProvider(stsSvc, roleARN) // changed variable name from cred to provider
	creds, err := provider.Retrieve(context.TODO())
	if err != nil {
		panic(err)
	}
	fmt.Println(creds)

	cfg.Credentials = aws.NewCredentialsCache(provider)
	return cfg, nil
}
```

Let me know if you need anything else.

Cheers,
Ran
