### ISSUE TITLE
NewDownloader - AWS S3 CMK compatible ?

### ISSUE THREAD

**Issue by udf2457** [aws/aws-sdk-go-v2#1769]
### Describe the bug

I validated a CMK implementation using ` _, err = downloader.Download(context.TODO(), fil, input)`  and the following config:

```
	input := &s3.GetObjectInput{
		Bucket:               aws.String(bucket),
		Key:                  aws.String(key),
		SSECustomerAlgorithm: aws.String(cmkAlgo),
		SSECustomerKey:       aws.String(cmk),
		SSECustomerKeyMD5:    aws.String(cmkHash),
		ChecksumMode:         s3ChecksumMode,
	}
```

The file successfully downloaded, no problems.

Now I have attempted to "drop-in" download manger, using the following call:
```
	downloader := manager.NewDownloader(client, func(u *manager.Downloader) {
		u.PartSize = downloadPartSize
		u.Concurrency = downloadConcurrency
	})
```

And with `ChecksumMode` removed from the config:
```
	input := &s3.GetObjectInput{
		Bucket:               aws.String(bucket),
		Key:                  aws.String(key),
		SSECustomerAlgorithm: aws.String(cmkAlgo),
		SSECustomerKey:       aws.String(cmk),
		SSECustomerKeyMD5:    aws.String(cmkHash),
		// ChecksumMode:         s3ChecksumMode,
	}
````

And changed

```
 res, err := client.GetObject(context.TODO(), input)
_, err = io.Copy(fil, res.Body)
```

to

```
  _, err = downloader.Download(context.TODO(), fil, input)
```

But now I get an error: 
`operation error S3: GetObject, https response error StatusCode: 403, RequestID: TSZ81Q7QJ55ZNAM8, HostID: ywJwZmubrAmlfbEaqXZFKLJXoivopKBaFWuaDDIhJdbkHrKTc76I4DmMaVgg3CYYLJ2Cq3YLzNg=, api error AccessDenied: Access Denied`

Is `NewDownloader` compatible with AWS S3 CMK ?  Otherwise does `NewDownloader` require different IAM permissions to standard `GetObject` ?

### Expected Behavior

File downloads

### Current Behavior

File does not download

### Reproduction Steps

See main text

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2 v1.16.7
	github.com/aws/aws-sdk-go-v2/config v1.15.14
	github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.11.20
	github.com/aws/aws-sdk-go-v2/service/s3 v1.27.1

### Compiler and Version used

go version go version go1.18.3 darwin/amd64

### Operating System and version

OS X Monterey 12.4

**Comment by RanVaknin** [comment]
Hi @udf2457 ,

Downloader calls getObject under the hood and should not have different IAM permissions. 

This is difficult to test without proper reproduction steps. If you want me to reproduce please include your full code example for getObject and the example with downloader.

A debug step you can try to do yourself is to enable request logs and see how your requests are being sent over the wire and how they differ.

You can enable request logs by doing the following:
```go
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogRequestWithBody))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}
```


Let me know if this helps,
Thanks,
Ran~
