### ISSUE TITLE
GetDocumentationParts Path issue

### ISSUE THREAD

**Issue by Rushilparikh1** [aws/aws-sdk-go-v2#1776]
### Describe the bug

we should get the documentation info of the resources/methods for the specified path strictly.

### Expected Behavior

in the input parameters for GetDocumentationParts in apigateway service, we should get the documentation details strictly for the path specified.

### Current Behavior

in the input parameters for GetDocumentationParts in apigateway service, when we are providing the path of the api entity, we are getting the documentation details of all the child resources of the path specified too.

### Reproduction Steps

just run this query on AWS CLI
aws apigateway get-documentation-parts --rest-api-id <input> --path <input> --location-status DOCUMENTED --type METHOD --no-cli-pager
make sure that the path provided has child resources and all the resources have method documentation in them

example:
create api alpha
add resources abc, abc/def, abc/def/xyz
add methods to these 3 resources
add documentation in these methods

run this
`aws apigateway get-documentation-parts --rest-api-id <api id of alpha> --path </abc> --location-status DOCUMENTED --type METHOD --no-cli-pager`

expected behaviour:
it should give documentation details of /abc only

current behaviour:
it is giving documentation details of /abc, /abc/def, /abc/def/xyz

### AWS Go SDK V2 Module Versions Used

go 1.18

require (
	github.com/aws/aws-sdk-go v1.40.54
	github.com/aws/aws-sdk-go-v2/config v1.15.11
	github.com/aws/aws-sdk-go-v2/service/apigateway v1.15.7
	github.com/aws/aws-sdk-go-v2/service/sqs v1.19.0
	github.com/bxcodec/faker/v3 v3.8.0
	github.com/dgrijalva/jwt-go v3.2.0+incompatible
	github.com/gin-gonic/gin v1.7.4
	github.com/go-playground/validator/v10 v10.4.1
	github.com/go-redis/redis/v8 v8.11.4
	github.com/golang-migrate/migrate/v4 v4.15.2
	github.com/newrelic/go-agent/v3 v3.3.0
	github.com/newrelic/go-agent/v3/integrations/logcontext/nrlogrusplugin v1.0.1
	github.com/newrelic/go-agent/v3/integrations/nrgin v1.1.2
	github.com/sirupsen/logrus v1.8.1
	github.com/spf13/viper v1.9.0
	go.mongodb.org/mongo-driver v1.9.1
	golang.org/x/exp v0.0.0-20220706164943-b4a6d9510983
)

require (
	github.com/aws/aws-sdk-go-v2 v1.16.7 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.12.6 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.6 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.14 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.13 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.6 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.11.9 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.7 // indirect
	github.com/aws/smithy-go v1.12.0 // indirect
	github.com/cenkalti/backoff/v4 v4.1.2 // indirect
	github.com/cespare/xxhash/v2 v2.1.2 // indirect
	github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f // indirect
	github.com/fsnotify/fsnotify v1.5.1 // indirect
	github.com/gin-contrib/sse v0.1.0 // indirect
	github.com/go-playground/locales v0.13.0 // indirect
	github.com/go-playground/universal-translator v0.17.0 // indirect
	github.com/go-stack/stack v1.8.0 // indirect
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/golang/snappy v0.0.4 // indirect
	github.com/hashicorp/errwrap v1.1.0 // indirect
	github.com/hashicorp/go-multierror v1.1.1 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/jmespath/go-jmespath v0.4.0 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/klauspost/compress v1.13.6 // indirect
	github.com/leodido/go-urn v1.2.0 // indirect
	github.com/magiconair/properties v1.8.5 // indirect
	github.com/mattn/go-isatty v0.0.12 // indirect
	github.com/mitchellh/mapstructure v1.4.2 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/pelletier/go-toml v1.9.4 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/spf13/afero v1.6.0 // indirect
	github.com/spf13/cast v1.4.1 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/subosito/gotenv v1.2.0 // indirect
	github.com/ugorji/go/codec v1.1.7 // indirect
	github.com/xdg-go/pbkdf2 v1.0.0 // indirect
	github.com/xdg-go/scram v1.0.2 // indirect
	github.com/xdg-go/stringprep v1.0.2 // indirect
	github.com/youmark/pkcs8 v0.0.0-20181117223130-1be2e3e5546d // indirect
	go.uber.org/atomic v1.7.0 // indirect
	golang.org/x/crypto v0.0.0-20210921155107-089bfa567519 // indirect
	golang.org/x/sync v0.0.0-20210220032951-036812b2e83c // indirect
	golang.org/x/sys v0.0.0-20220317061510-51cd9980dadf // indirect
	golang.org/x/text v0.3.7 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
	gopkg.in/ini.v1 v1.63.2 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
)

### Compiler and Version used

go version go1.18.3 darwin/amd64

### Operating System and version

macOS Monterey, version 12.4

**Comment by vudh1** [comment]
Hi @Rushilparikh1 can you clarify if this is a Go SDK issue? If yes, can you provide a sample of reproducible code that you are using so we can investigate this better?

**Comment by Rushilparikh1** [comment]
@vudh1 I raised it with AWS support team. They said it isn't a bug.
The reason child resources are also shown is because child resources have a precedence over parent resources.
But anyways, if you want to reproduce the behaviour, I have mentioned the steps in the issue that I have raised.

**Comment by Rushilparikh1** [comment]
@vudh1 I raised it with AWS support team. They said it isn't a bug.
The reason child resources are also shown is because child resources have a precedence over parent resources.
But anyways, if you want to reproduce the behaviour, I have mentioned the steps in the issue that I have raised. This isn't just with GO sdk but with sdk in general
Steps that I have provided are using AWS CLI
