### ISSUE TITLE
On the Using the AWS SDK for Go V2 with AWS Services link to AWS SDK for Go V2 API Reference is wrong

### ISSUE THREAD

**Issue by inv-vignesh** [aws/aws-sdk-go-v2#1777]
### Describe the issue

The link AWS SDK for Go V2 API Reference in https://aws.github.io/aws-sdk-go-v2/docs/making-requests/ redirects back to the same page. It should go to https://aws.github.io/aws-sdk-go-v2/docs/making-requests/ i think.

### Links

https://aws.github.io/aws-sdk-go-v2/docs/making-requests/

**Comment by RanVaknin** [comment]
Hi @inv-vignesh,

I think this was fixed? I'm able to click on the `AWS SDK for Go V2 API Reference` and it takes me to the correct link.

**Comment by inv-vignesh** [comment]
Yes the issue is fixed now. I checked.
Closing it.
