### ISSUE TITLE
Region required for IAM Client

### ISSUE THREAD

**Issue by principis** [aws/aws-sdk-go-v2#1778]
### Describe the bug

According to the [documentation](https://docs.aws.amazon.com/general/latest/gr/rande.html), IAM doesn't support regions
> Some services, such as IAM, do not support Regions.

Creating a client with `iam.New` or `iam.NewFromConfig` without specifying a region causes any operation (e.g. `ListUsers`) to throw the following error: `failed to resolve service endpoint, an AWS region is required, but was not found`

The client works as expected if any **nonempty** string is supplied as region.

### Expected Behavior

Creating an IAM client without specifying a region doesn't throw a region error.

### Current Behavior

The following error is thrown:
```
operation error IAM: ListUsers, failed to resolve service endpoint, an AWS region is required, but was not found
```

### Reproduction Steps

Ommitting the region, or supplying an empty string doesn't work:
```golang
cfg, _ := config.LoadDefaultConfig(context.TODO(), config.WithRegion(""))
client := iam.NewFromConfig(cfg)
_, err := client.ListUsers(context.TODO(), nil)
fmt.Println(err)
```

Supplying a space as region works:
```golang
cfg, _ := config.LoadDefaultConfig(context.TODO(), config.WithRegion(" "))
client := iam.NewFromConfig(cfg)
_, err := client.ListUsers(context.TODO(), nil)
fmt.Println(err)
```

### Possible Solution

Don't check region by length: https://github.com/aws/aws-sdk-go-v2/blob/d77599dedac844f5921b6525cab190d99dd9c13a/service/iam/internal/endpoints/endpoints.go#L71-L78

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2@v1.16.7 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2@v1.16.7 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.16.7 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/aws/aws-sdk-go-v2/credentials@v1.12.9
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.8
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.15
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.12
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.9
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2/config@v1.15.14 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/credentials@v1.12.9 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/credentials@v1.12.9 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.8
github.com/aws/aws-sdk-go-v2/credentials@v1.12.9 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.12
github.com/aws/aws-sdk-go-v2/credentials@v1.12.9 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.9
github.com/aws/aws-sdk-go-v2/credentials@v1.12.9 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2/credentials@v1.12.9 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.8 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.8 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.8 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.14 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.8 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.8 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.8 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.15 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/service/iam@v1.18.9 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/service/iam@v1.18.9 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.14
github.com/aws/aws-sdk-go-v2/service/iam@v1.18.9 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.8
github.com/aws/aws-sdk-go-v2/service/iam@v1.18.9 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.8 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.8 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.8 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.12 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.12 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.14
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.12 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.8
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.12 github.com/aws/smithy-go@v1.12.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.9 github.com/aws/aws-sdk-go-v2@v1.16.7
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.9 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.14
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.9 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.8
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.9 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.8
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.9 github.com/aws/smithy-go@v1.12.0

### Compiler and Version used

go version go1.18.4 linux/amd64

### Operating System and version

Fedora 36 kernel  5.18.13

**Comment by RanVaknin** [comment]
Hi @principis ,

IAM is a global service in the sense that no matter which region is specified, your `listUsers` command should return the same result. The reason the SDK requires a region is to know which AWS partition to direct your request to.
If you pass in an invalid region, then the default region from your shared config file would be loaded instead.

**Comment by principis** [comment]
@RanVaknin There is no shared config file. The client shouldn't throw an error if an empty string, or nothing (which is effectively the same) is passed. I checked the request, and no matter what region is passed, the HTTP request (headers, url, body, ...) stays the same.

So I am not sure what you mean with `AWS partition` but it's not applicable to this issue...

Please reopen this issue.

**Comment by RanVaknin** [comment]
Hi @principis ,

The AWS SDK requires a region for the client so it can route to the appropriate IAM endpoint for the partition associated with the given region.
https://docs.aws.amazon.com/general/latest/gr/iam-service.html

With regards to string with spaces, that is because we don’t strip the region identifiers and treat them as entirely opaque.
What you are witnessing by such behavior is that if they given a non zero length string that the SDK doesn’t know how to explicitly handle as a region, it will just by default fallback to the AWS partition and try to form a URL using that region identifier. In this case since the service is not a regional service, it will just fallback to the service’s partition endpoint. The SDK does this for forwards compatibility reasons so that new regions “just work” without requiring users to update.

**Conclusion:**
This is the expected behavior, and there are no plans to change it.

Let me know if you have any other questions.

Cheers~
Ran

**Comment by principis** [comment]
@RanVaknin Thank you for the comprehensive answer!
