### ISSUE TITLE
Improve Getting Started docs to make them systemd "safe"

### ISSUE THREAD

**Issue by udf2457** [aws/aws-sdk-go-v2#1780]
### Describe the issue

At present, the Getting Started docs all show `config.LoadDefaultConfig(context.TODO())` as the preferred way to do things.

Which is fine insofar as it works great if you are triggering a Go app manually.

The problem is that if you then go use `systemd` to trigger your app, you will find it will fail.

Why ?

Because `systemd` does not set `$HOME` by default and thus the application [will fail due to `UserHomeDir()` returning nothing](https://github.com/aws/aws-sdk-go-v2/blob/b7d8e15425d2f86a0596e8d7db2e33bf382a21dd/internal/shareddefaults/shared_config.go).

The fix for this is to use `EnvironmentFile` in systemd, and in that environment file,  you add two parameters:

```
AWS_CONFIG_FILE=""
AWS_SHARED_CREDENTIALS_FILE=""

```

This should be be better and more clearly documented.  Because at the moment, zero mention is made in the docs of `EnvironmentFile`, `AWS_CONFIG_FILE` or `AWS_SHARED_CREDENTIALS_FILE`.

`systemd` is a common tool and interop should be more clearly documented.

### Links

Just two examples (more pages follow similar structure).
https://aws.github.io/aws-sdk-go-v2/docs/getting-started/
https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/

**Comment by RanVaknin** [comment]
Hi @udf2457 ,

I have created a fix https://github.com/aws/aws-sdk-go-v2/pull/1794 to address your concern.

please update your project with the latest version of the SDK and let me know if this works for you.
Cheers~
Ran
