### ISSUE TITLE
Broken link to example in GeneratePresignedURLv2 Documentation

### ISSUE THREAD

**Issue by davidoconn** [aws/aws-sdk-go-v2#1792]
### Describe the issue

The link at the end of the page https://aws.github.io/aws-sdk-go-v2/docs/code-examples/s3/generatepresignedurl to [complete example in GitHub](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/gov2/s3/GeneratePresignedURL/GeneratePresignedURLv2.go) is incorrect.

### Links

https://aws.github.io/aws-sdk-go-v2/docs/code-examples/s3/generatepresignedurl/

**Comment by RanVaknin** [comment]
Hi @davidoconn ,

Thanks for submitting this issue. We are aware that there are issues with documentation and this will probably be addressed at a later point in time as a part of a bigger effort to improve our docs.

Let me know if you need anything else.

Cheers,
Ran

**Comment by RanVaknin** [comment]
Issue is now fixed 😄 

Thank you for engaging in the community and helping us make the SDK better!

All the best,
Ran~
