### ISSUE TITLE
Go get github.com/aws/aws-sdk-go-v2/feature/dynamodb not working, unable to add import "github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"

### ISSUE THREAD

**Issue by EarlChough** [aws/aws-sdk-go-v2#1803]
### Describe the bug

I have a simple Go function trying to update a visitor counter for a website using lambda and dynamodb using SAM CLI

I am unable to import "github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue" to the function. 
When trying to save the import is removed.
go mod vendor instructs me to run go get github.com/aws/aws-sdk-go-v2/feature/dynamodb but then go get fails.

I am trying to get attributevalues to work for the function. 

### Expected Behavior

everything not get getting an error message for these commands

### Current Behavior

First I am unable to add the import "github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue" in my main.go file
When saving the file the import disappears. 

I am able to add "github.com/aws/aws-sdk-go-v2/feature/dynamodb" but then when I try to build it fails
`Build Failed
Error: GoModulesBuilder:Build - Builder Failed: main.go:12:2: cannot find package "." in:
        /tmp/samcli/source/vendor/github.com/aws/aws-sdk-go-v2/feature/dynamodb
Running GoModulesBuilder:Build`

Trying to do go get for "github.com/aws/aws-sdk-go-v2/feature/dynamodb" I get:
`go: module github.com/aws/aws-sdk-go-v2@upgrade found (v1.16.11), but does not contain package github.com/aws/aws-sdk-go-v2/feature/dynamodb`

### Reproduction Steps

```go
package main

import (
	"context"
	"log"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

func handler(request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {

	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	svc := dynamodb.NewFromConfig(cfg)

	// Build the request with its input parameters
	resp, err := svc.UpdateItem(context.TODO(), &dynamodb.UpdateItemInput{
		TableName: aws.String("table-name"),
		Key: map[string]*dynamodb.attributevalue{
			"ID": {
				S: aws.String("visitors"),
			},
		},
		UpdateExpression: aws.String("ADD visitors :inc"),
		ExpressionAttributeValues: map[string]*dynamodb.attributevalue{
			":inc": {
				N: aws.String("1"),
			},
		},
	})

	if err != nil {
		log.Fatalf("Got error callingUpdateItem: %s", err)
	}

	return events.APIGatewayProxyResponse{
		Headers: map[string]string{
			"Access-Control-Allow-Origin":  "*",
			"Access-Control-Allow-Methods": "*",
			"Access-Control-Allow-Headers": "*",
		},
		StatusCode: 200,
	}, nil
}

func main() {
	lambda.Start(handler)
}
```

### AWS Go SDK V2 Module Versions Used

```
require (
	github.com/aws/aws-lambda-go v1.23.0
	github.com/aws/aws-sdk-go-v2 v1.16.11
	github.com/aws/aws-sdk-go-v2/config v1.17.0
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.15.13
)

require (
	github.com/aws/aws-sdk-go-v2/credentials v1.12.13 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.12 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.18 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.12 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.19 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.9.5 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.7.12 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.12 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.11.16 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.13 // indirect
	github.com/aws/smithy-go v1.12.1 // indirect
	github.com/jmespath/go-jmespath v0.4.0 // indirect
)

```

### Compiler and Version used

go 1.18

### Operating System and version

Windows 11 Version 10.0.22000 Build 22000

**Comment by RanVaknin** [comment]
Hi @EarlChough ,

`AttributeValue` is in the `service/dynamodb/types` module and should look like this:
```go
resp, err := svc.UpdateItem(context.TODO(), &dynamodb.UpdateItemInput{
	TableName: aws.String("table-name"),
	Key: map[string]types.AttributeValue{
		    //arguments go here
	}
}
```

Please let me know if this helps.
~Ran
