### ISSUE TITLE
Add CloudWatch code example from AWS SDK docs repo

### ISSUE THREAD

**Issue by carlos-jmh** [aws/aws-sdk-go-v2#1808]
### Describe the issue

I recently contributed a new code example, *GetLogEvents*, under CloudWatch examples to the  AWS SDK docs repository. This issue is a request to update the docs to include this (not sure if this is the proper way to request this, let me know).

Thanks

### Links

GetLogEvents under AWS SDK docs repo:
https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/gov2/cloudwatch/GetLogEvents
Location to be added:
https://github.com/aws/aws-sdk-go-v2/tree/documentation/content/en/docs/code-examples/cloudwatch

**Comment by RanVaknin** [comment]
Hi @carlos-jmh ,

First of all I'd like to thank you for your contribution! 

The `awsdocs` repo is owned by a completely separate team (I know, it's kind of funny).
I would transfer the issue there but they are on a completely separate organization so I can't even do that.
I'll suggest opening an issue there and they will be able to help. 

Thanks again!
Ran~
