### ISSUE TITLE
Current version of aws-sdk-go-v2/service/sts uses functionality from smithyhttp that does not exist in its current version.

### ISSUE THREAD

**Issue by LeShadow** [aws/aws-sdk-go-v2#1811]
### Describe the bug

Upon compiling my go project, I get to see the following error:

```
# github.com/aws/aws-sdk-go-v2/service/sts
../github.com/aws/aws-sdk-go-v2/service/sts/api_client.go:515:22: undefined: http.AddNoPayloadDefaultContentTypeRemover

Compilation finished with exit code 2
```

Now, I went to look as to why this is happening and according to what I have found, the AWS Golang SDK is using a version (v1.12.1) of smithy-go that does not contain abovementioned method. The file that is referencing to this method can be found [here](https://github.com/aws/aws-sdk-go-v2/blame/2efd426ab3a988fdc338634de3920b044e20e999/service/sts/api_client.go#L515)

That specific method I only found in smithy-go, in a weird tag: [Here](https://github.com/aws/smithy-go/blob/a73437245610ac013c23f64e3347fc77771ee020/transport/http/middleware_headers.go#L36)

Without this function it is impossible to compile your go binary it seems.

### Expected Behavior

Successfull compilation of my project.

### Current Behavior

Project fails to compile because of usage of undefined methods by the STS part of the AWS SDK for Golang.

### Reproduction Steps

- go get github.com/aws/aws-sdk-go-v2/aws
- go get github.com/aws/aws-sdk-go-v2/config
- go get github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs
- go get github.com/aws/aws-sdk-go-v2/service/cloudwatchevents
- go get github.com/aws/aws-sdk-go-v2/aws/session
- Write some Golang code where your import block might look like this:
```
import (
	"context"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	"sync"
)
```
- Compile --> Where the error appears.

### AWS Go SDK V2 Module Versions Used

Last release as mentioned here: [https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2022-08-19](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2022-08-19)

### Compiler and Version used

go version go1.18.1 darwin/arm64

### Operating System and version

macOS Monterrey 12.3.1

**Comment by RanVaknin** [comment]
Hi @LeShadow ,

I'm not able to reproduce your error.
I'm able to get those modules, run some cloudwatch related commands, build and run it just fine:

```go
import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	"log"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	cloudwatchClient := cloudwatchlogs.NewFromConfig(cfg)

	response, err := cloudwatchClient.ListTagsLogGroup(context.Background(), &cloudwatchlogs.ListTagsLogGroupInput{LogGroupName: aws.String("/aws/lambda/3183")})
	if err != nil {
		fmt.Println("error!", err.Error())
	}

	for k, v := range response.Tags {
		fmt.Println(k, ",", v)
	}
}
```

`go.mod`:
```
go 1.18

require (
	github.com/aws/aws-sdk-go-v2 v1.16.14 // indirect
	github.com/aws/aws-sdk-go-v2/config v1.17.5 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.12.18 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.15 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.21 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.15 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.22 // indirect
	github.com/aws/aws-sdk-go-v2/service/cloudwatchevents v1.14.17 // indirect
	github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs v1.15.18 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.15 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.11.21 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.13.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.17 // indirect
	github.com/aws/smithy-go v1.13.2 // indirect
)
```

There is no way of knowing what went wrong on your end because you didn't include the `go.mod` file.
Please follow this step in the submission form so I can better understand the problem:
>AWS Go SDK V2 Module Versions Used
Output of go mod graph or go.mod file listing the github.com/aws/* entries.
