### ISSUE TITLE
SignatureDoesNotMatch error when used with GCS

### ISSUE THREAD

**Issue by boraberke** [aws/aws-sdk-go-v2#1816]
### Describe the bug

I'm facing `SignatureDoesNotMatch` error when I use endpoint url as google cloud storage [https://storage.googleapis.com](url). 

I didn't have this error when using `aws-sdk-go`.

### Expected Behavior

To be able to send requests successfully just like in `aws-sdk-go`.

### Current Behavior

I used a simple code where I try to `ListBuckets` with default settings. Following is the debug output and error:
```
SDK 2022/08/25 10:01:40 DEBUG Request Signature:
---[ CANONICAL STRING  ]-----------------------------
GET
/

accept-encoding:identity
amz-sdk-invocation-id:159ecffe-dd09-43e5-8f3a-1c3a02e3da5b
amz-sdk-request:attempt=1; max=3
host:storage.googleapis.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20220825T070140Z

accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
---[ STRING TO SIGN ]--------------------------------
AWS4-HMAC-SHA256
20220825T070140Z
20220825/auto/s3/aws4_request
97655a46f48a0bab4d36278d984931d1a4c1bc6fa8cdf77d4f3e70465a62fa6f
-----------------------------------------------------
SDK 2022/08/25 10:01:40 DEBUG Request
GET / HTTP/1.1
Host: storage.googleapis.com
User-Agent: aws-sdk-go-v2/1.16.7 os/macos lang/go/1.18.3 md/GOOS/darwin md/GOARCH/amd64 api/s3/1.27.1
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: 159ecffe-dd09-43e5-8f3a-1c3a02e3da5b
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=GOOGXXXXCM3H4LRVOSWKUFX/20220825/auto/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=4613a0c21bfa65cbe2ca3895943c570dc14ae938d9059acb605bea8efc5aa81f
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220825T070140Z

SDK 2022/08/25 10:01:40 DEBUG Response
HTTP/2.0 403 Forbidden
Content-Length: 859
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0
Content-Type: application/xml; charset=UTF-8
Date: Thu, 25 Aug 2022 07:01:40 GMT
Expires: Thu, 25 Aug 2022 07:01:40 GMT
Server: UploadServer
X-Guploader-Uploadid: ADPycds0ijOgnsfw23HvSlSotY-STzCuGu6pj3GoXj49NNJeUCziHkT4sXz4vIcn_syis54UIon8h-O4KOcaR--G7Eq3lDhmrQmr

ListBuckets: operation error S3: ListBuckets, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
```

Similarly, when I try to use `aws-sdk-go`, it is successful:

```
2022/08/25 10:12:18 DEBUG: Request Signature:
---[ CANONICAL STRING  ]-----------------------------
GET
/

host:storage.googleapis.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20220825T071218Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
---[ STRING TO SIGN ]--------------------------------
AWS4-HMAC-SHA256
20220825T071218Z
20220825/auto/s3/aws4_request
802442955334a38685a8630a467ad8c046e350beb19662a3f4d2fdb8b5120511
-----------------------------------------------------
2022/08/25 10:12:18 DEBUG: Request s3/ListBuckets Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET / HTTP/1.1
Host: storage.googleapis.com
User-Agent: aws-sdk-go/1.40.25 (go1.18.3; darwin; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=GOOGXXXXVCM3H4LRVOSWKUFX/20220825/auto/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d211e86e8a77e5db71fcb99dc62f5c47ff6487a051169bf5fd787084800d8f13
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220825T071218Z
Accept-Encoding: gzip


-----------------------------------------------------
2022/08/25 10:12:18 DEBUG: Response s3/ListBuckets Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 251
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0
Content-Type: application/xml; charset=UTF-8
Date: Thu, 25 Aug 2022 07:12:18 GMT
Expires: Thu, 25 Aug 2022 07:12:18 GMT
Server: UploadServer
X-Guploader-Uploadid: ADPycdsAazh0HYg9mOjQrtoUryuKndpaFtZeRbadNnaiaCccL-7DAshcQzVbFcXqGHG1iLwWMWHmzNY_FK8koXLQBvgxRYe-FfXR


-----------------------------------------------------
Buckets:bbs-test-bucket
```

### Reproduction Steps

 Below there are two gists, identically doing the same thing using `aws-sdk-go` and `aws-sdk-go-v2` respectively. 

[using aws-sdk-go](https://gist.github.com/boraberke/7480a88824d596309ce518a08e2726a9)

[using aws-sdk-go-v2](https://gist.github.com/boraberke/6a2d34d7a1ba0d61dc78684ecb942c9f)

### Possible Solution

Some additional headers such as `amz-sdk-request` and `amz-sdk-invocation-id` are added to `SignedHeaders` in v2. Issue might be related to that, but I don't have a possible solution in mind.

### Additional Information/Context

GCS gives an example usage with `aws-sdk-go` [here](https://cloud.google.com/storage/docs/aws-simple-migration) but there is no example with `aws-sdk-go-v2`.

### AWS Go SDK V2 Module Versions Used

```
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
```
### Compiler and Version used

go version go1.18.3 darwin/amd64

### Operating System and version

macos monterey 12.4

**Comment by RanVaknin** [comment]
Hi @boraberke, 

Thanks for opening the issue. The SDKs don't guarantee compatibility with 3rd party platforms like in your case.
I don't know the exact reason v1 works and v2 doesn't - it could be because of some headers that you pointed out. You could try and remove them by writing your own middleware for the client and see if the signature will match but again this is a speculation.

I wish I could help.
Ran~

**Comment by boraberke** [comment]
Hi @RanVaknin,

I found the issue of the problem. When I remove `accept-encoding` header from signed headers, problem is solved. Instead of 
```
SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
````
I used 
```
SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
```

Do you know the reason why `accept-encoding` is added as one of the `SignedHeaders` in `aws-sdk-go-v2`? It is not used in `aws-sdk-go` either.

**Comment by RanVaknin** [comment]
Hi @boraberke ,

Im not entirely sure. The V2 of the SDK was released to conform to requirements from the AWS service teams.
I know that in the V2 of the SDK the signature is the very last step in the middleware stack and there are no un-signed headers, something that was not guaranteed in V1.

I'm happy you were able to figure it out and make it work! Hope I could be more help in the future.
Ran~

**Comment by szabolcsgelencser** [comment]
> Hi @RanVaknin,
> 
> I found the issue of the problem. When I remove `accept-encoding` header from signed headers, problem is solved. Instead of
> 
> ```
> SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> ```
> 
> I used
> 
> ```
> SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> ```
> 
> Do you know the reason why `accept-encoding` is added as one of the `SignedHeaders` in `aws-sdk-go-v2`? It is not used in `aws-sdk-go`.

Hi @boraberke, could you please share how you excluded the `accept-encoding` header exactly (what is the code for this)?

**Comment by boraberke** [comment]
> > Hi @RanVaknin,
> > I found the issue of the problem. When I remove `accept-encoding` header from signed headers, problem is solved. Instead of
> > ```
> > SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I used
> > ```
> > SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you know the reason why `accept-encoding` is added as one of the `SignedHeaders` in `aws-sdk-go-v2`? It is not used in `aws-sdk-go`.
> 
> Hi @boraberke, could you please share how you excluded the `accept-encoding` header exactly (what is the code for this, can it be done without modifying the lib's codebase itself)?

Hi @szabolcsgelencser,

Unfortunately I couldn't find a way to exclude accept-encoding without changing the source code of the sdk.

**Comment by RanVaknin** [comment]
Hi @boraberke ,@szabolcsgelencser, and anyone else who is also experiencing this:

I don't have experience in GCS, and in order to take a deeper look I need some detailed repro steps. 
If you can help with that I could try and find a workaround (probably implementing custom middleware to remove that header before signing)

Thanks,
Ran~

**Comment by runlilong** [comment]
> > Hi @RanVaknin,
> > I found the issue of the problem. When I remove `accept-encoding` header from signed headers, problem is solved. Instead of
> > ```
> > SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I used
> > ```
> > SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you know the reason why `accept-encoding` is added as one of the `SignedHeaders` in `aws-sdk-go-v2`? It is not used in `aws-sdk-go`.
> 
> Hi @boraberke, could you please share how you excluded the `accept-encoding` header exactly (what is the code for this, can it be done without modifying the lib's codebase itself)?

I found a little hack way to achieve it. the idea is to use `go:linkname` to access the internal variable `v4.IgnoredHeaders` and append a new item `accept-encoding` to it. @szabolcsgelencser  hope it can be helpful.
```
type Rule interface {
	IsValid(value string) bool
}
type Rules []Rule
//go:linkname __ignoredHeaders github.com/aws/aws-sdk-go-v2/aws/signer/internal/v4.IgnoredHeaders
var __ignoredHeaders unsafe.Pointer

// Avoids "go.info.github.com/aws/aws-sdk-go-v2/aws/signer/internal/v4.IgnoredHeaders:
// relocation target go.info.github.com/xxx/xxx/xxx.Rules not defined"
// refer https://github.com/pkujhd/goloader/blob/09f36c84ac85502eb5df4670f1aa7472934ba03a/iface.1.10.go#L31-L36
var ignoredHeaders = (*Rules)(unsafe.Pointer(&__ignoredHeaders))

reflect.ValueOf((*ignoredHeaders)[0]).FieldByName("Rule").Elem().SetMapIndex(
	reflect.ValueOf("Accept-Encoding"), reflect.ValueOf(struct{}{}))
```

**Comment by Slach** [comment]
More safe way, https://stackoverflow.com/a/74382598/1204665, but with more code and could

**Comment by ganigeorgiev** [comment]
I'm not sure whether it will be useful to others or if it is the best way to handle it, but based on the above stackoverflow question, here is my `ignoreSigningHeaders` middleware:

Usage pseudo-code:

```go
client := s3.NewFromConfig(cfg, func(o *s3.Options) {
    // Google Cloud Storage alters the Accept-Encoding header, which breaks the v2 request signature
    // (https://github.com/aws/aws-sdk-go-v2/issues/1816)
    if strings.Contains(endpoint, "storage.googleapis.com") {
        ignoreSigningHeaders(o, []string{"Accept-Encoding"})
    }
})
```

Middleware:

```go
package yourpackage

import (
    "context"
    "fmt"

    v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
    "github.com/aws/aws-sdk-go-v2/service/s3"
    "github.com/aws/smithy-go/middleware"
    smithyhttp "github.com/aws/smithy-go/transport/http"
)

// ignoreSigningHeaders excludes the listed headers
// from the request signature because some providers may alter them.
//
// See https://github.com/aws/aws-sdk-go-v2/issues/1816.
func ignoreSigningHeaders(o *s3.Options, headers []string) {
    o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
        if err := stack.Finalize.Insert(ignoreHeaders(headers), "Signing", middleware.Before); err != nil {
            return err
        }

        if err := stack.Finalize.Insert(restoreIgnored(), "Signing", middleware.After); err != nil {
            return err
        }

        return nil
    })
}

type ignoredHeadersKey struct{}

func ignoreHeaders(headers []string) middleware.FinalizeMiddleware {
    return middleware.FinalizeMiddlewareFunc(
        "IgnoreHeaders",
        func(ctx context.Context, in middleware.FinalizeInput, next middleware.FinalizeHandler) (out middleware.FinalizeOutput, metadata middleware.Metadata, err error) {
            req, ok := in.Request.(*smithyhttp.Request)
            if !ok {
                return out, metadata, &v4.SigningError{Err: fmt.Errorf("(ignoreHeaders) unexpected request middleware type %T", in.Request)}
            }

            ignored := make(map[string]string, len(headers))
            for _, h := range headers {
                ignored[h] = req.Header.Get(h)
                req.Header.Del(h)
            }

            ctx = middleware.WithStackValue(ctx, ignoredHeadersKey{}, ignored)

            return next.HandleFinalize(ctx, in)
        },
    )
}

func restoreIgnored() middleware.FinalizeMiddleware {
    return middleware.FinalizeMiddlewareFunc(
        "RestoreIgnored",
        func(ctx context.Context, in middleware.FinalizeInput, next middleware.FinalizeHandler) (out middleware.FinalizeOutput, metadata middleware.Metadata, err error) {
            req, ok := in.Request.(*smithyhttp.Request)
            if !ok {
                return out, metadata, &v4.SigningError{Err: fmt.Errorf("(restoreIgnored) unexpected request middleware type %T", in.Request)}
            }

            ignored, _ := middleware.GetStackValue(ctx, ignoredHeadersKey{}).(map[string]string)
            for k, v := range ignored {
                req.Header.Set(k, v)
            }

            return next.HandleFinalize(ctx, in)
        },
    )
}
```

**Comment by maxpain** [comment]
It would be much better to expose `IgnoreHeaders` somehow. I don't like hacky middlewares and other ways to fix this issue.

**Comment by maxpain** [comment]
By the way, the official `@aws-sdk/client-s3` npm package for Node.js doesn't have such a problem.

**Comment by ken-kuro** [comment]
> By the way, the official `@aws-sdk/client-s3` npm package for Node.js doesn't have such a problem.

The JS SDK client does **not** forcibly inject headers like the Go SDK does. The [current Go SDK](https://github.com/aws/aws-sdk-go-v2/blob/6a7e8b52e910b0dbd30c6b26a864a39c19e02294/service/internal/accept-encoding/accept_encoding_gzip.go#L65) always adds an `accept-encoding: identity` header to all requests, and also [injects AWS-internal headers](https://github.com/aws/aws-sdk-go-v2/blob/6a7e8b52e910b0dbd30c6b26a864a39c19e02294/aws/middleware/middleware.go#L26) such as `amz-sdk-invocation-id`. Since SigV4 signs every header present on the request, these extra headers are always included in the signature.

In contrast, with the JS SDK, the Node.js HTTP handler does **not** add `accept-encoding` unless the developer explicitly sets it, and the [browser handler](https://github.com/aws/aws-sdk-js-v3/blob/3bdc582de60b89982293391c8acf066e7b693489/packages/xhr-http-handler/src/xhr-http-handler.ts#L303) explicitly blocks it. Internal headers like `amz-sdk-invocation-id` or `amz-sdk-request` are only added for AWS endpoints, and are even explicitly deleted for signed URLs. As a result, since these extra headers are not present in the request, they are not signed.

Do you think we should reopen this issue to restore cross-sdk consistency for s3-compatible interoperability or not @maxpain ?

**Comment by Maousuki** [comment]
> I'm not sure whether it will be useful to others or if it is the best way to handle it, but based on the above stackoverflow question, here is my `ignoreSigningHeaders` middleware:
> 
> Usage pseudo-code:
> 
> client := s3.NewFromConfig(cfg, func(o *s3.Options) {
>     // Google Cloud Storage alters the Accept-Encoding header, which breaks the v2 request signature
>     // (https://github.com/aws/aws-sdk-go-v2/issues/1816)
>     if strings.Contains(endpoint, "storage.googleapis.com") {
>         ignoreSigningHeaders(o, []string{"Accept-Encoding"})
>     }
> })
> Middleware:
> 
> package yourpackage
> 
> import (
>     "context"
>     "fmt"
> 
>     v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
>     "github.com/aws/aws-sdk-go-v2/service/s3"
>     "github.com/aws/smithy-go/middleware"
>     smithyhttp "github.com/aws/smithy-go/transport/http"
> )
> 
> // ignoreSigningHeaders excludes the listed headers
> // from the request signature because some providers may alter them.
> //
> // See https://github.com/aws/aws-sdk-go-v2/issues/1816.
> func ignoreSigningHeaders(o *s3.Options, headers []string) {
>     o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
>         if err := stack.Finalize.Insert(ignoreHeaders(headers), "Signing", middleware.Before); err != nil {
>             return err
>         }
> 
>         if err := stack.Finalize.Insert(restoreIgnored(), "Signing", middleware.After); err != nil {
>             return err
>         }
> 
>         return nil
>     })
> }
> 
> type ignoredHeadersKey struct{}
> 
> func ignoreHeaders(headers []string) middleware.FinalizeMiddleware {
>     return middleware.FinalizeMiddlewareFunc(
>         "IgnoreHeaders",
>         func(ctx context.Context, in middleware.FinalizeInput, next middleware.FinalizeHandler) (out middleware.FinalizeOutput, metadata middleware.Metadata, err error) {
>             req, ok := in.Request.(*smithyhttp.Request)
>             if !ok {
>                 return out, metadata, &v4.SigningError{Err: fmt.Errorf("(ignoreHeaders) unexpected request middleware type %T", in.Request)}
>             }
> 
>             ignored := make(map[string]string, len(headers))
>             for _, h := range headers {
>                 ignored[h] = req.Header.Get(h)
>                 req.Header.Del(h)
>             }
> 
>             ctx = middleware.WithStackValue(ctx, ignoredHeadersKey{}, ignored)
> 
>             return next.HandleFinalize(ctx, in)
>         },
>     )
> }
> 
> func restoreIgnored() middleware.FinalizeMiddleware {
>     return middleware.FinalizeMiddlewareFunc(
>         "RestoreIgnored",
>         func(ctx context.Context, in middleware.FinalizeInput, next middleware.FinalizeHandler) (out middleware.FinalizeOutput, metadata middleware.Metadata, err error) {
>             req, ok := in.Request.(*smithyhttp.Request)
>             if !ok {
>                 return out, metadata, &v4.SigningError{Err: fmt.Errorf("(restoreIgnored) unexpected request middleware type %T", in.Request)}
>             }
> 
>             ignored, _ := middleware.GetStackValue(ctx, ignoredHeadersKey{}).(map[string]string)
>             for k, v := range ignored {
>                 req.Header.Set(k, v)
>             }
> 
>             return next.HandleFinalize(ctx, in)
>         },
>     )
> }

thank you so much, help me a lot

**Comment by NikosTsiligaridis** [comment]
Old problem but still relevant. For those googling it, two things for a simple workaround:
1. Remove `Accept-Encoding` header , looks like GCS fiddles with this header which invalidates the signature (which was included at the time of signing). Thus needs to be removed before signing.
2. Set checksum to be calculated only when required (via cfg but can be set via env)

```go
// wrap http signer to intercept header right before signing
type gcsHttpSigner struct {
	wrapped s3.HTTPSignerV4
}

func (s *gcsHttpSigner) SignHTTP(ctx context.Context, credentials aws.Credentials, req *http.Request, payloadHash string, service string, region string, signingTime time.Time, optFns ...func(*v4.SignerOptions)) error {
	req.Header.Del("Accept-Encoding")
	return s.wrapped.SignHTTP(ctx, credentials, req, payloadHash, service, region, signingTime, optFns...)
}
...

// Use when configuring client
s3Client := s3.NewFromConfig(cfg, func(o *s3.Options) {
	o.BaseEndpoint = aws.String("https://storage.googleapis.com")
	o.UsePathStyle = true
	o.HTTPSignerV4 = &gcsHttpSigner{wrapped: o.HTTPSignerV4}
	 // Avoid checksums or everything breaks
	// can also export env AWS_REQUEST_CHECKSUM_CALCULATION=when_required
	cfg.RequestChecksumCalculation = aws.RequestChecksumCalculationWhenRequired
})

```
