### ISSUE TITLE
Some errors always return StatusCode 200.

### ISSUE THREAD

**Issue by satorunooshie** [aws/aws-sdk-go-v2#1827]
### Describe the bug

Some specific errors always return status code 200.
```
operation error DynamoDB: Query, $tableName: https response error StatusCode: 200, RequestID: 123456, deserialization failed, failed to decode response body, read tcp $src->$dst: use of closed network connection
```

### Expected Behavior

should be 500

### Current Behavior

```
operation error DynamoDB: Query, $tableName: https response error StatusCode: 200, RequestID: 123456, deserialization failed, failed to decode response body, read tcp $src->$dst: use of closed network connection
```
Before reading body, StatusCode has been decided.
ref: https://github.com/aws/smithy-go/blob/main/transport/http/client.go#L55
https://github.com/aws/smithy-go/blob/main/middleware/step_deserialize.go#L192
https://github.com/aws/aws-sdk-go-v2/blob/main/service/dynamodb/deserializers.go#L4326

### Reproduction Steps

```go
	ddb := dynamodb.NewFromConfig(defaultCfg)
	result, err := ddb.Query(
		ctx,
		&dynamodb.QueryInput{
			TableName:                 aws.String(tableName),
			ExpressionAttributeNames:  expr.Names(),
			ExpressionAttributeValues: expr.Values(),
			KeyConditionExpression:    expr.KeyCondition(),
		},
	)
```

### AWS Go SDK V2 Module Versions Used

```
	github.com/aws/aws-sdk-go-v2 v1.16.8
	github.com/aws/aws-sdk-go-v2/config v1.15.15
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.9.8
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.4.14
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.15.10
	github.com/aws/smithy-go v1.12.0
```

### Compiler and Version used

1.19

### Operating System and version

Linux

**Comment by RanVaknin** [comment]
Hi @satorunooshie I see you opened a similar issue so Im going to reconcile them into the other one you opened and close this one.
