### ISSUE TITLE
Enable Share Dashboard for PutDashboard.

### ISSUE THREAD

**Issue by riita10069** [aws/aws-sdk-go-v2#1828]
### Describe the feature

I am looking to build an event driven CloudWatch Dashboard when an instance is launched.
I am trying to enrich the CloudWatch Dashboard by executing the following code by events received from Config.

However, the Dashboard is not Share and cannot communicate metrics to anyone without AWS privileges; we need to manually enable the Share Dashboard in order for it to function as a Dashboard.

Therefore, I want to enable Share Dashboard when I do PutDashboard.

If there is a way to do so, I would like to know.

```go
package main

import (
	"context"
	"log"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := cloudwatch.NewFromConfig(cfg)

	dashboardName := "dashboard-test-1"
	dashboardInput := cloudwatch.PutDashboardInput{
		DashboardBody: &dashboardBody,
		DashboardName: &dashboardName,
	}
	_, err = client.PutDashboard(context.Background(), &dashboardInput)
	if err != nil {
		log.Fatalf("failed to put dashboard, %v", err)
	}
}
```

### Use Case

I want to use CloudWatch Dashboard as our internal metrics portal (like Grafana).
I want to see metrics for each and every one of the large number of EC2 instances launched by auto-scaling-group.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2@v1.16.12 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2@v1.16.12 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.16.12 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/aws-sdk-go-v2/credentials@v1.12.16
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.13
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.20
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.19
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.1
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.15
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/config@v1.17.3 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/credentials@v1.12.16 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/credentials@v1.12.16 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.13
github.com/aws/aws-sdk-go-v2/credentials@v1.12.16 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.19
github.com/aws/aws-sdk-go-v2/credentials@v1.12.16 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.1
github.com/aws/aws-sdk-go-v2/credentials@v1.12.16 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.15
github.com/aws/aws-sdk-go-v2/credentials@v1.12.16 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/credentials@v1.12.16 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.13 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.13 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.13 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.19 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.20 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/cloudwatch@v1.21.2 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/cloudwatch@v1.21.2 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.19
github.com/aws/aws-sdk-go-v2/service/cloudwatch@v1.21.2 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13
github.com/aws/aws-sdk-go-v2/service/cloudwatch@v1.21.2 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/service/cloudwatch@v1.21.2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.13 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.13 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.13 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.19 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.19 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.19
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.19 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.19 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.1 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.1 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.19
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.1 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.1 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.15 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.15 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.19
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.15 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.15 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.13
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.15 github.com/aws/smithy-go@v1.13.0

### Go version used

1.19.0

**Comment by RanVaknin** [comment]
Hi @riita10069 ,

Thank you for opening this feature request.

Unfortunately what you are asking needs to exist on the Cloudwatch API before it can be available on the SDK. Since the SDKs are auto-generated from the API models of the various services, we can only change things that are SDK specific.

I have seen that the someone had already requested that from the Grafana team on their github: [link](https://github.com/aws/amazon-managed-grafana-roadmap/issues/4)
It seems like its on their roadmap. Once their API model changes, they will hopefully create an internal release so that the SDKs can get updated with this feature.

I have commented there on your behalf, maybe it will help move things forward. 

For now I'm going to close this issue because there is no action item for us, but please feel free to open any issues / feature requests in the future. They help us better the SDK and build our communnity.

All the best,
Ran~
