### ISSUE TITLE
Tags are not received as part of eks@v1.21.10#Client.DescribeCluster

### ISSUE THREAD

**Issue by ashutosrath** [aws/aws-sdk-go-v2#1829]
### Describe the bug

We are using the eks service of this SDK to fetch tags and the details of the EKS cluster. Suddenly we noticed that the SDK stopped providing the Tags associated with the EKS cluster. I further debugged this issue.

<img width="1283" alt="Screen Shot 2022-09-01 at 10 47 51 PM" src="https://user-images.githubusercontent.com/5246615/188055272-769d6838-9c49-44a8-bd97-c53aacc62c63.png">

It seems this is not coming from the server when SDK calls the REST API https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeCluster.html . However, I am receiving the tags if I use aws cli like `aws eks describe-cluster --name <eks-cluster-name> --region us-east-1`, So there is no permission issue as all other information is received. 

Is this an issue on the server side or the client side aws-sdk-go-v2 as it was working fine a few days ago and we recently discovered this in our production server?

### Expected Behavior

eks@v1.21.10#Client.DescribeCluster should provide Tags along with other cluster information

### Current Behavior

Tags are not received as part of eks@v1.21.10#Client.DescribeCluster

### Reproduction Steps

```go
clusterDescOut, err := eks.DescribeCluster(ctx, &eks.DescribeClusterInput{
		Name: aws.String(clusterName),
	})
	if err != nil {
		return ClusterDescription{}, err
	}
	if len(clusterDescOut.Cluster.Tags){
          fmt.println("Tags Received")
	}else{
          fmt.println("Tags Not Received")
        }
```

### Possible Solution

It needs to be checked why the server stopped providing this information to aws-sdk-go-v2 SDK-based user-agent as it works fine with aws cli

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2 v1.16.13
	github.com/aws/aws-sdk-go-v2/config v1.17.4
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.54.3
	github.com/aws/aws-sdk-go-v2/service/eks v1.21.10
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.16
	github.com/aws/smithy-go v1.13.1

### Compiler and Version used

go version go1.18.3 darwin/amd64

### Operating System and version

Mac OS 12.5.1 (21G83)

**Comment by ashutosrath** [comment]
Also I tried with https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks@v1.21.10#Client.ListTagsForResource , This also comes with nil Tag and nil err

**Comment by RanVaknin** [comment]
Hi @ashutosrath

Unfortunately I'm not able to reproduce your experience. I'm able to get tags with the code example you provided.

Here is my working code:

```go
import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/eks"
	"log"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.Background(), config.WithRegion("us-east-1"))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	eksClient := eks.NewFromConfig(cfg)

	clusterDescOut, err := eksClient.DescribeCluster(context.Background(), &eks.DescribeClusterInput{
		Name: aws.String(clusterName),
	})
	if err != nil {
		fmt.Errorf("error: %v", err)
	}

	if len(clusterDescOut.Cluster.Tags) > 0 {
		fmt.Println("Tags Received")
		for i, v := range clusterDescOut.Cluster.Tags {
			fmt.Printf("%s, %s\n", i, v)
		}
	}
}

```
Response:
```
Tags Received
foo, baz
dwight, schrute
scooby, doo
```

Are you sure you have set tags for the cluster you are running your code against?
Just to be sure I would enable logging to see the raw http response like so:
```go
cfg, err := config.LoadDefaultConfig(context.Background(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogResponseWithBody))
```

Please share the response you are seeing as that might help us point out the issue.

Thanks!
Ran~

**Comment by ashutosrath** [comment]
This issue was an intermittent issue from the AWS server. @RanVaknin, thanks for checking it.
