### ISSUE TITLE
GetChange broken in github.com/aws/aws-sdk-go-v2/service/route53 v1.21.11

### ISSUE THREAD

**Issue by mastermanu** [aws/aws-sdk-go-v2#1838]
### Describe the bug

1)  a.route53Client.ChangeResourceRecordSets returns a change ID with the "/change/" prefix.
2) Pass the changeID as received to a.route53Client.GetChange()
3) Get the following error:
```
operation error Route 53: GetChange, https response error StatusCode: 404, RequestID: e79ad9fd-e288-44ff-bfa3-47f6b7b968fc, NoSuchChange: Could not find resource with ID: /change/C003789825HUY95U5CD79"
```

Change ID does exist:
```
aws --profile test-dns route53 get-change --id /change/C003789825HUY95U5CD79
{
    "ChangeInfo": {
        "Id": "/change/C003789825HUY95U5CD79",
        "Status": "INSYNC",
        "SubmittedAt": "2022-09-09T19:00:56.449000+00:00"
    }
}
```

### Expected Behavior

This worked in 1.20.4. It broke in 1.21.11

### Current Behavior

See bug description. User has to workaround this by manually trimming "/change/" prefix on changeID before passing it to GetChange(), which is not ideal.

### Reproduction Steps

See bug description. Looks very similar to something reported on the rust SDK: https://github.com/awslabs/aws-sdk-rust/issues/554. Something clearly regressed.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go v1.44.94
	github.com/aws/aws-sdk-go-v2 v1.16.14
	github.com/aws/aws-sdk-go-v2/config v1.17.5
	github.com/aws/aws-sdk-go-v2/credentials v1.12.18
	github.com/aws/aws-sdk-go-v2/service/autoscaling v1.23.14
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.54.4
	github.com/aws/aws-sdk-go-v2/service/ecr v1.17.16
	github.com/aws/aws-sdk-go-v2/service/eks v1.21.11
	github.com/aws/aws-sdk-go-v2/service/route53 v1.21.11
	github.com/aws/aws-sdk-go-v2/service/s3 v1.27.9
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.17

### Compiler and Version used

go 1.18

### Operating System and version

Ubuntu AMD64

**Comment by RanVaknin** [comment]
Issue confirmed. I've added an action item for us to try and cleanup the path. 

Thank you!
Ran~
