### ISSUE TITLE
aws.Config with nil Credentials does not pick up AWS_ACCESS_KEY_ID

### ISSUE THREAD

**Issue by bep** [aws/aws-sdk-go-v2#1840]
### Describe the bug

I'm doing an upgrade from v1 to v2 in a library here https://github.com/bep/s3deploy/pull/296 (in progress).

Testing it, I have AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN set via [aws-vault](https://github.com/99designs/aws-vault).

My config code looks like this:

```go
func newAWSConfig(cfg Config) (aws.Config, error) {
	creds, err := createCredentials(cfg)
	if err != nil {
		return aws.Config{}, err
	}

	return aws.Config{
		Region:      cfg.RegionName,
		Credentials: creds,
	}, nil
}

func createCredentials(cfg Config) (aws.CredentialsProvider, error) {
	accessKey, secretKey := cfg.AccessKey, cfg.SecretKey

	if accessKey != "" && secretKey != "" {
		return credentials.NewStaticCredentialsProvider(accessKey, secretKey, os.Getenv("AWS_SESSION_TOKEN")), nil
	}

	if accessKey != "" || secretKey != "" {
		// provided one but not both
		return nil, errors.New("AWS key and secret are required")
	}

	// This seem to be a bug in https://github.com/aws/aws-sdk-go-v2
	// It should be possible to use the default credentials provider chain.
	if os.Getenv("AWS_ACCESS_KEY_ID") != "" {
		return credentials.NewStaticCredentialsProvider(os.Getenv("AWS_ACCESS_KEY_ID"), os.Getenv("AWS_SECRET_ACCESS_KEY"), os.Getenv("AWS_SESSION_TOKEN")), nil
	}

	// Use AWS default
	return nil, nil
}

```

The above works, but if I comment out `return credentials.NewStaticCredentialsProvider(os.Getenv("AWS_ACCESS_KEY_ID"), os.Getenv("AWS_SECRET_ACCESS_KEY"), os.Getenv("AWS_SESSION_TOKEN")), nil`, it fails:

```bash
error: operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: DTQPWDCPSV9FM0Y2, HostID: OrQ592KUUU8yHOzqUe7ntilr8lHTWYq50Xqms2MXAdTWXtBj2YiMSiLaIrIu96LjUhDlJR34u7g=, api error AccessDenied: Access Denied
```

### Expected Behavior

I expect a nil `Credentials´ to fall back to using AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN  from environment.

### Current Behavior

See above.

### Reproduction Steps

See above.

### AWS Go SDK V2 Module Versions Used

```
github.com/bep/s3deploy/v2 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/bep/s3deploy/v2 github.com/aws/aws-sdk-go-v2/credentials@v1.12.18
github.com/bep/s3deploy/v2 github.com/aws/aws-sdk-go-v2/service/cloudfront@v1.20.3
github.com/bep/s3deploy/v2 github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9
```

### Compiler and Version used

go version go1.19 darwin/arm64

### Operating System and version

Darwin bep-mac14.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

**Comment by RanVaknin** [comment]
Hi @bep ,

You are not calling the default config method here. Please check out the [v2 getting started guide](https://aws.github.io/aws-sdk-go-v2/docs/getting-started/#invoke-an-operation) or the [migration guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/)

```go
cfg, err := config.LoadDefaultConfig(context.TODO())
if err != nil {
	log.Fatal(err)
}
```

If you used v1 it looked like that:
```go
sess, err := session.NewSession()
if err != nil {
	// handle error
}
```

Let me know if you need anything else. 
Ty
Ran~

**Comment by bep** [comment]
OK, I didn't get/understand this. I did read the Go Doc on the `Config`, though:

```go
	// The credentials object to use when signing requests. Defaults to a
	// chain of credential providers to search for credentials in environment
	// variables, shared credential file, and EC2 Instance Roles.
	Credentials CredentialsProvider
```

But I guess "Defaults to a ..." doesn't mean "if not set ...". I'll keep this open so you can consider making the docs on this a little more clear.

**Comment by jasdel** [comment]
Thanks for pointing out the confusing doc. This should be updated clarifying the default behavior is performed by `config.LoadDefaultConfig`, not the `Config` type directly.

**Comment by RanVaknin** [comment]
@bep ,

Change is now pending a merge. Please follow the PR and pull the latest version when merged. 

Thank you for engaging in the community
All the best
Ran~
