### ISSUE TITLE
Client Side Throttling (Bucket Size and cost)

### ISSUE THREAD

**Issue by yevgenypats** [aws/aws-sdk-go-v2#1854]
### Describe the issue

It is not clear from the documentation when https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/ when to use different bucket size or bucket cost.

Also, it would be helpful to document in general why the client size rate-limiting exist at all (my guess is to detect outages?)

If my assumption is correct then what would be the right way to make full use of the client side rate limiting is it on a per service per region basis (where outages occur) ?

Is this functionality deprecated at all and we just need to have a no-rate limiter on client side ?

Help would be appreciated.

Context - we are using this in:
- https://github.com/cloudquery/cloudquery
- https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws

### Links

https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/

**Comment by RanVaknin** [comment]
Hi @yevgenypats ,

The purpose of request rate limiting is not detect outages, but rather avoid sending unnecessary requests that will likely fail.

This feature is for more advanced fine grained control, and its values are pre-populated by default in the SDK (its not deprecated).
The idea is that it should work "out of the box" without any need to explicitly interact with it.
You can read more about it [here](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/retry#Standard).

Thanks,
Ran~
