### ISSUE TITLE
Client reuse in documentation

### ISSUE THREAD

**Issue by emanuelef** [aws/aws-sdk-go-v2#1857]
### Describe the issue

Hi,
I'm looking for some documentation about the Client reuse.
On the v1 in the Docs I can read:
"Sessions should be cached when possible, because creating a new Session will load all configuration values from the environment, and config files each time the Session is created."

What's the approach with the Client in v2 ? I can see that if I cache it then subsequent calls to ExecuteStatement take less time but I'm wondering if it's possible that the Client can get stale and how to detect that.

Let's say that I have a µservice interacting with DynamoDB, what if I cache the client when starting up with:
dynamoClient_instance = dynamodb.NewFromConfig(cfg)

and then using:
dynamoClient_instance.ExecuteStatement

Would it be possible that dynamoClient_instance becomes stale ? In case is there a way to check it before running ExecuteStatement ?

Thanks for any help.

### Links

https://aws.github.io/aws-sdk-go-v2/docs/getting-started/

**Comment by RanVaknin** [comment]
Hi @emanuelef ,

I saw that you opened a discussion about this so Im closing this issue in favor of answering you in that discussion thread.

Thanks,
Ran
