### ISSUE TITLE
Port v1 SDK's CSM support

### ISSUE THREAD

**Issue by xibz** [aws/aws-sdk-go-v2#186]
Port the v1 SDK's client side metric (CSM) client support for reporting metrics.

* [aws/csm](https://github.com/aws/aws-sdk-go/tree/master/aws/csm)
* aws/aws-sdk-go#2677 
* aws/aws-sdk-go#2678

**Comment by skmcgrail** [comment]
Required changes:
https://github.com/aws/aws-sdk-go/pull/2768
https://github.com/aws/aws-sdk-go/pull/2785
