### ISSUE TITLE
Clarify the purpose of v2

### ISSUE THREAD

**Issue by errordeveloper** [aws/aws-sdk-go-v2#187]
It's not very clear from the README what's the technical purpose of this new version of the SDK and how does it compare to the previous version. There is a mention that Github will be used for project management, but a technical outline is currently missing.

**Comment by kaihendry** [comment]
I made a video about v2 https://engineers.sg/video/aws-sdk-for-go-gophers-meetup--2254
https://youtu.be/B0TMLDttLBE?t=529

**Comment by shawnsmithdev** [comment]
We may want to put a TLDR paragraph on why v2 is happening and, once released, why one might want to port existing code to it in the README.

**Comment by jasdel** [comment]
Thanks for the feedback. We'll look at adding more information to the SDK's README about what changed in V2, and why it exists.

In the meantime we have a blogpost which talks about these changes, and the reasons for updating the SDK, https://aws.amazon.com/blogs/developer/aws-sdk-for-go-2-0-developer-preview/
