### ISSUE TITLE
S3 s3.PutObjectInput generates wrong access point hostname

### ISSUE THREAD

**Issue by chilarai** [aws/aws-sdk-go-v2#1872]
### Describe the bug

I have used the following code to try and upload an object to S3. However, the code generates a wrong access point hostname which in turn is throwing an error

**Error**
```sh
500 Something went wrong uploading the file operation error S3: PutObject, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Put "https://<BUCKET_NAME>.s3.<BUCKET_NAME>.amazonaws.com/1517525715793.jfif?x-id=PutObject": dial tcp: lookup <BUCKET_NAME>.s3.<BUCKET_NAME>.amazonaws.com on 172.23.80.1:53: no such host
```

**Used Code**
```sh
uploader := manager.NewUploader(awsS3Client)
	_, err = uploader.Upload(context.TODO(), &s3.PutObjectInput{
		Bucket: aws.String(AWS_S3_BUCKET),
		Key:    aws.String(filename),
		Body:   file,
	})
```

### Expected Behavior

As per the documentation, the generated access point hostname should have been 
`<BUCKET_NAME>.s3.<REGION_CODE>.amazonaws.com`

### Current Behavior

But, it generates the URL in the following format which throws the error
`<BUCKET_NAME>.s3.<BUCKET_NAME>.amazonaws.com`

### Reproduction Steps

1. Created a bucket in AWS ap-south-1 with default settings
2. Tried to connect to the bucket which is successful
3. Tried to upload a doc with the code above and it results in failure

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/aws
github.com/aws/aws-sdk-go-v2/config
github.com/aws/aws-sdk-go-v2/credentials
github.com/aws/aws-sdk-go-v2/feature/s3/manager
github.com/aws/aws-sdk-go-v2/service/s3

### Compiler and Version used

go1.19.1

### Operating System and version

linux/amd64

**Comment by RanVaknin** [comment]
Hi @chilarai ,

That is indeed interesting. I'm not sure why you are running into it since this is not a known issue.
I attempted to do the same and it worked fine. Here is a code snippet:

```go
func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogRequestWithBody))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := s3.NewFromConfig(cfg)

	file, err := os.Open("<path to your file>")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	uploader := manager.NewUploader(client)
	_, err = uploader.Upload(context.TODO(), &s3.PutObjectInput{
		Bucket: aws.String("testbucket-3650"),
		Key:    aws.String("myKey"),
		Body:   file,
	})

	if err != nil {
		panic(err)
	}
}
```

Log Output:
```console
SDK 2022/10/06 11:22:08 DEBUG Request
PUT /UCSMRH?x-id=PutObject HTTP/1.1

Host: testbucket-3650.s3.us-east-1.amazonaws.com

User-Agent: aws-sdk-go-v2/<redacted>
Content-Length: 8
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: <redacted>
Amz-Sdk-Request: attempt=1; max=3
Authorization: <redacted>, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=<redacted>
Content-Type: application/octet-stream
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20221006T182208Z
```

How are you setting up your config?

Thanks,
Ran~

**Comment by chilarai** [comment]
Hmm, this is the config that I used

```
func configS3() {

	creds := credentials.NewStaticCredentialsProvider( your_access_key, your_secret_key, "")

	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithCredentialsProvider(creds), config.WithRegion(AWS_S3_BUCKET))
	if err != nil {
		log.Printf("error: %v", err)
		return
	}

	awsS3Client = s3.NewFromConfig(cfg)
}
```

**Comment by RanVaknin** [comment]
Hi @chilarai ,

The problem is here:

```go
   config.WithRegion(AWS_S3_BUCKET))
```
You are passing the bucket instead of the region.

Please let me know if you need anything else.
Thanks,
Ran~

**Comment by chilarai** [comment]
Ahh!! My bad
Thanks @RanVaknin
