### ISSUE TITLE
Typos `Checkout out` in README.md

### ISSUE THREAD

**Issue by bishal7679** [aws/aws-sdk-go-v2#1873]
### Describe the issue

In README.md file it should be `Check out the release notes for information` instead of `Checkout out the release notes for information`

![Screenshot (596)](https://user-images.githubusercontent.com/70086051/194365631-f7a85220-0d6d-43e2-adcb-2af267de2894.png)

### Links

https://github.com/aws/aws-sdk-go-v2/blob/main/README.md

**Comment by skmcgrail** [comment]
Merged the corresponding pull request, thanks for the contribution.
