### ISSUE TITLE
Adding `same`  in a sentence

### ISSUE THREAD

**Issue by bishal7679** [aws/aws-sdk-go-v2#1875]
#### It would be better if we write this 

`and see if others are also experiencing the same issue before opening a new issue.` 

#### instead of 

`and see if others are also experiencing the issue before opening a new issue.`

#### Screenshot

![Screenshot (597)](https://user-images.githubusercontent.com/70086051/194369813-632d7255-0eb4-48cd-bdfb-ec777ff47a36.png)

### Links

https://github.com/aws/aws-sdk-go-v2/blob/main/README.md

**Comment by skmcgrail** [comment]
Merged the corresponding pull request, thanks for the contribution.
