### ISSUE TITLE
Typos `a Amazon S3 client` should be corrected

### ISSUE THREAD

**Issue by bishal7679** [aws/aws-sdk-go-v2#1877]
### Describe the issue

`a Amazon S3 client` shoul be changed to `an Amazon S3 client`

### Screenshot

![Screenshot (598)](https://user-images.githubusercontent.com/70086051/194386289-abbb60dc-618e-4aab-a47c-f87ba455fd24.png)

### Links

https://github.com/aws/aws-sdk-go-v2/edit/documentation/content/en/docs/making-requests.md

**Comment by RanVaknin** [comment]
Hi,
Thanks for pointing this out. It's fixed.
https://github.com/aws/aws-sdk-go-v2/pull/1879

All the best,
Ran~
