### ISSUE TITLE
HeadObject leaks file descriptors

### ISSUE THREAD

**Issue by jeffeisen** [aws/aws-sdk-go-v2#1880]
### Describe the bug

Running s3.HeadObject several thousand times on different objects just to check existence of various objects in a bucket -- all the objects I am checking do exist

Doing it in 10 parallel goroutines to speed things up.

After a few seconds, almost always get the error something like  dial tcp: lookup <hostname>  no such host. 
Sometimes the error has appended to the end that it is out of file handles.

If I run "lsof -p <pid>" on the process before it fails there are hundreds of open file descriptors to the S3 host.

It appears that this is essentially leaving open the Body even though HeadObject doesn't return a body to be closed.  As a workaround, If I call GetObject and do a rest.Body.Close() on each call  instead of HeadObject, it works fine.

Note that If I run HeadObject in a single goroutine (main thread), it doesn't fail, but still leaks file descriptors as can be seen with lsof.  It just seems to run slowly enough in that case that it seems to expire/close file descriptors fast enough to keep from running out of them (I'll see maybe 250 file descriptors to S3 open rather than close to a thousand).

### Expected Behavior

I expected my loop to run to completion without errors

### Current Behavior

After a few seconds, almost always get the error something like  dial tcp: lookup <hostname>  no such host. 
Sometimes the error has appended to the end that it is out of file handles.

### Reproduction Steps

Run the following for thousands of times iterating over the objects in a s3 bucket

	  appCreds := aws.NewCredentialsCache(
		credentials.NewStaticCredentialsProvider(s3SecretAccessKeyID, s3SecretAccessKey, ""))

	 client := s3.New(s3.Options{
		Region:      s3Region,
		Credentials: appCreds,
	 })		

         input := &s3.HeadObjectInput{
			Bucket: aws.String(s3BucketID),
			Key:    aws.String(path),
		}

        _, err := client.HeadObject(context.TODO(), input)

       if err != nil {
         log-the-error
      }

While it is running, go to a shell and do "lsof -p <pid>" of the running process to see tons of open file descriptors.  OR, possible that you will eventually get a out of file descriptor error returned (happens to me when I run multi-threaded but not in a single thread)

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.16.16
github.com/aws/aws-sdk-go-v2/config v1.17.8
github.com/aws/aws-sdk-go-v2/credentials v1.12.21
github.com/aws/aws-sdk-go-v2/service/s3 v1.27.9
github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.16.2

### Compiler and Version used

 go1.17.3 linux/amd64

### Operating System and version

Ubuntu 20.04.5 LTS

**Comment by jeffeisen** [comment]
Note.  Just noticed that GetObject when the object does not exist (so GetObject returns err) seems to have same problem.  There's no Body to Close() and it seems to accumulate 80 or so open TCP connections to S3 if I repeatedly call GetObject

**Comment by skmcgrail** [comment]
Go's standard library maintains a pool of HTTP connections to a host that will remain alive so that subsequent API calls to the service can avoid having to establish a new TCP connection and TLS session with the S3 host. You can configure the SDK client with a custom HTTP client with a custom keep alive configuration. See a similar issue and response [here](https://github.com/aws/aws-sdk-go-v2/issues/1434#issuecomment-987225533).

**Comment by jeffeisen** [comment]
@skmcgrail -- thanks for the response.   

I will try out with setting keep alive to false as described in the linked issue.  But, this leaves me confused. Does the AWS library ever reuse sessions or always just create new ones?  If the latter, then why doesn't it automatically set keep-alive to false for me because keep-alive isn't doing me any good and is causing harm.

When I do lsof, I see lots of open file descriptors to the same server, just different ports.  I don't get the benefit of that if I can't reuse them.

Thanks.

**Comment by yuseferi** [comment]
Interesting question, 
@skmcgrail , I read all those related threads and sounds like you encourage to disable HTTP keep-alive to prevent  HTTP goroutine pool leak? 
what could be the drawback of disabling this?
more HTTPS connection establishing and handshaking?
in terms of performance, does it worth it?

**Comment by lucix-aws** [comment]
I'm inclined to close this as out-of-scope for the Go SDK. The behavior we're observing here is entirely within the HTTP client, which is external to us.
