### ISSUE TITLE
MediaConvert validation regression on __stringPatternS3

### ISSUE THREAD

**Issue by 0xpablo** [aws/aws-sdk-go-v2#1887]
### Describe the bug

MediaConvert_Shapes has introduced a regression when validating S3 destinations.
The `__stringPatternS3 ` validation pattern looks like this: ^s3:\\/\\/$ when it would previously look like this: ^s3:\\/\\/.

This means that only destinations that match "s3://" work, which is unexpected as destinations like this one "s3://bucket/folder/file" should be allowed.

Here's the line with the `__stringPatternS3` pattern:
https://vscode.dev/github.com/aws/aws-sdk-go-v2/blob/3e94e4194d12a3ecd967552f9824ad4b0c462488/codegen/sdk-codegen/aws-models/mediaconvert.json#L24622

### Expected Behavior

The `__stringPatternS3` should be `^s3:\\/\\/` instead of `^s3:\\/\\/$` to allow destinations like "s3://bucket/folder/file".

### Current Behavior

The validation does not allow any other destination than `s3://` which is unexpected.

### Reproduction Steps

N/A

### Additional Information/Context

The official JS SDK seems to have the right pattern: https://github.com/aws/aws-sdk-js/blob/bfb3aaf792c8e50962004a72f090f4fb067d2c27/apis/mediaconvert-2017-08-29.normal.json#L13314

This is affecting Swift's Soto SDK. I opened the original issue here: https://github.com/soto-project/soto/issues/624

### AWS Go SDK V2 Module Versions Used

N/A

### Compiler and Version used

v1.44.116

### Operating System and version

N/A

**Comment by skmcgrail** [comment]
The Go SDK does not have client side validation of input values using regular expressions from the model. If you have encountered a specific SDK that is performing such validation please open a ticket with that respective repository.

**Comment by adam-fowler** [comment]
@skmcgrail I guess the issue here isn't the SDKs though. The problem is with the Smithy AST model which includes the wrong validation pattern. Understandably there is no way to pass these issues on to the service teams, outside of AWS, so the only way to do it is via one of the open source SDKs.

Out of interest do any of the official SDKs do client side validation? I found issue #1 on the aws-sdk-go repo is add client side validation 🤣
