### ISSUE TITLE
S3 CopyObject errors when called inside for loop

### ISSUE THREAD

**Issue by Tahmeed27** [aws/aws-sdk-go-v2#1895]
### Describe the bug

Hey I need to copy the contents of one s3 bucket to another (i.e. mimic the aws cli sync command). I was doing this by first calling ListObjectsV2 and then iterating through the contents and calling CopyObject. I'm also currently testing using local stack locally and when I check the s3 bucket after calling this, the first two files are correctly copied but the other files are not.

### Expected Behavior

All objects copied without error

### Current Behavior

The first two elements of the list are copied exactly as expected but then the elements after that all fail the CopyObject operation with the given error:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/51849738/197882745-79f0f0c6-2593-44df-9687-47e0e3f5fcc0.png">

### Reproduction Steps

Populate s3 bucket with list of files.
resp, _ := ListObjectsV2
```
for _, item := range resp.Contents {
	if err = s3Client.CopyObject(ctx, destinationBucket, *item.Key); err != nil {
            log.Error(err)
         }
}
```

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2 v1.16.4
	github.com/aws/aws-sdk-go-v2/config v1.15.9
	github.com/aws/aws-sdk-go-v2/service/s3 v1.26.10

	github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.4.1 // indirect
	github.com/aws/aws-sdk-go-v2/credentials v1.12.4 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.5 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.11 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.5 // indirect

	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.12 // indirect
	github.com/aws/aws-sdk-go-v2/internal/v4a v1.0.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.9.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.1.6 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.5 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.13.5 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.11.7 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.16.6 // indirect
	github.com/aws/smithy-go v1.11.2 // indirect

### Compiler and Version used

go version go1.19.1 darwin/arm64

### Operating System and version

macOD Monterey, Version 12.3

**Comment by Tahmeed27** [comment]
Hey! Thanks a lot your sample code helped test the bare minimum. Turns out the problem was with the cron job timing out before the copying had finished rather than the actual copy not working. On that note, do you have any recommendations on how to do this copying faster rather than just sequentially copying every object?

**Comment by RanVaknin** [comment]
Hi @Tahmeed27 ,

I'm glad my code sample helped 😄 .

AS far as recommendations goes, I'm not an S3 expert and I don't know your exact use case. I suggest you take a look at [batch operation's copy objects.](https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-copy-object.html) I don't know how much faster it is than doing it the way you did, but I know its meant to operate on data in larger scale, so depending on your use case - this might be for you.

I'll go ahead and mark this issue resolved. If you run into any other issues feel free to open a new one.

All the best,
Ran~
