### ISSUE TITLE
Failed to sign request with a basic example and a profile passed as an environment variable

### ISSUE THREAD

**Issue by yvele** [aws/aws-sdk-go-v2#1897]
### Describe the bug

AWS SDK GO is unable to sign any request when passing a profile as an environment variable and I get this error:

> failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded

### Expected Behavior

To work with the provided profile 🤷 
Note that everything is working fine with AWS SDK for Node.js with the same profile.

### Current Behavior

```
hello world
operation error S3: ListBuckets, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10038865c]

goroutine 1 [running]:
main.main()
	/Users/yves/Projects/test/repro.go:27 +0x1ac
exit status 2
```

### Reproduction Steps

```go
package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	fmt.Println("hello world")

	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		panic("configuration error, " + err.Error())
	}

	client := s3.NewFromConfig(cfg)

	// https://docs.aws.amazon.com/code-library/latest/ug/go_2_s3_code_examples.html
	listBucketsResult, err := client.ListBuckets(context.Background(), &s3.ListBucketsInput{})
	if err != nil {
		fmt.Println(err)
	}

	for _, bucket := range listBucketsResult.Buckets {
		fmt.Printf("Bucket name: %s\t\tcreated at: %v\n", *bucket.Name, bucket.CreationDate)
	}
}
```

```sh
 AWS_REGION=eu-west-1 AWS_PROFILE=my-profile go run repro.go
```

### AWS Go SDK V2 Module Versions Used

```
go 1.16

require (
	github.com/aws/aws-lambda-go v1.34.1
	github.com/aws/aws-sdk-go-v2 v1.17.1
	github.com/aws/aws-sdk-go-v2/config v1.17.8
	github.com/aws/aws-sdk-go-v2/service/firehose v1.14.21
	github.com/aws/aws-sdk-go-v2/service/s3 v1.29.1
	github.com/aws/aws-sdk-go-v2/service/sqs v1.19.10
	github.com/aws/aws-xray-sdk-go v1.7.1
)
```

### Compiler and Version used

go version go1.18.4 darwin/arm64

### Operating System and version

macOS Monterey Version 12.6

**Comment by RanVaknin** [comment]
HI @yvele ,

I'm not sure why you are running into this issue. I can run your code on my machine without any issues.
Can you give me some context on how you are running this? Is this code running in a Docker container?

Thanks,
Ran~

**Comment by yvele** [comment]
> HI @yvele ,
> 
> I'm not sure why you are running into this issue. I can run your code on my machine without any issues. Can you give me some context on how you are running this? Is this code running in a Docker container?
> 
> Thanks, Ran~

I'm running this code with no container or VM.. directly on my MacBook Pro 2021 🤷 
Are you on the same OS?

**Comment by RanVaknin** [comment]
>I'm running this code with no container or VM.. directly on my MacBook Pro 2021 🤷
Are you on the same OS?

Hi @yvele ,

I'm really confused about why you are running into this issue. I see no indication in your code that something is wrong. Somehow the credentials are not being pulled in correctly.

Do you have `AWS_PROFILE=my-profile` setup somewhere? Have you configured your shared credentials file?

Can you enable wire logs and share them here?

```go
cfg, err := config.LoadDefaultConfig(context.Background(), config.WithClientLogMode(aws.LogRequestWithBody | aws.LogResponseWithBody))
```

Thanks,
Ran~

**Comment by nate-anderson** [comment]
I'm actually seeing a very similar error attempting to use the S3 client in a GitHub actions workflow:

```panic: operation error S3: CreateBucket, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, failed to get API token, cannot get API token, operation error ec2imds: getToken, http response error StatusCode: 400, request to EC2 IMDS failed```

I have no idea why the client is trying to use IMDS when I haven't asked it to. I am instantiating the client with the code below:

```go
endpoint := "http://localhost:4566"
region := "us-west-2"

customResolver := aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
	return aws.Endpoint{
		PartitionID:   "aws",
		URL:           endpoint,
		SigningRegion: region,
	}, nil
})

awsCfg, err := config.LoadDefaultConfig(
	context.Background(),
	config.WithRegion(region),
	config.WithEndpointResolver(customResolver), config.WithClientLogMode(aws.LogRequestWithBody|aws.LogResponseWithBody),
	)
if err != nil {
	log.Fatalf("Cannot load the AWS configs: %s", err)
}

client := s3.NewFromConfig(awsCfg, func(o *s3.Options) {
	o.UsePathStyle = true
})

_, err = client.CreateBucket(ctx, &s3.CreateBucketInput{
	Bucket: &bucket,
	CreateBucketConfiguration: &types.CreateBucketConfiguration{
		LocationConstraint: "us-west-2",
	},
})
```

**Comment by russellhaering** [comment]
@nate-anderson did you ever manage to make this work?

**Comment by aajtodd** [comment]
> I have no idea why the client is trying to use IMDS when I haven't asked it to.

You haven't asked it to use any particular credentials provider which means it will attempt to resolve credentials using the default chain. This consists of attempting multiple possible credential sources. The IMDS credentials provider is the last provider in the default chain. It means no other sources for credentials were found and it ended up attempting to use IMDS as last resort.

See [developer guide](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials) for more details
