### ISSUE TITLE
Error while DescribeRegions() using AssumeRole

### ISSUE THREAD

**Issue by nehatomar12** [aws/aws-sdk-go-v2#1898]
### Describe the bug

I am using AssumeRole, I wanted to fetch all the regions in the target account
```
cfg, err := config.LoadDefaultConfig(ctx,
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider("Access_key", "Secret_key", "")),
		config.WithRegion("us-east-1"),
	)

stsSvc := sts.NewFromConfig(cfg)
creds := stscreds.NewAssumeRoleProvider(stsSvc,"assumeRole_ARN")
cfg.Credentials = aws.NewCredentialsCache(creds)
svc := ec2.NewFromConfig(cfg)

svc.DescribeRegions(ctx, &ec2.DescribeRegionsInput{})

it gives an error:  api error UnauthorizedOperation: You are not authorized to perform this operation.

```
with the same code, I was able to do `DescribeKeyPairs` and with AWS cli I am able to list region

anything I am missing while sts configuration 

### Expected Behavior

Should list all the regions in target accountthe 

### Current Behavior

Giving error: UnauthorizedOperation

### Reproduction Steps

use AssumeRole to fetch all regions

### AWS Go SDK V2 Module Versions Used

v1.16.16

### Compiler and Version used

go1.18.2 darwin/amd64

### Operating System and version

mac

**Comment by RanVaknin** [comment]
Hi @nehatomar12 ,

Thanks for opening this issue!

Your code seems right. That error is not an SDK error but an error coming from the STS server.
> **with the same code, I was able to do DescribeKeyPairs** 

 You are either assuming the wrong role, either the role you are assuming does not have the right permissions. 
 In the IAM console -> Role -> find the role you are assuming -> add the right permissions to call `describeRegions`
 
 >and with AWS cli I am able to list region
 
Can you share the CLI command you used?

In addition please the response logs, as that might give me a better idea of what is failing server side. You can add them the following way:
```go
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogResponseWithBody))

```

Thanks,
Ran~

**Comment by nehatomar12** [comment]
@RanVaknin 
Cli I used:
` aws ec2 describe-regions --all-regions     Note(~/.aws/credentials has the target account accesskey/secretkey/region set)`

**Comment by RanVaknin** [comment]
@nehatomar12 ,

I ran your Go code just and was able to assume role, and describe the regions successfully. This leads me to believe that you are not assuming the role you say you are, or you are making a request that your role is not allowed to do.
These are the steps I'll do to investigate what are the discrepancies between the CLI and SDK:

1. >Note(~/.aws/credentials has the target account accesskey/secretkey/region set)

Sure, you have the credentials set up in the shared credentials file, but do you actually assume the role to then call that `describe-regions` command like you do in the SDK? Check [this guide](https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-cli/) if not.

2. You are not running the same command from the CLI vs the SDK (_I'm not actually sure if this will cause a 403 error or not)._
You can either run the CLI command without the `--all-regions` flag, or add that argument to the SDK and test:

```go
	regions, err := svc.DescribeRegions(context.Background(), &ec2.DescribeRegionsInput{
		AllRegions: aws.Bool(true),
	})
```

3. Investigate the Request made by each platform:
- Enable your logs on the Go SDK client by doing this:
```go
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogRequestWithBody | aws.LogResponseWithBody))
```
 
- In your CLI run the same command you used using the `--debug` flag and **check what is the account ARN that is making the reqeust.**

**(dont share these here)**

Invesitagte the request URI, the parameters, headers.

Let me know if this helps.
Ran

**Comment by nehatomar12** [comment]
@RanVaknin after adding permission to my assumeRole it worked!
Thanks
