### ISSUE TITLE
Custom Error Handling

### ISSUE THREAD

**Issue by jerrydevin96** [aws/aws-sdk-go-v2#1905]
### Describe the feature

I am using `aws-sdk-v2` to start and stop a state machine execution. Currently while starting a state machine using `StartExecution(ctx context.Context, params *sfn.StartExecutionInput, optFns ...func(*sfn.Options ))(*sfn.StartExecutionOutput, error)` the error returned is of type `*smithy.OperationError`.

Going through the `sfn` module in the library, I can see that custom error types have been defined, but they are wrapped too deep inside other error types making it hard to validate a specific error.

It would be really nice if the error type returned by the `StartExecution` function is one of the error types defined in `github.com/aws/aws-sdk-go-v2/service/sfn/types`

### Use Case

My use case is to check the error returned to see if a workflow has been already started. I can validate it easily by checking for the presence of `ExecutionAlreadyExists` in the error message, but a cleaner approach would be to validate against the custom error type `type ExecutionAlreadyExists struct` defined in the module.

To achieve the second case at the moment, I have to unwrap multiple error layers, before I can reach the actual error type. You can find the code snippet I used below

```
import(
        "github.com/aws/aws-sdk-go-v2/service/sfn/types"
	awshttp "github.com/aws/aws-sdk-go-v2/aws/transport/http"
	smithy "github.com/aws/smithy-go"
)

func func (c *Client) Start() {
<some code here>
	startExecutionOutput, err := c.SFNClient.StartExecution(ctx, startExecutionInput)

	if err != nil {
		smithyErr, isSmithyErr := err.(*smithy.OperationError)
		fmt.Println(isSmithyErr)
		awshttpErr, isawserr := smithyErr.Err.(*awshttp.ResponseError)
		fmt.Println(isawserr)
		respErr := awshttpErr.ResponseError
		_, repeatExecution := respErr.Err.(*types.ExecutionAlreadyExists)
		if repeatExecution {
			return &StartWorkflowOutput{
				Message: executionAlreadyExists,
			}, nil
		}
		return nil, err
	}
}
```

### Proposed Solution

The error type returned by `StartExecution` function can be one of the error types defined in `github.com/aws/aws-sdk-go-v2/service/sfn/types` instead of `*smithy.OperationError`. This allows cleaner error validation for anyone using the library. The same model can be used for error types returned by other modules under services as well.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.17.1
github.com/aws/aws-sdk-go-v2/config v1.17.10 // indirect
github.com/aws/aws-sdk-go-v2/service/sfn v1.14.3
github.com/aws/smithy-go v1.13.4 // indirect

### Go version used

go 1.12

**Comment by RanVaknin** [comment]
Hi @jerrydevin96 ,

To achieve what you are asking please refer to our error handling section in the v1-> v2 [migration guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/#errors-types). I believe this addresses your concern.

Let me know if you have any questions :) 
Ran~

**Comment by jerrydevin96** [comment]
Hey @RanVaknin

Thanks for your response. I will check how this works in my case and write back.

**Comment by jerrydevin96** [comment]
@RanVaknin 
Thanks a Lot!

I was able to resolve the custom error types by following the documentation.

Best,
Jerry

**Comment by RanVaknin** [comment]
My pleasure 😄
