### ISSUE TITLE
Please provide helper functions for generating AWS console signin URLs

### ISSUE THREAD

**Issue by jabalsad** [aws/aws-sdk-go-v2#1915]
### Describe the feature

It would be great if the process described here is provided for us by the AWS SDK:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html

Every developer requiring to re-implement this logic is burdensome and potentially error prone. 

### Use Case

Generate console sign-in URL from STS AssumeRole (or other) credentials.

### Proposed Solution

A helper function in the STS (or other module):
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

n/a

### Go version used

1.19

**Comment by RanVaknin** [comment]
Hi @jabalsad ,

We may add this eventually but we encourage customers to implement and share implementations—the core SDKs exist as a direct reflection of the AWS Services' models. We aim to keep the code generated SDKs separate from 'helper' behavior.
Ideally this would be added a standalone helper client and not a part of the Go SDK.

I really do appreciate you taking the time and opening the feature request here. Even though this will most likely not get implemented, we encourage you to engage with us whenever a problem / other needs arise.

Thanks again,
Ran
