### ISSUE TITLE
kinesis.ListStreams is missing a paginator

### ISSUE THREAD

**Issue by mraszplewicz** [aws/aws-sdk-go-v2#1924]
### Describe the feature

In the Go SDK v1 there is a ListStreamsPages function however ListStreamsPaginator is missing from Go SDK v2.

### Use Case

I want to iterate over all the existing Kinesis streams and remove some of them with certain tags.

### Proposed Solution

Please implement the ListStreamsPaginator in the Go SDK v2.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/kinesis v1.15.22

### Go version used

go version go1.19 linux/amd64

**Comment by RanVaknin** [comment]
Hi @mraszplewicz ,

Thanks for opening this feature request. 
Normally paginators are auto-generated based on the API models of the respective AWS service teams. Unfortunately the Kinesis team did not model their API correctly for the code-generation to take place and this would require us to hand write the paginator. 

I will discuss it with the team to see if we can add it to the backlog, but in the spirit of full transparency I will say that we don't have any bandwidth at the moment so if we decide to implement this it will be at some later point in the future.

Thank you very much again for engaging in our community!
All the best,
Ran~

**Comment by RanVaknin** [comment]
Hi @mraszplewicz ,

This has been added as of 12/15/22

Sorry for the long wait.
Thanks,
Ran~

**Comment by mraszplewicz** [comment]
I can confirm that it works. Thank you @RanVaknin!
