### ISSUE TITLE
Breaking changes released as a non major version bump

### ISSUE THREAD

**Issue by erezrokah** [aws/aws-sdk-go-v2#1951]
### Describe the bug

Hello 👋 lovely AWS SDK folks, and thank you for  building and maintaining this SDK 🚀 

In a recent SDK update of `github.com/aws/aws-sdk-go-v2/service/fsx` from `v1.25.4` to `v1.26.0` a breaking change was done as a part of the minor version bump.

The breaking change was the removal of `Subtype StorageVirtualMachineSubtype` from the `StorageVirtualMachine` struct, see (screenshot since it's a large diff):
![image](https://user-images.githubusercontent.com/26760571/205594549-355443ad-30d8-463c-a66f-8c8e8cc56ce9.png)
https://github.com/aws/aws-sdk-go-v2/compare/service/fsx/v1.25.4...service/fsx/v1.26.0#diff-652ce7e3a32e105d33459061674942ee5c358b50204aa8bb1711a17d0d016590L3077

`CreateOntapVolumeConfiguration` struct  also had a bunch of fields removed.

I'd consider removal of struct properties as breaking changes as they break compilation

### Expected Behavior

The above update should have been released as a major version bump

### Current Behavior

The above update was released as a minor version bump

### Reproduction Steps

See commit diff

### Possible Solution

Release removal, renames and type changes of struct fields as breaking changes

### Additional Information/Context

If I'm mistaken and a removal of a struct field is not considered a breaking change, is there a list of what consists an SDK breaking change documented anywhere for reference?

### AWS Go SDK V2 Module Versions Used

Trimmed for brevity

```
...
github.com/aws/aws-sdk-go-v2/service/fsx v1.26.0
...
```

### Compiler and Version used

`go version go1.19.3 darwin/arm64`

### Operating System and version

`MacOS Ventura 13.0.1 (22A400)`

**Comment by RanVaknin** [comment]
Hi @erezrokah,

Thank you for reaching out 😄.
We are aware of this issue. The fsx team removed that type from their model, and when they released their latest version of the API, the SDK got updated with that missing field and caused your code (and other's) to break. 

I can see that they have pushed a fix to re-introduce that member model member, and it's awaiting approvals. I can't commit to a timeline, but I really hope that it happens soon.

Apologies for the inconvenience. I Will keep this issue open for tracking and update when resolved.
Thank you!
Ran~

**Comment by erezrokah** [comment]
Hi @RanVaknin and thank you for the quick response, and I'm glad to know a fix for `fsx` is coming.

Looking forward for it 🚀

**Comment by RanVaknin** [comment]
Hi @erezrokah,

Sorry to update you in a such a delay. I had to manually check that this was updated.
It seems like the fsx team re-introduced this subtype. 

Thanks for your patience. 
All the best,
Ran~
