### ISSUE TITLE
Unresolved type 'RequestLaunchTemplateData'

### ISSUE THREAD

**Issue by nochet2211** [aws/aws-sdk-go-v2#1953]
### Describe the bug

I'm trying to use type 'RequestLaunchTemplateData' in 'CreateLaunchTemplateVersionInput'. 

However, for whatever reason the ec2 object doesn't seem to have the type.

```go
    svc := ec2.NewFromConfig(cfg)
    newLt, err := svc.CreateLaunchTemplateVersion(ctx, &ec2.CreateLaunchTemplateVersionInput{
		LaunchTemplateData: &ec2.RequestLaunchTemplateData{
			ImageId:      aws.String("ami-8c1be5f6"),
			InstanceType: aws.String("t2.small"),
			NetworkInterfaces: []*ec2.LaunchTemplateInstanceNetworkInterfaceSpecificationRequest{
				{
					AssociatePublicIpAddress: aws.Bool(true),
					DeviceIndex:              aws.Int64(0),
					Ipv6AddressCount:         aws.Int64(1),
					SubnetId:                 aws.String("subnet-7b16de0c"),
				},
			},
			TagSpecifications: []*ec2.LaunchTemplateTagSpecificationRequest{
				{
					ResourceType: aws.String("instance"),
					Tags: []*ec2.Tag{
						{
							Key:   aws.String("Name"),
							Value: aws.String("webserver"),
						},
					},
				},
			},
		},

		VersionDescription: "Created by xmxmxm"
	})
```

### Expected Behavior

It's supposed to accept RequestLaunchTemplateData as an input type within ec2 object.

### Current Behavior

Says `Unresolved type 'RequestLaunchTemplateData'`

### Reproduction Steps

Mentioned in code above

### AWS Go SDK V2 Module Versions Used

go get: upgraded github.com/aws/aws-sdk-go-v2/service/ec2 v1.74.0 => v1.75.0

### Compiler and Version used

go version go1.17.2 darwin/amd64

### Operating System and version

MacOS 12.6 (21G115)

**Comment by RanVaknin** [comment]
Hi @nochet2211 ,

Thanks for opening this issue 😄 

That type lives in this path: `"github.com/aws/aws-sdk-go-v2/service/ec2/types"`
So it will be :

```go
import (
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"	
)
// ...
// ...
// ...
		LaunchTemplateData: &types.RequestLaunchTemplateData{},
			ImageId:      aws.String("ami-8c1be5f6"),
			InstanceType: aws.String("t2.small"),
			//...
```
Same goes for `LaunchTemplateInstanceNetworkInterfaceSpecificationRequest`, and `LaunchTemplateTagSpecificationRequest`.

Let me know if you have any other questions!
All the best,
Ran~
