### ISSUE TITLE
Cannot get event selectors for a multiregion trail

### ISSUE THREAD

**Issue by xqi-aviatrix** [aws/aws-sdk-go-v2#1957]
### Describe the bug

When I create a regional cloudtrail client with a specific region (which region is a required input when creating the client config), I cannot get the event selectors for a multi-region Trail with the regional cloudtrail client (client.GetEventSelectors)

### Expected Behavior

There should be a way to get the event selectors for a multi-region trail 

### Current Behavior

There is no way to get the event selectors for a multi-region trail 

### Reproduction Steps

- create a cloudtrail client with a regional aws config
- create a multi-region Trail
- query the Trail's Selectors through the client created in step 1, client.GetEventSelectors
- no selector returned.

### AWS Go SDK V2 Module Versions Used

cloudtrail/playground github.com/aws/aws-sdk-go-v2@v1.17.2
cloudtrail/playground github.com/aws/aws-sdk-go-v2/config@v1.18.4
cloudtrail/playground github.com/aws/aws-sdk-go-v2/credentials@v1.13.4
cloudtrail/playground github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.20
cloudtrail/playground github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.26
cloudtrail/playground github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20
cloudtrail/playground github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.27
cloudtrail/playground github.com/aws/aws-sdk-go-v2/service/cloudtrail@v1.20.4
cloudtrail/playground github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.20
cloudtrail/playground github.com/aws/aws-sdk-go-v2/service/sso@v1.11.26
cloudtrail/playground github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.9
cloudtrail/playground github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6
cloudtrail/playground github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2@v1.17.2 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2@v1.17.2 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.17.2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/aws-sdk-go-v2/credentials@v1.13.4
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.20
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.27
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.26
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.9
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/config@v1.18.4 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/credentials@v1.13.4 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/credentials@v1.13.4 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.20
github.com/aws/aws-sdk-go-v2/credentials@v1.13.4 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.26
github.com/aws/aws-sdk-go-v2/credentials@v1.13.4 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.9
github.com/aws/aws-sdk-go-v2/credentials@v1.13.4 github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6
github.com/aws/aws-sdk-go-v2/credentials@v1.13.4 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/credentials@v1.13.4 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.20 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.20 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.20 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.26 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.27 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/service/cloudtrail@v1.20.4 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/service/cloudtrail@v1.20.4 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.26
github.com/aws/aws-sdk-go-v2/service/cloudtrail@v1.20.4 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20
github.com/aws/aws-sdk-go-v2/service/cloudtrail@v1.20.4 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.20 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.20 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.20 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.26 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.26 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.26
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.26 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.26 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.9 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.9 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.26
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.9 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.9 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6 github.com/aws/aws-sdk-go-v2@v1.17.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.26
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.20
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.20
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.6 github.com/aws/smithy-go@v1.13.5
github.com/aws/smithy-go@v1.13.5 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.5 github.com/jmespath/go-jmespath@v0.4.0

### Compiler and Version used

go version go1.19.1 darwin/amd64

### Operating System and version

macOS 13.0 (22A380)

**Comment by RanVaknin** [comment]
Hi @xqi-aviatrix ,

Since there is no code included I can only assume that what you are experiencing is the following situtation:

1. You created a multi-region trail on a certain region (for example `us-east-1`)
❗ _Note: if you haven't specified a region for the creation, the SDK will choose the region based on what is defined for 
   your profile in your `.aws/config` file._
2. you are querying that trail with the SDK supplying `us-east-1` and you get **valid response**.
3. you are querying that trail with the SDK supplying a different region, for example `us-east-2` and you get **an invalid response:**
```
{"__type":"TrailNotFoundException","Message":"Unknown trail: arn:aws:cloudtrail:us-east-2:REDACTED:trail/my-trail for the user: REDACTED"}
panic: operation error CloudTrail: GetEventSelectors, https response error StatusCode: 400, RequestID: cf6d3bf0-18ee-4b5e-a06e-9d8956cf75a1, TrailNotFoundException: Unknown trail: arn:aws:cloudtrail:us-east-2:REDACTED:trail/my-trail for the user: REDACTED
```
☝️  you will see this only if you enable response logging.

This error is coming from the server, and has nothing to do with the SDK. If I understand the Cloudtrail docs correctly, trails have a "home region" which they all live in.
<img width="2222" alt="Screen Shot 2022-12-09 at 12 56 28 PM" src="https://user-images.githubusercontent.com/50976344/206795065-120d251e-0162-44aa-b601-8914f548b893.png">


 The trails will get replicated across different regions for the purpose of logging to s3 and or a cloudwatch log group. 
To query the trail you'll have to use the region in which it was created.

From the docs:
>You can configure CloudTrail to deliver log files from multiple regions to a single S3 bucket for a single account. For example, you have a trail in the US West (Oregon) Region that is configured to deliver log files to a S3 bucket, and a CloudWatch Logs log group. When you change an existing single-region trail to log all regions, CloudTrail logs events from all regions that are in a single AWS partition in your account. CloudTrail delivers log files to the same S3 bucket and CloudWatch Logs log group. As long as CloudTrail has permissions to write to an S3 bucket, the bucket for a multi-region trail does not have to be in the trail's home region.

So in order to get a valid response from the Cloudtrail API you have to specify the home region of your multi-region trail.

Let me know if you have any questions.
Thanks,
Ran~

**Comment by xqi-aviatrix** [comment]
@RanVaknin , thanks for the response, here is what I encountered
- I create a multiregion trail, named as "test", on the Trail console with management event enabled
- I create cloudtrail client with region us-west-2
`region := "us-west-2"
  trailName := "test"
   cred := aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider("mykey", "my secret", ""))
   awsConfig, err := config.LoadDefaultConfig(ctx, config.WithCredentialsProvider(cred), config.WithRegion(region))
	if err != nil {
		fmt.Printf("aws config creation failed %v", err.Error())
		return
	}
	ctClient := cloudtrail.NewFromConfig(awsConfig)`
- I query the selectors of the multiregion trail with the client `ctClient`
`eventSelectors, err := ctClient.GetEventSelectors(ctx, &cloudtrail.GetEventSelectorsInput{TrailName: trailName})
			if err != nil {
				fmt.Println(err)
			}
cnt:=0
			for _, selector := range eventSelectors.EventSelectors {
				cnt++
			}`

     The cnt is zero which means no selectors are returned.

**Comment by RanVaknin** [comment]
Hi @xqi-aviatrix ,

Thanks for the clarification.

A few things to point out:
1. You can turn text into a code block on github by adding ``` **before** and **after** text or highlighting text and clicking on the `<>` button on the text editor. 
This will help readability 😄 .

2. The reason you are not seeing any Event Selectors returned is probably because there are none added for the given trail.
Consider my code:

```go
func main() {
	// creating my config, with response logging enabled
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogResponseWithBody))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	// initializing the client
	client := cloudtrail.NewFromConfig(cfg)

	// creating an event selector for my given trail.
	_, err = client.PutEventSelectors(context.Background(), &cloudtrail.PutEventSelectorsInput{
		TrailName: aws.String("my-trail"),
		EventSelectors: []types.EventSelector{
			{
				ReadWriteType: "All",
			},
		},
	})
	if err != nil {
		panic(err)
	}

	// fetching all event selectors for my given trail.
	out, err := client.GetEventSelectors(context.Background(), &cloudtrail.GetEventSelectorsInput{
		TrailName: aws.String("my-trail"),
	})
	if err != nil {
		panic(err)
	}

	// proof that I have selectors in my trail:
	fmt.Println("There are: ", len(out.EventSelectors), "selectors")
}
```

Output:

```console
Process finished with the exit code 0
```
