### ISSUE TITLE
problem with dynamodb expression builder and nested map attributes

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [aws/aws-sdk-go-v2#196]
### Version of AWS SDK for Go?
2.0.0-preview.4

### Version of Go (`go version`)?

go version go1.10.3 darwin/amd64

### What issue did you see?

Attempting to use nested map path expressions delimited by a period results in attribute surrounded by curly braces (e.g. `{likes}`).

### Steps to reproduce
```go
name := expression.Name("likes.user22")
value := expression.Value("FIXME")
update := expression.UpdateBuilder{}
update = update.Set(name, value)
builder := expression.NewBuilder().WithUpdate(update)
expression, error := builder.Build()
if error != nil {
	return nil, error
}
input := &dynamodb.UpdateItemInput{
	Key: map[string]dynamodb.AttributeValue{
		"id": {
			S: aws.String(messageID),
		},
	},
	TableName:                 aws.String(d.tableName),
	ExpressionAttributeNames:  expression.Names(),
	ExpressionAttributeValues: expression.Values(),
	UpdateExpression:          expression.Update(),
}

fmt.Println(input)
```

```
{
  ConditionalOperator: ,
  ExpressionAttributeNames: {
    #0: "{likes}",
    #1: "user22"
  },
  ExpressionAttributeValues: {
    :0: {
      S: "FIXME"
    }
  },
  Key: {
    id: {
      S: "l4wAHLvJzwI+"
    }
  },
  ReturnConsumedCapacity: ,
  ReturnItemCollectionMetrics: ,
  ReturnValues: ,
  TableName: "whatever",
  UpdateExpression: "SET #0.#1 = :0\n"
}
```

**Comment by xibz** [comment]
Hello @WIZARDISHUNGRY, thank you for reaching out to us. We've received this same issue in v1, please see [here](https://github.com/aws/aws-sdk-go/issues/682). The workaround will also work for v2. I am going to go ahead and mark this as a feature request. If you have any more questions or issues with workaround please let us know.

**Comment by WIZARDISHUNGRY** [comment]
@xibz I think you meant to reply to #195

**Comment by xibz** [comment]
@WIZARDISHUNGRY - Yep, let me move that comment

**Comment by WIZARDISHUNGRY** [comment]
I think I may have done something weird as when I recreated my test code (which had been extracted from significantly more confusing production code)
