### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method

### ISSUE THREAD

**Issue by GGDEAJ** [aws/aws-sdk-go-v2#1962]
### Describe the bug

We are executing a cloud function to make a query on the cloud watch, for that we are using the aws-go-sdk-v2 lib, but when we are invoking the startQuery method of the http client it shows an error.
`InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

You can help us with the indication of this problem or to solve it.

Thanks!

### Expected Behavior

Is expected data from cloudWatchLogs

### Current Behavior

When I call function of StartQuery from cloudwatchlogs.. is showing this error

InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

### Reproduction Steps

```go
func (q *QueryLogsInsigts) Execute(inputStartQuery *cloudwatchlogs.StartQueryInput) (*cloudwatchlogs.GetQueryResultsOutput, error) {

	user := "<USER>"
	pass := "<PASS>"
	region := "us-east-1"

	appCreds := aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider(user, pass, ""))

	config, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion(region))
	if err != nil {
		return nil, err
	}

	client := cloudwatchlogs.NewFromConfig(config, func(o *cloudwatchlogs.Options) {
		o.Credentials = appCreds
	})

	startQueryOutput, err := client.StartQuery(context.TODO(), inputStartQuery)
	if err != nil {
		return nil, err
	}

	resultsOutput, err := getQueryResultsUntilCompleate(q.ctx, q.cwl, startQueryOutput.QueryId, 10)
	if err != nil {
		return nil, err
	}

	return resultsOutput, nil
}
```

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs

### Compiler and Version used

go version go1.19.2 darwin/arm64

### Operating System and version

macOS Monterey v. 12.2.1

**Comment by GGDEAJ** [comment]
We have some example for this class

`https://github.com/aws/aws-sdk-go-v2/blob/main/service/cloudwatchlogs/api_op_StartQuery.go`

**Comment by RanVaknin** [comment]
Hi @GGDEAJ ,

I'm missing a lot of information to help you debug this. If I had to guess I would say that the way you are setting your credentials are causing this issue.

For example this line:
```go
	appCreds := aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider(user, pass, ""))
```
Where are using `appCreds`? I dont see it in your code. The code snippet you provided will not compile.

If you want to instruct the config to use those credentials you can use the following:
```go
	credentialProvider := aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider(user, pass, "")) // renamed variable because your naming was confusing.

	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion(region), config.WithCredentialsProvider(credentialProvider))
	if err != nil {
		panic(err)
	}
```

**⚠️ Warning:** Hard coding credentials is not recommended. 
Consider storing your credentials in your shared credentials file under `~/.aws/credentials`. 
That way you don't need to construct a credential provider object at all and your `config.LoadDefaultConfig()` function will resolve the credentials on your behalf using the default credential chain.
[For more info](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

Let me know if that helps.
Thanks,
Ran~
