### ISSUE TITLE
Region not being picked up from EKS node metadata

### ISSUE THREAD

**Issue by pdeva** [aws/aws-sdk-go-v2#1967]
### Describe the bug

Seems pods on EKS are not able to get instance metadata. I am getting erros about region not being specified. if i add the AWS_REGION env var, the error goes away. however that shouldnt be needed.

### Expected Behavior

region should be picked up from underlying ec2 node using aws intance metatadata.

### Current Behavior

getting error:
```json
 {"level":"fatal","error":"operation error RDS: DescribeDBClusters, failed to resolve service endpoint, an AWS region is required, but was not found","time":"2022-12-22T02:00:30Z","message":"error initializing application"}
```

### Reproduction Steps

code:

```go

import (
awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/rds"
)

func test() {
        aconfig, err := awsconfig.LoadDefaultConfig(ctx)
        ctx := context.Background()
	if err != nil {
		return nil, err
	}
	rdsClient := rds.New(rds.Options{
		Credentials: aconfig.Credentials,
		Region:      aconfig.Region,
	})

	

	clusterDesc, err := rdsClient.DescribeDBClusters(ctx, &rds.DescribeDBClustersInput{
		DBClusterIdentifier: &pgconfig.PGCluster,
	})
	if err != nil {
		return nil, err
	}
}
```

adding the env var AWS_REGION with value `us-east-1` makes the error go away. however that shouldnt be needed since region should be picked up from the ec2 node.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/rds v1.30.1

### Compiler and Version used

go 1.19

### Operating System and version

linux x64

**Comment by RanVaknin** [comment]
Hi @pdeva ,

Thanks for opening this issue!

When using the SDK on EC2 instance the proper way would be to create an IAM role with the correct permissions and use the `ec2rolecreds()` utility assume the role and retrieve credentials on your behalf. That utility exists under the umbrella of the IMDS or Instance Metadata Service. Which is a hand-written client (unlike all the other SDK clients that are code-generated) meant exactly for this.

Please check out my response [here](https://github.com/aws/aws-sdk-go/issues/4623#issuecomment-1314549666) for in an example. 

>region should be picked up from underlying ec2 node using aws intance metatadata.

This is not how the IMDS client was designed. The credentials are drawn from the role associated with the instance, 
when constructing a specific service client you'll have to explicitly define which region you are going to use.

Let me know if you have any questions.

Thanks,
Ran

**Comment by pdeva** [comment]
@RanVaknin if i understand this correctly:

1. AWS Resion *always* needs to be specified manually. The sdk cannot pick it up from the underlying ec2 instance profile.
2. The `ec2rolecreds` utility functions should be used when running code on EC2 instance so aws go sdk can pick up ec2 instance profile credentials.
3. However, `ec2rolecreds` dont seem to be required when running inside EKS pods using IRSA. I say that cause my pods are able to get permissions assigned to the IRSA role with just the code in my original post above, which does *not* use `ec2rolecreds`.

Is the above all correct?

**Comment by RanVaknin** [comment]
Hi @pdeva ,

Thanks for the follow up questions. I actually needed to do some deep dive to see how this is handled internally and It seems like I have misled you. Here is what I've learned:

You can use the IMDS (instance metadata service) client and you can call the `getRegion()` method from that client:
```go

func main() {
        cfg, err := config.LoadDefaultConfig(context.TODO())
        if err != nil {
                log.Fatalf("failed to load SDK configuration, %v", err)
        }

        client := imds.NewFromConfig(cfg)

        resp, err := client.GetRegion(context.TODO(), &imds.GetRegionInput{})
        if err != nil {
                log.Printf("Unable to retrieve the region from the EC2 instance %v\n", err)
        }

        fmt.Printf("region: %v\n", resp.Region)
}
```
ec2rolecreds really deals with the instance profile rather than the instance metadata. 

Hope this helps,

Thanks again!
Ran~

**Comment by pdeva** [comment]
@RanVaknin can you also paste the imports in your code snippet above. without the imports, i dont know which 'imds' client you are referring to is located.

**Comment by RanVaknin** [comment]
Hi @pdeva ,

its in ec2, so `"github.com/aws/aws-sdk-go-v2/feature/ec2/imds"`

Thanks,
Ran
