### ISSUE TITLE
amazon lightsail how to use service(like create instance)

### ISSUE THREAD

**Issue by loveyandex** [aws/aws-sdk-go-v2#1979]
### Describe the bug

dynamodb has many functions but lighsail not ...how to use lightsail and how to credentials(api token) for it 

![image](https://user-images.githubusercontent.com/53381292/210970291-3c79daa2-8efa-40fb-966c-00bc9ce3a12d.png)

![image](https://user-images.githubusercontent.com/53381292/210970049-3794e8b9-3368-4d42-85cf-6eb181dbb477.png)

### Expected Behavior

we expect find functionality of LightSail but we don't see any example

we also not seeing how to use config for authenticion

### Current Behavior

nothing

### Reproduction Steps

do

### AWS Go SDK V2 Module Versions Used

latest

### Compiler and Version used

1.19

### Operating System and version

windows

**Comment by loveyandex** [comment]
i found it and loaded funions but my question now is how config to detect my account 
    cfg, err := config.LoadDefaultConfig(context.TODO(),
   		config.WithRegion("us-west-2"),
   	)
i dont understand it by region without api token

![image](https://user-images.githubusercontent.com/53381292/210972644-29bfa083-61f9-49ac-abaf-20cb25b78cd9.png)

**Comment by RanVaknin** [comment]
Hi @loveyandex ,

>dynamodb has many functions but lighsail not

Lightsail is it's own service , and is **not** related to DynamoDB.  I see you figured out how to import the correct client for it.

>my question now is how config to detect my account

The SDK abstracts the need for API tokens and is using something called the default credentials chain to try and get your AWS Credentials to make those requests for you. It needs to have the credentials set either in your shared credential file (`~/.aws/credentials`), Environment variables, or hardcoded account key and secret (not recommended).

If you have not done that already, please check out [this doc.](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)

Let me know if you have any other questions. 

Thanks,
Ran
