### ISSUE TITLE
aws/ec2metadata: Avoid unnecessary redirect

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#198]
V2 port of the v1 SDK's aws-sdk-go#2037. Removes unneeded redirect when making ec2 metadata calls for ec2 instance roll credentials.

**Comment by stefansundin** [comment]
I had a thought that maybe in v2, there is no need for an [`sdkuri.PathJoin`](https://github.com/aws/aws-sdk-go/pull/2037/commits/65ec8477828bf76ec98a91b762cd8d1a1f246731) method to preserve the behavior.. One reason for a v2 is the ability to break things in the desire to simplify things, right?

Anyway, just a thought. :)

**Comment by jasdel** [comment]
Agreed, one of the the ways to address this is using `URI.ResolveReference`. This method will preserve trailing slashes when joining components of a URI path. I think using ResolveReference for v2 would be the best approach. And probably should be applied to who the SDK computes URIs in general.

**Comment by stefansundin** [comment]
Hi @jasdel,

I just gave URL.ResolveReference a quick try, and I'm not sure if it will produce the results you want. See https://play.golang.org/p/TrL2Jas6CKw

```
base = http://169.254.169.254/latest/meta-data/iam/security-credentials/
base + /test/ => http://169.254.169.254/test/
base + test/ => http://169.254.169.254/latest/meta-data/iam/security-credentials/test/
base + test// => http://169.254.169.254/latest/meta-data/iam/security-credentials/test//
```

I think you want `base + /test/` to return the same as `base + test/`, right?
