### ISSUE TITLE
HeadObject failed to decode response with invalid Http bindings, unable to parse time string

### ISSUE THREAD

**Issue by benmcclelland** [aws/aws-sdk-go-v2#1981]
### Describe the bug

HeadObject fails with "failed to decode response with invalid Http bindings, unable to parse time string" if "Expires" tag is set with UTC value.

site specific info redacted:
```
SDK 2023/01/09 09:19:18 DEBUG Request Signature:
---[ CANONICAL STRING  ]-----------------------------
HEAD
<BUCKET><OBJECT>
accept-encoding:identity
amz-sdk-invocation-id:eb443c6d-8543-4d64-aef4-c95ce4c62af2
amz-sdk-request:attempt=1; max=3
host:XXX.domain
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20230109T081918Z
accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
---[ STRING TO SIGN ]--------------------------------
AWS4-HMAC-SHA256
20230109T081918Z
20230109/us-east-1/s3/aws4_request
7923d4a76bcfbe0c9ce413d460be5dc5c45abf721f79ef26fbc4f790417daee8
-----------------------------------------------------
SDK 2023/01/09 09:19:18 DEBUG Request
HEAD <BUCKET><OBJECT> HTTP/1.1
Host: XXX.domain
User-Agent: aws-sdk-go-v2/1.11.2 os/linux lang/go/1.19.4 md/GOOS/linux md/GOARCH/amd64 api/s3/1.21.0
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: eb443c6d-8543-4d64-aef4-c95ce4c62af2
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=ARXQX0GZLOX30O9ZH6Q1/20230109/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=d589627bbea9dc67e25ea4eed5af0b1d9b4fd40754045cf4006a1468d8d12819
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230109T081918Z
SDK 2023/01/09 09:19:19 DEBUG Response
HTTP/1.1 200 OK
Content-Length: 4266437120
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Date: Mon, 09 Jan 2023 08:19:19 GMT
Etag: "1e3bf0b974fe66aaad63a76a9bccf1cb-64"
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Last-Modified: Wed, 14 Dec 2022 07:27:19 GMT
X-Amz-Request-Id: tx0000057976e0acf16d09f-0063bbce07-268c88-default
X-Rgw-Object-Type: Normal
SDK 2023/01/09 09:19:19 DEBUG request failed with unretryable error https response error StatusCode: 200, RequestID: tx0000057976e0acf16d09f-0063bbce07-268c88-default, HostID: , deserialization failed, failed to decode response with invalid Http bindings, unable to parse time string, parse errors:
 * "Mon, 02 Jan 2006 15:04:05 GMT": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Mon, 02 Jan 2006 15:04:05 GMT": cannot parse "UTC" as " GMT"
 * "Mon, _2 Jan 2006 15:04:05 GMT": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Mon, _2 Jan 2006 15:04:05 GMT": cannot parse "UTC" as " GMT"
 * "Monday, 02-Jan-06 15:04:05 MST": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Monday, 02-Jan-06 15:04:05 MST": cannot parse "Thu, 01 Jan 1970 00:00:00 UTC" as "Monday"
 * "Mon Jan _2 15:04:05 2006": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Mon Jan _2 15:04:05 2006": cannot parse ", 01 Jan 1970 00:00:00 UTC" as " "
2023/01/09 09:19:19 head <BUCKET><OBJECT>: operation error S3: HeadObject, https response error StatusCode: 200, RequestID: tx0000057976e0acf16d09f-0063bbce07-268c88-default, HostID: , deserialization failed, failed to decode response with invalid Http bindings, unable to parse time string, parse errors:
 * "Mon, 02 Jan 2006 15:04:05 GMT": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Mon, 02 Jan 2006 15:04:05 GMT": cannot parse "UTC" as " GMT"
 * "Mon, _2 Jan 2006 15:04:05 GMT": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Mon, _2 Jan 2006 15:04:05 GMT": cannot parse "UTC" as " GMT"
 * "Mon, _2 Jan 06 15:04:05 GMT": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Mon, _2 Jan 06 15:04:05 GMT": cannot parse "70 00:00:00 UTC" as " "
 * "Monday, 02-Jan-06 15:04:05 MST": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Monday, 02-Jan-06 15:04:05 MST": cannot parse "Thu, 01 Jan 1970 00:00:00 UTC" as "Monday"
 * "Mon Jan _2 15:04:05 2006": parsing time "Thu, 01 Jan 1970 00:00:00 UTC" as "Mon Jan _2 15:04:05 2006": cannot parse ", 01 Jan 1970 00:00:00 UTC" as " "
```

### Expected Behavior

aws cli and other cli tools using python/boto are able to handle this request/response. This is a 3rd party S3 server, so I am unable to change the Expires response.

### Current Behavior

HeadObject fails to parse Expires tag with UTC format resulting in returning a failure

### Reproduction Steps

```
	info, err := client.HeadObject(context.Background(), &s3.HeadObjectInput{
		Bucket: &bucket,
		Key:    &object,
	})
```

and server response must include:
```
Expires: Thu, 01 Jan 1970 00:00:00 UTC
```

### Possible Solution

The issue appears to be smithy.ParseHTTPDate() is used for date parsing of known tags. And this is currently forcing only GMT timezone.  A suggested pull requests has been submitted here:
https://github.com/aws/smithy-go/pull/407

### Additional Information/Context

GMT is probably more correct per RFC, but since aws cli and others are successful handling this response I assume this should be considered a bug.

### AWS Go SDK V2 Module Versions Used

require (
	github.com/aws/aws-sdk-go-v2 v1.11.2
	github.com/aws/aws-sdk-go-v2/config v1.11.0
	github.com/aws/aws-sdk-go-v2/credentials v1.6.4
	github.com/aws/aws-sdk-go-v2/service/s3 v1.21.0
)

require (
	github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.0.0 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.8.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.0.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.5.0 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.5.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.9.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.6.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.11.1 // indirect
	github.com/aws/smithy-go v1.9.0 // indirect
)

### Compiler and Version used

1.19.4

### Operating System and version

linux amd64

**Comment by RanVaknin** [comment]
Hi @benmcclelland ,

This was [brought up recently](https://github.com/aws/aws-sdk/issues/434) and is due to the service accepting any arbitrary data as an argument and is wrong.
We have an internal ticket with the s3 service team to fix this.

I'm going to close this issue here in favor of tracking it in the original issue. Please comment or upvote on the original one so the impact of that would be noticable.

Thanks again!
Ran~
