### ISSUE TITLE
InitiateAuthRequest.Send() takes approximately 4 mins to complete

### ISSUE THREAD

**Issue by alwindoss** [aws/aws-sdk-go-v2#199]
I used the example here in the READMe: [cognito-srp](https://github.com/AlexRudd/cognito-srp/blob/master/README.md)
But, what I observe is it takes more than 4 mins for `Send` to complete.

Would you have pointers to what is going on here and what I am doing wrong.

Following is the dump of `go env`:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alwin/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alwin/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hb/9ds_k1_s47q5wj87wmp33snc0000gn/T/go-build037270247=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by jasdel** [comment]
Thanks for contacting us @alwindoss. I suggest enabling the SDK's debug logger which will log the HTTP request and response messages as they are sent. This debug logging will show if the SDK is attempting to retry the request to the service due to an error.

Update the client's `Config` to add the `LogLevel` value setting.
```go
	// configure cognito identity provider
	cfg, _ := external.LoadDefaultAWSConfig()
	cfg.LogLevel = aws.LogDebugWithHTTPBody | aws.LogDebugWithRequestRetries
	cfg.Region = endpoints.EuWest1RegionID
	cfg.Credentials = aws.AnonymousCredentials
	svc := cip.New(cfg)
```

**Comment by alwindoss** [comment]
I did that and the time between InitiateAuth request response was really long and contributes to the 4 mins delay.

```
2018/07/28 10:52:06 DEBUG: Request cognito-idp/InitiateAuth Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: cognito-idp.us-west-2.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.4 (go1.10.3; darwin; amd64)
Content-Length: 889
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth
Accept-Encoding: gzip


-----------------------------------------------------
2018/07/28 10:55:53 DEBUG: Response cognito-idp/InitiateAuth Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 2665
Content-Type: application/x-amz-json-1.1
Date: Sat, 28 Jul 2018 05:25:53 GMT
X-Amzn-Requestid: <REQUESTID>


-----------------------------------------------------
```

**Comment by alwindoss** [comment]
This seems fixed, should we close it?

**Comment by jasdel** [comment]
HI @alwindoss thanks for the update. It is possible that v0.12.0 fix to the SDK's request retry behavior could of improved the experience with this operation. The fixes in that release improved the SDK's ability to retry request errors, with back off delay being capped at a reasonable time. Before this change it is possible for the SDK's retry back off delay to take exceptionally long time.

I suggest updating to the latest version of the SDK to see you continue to see improved request delays.

**Comment by alwindoss** [comment]
@jasdel I used the latest version of the SDK and I didn't see this kind of delay. If you see fit you can close this issue.
