### ISSUE TITLE
Expose the missing SQS APIs CreateMoveTask and ListMoveTasks

### ISSUE THREAD

**Issue by fgm** [aws/aws-sdk-go-v2#1991]
### Describe the feature

The implementation of SQS DLS Redrive tasks rests on these two API calls:

- `CreateMoveTask(Source ARN: <arn>, TaskName: <UUID>)` to start the redrive, returning `Status`, `SourceARN`, `ApproximateNumberOfMessagesMoved`
- `ListMoveTasks(MaxResults: int, SourceARN: <arn>)` to report on the tasks, returning `NextToken`, `Results: { TaskName, Status, SourceARN, ApproximateNumberOfMessagesMoved }`

The SDK does not provide access to them, but it should.

### Use Case

I need to expose the DLQ Redrive mechanism in our back office with extra limitations, as our service agents do not have login access to the AWS Console.

Without that mechanism, which is the one used by the AWS Console, we would have to use client-side Receive / Produce / Delete operations on all messages, which is less efficient and O(n) API calls instead of O(1).

### Proposed Solution

Wrap the existing APIs, as used by the AWS Console

### Other Information

These APIs are not documented.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2@v1.17.3 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2@v1.17.3 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.17.3 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/aws-sdk-go-v2/credentials@v1.13.7
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.21
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.28
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.28
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.11
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/aws-sdk-go-v2/service/sts@v1.17.7
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/config@v1.18.7 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/credentials@v1.13.7 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/credentials@v1.13.7 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.21
github.com/aws/aws-sdk-go-v2/credentials@v1.13.7 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.28
github.com/aws/aws-sdk-go-v2/credentials@v1.13.7 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.11
github.com/aws/aws-sdk-go-v2/credentials@v1.13.7 github.com/aws/aws-sdk-go-v2/service/sts@v1.17.7
github.com/aws/aws-sdk-go-v2/credentials@v1.13.7 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/credentials@v1.13.7 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.21 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.21 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.21 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.27 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.28 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.21 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.21 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.21 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/sqs@v1.19.17 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/service/sqs@v1.19.17 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.27
github.com/aws/aws-sdk-go-v2/service/sqs@v1.19.17 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21
github.com/aws/aws-sdk-go-v2/service/sqs@v1.19.17 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.28 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.28 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.27
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.28 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.28 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.11 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.11 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.27
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.11 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.13.11 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.7 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.7 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.27
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.7 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.7 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.21
github.com/aws/aws-sdk-go-v2/service/sts@v1.17.7 github.com/aws/smithy-go@v1.13.5
github.com/aws/smithy-go@v1.13.5 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.5 github.com/jmespath/go-jmespath@v0.4.0

### Go version used

go version go1.19.4 darwin/arm64

**Comment by RanVaknin** [comment]
Hi @fgm ,

The AWS SDK clients are auto-generated from the respective Services' API model and the SDK team can't add / remove / expose operations that do not exist on the API model. 

With feature request like these I'd cut an internal ticket to the SQS team but I already see that they are working on adding these operations to the model. Unfortunately I cannot provide a timeline for the release but I suggest keeping an eye on their [announcements page](https://aws.amazon.com/blogs/aws/category/messaging/amazon-simple-queue-service-sqs/).

Thanks for your submission!
Ran~

**Comment by fgm** [comment]
@RanVaknin thanks for your fast answer, even though it is disappointing since these API do exist as the console uses them. But I guess you cannot do more than maybe notify the SQS team someone is actually needing those. Just in case they think no one does ;-) 

Beyond that, I went to the announcements page you linked, but it has no RSS/Atom feed: is there any way to subscribe to those announcements without getting drowned under all the AWS announcements for services I don't use ?
