### ISSUE TITLE
Not receiving ApproximateReceiveCount in Attributes of Message

### ISSUE THREAD

**Issue by sourabh-hotstar** [aws/aws-sdk-go-v2#2005]
### Describe the bug

When a message is received from SQS, no ApproximateReceiveCount is present in the attributes

### Expected Behavior

When a message is received from SQS, ApproximateReceiveCount should be present in the attributes

### Current Behavior

When a message is received from SQS, no ApproximateReceiveCount is present in the attributes

### Reproduction Steps

Send any message to SQS, check the attributes received in message.

### Possible Solution

Send the ApproximateReceiveCount in the attributes

### AWS Go SDK V2 Module Versions Used

1.42.45

### Compiler and Version used

go version go1.19.1 darwin/arm64

### Operating System and version

MacOS Monterey Version 12.6

**Comment by RanVaknin** [comment]
Hi @sourabh-hotstar ,

Can you please share your code to reproduce the issue?

Thanks,
Ran~

**Comment by sourabh-hotstar** [comment]
```messageOutput, err := sqs_client.GetMessages(awsSession, &queueURL, 15*60)
	if err != nil {
		log.Error().Err(err).Msg("Failed to retrieve messages...")
	} else {
		if nil != messageOutput {
			for _, message := range messageOutput.Messages {
                               approximateReceiveCount, ok := message.Attributes["ApproximateReceiveCount"]
                         }
                 }
        }

**Comment by sourabh-hotstar** [comment]
@RanVaknin Can you have a look at this?

**Comment by sourabh-hotstar** [comment]
@RanVaknin This is happening even with the current release as well.

**Comment by sourabh-hotstar** [comment]
@RanVaknin My Bad. The issue is with the aws-sdk-go and not v2. Thanks for helping.
