### ISSUE TITLE
File become corrupted after upload on s3

### ISSUE THREAD

**Issue by gdgcentrica** [aws/aws-sdk-go-v2#2011]
### Describe the bug

When i try to upload a file to s3 using either manager.Uploader.Upload or s3.Client.PutObject, the file become corrupted.

### Expected Behavior

The file uploaded to s3 must be identical to the one in input

### Current Behavior

Some parts on top or on bottom are missing (random behavior)  
[before.pdf](https://github.com/aws/aws-sdk-go-v2/files/10578833/before.pdf)
[after.pdf](https://github.com/aws/aws-sdk-go-v2/files/10578834/after.pdf)

### Reproduction Steps

```go
import (
	"bytes"
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"io"
	"log"
)
type S3Storage struct {
	accessKey string
	secret    string
	token     string
	region    string
	bucket    string
	client    *s3.Client
}


func NewS3Storage(accessKey string, secret string, token string, region string, bucket string) *S3Storage {
	return &S3Storage{
		accessKey,
		secret,
		token,
		region,
		bucket,
		nil,
	}
}

func (s *S3Storage) init() error {
	if s.client != nil {
		return nil
	}
	creds := credentials.NewStaticCredentialsProvider(s.accessKey, s.secret, s.token)
	_, err := creds.Retrieve(context.TODO())
	if err != nil {
		return ErrorInvalidCredentials
	}
	cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithRegion(s.region),
		config.WithCredentialsProvider(creds),
	)
	s.client = s3.NewFromConfig(cfg)
	return nil
}


func (s *S3Storage) UploadFileWithContentType(reader io.Reader, path string, contentType string) (string, error) {
	err := s.init()
	if err != nil {
		return "", err
	}

	_, err = s.client.PutObject(context.TODO(), &s3.PutObjectInput{
		Bucket:             aws.String(s.bucket),
		Key:                aws.String(path),
		Body:               reader,
		ACL:                "public-read",
		ContentType:        aws.String(contentType),
		ContentDisposition: aws.String("inline"),
	})
	if err != nil {
		log.Println("S3 upload error: " + err.Error())
		return "", err
	}
	return s.getUploadLocation(path), nil
}


func (s *S3Storage) UploadFileWithContentType2(reader io.Reader, path string, contentType string) (string, error) {
	err := s.init()
	if err != nil {
		return "", err
	}

	largeObject, _ := io.ReadAll(reader)
	buffer := bytes.NewReader(largeObject)
	uploader := manager.NewUploader(s.client, func(u *manager.Uploader) {
		u.PartSize = 10 * 1024 * 1024
		u.LeavePartsOnError = true
	})
	out, err := uploader.Upload(context.TODO(), &s3.PutObjectInput{
		Bucket:             aws.String(s.bucket),
		Key:                aws.String(path),
		Body:               buffer ,
		ACL:                "public-read",
		ContentType:        aws.String(contentType),
		ContentDisposition: aws.String("inline"),
	})
	if err != nil {
		log.Println("S3 upload error: " + err.Error())
		return "", ErrorUploadFails
	}
	return out.Location, nil
}

func (s *S3Storage) getUploadLocation(key string) string {
	url := "https://%s.s3.%s.amazonaws.com/%s"
	return fmt.Sprintf(url, s.bucket, s.region, key)
}


```

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.17.3
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.4.10
github.com/aws/aws-sdk-go-v2/config v1.18.11
github.com/aws/aws-sdk-go-v2/credentials v1.13.11
github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.21
github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.11.50
github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.27
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.21
github.com/aws/aws-sdk-go-v2/internal/ini v1.3.28
github.com/aws/aws-sdk-go-v2/internal/v4a v1.0.18
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.9.11
github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.1.22
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.21
github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.13.21
github.com/aws/aws-sdk-go-v2/service/s3 v1.30.1
github.com/aws/aws-sdk-go-v2/service/sso v1.12.0
github.com/aws/aws-sdk-go-v2/service/ssooidc v1.14.0
github.com/aws/aws-sdk-go-v2/service/sts v1.18.2

### Compiler and Version used

go version go1.19.4 linux/amd64

### Operating System and version

Ubuntu 22.04.1 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)

**Comment by gdgcentrica** [comment]
I've done another test, adding md5 hash of the file in the request
```go
func (s *S3Storage) UploadFileWithContentType2(reader io.Reader, path string, contentType string) (string, error) {
	err := s.init()
	if err != nil {
		return "", err
	}

	largeObject, _ := io.ReadAll(reader)
	largeBuffer := bytes.NewReader(largeObject)

	md5sum := md5.New()
	md5, err := md5sum.Write(largeObject)

	if err != nil {
		return "", err
	}

	uploader := manager.NewUploader(s.client, func(u *manager.Uploader) {
		u.PartSize = 10 * 1024 * 1024
		u.LeavePartsOnError = true
	})
	out, err := uploader.Upload(context.TODO(), &s3.PutObjectInput{
		Bucket:             aws.String(s.bucket),
		Key:                aws.String(path),
		Body:               largeBuffer,
		ACL:                "private",
		ContentType:        aws.String(contentType),
		ContentDisposition: aws.String("inline"),
		ContentMD5:         aws.String(string(md5)),
	})
	if err != nil {
		log.Println("S3 upload error: " + err.Error())
		return "", ErrorUploadFails
	}
	return out.Location, nil
}
```

Now the upload fail with this error: 
```
operation error S3: PutObject, exceeded maximum number of attempts, 3, https response error StatusCode: 500, RequestID: PA6JS9MDV85X4MC2, HostID: 1MMAFgQfzhYznEvXydkVU1m7SkCrRMpF91JfyIHyg7JcZpc5I8PTDIBbHYyco4W/enpuLyBAeIc=, api error InternalError: We encountered an internal error. Please try again.
```

**Comment by RanVaknin** [comment]
I'm missing context here as to which file you are uploading and how you are calculating the content type.
I would make some validations before  

As an experiment I uploaded the docker.dmg (500 mb) to s3, and downloaded it successfully (not corrupted) with this code:

```go
func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := s3.NewFromConfig(cfg)

	file, err := os.Open("/path/to/my/Docker.dmg")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	uploader := manager.NewUploader(client)
	uploader.PartSize = 10 * 1024 * 1024
	uploader.LeavePartsOnError = true

	_, err = uploader.Upload(context.Background(), &s3.PutObjectInput{
		Bucket: aws.String("testbucket"),
		Key:    aws.String("docker-copy.dmg"),
		Body:   file,
	})
	if err != nil {
		panic(err)
	}
}

```

My best guess is that when you are calculating the content type you are reading through the body of your file, reaching EOF without using the seek method to walk back to the beginning of the file.

Let me know if this helps.
Thanks,
Ran~

**Comment by gdgcentrica** [comment]
Hi @RanVaknin, thank you for your reply.

The content type is passed to the function without reading the file, because in the software i'm developing i need to upload only pdf, jpeg and png files generated at runtime, so i already know the value without reading it.

This bug is giving me headache:
I've spent a day to search the problem in my code, because the same code works fine in another software i've done, so i was thinking i was the problem. 

The differences here are in the os (Ubuntu 20 instead of 22) the go version (1.19.2) and in the aws sdk version (1.17.1).

The ultimate reason why i opened this issue is because if i send back the file as it is, just before the call of uploader.Upload function, the file is fine, so i'm sure the corruption happens on the library side. 

You can also see the difference between the two files on the attachments: some peaces are missing. To me seams like something going wrong in the chunking and transmission of the file.

**Comment by RanVaknin** [comment]
Hi @gdgcentrica ,

Thanks for the clarification. I'm not sure why you are seeing the corruption. I've tested the your code using the "before" pdf both with the upload manager, and the direct putObject command, and have not seen any corruption happening. 

The only difference is that in my call is that I dont specify `ACL: "public-read"` , for security purposes I can't provision a resource that is open to the internet. 

Can you try to put the object without that ACL argument? In addition it would help to see your logs, so if you can share them that would be insightful. Just make sure to remove sensitive information. You can enable logs the following way:
```go
cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithRegion(s.region),
		config.WithCredentialsProvider(creds),
                config.WithClientLogMode(aws.LogRequest | aws.LogResponseWithBody))
```

Please let me know what you find.
Thanks,
Ran~

**Comment by gdgcentrica** [comment]
This is the log content when i upload the same file without ACL in configuration:
(asterisks are in place of my sensitive informations)
```
SDK 2023/02/07 15:42:31 DEBUG Request
PUT /****/pdf/63e271675fbbf097b8d5e39a.pdf?x-id=PutObject HTTP/1.1
Host: ****.s3.eu-west-1.amazonaws.com
User-Agent: aws-sdk-go-v2/1.17.3 os/linux lang/go/1.19.4 md/GOOS/linux md/GOARCH/amd64 api/s3/1.30.1 ft/s3-transfer
Content-Length: 71921
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: f977a3af-6d89-4471-95e3-1222b1620061
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=********/20230207/eu-west-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;content-disposition;content-length;content-type;host;x-amz-content-sha256;x-amz-date, Signature=61c3bb166ad460995ec504dd14476e94d13c331dd77e8eb5e6eedf7459e2250c
Content-Disposition: inline
Content-Type: application/pdf
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20230207T154231Z

SDK 2023/02/07 15:42:31 DEBUG Response
HTTP/1.1 200 OK
Content-Length: 0
Date: Tue, 07 Feb 2023 15:42:32 GMT
Etag: "00c8bb55a6fbaa6d33b00b9dfe1017a3"
Server: AmazonS3
X-Amz-Id-2: 2xlnYtg1wZiHw0sjxdsNmTwZvnECzZHfWPIksCWdccuCAmadRkxcqkeeQn3DUq43ijTHioewvUY=
X-Amz-Request-Id: Q6JAFY2WJ8TF8AXF
X-Amz-Server-Side-Encryption: AES256
```

The file after the upload is corrupted.

Meanwhile i switched to the client side js aws sdk for browser, but if possible i would like to switch back to a server side solution

Thanks

**Comment by RanVaknin** [comment]
Hi @gdgcentrica ,

Thanks for the logs. I don't see anything that raises my suspicion. Im not sure why you are seeing corrupted data.

How are you downloading your file? Through the console? with a getObject call using the SDK? you said you are using a web environment, can you try doing this just by running all of these locally? Do you have any more info that you can provide in terms of trying to reproduce this?

Another thing you can try is specifying a checksum algorithm to ensure data integrity on s3 by doing the following:

```go
	_, err = uploader.Upload(context.Background(), &s3.PutObjectInput{
		Bucket: aws.String("testbucket"),
		Key:    aws.String("docker-copy.dmg"),
		Body:   file,
		ChecksumAlgorithm:  types.ChecksumAlgorithmSha256,
	})
```

If you are using the console it should look something like this:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/50976344/217343211-26bab090-9e22-40cc-81e0-758989269bbc.png">

Thanks,
Ran~
