### ISSUE TITLE
Encryption/Decryption for LastEvaluatedKey

### ISSUE THREAD

**Issue by sbilello** [aws/aws-sdk-go-v2#2018]
### Describe the feature

When exposing the `LastEvaluatedKey` parameter `map[string]types.AttributeValue` via API such parameter could be manipulated by the client and expose DynamoDB to Security SQL Injection Attacks.
There are many implementations around like this one: [dynamodb-paginator](https://github.com/supersoniko/dynamodb-paginator#security-disclaimer)

### Use Case

It would facilitate the development if I don't have to deal with encryption/decryption and marshaling/unmarshaling from Json/DynamoDB to struct types.

### Proposed Solution

I created an *almost* straightforward  solution and [Go PlayGround With Encrypt/Decrypt](https://go.dev/play/p/MkD5bN3cznD) due to some unmarshaling issue for `map[string]types.AttributeValue`

```
func DecryptToLastEvaluatedKey(input string) (map[string]types.AttributeValue, error) {
	cryptBytes := cryptkeeper.CryptBytes{Bytes: []byte(input)}
	err := cryptBytes.UnmarshalJSON([]byte(input))
	if err != nil {
		log.Error().Err(err).Msg("It was not possible to decrypt: " + string(cryptBytes.Bytes))
		panic(err)
	}
	var decodeJson map[string]interface{}
	err = json.Unmarshal(cryptBytes.Bytes, &decodeJson)
	if err != nil {
		log.Error().Err(err).Msg("It was not possible to deserialize: " + string(cryptBytes.Bytes))
		panic(err)
	}
	var decodedExclusiveStartKey = convertToExclusiveStartingKey(decodeJson)
	if err != nil {
		log.Error().Err(err).Msg("It was not possible to decode: " + string(cryptBytes.Bytes))
		panic(err)
	}
	return decodedExclusiveStartKey, nil
}
func convertToExclusiveStartingKey(input map[string]interface{}) map[string]types.AttributeValue {
	var result = make(map[string]types.AttributeValue, len(input))
	for key, value := range input {
		for _, innerValue := range value.(map[string]interface{}) {
			attributeValue, err := attributevalue.Marshal(innerValue)
			if err != nil {
				log.Err(err).Msg(fmt.Sprintf("It was not possible to marshal %#v", attributeValue))
			}
			result[key] = attributeValue
		}
	}
	return result
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

```
	github.com/aws/aws-sdk-go-v2 v1.17.4
	github.com/aws/aws-sdk-go-v2/config v1.18.12
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.10.11
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.18.2
```

### Go version used

1.19

**Comment by RanVaknin** [comment]
Hi @sbilello ,

Thanks for the raising the feature request. 

I discussed this with the team and at this point there is no plans to implement this.

I appreciate you taking the time, and hope you are not discouraged to raise additional PRs in the future. We go through and consider all of them.

All the best,
Ran~
