### ISSUE TITLE
Add support for recursion detection

### ISSUE THREAD

**Issue by aajtodd** [aws/aws-sdk-go-v2#2025]
### Describe the feature

Implement support for the recursion detection SEP

### Use Case

see `recursion-detection.md` SEP

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

N/A

### Go version used

N/A

**Comment by lucix-aws** [comment]
Completed by #2105
