### ISSUE TITLE
Support io.Writer in s3 transfer manager downloader

### ISSUE THREAD

**Issue by aajtodd** [aws/aws-sdk-go-v2#2036]
### Describe the feature

Currently the s3 transfer manager only allows taking an `io.WriterAt` target for where to write the response body. This feature request is to add an API that supports `io.Writer` directly. 

### Use Case

See use cases laid out in community PRs:

https://github.com/aws/aws-sdk-go-v2/pull/1301
https://github.com/aws/aws-sdk-go-v2/pull/1742

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

N/A

### Go version used

N/A

**Comment by lucix-aws** [comment]
Will be OBE by addressing #2247 (joining a reader to a writer is trivial)
