### ISSUE TITLE
aws/external: Resolver not using the default path for AWS_SHARED_CREDENTIALS_FILE when not defined as environment var

### ISSUE THREAD

**Issue by chrisgoffinet** [aws/aws-sdk-go-v2#204]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
master

### Version of Go (`go version`)?
1.10

### What issue did you see?
Noticed that on MacOS when not setting `AWS_SHARED_CREDENTIALS_FILE`,  the sdk no longer tries to look for the default path defined using `DefaultSharedCredentialsFilename` in the `shared_config.go`.

### Steps to reproduce

Here a basic example of using the SDK to check if a bucket exists. I have an `AWS_PROFILE` environment set, but not setting the `AWS_SHARED_CREDENTIALS_FILE`.

```
package main

import (
	"log"

	"github.com/aws/aws-sdk-go-v2/aws/external"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

func main() {
	bucket := "test"
	cfg, err := external.LoadDefaultAWSConfig()
	if err != nil {
		log.Fatal("unable to load SDK config, " + err.Error())
	}
	cfg.Region = "us-east-2"

	svc := s3.New(cfg)
	req := svc.HeadBucketRequest(&s3.HeadBucketInput{Bucket: &bucket})
	_, err = req.Send()
	if err != nil {
		log.Fatal(err)
	}
}
```

Output
```
AWS_PROFILE=myprofile go run main.go
2018/07/21 20:58:33 EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/iam/security-credentials: EOF
exit status 1
```

If this is an expected scenario, please close. As a new user of the SDK, this was not very clear on what was going wrong until diving into the code and tracing why it trying to make a call to http://169.251.169.254/ ....

Maybe as an improvement of developer experience, it could to try to use the default path to look when going through the resolvers?

**Comment by jasdel** [comment]
Thanks for reaching out to us @chrisgoffinet. The SDK should be using the `external.DefaultSharedCredentialsFilename` to retrieve the shared credentials file path if the `AWS_SHARED_CREDENTIALS_FILE` env var is not set. The env var should be overriding where the SDK retrieves the shared credential filename path from.

I'm having difficulty reproducing this on my end. Could you checkout the following example in your environment to see what kind of output it returns?

Could you check what path the `external.DefaultSharedCredentialsFilename` helper is returning, if called directly?  Does this correspond the the shared credential file you're expecting to be loaded?

The following program will print out the default filepath, and the env var's override path. Then the paths will be checked to see if the file at the destination exists.  Finally the credentials error or success will be show with the source filepath they were loaded.

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/aws/aws-sdk-go-v2/aws/external"
)

func main() {
	filepath := external.DefaultSharedCredentialsFilename()
	fmt.Println("DefaultSharedCredentialsFilename:", filepath)
	info, err := os.Stat(filepath)
	if err != nil {
		fmt.Printf("unable to open default filename: %s, %v\n", filepath, err)
	} else {
		fmt.Println("default filename found:", filepath, info.Size())
	}

	envCfg, _ := external.NewEnvConfig()
	filepath = envCfg.SharedCredentialsFile
	fmt.Println("AWS_SHARED_CREDENTIALS_FILE:", filepath)
	info, err = os.Stat(filepath)
	if err != nil {
		fmt.Printf("unable to open env var override: %s, %v\n", filepath, err)
	} else {
		fmt.Println("env var override found:", filepath, info.Size())
	}

	fmt.Println()

	cfg, err := external.LoadDefaultAWSConfig()
	if err != nil {
		log.Fatal("unable to load SDK config, " + err.Error())
	}
	cfg.Region = "us-east-2"

	creds, err := cfg.Credentials.Retrieve()
	if err != nil {
		log.Fatalf("unable to load credentials, %v", err)
	}

	fmt.Println("Credentials:", creds.Source, "HasKeys:", creds.HasKeys())
}
```

**Comment by chrisgoffinet** [comment]
Here is the output from the script above:

```
DefaultSharedCredentialsFilename: /Users/chrisg/.aws/credentials
default filename found: /Users/chrisg/.aws/credentials 344
AWS_SHARED_CREDENTIALS_FILE:
unable to open env var override: , stat : no such file or directory

2018/07/23 13:53:27 unable to load credentials, EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/iam/security-credentials: EOF
exit status 1
```

**Comment by jasdel** [comment]
Thanks for the update @chrisgoffinet It looks like the SDK is trying to use the `/Users/chrisg/.aws/credentials` file for credentials. Does this file contain the `profile` you expect your application to use?  If a profile name is not specified via the `AWS_PROFILE` environment variable or directly in your application's code, the SDK will use `default` as the profile name.

**Comment by chrisgoffinet** [comment]
Yes it does exist. When running your code, I put in `AWS_PROFILE=myprofile go run main.go`, and it still errors out. Thats the issue I was running into from my test app as well. Even though I set the profile through `AWS_PROFILE`, it still looks to not be looking at ` /Users/chrisg/.aws/credentials`. It's not only until I set `AWS_SHARED_CREDENTIALS_FILE` will it work with my profile

**Comment by jasdel** [comment]
Thanks for the update @chrisgoffinet, and glad the issue was resolved.

If any of the environment variables for the shared files are set the SDK will [use that that file and not include the default fallback file paths](https://github.com/aws/aws-sdk-go-v2/blob/295bebb2e006e56d9f914d2680d7a9edafe45405/aws/external/shared_config.go#L158-L164). This is being performed with the assumption that a set environment variable means the SDK should load files from that environment variable. If both `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` are set the [shared credential file should have precedence](https://github.com/aws/aws-sdk-go-v2/blob/59346b26df55278cc60f47b08f056cad7377c207/aws/external/env_config.go#L208).
