### ISSUE TITLE
dynamodb/attributevalue: allow registration of custom type marshal/unmarshal functions

### ISSUE THREAD

**Issue by ztison** [aws/aws-sdk-go-v2#2042]
### Describe the feature

As a DynamoDB user, I want to be able to register custom marshaler/unmarshaler functions. 

### Use Case

- I want to have common API types not coupled with the repository layer. So I don't want to implement  `MarshalDynamoDBAttributeValue` and `UnmarshalDynamoDBAttributeValue` functions with dependency on `AttributeValue` in my high-level code.

- I want to implement custom marshaler/unmarshaler for types that  I don't own. It can be required because of data masking or to omit empty values.

### Proposed Solution

```
func (e *Encoder) RegisterMarshaller(t reflect.Type, f func(interface{}) (types.AttributeValue, error)) error
func (d *Decoder) RegisterUnmarshaller(t reflect.Type, f func(types.AttributeValue) (interface{}, error)) error
```

```
type Foo string

func StringMarshaller(value interface{}) (types.AttributeValue, error) {
	if foo, ok := value.(Foo); ok {
		return &types.AttributeValueMemberS{Value: string(foo)}, nil
	}
	return nil, fmt.Errorf("type error")
}

var foo = "foo"
enc.RegisterMarshaller(reflect.TypeOf(foo), StringMarshaller)
```

### Other Information

Based on [customer marshaler/unmarshaler for json](https://github.com/golang/go/issues/5901)

### Rejected Alternatives

API without exposing reflect:
```
func (e *Encoder) RegisterFunc(f interface{})
func (d *Decoder) RegisterFunc(f interface{})
```

API based on generics:
```
func (e *Encoder)  Register[T any](f func(T) (types.AttributeValue, error)) { ... }
func (d *Decoder)  Register[T any](f func(types.AttributeValue) (T, error)) { ... }

```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.14
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.39
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.18.4
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.14.4

### Go version used

go version go1.19.5 darwin/arm64

**Comment by raulvc** [comment]
so.. turns out this still isn't a thing, could you point me to a fork/custom implementation of an attributevalue encoder/decoder that allows me to register a uuid type?

**Comment by ztison** [comment]
> 

Just closed PR exists https://github.com/aws/aws-sdk-go-v2/pull/2060/files

**Comment by RanVaknin** [comment]
Hi all, thank you for your patience. At this point in time, there is no plan to implement this. We are aware that there discussions happening on the standard library level, and we want to see how this is developing before taking any action on it from our side.

I hope we can revisit this sooner than later.
Thanks,
Ran~

**Comment by ashwinrs** [comment]
+1 to @ztison proposal on how to ideally expose custom marshaler/unmarshaller. The existing interface makes the code extremely verbose and complex. 

For example, we use go generics when interacting with DynamoDB. DynamoDB [does not handle `structpb.Struct` well](https://github.com/aws/aws-sdk-go/issues/3208). So the way we now have to handle it is, basically, iterate over every field in all the structs to check if its `structpb.Struct` and then do additional handling. It would be a lot cleaner with the approach @ztison proposed.

**Comment by austince** [comment]
I work with @ztison, we were ultimately forced to fork
