### ISSUE TITLE
S3 | `CopyObject`,` GetObject`, `PutObject` | SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by rhighs** [aws/aws-sdk-go-v2#2049]
### Describe the bug

I think I've spent almost an entire day on this. I don't really think this is a bug, it might be a documentation issue, as I'm quite sure I'm missing some sort of parameter in the sdk's requests input config. But trying to do a simple `CopyObject` on a given bucket (of which I checked it is formatted properly) with SSE set to AES256 would always result in the following error:

`operation error S3: CopyObject, https response error StatusCode: 403 api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

After that I had the brilliant idea do emulate a copy behavior by doing `GetObject` and then `PutObject`, which isn't that convenient but did what I wanted. To my surprise, the same error occurred: `operation error S3: GetObject, https response error StatusCode: 403 api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`, just for the sake of it, it went on trying with `PutObject` and guess what?

`operation error S3: PutObject, https response error StatusCode: 403 api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

Instead! trying a CopyObject command using the aws cli works flawlessly how's that?

`aws s3 cp <s3SourceUri> <s3DestUri>`

### Expected Behavior

I want the operations listed above to work as intended, Just like the cli does.

### Current Behavior

`operation error S3: <Copy|Get|Put>Object, https response error StatusCode: 403 api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

### Reproduction Steps

Its quite easy to reproduce this, just create a client using a default config (yes I do have credentials set up properly on my machine) and perform a `CopyObject` (this would happen for `GetObject` and `PutObject` as well)

```go
package main

import (
    "fmt"
    "log"
    "context"

    "github.com/aws/aws-sdk-go-v2/aws"
    "github.com/aws/aws-sdk-go-v2/config"
    "github.com/aws/aws-sdk-go-v2/service/s3"
    "github.com/aws/aws-sdk-go-v2/service/s3/types"
)

func main() {
    fromBucket := "some_bucket_name"
    fromKey := "some_bucket_key"
    toBucket := "some_bucket_name_"
    toKey := "some_bucket_key_"

    ctx := context.Background()
    awsConfig, err := config.LoadDefaultConfig(ctx, config.WithRegion("cool-region-here"))
    if err != nil {
        log.Fatal(err)
    }
    client := s3.NewFromConfig(awsConfig)

    copySource := fmt.Sprintf("%s/%s", fromBucket, fromKey)
    _, err = client.CopyObject(ctx, &s3.CopyObjectInput{
        Bucket: aws.String(toBucket),
        CopySource: aws.String(copySource), // I tried url.QueryEscape(aws.String(copySource)) as well
        Key: aws.String(toKey),
        ServerSideEncryption: types.ServerSideEncryptionAes256,
    })

    if err != nil {
        log.Fatal(err) // Halts here
    }
}

```

### Possible Solution

I've seen people trying out with different values for the `ACL` parameter in `CopyObjectInput`, I did that too with no success though.

### Additional Information/Context

I have both read and write access to the buckets I'm trying to copy from/to

### AWS Go SDK V2 Module Versions Used

1.17.5

### Compiler and Version used

go version go1.20 linux/amd64

### Operating System and version

6.1.12-1-MANJARO

**Comment by RanVaknin** [comment]
Hi @rhighs 

We have Go v1 code documented [here](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/go/example_code/s3/s3_copy_object.go) It should be almost identical.

Additionally I ran the following from my local machine successfully:
```go
func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogResponseWithBody|aws.LogRequestWithBody))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := s3.NewFromConfig(cfg)
	item := "hey.txt"
	copied, err := client.CopyObject(context.Background(), &s3.CopyObjectInput{
		Bucket:     aws.String("destinationBucket"),
		CopySource: aws.String("originBucket/" + item),
		Key:        aws.String("new-hey.txt"),
		ServerSideEncryption: types.ServerSideEncryptionAes256,
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(copied.ResultMetadata)
}
```

In my config setup I have the request and response logs enabled. If my code snippet doesn't help, you can enable the same debug flags and inspect the raw http request structure to make sure the constructed request looks correct. If you are not sure, you can share that here, just make sure to redact any sensitive info like credentials. 

For example:

```console
SDK 2023/03/09 10:41:29 DEBUG Request
PUT /new-hello.txt?x-id=CopyObject HTTP/1.1
Host: destinationBucket.s3.us-east-1.amazonaws.com
User-Agent: aws-sdk-go-v2/1.17.3 os/macos lang/go/1.19.1 md/GOOS/darwin md/GOARCH/arm64 api/s3/1.30.1
Content-Length: 0
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: REDACTED
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20230309/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-server-side-encryption, Signature=REDACTED
X-Amz-Content-Sha256: REDACTED
X-Amz-Copy-Source: originBucket/hey.txt
X-Amz-Date: 20230309T184129Z
X-Amz-Server-Side-Encryption: AES256
```

Additionally since you mentioned the same request is working on the CLI, you can run the same command with the `--debug` flag, and you should get a similar log of the raw http request. You can compare between the two and see where the discrepancy is.

Thanks,
Ran~

**Comment by rhighs** [comment]
Hey there @RanVaknin, I did as you said and the tow logs do differ as you expected. It seems the `Host:` value in the request header is getting set for some reason.

```SDK 2023/03/10 14:53:04 DEBUG Request
PUT <WHOLE_COPY_SOURCE_HERE>?x-id=CopyObject HTTP/1.1
Host: s3.eu-west-1.amazonaws.com // <---- Destination is not present??
User-Agent: aws-sdk-go-v2/1.17.5 os/linux lang/go/1.20 md/GOOS/linux md/GOARCH/amd64 api/s3/1.30.5
Content-Length: 0
Accept-Encoding: identity
```

Also why is it using the whole copy source for the `PUT` resource path? shouldn't it be only using the `toKey` bucket value instead? the code I've used is the same as the one above. Thank you

**Comment by RanVaknin** [comment]
Hi @rhighs ,

Thanks for the follow-up, this is indeed interesting. 

I used the code you provided verbatim and its working perfectly. 
My suspicion is that you are providing either a key or a bucket name that doesn't comply with the [s3 naming guidelines](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html). Since you redacted that information I can only speculate.

Can you share that info with us? 

Thank you,
Ran~

**Comment by rhighs** [comment]
Unfortunately this is not information I can share with you here. However, with further investigation I found the error, for some reason a tool I was using to parse s3 urls was failing and never really split urls into their components (bucketname and key). It would give me a bucketname+some garbage and a key+some garbage hence the error.

Thank you for your help @RanVaknin :^)
