### ISSUE TITLE
SDK development status?

### ISSUE THREAD

**Issue by mxk** [aws/aws-sdk-go-v2#206]
Has this SDK been abandoned or is there still active development happening in the background somewhere? I ask because there are many design-related TODOs in the source and issues here on GitHub that don't seem to be making any progress. Is there a timeline for when this SDK will reach production-ready state?

I started using this SDK a few months ago and the changes that were made so far have been a great improvement on v1 (particularly client config handling and the credentials interface), but the lack of further progress is making me a bit worried about using this SDK for further development without clarification of what its eventual fate may be.

Thanks!

**Comment by jasdel** [comment]
Hi @mxk thanks for reaching out to us. Don't worry the v2 SDK is still active. We're actively working through the design TODOs internally for how the SDK's request lifecycle should be refactored, along with error handling.  We'll update the Github Issues with our ideas for the community to provide feedback.

Also thanks for the feedback on the configuration, and credentials updates. Let us know any additional feedback or ideas you have for the v2 SDK.
