### ISSUE TITLE
Presigned URL for PUT with ContentType but no ContentLength results in URL that doesn't include ContentType in the signed headers

### ISSUE THREAD

**Issue by ieguinoa** [aws/aws-sdk-go-v2#2063]
### Describe the bug

Signing a PUT URL with a ContentType value results in a signed URL without Content-Type included in the signed headers unless a ContentLength is also specified.

### Expected Behavior

When signing a request with ContentType but no ContentLength I expect to have the signed URL containing content-type but no content-length in the 

### Current Behavior

There is no content-type in the signed headers (X-Amz-SignedHeaders). The type header is silently removed from the request.

### Reproduction Steps

  const contentType = "text/plain"
  in := &s3.PutObjectInput{
          Bucket: aws.String(bucket),
          Key:    aws.String(key),
          ContentType: aws.String(contentType),
  }
  p, _ := s3.NewPresignClient(client).PresignPutObject(ctx, in)
  fmt.Println(p.URL)

### Possible Solution

The problem is [here](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/transport/http/content_type.go#L30), where it silently removes the content-type when content-length is == 0. 
Ideally there should be a way to remove this RemoveContentTypeHeader middleware from the stack, or define a value of content-length that could escape that condition, may not be a clean solution but content-length=-1 could be a value that the user can specify to indicate they know the type but not the length of the content.

### Additional Information/Context

This bug was reported before  #1475 but no solution was given for the case when you don't know the length value, so you don't want to specify that header at all.

### AWS Go SDK V2 Module Versions Used

v1.17.6

### Compiler and Version used

1.20

### Operating System and version

Ventura 13.2.1

**Comment by RanVaknin** [comment]
Hi @ieguinoa ,

>The problem is [here](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/transport/http/content_type.go#L30), where it silently removes the content-type when content-length is == 0.

This is by design, this isn't a bug. Like I mentioned before in the issue you have linked, you must to supply content length to presigned url request if you are specifying content-type.

Ran

**Comment by ieguinoa** [comment]
Hi @RanVaknin and @isaiahvita,

Thanks for the response.
I think the solution you proposed [here](https://github.com/aws/aws-sdk-go-v2/issues/1475#issuecomment-1306232029)  does not apply to our case.
In our use case we don't know the contentLength value (therefore we can't use any fixed value and sign the url with it) but we do know the content type, and we want to enforce it during the uploading by adding it to the signed contents so we can be sure the uploader will upload content with that type.
Is there a way to make use of the sdk for this case?

Ignacio

**Comment by isaiahvita** [comment]
Hi @ieguinoa 

Thanks for the engagement. When it comes to presigned URLs we tend to bias towards removing potentially extraneous headers that would make it harder for customers to configure. Conceptually, presigned URLs are meant to be self-contained requests that will "just work" without need for modification. 
While we agree that your use case seems like a valid one, we are going to have to be careful about outright removal of the `RemoveContentTypeHeader` middleware from this operation due to backwards compatibility concerns. We will keep your use case in mind as we reevaluate this in the future.

In the meantime, you can actually customize this behavior for your particular use case by providing a custom client option 

```
package main

import (
	"bytes"
	"context"
	"log"
	"net/http"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)


func main() {

	ctx := context.Background()
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion("us-west-2"), config.WithClientLogMode(aws.LogRequest|aws.LogSigning))

	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	s3Client := s3.NewFromConfig(cfg)
	presignClient := s3.NewPresignClient(s3Client)
	requestBody := []byte("foo")

	presignResp, _ := presignClient.PresignPutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String("PLACEHOLDER_BUCKET"),
		Key:    aws.String("PLACEHOLDER_FILENAME"),
	},
	func(o *s3.PresignOptions) {
		o.ClientOptions = append(o.ClientOptions, func(o *s3.Options) {
			 o.APIOptions = append(o.APIOptions, smithyhttp.AddHeaderValue("Content-Type", "text/plain"))
		})
	})

	req, _ := http.NewRequest(http.MethodPut, presignResp.URL, bytes.NewBuffer(requestBody))
	req.Header.Set("Content-Type", "text/plain")
	client := &http.Client{}
	client.Do(req)

}

```

**Comment by ieguinoa** [comment]
Thanks for the response @isaiahvita, that approach did the trick for now.
