### ISSUE TITLE
Unable to create ECS service with ServiceRegistries

### ISSUE THREAD

**Issue by khanhtc1202** [aws/aws-sdk-go-v2#2064]
### Describe the bug

I want to use `ecs.CreateService` but when creating ECS service with `service.ServiceRegistries` provided, an error is returned as below

> Failed to apply service customer-api: failed to create ECS service customer-api: failed to create ECS service customer-api: operation error ECS: CreateService, https response error StatusCode: 400, RequestID: 1dc9e85b-2373-4aa2-a369-c8ece8ccca8a, InvalidParameterException: ServiceRegistries must be empty or null.

Throw the CreateServiceInput struct contains the ServiceRegistries field (ref: https://github.com/aws/aws-sdk-go-v2/blob/main/service/ecs/api_op_CreateService.go#L324-L329). And my service definition contains ServiceRegistries config that follows the ServiceRegistries struct definition

```
   "serviceRegistries": [ 
      { 
         "containerName": "string",
         "containerPort": number,
         "port": number,
         "registryArn": "string"
      }
   ],
```

### Expected Behavior

Be able to create ECS service in case of ServiceRegistries is provided.

### Current Behavior

Can not create ECS service which provides ServiceRegistries config.

### Reproduction Steps

ref: https://github.com/pipe-cd/pipecd/blob/master/pkg/app/piped/platformprovider/ecs/client.go#L92

### Possible Solution

If a newer version solves this problem, please tell me the version number.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.6.0
github.com/aws/aws-sdk-go-v2/tree/master/service/ecs v1.1.1

### Compiler and Version used

1.19

### Operating System and version

MacOS 11.4

**Comment by RanVaknin** [comment]
Hi @khanhtc1202 ,

Can you please share the following:
- your full code snippet including imports and config initialization
This would help us set up a repro and validate your concern.

- your request logs with body. 
This can help us see if the request body is not being serialized correctly. 
You can enable debug logs by doing the following:

```go
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogRequestWithBody))

```
Just make sure to redact any sensitive information like your credentials and the signature.

Thanks,
Ran~
