### ISSUE TITLE
Shield API doesn't work in eu-west-1 region

### ISSUE THREAD

**Issue by Loofort** [aws/aws-sdk-go-v2#208]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2.0.0-preview.4

### Version of Go (`go version`)?
code deployed as a aws lambda with
Runtime: go1.x
(assume, it is 1.10)

### What issue did you see?
Calling shield API get error: 
"RequestError: send request failed caused by: Post https://shield.eu-west-1.amazonaws.com/: dial tcp: lookup shield.eu-west-1.amazonaws.com on 169.254.169.253:53: no such host"

looks like shield endpoint URL is impacted by region,

### Steps to reproduce
try to execute https://godoc.org/github.com/aws/aws-sdk-go-v2/service/shield#CreateProtectionRequest within lambda deployed to eu-west-1

**Comment by jasdel** [comment]
Thanks for reaching out to us @Loofort. the AWS Shield Advanced service is only available in `us-east-1` region. It is not available in the `eu-west-1` region. You can provide your feedback on the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=238&start=0) for this service, requesting additional regional support.

https://docs.aws.amazon.com/general/latest/gr/rande.html#shield_region

**Comment by Loofort** [comment]
Hi @jasdel , sorry for reopening this but  
According to AWS page https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ the Advanced Shield is available in eu-west-1 (Ireland) particularly and it is global in general.

My understanding is since the service is global it provides the only one access point , that is shield.us-east-1.amazonaws.com
Shouldn't the SDK distinct region-specific services from global, and correctly routes requests ?

**Comment by jasdel** [comment]
Thanks for pointing out the other doc @Loofort. I think there is a disconnect in this documentation. I'll reach out further to see where this service is supported.

**Comment by jasdel** [comment]
@Loofort I looked into the AWS Shield service in more detail. The service's control plane API is only accessible in the `us-east-1` region.  The service can be configured for other regions that are supported via the [Region Table](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/), using the [CreateProtection](https://docs.aws.amazon.com/sdk-for-go/api/service/shield/#CreateProtectionInput). But, the service can only be controlled via the `us-east-1` region. The `us-east-1` region is the "global" endpoint for controlling this service.

**Comment by Loofort** [comment]
ok, thank you for the clarification.

**Comment by jasdel** [comment]
let us know if you have additional questions, or feedback. We're always glad to review PRs and Github issue and feature requests.
