### ISSUE TITLE
DBInstanceAvailableWaiter silently fails without rds:DescribeDBInstances permissions

### ISSUE THREAD

**Issue by threesquared** [aws/aws-sdk-go-v2#2080]
### Describe the bug

When using the DBInstanceAvailableWaiter to wait for a RDS instance to be modified I was constantly getting the error `exceeded max wait time for DBInstanceAvailable waiter` even though I could verify the changes had been made successfully. 

It was only after [enabling](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/logging/#clientlogmode) client request and response logging. It was possible to see the `is not authorized to perform: rds:DescribeDBInstances on resource` messages being returned from the API.

### Expected Behavior

Exceptions should not be swallowed and any issues in checking the status of the instance should be surfaced as an error.

### Current Behavior

The waiter behaves as if the condition has not been met and continues to retry until it times out.

### Reproduction Steps

If you run the following with `rds:ModifyDBInstance` but not `rds:DescribeDBInstances` permissions it will look like the waiter times out waiting for the condition.

```go
DBInstanceIdentifier := "rds-identifier"
password := "new-password"

dbDetails, err := rdsClient.ModifyDBInstance(context.TODO(), &rds.ModifyDBInstanceInput{
  DBInstanceIdentifier: aws.String(DBInstanceIdentifier),
  ApplyImmediately:     true,
  MasterUserPassword:   aws.String(password),
})
if err != nil {
  return fmt.Errorf("failed to modify the instance: %v", err)
}

waiter := rds.NewDBInstanceAvailableWaiter(rdsClient)
maxWaitTime := 5 * time.Minute

err = waiter.Wait(context.TODO(), &rds.DescribeDBInstancesInput{
  DBInstanceIdentifier: dbDetails.DBInstance.DBInstanceIdentifier,
}, maxWaitTime, func(options *rds.DBInstanceAvailableWaiterOptions) {
  options.LogWaitAttempts = true
})
if err != nil {
  return fmt.Errorf("error waiting for instance to be modified: %v", err)
}
```

### AWS Go SDK V2 Module Versions Used

```
github.com/aws/aws-sdk-go-v2 v1.17.7
github.com/aws/aws-sdk-go-v2/config v1.18.5
github.com/aws/aws-sdk-go-v2/service/rds v1.42.0
```

### Compiler and Version used

go version go1.19.1 darwin/arm64

### Operating System and version

MacOS 12.6

**Comment by RanVaknin** [comment]
Hi @threesquared ,

The issue is with how you are error handling.

Fixing your code to this:

```diff
dbDetails, err := rdsClient.ModifyDBInstance(context.TODO(), &rds.ModifyDBInstanceInput{
  DBInstanceIdentifier: aws.String(DBInstanceIdentifier),
  ApplyImmediately:     true,
  MasterUserPassword:   aws.String(password),
})
- if err != nil {
-  return fmt.Errorf("failed to modify the instance: %v", err)
- }
+ if err != nil {
+   panic(err)
+ }
```

Will result in the error bubbling up correctly:
```
panic: operation error RDS: ModifyDBInstance, https response error StatusCode: 403, RequestID: REDACTED, api error AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/REDACTED/aws-go-sdk-REDACTED is not authorized to perform: rds:ModifyDBInstance on resource: arn:aws:rds:us-east-1:REDACTED:db:delete-me-later-db because no identity-based policy allows the rds:ModifyDBInstance action
```

Thanks,
Ran~
