### ISSUE TITLE
Elasticbeanstalk `DescribeEnvironmentManagedActions` API always returns empty result 

### ISSUE THREAD

**Issue by ParthaI** [aws/aws-sdk-go-v2#2082]
### Describe the bug

I am using the the [DescribeEnvironmentManagedActions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0#Client.DescribeEnvironmentManagedActions) API for getting the `Managed Action` info for an environment. But this API always returns empty result. 

### Expected Behavior

The API should return the Managed action info as per [this structure](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0#DescribeEnvironmentManagedActionsOutput).

### Current Behavior

The API  [DescribeEnvironmentManagedActions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0#Client.DescribeEnvironmentManagedActions) doesn't provide any result.

### Reproduction Steps

Run the following code and please check the output.

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"

	"github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk"
)

func main() {
	listManagedActions("us-east-1")
}

func listManagedActions(region string) {
	fmt.Println("Region:", region)
	ctx := context.Background()
	configOptions := []func(*config.LoadOptions) error{
		config.WithRegion(region),
	}

	cfg, err := config.LoadDefaultConfig(ctx, configOptions...)
	if err != nil {
		log.Fatalln("load_default_config", err)
	}

	svc := elasticbeanstalk.NewFromConfig(cfg)

	params := &elasticbeanstalk.DescribeEnvironmentManagedActionsInput{
		EnvironmentName: aws.String("<Environment Name>"),
	}

	result, err := svc.DescribeEnvironmentManagedActions(ctx, params)
	if err != nil {
		log.Fatalln("listManagedActions", "api_error", err)
	}

	for _, managedAction := range result.ManagedActions {
		fmt.Println("Result: ", *managedAction.ActionId)
	}

}
```

### AWS Go SDK V2 Module Versions Used

```
github.com/turbot/steampipe-plugin-aws github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0
github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0 github.com/aws/aws-sdk-go-v2@v1.17.3
github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.27
github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.21
github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk@v1.15.0 github.com/jmespath/go-jmespath@v0.4.0
```

### Compiler and Version used

go version go1.19 darwin/arm64

### Operating System and version

MacOS Big Sur - Version 11.4

**Comment by jmklix** [comment]
Can you make sure that you've set up the [Managed Action correctly](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-platform-update-managed.html?icmpid=docs_elasticbeanstalk_console)? I've been able to use your code to print the action id.

Also you can try using the cli to confirm if you have set up the managed action:
```
aws elasticbeanstalk describe-environment-managed-actions --environment-name "<Environment Name>" --region us-east-1
```

**Comment by ParthaI** [comment]
Thanks @jmklix, for your response, will play around a bit more with it and will let you know. 

Could you please share your output of the above mentioned code(The whole API response by modifying the code a bit `fmt.Println("Result: ", *managedAction)`)?
