### ISSUE TITLE
Field `ShareResourceType` comes blank in `wellarchitected.ListShareInvitations` output

### ISSUE THREAD

**Issue by karanpopat** [aws/aws-sdk-go-v2#2098]
### Describe the bug

Field `ShareResourceType` comes blank in `wellarchitected.ListShareInvitations` output

```json
{
    "ShareInvitationSummaries": [
        {
            "ShareInvitationId": "12340579f47d8aa9bc73d766b8fe37b1",
            "SharedBy": "111122223333",
            "SharedWith": "arn:aws:iam::111122223333:user/karan",
            "PermissionType": "CONTRIBUTOR",
            "WorkloadName": "workload1",
            "WorkloadId": "123ec851ac1d8d9d5b9938615da016ce",
            "LensName": "",
            "LensArn": ""
        }
    ]
}
```

### Expected Behavior

The API should return the `ShareResourceType` as either LENS/WORKLOAD

### Current Behavior

Field ShareResourceType comes blank in wellarchitected.ListShareInvitations output

### Reproduction Steps

Call `wellarchitected.ListShareInvitations` API

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/wellarchitected v1.19.2

### Compiler and Version used

go version go1.19.1

### Operating System and version

MacOS darwin/arm64

**Comment by RanVaknin** [comment]
Hi @karanpopat ,

Thanks for opening the issue. 

I see that the value is not being shown at all. Are you seeing the value when running the same command from the CLI? Or instead you can just enable the response logs and see if the response body contains that field? 

I'm trying to rule out if this is a serialization issue with the SDK, or the Service simply does not respond with `ShareResourceType` field / or sends it as the wrong data type? 

Thanks,
Ran~

**Comment by karanpopat** [comment]
@RanVaknin's response from the CLI also doesn't have the `ShareResourceType` field. I guess it's not coming from the Service itself.
