### ISSUE TITLE
Inner array in `map[string]interface{}` does not deserialize correctly

### ISSUE THREAD

**Issue by Dregorio1** [aws/aws-sdk-go-v2#2099]
### Describe the bug

Inner array in `map[string]interface{}` does not deserialize correctly. 

For `PutItem` I use `dJson, _ := attributevalue.MarshalMap(data)` and `dJson` has correct data structure.

### Expected Behavior

```
res, _ := Scan(ctx, scanInput)
_ = attributevalue.UnmarshalListOfMaps(res.Items, &data)
``` 
should return
```
data = Data {
    Name:         "data1",
    Fields: map[string]interface{}{
        "Field1":        true,
        "Field2": map[string]interface{}{
            "Key":           "foo",
        },
        "Field3": []map[string]interface{}{
            {
                "Key": "Bar",
            },
            {
                "Key": "Baz",
            },
        },
    },
}
```

### Current Behavior

But return:
```
data = Data {
    Name:         "data1",
    Fields: map[string]interface{}{
        "Field1":        true,
        "Field2": map[string]interface{}{
            "Key":           "foo",
        },
        "Field3": []interface{}{},
    },
}
```

### Reproduction Steps

```
var data Data

res, _ := Scan(ctx, dynamodb.ScanInput{TableName: aws.String("table_name")})
_ = attributevalue.UnmarshalListOfMaps(res.Items, &data)
``` 

### AWS Go SDK V2 Module Versions Used

my_proj github.com/aws/aws-sdk-go@v1.44.211
my_proj github.com/aws/aws-sdk-go-v2@v1.17.8
my_proj github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.10
my_proj github.com/aws/aws-sdk-go-v2/config@v1.18.15
my_proj github.com/aws/aws-sdk-go-v2/credentials@v1.13.15
my_proj github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.21
my_proj github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.48
my_proj github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.23
my_proj github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.11.27
my_proj github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.32
my_proj github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.26
my_proj github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.30
my_proj github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.21
my_proj github.com/aws/aws-sdk-go-v2/service/datasync@v1.19.0
my_proj github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4
my_proj github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.14.9
my_proj github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.11
my_proj github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.24
my_proj github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.26
my_proj github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.23
my_proj github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.23
my_proj github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5
my_proj github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.16.7
my_proj github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4
my_proj github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4
my_proj github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5
my_proj github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go@v1.44.211 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go@v1.44.211 github.com/pkg/errors@v0.9.1
github.com/aws/aws-sdk-go@v1.44.211 golang.org/x/net@v0.1.0
github.com/aws/aws-sdk-go-v2@v1.17.8 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2@v1.17.8 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.17.8 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.10 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/aws-sdk-go-v2/credentials@v1.13.15
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.23
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.30
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/config@v1.18.15 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/credentials@v1.13.15 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/credentials@v1.13.15 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.23
github.com/aws/aws-sdk-go-v2/credentials@v1.13.15 github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4
github.com/aws/aws-sdk-go-v2/credentials@v1.13.15 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4
github.com/aws/aws-sdk-go-v2/credentials@v1.13.15 github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5
github.com/aws/aws-sdk-go-v2/credentials@v1.13.15 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/credentials@v1.13.15 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.21 github.com/aws/aws-sdk-go-v2@v1.17.8
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.21 github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.21 github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.14.9
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.21 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.21 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.48 github.com/aws/aws-sdk-go-v2@v1.17.8
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.48 github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue@v1.10.21
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.48 github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression@v1.4.48 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.23 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.23 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.23 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.11.27 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.11.27 github.com/aws/aws-sdk-go-v2/config@v1.17.1
github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.11.27 github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5
github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.11.27 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.11.27 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.32 github.com/aws/aws-sdk-go-v2@v1.17.8
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.26 github.com/aws/aws-sdk-go-v2@v1.17.8
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.26 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.26 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.30 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.21 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.21 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.21 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/datasync@v1.19.0 github.com/aws/aws-sdk-go-v2@v1.17.1
github.com/aws/aws-sdk-go-v2/service/datasync@v1.19.0 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.25
github.com/aws/aws-sdk-go-v2/service/datasync@v1.19.0 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.19
github.com/aws/aws-sdk-go-v2/service/datasync@v1.19.0 github.com/aws/smithy-go@v1.13.4
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4 github.com/aws/aws-sdk-go-v2@v1.17.8
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.32
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.26
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.11
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4 github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.26
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.19.4 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.14.9 github.com/aws/aws-sdk-go-v2@v1.17.8
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.14.9 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.32
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.14.9 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.26
github.com/aws/aws-sdk-go-v2/service/dynamodbstreams@v1.14.9 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.11 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.24 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.24 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.24 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.26 github.com/aws/aws-sdk-go-v2@v1.17.8
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery@v1.7.26 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.23 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.23 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.23 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.23 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.23 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.10
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.29
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.21
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.11
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.24
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.23
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.23
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.16.7 github.com/aws/aws-sdk-go-v2@v1.17.1
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.16.7 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.25
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.16.7 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.19
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.16.7 github.com/aws/smithy-go@v1.13.4
github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.29
github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23
github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.29
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.29
github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23
github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.23
github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5 github.com/aws/smithy-go@v1.13.5
github.com/aws/smithy-go@v1.13.5 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.5 github.com/jmespath/go-jmespath@v0.4.0
github.com/golang-migrate/migrate/v4@v4.7.0 github.com/aws/aws-sdk-go@v1.17.7
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go@v1.44.211
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/config@v1.18.15
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/credentials@v1.13.15
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/s3@v1.30.5
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.10
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.23
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.29
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.30
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.21
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.11
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.24
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.23
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.23
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/sso@v1.12.4
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.14.4
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/aws-sdk-go-v2/service/sts@v1.18.5
github.com/testcontainers/testcontainers-go/modules/localstack@v0.19.0 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2@v1.17.5 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2@v1.17.5 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.17.5 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2@v1.16.11 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2@v1.16.11 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.16.11 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/credentials@v1.12.14
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.19
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.4
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.18
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.9
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.5
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.13
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.12
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.12
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.5 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.12.1 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.12.1 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2@v1.17.1 github.com/aws/smithy-go@v1.13.4
github.com/aws/aws-sdk-go-v2@v1.17.1 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.17.1 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.25 github.com/aws/aws-sdk-go-v2@v1.17.1
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.19 github.com/aws/aws-sdk-go-v2@v1.17.1
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.19 github.com/aws/smithy-go@v1.13.4
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.19 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.4 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.4 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.29 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23 github.com/aws/aws-sdk-go-v2@v1.17.5
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.23 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go@v1.17.7 github.com/jmespath/go-jmespath@v0.0.0-20180206201540-c2b33e8439af
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.19 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.18
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.18
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.12
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.4 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.18 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.9 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.9 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.9 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.5 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.13 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.13 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.13 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.12 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.12 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.12 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.12 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.12 github.com/aws/smithy-go@v1.12.1

### Compiler and Version used

1.19

### Operating System and version

Ubuntu 22.04

**Comment by RanVaknin** [comment]
Hi @Dregorio1 ,

To rule out a deserialization issue can you please enable the response logs on your client? You can do it like so:

```go
	ctx := context.Background()

	cfg, err := config.LoadDefaultConfig(ctx, config.WithClientLogMode(aws.LogResponseWithBody))
	if err != nil {
		panic(err)
	}
```

Doing my own investigation based on the info you have provided did not yield the error you reported
Using the expected output you have provided, I have created a table on dynamodb and created an item that looks like this:

```json
{
  "Name": {
    "S": "data2"
  },
  "Fields": {
    "M": {
      "Field1": {
        "BOOL": true
      },
      "Field2": {
        "M": {
          "Key": {
            "S": "foo"
          }
        }
      },
      "Field3": {
        "L": [
          {
            "M": {
              "Key": {
                "S": "bar"
              }
            }
          },
          {
            "M": {
              "Key": {
                "S": "baz"
              }
            }
          }
        ]
      }
    }
  }
}
```

Im able to read and deserialize the data as expected:

```go
package main

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

type Data struct {
	Name   string                 `dynamodbav:"Name"`
	Fields map[string]interface{} `dynamodbav:"Fields"`
}

func main() {
	ctx := context.Background()

	cfg, err := config.LoadDefaultConfig(ctx, config.WithClientLogMode(aws.LogResponseWithBody))
	if err != nil {
		panic(err)
	}

	client := dynamodb.NewFromConfig(cfg)

	scanInput := &dynamodb.ScanInput{
		TableName: aws.String("table-foo"),
	}

	var data []Data

	res, err := client.Scan(ctx, scanInput)
	if err != nil {
		panic(err)
	}

	err = attributevalue.UnmarshalListOfMaps(res.Items, &data)
	if err != nil {
		panic(err)
	}

	fmt.Println(data)
}
```
Raw response and data printed out:

```console
{"Count":1,"Items":[{"Fields":{"M":{"Field1":{"BOOL":true},"Field2":{"M":{"Key":{"S":"foo"}}},"Field3":{"L":[{"M":{"Key":{"S":"bar"}}},{"M":{"Key":{"S":"baz"}}}]}}},"Name":{"S":"data2"}}],"ScannedCount":1}

[{data2 map[Field1:true Field2:map[Key:foo] Field3:[map[Key:bar] map[Key:baz]]]}]
```

One thing I noticed about your code, that your `data` variable is of type of `Data` and not a slice, based on the documentation it should be []Data. 
If you need further help, please share a complete and concise code example and include the response logs so we can better assist you. 

Thanks,
Ran~
