### ISSUE TITLE
StartTranscriptionJobInput{} missing OutputBucketName

### ISSUE THREAD

**Issue by jokebroker** [aws/aws-sdk-go-v2#210]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go? 
2

### Version of Go (`go version`)? 
1.10.1

### What issue did you see?
[https://github.com/aws/aws-sdk-go-v2/blob/master/service/transcribeservice/api.go](url)
 is missing a field in the struct StartTranscriptionJobInput.

In V1 this field appears as: 
> OutputBucketName *string `type:"string"`

**Comment by jasdel** [comment]
Thanks for letting us know about this issue @jokebroker. The [OutputBucketName](https://github.com/aws/aws-sdk-go/blob/master/service/transcribeservice/api.go#L1656) has been added since the v2 SDK's api models were last updated.

We'll sync the V2 SDK's models to bring the SDK upto to date.

**Comment by skmcgrail** [comment]
Sync has been completed closing issue.
