### ISSUE TITLE
IMDS Client - Methods to get and validate instance identity document signature

### ISSUE THREAD

**Issue by adammw** [aws/aws-sdk-go-v2#2103]
### Describe the feature

Methods in the [IMDS client package](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/ec2/imds) to fetch and validate the instance identity document signature which is available at a [different URL](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-pkcs7.html) to the existing GetInstanceIdentityDocument method.

### Use Case

To contain all the IMDS accessing code in one place and reuse the IMDSv2 token middleware.

### Proposed Solution

add GetInstanceIdentityDocumentSignaturePKCS7 / GetInstanceIdentityDocumentSignatureRSA2048 etc. methods to the existing IMDS client.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

```
github.com/aws/aws-sdk-go-v2/config v1.18.21
github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.13.2
```

### Go version used

1.20

**Comment by jmklix** [comment]
You should be able to do this with [GetDynamicData](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/ec2/imds#Client.GetDynamicData) by providing a path.
> GetDynamicData uses the path provided to request information from the EC2 instance metadata service for dynamic data. The content will be returned as a string, or error if the request failed.

We don't have any plans to add any more specific functions like the ones you mentioned. Closing this feature request
