### ISSUE TITLE
Failing to assume role with STS

### ISSUE THREAD

**Issue by mrinalwahal** [aws/aws-sdk-go-v2#2111]
### Describe the bug

I'm trying to programmatically create Secrets on behalf of a client using their RoleARN. And failing to assume role with STS. Attached the bug description below.

Since this code is supposed to run on my API, I've cleared all my personal `AWS_*` env variables. I have no AWS configuration in my machine right now.

### Expected Behavior

I expect it to return valid values for `AccessKeyID`, `SecretAccessKey` and `SessionToken`.

### Current Behavior

I'm getting the following error on while assuming role using `RoleARN` and `ExternalD`.

```
failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded
```

### Reproduction Steps

Following is the code snippet I'm running:

```
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute*30)
	defer cancel()
	cfg, err := config.LoadDefaultConfig(ctx,
		config.WithRegion(REGION),
		config.WithAssumeRoleCredentialOptions(func(aro *stscreds.AssumeRoleOptions) {
			aro.RoleARN = ARN
			aro.ExternalID = aws.String(ORG_ID)
		}),
	)
	if err != nil {
		log.Fatal(err)
	}

	creds, err := cfg.Credentials.Retrieve(ctx)
	if err != nil {
		log.Fatal(err)
	}
```

### AWS Go SDK V2 Module Versions Used

v1.18

### Compiler and Version used

1.20

### Operating System and version

Mac M1

**Comment by RanVaknin** [comment]
Hi @mrinalwahal ,

I believe this is discussed in this thread, specifically [this](https://github.com/aws/aws-sdk-go-v2/issues/1382#issuecomment-939362001) comment.  Can you take a look and let me know if solves your problem? 

Thanks,
Ran~

**Comment by mrinalwahal** [comment]
> Hi @mrinalwahal ,
> 
> I believe this is discussed in this thread, specifically [this](https://github.com/aws/aws-sdk-go-v2/issues/1382#issuecomment-939362001) comment.  Can you take a look and let me know if solves your problem? 
> 
> Thanks,
> Ran~

Hey, @RanVaknin! Thanks for the response.

And no, the attached thread doesn't solve my problem.

@benkehoe is right in assessing that we require a way to programmatically assume roles.

Is there an existing method to do that?

**Comment by RanVaknin** [comment]
Hi @mrinalwahal ,

Thanks for checking.
>I'm trying to programmatically create Secrets on behalf of a client using their RoleARN. And failing to assume role with STS. Attached the bug description below.

The error you are seeing is because you have cleared you AWS_* environment variables. Your application needs to get valid credentials first, and then call the STS client to assume the role programmatically, only then you can calll .Retrieve():

```go
package main

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials/stscreds"
	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"log"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogResponseWithBody|aws.LogRequestWithBody))
	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := sts.NewFromConfig(cfg)
	appCreds := stscreds.NewAssumeRoleProvider(client, "arn:aws:iam::012345678912:role/clients_role")

	cfg.Credentials = aws.NewCredentialsCache(appCreds)
	svc := secretsmanager.NewFromConfig(cfg)

	out, err := svc.CreateSecret(context.Background(), &secretsmanager.CreateSecretInput{
		Name: aws.String("my-foo-secret"),
	})
	if err != nil {
		return
	}

	fmt.Println(*out.Name)
}
```

output:

```
SDK 2023/05/02 10:15:47 DEBUG Response
HTTP/1.1 200 OK
Content-Length: 106
Content-Type: application/x-amz-json-1.1
Date: Tue, 02 May 2023 17:15:47 GMT
X-Amzn-Requestid: REDACTED

{"ARN":"arn:aws:secretsmanager:us-east-1:REDACTED:secret:my-foo-secret-REDACTED","Name":"my-foo-secret"}

```

Let me know if that helps.
Thanks,
Ran~

**Comment by mrinalwahal** [comment]
Thanks for responding, @RanVaknin.

I understand I need to initialize my local AWS config. I'm just deliberately avoiding it.

As I mentioned - I need to run this script in my API server.

Is there a way for me to hard-code my personal AWS credentials, so that they can be used to assume role?

By hard-code, I mean, obviously - load them from env vars.

**Comment by RanVaknin** [comment]
Hi @mrinalwahal ,

I'm a bit confused because of:
>I've cleared all my personal AWS_* env variables. I have no AWS configuration in my machine right now.

>I mean, obviously - load them from env vars.

`LoadDefaultConfig()` will check all the different places you can configure your credentials. Shared credentials file, Env variables, hard coded strings, and ec2 role creds (if you are running your code from an EC2 instance context)

You cannot avoid having valid config since before calling `AssumeRole`, the SDK needs to get some sort of context of who is assuming the role and if they are allowed to.

Please refer to [this doc](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#environment-variables) on how to set credentials in environment variables.

Let me know if you have any other questions.
Thanks,
Ran~

**Comment by RanVaknin** [comment]
This is what we are here for! Glad I could help 😄
