### ISSUE TITLE
S3.SelectObjectContent equivalent

### ISSUE THREAD

**Issue by franciscocpg** [aws/aws-sdk-go-v2#212]
Is there any equivalent to https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.SelectObjectContent in aws-sdk-go-v2?

**Comment by jasdel** [comment]
Thanks for reaching out to us @franciscocpg. The SelectObjectContent support is in our backlog with #174. We plan on adding this feature to support the S3 Select API.  But until this work is ported to the V2 SDK there is not a workaround.

**Comment by franciscocpg** [comment]
Hi @jasdel.

Thanks for your response.

So I'm closing this one in favor of #174.

**Comment by skmcgrail** [comment]
This is now available as of 2021-11-06 release. https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-11-06
