### ISSUE TITLE
Unable to use SDK with presigned URL

### ISSUE THREAD

**Issue by mytototo** [aws/aws-sdk-go-v2#213]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2

### Version of Go (`go version`)?
v1.11

### Question
I try to make requests against pre-signed S3 URLs generated by a server. This way, the client doesn't need to know the AWS IAM access keys. Unfortunately, it looks like I'm forced to put credentials inside the AWS config for the client, even though I provide a endpoint URL.

What is the best way to make something like this work?

```go
config := aws.Config{
	Region:           "my-region",
	EndpointResolver: aws.ResolveWithEndpointURL(<presigned-url>),
}

uploader := s3manager.NewUploader(config)

iter := &s3manager.UploadObjectsIterator{Objects: objects}
if err := uploader.UploadWithIterator(aws.BackgroundContext(), iter); err != nil {
	fmt.Println(err)
}
```

Thanks.

**Comment by jasdel** [comment]
@mytototo  you can use the [credentials.AnonymousCredentials](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#AnonymousCredentials) variable in your `Config` to create presigned URLs without having credentials.

**Comment by mytototo** [comment]
Thank you @jasdel, authentication works as expected.

One question though: I can't make this work perfectly because the POST URL is malformed. It's `https://<my-bucket>.<my-bucket>.s3.<my-region>.amazonaws.com`. The pre-signed URL however looks good. Do you think it's an error on my side or a SDK issue?

Here is the error:

```
RequestError: send request failed
caused by: Post https://<my-bucket>.<my-bucket>.s3.<my-region>.amazonaws.com/...

...

certificate is valid for *.s3.eu-west-3.amazonaws.com, s3.eu-west-3.amazonaws.com, *.s3-eu-west-3.amazonaws.com, s3-eu-west-3.amazonaws.com, *.s3.dualstack.eu-west-3.amazonaws.com, s3.dualstack.eu-west-3.amazonaws.com, *.s3.amazonaws.com, *.s3-control.eu-west-3.amazonaws.com, s3-control.eu-west-3.amazonaws.com, *.s3-control.dualstack.eu-west-3.amazonaws.com, s3-control.dualstack.eu-west-3.amazonaws.com, not <my-bucket>.<my-bucket>.s3.<my-region>.amazonaws.com
```

**Comment by jasdel** [comment]
@mytototo it looks like your `<my-bucket>` is showing up in the URL twice. Is that intentional? Bucket names with dot(.) in their name are not valid to use in the host.  Buckets with dots(.) must be in the URL path.

**Comment by mytototo** [comment]
No it's not intentional, and this is why the URL is malformed. The bucket name doesn't have dots.
I can't find why the bucket name appears twice in the URL...

**Comment by mytototo** [comment]
Here is what the pre-signed URL looks like : 

```
https://<my-bucket>.s3.<my-region>.amazonaws.com/<folder>/<file>?X-Amz-Algorithm=....
```

**Comment by mytototo** [comment]
I'm still stuck with this _duplicated_ bucket name issue. I can't figure out how to fix it.
Do you think this is a SDK issue ? If so, do you want me to open a new issue for this ?

Thanks for your time.

**Comment by diehlaws** [comment]
@mytototo the SDK is not required when issuing requests to a presigned S3 URL once it is generated - you can use [`http.NewRequest`](https://golang.org/pkg/net/http/?#NewRequest) to issue a PUT to the presigned URL.

We have a [Presigned S3 API Operations Example](https://github.com/aws/aws-sdk-go-v2/tree/master/example/service/s3/presignURL) available that goes into more detail on how to implement a server to create presigned GET and PUT URLs as well as a client that prompts the server to generate a pre-signed URL and uses it to GET or PUT the specified object.

As for your POST URL containing your bucket name twice, `EndpointResolver` is expecting an endpoint listed in our [AWS Regions and Endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) documentation page; `s3manager` will prepend the `Bucket` value for the objects you're specifying in your `objects` variable to the URL the request is sent to, so including the bucket name in the endpoint will result in the behavior you're experiencing.

**Comment by Naatan** [comment]
I'm running into this issue as well. I can get around the redundant bucket in the URL by supplying an empty string to the bucket when providing the download input (`s3.GetObjectInput`). However this ends up resulting in an `signature we calculated does not match the signature you provided` error.

Using `http.NewRequest` is not a viable solution as that method is way less robust in dealing with shaky network connections. I'm specifically trying to use the AWS libraries because they should be more robust.

**Comment by Naatan** [comment]
fyi you can find the relevant bug and workaround to the bug here: https://github.com/aws/aws-sdk-go-v2/issues/719

**Comment by jasdel** [comment]
This is an unsupported feature, to use a presigned URL generically with the SDK. An endpoint that can be provided to the SDK may contain a scheme and host, but any query parameter are not guarantied to be persisted when the SDK invokes the operation request.

Its best to use presigned URLs with a HTTP client directly as the SDK makes several assumptions about how the endpoint can be manipulated.
