### ISSUE TITLE
How to access account number?

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#214]
It's not clear to me from https://godoc.org/github.com/aws/aws-sdk-go-v2/aws#Config or https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/ or the example https://github.com/aws/aws-sdk-go-v2/pull/109 how to see the account identifier. What am I missing please?

**Comment by harkamals** [comment]
Use ec2metadata.New() / it has account number property.

Or use STS, but it is much slower.

**Comment by kaihendry** [comment]
Oh, I have done it before here: https://github.com/unee-t/lambda2sns/blob/master/functions/simple/main.go#L40

**Comment by julienbonastre** [comment]
> Oh, I have done it before here: https://github.com/unee-t/lambda2sns/blob/master/functions/simple/main.go#L40

Dead link

**Comment by dharnitski** [comment]
Alive link - https://github.com/unee-t/lambda2sqs/blob/b78a3148a9f197fd0b70a7f5b71f6c094450bb70/process/main.go#L50

**Comment by JamesMarino** [comment]
Here's a more updated example to stay with the issue

```go
func getAccountId() (string, error) {
	cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Fatal(err)
	}

	client := sts.NewFromConfig(cfg)
	input := &sts.GetCallerIdentityInput{}

	req, err := client.GetCallerIdentity(context.TODO(), input)
	if err != nil {
		return "", err
	}

	return *req.Account, nil
}
```
