### ISSUE TITLE
Cut a new release.

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-go-v2#215]
Can someone please cut a new release of the SDK? The last one was in May 2018.

**Comment by Cyberax** [comment]
It also needs model update (e.g. Amazon SSM Session Manager API is missing)

**Comment by jasdel** [comment]
Thanks, I've created #219 updating the SDK's version. Once the PR is merged in a new tag `v2.0.0-preview.5` will be created. This update includes all of the current AWS service API updates.
