### ISSUE TITLE
Add cloud9 CreateEnvironmentSSH, DescibeSSHRemote and UpdateSSHRemote functions

### ISSUE THREAD

**Issue by m1dugh** [aws/aws-sdk-go-v2#2156]
### Describe the feature

Add Cloud9 service CreateEnvironmentSSH, DescribeSSHRemote and UpdateSSHRemote operations for AWSCloud9WorkspaceManagementService service.

### Use Case

The final goal would be to be able to create SSH environments from the go API to be able to integrate it in the terraform provider.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 github.com/aws/smithy-go@v1.13.5
github.com/aws/aws-sdk-go-v2 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/smithy-go@v1.13.5 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.5 github.com/jmespath/go-jmespath@v0.4.0
github.com/jmespath/go-jmespath@v0.4.0 github.com/jmespath/go-jmespath/internal/testify@v1.5.1
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/davecgh/go-spew@v1.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/pmezard/go-difflib@v1.0.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/stretchr/objx@v0.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 gopkg.in/yaml.v2@v2.2.8
gopkg.in/yaml.v2@v2.2.8 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405

### Go version used

1.19.4 linux/amd64

**Comment by m1dugh** [comment]
The fix is available at this PR https://github.com/aws/aws-sdk-go-v2/pull/2157

**Comment by RanVaknin** [comment]
HI @m1dugh ,

Thanks for taking the time and writing a feature request. 

Unfortunately we cannot accept it. These operations are not listed under the API reference and were intentionally left out from the SDKs and CLI.

This was a service side decision and the SDK team has to honor it. 

I do appreciate you taking the time to delve into our codebase and understand the codegen mechanism. As a rule of thumb, we never change the model files directly, those are also generated from an upstream source on the service side. So if this was a publicly released, I would have created an internal request to add these to the model. 

Please don't let this dissuade you from submitting more FRs and PRs in the future. My only suggestion would be to check with the SDK team before starting to work on a feature so we can help advise. We appreciate your contribution. 

All the best,
Ran~
