### ISSUE TITLE
Add S3 to S3 copy to S3 transfer manager

### ISSUE THREAD

**Issue by devnev** [aws/aws-sdk-go-v2#2165]
### Describe the feature

Extend the s3 manager, `github.com/aws/aws-sdk-go-v2/feature/s3/manager`, to include methods for doing s3-to-s3 copy operations, that include handling multipart copies and concurrency.

### Use Case

I recently had to implement an s3-to-s3 copy, including large files that might require a multipart copy. This is a first class feature of the S3 API, but has some subtleties that will be the same for any user of this API, i.e. when to use multipart copies, how to choose part sizes, and how to manage concurrency. This is also very similar to the existing code in the s3 manager for uploads and downloads.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

```
	github.com/aws/aws-sdk-go-v2 v1.18.1
	github.com/aws/aws-sdk-go-v2/config v1.18.27
	github.com/aws/aws-sdk-go-v2/service/s3 v1.35.0
```

### Go version used

go version go1.20.5 darwin/amd64

**Comment by RanVaknin** [comment]
Hi, 

Thanks for opening this Feature Request. We already have a [backlog item](https://github.com/aws/aws-sdk-go-v2/issues/2095) to address this down the line. 

I will close this because it's a duplicate.

Thanks,
Ran~
