### ISSUE TITLE
ChangeResourceRecordSetsRequest call throws a nil pointer reference 

### ISSUE THREAD

**Issue by tyjohnson01** [aws/aws-sdk-go-v2#217]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
V2

### Version of Go (`go version`)?
go version go1.10.3 darwin/amd64

### What issue did you see?
using the lib github.com/aws/aws-sdk-go-v2/service/route53

Following code fails at 'request := svc.ChangeResourceRecordSetsRequest(input)'
Error is --> runtime error: invalid memory address or nil pointer dereference
I have verified that the svc object is not null and has been properly initialized with aws credentials that full access to Route53 service.

### Steps to reproduce
1) manual add a CName Recordset (no alias), ttl of 300
2) use the following code to delete it

If you have have an runnable example, please include it.

```go
func deleteRecord(svc *route53.Route53, dnsName string, target string, ttl int64, zoneID string) {
	fmt.Printf("Deleting DNS Record %v\n", dnsName)

	input := &route53.ChangeResourceRecordSetsInput{
		ChangeBatch: &route53.ChangeBatch{
			Changes: []route53.Change{
				{
					Action: "DELETE",
					ResourceRecordSet: &route53.ResourceRecordSet{
						Name: aws.String(dnsName),
						Type: "CNAME",
						TTL: aws.Int64(ttl),
						ResourceRecords: []route53.ResourceRecord{
							{ // Required
								Value: aws.String(target), // Required
							},
						},
					},
				},
			},
		},
		HostedZoneId: aws.String(zoneID),
	}


	request := svc.ChangeResourceRecordSetsRequest(input)
	resp, err := request.Send()
	if err != nil {
		fmt.Printf("Unable to delete DNS Record: %v\n", err.Error())
	} else {
		fmt.Println("Successfully deleted DNS Record")
	}
	fmt.Println(resp)
}
```

**Comment by diehlaws** [comment]
Thanks for reaching out about this @tyjohnson01. Unfortunately I'm not able to reproduce this behavior with the code you've provided unless I declare the variable `svc` without initializing it, which you have stated is not the case on your end. Can you provide the full panic call stack you're receiving? This would help us pinpoint the cause of the runtime error you've encountered.

Below is the main function I'm using to call your `deleteRecord` function, does this differ significantly from the way in which you are initializing your config and service variables, and calling your `deleteRecord` function?

```go
func main() {
	cfg, _ := external.LoadDefaultAWSConfig()
	svc := route53.New(cfg)
	dnsName := "test.domain.tld"
	ttl := int64(300)
	target := "amazon.com"
	zoneID := "ZONEIDVALUE123"
	deleteRecord(svc, dnsName, target, ttl, zoneID)
}
```

**Comment by tyjohnson01** [comment]
the one thing was different was the target 'amazon.com', i tried that and I got the same error, here is the stack;
```javascript
runtime error: invalid memory address or nil pointer dereference: errorString
[{"path":"github.com/aws/aws-lambda-go/lambda/function.go","line":27,"label":"(*Function).Invoke.func1"},{"path":"runtime/asm_amd64.s","line":573,"label":"call32"},{"path":"runtime/panic.go","line":502,"label":"gopanic"},{"path":"runtime/panic.go","line":63,"label":"panicmem"},{"path":"runtime/signal_unix.go","line":388,"label":"sigpanic"},{"path":"github.com/aws/aws-sdk-go-v2/aws/request.go","line":102,"label":"New"},{"path":"github.com/aws/aws-sdk-go-v2/aws/client.go","line":73,"label":"(*Client).NewRequest"},{"path":"github.com/aws/aws-sdk-go-v2/service/route53/service.go","line":72,"label":"(*Route53).newRequest"},{"path":"github.com/aws/aws-sdk-go-v2/service/route53/api.go","line":195,"label":"(*Route53).ChangeResourceRecordSetsRequest"},{"path":"ec2SunsetManager/main.go","line":352,"label":"deleteRecord"},{"path":"ec2SunsetManager/main.go","line":142,"label":"Handler"},{"path":"runtime/asm_amd64.s","line":573,"label":"call32"},{"path":"reflect/value.go","line":447,"label":"Value.call"},{"path":"reflect/value.go","line":308,"label":"Value.Call"},{"path":"github.com/aws/aws-lambda-go/lambda/handler.go","line":111,"label":"newHandler.func1"},{"path":"github.com/aws/aws-lambda-go/lambda/handler.go","line":22,"label":"lambdaHandler.Invoke"},{"path":"github.com/aws/aws-lambda-go/lambda/function.go","line":59,"label":"(*Function).Invoke"},{"path":"runtime/asm_amd64.s","line":574,"label":"call64"},{"path":"reflect/value.go","line":447,"label":"Value.call"},{"path":"reflect/value.go","line":308,"label":"Value.Call"},{"path":"net/rpc/server.go","line":384,"label":"(*service).call"},{"path":"runtime/asm_amd64.s","line":2361,"label":"goexit"}]
END RequestId: 67b4f339-bdcc-11e8-8518-735d54961c4c
REPORT RequestId: 67b4f339-bdcc-11e8-8518-735d54961c4c	Duration: 2084.91 ms	Billed Duration: 2100 ms 	Memory Size: 256 MB	Max Memory Used: 44 MB	
runtime error: invalid memory address or nil pointer dereference
errorString
```

I am initializing the svc differently however;
```javascript
staticCredProvider := aws.NewStaticCredentialsProvider(dnsUpdaterAccess,dnsUpdaterSecret, "SESSION")

route53Svc := route53.New(aws.Config{Region:region, Credentials:staticCredProvider })
```

**Comment by diehlaws** [comment]
It looks like your service initialization is missing an endpoint resolver and handlers, which is what's causing the runtime error. In order to avoid having to correctly declare each handler and an endpoint resolver (be it the default `endpoints.NewDefaultResolver` or a custom resolver) in your service declaration, I recommend loading the default AWS config and then modifying the region and credentials to fit your needs.

```go
cfg, _ := external.LoadDefaultAWSConfig()
staticCredProvider := aws.NewStaticCredentialsProvider(dnsUpdaterAccess,dnsUpdaterSecret, "SESSION")
cfg.Region = region
cfg.Credentials = staticCredProvider
```

**Comment by tyjohnson01** [comment]
thanks alot for your help with this, ill try to declare the handler... unfortunately the defaultAWSConfig account does not have access to the route53 service so i cannot use external.LoadDefaultAWSConfig(). ill let you know how it goes.

**Comment by xibz** [comment]
Hello @tyjohnson01, the configuration received can be modified. I would suggest using the `external.LoadDefaultAWSConfig()` function to retrieve the bare essentials needed to make a request and then add or modify whatever it is you are needing.

For example,
```go
cfg, err := external.LoadDefaultAWSConfig()
if err != nil {
    return err
}
cfg.Credentials = aws.NewStaticCredentialsProvider(dnsUpdaterAccess,dnsUpdaterSecret, "SESSION")
```

Please let us know if that helps!

**Comment by tyjohnson01** [comment]
ooh thats a great idea, ill try it now...

**Comment by tyjohnson01** [comment]
this has unblocked me. Thank you so much for the assist.

**Comment by jasdel** [comment]
@tyjohnson01  also if you don't want to use the `external.LoadDefaultAWSConfig()` and only want to use a default configuration without any external data in it you can use the [defaults.Config](https://godoc.org/github.com/aws/aws-sdk-go-v2/aws/defaults#Config) function for creating a initialized Config with the default configuration. No external data will be used, e.g. shared config file.

```go
cfg := defaults.Config()
cfg.Credentials = aws.NewStaticCredentialsProvider(dnsUpdaterAccess,dnsUpdaterSecret, "SESSION")
cfg.Region = region
```

**Comment by tyjohnson01** [comment]
good to know... I went with the first selection and it absolutely worked, i am very grateful for your help in resolving this issue.
