### ISSUE TITLE
Different retryer for different error type

### ISSUE THREAD

**Issue by yuseferi** [aws/aws-sdk-go-v2#2170]
### Describe the feature

In one of the recent project we resolved the token limit throttling with 

```GO
		awsConfig.WithRetryer(func() aws.Retryer {
			return retry.NewStandard(func(so *retry.StandardOptions) {
				so.RateLimiter = ratelimit.NewTokenRateLimit(5000)
				so.MaxAttempts = 2
			})
		}),
```

which resolves the problem for it, but I applied to all retries in the system, So I would say if we could specify the retryer based on the error type that would be great, for example if the error type is  Token Throttle increase the token limit, 
if it's Database throttle , do decrease the MaxAttem to 1 and so on.

### Use Case

Based on the error type define retryers. 

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/aws/retry

### Go version used

1.21

**Comment by lucix-aws** [comment]
Thanks for the engagement.

At this time, we're not looking to expand the retry customization capability in this manner. [aws.Retryer](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#Retryer) is an interface, so you are ultimately able to implement your own for whatever custom behavior you need, including but not limited to what you've described above.

**Comment by yuseferi** [comment]
Hi @lucix-aws, I will before closing it I will wait for your reply.
I know it's an interface and I can implement it, but do you have a sample that shows that where the error located and how can I get the error ?

Best
