### ISSUE TITLE
cloudformation Template format error: unsupported structure.

### ISSUE THREAD

**Issue by AlexFromXD** [aws/aws-sdk-go-v2#2171]
### Describe the bug

While trying to create a stack, I'm keeping getting this error:
```
operation error CloudFormation: CreateStack, https response error StatusCode: 400, RequestID: xxxx-xxxx-xxxx, api error ValidationError: Template format error: unsupported structure.
```

Since the same template file works fine with `aws-cli`, I guess it's something to do with the `TemplateBody` field.
I also try the validate template api, and I get the same error again while cli works well.

### Expected Behavior

no error message

### Current Behavior

```
operation error CloudFormation: CreateStack, https response error StatusCode: 400, RequestID: xxxx-xxxx-xxxx, api error ValidationError: Template format error: unsupported structure.
```

### Reproduction Steps

ok
```sh
aws cloudformation validate-template --template-body file:///absolute/path/template.yaml
```

failed
```go
package main

import (
	"context"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
)

func main() {
	cfg, _ := config.LoadDefaultConfig(context.TODO())
	client := cloudformation.NewFromConfig(cfg)
	_, err := client.ValidateTemplate(context.TODO(), &cloudformation.ValidateTemplateInput{
		TemplateBody: aws.String("file:///absolute/path/template.yaml"),
	})

	if err != nil {
		log.Fatal(err)
	}
}

```

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.18.1
github.com/aws/aws-sdk-go-v2/config v1.18.27
github.com/aws/aws-sdk-go-v2/credentials v1.13.26
github.com/aws/aws-sdk-go-v2/service/cloudformation v1.30.0

### Compiler and Version used

go version go1.19.1 darwin/arm64

### Operating System and version

MacOS 13.4

**Comment by RanVaknin** [comment]
Hi @AlexFromXD ,

The issue you are having is that you are trying to send the template as a filepath which is not supported the same way it is in the CLI:
```go
		TemplateBody: aws.String("file:///absolute/path/template.yaml"),
```

Template body expects a stringified byte array that is representing the template, and not the location of the template:

```go
	template, err := os.ReadFile("file:///absolute/path/template.json")
	if err != nil {
		panic(err)
	}
	
	client := cloudformation.NewFromConfig(cfg)

	templateBody := string(template)
	_, err := client.ValidateTemplate(context.TODO(), &cloudformation.ValidateTemplateInput{
		TemplateBody: &templateBody,
	})
	
	// more code ...
```

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Glad I could help 😄
