### ISSUE TITLE
HTTP User-Agent string-building no longer supports comments

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#2198]
### Describe the bug

In the HTTP spec, [User-Agent strings](https://www.rfc-editor.org/rfc/rfc9110#section-10.1.5) support a combination of `product`s and `comment`s. [A `comment`](https://www.rfc-editor.org/rfc/rfc9110#section-5.6.5) is text contained within parentheses.

Prior to `aws-sdk-go-v2` v1.19.0, comments could be added using

```go
middleware.AddSDKAgentKey("(" + comment + ")")
```

### Expected Behavior

I expected

```go
middleware.AddSDKAgentKey("(" + comment + ")")
```

to continue working.

For example, a comment with the text `this is a comment` should be included in the User-Agent string as

```
(this is a comment)
```

### Current Behavior

Several characters in the comment are replaced by `-`. For example, a comment with the text `this is a comment` is included in the User-Agent string as

```
-this-is-a-comment-
```

instead of

```
(this is a comment)
```

### Reproduction Steps

Generate an HTTP User-Agent string after setting

```go
comment := "this is a comment"
middleware.AddSDKAgentKey("(" + comment + ")")
```

### Possible Solution

One of two solutions:

1. Directly support HTTP User-Agent comment with a function like `middleware.AddUserAgentComment()`

1. Update the escaping rules to not escape keys that match the `comment` pattern defined in [the HTTP spec](https://www.rfc-editor.org/rfc/rfc9110#section-5.6.5)

### AWS Go SDK V2 Module Versions Used

aws-sdk-go-v2 v1.19.0

### Compiler and Version used

go version go1.20.3 darwin/arm64

### Operating System and version

macOS 12.6.7

**Comment by lucix-aws** [comment]
This is definitely a side effect of a [recent User-Agent change](https://github.com/aws/aws-sdk-go-v2/pull/2154).

Note that for the time being you can reclaim this behavior through a build-phase middleware:

```go
import (
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

type userAgentAppender struct {
	v string
}

func (*userAgentAppender) ID() string {
	return "userAgentAppender"
}

func (m *userAgentAppender) HandleBuild(ctx context.Context, in middleware.BuildInput, next middleware.BuildHandler) (
	out middleware.BuildOutput, metadata middleware.Metadata, err error,
) {
	r, ok := in.Request.(*smithyhttp.Request)
	if !ok {
		return out, metadata, fmt.Errorf("unknown transport type %T", in.Request)
	}

	if ua := r.Header.Get("user-agent"); ua != "" {
		r.Header.Set("user-agent", fmt.Sprintf("%s %s", ua, m.v))
	}

	return next.HandleBuild(ctx, in)
}

func withUserAgentAppender(v string) func(*middleware.Stack) error {
	return func(stack *middleware.Stack) error {
		return stack.Build.Add(&userAgentAppender{v: v}, middleware.After)
	}
}

**Comment by gdavison** [comment]
Thanks, the workaround works

**Comment by lucix-aws** [comment]
Ive created #2202 to re-add this through the new `middleware.WithHeaderComment`.

The `AddUserAgentKey` (and friends) APIs were created with the express purpose of allowing a user to add metadata to the `User-Agent` header in a manner befitting how it's handled throughout AWS (including encoding specifications, which as you can see have since tightened). The ability to inject comments through the `AddUserAgentKey` was an unintended side-effect of its existence.

For that reason I believe a new, separate API (which can also apply to any header generically) was the most sensible way forward here.

**Comment by lucix-aws** [comment]
Hi @gdavison -- apologies for dropping the ball on this. I've just now re-spawned the PR in smithy-go, we decided to expose it there instead back in July and it never happened.

**Comment by lucix-aws** [comment]
Fixed by https://github.com/aws/smithy-go/pull/461. This will be available in the next release.
