### ISSUE TITLE
Add `CredentialsProvider` for wrapping RolesAnywhere CreateSession API

### ISSUE THREAD

**Issue by fire833** [aws/aws-sdk-go-v2#2217]
### Describe the feature

This feature request proposes adding a new CredentialsProvider to the SDK which could live within the `credentials` module, and provide an interface to retrieve short-lived credentials using the AWS RolesAnywhere CreateSession API. 

### Use Case

Currently, [this tool](https://github.com/aws/rolesanywhere-credential-helper) provides a CLI interface, (and a slightly rough-around-the-edges API interface underlying it) for generating short-term credentials from an IAM RolesAnywhere certificate bundle. But, the interface isn't really designed for external programmatic use as the interface requires a file path for the cert, key, and chain, as opposed to something like an io.Reader or just a buffer of bytes or a string pointer. I plan fork this method internally and create a `CredentialsProvider` that could satisfy this use case (and hopefully only require v2 of the sdk), but wanted input about trying to merge this type of feature upstream. Or, if there is a more idiomatic solution that I don't know about that would make this proposal irrelevant. 

### Proposed Solution

Here is a short snippet of what this interface could look like:

```go

type RolesAnywhereProvider struct {
   // Probably will just be private fields
}

func (r *RolesAnywhereProvider) Retrieve(ctx context.Context) (aws.Credentials, error) {
 // implement call to CreateSession.
}

func NewRolesAnywhereProvider(cert, key, bundle io.Reader, roleArn, profileArn, trustAnchorArn, region, endpoint string) *RolesAnywhereProvider {
 
}

```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go v1.44.292
github.com/aws/aws-sdk-go-v2 v1.19.1
github.com/aws/aws-sdk-go-v2/config v1.18.30
github.com/aws/aws-sdk-go-v2/service/acm v1.17.13
github.com/aws/aws-sdk-go-v2/service/acmpca v1.21.15
github.com/aws/rolesanywhere-credential-helper v1.0.4	
github.com/aws/aws-sdk-go-v2/credentials v1.13.29 // indirect
github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.13.6 // indirect
github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.36 // indirect
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.30 // indirect
github.com/aws/aws-sdk-go-v2/internal/ini v1.3.37 // indirect
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.30 // indirect
github.com/aws/aws-sdk-go-v2/service/sso v1.12.14 // indirect
github.com/aws/aws-sdk-go-v2/service/ssooidc v1.14.14 // indirect
github.com/aws/aws-sdk-go-v2/service/sts v1.20.1 // indirect

### Go version used

go1.20.4 linux/amd64

**Comment by RanVaknin** [comment]
Hi @fire833,

Thanks for raising this feature request. Admittedly I'm not familiar with the RolesAnywhere tool to get credentials but since its a CLI tool, you might be able to use the existing process credential provider.

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/processcreds

Can you give this a read and let me know what you think?

Thanks,
Ran~

**Comment by ekristen** [comment]
@RanVaknin it would be nice to get this support built directly into the SDK with environment variables so you don't have to do a multi step process. As of right now you have to make calls to a binary to get data to then pass to the SDK, all other authentication mechanisms are just built in, it would be nice to have this built in as well.
