### ISSUE TITLE
Support endpoint configuration via env and shared config

### ISSUE THREAD

**Issue by adrianlungu** [aws/aws-sdk-go-v2#2226]
### Describe the feature

Given that the AWS-CLI has received support for endpoint configuration via `AWS_ENDPOINT_URL` env vars, or the shared config file, as detailed here: https://aws.amazon.com/blogs/developer/new-improved-flexibility-when-configuring-endpoint-urls-with-the-aws-sdks-and-tools/

It would be nice if the Go AWS SDK also supported this to be able to configure the AWS endpoint url automatically as done with other variables, without having to explicitly specify it in code. 

### Use Case

Configuring the AWS session via environment variables or the shared configuration file without having to maintain the variable in multiple places to pass it to code via a `WithEndpoint` func. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.20.1

### Go version used

go1.20.5, MacOS Ventura 13.5

**Comment by bhechinger** [comment]
I was just searching this exact thing yesterday myself as well. Is there any idea of an ETA for when this might be released?

**Comment by lucix-aws** [comment]
Will be resolved be #2328.

**Comment by lucix-aws** [comment]
This is being held back from release temporarily to investigate/resolve a moduling issue which is preventing us from being able to perform the [minimum go version bump to 1.19](https://aws.amazon.com/blogs/developer/aws-sdk-for-go-aligns-with-go-release-policy-on-supported-runtimes/).
