### ISSUE TITLE
GetMetricWidgetImage needs modelling

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#223]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Metric-Widget-Structure.html

**Comment by jasdel** [comment]
Thanks for letting us know about this issue @kaihendry. The V2 SDK needs to be synced with the v1 SDK's latest models.

**Comment by jasdel** [comment]
Thanks for requesting this sync, the SDK was updated in #219.

**Comment by kaihendry** [comment]
I don't understand **where** in Go SDK to find this model. Could you please point out the file since it was a huge change?

<img src="https://s.natalian.org/2019-09-22/1569135728_2560x1440.png">

**Comment by jasdel** [comment]
@kaihendry the SDK's API models are stored in the `models/apis/monitoring/2010-08-01/api-2.json`

The generated API operation can be found: ./service/cloudwatch/api_op_GetMetricWidgetImage.go
