### ISSUE TITLE
github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn should be it's own module

### ISSUE THREAD

**Issue by parsnips** [aws/aws-sdk-go-v2#2244]
### Describe the feature

github.com/aws/aws-sdk-go-v2/internal/endpoints/awsrulesfn should be a module that's rev'd on it's own similar to how configsources is.  

### Use Case

Trying to use services/scheduler in a bazel/gazelle managed build and gazelle attempts to depend on the module via this dependency:

```
"@com_github_aws_aws_sdk_go_v2_internal_endpoints_v2//:awsrulesfn",
```

Even though this package/path does not have `awsrulesfn`

### Proposed Solution

add a go.mod and version that package or
move it into github.com/aws/aws-sdk-go-v2/internal/endpoints/v2

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/scheduler v1.2.2

### Go version used

go version go1.20.2 darwin/arm64

**Comment by lucix-aws** [comment]
This appears to be an issue with this dependency manager, there's nothing semantically invalid about how this subpackage is exposed, nor is it an outlier in `internal` - `internal/auth` is "unmoduled" in this same way.

We're not opposed to improved module granularity, we had briefly picked this up accordingly but we had to reprioritize.

Closing for now.

**Comment by Avinodh** [comment]
@parsnips  - I'm hitting a similar issue when trying to use service/cloudtrail in my project:

`ERROR: /private/var/tmp/<redacted>/external/com_github_aws_aws_sdk_go_v2_service_cloudtrail/BUILD.bazel:3:11: no such target '@com_github_aws_aws_sdk_go_v2_internal_endpoints_v2//:awsrulesfn': target 'awsrulesfn' not declared in package '' defined by /private/var/tmp/_<redacted?/external/com_github_aws_aws_sdk_go_v2_internal_endpoints_v2/BUILD.bazel (Tip: use `query "@com_github_aws_aws_sdk_go_v2_internal_endpoints_v2//:*"` to see all the targets in that package) and referenced by '@com_github_aws_aws_sdk_go_v2_service_cloudtrail//:cloudtrail'`

Were you able to work around this issue?

**Comment by joseph-galindo** [comment]
Just making a note and subscribing to this thread - running into similar issues with attempting to use `service/organizations v1.30.2` with bazel
