### ISSUE TITLE
Add IAM Policy struct

### ISSUE THREAD

**Issue by pete911** [aws/aws-sdk-go-v2#225]
### Steps to reproduce

Would be nice to have struct for IAM Policy, to make it easier check/verify and/or update policy. Some fields can have either string value or slice of strings, proposed struct is below:

```
type Policy struct {
	// 2012-10-17 or 2008-10-17 old policies, do NOT use this for new policies
	Version    string      `json:"Version"`
	Id         string      `json:"Id,omitempty"`
	Statements []Statement `json:"Statement"`
}

type Statement struct {
	Sid          string           `json:"Sid,omitempty"`          // statement ID, service specific
	Effect       string           `json:"Effect"`                 // Allow or Deny
	Principal    map[string]Value `json:"Principal,omitempty"`    // principal that is allowed or denied
	NotPrincipal map[string]Value `json:"NotPrincipal,omitempty"` // exception to a list of principals
	Action       Value            `json:"Action"`                 // allowed or denied action
	NotAction    Value            `json:"NotAction,omitempty"`    // matches everything except
	Resource     Value            `json:"Resource,omitempty"`     // object or objects that the statement covers
	NotResource  Value            `json:"NotResource,omitempty"`  // matches everything except
	Condition    json.RawMessage  `json:"Condition,omitempty"`    // conditions for when a policy is in effect
}

// AWS allows string or []string as value, we convert everything to []string to avoid casting
type Value []string

func (value *Value) UnmarshalJSON(b []byte) error {

	var raw interface{}
	err := json.Unmarshal(b, &raw)
	if err != nil {
		return err
	}

	var p []string
	//  value can be string or []string, convert everything to []string
	switch v := raw.(type) {
	case string:
		p = []string{v}
	case []interface{}:
		var items []string
		for _, item := range v {
			items = append(items, fmt.Sprintf("%v", item))
		}
		p = items
	default:
		return fmt.Errorf("invalid %s value element: allowed is only string or []string", value)
	}

	*value = p
	return nil
}
```
Custom unmarshal will make sure that fields will always have `[]string` type, even if they contain only one element.

**Comment by jasdel** [comment]
Thanks for requesting this feature @pete911. The v1 and v2 SDK have not yet added policy structures because they are inconsistent between services, and have a fairly generic structure. The v1 SDK has aws/aws-sdk-go#127 outstanding for this feature as well.

**Comment by pete911** [comment]
@jasdel can you send an example of the different policies pls? I don't mind looking into to it. I was under impression there's only one standard policy.

**Comment by nickatsegment** [comment]
@jasdel can this be reopened? Seems like a pretty key feature. The service-agnostic parts seem well-specified https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html

**Comment by pete911** [comment]
@nickatsegment (and @jasdel) I kind of already gave up on creating PRs and issues on aws-sdk, I find it strange that it takes 8 months (created issue in October 2018, comment from aws was added in May 2019) to just add comment on a issue that I offered help and also created PR. I even asked one day after the comment to give me directions how I can solve this, but since then no reply (more than one year ago ...). I would understand if this was some kind of startup/one man job, but this is aws sdk and most of us using this are paying customers ... Sorry for the rant, but I  honestly don't know what to say.

**Comment by t0rr3sp3dr0** [comment]
It would be nice to have this struct available on the SDK since we now have the grammar of a policy.

**Comment by sushi30** [comment]
why is it closed? very confusing that a feature request is closed due to staleness when it's still getting upvotes.

**Comment by csuzhangxc** [comment]
can this be reopened?

**Comment by cvirtucio** [comment]
I'm interested in this request, but I'm wondering how this would work. `Action`, `Principal`, `Condition` and `Resource` have several possible types, leading to several possible permutations of a `Statement` struct.
