### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by Shaharbad** [aws/aws-sdk-go-v2#2266]
### Describe the bug

Hey everyone,

I kindly need your help with creating a MediaTailor configuration using the API, I am completely lost with this, after looking at the documentation I couldn't find a proper method to create a configuration.

### Expected Behavior

what I'm looking for is creating a configuration using a content source url, ad decision server url and a configuration name, and then log the generated HLS when it's done.

### Current Behavior

It's my first time working with the aws api and I've successfully installed Aws CLI in the meanwhile.

### Reproduction Steps

I would appreciate any help! thanks.

### AWS Go SDK V2 Module Versions Used

null

### Compiler and Version used

go version 1.20

### Operating System and version

macOS

**Comment by RanVaknin** [comment]
Hi @Shaharbad ,

You opened the same issue in the v1 repo. 
https://github.com/aws/aws-sdk-go/issues/4974

The implementation should be almost identical between the two versions. 

Thanks,
Ran~
