### ISSUE TITLE
`eks.Client.CreateNodegroup()` does not allow k8s label with empty value

### ISSUE THREAD

**Issue by wainersm** [aws/aws-sdk-go-v2#2267]
### Describe the bug

Creating a node group `eks.Client.CreateNodegroup()` for EKS, it doesn't allow a kubernetes `Labels` (`key=value`) with empty `value`.

For example, the kubernetes `node.kubernetes.io/worker=` label (key  is `node.kubernetes.io/worker` and value is empty) is a valid node label.  

### Expected Behavior

Using the following snippet of code:

```go
	if _, err = e.Client.CreateNodegroup(context.TODO(),
		&eks.CreateNodegroupInput{
			ClusterName:   aws.String(e.Name),
			NodeRole:      aws.String(NodesRoleArn),
			NodegroupName: aws.String(e.NodeGroupName),
			Subnets:       []string{e.Vpc.SubnetId},
			AmiType:       ekstypes.AMITypesAl2X8664, // AL2_x86_64
			CapacityType:  ekstypes.CapacityTypesOnDemand,
			InstanceTypes: []string{"t3.medium"},
			RemoteAccess: &ekstypes.RemoteAccessConfig{
				Ec2SshKey: aws.String(e.SshKpName),
			},
			ScalingConfig: &ekstypes.NodegroupScalingConfig{
				DesiredSize: aws.Int32(e.NumWorkers),
				MaxSize:     aws.Int32(e.NumWorkers),
				MinSize:     aws.Int32(e.NumWorkers),
			},
			Version: aws.String(e.Version),
			Labels:  map[string]string{"node.kubernetes.io/worker": ""},
		}); err != nil {
		return err
```

I expect it to create the node group.

### Current Behavior

Instead it fails with the followin error:

```
FATA[0587] operation error EKS: CreateNodegroup, https response error StatusCode: 400, RequestID: 4ad8baba-0782-470a-9a53-5ee8144b494b, InvalidParameterException: Invalid value:  : field must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

### Reproduction Steps

Provided a snippet of code in `Expected Behavior`.

### AWS Go SDK V2 Module Versions Used

        github.com/aws/aws-sdk-go-v2 v1.21.0
        github.com/aws/aws-sdk-go-v2/config v1.15.11
        github.com/aws/aws-sdk-go-v2/credentials v1.12.6
        github.com/aws/aws-sdk-go-v2/service/ec2 v1.114.0
        github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.6
        github.com/aws/aws-sdk-go-v2/service/iam v1.22.5
        github.com/aws/aws-sdk-go-v2/service/s3 v1.38.5
        github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.4.13 // indirect
        github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.41 // indirect
        github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.35 // indirect
        github.com/aws/aws-sdk-go-v2/internal/ini v1.3.13 // indirect
        github.com/aws/aws-sdk-go-v2/internal/v4a v1.1.4 // indirect
        github.com/aws/aws-sdk-go-v2/service/eks v1.29.5 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.9.14 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.1.36 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.35 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.15.4 // indirect
        github.com/aws/aws-sdk-go-v2/service/sso v1.11.9 // indirect
        github.com/aws/aws-sdk-go-v2/service/sts v1.16.7 // indirect
        github.com/aws/smithy-go v1.14.2 // indirect

### Compiler and Version used

go version go1.20.6 linux/amd64

### Operating System and version

Linux, Fedora 36

**Comment by RanVaknin** [comment]
Hi @wainersm,

>For example, the kubernetes node.kubernetes.io/worker= label (key is node.kubernetes.io/worker and value is empty) is a valid node label.

This might be a valid Kubernetes behavior, but based on the very explicit error you got back from the EKS service, supplying empty label values is not allowed. 

I have ruled out a potential serialization issue with the SDK by logging the raw request body sent to EKS, and I can see that the SDK serializes even the explicit empty value:

```json
{
  "amiType": "AL2_x86_64",
  "capacityType": "ON_DEMAND",
  "clientRequestToken": "REDACTED",
  "instanceTypes": [
    "t3.medium"
  ],
  "labels": {
    "node.kubernetes.io/worker": ""
  },
  "nodegroupName": "bazz",
  "nodeRole": "bar",
  "remoteAccess": {
    "ec2SshKey": "SshKpName"
  },
  "scalingConfig": {
    "desiredSize": 1,
    "maxSize": 2,
    "minSize": 1
  },
  "subnets": [
    "123"
  ],
  "version": "1"
}
```

Which shows that this is not an SDK issue, but more of a design choice from EKS itself. 

Since there is nothing the SDK team can do with regards to the service side behavior, I'm inclined to close this. 
Feel free to use the AWS console to open an internal ticket with AWS, the Technical Account manager that will be assigned to you can help navigate your request to the EKS team. 

All the best,
Ran~
