### ISSUE TITLE
Support PKCS#8PrivateKey Parsing in CloudFront Signed URL Signer

### ISSUE THREAD

**Issue by payt0nc** [aws/aws-sdk-go-v2#2270]
### Describe the feature

Since OpenSSL version >3.0.0 was deprecated `genrsa` and by default generates Private Key using `PKCS#8` standard and encodes in PEM format,  I would suggest that this SDK would include the `PKCS#8` in reading Private Key file.

Following the instructions in [CloudFront documents]((https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html)), there would be generated PKCS#8 format. If users would have PKCS#1 format, users should add [`-traditional`](https://www.openssl.org/docs/man3.0/man1/openssl-rsa.html) flag on their command.

### Use Case

Creating the Signed URL

### Proposed Solution

Either one at the below:
1. add new function `LoadEncryptedPEMPKCS8PrivKey`
2. amend the implementation of `LoadEncryptedPEMPrivKey` with using `x509.ParsePKCS8PrivateKey` for parsing the key file

### Other Information

This OpenSSL feature updates may effect the AWS CLI with `aws cloudfront sign`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/feature/cloudfront/sign@v1.3.49 github.com/aws/aws-sdk-go-v2@v1.21.0
github.com/aws/aws-sdk-go-v2@v1.21.0 github.com/aws/smithy-go@v1.14.2
github.com/aws/aws-sdk-go-v2@v1.21.0 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.21.0 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/smithy-go@v1.14.2 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.14.2 github.com/jmespath/go-jmespath@v0.4.0

### Go version used

1.21.0

**Comment by lucix-aws** [comment]
I think this is a reasonable add. Granted, it shouldn't been seen as a blocker to users of the cloudfront URL signer - the  [existing key utils therein](https://github.com/aws/aws-sdk-go-v2/blob/main/feature/cloudfront/sign/privkey.go) are thin wrappers around `crypto` stdlib constructs that anyone could reasonably implement for their own needs.

**Comment by webbhlin** [comment]
I aslo have the same pkcs8 private key issue.  Is there any workaround?

**Comment by webbhlin** [comment]
Thank you so much for the workaround.  :)   Please allow me to clarify: 
I still can use the private_key.pem and public_key.pym files generated by openssl with the pkcs8 format.  The thing instead of the sdk one is to use crypto/ras and crypto/x509 to read my private_key.pem then pas the key to sign.NewURLSigner.

**Comment by luabagg** [comment]
Is it done? I'm using the "sign.LoadPEMPrivKeyFile" function and getting this error:

 "x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)"

I don't know exactly what to do. I generated the file with ```openssl genrsa -out privkey.pem 2048```

**Comment by vubon** [comment]
@luabagg you have three options. 
1. You can generate a PKCS1 certificates
2. You use PKCS8 with custom changes of AWS SDK 
3. You need to wait until they publish a new release with this feature. 

By the below command, you can use generate PKCS1 certificate 
`openssl genrsa -traditional -out privkey.pem 2048`

OpenSSL version: 3.1.2

**Comment by webbhlin** [comment]
Thanks a lot. Here is my way to solve the issue.

func loadPrivateKey(pemString string) (*rsa.PrivateKey, error) {
	block, _ := pem.Decode([]byte(pemString))
	if block == nil {
		return nil, errors.New("failed to decode PEM block containing private key")
	}

	// Try to parse the PEM block as a PKCS#1 private key
	rsaKey, err1 := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err1 == nil {
		return rsaKey, nil
	}

	// If the above failed, try to parse it as a PKCS#8 private key
	privKey, err2 := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err2 == nil {
		if rsaPrivKey, ok := privKey.(*rsa.PrivateKey); ok {
			return rsaPrivKey, nil
		} else {
			return nil, errors.New("private key is not of RSA type")
		}
	}

	// If both parsing attempts failed, return an error
	return nil, errors.New("failed to parse the private key")
}

**Comment by luabagg** [comment]
Yeah, it worked, the PKCS1 resolved.

I was parsing the PKCS8 before, I think it was right though. What I discovered was that my issue was actually caused by a misconfig in the SDK request...

But now it's working smooth.

**Comment by lucix-aws** [comment]
Given the sudden amount of activity on this and relative simplicity of implementation I'll go ahead and add it.

Given the unspecified nature of the returned key type from `x509.ParsePKCS8PrivateKey` I think the following is probably the most sensible way to support it for us:

```go
// LoadPEMPrivKeyPKCS8 reads a PEM-encoded RSA private key in PKCS8 format from
// the given reader.
//
// [x509.ParsePKCS8PrivateKey] can return multiple key types and this API does
// not discern between them. Callers in need of the underlying value must
// obtain it via type assertion:
//
//  key, err := sign.LoadPEMPrivKeyPKCS8(r)
//  if err != nil { /* ... */ }
//
//  switch key.(type) {
//  case *rsa.PrivateKey:
//      // ...
//  case *ecdsa.PrivateKey:
//      // ...
//  case ed25519.PrivateKey:
//      // ...
//  default:
//      panic("unrecognized private key type")
//  }
//
// See aforementioned API docs for a full list of possible key types.
//
// If calling code can opaquely handle the returned key as a [crypto.Signer],
// use [LoadPEMPrivKeyPKCS8AsSigner] instead.
func LoadPEMPrivKeyPKCS8(reader io.Reader) (interface{}, error)

// LoadPEMPrivKeyPKCS8AsSigner wraps [LoadPEMPrivKeyPKCS8] to expect a
// [crypto.Signer].
func LoadPEMPrivKeyPKCS8AsSigner(reader io.Reader) (crypto.Signer, error)
```

**Comment by lucix-aws** [comment]
@payt0nc @webbhlin @luabagg @vubon 

`sign.LoadPEMPrivKeyPKCS8` and `sign.LoadPEMPrivKeyPKCS8AsSigner` have been merged and will be available in the next release.
