### ISSUE TITLE
Windows: credential_process cannot handle paths denoted with backslashes

### ISSUE THREAD

**Issue by jordankay13** [aws/aws-sdk-go-v2#2273]
### Describe the bug

On Windows, when using `credential_process`, the executable cannot be contained in a folder that starts with `t` or `n` when using backslashes in the path.

For example:
```
[default]
credential_process = "C:\somefolder\tools\myexe.exe"
```
This will fail with the error:
```
'C:\somefolder' is not recognized as an internal or external command, operable program or batch file.
```

### Expected Behavior

I expected my executable in the `tools` folder to be executed to fetch my AWS credentials:
```
[default]
credential_process = "C:\somefolder\tools\myexe.exe"
```

### Current Behavior

Folders beginning with `t` or `n` are treated as tabs or newlines when using backslashes.

In fact, the example path in these docs for Windows would hit this bug:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html 
because "C:\Path\To\credentials.cmd" would be corrupted at the To folder.

### Reproduction Steps

Setup your credentials file similar to:
```
[default]
credential_process = "C:\somefolder\tools\myexe.exe"
```

I don't have a program that I've written for this -- I'm just using an OpenTelemetry Collector, and it's written in Go:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awskinesisexporter/exporter.go#L60

The premise is that the call to `config.LoadDefaultConfig` with the above credentials file results in the error.

### AWS Go SDK V2 Module Versions Used

[github.com/aws/aws-sdk-go-v2/config v1.18.38](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/89e27cb4cbf0c70cc0e03483179c5a992392b882/exporter/awskinesisexporter/go.mod#L7)

### Compiler and Version used

1.20.8

### Operating System and version

Windows

**Comment by lucix-aws** [comment]
@jordankay13 -- Do escaped backslashes exhibit the same issue?

e.g.

```
[default]
credential_process = "C:\\somefolder\\tools\\myexe.exe"
```

**Comment by jordankay13** [comment]
> @jordankay13 -- Do escaped backslashes exhibit the same issue?
> 
> e.g.
> 
> ```
> [default]
> credential_process = "C:\\somefolder\\tools\\myexe.exe"
> ```

It looks like that also fails -- Using forward slashes work though (`C:/somefolder/tools/myexe.exe`)

**Comment by lucix-aws** [comment]
I have some more context into this after recently re-writing the entire ini parser in #2365.

This manual escaping of `\*` sequences is something we've always done, it's not standardized behavior whatsoever.

As it so happens, **in the aforementioned refactor I unintentionally removed part of that behavior**. As of the current version we now only escape `\n`, `\"`, and `\'`.

Normally we're opposed to making changes like this - https://www.hyrumslaw.com/ - but I'm reconsidering here given that there was no apparent fallout from the partial removal.

**Comment by lucix-aws** [comment]
Will be resolved by https://github.com/aws/aws-sdk-go-v2/pull/2461
