### ISSUE TITLE
secret config does not update

### ISSUE THREAD

**Issue by sumz95** [aws/aws-sdk-go-v2#2274]
### Describe the bug

When calling the ListSecrets Function and inspecting a secret, the secret.RotationRules rules do not match what you configured them to be

### Expected Behavior

I expected the varible `secret.RotationEnabled` and `secret.RotationRules.AutomaticallyAfterDays`   to be `nil` as I had disabled rotation on a secret.

### Current Behavior

I created a secret with rotation which would rotate automatically after 2 days.
So when I checked  `secret.RotationRules.AutomaticallyAfterDays` I got 2 as expected.

Then from the console I disabled the rotation, 
Then I checked `secret.RotationRules.AutomaticallyAfterDays` again but I still get 2 days rather than nil

### Reproduction Steps

Creates secret from the aws console with rotation of 2 days.
Then disable the rotation	

```
secretsManagerInst := secretsmanager.NewFromConfig(cfg)
listSecretInput := secretsmanager.ListSecretsInput{}
resp, err := secretsManagerInst.ListSecrets(ctx, &listSecretInput)
for _, secret := range resp.SecretList {
      if secret.RotationEnabled != nil {
           rotationInDays = *secret.RotationRules.AutomaticallyAfterDays
      }
}
```

rotationInDays will be a 2 rather than nil

### AWS Go SDK V2 Module Versions Used

go 1.20

require (
	github.com/aws/aws-lambda-go v1.41.0
	github.com/aws/aws-sdk-go-v2 v1.20.1
	github.com/aws/aws-sdk-go-v2/config v1.18.33
	github.com/aws/aws-sdk-go-v2/service/cloudtrail v1.28.3
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.21.0
)

require (
	github.com/aws/aws-sdk-go-v2/credentials v1.13.32 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.13.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.38 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.32 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.39 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.32 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.13.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.15.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.21.2 // indirect
	github.com/aws/smithy-go v1.14.1 // indirect
)

### Compiler and Version used

go version go1.20.5 darwin/amd64

### Operating System and version

Mac OS Ventura 13.2.1

**Comment by lucix-aws** [comment]
It's difficult to discern whether there's an SDK issue here given the use of the console in the workflow.

As I understand it, you created a secret (either in the console or via the SDK) with the rotation config, then disabled that rotation config (from the console). Then the listing of the secret as retrieved by the SDK still has the original rotation. Absent further context, it appears _the console itself_ failed to update the rotation config.

Are you able to reproduce with the console removed from the equation? i.e. Does creating the secret, updating the config, and then re-reading the secret _exclusively_ from the SDK exhibit the same behavior?

**Comment by sumz95** [comment]
I can still reproduce it.

I am able to create a secret with the go-sdk function `CreateSecret` and set a rotation.
Then I cancel it with `CancelRotateSecret`
Then If I describe with `DescribeSecret`, I get

```
{
    "ARN": "###",
    "Name": "###",
    "RotationEnabled": false,
    "RotationRules": {
        "AutomaticallyAfterDays": 2,
        "ScheduleExpression": "rate(2 days)"
   }
 }
```
You can see that the field `AutomaticallyAfterDays` is still set: 

After looking into this `CancelRotateSecret` only sets the `RotationEnabled` field to `False`.
I found this to be confusing because when you create a secret without any rotation the `RotationEnabled` is `nil`. So I was expecting `RotationEnabled` to be `nil` again after the `CancelRotateSecret` call.

However I found the same behaviour in the aws cli, so it is consistent, and seems to be a issue with the design rather than the go-sdk

**Comment by RanVaknin** [comment]
Hi @sumz95 ,

I understand the confusion, but this seems like the intended behavior of the API.
The idea is that the rotation rules are still in place, if you want to re-enable rotation all you need to do is set `RotationEnabled` to true, avoiding having to specify the rotation rules again. 

Since this behavior is consistent between the various SDKs and the CLI, this is a service side behavior, and not actionable by the SDK team. 

All the best,
Ran~
