### ISSUE TITLE
Sort image tag list based on timestamp

### ISSUE THREAD

**Issue by abhibhaw** [aws/aws-sdk-go-v2#2275]
### Describe the feature

I want to only fetch latest 50 images but the package always returns in alphabetical order.

### Use Case

- I want to fetch the latest image and deploy the same.

### Proposed Solution

A sort option where I can fetch sorted images from ecr and that sort option should have timestamp (pushed time) as an option

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

v1.20.0

### Go version used

go version go1.19.5 darwin/amd64

**Comment by RanVaknin** [comment]
Hi @abhibhaw,

What you are asking for is a service-side feature request. client-side sorting is not something the SDKs support. That utility can be implemented by the end user and this is not something that is in the scope of the SDK. 

If you don't want to implement this yourself, you can open a support ticket and asked to be routed to the ECR service team using the AWS console.

At this moment we are not inclined to implement this on the SDK level.
Apologies for the inconvenience. 

Thanks,
Ran~
