### ISSUE TITLE
Could this support Signature Version 2 for S3?

### ISSUE THREAD

**Issue by DamonYellow** [aws/aws-sdk-go-v2#228]
I met `InvalidArgument: status code: 400` with `aws-sdk-go`:https://github.com/aws/aws-sdk-go/issues/2212, may I ask if this one could help?

**Comment by jasdel** [comment]
Thanks for reaching out to us @DamonYellow. The v2 SDK does not plan to provide support for the signature version 2 for S3. S3 is moving towards only supporting the v4 signature version starting June 24, 2019 per the [AWS Forums announcement](https://forums.aws.amazon.com/ann.jspa?annID=5816).

The SDK does allow custom signers to be added at runtime. You will be able to inject a custom v2 signer into the SDK's runtime.

**Comment by DamonYellow** [comment]
That'll be great, could show me some code example pls?

**Comment by jasdel** [comment]
HI @DamonYellow  I don't have a code sample, but the [AWS Signature Version 2](https://docs.aws.amazon.com/AmazonS3/latest/dev/auth-request-sig-v2.html) outlines how the v2 signature for S3 needs to be constructed.
