### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by ewosborne** [aws/aws-sdk-go-v2#2280]
### Describe the issue

"All service operation output structs include a ResultMetadata member of type [middleware.Metadata](https://pkg.go.dev/github.com/aws/smithy-go/middleware#Metadata). middleware.Metadata is used by the SDK middleware to provide additional information from a service response that is not modeled by the service. This includes metadata like the RequestID. For example to retrieve the RequestID associated with a service response to **assit** AWS Support in troubleshooting a request:"

s/assit/assist/

### Links

https://aws.github.io/aws-sdk-go-v2/docs/making-requests/

**Comment by RanVaknin** [comment]
Hi. 

Thanks for the report. Will take care of that. 

Thanks,
Ran~

**Comment by lucix-aws** [comment]
Fixed by #2281
