### ISSUE TITLE
jmespath package dependency problem

### ISSUE THREAD

**Issue by wolfkang** [aws/aws-sdk-go-v2#229]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2

### Version of Go (`go version`)?
go version go1.10.3 linux/amd64

### What issue did you see?
An error message like this
```
cannot find package "github.com/jmespath/go-jmespath"
```

### Steps to reproduce
```
$ go get -u github.com/aws/aws-sdk-go-v2
$ go test
../github.com/aws/aws-sdk-go-v2/internal/awsutil/path_value.go:9:2: cannot find package "github.com/jmespath/go-jmespath" in any of:
	/usr/local/go/src/github.com/jmespath/go-jmespath (from $GOROOT)
	/efs/manager/src/github.com/jmespath/go-jmespath (from $GOPATH)
$ go get -u github.com/jmespath/go-jmespath  # I had to do this
$ go test
$
```

Please check this out.

**Comment by jasdel** [comment]
Hi @wolfkang thanks for reaching out to us @wolfkang  the reason the `go test` failed is because the original `go get` command didn't retrieve the dependencies of of the SDK.

Using Go 1.11 will use the `go modules` which will will not require any additional command other than `go get github.com/aws/aws-sdk-go-v2`.  

If you'd like to not change to Go 1.11, you can change your original `go get` command to the following:

```
go get github.com/aws/aws-sdk-go-v2/...
```

**Comment by Crazometer** [comment]
I got this problem too with go `1.11.14`. It seems like whether modules will be used depends on a few factors.

https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support

**Comment by j0hnsmith** [comment]
This is still a problem 5 months later.

**Comment by jasdel** [comment]
Thanks for the feedback. With Go modules the SDK's dependencies will be downloaded as expected, but without modules enabled, or within a GOPATH (via Go1.11, or Go1.12) I think you'll need to use `go get github.com/aws/aws-sdk-go-v2/...`  the `/...` is needed to get the SDK's dependencies in packages outside of the SDK's root package.  Without the `/...` only dependencies of the SDK's root package will be retrieved.

I also updated the SDK's README to reflect this, e97b9cb.

Are you still having issues getting the SDK and its dependencies with the `/...` suffix?

**Comment by j0hnsmith** [comment]
Didn't realise the `/...` is necessary, had to delete and reinstall but works. Thanks

**Comment by jasdel** [comment]
Closing, please let us know if you're still running into this issuse.
