### ISSUE TITLE
S3ObjectLambdaEvent is missed in codebase

### ISSUE THREAD

**Issue by ikovalyov** [aws/aws-sdk-go-v2#2334]
### Describe the feature

S3ObjectLambdaEvent is used for S3 Object Lambdas to communicate with S3 but this event type is missed. I can see this event exists in typescript, java, python versions of AWS SDK,

### Use Case

Use S3 Object Lambda in golang.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

1.21.2

### Go version used

1.21.3

**Comment by lucix-aws** [comment]
This is generally part of the lambda runtime for a language, not the SDK. Note that [S3ObjectLambda](https://javadoc.io/doc/com.amazonaws/aws-lambda-java-events/3.9.0/com/amazonaws/services/lambda/runtime/events/S3ObjectLambdaEvent.html) in Java is part of that lambda runtime.

If this is missing in [aws-lambda-go](https://github.com/aws/aws-lambda-go) you'll need to file a request there.
