### ISSUE TITLE
Add missing matching event types `deliveryDelay` and `subscription` to SES EventDestination

### ISSUE THREAD

**Issue by Jimmy89** [aws/aws-sdk-go-v2#2342]
### Describe the bug

The `EventDestination` matchingEventTypes is missing support for two types: `deliveryDelay` and `subscription`.

Place where it should be added: https://github.com/aws/aws-sdk-go-v2/blob/main/service/ses/types/types.go#L361-L374

### Expected Behavior

I'm using the AWS terraform package to create all my SES event destinations and I noticed that I cannot use the missing two types. 

I inserted a ticket (https://github.com/hashicorp/terraform-provider-aws/issues/33983) which lead to this repo.

According to the AWS Cloud Control API and Cloudformation documentation the matching event types for the event destinations exists, so it would be great if they are added.

Cloudformation doc link: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-eventdestination.html#cfn-ses-configurationseteventdestination-eventdestination-matchingeventtypes

### Current Behavior

-

### Reproduction Steps

Sorry, I'm not able to provide this, but I hope the description and links are sufficient.

### AWS Go SDK V2 Module Versions Used

-

### Compiler and Version used

-

### Operating System and version

-

**Comment by RanVaknin** [comment]
Hi @Jimmy89,

Thanks for the issue. I'm not sure if these values are unique to Cfn but from looking at the model and the service [documentation](https://docs.aws.amazon.com/ses/latest/APIReference/API_EventDestination.html), those types are not listed. My guess is that the service team has rolled those service side but never updated the model from which the SDK is generated.

I created a ticket with the SES service team to further investigate this: `P104431082`

Please stay tuned.
All the best,
Ran~

**Comment by RanVaknin** [comment]
Hi @Jimmy89 ,

I heard back from the service team. The fields in question are available in sesv2 API
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_EventDestination.html

Thanks,
Ran~

**Comment by lucix-aws** [comment]
sesv2 is supported - it's a separate service ID and has its own package https://github.com/aws/aws-sdk-go-v2/tree/main/service/sesv2.

Closing since it sounds like there's nothing missing.
