### ISSUE TITLE
Error building with Bazel using module github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.2

### ISSUE THREAD

**Issue by digitalandrew** [aws/aws-sdk-go-v2#2372]
### Describe the bug

Since the most recent version of the `github.com/aws/aws-sdk-go-v2/service/dynamodb` module builds via Bazel using this module are failing with error message: `external/com_github_aws_aws_sdk_go_v2_service_dynamodb/endpoints.go:495:39: undefined: endpoints.MapFIPSRegion`

Manually reverting back to the previous version of the module fixes this issue. 

### Expected Behavior

Binaries will successfully build using this module. 

### Current Behavior

Binaries importing this module are failing to build when building via Bazel with error:

`external/com_github_aws_aws_sdk_go_v2_service_dynamodb/endpoints.go:495:39: undefined: endpoints.MapFIPSRegion`

### Reproduction Steps

Create a simple go application that imports "github.com/aws/aws-sdk-go-v2/service/dynamodb" and use standard Bazel build settings to build. 

### AWS Go SDK V2 Module Versions Used

require (
	github.com/aws/aws-sdk-go-v2 v1.23.0
	github.com/aws/aws-sdk-go-v2/config v1.19.1
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.12.2
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.6.2
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.2
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.21.6
)

require (
	github.com/aws/aws-sdk-go-v2/credentials v1.13.43 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.13.13 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.3 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.3 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.45 // indirect
	github.com/aws/aws-sdk-go-v2/service/dynamodbstreams v1.17.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.8.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.37 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.15.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.17.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.23.2 // indirect
	github.com/aws/smithy-go v1.17.0 // indirect
)

### Compiler and Version used

go version go1.20.5 linux/amd64

### Operating System and version

linux 5.15.49-linuxkit

**Comment by lucix-aws** [comment]
@digitalandrew `endpoints.MapFIPSRegion` is a new API in the main `aws-sdk-go-v2` module. It appears that you have only upgraded the dynamodb module, rolling all of your SDK dependencies forward to the latest release should resolve this.

**Comment by digitalandrew** [comment]
@lucix-aws - I followed your advice and rolled all of my aws sdk deps forward to the latest version, this fixed the issue at that time for `dynamodb`. Coming back after the weekend and trying to build and I'm getting the same error but this time for `ssoidc` - `external/com_github_aws_aws_sdk_go_v2_service_ssooidc/endpoints.go:464:39: undefined: endpoints.MapFIPSRegion`.

I've rolled all aws go deps forward to latest `go get -u ./...`

Here is my `go.mod `

```
require (
	github.com/aws/aws-sdk-go-v2 v1.23.0
	github.com/aws/aws-sdk-go-v2/config v1.25.3
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.12.2
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.6.2
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.2
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.23.2
)

require (
	github.com/aws/aws-sdk-go-v2/credentials v1.16.2 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.14.4 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.3 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.3 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.7.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/dynamodbstreams v1.17.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.8.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.10.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.17.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.20.0 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.25.3 // indirect
	github.com/aws/smithy-go v1.17.0 // indirect
)
```
