### ISSUE TITLE
`ListObjectVersions` and `ListMultipartUploads` paginators send 0 for max items when input is nil

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-sdk-go-v2#2379]
### Describe the bug

My specific problem is to do with the S3 API's `ListObjectVersionsInput.MaxKeys` field, but the underlying cause may affect other APIs.

The recent (https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-17) change to default value serialization, https://github.com/aws/aws-sdk-go-v2/issues/2162, has caused the S3 `ListObjectVersions` API to return no object versions when no value (now `nil`) is specified for `ListObjectVersionsInput.MaxKeys`.
Previously (https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-16) up to 1000 object versions were returned when no value was specified, as [documented in the API Reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html#AmazonS3-ListObjectVersions-request-querystring-MaxKeys):
> Sets the maximum number of keys returned in the response. By default, the action returns up to 1,000 key names.

Sniffing the HTTP request I can now see an explicit `max-keys=0` URL query parameter added.

### Expected Behavior

If no value for `ListObjectVersionsInput.MaxKeys` is specified, up to 1000 object version should be returned.

### Current Behavior

See above.

### Reproduction Steps

```go
input := &s3.ListObjectVersionsInput{
	Bucket:  aws.String("tf-acc-test-7828939106372858870"),
}

pages := s3.NewListObjectVersionsPaginator(conn, input)
for pages.HasMorePages() {
	page, err := pages.NextPage(ctx)

	if err != nil {
		return err
	}

	for _, objectVersion := range page.Versions {
	}
}
```

leads to

```
http.url="https://tf-acc-test-7828939106372858870.s3.us-west-2.amazonaws.com/?max-keys=0&versions="
http.response.body=
| <?xml version="1.0" encoding="UTF-8"?>
| <ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>tf-acc-test-7828939106372858870</Name><KeyMarker></KeyMarker><VersionIdMarker></VersionIdMarker><MaxKeys>0</MaxKeys><IsTruncated>false</IsTruncated></ListVersionsResult>
```

### Additional Information/Context

Workaround is to add an explicit default value:

```
input := &s3.ListObjectVersionsInput{
	Bucket:  aws.String("tf-acc-test-7828939106372858870"),
	MaxKeys: aws.Int32(1000),
}
```

### AWS Go SDK V2 Module Versions Used

```console
% grep s3 go.mod 
	github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.14.0
	github.com/aws/aws-sdk-go-v2/service/s3 v1.43.0
	github.com/aws/aws-sdk-go-v2/service/s3control v1.37.0
	github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.16.3 // indirect
```

### Compiler and Version used

go version go1.20.10 darwin/amd64

### Operating System and version

macOS Ventura 13.6

**Comment by lucix-aws** [comment]
The handwritten paginator for `ListObjectVersions` was updated incorrectly as part of this change. Will work on a fix immediately.

> change to default value serialization

As an aside, the behavior of default value serialization in the SDK itself was _not_ changed. The service model was updated in a way that causes us to instead generate the affected fields like this as `*type` instead of the value variant.

**Comment by lucix-aws** [comment]
Linked PR will correct this behavior.

Note that explicit use of `ListObjectVersions` / `ListMultipartUploads` is unaffected.
