### ISSUE TITLE
s3control `types.PublicAccessBlockConfiguration` failing to serialize correctly when all (boolean) fields are `false`

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-sdk-go-v2#2384]
### Describe the bug

The s3control service's `types.PublicAccessBlockConfiguration` structure fails to serialize correctly when all its (boolean) fields are `false`:

```go
input := &s3control.PutPublicAccessBlockInput{
	AccountId: aws.String("123456789012"),
	PublicAccessBlockConfiguration: &types.PublicAccessBlockConfiguration{
		BlockPublicAcls:       false,
		BlockPublicPolicy:     false,
		IgnorePublicAcls:      false,
		RestrictPublicBuckets: false,
	},
}
```

HTTP request and response:

```
  http.request.body=
  | <PublicAccessBlockConfiguration xmlns="http://awss3control.amazonaws.com/doc/2018-08-20/"></PublicAccessBlockConfiguration>
  http.response.body=
  | <?xml version="1.0" encoding="UTF-8"?>
  | <ErrorResponse><Error><Code>InvalidRequest</Code><Message>Must specify at least one configuration.</Message></Error><RequestId>7ESN3M87GKFSGK0T</RequestId><HostId>XoGVKFltZ6t++IFu6TDSibAhtgLGAPC9xSUa/kv+UEm6lxmQNeurd3TWYgVPGaFj5pzjiXoIv/g=</HostId></ErrorResponse>
```

### Expected Behavior

Expected no error (AWS SDK for Go v1 behavior).

### Current Behavior

See above.

### Reproduction Steps

See above.

### Additional Information/Context

Relates https://github.com/aws/aws-sdk-go-v2/issues/2162.

### AWS Go SDK V2 Module Versions Used

```console
% grep s3control go.mod
	github.com/aws/aws-sdk-go-v2/service/s3control v1.37.1
```

### Compiler and Version used

go version go1.20.10 darwin/amd64

### Operating System and version

macOS Ventura 13.6

**Comment by lucix-aws** [comment]
It's unclear why this was missed in the bulk s3 update that just went out. I'll check with the smithy folks.

**Comment by lucix-aws** [comment]
Sorry -- missed that it was `s3control`. The equivalent in the s3 namespace _was_ updated on Friday.

This was a miss in the previous update that addressed s3control. The smithy team has opened ticket [internal tracking `V1120201288`] to address this in the s3control model.

**Comment by lucix-aws** [comment]
@ewbankkit We've been advised to patch this locally to the SDK for now given the potential lead time on having it fixed upstream. I've done so in #2385.
