### ISSUE TITLE
Undefined endpoints.MapFIPSRegion in ssooidc/endpoints.go

### ISSUE THREAD

**Issue by digitalandrew** [aws/aws-sdk-go-v2#2386]
### Describe the bug

After the large recent update to the sdk-go-v2 module builds importing the module have been failing with the error:

`external/com_github_aws_aws_sdk_go_v2_service_sso/endpoints.go:464:39: undefined: endpoints.MapFIPSRegion`

Based on @lucix-aws suggestion I have checked to roll ahead all of the dependencies and am still facing the issue. If I roll back the sdk packages to previous versions the builds work. 

### Expected Behavior

Able to build Go application using the external packages without error. 

### Current Behavior

Trying to use the most up to date aws-sdk-go-v2 packages breaks builds with error:

`external/com_github_aws_aws_sdk_go_v2_service_sso/endpoints.go:464:39: undefined: endpoints.MapFIPSRegion`

### Reproduction Steps

Create a simple go application that uses the packages listed below and try to build. 

### Additional Information/Context

These versions of SDK modules do not fail to build:

require (
	github.com/aws/aws-sdk-go-v2 v1.22.2
	github.com/aws/aws-sdk-go-v2/config v1.19.1
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.12.1
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.6.1
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.1
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.21.6
)

require (
	github.com/aws/aws-sdk-go-v2/credentials v1.13.43 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.13.13 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.2 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.3.45 // indirect
	github.com/aws/aws-sdk-go-v2/service/dynamodbstreams v1.17.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.0 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.8.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.37 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.15.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.17.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.23.2 // indirect
	github.com/aws/smithy-go v1.16.0 // indirect
)

### AWS Go SDK V2 Module Versions Used

require (
	github.com/aws/aws-sdk-go-v2 v1.23.1
	github.com/aws/aws-sdk-go-v2/config v1.25.5
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.12.3
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.6.3
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.3
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.23.3
)

require (
	github.com/aws/aws-sdk-go-v2/credentials v1.16.4 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.14.5 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.4 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.4 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.7.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/dynamodbstreams v1.17.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.8.4 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.10.4 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.17.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.20.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/sts v1.25.4 // indirect
	github.com/aws/smithy-go v1.17.0 // indirect
)

### Compiler and Version used

go1.20.5 linux/amd64

### Operating System and version

linux 5.15.49-linuxkit

**Comment by lucix-aws** [comment]
I'm unable to reproduce this. The only thing I can do is advise you to potentially clear your go module cache. [`MAPFIPSRegion` is definitively present in the source of the `aws-sdk-go-v2` module at `v1.23.1`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v1.23.1/internal/endpoints#MapFIPSRegion), which is what you're depending on.

**Comment by digitalandrew** [comment]
For anyone that stumbles on this looking for a solution, this was fixed for me by updating go_rules in bazel.

**Comment by ashleydavies** [comment]
Thanks for replying saying what helped @digitalandrew 😄 saved me a lot of pain

**Comment by hnoshab75** [comment]
@digitalandrew what was the version of rules_go you were using earlier and which one did you upgrade to which fixed the issue?
