### ISSUE TITLE
"not found, ResolveEndpointV2" with latest config service modules (v1.25.7 and v1.25.8)

### ISSUE THREAD

**Issue by laraoz** [aws/aws-sdk-go-v2#2397]
### Describe the bug

I am experiencing a not found, ResolveEndpointV2 error.
This error occurs during the process of trying to decrypt a cyphertext blob using KMS.
```go
config, err := awsconfig.LoadDefaultConfig(context.Background())
if err != nil { ... }
kmsSvc := kms.NewFromConfig(config)
params := &kms.DecryptInput{
	CiphertextBlob: someCipherTextBlob,
}
resp, err := kmsSvc.Decrypt(context.TODO(), params) // <-- resolve error here
if err != nil {
	return ....
}

return ...
```

### Expected Behavior

The KMS Decrypt method is expected to execute without errors.

### Current Behavior

When executing the Decrypt method, the following error occurs:
```
not found, ResolveEndpointV2
```

### Reproduction Steps

Use/Create a cipher text blob ([]byte) payload.
Use the AWS SDK V2 for Go to create an KMS client.
Use the Decrypt method of the KMS client to decrypt the text blob.
Observe the ResolveEndpointV2 error during the execution of the Decrypt call.

### Additional Information/Context

The issue does not occur with previous versions of the SDK, and reverting to an earlier version resolves the issue:

```go 
github.com/aws/aws-sdk-go-v2 v1.22.1
github.com/aws/aws-sdk-go-v2/config v1.22.0
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.10.43
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.4.71
github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.11.89
github.com/aws/aws-sdk-go-v2/service/dynamodb v1.23.0
github.com/aws/aws-sdk-go-v2/service/glue v1.62.1
github.com/aws/aws-sdk-go-v2/service/s3 v1.40.2
```

### AWS Go SDK V2 Module Versions Used

```go
github.com/aws/aws-sdk-go-v2 v1.23.2
github.com/aws/aws-sdk-go-v2/config v1.25.8
github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.12.5
github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression v1.6.5
github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.15.1
github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.5
github.com/aws/aws-sdk-go-v2/service/glue v1.70.2
github.com/aws/aws-sdk-go-v2/service/s3 v1.46.0
```

### Compiler and Version used

go version go1.21.0 darwin/arm64

### Operating System and version

macOS Ventura - Apple M1 Max

**Comment by laraoz** [comment]
related issue https://github.com/aws/aws-sdk-go-v2/issues/2370

**Comment by lucix-aws** [comment]
The solution is in that issue's thread -- you have to upgrade every v2 sdk module to the latest version. Closing as duplicate.

**Comment by ganesh-KB** [comment]
Please execute:
`go clean -modcache`

<img width="470" alt="how... go clean works" src="https://github.com/aws/aws-sdk-go-v2/assets/113498558/0f613dfe-a60f-4de7-97d5-f148a4aad2f4">

Then execute 
`go mod tidy` 

!!! Done !!!

**Comment by yuseferi** [comment]
you need to update all the AWS SDK-related dependencies and the error will gone. 

    go get -u github.com/aws/aws-sdk-go-v2/...

**Comment by gams-temark** [comment]
> you need to update all the AWS SDK-related dependencies and the error will gone.
> 
> ```
> go get -u github.com/aws/aws-sdk-go-v2/...
> ```

Thanks so much! I've been stuck on this issue for hours!

**Comment by pranjalgdev** [comment]
https://github.com/aws/aws-sdk-go-v2/issues/2397#issuecomment-2126792353

Thanks it worked 👍 ❤
