### ISSUE TITLE
Could you sync the models with v1?

### ISSUE THREAD

**Issue by i0rek** [aws/aws-sdk-go-v2#240]
I am specifically looking for `servicediscovery.DiscoverInstances`! Thank you! :heart:

**Comment by jasdel** [comment]
Thanks for creating this issue @i0rek. We're working to update the v2 SDK with the updates released during re:Invent. There are a few customizations that need to be ported to the v2 SDK in order for this to happen, but I will refer to this issue when the PR updates are ready.

**Comment by i0rek** [comment]
Thank you @jasdel! Do you know when this is going to happen? Would love to stay on `v2` but I need that. If you don't get to it I will probably go back to `v1` until it made to `v2`.

**Comment by jasdel** [comment]
@i0rek there are a few features that need to be ported to the v2 SDK in order to sync the recent model updates. We'll work to port these features, but do not have a ETA to share.

**Comment by i0rek** [comment]
Thank you!

**Comment by jasdel** [comment]
going to reopen this issue to keep track of the features that need to be ported from the v1 SDK in order to update the V2 SDK to the latest models

Need:
* aws/aws-sdk-go#2219
* aws/aws-sdk-go#2299
* aws/aws-sdk-go#2296
* aws/aws-sdk-go#2278
* aws/aws-sdk-go#2286

**Comment by jasdel** [comment]
The SDK's been updated to `v0.6.0`. This brings the SDK up to date with the AWS service releases since reInvent.

**Comment by i0rek** [comment]
Thank you!
