### ISSUE TITLE
Allow setting `BaseEndpoint` on `config.LoadOptions`

### ISSUE THREAD

**Issue by gdavison** [aws/aws-sdk-go-v2#2422]
### Describe the feature

The `config.SharedConfig` and `config.EnvConfig` structs both have a parameter `BaseEndpoint` that sets a common endpoint URL for all services. `config.LoadOptions` does not have the corresponding parameter.

Also add the corresponding `config.WithBaseEndpoint` functional option.

### Use Case

While an endpoint resolver could be configured with a base endpoint, adding `BaseEndpoint` would make a more consistent interface, as well as allowing the SDK to handle the override logic including service-specific endpoints and ignoring configured endpoints.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.24.0
github.com/aws/aws-sdk-go-v2/config v1.26.1

### Go version used

go version go1.21.0 darwin/arm64

**Comment by lucix-aws** [comment]
I've identified this as a major migration blocker across the broader set of SDK use cases. Increasing priority.
