### ISSUE TITLE
Support for the Eventbridge Scheduler

### ISSUE THREAD

**Issue by ronfor** [aws/aws-sdk-go-v2#2429]
### Describe the feature

Support for Eventbridge Scheduler: https://docs.aws.amazon.com/scheduler/latest/UserGuide/what-is-scheduler.html

I was unable to find support for this feature within the SDK, so creating this Feature Request.

### Use Case

When creating and interacting with the Eventbridge Scheduler.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2 v1.24.0
	github.com/aws/aws-sdk-go-v2/service/eventbridge v1.26.5

### Go version used

1.20.1

**Comment by RanVaknin** [comment]
Hi @ronfor ,

Scheduler has its own client https://github.com/aws/aws-sdk-go-v2/tree/main/service/scheduler

Thanks,
Ran~
