### ISSUE TITLE
`Config.Copy`, godocs specify additional configuration being passable, but its not

### ISSUE THREAD

**Issue by Nikola-Milovic** [aws/aws-sdk-go-v2#2436]
### Describe the issue

Current documentation for `Config.Copy` states the following

```
// Copy will return a shallow copy of the Config object. If any additional
// configurations are provided they will be merged into the new config returned.
func (c Config) Copy() Config {
	cp := c
	return cp
}
```

If this was intended to be used via builder pattern or some other approach, then it would make sense, but as it stands, it just seems that it was intended to allow for additional options to be passed to the copied object. Since this isn't possible, the docs should probably be updated

### Links

https://github.com/aws/aws-sdk-go-v2/blob/4837b20ebbea7042e34df9cfd4fcf06f8a852d2c/aws/config.go#L175

### AWS Go SDK V2 Module Versions Used

`github.com/aws/aws-sdk-go-v2/config@v1.26.1` and `github.com/aws/aws-sdk-go-v2@v1.24.0`

**Comment by RanVaknin** [comment]
Hi @Nikola-Milovic ,

Good catch, I fixed it.

Thanks for your help,
Ran~
