### ISSUE TITLE
 ec2..amazonaws.com: no such host

### ISSUE THREAD

**Issue by Horiodino** [aws/aws-sdk-go-v2#2437]
### Describe the bug

I was working on an issue and using aws-sdk-go-v2, I was using Linux previously and everything working fine but now I shifted to windows and getting this error message:
```
https response error StatusCode: 0, RequestID  request send failed, Post https://ec2..amazonaws.com: dial tcp: lookup ec2..amazo
```  

### Expected Behavior

should accept Api calls.

### Current Behavior

```returns http error code 0```

### Reproduction Steps

use windows-10 and try to access list of Aws-regions. 

### Possible Solution

may be the ```https://ec2..amazonaws.com``` should be using one ```.``` and then everything works!

### SDK version used

aws-sdk-go-v2

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

windows-10

**Comment by matthewkmayer** [comment]
I'm seeing a similar error with the S3 download manager.

```go
        getObjReq := s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	}

	_, err = downloader.Download(ctx, fd, &getObjReq)
	if err != nil {
		log.Infof(ctx, "Couldn't download file: %v", err.Error())
		return err
	}
```


```
Couldn't download file: operation error S3: GetObject, https response error StatusCode: 0, RequestID: , HostID: , request send failed, 
Get "https://s3/..amazonaws.com/(snip)image.bin?x-id=GetObject": dial tcp: lookup s3..amazonaws.com: no such host
```

Using:

github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.15.9

github.com/aws/aws-sdk-go-v2/service/s3 v1.47.7

This is in a Go binary in a Docker container from a `scratch` image running on ECS.

**Comment by Horiodino** [comment]
> I'm seeing a similar error with the S3 download manager.
> 
> ```go
>         getObjReq := s3.GetObjectInput{
> 		Bucket: aws.String(bucket),
> 		Key:    aws.String(key),
> 	}
> 
> 	_, err = downloader.Download(ctx, fd, &getObjReq)
> 	if err != nil {
> 		log.Infof(ctx, "Couldn't download file: %v", err.Error())
> 		return err
> 	}
> ```
> 
> ```
> Couldn't download file: operation error S3: GetObject, https response error StatusCode: 0, RequestID: , HostID: , request send failed, 
> Get "https://s3/..amazonaws.com/(snip)image.bin?x-id=GetObject": dial tcp: lookup s3..amazonaws.com: no such host
> ```
> 
> Using:
> 
> github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.15.9
> 
> github.com/aws/aws-sdk-go-v2/service/s3 v1.47.7
> 
> This is in a Go binary in a Docker container from a `scratch` image running on ECS.

you find any solution? or its due to aws!

**Comment by matthewkmayer** [comment]
@Horiodino in my case the AWS_REGION environment variable wasn't set on the running container. I proved this by going from

```go
awsConfig, err := config.LoadDefaultConfig(ctx)
```

to

```go
awsConfig, err := config.LoadDefaultConfig(ctx, config.WithRegion("us-east-1"))
```

And the request was able to be sent.
