### ISSUE TITLE
use FIPS aws endpoints with v2 golang indicate still uses regular endpoints 

### ISSUE THREAD

**Issue by sandakith** [aws/aws-sdk-go-v2#2464]
### Describe the bug

Hi if we are to use FIPS aws endpoints with v2 golang this is the approach I took but find very hard to verify if it does the correctly use FIPS endpoints, any point would be appreciated
```
cfg, err := config.LoadDefaultConfig( context.TODO(), config.WithRegion("us-west-2"), config.WithUseFIPSEndpoint(aws.FIPSEndpointStateEnabled), )
```
Lets say I am using s3 client after
```
	 s3client = s3.NewFromConfig(cfg) 
```
How can I verify this client is using FIPS urls not default s3 urls?

### Expected Behavior

PutObject HTTP/1.1
**Host: o2-input-data-xxxxxxxxxx.s3.us-west-2.amazonaws.com**.  <--- Needed to be FIPS
User-Agent: aws-sdk-go-v2/1.18.0 os/linux lang/go/1.20.6 md/GOOS/linux md/GOARCH/amd64 api/s3/1.17.0 ft/s3-transfer
Content-Length: 76786
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: b06662cf-595e-42ab-a465-3724af4c9b8b

### Current Behavior

Using non FIPS ? 
Host: o2-input-data-xxxxxxxxxxx.s3.us-west-2.amazonaws.com. <--- Needed to be FIPS

### Reproduction Steps

* create same config as above 
* try to put object to bucket 

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2 v1.18.0
	github.com/aws/aws-sdk-go-v2/config v1.11.0
	github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.3.0
	github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.6.0
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.6.0
	github.com/aws/aws-sdk-go-v2/service/s3 v1.17.0
	github.com/aws/aws-sdk-go-v2/service/sqs v1.19.0
	github.com/aws/smithy-go v1.13.5

### Compiler and Version used

 go1.20.6 linux/amd64

### Operating System and version

RHEL9

**Comment by sandakith** [comment]
@RanVaknin  Thanks - Let me know if you need more details basically we started from here https://docs.aws.amazon.com/sdkref/latest/guide/feature-endpoints.html tried that but that did not work and then falling back to application sdk config to see if that works.

**Comment by RanVaknin** [comment]
Hi @sandakith ,

It works fine for me on the latest version:

```
SDK 2024/01/24 12:16:36 DEBUG Request
POST /some-object-name?uploads=&x-id=CreateMultipartUpload HTTP/1.1
Host: o2-input-data-xxxxxxxxxx.s3-fips.us-west-2.amazonaws.com    <-- fips endpoint is correct.
User-Agent: aws-sdk-go-v2/1.24.1 os/macos lang/go#1.19.1 md/GOOS#darwin md/GOARCH#arm64 api/s3#1.48.0
Content-Length: 0
Accept-Encoding: identity
Amz-Sdk-Invocation-Id: 17dc3698-4c99-4028-b431-6f5842734878
Amz-Sdk-Request: attempt=1; max=3
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20240124/us-west-2/s3/aws4_request, SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date, Signature=REDACTED
X-Amz-Content-Sha256: REDACTED
X-Amz-Date: 20240124T201636Z
```

I believe you are seeing this issue because your version is quite old. It says that you are using s3 v1.17.0, but we are on 1.48.1.

Can you please update the SDK version and try again? 

Thanks,
Ran~

**Comment by sandakith** [comment]
Hi @RanVaknin Thanks for the suggestion. your suggestion worked and we are now on s3 1.48.1 and fips woks with it.  
Also we tested dynamodb and got to know that we need to use v1.26.9 and FIPS works.
However we still cant get sqs to work, we updated the version to v1.28.0 and this is the error we get. 
{"level":"error","error":"not found, ResolveEndpointV2","time":"2024-01-24T22:03:04Z","message":"Got an error creating the queue:"}
Can you help us with this too to test it. Thanks!

**Comment by RanVaknin** [comment]
Hi @sandakith, Happy to hear that works. 

SQS is right now at v1.29.1, can you please update it as well to the latest version?
Additionally, without seeing a code sample that can reliably reproduce your error it will be difficult to diagnose.

If you can provide us with a concise code snippet that highlights the issue that would be great.

Thanks,
Ran~

**Comment by sandakith** [comment]
Thank you @RanVaknin  for all your suggestions! We have now migrated to latest versions and FIPS endpoint client enabelment is working with config update with s3, dynamodb, sts and sqs. Therefore, I am going to close this now. We still have some localstack issues we are encountering but this seems to be a limitation with localstack not AWS golang SDK v2. Here is the ticket for your reference https://github.com/localstack/localstack/issues/10123
