### ISSUE TITLE
Unresolvable Endpoint Error with ListBuckets API Call using fips endpoint

### ISSUE THREAD

**Issue by MichaelChovanakDatavant** [aws/aws-sdk-go-v2#2468]
### Describe the bug

The S3 endpoints behave in an unexpected manner. Specifically, the endpoint `s3-fips.<region>.amazonaws.com` does not resolve, whereas `<bucket>.s3-fips.<region>.amazonaws.com` and `s3.<region>.amazonaws.com` resolve as expected.

When non-fips endpoints are used, the ListBuckets API call utilizes the `s3.<region>.amazonaws.com` endpoint and successfully lists the buckets. However, with fips endpoints, the SDK attempts to use `s3-fips.<region>.amazonaws.com` which results in a DNS resolution failure with the following error (from a terraform plan that calls ListBuckets for a resource):
```
Error: listing S3 Buckets: RequestError: send request failed
caused by: Get "https://s3-fips.us-east-1.amazonaws.com/": dial tcp: lookup s3-fips.us-east-1.amazonaws.com on 172.20.0.10:53: no such host
```
This behavior suggests that the FIPS endpoint handling in the SDK does not currently account for this edge case where service-level operations like ListBuckets are incompatible with FIPS endpoints.

### Expected Behavior

When fips endpoints are used, it is expected that the s3 FIPS endpoint supports all API functionalities, including the ListBuckets call. Since this endpoint resolution behavior is almost certainly outside of the control of this repo (AWS side), a workaround could allow manual override of the endpoint for edge cases such as this (specifically ListBuckets) without having to disable the use of all fips endpoints.

### Current Behavior

When the fips endpoint is used, we get this error on ListBuckets:
```
Error: listing S3 Buckets: RequestError: send request failed
caused by: Get "https://s3-fips.us-east-1.amazonaws.com/": dial tcp: lookup s3-fips.us-east-1.amazonaws.com on 172.20.0.10:53: no such host
```
When normal endpoints are used, we get no error listing buckets.

### Reproduction Steps

The `data "aws_canonical_user_id" "current" {}` datasource uses AWS SDK for Go V2 to call ListBuckets ([implementation](https://github.com/hashicorp/terraform-provider-aws/blob/v5.34.0/internal/service/s3/canonical_user_id_data_source.go)) where (from my understanding) the AWSClient uses fips endpoints if the aws provider has `use_fips_endpoints = true`.

### Possible Solution

A method to override the endpoint used in edge cases where the fips endpoint is unusable (like ListBuckets) while allowing fips endpoints to be used elsewhere.

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.15.13
github.com/aws/aws-sdk-go-v2/service/s3 v1.48.0
github.com/aws/aws-sdk-go-v2/service/s3control v1.42.0
github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.16.10 // indirect

### Compiler and Version used

1.20.5

### Operating System and version

macOS Sonoma 14.3

**Comment by RanVaknin** [comment]
Hi @MichaelChovanakDatavant ,

Thanks for reaching out. After looking a bit into this, It seems related to this [existing issue](https://github.com/aws/aws-sdk/issues/521). I can see that we have an internal ticket with the s3 team, and it seems like there is simply no FIPS  endpoint for listBuckets. We are waiting on official wording, but _it seems like_ you can just use the non-FIPS endpoint for listing object and it should still be FIPS compliant.

I'm going to close this issue in favor of tracking it in https://github.com/aws/aws-sdk/issues/521. Please check that thread for more updates about an official workaround.

Thanks again,
Ran~
