### ISSUE TITLE
Missing release notes for 1.25.0

### ISSUE THREAD

**Issue by tyler-french** [aws/aws-sdk-go-v2#2497]
### Describe the issue

I can't find the release notes for `v1.25.0`. The latest I can find is https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2024-01-04 includes `v1.24.1`

### Links

https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2024-01-04
https://github.com/aws/aws-sdk-go-v2/releases
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2?tab=versions

**Comment by lucix-aws** [comment]
There is a fundamental mismatch here between when a module is _tagged_ and when it gets release notes. A module is _tagged_ any time its code changes (this is handled automagically by build internals).

Changelog entries on the other hand are added manually by a homespun tool. This tool allows us to specify a description of the change and the list of modules to which it applies.

Notable here is that to avoid bloating the root CHANGELOG.md file for many-module changes (and to prevent release automation from failing to post such a large message in GitHub APIs), we include a "collapse" setting which affects how the resulting changelog appears.

In the _root_ changelog (NOT module-specific changelogs), these entries are condensed into the "General Highlights" section that you see in that file. **This has a side-effect of obfuscating when a changelog entry applies to the root SDK module, which is understandably confusing.**

The set of "changes" for the main SDK module tagged 1.25.0 was thus effectively this:

* General Highlights
  * Feature: Bump minimum Go version to 1.20 per our language support policy.

Internally this changelog entry is designated as applying to that root module, but it doesn't show that way with how we generate the root changelog. Per-module changelogs aren't affected by this, if you go to any of the tags for services released yesterday you'll see that the new tagged version is associated with that same "bump minimum go version" message.

I've backlogged an item to retool this internally and prevent this confusion in the future.
