### ISSUE TITLE
Unset/zero-value region should explicitly fail endpoint resolution

### ISSUE THREAD

**Issue by lucix-aws** [aws/aws-sdk-go-v2#2502]
There was a subtle change with either the introduction of `EndpointResolverV2` or `AuthSchemeResolver` (I haven't deep-dived yet) - an empty region string on client config now incorrectly gets passed to endpoint resolution, which tends to result in nonsense hostnames like `ram..amazonaws.com`.

This should instead result in the "region" endpoint parameter being effectively unset/`nil` which will cause endpoint resolution to fail with an error that's actually useful.

There has been a _ton_ of very warranted customer confusion around this recently, see the following:
* https://github.com/aws/aws-sdk-go-v2/issues/2501
* https://github.com/aws/aws-sdk-go-v2/issues/2472
* https://github.com/aws/aws-sdk-go-v2/issues/2437

**Comment by nikpivkin** [comment]
Hi @lucix-aws !

Am I understanding correctly that this has only been fixed for endpoint v2?

I ran into this:
```bash
 - operation error EBS: ListSnapshotBlocks, https response error StatusCode: 0, RequestID: , request send failed, Get "https://ebs..amazonaws.com/snapshots/snap-03d27487772cf94a3/blocks": dial tcp: lookup ebs..amazonaws.com: no such host
```
