### ISSUE TITLE
Glacier - signature we calculated does not match the signature you provided when uploading in parallel

### ISSUE THREAD

**Issue by jczornik** [aws/aws-sdk-go-v2#2509]
### Describe the bug

I get the following error:
`api error InvalidSignatureException: The request signature we calculated does not match the signature you provided.`
when trying to run multiple parts upload in parallel. The same code runs without any issues when uploading parts in a single thread.

### Expected Behavior

No error should be returned.

### Current Behavior

API return following error:
`peration error Glacier: UploadMultipartPart, https response error StatusCode: 403, RequestID: <request id>, api error InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

### Reproduction Steps

I have the following function to upload a part:
```
func uploadPart(client *glacier.Client, account string, vault string, uploadId string, part part) ([]byte, error) {
	input := glacier.UploadMultipartPartInput{
		AccountId: &account,
		Body:      part.reader,
		VaultName: &vault,
		UploadId:  &uploadId,
		Range:     &part.contentRange,
	}

	r, err := client.UploadMultipartPart(context.TODO(), &input)
	if err != nil {
		return nil, err
	}

	if *r.Checksum != part.sha256 {
		return nil, errors.New("Checksums mismatch")
	}

	return hex.DecodeString(*r.Checksum)
}
```

Where `part` is defined as:
```
type part struct {
	reader       io.Reader
	sha256       string
	contentRange string
	partNo       int64
}
```

If I run `uploadPart` multiple times in the goroutine, I get an error about the signature mismatch.

### AWS Go SDK V2 Module Versions Used

github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/config@v1.26.2
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/credentials@v1.16.13
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.14.10
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/internal/ini@v1.7.2
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/service/glacier@v1.19.5
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.10.4
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.10.9
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5
github.com/jczornik/glacier_backup github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6
github.com/jczornik/glacier_backup github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2@v1.24.0 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2@v1.24.0 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.24.0 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/credentials@v1.16.13
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.14.10
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/internal/ini@v1.7.2
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.10.4
github.com/aws/aws-sdk-go-v2/config@v1.26.2 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.10.9
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.14.10
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.10.4
github.com/aws/aws-sdk-go-v2/credentials@v1.16.13 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.10.9
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.14.10 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.14.10 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.14.10 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/glacier@v1.19.5 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/service/glacier@v1.19.5 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9
github.com/aws/aws-sdk-go-v2/service/glacier@v1.19.5 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9
github.com/aws/aws-sdk-go-v2/service/glacier@v1.19.5 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/service/glacier@v1.19.5 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.10.4 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.10.9 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.10.9 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.10.9 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9
github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9
github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/service/sso@v1.18.5 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.21.5 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6 github.com/aws/aws-sdk-go-v2@v1.24.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.2.9
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.5.9
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.10.4
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.10.9
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6 github.com/aws/smithy-go@v1.19.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.26.6 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.19.0 github.com/google/go-cmp@v0.5.8

### Compiler and Version used

go version go1.21.5 linux/amd64

### Operating System and version

Debian GNU/Linux 12 (bookworm)

**Comment by RanVaknin** [comment]
Hi @jczornik ,

Thanks for your patience. I'm looking into this and will update you with my findings. 

All the best,
Ran~

**Comment by RanVaknin** [comment]
Hi @jczornik ,

Do you mind sharing a more complete code sample of both the non current calls that succeeds, and then the concurrent one that fails? 

Thanks!
Ran~
