### ISSUE TITLE
Impossible to generate clients for non-aws services due to dependency on aws.api#Service trait

### ISSUE THREAD

**Issue by Petroniuss** [aws/aws-sdk-go-v2#2522]
### Describe the feature

Looks like the only way to generate go smithy clients is to build both projects [source - codegen: Move protocol generators out of aws-sdk-go-v2 into smithy-go](https://github.com/aws/smithy-go/issues/458):
- smithy-go
- aws-sdk-go-v2

However, it's not possible to generate basic http clients without modifying source of aws-sdk-go-v2. The reason for that is that most `GoIntegration`s  specific to AWS residing in `aws-sdk-go-v2` do something similar to lines below:
```
 ServiceShape serviceShape = settings.getService(model);
 return serviceShape.expectTrait(ServiceTrait.class).getSdkId();
```
 
This causes the code generation to fail if the service isn't annotated with [aws.api#Service](https://smithy.io/2.0/aws/aws-core.html#aws-api-service-trait).

Relevant parts of the stacktrace showing the problem:

 ```
software.amazon.smithy.model.node.ExpectationNotMetException: 
Expected shape example#ExampleClient to have a trait 
software.amazon.smithy.aws.traits.ServiceTrait...
```

 ```
...
 at software.amazon.smithy.model.shapes.Shape.lambda$expectTrait$0(Shape.java:332)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at software.amazon.smithy.model.shapes.Shape.expectTrait(Shape.java:332)
	at software.amazon.smithy.aws.go.codegen.AwsSdkServiceId.processServiceId(AwsSdkServiceId.java:33)
	at software.amazon.smithy.go.codegen.ServiceGenerator.generateMetadata(ServiceGenerator.java:109)
	at software.amazon.smithy.go.codegen.ServiceGenerator.generate(ServiceGenerator.java:96)
```
	

### Use Case

Trying to generate go clients using smithy for non-aws services.

### Proposed Solution

Would it be possible to first check if a service has the `aws.api#Service` trait and if it doesn't then skip applying the integration? This is how I've seen other aws smithy repos do it. Of course I'd prefer to just use `smithy-go` but this seems to be blocked/not prioritized.,

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

2024-02-28 release

### Go version used

1.20

**Comment by lucix-aws** [comment]
This repository's codegen is not consumer-facing, and is not written to be reusable for arbitrary smithy models. Its sole purpose is to effect codegen of AWS SDKs. The only "artifact" produced by this repository is the runtimes and service clients for public AWS services.

With that context, the integrations are correct as written, as the trait is necessary to correctly generate AWS service clients.

**Comment by Petroniuss** [comment]
Hi @lucix-aws,
thanks for your answer - makes sense.

Would you be able to point me what would be the correct way to consume [smithy-go](https://github.com/aws/smithy-go) - would depending on smithy-go and implementing restJson protocol using tools provided in smithy-go be a good idea?
