### ISSUE TITLE
operation error SQS: ReceiveMessage, get identity: get credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 400(short issue description)

### ISSUE THREAD

**Issue by EnzoNguyenMF** [aws/aws-sdk-go-v2#2544]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

Today, our service has been crashed suddenly. And we got the error.
`
smithy.OperationError operation error SQS: ReceiveMessage, get identity: get credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 28f9ea25-8179-45a4-a569-1b25baf9607e, api error Throttling: Rate exceeded
`

### Expected Behavior

Service can working normally.

### Current Behavior

Service crash.

### Reproduction Steps

We've unexpected shutting down error.

### AWS Go SDK V2 Module Versions Used

```
github.com/aws/aws-sdk-go-v2 v1.24.1
github.com/aws/aws-sdk-go-v2/config v1.26.6
github.com/aws/aws-sdk-go-v2/service/sqs v1.29.7
```

```
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.4.14 // indirect
github.com/aws/aws-sdk-go-v2/credentials v1.16.16 // indirect
github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.14.11 // indirect
github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.10 // indirect
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.10 // indirect
github.com/aws/aws-sdk-go-v2/internal/ini v1.7.3 // indirect
github.com/aws/aws-sdk-go-v2/internal/v4a v1.1.6 // indirect
github.com/aws/aws-sdk-go-v2/service/dynamodb v1.21.4 // indirect
github.com/aws/aws-sdk-go-v2/service/eventbridge v1.20.4 // indirect
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.4 // indirect
github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.1.38 // indirect
github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.7.34 // indirect
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.10.10 // indirect
github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.15.6 // indirect
github.com/aws/aws-sdk-go-v2/service/kinesis v1.18.4 // indirect
github.com/aws/aws-sdk-go-v2/service/s3 v1.40.2 // indirect
github.com/aws/aws-sdk-go-v2/service/sfn v1.19.4 // indirect
github.com/aws/aws-sdk-go-v2/service/sns v1.21.4 // indirect
github.com/aws/aws-sdk-go-v2/service/sso v1.18.7 // indirect
github.com/aws/aws-sdk-go-v2/service/ssooidc v1.21.7 // indirect
github.com/aws/aws-sdk-go-v2/service/sts v1.26.7 // indirect
github.com/aws/smithy-go v1.19.0 // indirect
```

### Compiler and Version used

1.21.3

### Operating System and version

Linux AMD

**Comment by RanVaknin** [comment]
Hi @EnzoNguyenMF ,

Thanks for reaching out. I'm sorry to hear that you are experiencing service errors. 
From the issue description it sounds like this happened all of a sudden, meaning, this didnt start happening after an SDK update? This sounds like an intermittent server error. 

Can you tell us more about the nature of how this arises? Does this happen consistently, meaning you are not able to assume role at all? Is it happening intermittently? Or is it now solved and not happening anymore?

Thanks,
Ran~
