### ISSUE TITLE
S3 APIs missing paginators

### ISSUE THREAD

**Issue by mxk** [aws/aws-sdk-go-v2#256]
### Version of AWS SDK for Go?
v0.6.0

### Version of Go (`go version`)?
v1.11.4

### What issue did you see?
Except for `ListObjectsV2`, none of the other S3 API methods that use `ContinuationToken` define a paginator. These include: `ListBucketAnalyticsConfigurations`, `ListBucketInventoryConfigurations`, and `ListBucketMetricsConfigurations`.

**Comment by jasdel** [comment]
Thanks for reporting this issue @mxk. The Amazon S3 service does not currently model paginators for these API operations that the SDK can consume to auto generate the pagination functionality. I've reached out to the service team to request they add this to their service.  The SDK will automatically include these paginators once the service's models are updated
