### ISSUE TITLE
Set preview text for emails that will show only in subject line not in the top of email body.

### ISSUE THREAD

**Issue by Gurarkpreet** [aws/aws-sdk-go-v2#2564]
### Describe the feature

I was finding out to set preview text for emails. I have tried many things like - setting preview_text and email_template in Body field of Message but it show preview text in the beginning of the email body. But I need to show preview text only in subject line not in the top of email body.
Is there any way to set preview_text only in subject line. If yes, then please let me know I did not find it in documentation and tried many ways to get a solution. 

### Use Case

I want to send email with Preview_text that will visible with subject in subject line but not in the body of the email.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

"github.com/aws/aws-sdk-go-v2/aws"
"github.com/aws/aws-sdk-go-v2/config"
"github.com/aws/aws-sdk-go-v2/feature/s3/manager"
"github.com/aws/aws-sdk-go-v2/service/s3"
"github.com/aws/aws-sdk-go-v2/service/s3/types"
"github.com/aws/aws-sdk-go-v2/service/ses"
"github.com/aws/aws-sdk-go-v2/service/sesv2"
"github.com/aws/aws-sdk-go-v2/service/sesv2/types"

### Go version used

go version go1.20.7 linux/amd64

**Comment by lucix-aws** [comment]
The SDKs cannot field requests of this nature, as we do not own the APIs dictated by the service teams.
