### ISSUE TITLE
PartiQl for the go sdk

### ISSUE THREAD

**Issue by hubo123** [aws/aws-sdk-go-v2#2568]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

Hi team,

I used PartiQL to select data with golang sdk,  and I used contains function

such as "SELECT  product_id  FROM traffic_logger WHERE uuid='94b0eff8-b8fb-443d-a567-c57a65730277'  AND contains(product_id, '1') ".  The product_id field type is string.

If product_id field value is "0", we shouldn't return the result, but the go sdk still return it. Can you help me to check it?

Thanks.

### Expected Behavior

If the product_id field value is "0", we shouldn't return it.

### Current Behavior

We return the result If the field value is "0" and using contains(product_id, '1') where condition to select, 

### Reproduction Steps

Use this SQl 
SELECT  product_id  FROM traffic_logger WHERE uuid='94b0eff8-b8fb-443d-a567-c57a65730277'  AND contains(product_id, '1')

### AWS Go SDK V2 Module Versions Used

Use go sdk v2 

### Compiler and Version used

v2

### Operating System and version

windows

**Comment by lucix-aws** [comment]
The Go SDK team is not familiar with the PartiQI software described in the issue, this isn't something we can assist with.

**Comment by hubo123** [comment]
> The Go SDK team is not familiar with the PartiQI software described in the issue, this isn't something we can assist with.

I used go sdk to run sql, why do you say go sdk team is not familar with the dyanamodb partiql?
