### ISSUE TITLE
Support API Gateway Version 2018-11-29

### ISSUE THREAD

**Issue by sudhirj** [aws/aws-sdk-go-v2#257]
Specifically the announcements here https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/ - both in terms of calling the API gateway methods and any lambda event handler structs.

**Comment by jasdel** [comment]
Closing this issue as The SDK was updated in v0.6.0 with the updated API gateway models. Thanks for reporting this issue.
