### ISSUE TITLE
EventBridge/CloudWatch Events: Add support for time zones

### ISSUE THREAD

**Issue by rg-tui** [aws/aws-sdk-go-v2#2592]
### Describe the feature

The api now supports time zones in the EventBridge scheduled rule. Please add support for time zones.
https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/

### Use Case

We are not able to use the CDK to create EventBridge scheduled rules with time zones. This is frustrating because the time changes twice every year.

### Proposed Solution

Add "ScheduleExpressionTimezone" here:
https://github.com/aws/aws-sdk-go-v2/blob/9632aaa29f1d1f2b797628b2b8163de600b81aa1/codegen/sdk-codegen/aws-models/eventbridge.json

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 github.com/aws/smithy-go@v1.20.2
github.com/aws/aws-sdk-go-v2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2 go@1.20
github.com/jmespath/go-jmespath@v0.4.0 github.com/jmespath/go-jmespath/internal/testify@v1.5.1
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/davecgh/go-spew@v1.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/pmezard/go-difflib@v1.0.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/stretchr/objx@v0.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 gopkg.in/yaml.v2@v2.2.8
gopkg.in/yaml.v2@v2.2.8 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405

### Go version used

go version go1.22.1 windows/amd64

**Comment by RanVaknin** [comment]
Hi @rg-tui ,

Scheduler is its own client https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/scheduler and is separated from the EventBridge client.

Thanks,
Ran~

**Comment by LukeLaScala** [comment]
Helped me also realize this was in a separate package.
