### ISSUE TITLE
PresignedPutObject ignores ChecksumAlgorithm

### ISSUE THREAD

**Issue by xxgreg** [aws/aws-sdk-go-v2#2610]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

If I use `PresignPutObject` together with `ChecksumAlgorithm` set to `ChecksumSHA256`, a url is created to which I can upload files which do not match the checksum.

When I look in the AWS console, the files have "Additional checksums" set as "Off".

I expect to get a 403 or 400 in response to this request.

```
	in := &s3.PutObjectInput{
		Bucket:                       aws.String(bucket),
		Key:                             aws.String(key),
		Body:                           bytes.NewReader(body),
		ChecksumAlgorithm: types.ChecksumAlgorithmSha256,
                 // A checksum which doesn't match the content.
		ChecksumSHA256:    aws.String("bad+nDnO0vTnour8G+5YPPx4tLMvxgS0K3ZBusogZxU="),
	}

	req, err := psc.PresignPutObject(ctx, in, s3.WithPresignExpires(time.Hour))
```

Here is a modified copy of the HTTP request and response:
```
PUT /cxvxcvewr?X-Amz-Algorithm=AWS4-HMAC-SHA256
  ... &X-Amz-Checksum-Sha256=bad%2BnDnO0vTnour8G%2B5YPPx4tLMvxgS0K3ZBusogZxU%3D
  ... &X-Amz-Credential=xxxxxxxxxxxxxxxxxx%2Fap-southeast-2%2Fs3%2Faws4_request
  ... &X-Amz-Date=20240418T115205Z
  ... &X-Amz-Expires=3600
  ... &X-Amz-Sdk-Checksum-Algorithm=SHA256
  ... &X-Amz-Security-Token=xxxxxxxxxxxxxxxxxx
  ... &X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost
  ... &x-id=PutObject
  ... &X-Amz-Signature=xxxxxxxxxxxxxxxxxx HTTP/1.1
Host: xxxxxxxxxxxxxxxxxx.s3.ap-southeast-2.amazonaws.com
User-Agent: Go-http-client/1.1
Content-Length: 185
Content-Type: application/octet-stream
Accept-Encoding: gzip


And both that morning equally lay
In leaves no step had trodden black.
Oh, I kept the first for another day!
Yet knowing how way leads on to way,
I doubted if I should ever come back.


HTTP/1.1 200 OK
Content-Length: 0
Date: Thu, 18 Apr 2024 11:52:06 GMT
Etag: "ccabdc72853be781e1c1819ac6d13d7e"
Server: AmazonS3
X-Amz-Id-2: xxxxxxxxxxxxxxxxxx
X-Amz-Request-Id: xxxxxxxxxxxxxxxxxx
X-Amz-Server-Side-Encryption: AES256


```

I was able to get this to work correctly, i.e. fail for bad checksums, and enable "Additional Checksums", by setting `DisableHeaderHoisting` on the presigner. 

So I'm not sure if this is a bug, and `DisableHeaderHoisting` should always be set, or perhaps a doc bug. 

Or perhaps I'm just using it wrong. Any tips appreciated.

An example of setting `DisableHeaderHoisting`. There must be a better way - but that's all I could figure out.

```
	checksumBytes := sha256.Sum256(body)
	checksum := base64.StdEncoding.EncodeToString(checksumBytes[:])

	withPresigner := func(opt *s3.PresignOptions) {
		opt.Presigner = v4.NewSigner(func(so *v4.SignerOptions) {
			// I copied the Default settings.
			o := s3c.Options()
			so.Logger = o.Logger
			so.LogSigning = o.ClientLogMode.IsSigning()
			so.DisableURIPathEscaping = true

			// This is the magic sauce which makes SHA256 checksums work.
			so.DisableHeaderHoisting = true
		})
	}

	psc := s3.NewPresignClient(s3c)

	in := &s3.PutObjectInput{
		Bucket:  aws.String(bucket),
		Key:   aws.String(key),
		Body:  bytes.NewReader(body),
		ChecksumAlgorithm: types.ChecksumAlgorithmSha256,
		ChecksumSHA256:    aws.String(checksum),
		// Try it with an incorrect checksum to make sure it fails.
		//ChecksumSHA256: aws.String("bad+nDnO0vTnour8G+5YPPx4tLMvxgS0K3ZBusogZxU="),
		ContentLength: aws.Int64(int64(len(body))),
	}

	req, err := psc.PresignPutObject(ctx, in, s3.WithPresignExpires(time.Hour), withPresigner)
```

Example of being denied due to an invalid checksum:
```
PUT /cxvxcvewr?X-Amz-Algorithm=AWS4-HMAC-SHA256
 ... &X-Amz-Credential=xxxxxxxxxxxxxxx%2Fap-southeast-2%2Fs3%2Faws4_request
 ... &X-Amz-Date=20240418T120519Z&X-Amz-Expires=3600&X-Amz-Security-Token=xxxxxxxxxxxxxxx
 ... &X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-checksum-sha256%3Bx-amz-sdk-checksum-algorithm
 ... &x-id=PutObject
 ... &X-Amz-Signature=xxxxxxxxxxxxxxx HTTP/1.1
Host: xxxxxxxxxxxxxxx.s3.ap-southeast-2.amazonaws.com
User-Agent: Go-http-client/1.1
Content-Length: 185
Content-Type: application/octet-stream
X-Amz-Checksum-Sha256: bad+nDnO0vTnour8G+5YPPx4tLMvxgS0K3ZBusogZxU=
X-Amz-Sdk-Checksum-Algorithm: SHA256
Accept-Encoding: gzip


And both that morning equally lay
In leaves no step had trodden black.
Oh, I kept the first for another day!
Yet knowing how way leads on to way,
I doubted if I should ever come back.
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 18 Apr 2024 12:05:19 GMT
Server: AmazonS3
X-Amz-Id-2: xxxxxxxxxxxxxxx
X-Amz-Request-Id: xxxxxxxxxxxxxxx

12e
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BadDigest</Code><Message>The SHA256 you specified did not match the calculated checksum.</Message>xxxxxxxxxxxxxxx</Error>
0


status 400 Bad Request
```

Successful upload Example:
```
PUT /cxvxcvewr?X-Amz-Algorithm=AWS4-HMAC-SHA256
    ... &X-Amz-Credential=xxxxxxxxxxxxxxxx%2Fap-southeast-2%2Fs3%2Faws4_request
    ... &X-Amz-Date=20240418T121120Z
    ... &X-Amz-Expires=3600
    ... &X-Amz-Security-Token=xxxxxxxxxxxxxxxx
    ... &X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-checksum-sha256%3Bx-amz-sdk-checksum-algorithm
    ... &x-id=PutObject
    ... &X-Amz-Signature=xxxxxxxxxxxxxxxx HTTP/1.1
Host: xxxxxxxxxxxxxxxx.s3.ap-southeast-2.amazonaws.com
User-Agent: Go-http-client/1.1
Content-Length: 185
Content-Type: application/octet-stream
X-Amz-Checksum-Sha256: FcQS6qqASH2wqjlYCJ5H/cBhDqZTfKQcRBkiToJpwho=
X-Amz-Sdk-Checksum-Algorithm: SHA256
Accept-Encoding: gzip


And both that morning equally lay
In leaves no step had trodden black.
Oh, I kept the first for another day!
Yet knowing how way leads on to way,
I doubted if I should ever come back.
HTTP/1.1 200 OK
Content-Length: 0
Date: Thu, 18 Apr 2024 12:11:21 GMT
Etag: "ccabdc72853be781e1c1819ac6d13d7e"
Server: AmazonS3
X-Amz-Checksum-Sha256: FcQS6qqASH2wqjlYCJ5H/cBhDqZTfKQcRBkiToJpwho=
X-Amz-Id-2: xxxxxxxxxxxxxxxx
X-Amz-Request-Id: xxxxxxxxxxxxxxxx
X-Amz-Server-Side-Encryption: AES256


status 200 OK
```

### Expected Behavior

I expect to get a 403 or 400 when the checksum does not match the body of the put object request.

### Current Behavior

The put object request completes and the file is uploaded even though the checksum does not match.

### Reproduction Steps

I wrote some code here which demonstrates the workaround.

https://github.com/xxgreg/s3_presign_put_sha256

### AWS Go SDK V2 Module Versions Used

go 1.22.2

require (
        github.com/aws/aws-sdk-go-v2 v1.26.1 // indirect
        github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.6.2 // indirect
        github.com/aws/aws-sdk-go-v2/config v1.27.11 // indirect
        github.com/aws/aws-sdk-go-v2/credentials v1.17.11 // indirect
        github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.16.1 // indirect
        github.com/aws/aws-sdk-go-v2/internal/configsources v1.3.5 // indirect
        github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.6.5 // indirect
        github.com/aws/aws-sdk-go-v2/internal/ini v1.8.0 // indirect
        github.com/aws/aws-sdk-go-v2/internal/v4a v1.3.5 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.11.2 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.3.7 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.11.7 // indirect
        github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.17.5 // indirect
        github.com/aws/aws-sdk-go-v2/service/s3 v1.53.1 // indirect
        github.com/aws/aws-sdk-go-v2/service/sso v1.20.5 // indirect
        github.com/aws/aws-sdk-go-v2/service/ssooidc v1.23.4 // indirect
        github.com/aws/aws-sdk-go-v2/service/sts v1.28.6 // indirect
        github.com/aws/smithy-go v1.20.2 // indirect
)

### Compiler and Version used

go version go1.22.2 darwin/arm64

### Operating System and version

Mac OS 14.4.1

**Comment by RanVaknin** [comment]
Hi @xxgreg ,

Thanks for reaching out. This is a [known issue](https://github.com/aws/aws-sdk/issues/338) with S3.
Ideally S3 should support both providing headers as a query string or as headers for presigned URL but as you saw it is indeed not working as expected.

I'll try to ping the right people once again and raise visibility for this issue.

Since this is a know behavior and we already have a tracking issue for this problem, Im going to close this as a duplicate. 
Please feel free to comment on the other issue.

Thanks again!
Ran~

**Comment by thelovekesh** [comment]
hey @RanVaknin, I don't think there is a open ticket to track this issue, and this undocumented behavior is a serious security issue since sdk users assume that checksum verification is enabled by default but it's not until you enable `DisableHeaderHoisting`.

I think this issue should be re-opened to track the issue.
