### ISSUE TITLE
How to set a field to NULL using the Redshift Data API?

### ISSUE THREAD

**Issue by JoseAngel1196** [aws/aws-sdk-go-v2#2621]
### Describe the issue

AWS indicates that you cannot set a value to NULL nor can you set a zero-length value. Is there a way to handle this using the Redshift Data API?

My code:

```
if value == "" {
				paramValue = "null"
			} else {
				paramValue = fmt.Sprintf("%v", value)
			}
			parameters = append(parameters, types.SqlParameter{
				Name:  aws.String(paramName),
				Value: aws.String(paramValue),
			})
```

As you can see, if the value is empty, we're using a literal string 'null' and would prefer to store it as NULL. How can I achieve this?

### Links

https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html

**Comment by lucix-aws** [comment]
https://github.com/aws/aws-sdk-go-v2/discussions/2619
