### ISSUE TITLE
When sharing a svc handler in my prog, should my handler be method or pointer receiver?

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#263]
If i use "methods" with type handler struct { S3 *s3.S3 }, as opposed to "pointer receivers", does it make any difference in real terms to use of the SDK?

https://s.natalian.org/2019-01-11/method-pointer-receiver.mp4

Apologies if I have the terminology totally wrong. Let me know if there is some best practices to follow.

**Comment by jasdel** [comment]
I suggest using a pointer receiver just in case. Currently the client types do not hold state, but this may change in the future with the addition of concepts like support for rate limiting within a client.
