### ISSUE TITLE
package docs for github.com/aws/aws-sdk-go-v2/aws/signer/v4 are malformed

### ISSUE THREAD

**Issue by rittneje** [aws/aws-sdk-go-v2#2639]
### Describe the issue

The package docs for github.com/aws/aws-sdk-go-v2/aws/signer/v4 are jumbled up.

![image](https://github.com/aws/aws-sdk-go-v2/assets/28784688/92974f92-cfd6-46c1-947e-74ebd7aa4577)

As you can see, it has half a sentence, followed by a random code block, which itself contains the first half of another sentence.

My _guess_ is that first sentence is supposed to say "Generally using the signer outside of the SDK should not require any additional _code_." But some automated tooling is misinterpreting the word "code" to signal a code block.

### Links

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/signer/v4

**Comment by lucix-aws** [comment]
It appears to have been copied from [its v1 predecessor](https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/signer/v4) - we can see what it used to say there. I'm going to tweak the docs here in general, they need some updating.
