### ISSUE TITLE
DescribeAvailablePatches SSM api - incorrect type for the field epoch

### ISSUE THREAD

**Issue by svagner** [aws/aws-sdk-go-v2#2655]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
```
error while getting available patches","error":"SerializationError: failed decoding JSON RPC response\n\tstatus code: 200, request id: 5ff26977-ddee-4ddf-82cf-c88291a6cac0\ncaused by: unsupported value: <nil> (*int64)
```

**Version of AWS SDK for Go?**

`v1.36.15`

**Version of Go (`go version`)?**

`go version go1.16.4 linux/amd64`

**To Reproduce (observed behavior)**

```
	if err := DescribeAvailablePatchesPagesWithContext(ctx, &DescribeAvailablePatchesInput{
		Filters: []*PatchOrchestratorFilter{
			{
				Key: aws.String("PRODUCT"),
				Values: []*string{
					aws.String("AmazonLinux2.0"),
				},
			},
		},
		MaxResults: aws.Int64(50),
	}, func(result *DescribeAvailablePatchesOutput, lastPage bool) bool {
		res = append(res, result.Patches...)
		return !lastPage
	}); err != nil {
		return nil, err
	}

```

**Expected behavior**

The method should be finished without error

**Comment by RanVaknin** [comment]
Hi there,

I'm Not sure why @ashishdhingra is able to reproduce this with .NET. I tested this with the Go SDK and can see that the response field `Epoch` is set to return a value a `string` instead of a `number` as described in the API model.

I have created an internal ticket with the SSM service team ( P137583768) and will update you when we hear back from them. Sorry for the delay.
 
Ran~

**Comment by RanVaknin** [comment]
Hi,

The service had acknowledged this needs to get fixed. Since it is not actionable by the Go SDK team, Im going to go ahead and close this. 
Thanks,
Ran~
