### ISSUE TITLE
OK I give in how do I actually use this sdk to get a parameter from the parameter store?

### ISSUE THREAD

**Issue by Chanonry** [aws/aws-sdk-go-v2#267]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2.0

### Version of Go (`go version`)?
1.11.5

### What issue did you see?
No idea, sdk is impenetrable

### Steps to reproduce

If you have have an runnable example, please include it.

**Comment by jasdel** [comment]
Hi @Chanonry thanks for reaching out. Could you clarify which service you're using? Is it the [AWS Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html)? The SDK provides clients for many AWS services. The best place to find out how to use a service's specific client is via the client's package, and service's API reference guide. 

*  [SSM service's client documentation](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/ssm)
* [SSM's API reference guide](https://docs.aws.amazon.com/systems-manager/latest/APIReference/Welcome.html)

**Comment by kaihendry** [comment]
This is how I get parameter stores value out https://github.com/unee-t/env/blob/master/main.go

**Comment by jasdel** [comment]
Thanks for sharing the example @kaihendry.

**Comment by Chanonry** [comment]
I appreciate the example, thanks

Thanks for the document references but actually that is aws great failing. There is a reference with a couple of examples and that's it.  Hardly full coverage.

The biggest problems I have by far are every time I interact with aws systems. It takes too long to do things that should be straightforward.

You can close this

**Comment by jasdel** [comment]
Thanks for the the additional feedback @Chanonry. One of the best ways to submit your feedback on using AWS APIs is via the `Feedback` button in the bottom left hand corner on the AWS API reference and Guide web pages. This feedback will be sent to the documentation  and service team for the service.
