### ISSUE TITLE
Support KRaft mode for MSK

### ISSUE THREAD

**Issue by LittleWat** [aws/aws-sdk-go-v2#2671]
### Describe the feature

AWS supported KRaft mode about two weeks ago
- [Introducing support for Apache Kafka on Raft mode (KRaft) with Amazon MSK clusters | AWS Big Data Blog](https://aws.amazon.com/jp/blogs/big-data/introducing-support-for-apache-kafka-on-raft-mode-kraft-with-amazon-msk-clusters/)

and it would be nice if this is supported in the awscli/terraform as well.

### Use Case

- Terraform
  - I made an issue: https://github.com/hashicorp/terraform-provider-aws/issues/37877

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

none

### Go version used

none

**Comment by lucix-aws** [comment]
What exactly is missing in the SDK that prevents you from doing this? According to the terraform person's response in the issue you opened there, you can enable this new feature just by setting a new value on a field in an existing operation.

**Comment by LittleWat** [comment]
Thanks for your reply!
I misunderstood that version only contains version information. (not includes the metadata mode.) 🤦 
This would be an issue, let me close this 🙇
