### ISSUE TITLE
Duplicate Go Pkg Docs

### ISSUE THREAD

**Issue by gogingersnap777** [aws/aws-sdk-go-v2#2672]
### Describe the issue

There are 2 versions of the go docs. `aws-sdk-go-V2` should be removed.

### Links

Correct: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2
Incorrect : https://pkg.go.dev/github.com/aws/aws-sdk-go-V2

**Comment by lucix-aws** [comment]
Unfortunate but we're not going to be able to do anything about this. It appears the repository was renamed from V2 -> v2 early on (it redirects) and getting that repository re-created just to be able to push the retract statements isn't possible internally.
