### ISSUE TITLE
MIGRATION ISSUE: EC2 AttachmentStatus has improper values

### ISSUE THREAD

**Issue by pavlo-strokov-scylladb** [aws/aws-sdk-go-v2#2675]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for similar migration issues.

### Go Version Used

Go 1.22

### Describe the Migration Issue

I have replaced the old call `DescribeInternetGatewaysWithContext` with the new one `DescribeInternetGateways`. The upgraded version return `DescribeInternetGatewaysOutput`, it has `InternetGateways []types.InternetGateway` field. The type `InternetGateway` has field `Attachments []InternetGatewayAttachment` and type `InternetGatewayAttachment` has field `State AttachmentStatus`. The [AttachmentStatus](https://github.com/aws/aws-sdk-go-v2/blob/
de2612e/service/ec2/types/enums.go#L501-L509) is enum type that has predefined values.  
What I can see it doesn't have `available` value that we are using. Also, `available` is the only value mentioned in the EC2 cli [documentation](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-internet-gateways.html#output).

### Observed Differences/Errors

SDK v2 provides wrong enum values.

**Comment by lucix-aws** [comment]
Note not strictly a migration issue since the list of enum variants comes from the service model (i.e. it's the same wrong list in both v1 and v2).

**Comment by lucix-aws** [comment]
The modeling here definitely seems incorrect based on the documentation mentioning the nonexistent "available" state.

You can work around this with a typecast for the time being.

```go
types.AttachmentStatus("available")
```

Upstreamed to ec2 @ `V1414968710`.
