### ISSUE TITLE
non-`io.Seeker` body in streaming-blob operation causes content-length to not be set, resulting in 5xx

### ISSUE THREAD

**Issue by ivanshiras** [aws/aws-sdk-go-v2#2683]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

I've seen that there have been previous reports of this issue, e.g. https://github.com/aws/aws-sdk-go-v2/issues/1108

However the resolution is missing what feels like the actual problem: the SDK clearly provides `io.Reader` as the interface and then returns an error when given a Body that implements that interface.

I cannot use an `http.Response.Body`  as the `PutObjectInput.Body`, which is a bug either in implementation of the S3 client `PutObject` method or with the Go typing.

### Expected Behavior

If the SDK says that the `PutObjectInput` supports `io.Reader`: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#PutObjectInput it should support them.

Otherwise the SDK should state what interface it actually supports.

### Current Behavior

SDK operation returns a 501, `api error NotImplemented: A header you provided implies functionality that is not implemented`

### Reproduction Steps

- Make an http request and store the response body (io.ReadCloser)
- Use that response body as the `PutObjectInput.Body`

### AWS Go SDK V2 Module Versions Used

"github.com/aws/aws-sdk-go-v2/service/s3"

### Compiler and Version used

go version go1.22.4 darwin/arm64

### Operating System and version

MacOS 14.5 (23F79)

**Comment by lucix-aws** [comment]
> SDK operation returns a 501, api error NotImplemented: A header you provided implies functionality that is not implemented

FYI this is unrelated. The error you get when using a non-seekable body is going to be different (we're going to detect that and return it as an error before even sending the request).

This is a known pain point as you've indicated, I'm going to spawn a dedicated issue for tracking.

**Comment by lucix-aws** [comment]
#2685

**Comment by lucix-aws** [comment]
Trivially reproducible:

```go
package main

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

type reader []byte

func (r reader) Read(p []byte) (n int, err error) {
	copy(p, r)
	return len(r), nil
}

func (r reader) Seek(offset int64, whence int) (int64, error) {
	return 0, nil
}

func main() {
	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		panic(err)
	}

	svc := s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.ClientLogMode = aws.LogRequest
	})
	_, err = svc.PutObject(context.Background(), &s3.PutObjectInput{
		Bucket: aws.String("bucket"),
		Key:    aws.String("key"),
		Body:   reader("foo"),
	})
	if err != nil {
		panic(err)
	}
}
```

If you make this request as-is, it will succeed. **If you remove the `Seek` implementation from `reader`, we will not set content-length and thus the request will fail with a 501** (at least that's what S3 does - other services may behave differently).

**Comment by lucix-aws** [comment]
@ivanshiras note that if you're streaming from another S3 response (or you know the content length yourself some other way), you can get around this by just setting `ContentLength` on the input directly (hardcoded in this example, but you'd pass it in from the response etc.):

```go
package main

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

type reader []byte

func (r reader) Read(p []byte) (n int, err error) {
	copy(p, r)
	return len(r), nil
}

// no seek

func main() {
	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		panic(err)
	}

	svc := s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.ClientLogMode = aws.LogRequest
	})
	_, err = svc.PutObject(context.Background(), &s3.PutObjectInput{
		Bucket: aws.String("bucket"),
		Key:    aws.String("key"),
		Body:   reader("foo"),
		ContentLength: aws.Int64(3),
	})
	if err != nil {
		panic(err)
	}
}
```

**Comment by ivanshiras** [comment]
> @ivanshiras note that if you're streaming from another S3 response (or you know the content length yourself some other way), you can get around this by just setting `ContentLength` on the input directly (hardcoded in this example, but you'd pass it in from the response etc.):
> 
> ```go
> package main
> 
> import (
> 	"context"
> 
> 	"github.com/aws/aws-sdk-go-v2/aws"
> 	"github.com/aws/aws-sdk-go-v2/config"
> 	"github.com/aws/aws-sdk-go-v2/service/s3"
> )
> 
> type reader []byte
> 
> func (r reader) Read(p []byte) (n int, err error) {
> 	copy(p, r)
> 	return len(r), nil
> }
> 
> // no seek
> 
> func main() {
> 	cfg, err := config.LoadDefaultConfig(context.Background())
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	svc := s3.NewFromConfig(cfg, func(o *s3.Options) {
> 		o.ClientLogMode = aws.LogRequest
> 	})
> 	_, err = svc.PutObject(context.Background(), &s3.PutObjectInput{
> 		Bucket: aws.String("bucket"),
> 		Key:    aws.String("key"),
> 		Body:   reader("foo"),
> 		ContentLength: aws.Int64(3),
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> }
> ```

Thanks Luc, I switched to the using the S3 manager Uploader which doesn't have the issue and has some performance benefits where I don't need to parse the response into memory and/or disk before uploading.
