### ISSUE TITLE
 Unable to use apigatewaymanagementapi using sdk v2 1.19.11

### ISSUE THREAD

**Issue by zxl199409** [aws/aws-sdk-go-v2#2687]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'. 

### Expected Behavior

I don’t know why it is incompatible after the upgrade

### Current Behavior

impact test

### Reproduction Steps

1

### Additional Information/Context
```go
func init() {
	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		return
	}

	pushClient = apigatewaymanagementapi.NewFromConfig(cfg, func(o *apigatewaymanagementapi.Options) {
		o.EndpointResolver = apigatewaymanagementapi.EndpointResolverFromURL(imConfig.EnvVar.ApiGatewayEndpoint)
		o.HTTPClient = &http.Client{Transport: service.DefaultHTTPTransport()}
	})
}


	_, err := pushClient.PostToConnection(ctx, &apigatewaymanagementapi.PostToConnectionInput{
		ConnectionId: &connectionId,
		Data:         data,
	})


```

error！！！
PostToConnection error: operation error ApiGatewayManagementApi: PostToConnection, https response error StatusCode: 403, RequestID: 5192a476-9b9c-46f4-8e1d-aed5e7492917, api error InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'. 

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi v1.19.11

### Compiler and Version used

go 1.19

### Operating System and version

arm64

**Comment by RanVaknin** [comment]
Hi @zxl199409,

You mentioned "incompatible after the upgrade" does downgrading the SDK version resolve this issue for you?

Thanks,
Ran~

**Comment by timvlaer** [comment]
I saw the exact same issue using `github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi 1.23.2` 
I see the same issue on 1.18.1 and  1.16.5. Didn't try 1.17.x yet.

My original version was 1.10.15, but when I rollback to that version I get `not found, ResolveEndpointV2` so I am expecting another depency (`github.com/aws/aws-sdk-go-v2` or `github.com/aws/aws-sdk-go-v2/config`) is the culprit.

**Comment by timvlaer** [comment]
I brought everything back to `v1.16.14`, including the kinesis service dependency I wanted to add and triggered the update. 

For future ref: if you select the version tag in github, you can check the `go_module_metadata.go` in the services you need to see the corresponding versions at that release. Because the versions of the main project, services and config are not the same. I ended up with:

```
	github.com/aws/aws-sdk-go-v2 v1.16.14
	github.com/aws/aws-sdk-go-v2/config v1.17.5
	github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi v1.10.15
	github.com/aws/aws-sdk-go-v2/service/eventbridge v1.16.12
	github.com/aws/aws-sdk-go-v2/service/kinesis v1.15.17
```
This version is ancient ([2022-09-02]) so I'd love to go to a more recent version. Also, I don't know which exact version caused this issue. 

Happy to help with an upgrade if that'd help.

The versions I tried first, the latest and greatest, but that kept failing with the `InvalidSignatureException`
```
github.com/aws/aws-sdk-go-v2 v1.32.2
github.com/aws/aws-sdk-go-v2/config v1.28.0
github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi v1.23.2
github.com/aws/aws-sdk-go-v2/service/eventbridge v1.35.2
github.com/aws/aws-sdk-go-v2/service/kinesis v1.32.2
```

**Comment by nantiferov** [comment]
Just in case - root cause and solution to fix described here https://github.com/aws/aws-sdk-go-v2/issues/2370#issuecomment-1953308268
