### ISSUE TITLE
DynamoDB UnmarshalListOfMaps: "dynamodb" struct tag is not respected when json tag is present

### ISSUE THREAD

**Issue by pangminfu** [aws/aws-sdk-go-v2#270]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
github.com/aws/aws-sdk-go-v2 v0.7.0

### Version of Go (`go version`)?
go1.11 darwin/amd64

### What issue did you see?
Below **ItemQueue** struct can Unmarshal without issue:
```Go
type ItemQueue struct {
	Id string `dynamodb:"id"`
	Name      string `dynamodb:"name"`
	IsPublish string `dynamodb:"is_publish`
}
```
Below **ItemQueue** struct failed to Unmarshal:
```Go
type ItemQueue struct {
	Id string `json:"id" dynamodb:"id"`
	Name      string `json:"name" dynamodb:"name"`
	IsPublish string `json:"name" dynamodb:"is_publish"`
}
```

**Note :** I read in [this doc](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbattribute) the struct tag should be `dynamodbav` but in my code if i'm using `dynamodbav` i will get error is it due to i am using older version 0.7.0 of v2? Should I upgrage it to **v2.0.0-preview.5**?

**Comment by jasdel** [comment]
Thanks for reaching out to us @pangminfu. The `v0.7.0` is the correct tag to be tracking. `v2.0.0-x` are deprecated since they are not compatible with Go's module versioning.

Could you describe the error you're getting, or pasting the error message.  `dynamodbav` is the correct tag to use.

**Comment by pangminfu** [comment]
Hi @jasdel ,

I think I don't have this issue anymore probably is due to some unknown issue. I tested no issue now.
