### ISSUE TITLE
Enable JSON Tags for Struct types

### ISSUE THREAD

**Issue by awatterson22** [aws/aws-sdk-go-v2#2710]
### Describe the feature

Hi, I would like to see if it is possible to add json tagging to the struct types like below:

```
type person struct {     
      name string `json:"name,omitempty"`
      age  int `json:"age,omitempty"`
}
```

### Use Case

I am trying to use the AWS Batch Types as part of a Kubernetes Controller and the tool [controller-gen](https://book.kubebuilder.io/reference/controller-gen) to generate CRDs expects JSON tags. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/batch v1.41.1

### Go version used

1.22

**Comment by lucix-aws** [comment]
The lack of tags is intentional. JSON tags have no meaning within the context of the SDK where they're defined - we're not going to add them for the sake of compatibility with other arbitrary software.
