### ISSUE TITLE
MIGRATION ISSUE: `imagebuilder.LaunchTemplateConfiguration.SetDefaultVersion` not sending `false` value

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-sdk-go-v2#2734]
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for similar migration issues.

### Go Version Used

go1.22.5

### Describe the Migration Issue

If the bool `SetDefaultVersion` field of the `imagebuilder.LaunchTemplateConfiguration` structure is set to `false`, that value is not being serialized and sent to the AWS service. The means that it is impossible to update the value from `true` to `false` via v2 of the Go SDK.

#### v1

```go
	apiObject := &imagebuilder.LaunchTemplateConfiguration{}

	if v, ok := tfMap["launch_template_id"].(string); ok && v != "" {
		apiObject.LaunchTemplateId = aws.String(v)
	}

	if v, ok := tfMap["default"].(bool); ok {
		apiObject.SetDefaultVersion = aws.Bool(v)
	}
```

#### v2

```go
	apiObject := &awstypes.LaunchTemplateConfiguration{}

	if v, ok := tfMap["launch_template_id"].(string); ok && v != "" {
		apiObject.LaunchTemplateId = aws.String(v)
	}

	if v, ok := tfMap["default"].(bool); ok {
		apiObject.SetDefaultVersion = v
	}
```

#### v1

```json
{"distributionConfigurationArn":"arn:aws:imagebuilder:us-west-2:...:distribution-configuration/ewbankkit-test-001","distributions":[{"launchTemplateConfigurations":[{"accountId":"...","launchTemplateId":"lt-00c9b21fbf4907bdb","setDefaultVersion":false}],"region":"us-west-2"}]}
```

#### v2

```json
{"distributionConfigurationArn":"arn:aws:imagebuilder:us-west-2:...:distribution-configuration/ewbankkit-test-001","distributions":[{"launchTemplateConfigurations":[{"accountId":"...","launchTemplateId":"lt-00c9b21fbf4907bdb"}],"region":"us-west-2"}]}
```

**Comment by ewbankkit** [comment]
Relates https://github.com/aws/aws-sdk/issues/736.

**Comment by RanVaknin** [comment]
Hi @ewbankkit ,

Thanks for raising this once again.
I will re-raise this issue internally to see how we should go about fixing this.

Ran~

**Comment by RanVaknin** [comment]
We have an internal ticket with the ec2 service team. Closing to consolidate with the cross SDK issue.

Thanks,
Ran~

**Comment by codymaust** [comment]
@RanVaknin has there been any recent update on this?
thanks!

**Comment by lucix-aws** [comment]
I'm not waiting for the service team to deliberate. Will patch this locally as we did for #2250.
