### ISSUE TITLE
imagebuilder service endpoints are missing from endpoints.json in specs file

### ISSUE THREAD

**Issue by mitkama** [aws/aws-sdk-go-v2#2740]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

"imagebuilder" service endpoints are missing from endpoints.json in the specs file.

https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json

### Expected Behavior

"imagebuilder" service endpoints should be present in endpoints.json.

https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json

### Current Behavior

"imagebuilder" service endpoints are missing from endpoints.json in the specs file.

https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json

### Reproduction Steps

"imagebuilder" service endpoints are missing from endpoints.json in the specs file

https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json

### Possible Solution

add "imagebuilder" service endpoints to endpoints.json

https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json

### AWS Go SDK V2 Module Versions Used

go version go1.22.3 darwin/arm64

### Compiler and Version used

go version go1.22.3 darwin/arm64

### Operating System and version

MacOS , Sonoma 14.5

**Comment by lucix-aws** [comment]
This isn't a defect - service-specific entries in this table are only needed for specifying non-standard endpoint schemes for the partition. The Imagebuilder endpoint scheme is the default, therefore it has no entries.

Note this endpoints.json resource is also no longer used by default - EndpointResolverV2 uses a separate rules "syntax" that lives in each service's API model (though the underlying dataset is related).

**Comment by mitkama** [comment]
@lucix-aws 

I have few questions , it would be really great if you are able to answer these questions.

1. Can I assume, if the entry is missing in endpoints.json, in that case, the endpoint schemes will be standard as
