### ISSUE TITLE
Add Support for AWS Cloud Map Service

### ISSUE THREAD

**Issue by john-s58** [aws/aws-sdk-go-v2#2760]
### Describe the feature

Add support for the CloudMap service https://docs.aws.amazon.com/cloud-map/latest/api/Welcome.html

### Use Case

At [CloudQuery](https://partners.amazonaws.com/partners/0010h00001kNW07AAG) we are developing an [AWS plugin](https://hub.cloudquery.io/plugins/source/cloudquery/aws/latest/docs) that enables users to fetch data about various AWS services.  We would like to extend this plugin to support the AWS Cloud Map service.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

1.30.4

### Go version used

1.22.4

**Comment by RanVaknin** [comment]
Hi @john-s58 ,

The SDK already has a client generated for cloud map, its called [ServiceDiscovery](https://github.com/aws/aws-sdk-go-v2/tree/main/service/servicediscovery).

Thanks,
Ran~

**Comment by john-s58** [comment]
Thank you !
