### ISSUE TITLE
Example of a date expression

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#280]
https://github.com/aws/aws-sdk-go-v2/tree/master/example/service/dynamodb/expression

I'm struggling to build an expression which filters my table "Due", by the key "when".

<img src="https://s.natalian.org/2019-03-27/1553678208_2560x1440.png" alt="dynamodb expression">

Ideally the Golang code could be generated from the console. :laughing: 

Also I can't help but think perhaps it's wiser to separate date and time since it's not easy to query by just date "2019-03-27" otherwise. That would be easier than battling hours to make a FilterExpression.

**Comment by jasdel** [comment]
Thanks for the question @kaihendry. You should suggest that the dynamoDB console page has a way to generate an SDK expression given the filter specified in the console. The `Feedback` link in the bottom left corner is a great way to do that.

With that said. I think something like the following is what you're looking for to create the Scan expression.

```go
// TODO May need to a adjust time to be UTC, or local depending on usecase.
myStartTime := time.Date(2019, 3, 21, 0, 0, 0, 0, nil)
myEndTime := time.Date(2019, 3, 28, 0, 0, 0, 0, nil)

expr, err := expression.NewBuilder().
	WithFilter(
		expression.And(
			expression.GreaterThanEqual(
				expression.Name("when"), expression.Value(myStartTime),
			),
			expression.LessThanEqual(
				expression.Name("when"), expression.Value(myEndTime),
			),
		),
	).
	Build()
if err != nil {
	return errors.Wrapf(err, "failed to create DynamoDB expression")
}

ddbSvc.Scan(&dynamodb.ScanInput{
	ExpressionAttributeNames:  expr.Names(),
	ExpressionAttributeValues: expr.Values(),
	FilterExpression:          expr.Filter(),
	TableName:                 aws.String("Due"),
})
```

**Comment by jasdel** [comment]
Closing this issue as the as it is a request for the AWS console UI.
