### ISSUE TITLE
XML Parsing mismatch in ListStorageLensConfiguration

### ISSUE THREAD

**Issue by ViBiOh** [aws/aws-sdk-go-v2#2801]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

The mapping of `s3control.ListStorageLensConfigurations` is not aligned with the response from the API.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

When I request `s3control.ListStorageLensConfigurations` I get the results in `StorageLensConfigurationList`.

### Current Behavior

When I request `s3control.ListStorageLensConfigurations`, `StorageLensConfigurationList` is always empty.

Payload response looks like this

```xml
<ListStorageLensConfigurationResult xmlns="http://awss3control.amazonaws.com/doc/2018-08-20/">
  <StorageLensConfiguration>
    <StorageLensArn>arn:aws:s3:eu-west-3:XXXX:storage-lens/vibioh-test</StorageLensArn>
    <Id>vibioh-test</Id>
    <HomeRegion>eu-west-3</HomeRegion>
    <IsEnabled>true</IsEnabled>
  </StorageLensConfiguration>
</ListStorageLensConfigurationResult>
```

### Reproduction Steps

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3control"
	"github.com/aws/smithy-go/logging"
)

func main() {
	cfg, err := config.LoadDefaultConfig(
		context.Background(),
		config.WithRegion("YOUR_REGION_HERE"),
		config.WithSharedConfigProfile("YOUR_PROFILE_HERE"),
		config.WithLogger(logging.LoggerFunc(func(_ logging.Classification, format string, v ...interface{}) {
			fmt.Printf(format, v...)
		})),
		config.WithClientLogMode(aws.ClientLogMode(aws.LogRequestWithBody|aws.LogResponseWithBody)),
	)
	if err != nil {
		log.Fatalf("unable to load SDK config: %s", err)
	}

	client := s3control.NewFromConfig(cfg)
	payload, err := client.ListStorageLensConfigurations(
		context.Background(), &s3control.ListStorageLensConfigurationsInput{
			AccountId: aws.String("YOUR_AWS_ACCOUNT"),
		},
	)
	if err != nil {
		panic(err)
	}

	fmt.Printf("\n%s\n", payload.StorageLensConfigurationList)
}
```

### Possible Solution

Remove the extra `List` from [here](https://github.com/aws/aws-sdk-go-v2/blob/06150d9630/service/s3control/deserializers.go#L9795) (but it's codegen so I don't know where to change the exact config)

### AWS Go SDK V2 Module Versions Used

```
require (
	github.com/aws/aws-sdk-go-v2 v1.31.0
	github.com/aws/aws-sdk-go-v2/config v1.27.36
	github.com/aws/aws-sdk-go-v2/service/s3control v1.48.0
	github.com/aws/smithy-go v1.21.0
)
```

### Compiler and Version used

go1.23

### Operating System and version

macOS 14.6.1 (23G93)

**Comment by RanVaknin** [comment]
Hi @ViBiOh ,

Thanks for reaching out. This was already reported a long while ago in https://github.com/aws/aws-sdk/issues/259. We have reached out to the service team internally about and there was no ETA on a fix. I have reached out again to see if I can get someone to take another look at this.

Thanks,
Ran~
