### ISSUE TITLE
Arn to friendly name?

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#281]
Given a role ARN, how does one get the friendly name?

https://godoc.org/github.com/aws/aws-sdk-go-v2/aws/arn Resource doesn't help.

**Comment by jasdel** [comment]
Hi @kaihendry you'll need to parse the resource portion of the ARN based on the context you'll be using it in. The SDK does not have this logic built in since there are so many different formats the Resource could be in across AWS services.

**Comment by jasdel** [comment]
Hi @kaihendry  are you still running into this issue?  If so please reopen this issue.
