### ISSUE TITLE
Excessive service module version churn

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-sdk-go-v2#2819]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

Over recent weeks there have been a number of releases where every service module's version has increased and the only change for those services without API model changes has been a re-ordering of calls inside the service's `New` function.
For example with yesterday's `2024-10-03` release for the `accessanalyzer` service, calls to `resolveTracerProvider` and `resolveMeterProvider` were swapped. This module had no functionality changes but a new version of the module was published.

This module version churn causes projects that use many service modules (e.g. `terraform-provider-aws`) to update a large number of dependencies and can cause a problem with `dependabot` timeouts.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Service module only publish new versions when there is new functionality (or their own dependencies change).

### Current Behavior

Excessive module version churn.

### Reproduction Steps

n/a

### AWS Go SDK V2 Module Versions Used

n/a

### Compiler and Version used

go 1.23.1

### Operating System and version

linux

**Comment by lucix-aws** [comment]
Do you have any examples of this happening for something _other_ than `resolveTracerProvider` and `resolveMeterProvider`?

The order of codegen for these two is evidently unstable - just checked on my own system, and I can re-generate multiple times and get either result. The abstraction through which they're inserted uses a [HashMap](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/HashSet.html), which is very much not guaranteed to retain order. How we have only run into this now, I have no idea. 🤦 

Unfortunately the release is about to happen again and so there's a 50/50 chance it'll swap today. We'll stabilize the order to prevent it in the future, at least.

**Comment by lucix-aws** [comment]
I have a patch ready. Waiting to see what the order is in today's release so I can match that (which would prevent an extra chrun on monday's release).

**Comment by ewbankkit** [comment]
@lucix-aws In my (relatively rather superficial) investigations I've only seen `resolveTracerProvider` and `resolveTracerMeter` swap.

**Comment by lucix-aws** [comment]
We've structured things to be ordered in codegen by design (e.g. struct members are sorted, generated serde is sorted) so this should be an exception rather than the rule.

**Comment by lucix-aws** [comment]
https://github.com/aws/smithy-go/pull/545
