### ISSUE TITLE
copy error when used with HuaweiOBS

### ISSUE THREAD

**Issue by haoze15236** [aws/aws-sdk-go-v2#2834]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

I'm facing NoSuchKey error when I use HuaweiOBS provider
![image](https://github.com/user-attachments/assets/ef6fef4a-22e6-4aa7-beb7-82d752731dfe)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I hope the copy can be successful when i use HuaweiOBS

### Current Behavior

After consulting Huawei OBS technical personnel, they concluded that the query parameter cannot be added during put upload, but x-id can be added during rclone copy. Only GCS requests will remove this parameter.

### Reproduction Steps

rclone copy /root/aa posix:haozebucket/

### Possible Solution

Is the x-id parameter mandatory? Can a configuration be provided to control whether the X-ID is carried?

### AWS Go SDK V2 Module Versions Used

rclone v1.68.1
- os/version: euleros 2.0 (64 bit)
- os/kernel: 3.10.0-327.62.59.83.h108.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.1
- go/linking: static
- go/tags: none

### Compiler and Version used

go version go1.21.6 windows/amd64

### Operating System and version

centos 8.1

**Comment by bhavya2109sharma** [comment]
Hello @haoze15236,

Thanks for reaching out.
Could you please provide a code example that reproduces the issue you're facing? Also, can you provide more details/context about the issue for better understanding.
 
Thanks,
Bhavya

**Comment by RanVaknin** [comment]
Hi @haoze15236 ,

>Is the x-id parameter mandatory? Can a configuration be provided to control whether the X-ID is carried?

x-id was added as a parameter to disambiguate calls to S3, and the actual AWS S3 server supports it.

The AWS SDK only guarantees support for AWS products. We do not support HuaweiOBS / digital ocean spaces /Minio and any other S3 clones. You'll have to reach out to Huawei for them to add support for it or implement a middleware the removes this from the request before its being sent to the server.

Thanks,
Ran~
