### ISSUE TITLE
Bug(`aws-sdk-go-v2/service/athena`): Breaking change released as a minor version bump

### ISSUE THREAD

**Issue by erezrokah** [aws/aws-sdk-go-v2#2844]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

The latest release ([v1.48.0](https://github.com/aws/aws-sdk-go-v2/blob/release-2024-10-18/service/athena/CHANGELOG.md#v1480-2024-10-18)) of the Athena SDK removed some fields from `types.DataCatalog`.

The commit is [here](https://github.com/aws/aws-sdk-go-v2/commit/d7913b75831080e1289cc9c15e29b4c682b3c8d8#diff-bca825a698a887ec98fa6dde2edd3582df0e3cadbc2240c24b70759655ed1f45). Fields removed are `ConnectionType, Error, Status`

This is a breaking change so it should be released as v2 I think (unless this SDK doesn't follow SemVer), or at explain the reasoning for the change and how to migrate from it.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

Breaking changes should be released in major version bumps, or at least have an descriptive changelog message with a migration path

### Current Behavior

Breaking change released in a minor bump without explaining how to handle the change

### Reproduction Steps

Update from Athena SDK v1.47.2 to v1.48.0

### Possible Solution

When fields are removed or have their types changed (i.e. a breaking change is done), document how to handle the change and why it was done

### AWS Go SDK V2 Module Versions Used

`github.com/aws/aws-sdk-go-v2/service/athena`

### Compiler and Version used

go version go1.23.1 darwin/arm64

### Operating System and version

macOS 15.0.1

**Comment by lucix-aws** [comment]
related: #2549

**Comment by lucix-aws** [comment]
Will need to confirm internally to see whether this was intentional.

**Comment by erezrokah** [comment]
Thanks for the quick response @lucix-aws 🚀  I get it's hard to manage the major bumps with the dependency on the service API changes, and that it might take a while to adhere to semantic versioning.
A good resolution on my end at least would be to communicate the context behind the breaking change and how to handle it

**Comment by lucix-aws** [comment]
Agreed, that's what we've been doing for [recent changes like this](https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md?plain=1#L40) and I think it goes a long way in the absence of major versioning bumps. I've asked internally that IF the Athena team intended for this change to happen, that they us with more proper release notes that include context/guidance so we can update them in all our SDKs.

**Comment by ejeffrli** [comment]
What calls were working before and how are they breaking now?

**Comment by erezrokah** [comment]
> What calls were working before and how are they breaking now?

It's not about API calls breaking, but changes the models. Data that was there before is now missing

> The commit is [here](https://github.com/aws/aws-sdk-go-v2/commit/d7913b75831080e1289cc9c15e29b4c682b3c8d8#diff-bca825a698a887ec98fa6dde2edd3582df0e3cadbc2240c24b70759655ed1f45). Fields removed are ConnectionType, Error, Status

**Comment by lucix-aws** [comment]
> What calls were working before and how are they breaking now?

It's not that straightforward. **A customer calling the SDK can reference a field in any number of ways without doing so in the context of a request/response.**

Consider the following:

```go
func CopyCreateDataCatalogOutput(v *athena.CreateDataCatalogOutput) *athena.CreateDataCatalogOutput {
    return &athena.CreateDataCatalogOutput{
        DataCatalog: CopyDataCatalog(v.DataCatalog),
        // ... other fields
    }
}

func CopyDataCatalog(v *types.DataCatalog) *types.DataCatalog {
    return &types.DataCatalog{
        // ...
    }
}
```

This code, however or for whatever reason it's used, was broken by this change.

The exact purpose of this function or where it's used are irrelevant. We can think of infinite examples across the realm of Turing completeness here. What matters is that _the service team has released this field in their expressly-public API, and customers have taken a dependency on it_. Essentially, the service team is not the authority on what constitutes possible use of a field, the customer is.

Hashicorp's Terraform is an excellent real-world case study for this kind of thing. Terraform is a multi-cloud IaC tool - think CDK but works with other cloud providers. Terraform uses the Go SDK, and by the nature of the product, it essentially _comprehensively_ references fields in the Go SDK that it needs to support for its users. It may do so without regard to the nature of a particular field, how it's used, or whether it even works - it simply needs to support configuring it and referencing it so the customer using Terraform can use it if need be.

**Comment by lucix-aws** [comment]
Updated messaging: https://github.com/aws/aws-sdk-go-v2/commit/3bab20015daf03d8d70e6ee8601b8aeb457d855f
