### ISSUE TITLE
DynamoDB example missing ·ExpressionAttributeNames:  expr.Names(),

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#285]
https://github.com/aws/aws-sdk-go-v2/blob/master/service/dynamodb/expression/examples_test.go#L107-L112

`·ExpressionAttributeNames:  expr.Names(),` is needed, else you will get these odd:

    ValidationException: Invalid KeyConditionExpression: An expression attribute name used in the document path is not defined; attribute name: #0

**Comment by jasdel** [comment]
Thanks for reporting this issue. We'll fix this in both the v1 and v2 SDK's examples.
