### ISSUE TITLE
[BUG] Panic - Invalid Memory Address due to MaxResults

### ISSUE THREAD

**Issue by iocron** [aws/aws-sdk-go-v2#2853]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

Using MaxResults works only up to a value of 100, otherwise it throws a panic `panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100dd9200]`  

Code to reproduce: 

```go
	identityStoreId := "d-xxxxxxxxxx"
	ctx := context.Background()
	cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Fatal(err)
	}

	client := identitystore.NewFromConfig(cfg)
	result, err := client.ListUsers(ctx, &identitystore.ListUsersInput{
		IdentityStoreId: &identityStoreId,
		MaxResults:      aws.Int32(101),
	})
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Should not crash with a hard panic and inform the user about the hard limit. 

### Current Behavior

Crashes with a hard segmentation violation panic error. 

### Reproduction Steps

Execute the mentioned code above. 

```go
package main

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/identitystore"
	"log"
)

func main() {
	identityStoreId := "d-xxxxxxxxxx"
	ctx := context.Background()
	cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {
		log.Fatal(err)
	}

	client := identitystore.NewFromConfig(cfg)
	result, err := client.ListUsers(ctx, &identitystore.ListUsersInput{
		IdentityStoreId: &identityStoreId,
		MaxResults:      aws.Int32(101),
	})
}
```

### AWS Go SDK V2 Module Versions Used

aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2@v1.32.2
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/config@v1.28.0
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/credentials@v1.17.41
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.16.17
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.1
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/service/identitystore@v1.27.2
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.12.0
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.2
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2
aws-identitycenter-groupsync github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2
aws-identitycenter-groupsync github.com/aws/smithy-go@v1.22.0
aws-identitycenter-groupsync go@1.23.2
github.com/aws/aws-sdk-go-v2@v1.32.2 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2@v1.32.2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2@v1.32.2 go@1.21
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/credentials@v1.17.41
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.16.17
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.1
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.12.0
github.com/aws/aws-sdk-go-v2/config@v1.28.0 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.2
github.com/aws/aws-sdk-go-v2/config@v1.28.0 go@1.21
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.16.17
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.12.0
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.2
github.com/aws/aws-sdk-go-v2/credentials@v1.17.41 go@1.21
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.16.17 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.16.17 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.16.17 go@1.21
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21 go@1.21
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21 go@1.21
github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.1 go@1.21
github.com/aws/aws-sdk-go-v2/service/identitystore@v1.27.2 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/service/identitystore@v1.27.2 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21
github.com/aws/aws-sdk-go-v2/service/identitystore@v1.27.2 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21
github.com/aws/aws-sdk-go-v2/service/identitystore@v1.27.2 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/service/identitystore@v1.27.2 go@1.21
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.12.0 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.12.0 go@1.21
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.2 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.2 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.2 go@1.21
github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21
github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21
github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/service/sso@v1.24.2 go@1.21
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.2 go@1.21
github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2 github.com/aws/aws-sdk-go-v2@v1.32.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.21
github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.21
github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.12.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.2
github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2 github.com/aws/smithy-go@v1.22.0
github.com/aws/aws-sdk-go-v2/service/sts@v1.32.2 go@1.21
github.com/aws/smithy-go@v1.22.0 go@1.21
go@1.23.2 toolchain@go1.23.2

### Compiler and Version used

go version go1.23.2 darwin/arm64

### Operating System and version

macOS 14.6.1

**Comment by RanVaknin** [comment]
Hi @iocron ,

I tried reproducing this issue, but Im not seeing a panic, instead I'm seeing a validation error. Is your code snippet incomplete and somehow references results at the 101th index that causes the nil pointer exception?

From the documentation: https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListUsers.html#singlesignon-ListUsers-request-MaxResults

Max results should be set between 1-100. 

Thanks,
Ran~

**Comment by iocron** [comment]
Hi @RanVaknin 
I checked it with some other example and i am getting a validation error as well. I think the panic I mentioned might have been indirectly caused (can't find/reproduce the panic anymore). The validation error only says: 

```
operation error identitystore: ListUsers, https response error StatusCode: 400, RequestID: ..., ValidationException: exit status 1
```

That information does not provide very much to the enduser. Would it make sense to define a generally intelligible error message for this instead?
