### ISSUE TITLE
S3Control: StorageLensConfigurationList not deserialized from the response correctly

### ISSUE THREAD

**Issue by yznima** [aws/aws-sdk-go-v2#2863]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

I'm using AWS SDK V2 to describe S3 StorageLensConfiguations. The result is always empty even though I definitely have the storage lens in the region. The StoragelLensConfiguationsList is always empty.

**Version of AWS SDK for Go?**
Example: v1.29.22
* `aws-sdk-go-v2/service/s3control@v1.11.0`

**Version of Go (`go version`)?**

go 1.17

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```go
import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/s3control"
)

....

const AccountId = "XXXXX"
func DescribeS3StorageLens(ctx context.Context, cfg aws.Config) ([]interface{}, error) {
        ....
	client := s3control.NewFromConfig(cfg)
	output, err := client.ListStorageLensConfigurations(ctx, &s3control.ListStorageLensConfigurationsInput{
		AccountId: AccountId,
	})
	if err != nil {
		return nil, err
	}
	b, _ := json.Marshal(output.StorageLensConfigurationList)
	fmt.Println(string(b))
       ....
}
```

When I turn on AWS Client logging, I see

```xml
<ListStorageLensConfigurationResult xmlns="http://awss3control.amazonaws.com/doc/2018-08-20/">
	<StorageLensConfiguration>
		<StorageLensArn>arn:aws:s3:us-east-1:XXXXXX:storage-lens/MyDashboard</StorageLensArn>
		<Id>MyDashboard</Id><HomeRegion>us-east-1</HomeRegion>
		<IsEnabled>true</IsEnabled>
	</StorageLensConfiguration>
	<StorageLensConfiguration>
		<StorageLensArn>arn:aws:s3:us-east-1:XXXXXXX:storage-lens/default-account-dashboard</StorageLensArn>
		<Id>default-account-dashboard</Id>
		<HomeRegion>us-east-1</HomeRegion>
		<IsEnabled>true</IsEnabled>
	</StorageLensConfiguration>
</ListStorageLensConfigurationResult>
```

From me looking around, I think it is because the [deserializer.go](https://github.com/aws/aws-sdk-go-v2/blob/b3a5250449564f7d11eaa031bb230ea7c3bb052e/service/s3control/deserializers.go#L5737) is looking for `StorageLensConfigurationList` in the XML however, there is none as shown in the output about

**Expected behavior**

I expect the `output.StorageLensConfigurationList` to be populated with the result.

**Additional context**

**Comment by RanVaknin** [comment]
This is now fixed.
