### ISSUE TITLE
Codecommit implement GetChanges

### ISSUE THREAD

**Issue by reckerdaniel** [aws/aws-sdk-go-v2#2876]
### Describe the feature

I want to get a list of changes in a pullrequest. Right now there is a `GetDifferences` function but that lists all the differences between two different commits. i want to only list the changes that a given pullrequest has made without including the differences in main that were added by other teams.

It's possible this already exists but i wasn't able to find it in the documentation. 
https://github.com/aws/aws-sdk-go/tree/v1.44.31/service/codecommit

### Use Case

We want to use the list of changes in a pullrequest to generate the approver list. we map changes within a specified folder to have specific approvers. If we are able to get the changes a pullrequest has we can limit our approver list just to the people we need. currently using GetDifferences it would include any difference between main and a Commit ID so we include changes outside of the Pullrequest therefore requesting too many approvers.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

aws-sdk-go-v2

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

go version go1.15.3 windows/amd64

**Comment by zshzbh** [comment]
Hey there,

Got back from service team - No new changes are planned in CodeCommit. Closing this issue. Please let us know if there's anything else.

Thanks!
