### ISSUE TITLE
EFS should have snapshot function similar to EBS

### ISSUE THREAD

**Issue by kaovilai** [aws/aws-sdk-go-v2#2906]
### Describe the feature

https://docs.aws.amazon.com/efs/latest/ug/awsbackup.html suggests one can start ondemand backup
seems to be via
https://docs.aws.amazon.com/aws-backup/latest/devguide/API_StartBackupJob.html

make similar functions to https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ebs#Client.StartSnapshot and others

### Use Case

So that https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/511 can actually implement snapshot in a similar way to EBS CSI driver

So that https://github.com/vmware-tanzu/velero/issues/5418 and others can implemente universally using CSI interface, a way to trigger backup of EBS volumes.

### Proposed Solution

Use https://docs.aws.amazon.com/aws-backup/latest/devguide/API_StartBackupJob.html or other APIs to create function equivalent to StartSnapshot for EBS.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

latest

### Go version used

1.23

**Comment by RanVaknin** [comment]
Hi @kaovilai ,

The AWS SDKs are all code-generated from the upstream API models of each AWS service. The SDK team cannot "add" API operations / options since those must be modeled and also have backend support for it to work. 

I saw that this feature request already exists with the EFS service team, so I added this github issue as a data point for that team to consider. Unfortunately I don't have visibility to when / if it will get implemented. 

Since this is not actionable by the Go SDK team, I'm going to close it. 

Thanks,
Ran~

**Comment by kaovilai** [comment]
@RanVaknin is there any public visibility into the ticket with EFS team? Some way to ad-hoc check on the status.

**Comment by RanVaknin** [comment]
Unfortunately there is not.

**Comment by pedroapero** [comment]
> Hi [@kaovilai](https://github.com/kaovilai) ,
> 
> The AWS SDKs are all code-generated from the upstream API models of each AWS service. The SDK team cannot "add" API operations / options since those must be modeled and also have backend support for it to work.
> 
> I saw that this feature request already exists with the EFS service team (`#a2vRU000000AJSoYAO`) , so I added this github issue as a data point for that team to consider. Unfortunately I don't have visibility to when / if it will get implemented.
> 
> Since this is not actionable by the Go SDK team, I'm going to close it.
> 
> Thanks, Ran~

Hi @RanVaknin , can you share if there has been any update from the EFS service team in the mentioned AWS ticket since 2024?
