### ISSUE TITLE
DMS S3 Settings Missing KmsKeyArn 

### ISSUE THREAD

**Issue by pvassiliev** [aws/aws-sdk-go-v2#2908]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

DMS S3 Settings Missing KmsKeyArn

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

DMS S3 Settings to have KmsKeyArn

### Current Behavior

Not able to use KmsKeyArn from DMS S3 Settings

### Reproduction Steps

`s3settings := endpoint.S3Settings`
`d.Set("kms_key_arn", s3settings.KmsKeyArn)`

### Possible Solution

Add KmsKeyArn to S3Settings struct

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 github.com/aws/smithy-go@v1.22.1
github.com/aws/aws-sdk-go-v2 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2 go@1.21
github.com/aws/smithy-go@v1.22.1 go@1.21
github.com/jmespath/go-jmespath@v0.4.0 github.com/jmespath/go-jmespath/internal/testify@v1.5.1
go@1.21 toolchain@go1.21
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/davecgh/go-spew@v1.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/pmezard/go-difflib@v1.0.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 github.com/stretchr/objx@v0.1.0
github.com/jmespath/go-jmespath/internal/testify@v1.5.1 gopkg.in/yaml.v2@v2.2.8
gopkg.in/yaml.v2@v2.2.8 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405

### Compiler and Version used

go version go1.22.7 linux/amd64

### Operating System and version

Amazon Linux 2

**Comment by RanVaknin** [comment]
Hi @pvassiliev ,

I'm not sure I understand the issue you have described. 

>DMS S3 Settings to have KmsKeyArn

Which settings? 

>Reproduction Steps
```
s3settings := endpoint.S3Settings
d.Set("kms_key_arn", s3settings.KmsKeyArn)
```

The code sample is incomplete, this doesn't look like the Go SDK code. 

Can you be a little more specific about which settings are missing the field in question? Also you opened this as a bug, but this sounds like an issue you are having with the DMS API itself. The SDK is code-generated from the API model of each service, which means that the SDK wont have settings that do no exist on the API itself. Do you have any documentation that show that the `KmsKeyArn` field is documented but actually missing from the model? 

Thanks,
Ran~
