### ISSUE TITLE
Add custom query parameters when creating S3 Presigned URLs through exposing options/middleware

### ISSUE THREAD

**Issue by wspurgin** [aws/aws-sdk-go-v2#2932]
### Describe the feature

As described in [AWS blog post](https://aws.amazon.com/blogs/storage/using-presigned-urls-to-identify-per-requester-usage-of-amazon-s3/), you can hook into the SigV4 process to add custom query parameters to the generated presigned URLs.

As in the scenario of that blog post, this is incredibly useful to create per-requestor Presigned URLs and have that traceability in the access logs for those objects in Cloudtrail.

Today, the only (theoretical) way to accomplish that is through creating an entirely custom v4(a) Presigner and providing that to an S3 Presigner Client - which is [thoroughly discouraged](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv.html) by AWS' User Guides.

Because of the complex nature of v4, I don't think it advisable to roll your own. Just as an example, getting [the right keys](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/signer/v4/v4.go) is something internal to the module today and doing it yourself is ripe with peril.

I think, perhaps, the simplest way to support a feature like this is adding something like a RequestOptionFunc to [`SignHTTP`](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/signer/v4/v4.go#L70-L72) to allow a caller to modify an input request (at their own risk) - or a more specific SignOption that adds a map of string-to-string query [parameters to the request before adding necessary signing parameters](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/signer/v4/v4.go#L143-L149).

### Use Case

Adding custom query params for requestor logging like that described in [AWS blog post](https://aws.amazon.com/blogs/storage/using-presigned-urls-to-identify-per-requester-usage-of-amazon-s3/) without needing to roll your own v4 presigner (which is heavily discouraged by AWS)

### Proposed Solution

I think, perhaps, the simplest way to support a feature like this is adding something like a RequestOptionFunc to [`SignHTTP`](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/signer/v4/v4.go#L70-L72) to allow a caller to modify an input request (at their own risk) - or a more specific SignOption that adds a map of string-to-string query [parameters to the request before adding necessary signing parameters](https://github.com/aws/aws-sdk-go-v2/blob/main/aws/signer/v4/v4.go#L143-L149).

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2@v1.32.5
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.6.7
github.com/aws/aws-sdk-go-v2/config@v1.28.5
github.com/aws/aws-sdk-go-v2/credentials@v1.17.46
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.16.20
github.com/aws/aws-sdk-go-v2/feature/s3/manager@v1.17.18
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.3.24
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.6.24
github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.1
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.3.24
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.12.1
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.4.5
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.12.5
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.18.5
github.com/aws/aws-sdk-go-v2/service/s3@v1.68.0
github.com/aws/aws-sdk-go-v2/service/sso@v1.24.6
github.com/aws/aws-sdk-go-v2/service/ssooidc@v1.28.5
github.com/aws/aws-sdk-go-v2/service/sts@v1.33.1
github.com/aws/smithy-go@v1.22.1

### Go version used

go version go1.23.3 darwin/arm64

**Comment by lucix-aws** [comment]
We already have a generic way to do this - the blessed way to modify the transport request in SDK v2 is [middleware](https://aws.github.io/aws-sdk-go-v2/docs/middleware/).

**Comment by wspurgin** [comment]
Thanks @lucix-aws - appreciate the link to documentation and the issue to track for HTTP interceptors!
