### ISSUE TITLE
Add missing ListTagsForResource API

### ISSUE THREAD

**Issue by Limess** [aws/aws-sdk-go-v2#295]
Would it be possible to cut a new release with the latest AWS API models to support this new API?

### Version of AWS SDK for Go?

* aws-sdk-go-v2 v0.7.0
* master [80eda21e3854386d2a56de1236efe984f6e687de](https://github.com/aws/aws-sdk-go-v2/commit/80eda21e3854386d2a56de1236efe984f6e687de)

### Version of Go (`go version`)?
N/A

### What issue did you see?

The Cloudwatch API [ListTagsForResource](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListTagsForResource.html) is missing. 

This does exist in the current V1 SDK (https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.ListTagsForResource)

**Comment by jasdel** [comment]
Thanks for reporting this issue @Limess. This is one of the API's the V2 SDK is lagging behind the V1 SDK's API models.  Tagging this as a v1-sync so we can update the V2 SDK's API model definitions.
