### ISSUE TITLE
CH - Nonrenewable / denylpcreq

### ISSUE THREAD

**Issue by SuperintendentColeman** [aws/aws-sdk-go-v2#296]
Please fill out the sections below to help us address your issue.

req := svc.MyCoolAPIRequest(params)

### Steps to reproduce

If you have have an runnable example, please include it.

**Comment by SuperintendentColeman** [comment]
I have the most recent version of Go. Issues are unhealthy practices. Steps
taken DHP incident report. IoT prevent renewal process due to severe risk.

Kind regards

K. Coleman

**Comment by jasdel** [comment]
HI @SuperintendentColeman, could you please clarify the issue that you are running into? If possible with examples of or links to the issue you're seeing.

**Comment by jasdel** [comment]
HI @SuperintendentColeman  are you still experiencing this issue?
