### ISSUE TITLE
Regenerate the SDK with new models

### ISSUE THREAD

**Issue by Cyberax** [aws/aws-sdk-go-v2#304]
Would you mind regenerating the SDK with the new models? In particular, we need AssumeRole with the new "PolicyArn" parameters.

Also, what's the long-term plan for the V2 SDK? It's kinda falling behind V1.

### Version of AWS SDK for Go?
0.8.0

### Version of Go (`go version`)?
1.12.5

### What issue did you see?
The models are not up-to-date

### Steps to reproduce
N/A

**Comment by jasdel** [comment]
Thanks @Cyberax, we'll get the V2 SDK updated. We do not have the v2 included in our CI/CD release automation yet. We have this task in our backlog, and I'll bring this up at our next sprint planning to evaluate where in the backlog the CI/CD release automation should be adjusted.

**Comment by pete911** [comment]
@Cyberax @jasdel I feel the same way that v2 is slowing down in terms of development. I just had some issues answered after 7 months ... There seems to be only one committer ... Can we help somehow?
