### ISSUE TITLE
doc: fix header '### Hello AWS' in godoc: https://godoc.org/github.com/aws/aws-sdk-go-v2

### ISSUE THREAD

**Issue by udhos** [aws/aws-sdk-go-v2#313]
### Version of AWS SDK for Go?
v2
### Version of Go (`go version`)?
Does not matter.
### What issue did you see?
'### Hello AWS' in https://godoc.org/github.com/aws/aws-sdk-go-v2
### Steps to reproduce
1) Open https://godoc.org/github.com/aws/aws-sdk-go-v2
2) Look for '### Hello AWS'

Possible fix is to replace:
```
### Hello AWS
```
With:
```
Hello AWS
```
in the file https://github.com/aws/aws-sdk-go-v2/blob/master/doc.go

**Comment by jasdel** [comment]
Thanks for reporting this issue @udhos. I went ahead and updated the package doc.
