### ISSUE TITLE
The file name is too long to compile.

### ISSUE THREAD

**Issue by Nazozen** [aws/aws-sdk-go-v2#317]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
aws-sdk-go-v2

### Version of Go (`go version`)?
go 1.9.2 windows / amd64

### What issue did you see?
I use "c:\usera\username\go" as GOPATH and use aws-sdk-v2. When I updated sdk yesterday, the go compiler got a "file name is too long to compile" error.
The file in error is the file in the "aws-sdk-go-v2\service\ec2" folder. I think there are other things.
Once I moved GOPATH to "c:\g" I got no errors.

For example, "api_op_" at the beginning of the file name is unnecessary?

**Comment by jasdel** [comment]
Thanks for reporting this issue. It looks like Go compiler fixed this issue in Go 1.11.

golang/go#18468

Have you tried updating your Go version to see if that addresses your issue as well so you don't have to move your GOPATH? Also Go modules should also remove this issue as well.

With that said, the `api_op_` isn't critical, but was a convenient prefix for the generated Go code. We can review the length issue, but updating to Go version, or changing GOPATH is a good work around.
