### ISSUE TITLE
SDK's http.Request Body contains a value when it should be nil

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#318]
The SDK's `aws.Request.HTTPRequest.Body` member may contain a non-nil value even though the SDK has no intention of sending a Body in the request. The SDK should only build a `http.Request` with a `Body` when there is a body to actually send.

**Comment by fifarafa** [comment]
@jasdel Could you provide some example of situations when body is not needed?

**Comment by jasdel** [comment]
Hi @fifarafa the SDK is currently always setting the `Body` field regardless if the API operation will provide a payload. This leads to the circumstance where the SDK setting the `Body` field causes the Go HTTP client to send the request with chunked transfer encoding which is not expected, and in the case of S3 not supported.

aws/aws-sdk-go#991 is the V1 SDK's issue that resolved this issue. The V2 SDK should prevent this issue from the beginning by only ever setting the `http.Request.Body` member when a non-zero length payload will be sent.
