### ISSUE TITLE
is there anything wrong with route53 sdk?

### ISSUE THREAD

**Issue by spikoxbb** [aws/aws-sdk-go-v2#322]
../vendor/github.com/aws/aws-sdk-go-v2/service/route53/api_client.go:44:5: unknown field 'ServiceID' in struct literal of type aws.Metadata
../vendor/github.com/aws/aws-sdk-go-v2/service/route53/api_client.go:45:5: unknown field 'EndpointsID' in struct literal of type aws.Metadata
../vendor/github.com/aws/aws-sdk-go-v2/service/route53/api_op_ListHealthChecks.go:226:4: cannot use func literal (type func(context.Context) (*aws.Request, error)) as type func() (*aws.Request, error) in field value
../vendor/github.com/aws/aws-sdk-go-v2/service/route53/api_op_ListHostedZones.go:244:4: cannot use func literal (type func(context.Context) (*aws.Request, error)) as type func() (*aws.Request, error) in field value
../vendor/github.com/aws/aws-sdk-go-v2/service/route53/api_op_ListResourceRecordSets.go:370:4: cannot use func literal (type func(context.Context) (*aws.Request, error)) as type func() (*aws.Request, error) in field value
../vendor/github.com/aws/aws-sdk-go-v2/service/route53/api_waiters.go:48:10: w.Wait undefined (type aws.Waiter has no field or method Wait)

Compilation finished with exit code 2

**Comment by jasdel** [comment]
HI @spikoxbb thanks for reaching out to us. Are you still experiencing this issue? This looks like an issue with your application's `vendor` folder not being synced correctly with the SDK's repository. Try to re-retrieve the SDK into your your application's `vendor` folder.
