### ISSUE TITLE
Link is broken in sagemaker documentation 

### ISSUE THREAD

**Issue by gautamkmr** [aws/aws-sdk-go-v2#327]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v0.9.0

### Version of Go (`go version`)?
1.12.6

### What issue did you see?
https://docs.aws.amazon.com/goto/WebAPI/sagemaker-2017-07-24/ListTrainingJobsRequest is not reachable

https://github.com/aws/aws-sdk-go-v2/blob/master/service/sagemaker/api_op_ListTrainingJobs.go#L13

### Steps to reproduce
N/A

If you have have an runnable example, please include it.

**Comment by jasdel** [comment]
Thanks for reporting this issue @gautamkmr. It looks like this is a mixup with the SDK's generated API reference doc links not being valid. The issue looks to be the `Request` suffix of `ListTrainingJobsRequest`  in the link.

The V1 SDK looks to be generating this link correct, https://github.com/aws/aws-sdk-go/blob/master/service/sagemaker/api.go#L5314
