### ISSUE TITLE
Unable to send empty map value in request

### ISSUE THREAD

**Issue by j0hnsmith** [aws/aws-sdk-go-v2#332]
### Version of AWS SDK for Go?
`v0.9.0`

### Version of Go (`go version`)?
all

### What issue did you see?

In the api lex api, sending an empty map for the key `sessionAttributes: {}` deletes existing session attributes however omitting the key keeps the existing ones. It's not possible to delete attributes as no distinction, in the current implementation, is made between a `nil` map and an empty one.

https://github.com/aws/aws-sdk-go-v2/blob/801e5eec4159d01c5a0c7ba696d8a1caa221a54d/service/lexruntimeservice/api_op_PostText.go#L132

### Steps to reproduce
* make first request with session attributes
* response includes session attributes as expected
* make second request with empty session attributes map
* response includes session attributes as set by first request, they should have been removed

https://docs.aws.amazon.com/lex/latest/dg/context-mgmt.html

**Comment by jasdel** [comment]
Thanks for reporting this issue @j0hnsmith. This looks to be a issue with the SDK's marshaling code generator not distinguishing between empty and nil. This behavior is probably similar with slices as well as maps.

We need to investigate this behavior, I would think sending empty list/map would be the correct behavior when empty.

**Comment by jasdel** [comment]
The code generation that drives the `len(v) > 0`  check is in [private/model/api/shape_marshal.go](https://github.com/aws/aws-sdk-go-v2/blob/801e5eec4159d01c5a0c7ba696d8a1caa221a54d/private/model/api/shape_marshal.go#L295)

**Comment by jasdel** [comment]
Thanks for reporting this issue @j0hnsmith. We've merged in a fix that addresses this bug. You should now be able to send empty maps and lists with the V2 SDK.

**Comment by j0hnsmith** [comment]
Great work and so quick, thanks, I'll try it out tomorrow.
