### ISSUE TITLE
Golint failed on sqsiface GetQueueUrlRequest  function

### ISSUE THREAD

**Issue by pilathraj** [aws/aws-sdk-go-v2#361]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v0.10.0

### Version of Go (`go version`)?
go version go1.12.5 windows/amd64

### What issue did you see?
Golint failed when i extend "github.com/aws/aws-sdk-go-v2/service/sqs/sqsiface" 's GetQueueUrlRequest should be GetQueueURLRequest. 

### Steps to reproduce

```go
package sqs

import (
	"errors"
	"net/http"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/aws/aws-sdk-go-v2/service/sqs/sqsiface"
)

// Mock SQS
type mockSQSClient struct {
	sqsiface.ClientAPI
	Request         sqs.SendMessageRequest
	QueueURLRequest sqs.GetQueueUrlRequest
}

func (m *mockSQSClient) GetQueueUrlRequest(input *sqs.GetQueueUrlInput) sqs.GetQueueUrlRequest {
	return m.QueueURLRequest
}
```
If you have have an runnable example, please include it.
Above code

**Comment by jasdel** [comment]
Thanks for reaching out to us @pilathraj with this issue. The names of API operations, types, and their associated mocking interfaces are defined through models that the SDK uses to generate the API's client and types code with. The v2 SDK does not make any attempt to make these names idiomatic. This is the reason some operations and types will have non capitalized initialisms in their names. 

Prior to the v1 SDK's GA release it did attempt to capitalize initialisums like `URL`, but this behavior was removed. Maintaining the set of initialisums and rules became overly complex, and effectively required a constantly growing dictionary to be included in the SDK's code generation. aws/aws-sdk-go#347

**Comment by pilathraj** [comment]
Thanks for your response.
