### ISSUE TITLE
Please user major version increments for breaking changes

### ISSUE THREAD

**Issue by TopherGopher** [aws/aws-sdk-go-v2#381]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
`github.com/aws/aws-sdk-go-v2 v0.11.0`

### Version of Go (`go version`)?
`go1.12.7 darwin/amd64`

### What issue did you see?
Breaking changes were introduced during minor version increments.

### More Info
Standard golang practice is to introduce any breaking changes at major version releases. That way, when someone runs `go mod` or `vgo` to update their library, they can immediately tell from the version itself that they need to be cautious.

You can find the original proposal on package versioning here: https://go.googlesource.com/proposal/+/master/design/24301-versioned-go.md

**Comment by shawnsmithdev** [comment]
As this is tagged v0.x, anything can change at any time, and the API should not be considered stable.

https://semver.org/#spec-item-4

**Comment by TopherGopher** [comment]
You are 100% right and I am totally wrong. Closing.
