### ISSUE TITLE
Making AWS API calls from Fargate - example/guidance

### ISSUE THREAD

**Issue by Chanonry** [aws/aws-sdk-go-v2#395]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2

### Version of Go (`go version`)?
1.12.7

It's not clear how to create a client/enable calls to other AWS services from within a Fargate Task. There is clearly some confusion on this issue reflected in this https://forums.aws.amazon.com/thread.jspa?threadID=273767 post on the developers forum. 

A helpful response at the end (kind of) but its such a basic requirement it would be extremely helpful to see a best practice example/s on how to achieve this with the go SDK. 

Please. Thanks.

**Comment by jasdel** [comment]
Closing this issue due to its age. If you're still having issues please let us know. 

With regard to configuring the SDK, check out the documentation at, https://github.com/aws/aws-sdk-go-v2/blob/documentation/content/en/docs/configuring-sdk/_index.md
