### ISSUE TITLE
Can't test against some types in the api

### ISSUE THREAD

**Issue by Chanonry** [aws/aws-sdk-go-v2#422]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v2

### Version of Go (`go version`)?
1.13

### What issue did you see?
Some types in the api have unexported fields which prevents testing

### Steps to reproduce

One example
```go
testTaskResponse := ecs.RunTaskResponse{
		&taskOP,
}
```

produces a "too few values" error

while

```go
testTaskResponse := ecs.RunTaskResponse{
		&taskOP,
		&aws.Response{}
	}
```

obviously produces "implicit assignment of unexported field 'response' in ecs.RunTaskResponse literal

So the api lets me generate code but not test it ??

If you have have an runnable example, please include it.

**Comment by jasdel** [comment]
The v2 SDK's API client has been redesigned and refactored in release v0.25.0.  See https://github.com/aws/aws-sdk-go-v2/issues/438 for more details on the new design.
