### ISSUE TITLE
SDK should provide utility to stringify API paramaters

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-go-v2#425]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

V2, v0.15.0

### Version of Go (`go version`)?

`go version go1.13.3 darwin/amd64`

### What issue did you see?

[`cloudfront.SslProtocol`](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/cloudfront#SslProtocol) is an enum that cannot be _stringified_ the way that other objects can.

### Steps to reproduce

While iterating through a CloudFront ListDistributions response, I was expecting to be able to do this:

```go
// [snip…]
for _, policy := range origin.CustomOriginConfig.OriginSslProtocols.Items {
    securityPolicy = append(securityPolicy, string(policy))
}
// [/…snip]
```

…but instead had to do this.

```go
// [snip…]
for _, policy := range origin.CustomOriginConfig.OriginSslProtocols.Items {

    strpol, err := policy.MarshalValue()
    if err != nil {
        return *emptyCloudFrontResponse, err
    }

    securityPolicy = append(securityPolicy, strpol)
}
// [/…snip]
```

**Comment by skyzyx** [comment]
It's been 6 months. Can I get an acknowledgement?

**Comment by jasdel** [comment]
Thanks for creating this feature request. The v2 SDK v0.26.0 update currently does not have stringer helper implemented. We can use this feature request to track, how this could be provided.

**Comment by jasdel** [comment]
The SDK has not exported any utilities to stringify the types. Third party utilities such as [go-spew](https://pkg.go.dev/github.com/davecgh/go-spew@v1.1.1/spew#Dump) are able to provide this stringify behavior.
