### ISSUE TITLE
IAM DB Authentication for Aurora Postgresql

### ISSUE THREAD

**Issue by KarthickEmis** [aws/aws-sdk-go-v2#428]
Please fill out the sections below to help us address your issue.

### Steps to reproduce

If you have have an runnable example, please include it.

In your example , it shows for connecting to mysql . Do you have an example of connecting to Aurora PostgreSQL using IAM Authentication in go lang.  

i tried the same , instead of mysql i used  the below one 

dnsStr := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?allowCleartextPasswords=true",
		"test", authtoken, config["dbhost"], config["dbport"], config["dbname"],
	)

but my lambda returns 
panic: dial tcp: lookup test:xyzcluster.eu-west-1.rds.amazonaws.com:5432: no such host

If you have an example of connecting to Aurora PostgreSQL, share me the example or syntax.

**Comment by mpreziuso** [comment]
Have you tried something like:
```
fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=verify-full password=%s", config["dbhost"], config["dport"], "test", config["dbname"], authtoken)
```
making sure that dbhost is just the endpoint (i.e. without ':5432' at the end)?

**Comment by KarthickEmis** [comment]
> fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=verify-full password=%s", config["dbhost"], config["dport"], "test", config["dbname"], authtoken)

Hi, I tried the above , but getting "ping db: **pq: password authentication failed for user "test"** error.
Do you have any working example for connecting Aurora PostgreSQL through IAM DB Authentication

**Comment by mpreziuso** [comment]
That sounds like you need to set up the user:
```sql
CREATE USER db_userx WITH LOGIN; 
GRANT rds_iam TO db_userx;
```

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.DBAccounts.html

**Comment by KarthickEmis** [comment]
> suspect you'll need to grant some permissions to that user to

No.. I gave permission for my test user with login access and rds_iam role. Below is the piece of code , when i try to generate auth code ...

awsCreds := stscreds.NewCredentials(session.New(), **mylambdarolearn**)
authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
		awsRegion, "test", awsCreds) 
dnsStrr := fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=require password=%s",
		config["dbhost"], 5432, "test", config["dbname"], authToken)

note: while buildauthtoken , i used only dbhost and also with port ... Nothing works out... 

It shows **panic: pq: password authentication failed for user "test"**

**Comment by mpreziuso** [comment]
The fact that it says "password authentication" is a bit odd - I'd expect something about PAM instead.
Perhaps try and use
```go
	cfg, err := external.LoadDefaultAWSConfig()
        if err != nil { ... }
        authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
awsRegion, "test", cfg.Credentials)
```

**Comment by KarthickEmis** [comment]
> ```go
> if err != nil { ... }
> ```

Hi,

When using cfg.Credentials in BuildAuthToken Method , it shows cannot uses **cfg.credentials as type *credentials.credentials in argument to rdsutils.BuildAuthToken**...

**Comment by mpreziuso** [comment]
That works for me - are you sure you're using this version of the SDK vs the regular one?

**Comment by KarthickEmis** [comment]
> ure you're using this version of the SDK

I am using go version go1.12.9 windows/amd64

**Comment by mpreziuso** [comment]
What version of aws-sdk-go are you using? What's your import?

**Comment by KarthickEmis** [comment]
> What version of aws-sdk-go are you using? What's your import?

import (
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go-v2/aws/external"
	"github.com/aws/aws-sdk-go/aws/credentials/stscreds"
	"github.com/aws/aws-sdk-go/aws/session"
	rds "github.com/aws/aws-sdk-go/service/rds"
	rdsutils "github.com/aws/aws-sdk-go/service/rds/rdsutils"
	dbconnection "github.com/emisgroup/appointment-examples/src/go/db"
	_ "github.com/lib/pq"
)

**Comment by mpreziuso** [comment]
Ok you're using a mix of the aws-sdk-go and aws-sdk-go-v2. Since you've asked this on the v2 issues, I'd suggest getting rid off all the 'aws-sdk-go' imports - in my case I only need 
```
github.com/aws/aws-sdk-go-v2/aws-external
github.com/aws/aws-sdk-go-v2/service/rds/rdsutils
```
not sure if you need any other imports (i.e. session/stscreds), but to get a connection string that you can use in Go this should be sufficient:
```go
cfg, err := external.LoadDefaultAWSConfig()
if err != nil {
 [..]
}
authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
awsRegion, config["dbuser"], cfg.Credentials)
if err != nil {
  [...]
}
return fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=verify-full password=%s", config["dbhost"], 5432, config["dbuser"], config["dbname"], authToken)
```

**Comment by KarthickEmis** [comment]
> ther imports (i.e. session/stscreds), but to get a connection string that you can use in Go this should be sufficient:


I tried like what you specified above ... Getting same error **panic: pq: password authentication failed for user "test"**

import (
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go-v2/aws/external"
	"github.com/aws/aws-sdk-go-v2/service/rds/rdsutils"
	dbconnection "github.com/emisgroup/appointment-examples/src/go/db"
	_ "github.com/lib/pq"
)

var (
	appID, sender string
	db            *sql.DB
)

const awsRegion = "eu-west-2"

func init() {

	fmt.Println("Code Started")
	cfg, err := external.LoadDefaultAWSConfig()
	if err != nil {
		fmt.Println(err)
	}
	config := gettoken()
authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
		awsRegion, "test", cfg.Credentials)
	dnsStrr := fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=require password=%s",
		config["dbhost"], 5432, "test", config["dbname"], authToken)
db, err = sql.Open("postgres", dnsStrr)

	fmt.Printf(" ping db dnsStrr: %s\n", db.Ping())
	if err != nil {
		panic(err)
	}
}

**Comment by mpreziuso** [comment]
Sorry to ask the obvious - have you also enabled IAM Authentication in RDS on your instance?

**Comment by KarthickEmis** [comment]
> thentication in RDS on your inst

yes... the below query has been runned 
CREATE USER test WITH LOGIN; 
GRANT rds_iam TO test;

**Comment by KarthickEmis** [comment]
> Sorry to ask the obvious - have you also enabled IAM Authentication in RDS on your instance?

DO you have any working example for iam db authentication for aurora postgresql ?

**Comment by mpreziuso** [comment]
I do - that works for me... 
But I meant did you set it up in the Console?

![image](https://user-images.githubusercontent.com/10457038/69425130-41127800-0d22-11ea-9ecc-8f68c2cf5e8a.png)

**Comment by KarthickEmis** [comment]
> I do - that works for me...
> But I meant did you set it up in the Console?
> 
> ![image](https://user-images.githubusercontent.com/10457038/69425130-41127800-0d22-11ea-9ecc-8f68c2cf5e8a.png)
> 
> See the last section about IAM authentication

Now after enabling that section , i am getting the below error

{
  "errorMessage": "2019-11-22T14:36:33.871Z 8737d508-2028-4fb8-8fc5-6a6086e8f7d5 Task timed out after 15.02 seconds"
}

START RequestId: 8737d508-2028-4fb8-8fc5-6a6086e8f7d5 Version: $LATEST
END RequestId: 8737d508-2028-4fb8-8fc5-6a6086e8f7d5
REPORT RequestId: 8737d508-2028-4fb8-8fc5-6a6086e8f7d5	Duration: 15015.53 ms	Billed Duration: 15000 ms	Memory Size: 512 MB	Max Memory Used: 36 MB	Init Duration: 85.21 ms	
XRAY TraceId: 1-5dd7f262-30cd55b8ba6243600f9fabf0	SegmentId: 58ce4eaa5617e4f8	Sampled: true	
2019-11-22T14:36:33.871Z 8737d508-2028-4fb8-8fc5-6a6086e8f7d5 Task timed out after 15.02 seconds


Mycode :
func init() {

	fmt.Println("Code Started")
	cfg, err := external.LoadDefaultAWSConfig()
	if err != nil {
		fmt.Println(err)
	}
	config := gettoken()
	
	authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
		awsRegion, "test", cfg.Credentials)
	dnsStrr := fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=require password=%s",
		config["dbhost"], 5432, "test", config["dbname"], authToken)

	
	fmt.Println("authtoken: " + authToken)
	fmt.Println("--------------------------------------------------------------: ")
	fmt.Println("dnsStrr: " + dnsStrr)

	db, err = sql.Open("postgres", dnsStrr)

	fmt.Printf(" ping db dnsStrr: %s\n", db.Ping())
	if err != nil {
		panic(err)
	}
	err = db.Ping()
	if err != nil {
		panic(err)
	}
	fmt.Println("Successfully connected with IAM Authentication Token dnsStrr!")

	

	fmt.Println("Successfully connected with IAM Authentication Token!")
	defer db.Close()
}

**Comment by KarthickEmis** [comment]
> > I do - that works for me...
> > But I meant did you set it up in the Console?
> > ![image](https://user-images.githubusercontent.com/10457038/69425130-41127800-0d22-11ea-9ecc-8f68c2cf5e8a.png)
> > See the last section about IAM authentication
> 
> Now after enabling that section , i am getting the below error
> 
> {
> "errorMessage": "2019-11-22T14:36:33.871Z 8737d508-2028-4fb8-8fc5-6a6086e8f7d5 Task timed out after 15.02 seconds"
> }
> 
> START RequestId: 8737d508-2028-4fb8-8fc5-6a6086e8f7d5 Version: $LATEST
> END RequestId: 8737d508-2028-4fb8-8fc5-6a6086e8f7d5
> REPORT RequestId: 8737d508-2028-4fb8-8fc5-6a6086e8f7d5 Duration: 15015.53 ms Billed Duration: 15000 ms Memory Size: 512 MB Max Memory Used: 36 MB Init Duration: 85.21 ms
> XRAY TraceId: 1-5dd7f262-30cd55b8ba6243600f9fabf0 SegmentId: 58ce4eaa5617e4f8 Sampled: true
> 2019-11-22T14:36:33.871Z 8737d508-2028-4fb8-8fc5-6a6086e8f7d5 Task timed out after 15.02 seconds
> 
> Mycode :
> func init() {
> 
> ```
> fmt.Println("Code Started")
> cfg, err := external.LoadDefaultAWSConfig()
> if err != nil {
> 	fmt.Println(err)
> }
> config := gettoken()
> 
> authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
> 	awsRegion, "test", cfg.Credentials)
> dnsStrr := fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=require password=%s",
> 	config["dbhost"], 5432, "test", config["dbname"], authToken)
> 
> 
> fmt.Println("authtoken: " + authToken)
> fmt.Println("--------------------------------------------------------------: ")
> fmt.Println("dnsStrr: " + dnsStrr)
> 
> db, err = sql.Open("postgres", dnsStrr)
> 
> fmt.Printf(" ping db dnsStrr: %s\n", db.Ping())
> if err != nil {
> 	panic(err)
> }
> err = db.Ping()
> if err != nil {
> 	panic(err)
> }
> fmt.Println("Successfully connected with IAM Authentication Token dnsStrr!")
> 
> 
> 
> fmt.Println("Successfully connected with IAM Authentication Token!")
> defer db.Close()
> ```
> 
> }

Atleast when i try with sdk version 1 , i am getting print statements.. PFB the code below

package main

import (
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go/aws/credentials/stscreds"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/rds/rdsutils"
	dbconnection "github.com/emisgroup/appointment-examples/src/go/db"
	_ "github.com/lib/pq"
)

var (
	appID, sender string
	db            *sql.DB
)

const awsRegion = "eu-west-2"

func init() {

	fmt.Println(" test code base")
	// cfg, err := external.LoadDefaultAWSConfig()
	// if err != nil {
	// 	fmt.Println(err)
	// }
	config := gettoken()
	awsCreds := stscreds.NewCredentials(session.New(), "arn:aws:iam::443638508890:role/lambda-vpc-role")
	authToken, err := rdsutils.BuildAuthToken(config["dbhost"], awsRegion, "test", awsCreds)
	// authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
	// 	awsRegion, "test", cfg.Credentials)
	dnsStrr := fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=require password=%s",
		config["dbhost"], 5432, "test", config["dbname"], authToken)


	fmt.Println("authtoken: " + authToken)
	fmt.Println("--------------------------------------------------------------: ")
	fmt.Println("dnsStrr: " + dnsStrr)

	db, err = sql.Open("postgres", dnsStrr)

	fmt.Printf(" ping db dnsStrr: %s\n", db.Ping())
	if err != nil {
		panic(err)
	}
	err = db.Ping()
	if err != nil {
		panic(err)
	}
	fmt.Println("Successfully connected with IAM Authentication Token dnsStrr!")

	

	fmt.Println("Successfully connected with IAM Authentication Token!")
	defer db.Close()
}

Error : **panic: pq: PAM authentication failed for user "test"**

**Comment by mpreziuso** [comment]
I'm getting a bit confused here due to the formatting of your messages, but I can see this is wrong
```
authToken, err := rdsutils.BuildAuthToken(config["dbhost"], awsRegion, "test", awsCreds)
```
the first parameter should be host:port as you were doing previously.
If you do that I guess the PAM auth failure should go away

**Comment by KarthickEmis** [comment]
> that I guess the PAM auth failure sho

I did like below
authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
		awsRegion, "test", awsCreds)

but now getting time out error.
**"errorMessage": "2019-11-22T14:58:40.086Z 4193222c-a637-436f-83e7-943b46ce4428 Task timed out after 15.01 seconds"**

My DB is publicly accessible only...

**Comment by mpreziuso** [comment]
Not sure why that would happen: since you were getting authentication failures that should mean you can reach your RDS instance on port 5432. Have you changed anything else? Security groups, routes, IAM role of your lambda?

**Comment by KarthickEmis** [comment]
> Not sure why that would happen: since you were getting authentication failures that should mean you can reach your RDS instance on port 5432. Have you changed anything else? Security groups, routes, IAM role of your lambda?

Hey , Is working fine .... After we modified the host with port in building the auth token , it is working....

**Comment by KarthickEmis** [comment]
> > Not sure why that would happen: since you were getting authentication failures that should mean you can reach your RDS instance on port 5432. Have you changed anything else? Security groups, routes, IAM role of your lambda?
> 
> Hey , Is working fine .... After we modified the host with port in building the auth token , it is working....

import (
	"database/sql"
	"fmt"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go-v2/aws/external"
	"github.com/aws/aws-sdk-go-v2/service/rds/rdsutils"
	_ "github.com/lib/pq"
)

var (
	appID, sender string
	db            *sql.DB
)

const awsRegion = "eu-west-2"

func init() {

	fmt.Println(" test code base")
	cfg, err := external.LoadDefaultAWSConfig()
	if err != nil {
		fmt.Println(err)
	}
	config := gettoken()
	authToken, err := rdsutils.BuildAuthToken(fmt.Sprintf("%s:%d", config["dbhost"], 5432),
		awsRegion, "test", cfg.Credentials)
	dnsStrr := fmt.Sprintf("host=%s port=%d user=%s dbname=%s sslmode=require password=%s",
		config["dbhost"], 5432, "test", config["dbname"], authToken)

	fmt.Println("authtoken: " + authToken)
	fmt.Println("--------------------------------------------------------------: ")
	fmt.Println("dnsStrr: " + dnsStrr)

	db, err = sql.Open("postgres", dnsStrr)

	if err != nil {
		panic(err)
	}
	err = db.Ping()
	if err != nil {
		panic(err)
	}
	fmt.Println("Successfully connected with IAM Authentication Token dnsStrr!")

	defer db.Close()
}

**Comment by KarthickEmis** [comment]
its working .. I am closing this issue.. I posted the working code above .... thanks @mpreziuso  for your help on this issue.
