### ISSUE TITLE
Please add environment variable to configure proxy for credential fetch

### ISSUE THREAD

**Issue by hixichen** [aws/aws-sdk-go-v2#451]
Right now, when aws service starts the session, it will send request to `https//169.254.xxxx/meta-data/iam/security-credentials` based on the chain. 

Ideally, we  want to manage the credentials somewhere but grant just session token to pod/container. 

is that possible for us to have `CREDENTIAL_PROXY` env, that it will send request to `CREDENTIAL_PROXY/meta-data/iam/security-credentials` for session token? 

if that happens, at least it solved problems like:
 - no access key/id configured required for pod/container
-  no key rotation require for pod/container as aws-go-sdk can handle it automatically.
- people can use aws IAM anywhere without strict to aws ec2.  
    Right now, unless you are running it on aws ec2, you need to do code injection on code level to handle the credential rotation.

**Comment by jasdel** [comment]
Thanks for the feature request @hixichen. The V2 SDK has a feature that i think will allow you to use an arbitrary credential provider endpoint with your application.

The SDK's [endpointcreds](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/endpointcreds?tab=doc) package is a credentials provider based on an arbitrary endpoint URL. This credential provider can be triggered via the environment variable, `AWS_CONTAINER_CREDENTIALS_FULL_URI`

```sh
export AWS_CONTAINER_CREDENTIALS_FULL_URI=https://localhost:1234/path/to/creds
```

This will be read, and trigger the endpoint credentials provider to be used by the SDK when the `LoadDefaultAWSConfig` configuration loader is used.

```go
func main() {
    os.SetEnv("AWS_CONTAINER_CREDENTIALS_FULL_URI", "https://localhost:1234/path/to/creds")

    cfg, err := external.LoadDefaultAWSConfig()

    // use cfg with client.
}
```

**Comment by hixichen** [comment]
@jasdel  that is awesome. 

thanks. 
If I want to implement the external credential provider, 
Any doc on the input/output structure for this is credential api?
thanks

**Comment by foxroot** [comment]
>     os.SetEnv("AWS_CONTAINER_CREDENTIALS_FULL_URI", "https://localhost:1234/path/to/creds")

it should be os.Setenv

**Comment by jasdel** [comment]
Thanks for pointing the typo out. I've pdated the example.

**Comment by jasdel** [comment]
The [IAM Roles for Tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) doc describes the input/output expectations of the endpoint credential provider.

Closing this issue due to age, and feature supported.
