### ISSUE TITLE
aws clonning gitbun error 

### ISSUE THREAD

**Issue by SlowMonk** [aws/aws-sdk-go-v2#455]
Dec 12 03:51:11 ip-172-31-18-207 amazon-ssm-agent.amazon-ssm-agent[1282]: 2019-12-12 03:51:11 ERROR Health ping failed with error - EC2RoleRequestError: no EC2 instance role found
Dec 12 03:51:11 ip-172-31-18-207 amazon-ssm-agent.amazon-ssm-agent[1282]: caused by: EC2MetadataError: failed to make EC2Metadata request
Dec 12 03:51:11 ip-172-31-18-207 amazon-ssm-agent.amazon-ssm-agent[1282]: caused by: <?xml version="1.0" encoding="iso-8859-1"?>

got following error when I was clonning the github from aws server

**Comment by skotambkar** [comment]
Thanks for reaching out. Can you give us more information about this issue you are facing? This seems like an ssm agent issue. If so, you should open a ticket at https://github.com/aws/amazon-ssm-agent
