### ISSUE TITLE
Unable to mock responses in dynamodbiface

### ISSUE THREAD

**Issue by hgl** [aws/aws-sdk-go-v2#466]
the `ClientAPI` interface only lets you mock methods like
```
QueryRequest(*dynamodb.QueryInput) dynamodb.QueryRequest
```
However, the response is returned by `QueryRequest`'s `Send` method, so mocking this method doesn't give the ability to control the response, which is what I'd actually like to mock.

This doesn't seem right. Did I miss something?

**Comment by hgl** [comment]
Given the current API design, it's actually not easy to mock I think.

I wonder why dynamodb didn't use an API like

```
Query(context.Context, *dynamodb.QueryInput) (dynamodb.QueryResponse, err)
```

That will make it very easy to mock responses

**Comment by jasdel** [comment]
Thanks for the feedback @hgl We're working on a design that will hopefully address this issue, and is very similar to your suggestion. Check out issue #438

**Comment by jasdel** [comment]
Lets use #438 to track this issue, and additional feedback.
