### ISSUE TITLE
dynamodb transaction API is confusing

### ISSUE THREAD

**Issue by hgl** [aws/aws-sdk-go-v2#467]
`TransactWriteItem` has a struct like this
```go
type TransactWriteItem struct {

    // A request to perform a check item operation.
    ConditionCheck *ConditionCheck `type:"structure"`

    // A request to perform a DeleteItem operation.
    Delete *Delete `type:"structure"`

    // A request to perform a PutItem operation.
    Put *Put `type:"structure"`

    // A request to perform an UpdateItem operation.
    Update *Update `type:"structure"`
    // contains filtered or unexported fields
}
```

So it seems we can, for example, specify both a `Delete` and `Put` in the same `TransactWriteItem`.

But [from doc's code example](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-example.html), each `TransactWriteItem` seems should only contain one type of operation.

If that's the case, I'd suggest turn `TransactWriteItem` intro an interface, and each concrete type determines it's a `Delete` or `Put`, etc, so there is no confusion.

**Comment by jasdel** [comment]
Thanks for the feedback @hgl. Using interfaces to provide tagged union like behavior would help improve the usability of these APIs types. Regretfully the API model and SDKs do not support tagged unions. This feature is something that we are looking to support in the v2 SDK before GA. Though the v2 SDK's feature would only be applied to API models that also use tagged unions, and only new API models could take advantage of the tagged union feature.

**Comment by hgl** [comment]
Thanks for the quickly reply @jasdel.

By "API models" do you mean the low level restful API aws offers?

Does the transaction API falls under tagged unions? Sorry, I'm not quite familiar with the term.

**Comment by jasdel** [comment]
`API models` refers to the modeled definitions of the services' APIs. For example the Amazon DynamoDB's model is defined in an [api-2.json](https://github.com/aws/aws-sdk-go-v2/blob/cb4b3d06029127cf8416fb1730250bffd107c642/models/apis/dynamodb/2012-08-10/api-2.json) file that the SDK's code generation reads from and generates the Go clients and types from.

These models define operations, parameters, and how the SDK interacts with the API. With regard the Go `TransactWriteItem` struct is generated from the model's definition. Which defines the separate members, (e.g. `Delete`, `Put`, and `Update`).

If the API models supported the [tagged unions](https://awslabs.github.io/smithy/spec/core.html#union) the API could be defined the way you've suggested and the SDK could generate an interface implementations for the specific `Delete`, `Put`, and `Update` behaviors.

While this feature is currently not supported, it is something we are investigating for the v2 SDK. We're investigating how the SDK could be updated to support this feature prior to GA of the v2 SDK.

**Comment by hgl** [comment]
Didn't know they exist, thanks.

Since v2 SDK has been in the pipeline for almost 2.5 years (from the earliest commit date), I guess it's going to be awhile before GA can be ready? The new APIs are probably going to be available sooner, but I guess it's still a long way ?

BTW, is it advisable that I build my projects on V2  right now? Will the new APIs be a breaking or compatible change?

**Comment by jasdel** [comment]
I do not suggest building projects with the V2 SDK currently. While there are no know functional issues with it, it is not ready for production, and does have several planned breaking changes prior to its GA. 

While I cannot share a timeline for when the project will be GA, we are actively working on it. Priories with the v1 SDK slowed down the development of the v2 SDK last year.

**Comment by jasdel** [comment]
Closing this due to age. The v2 SDK is working with the Smithy API model team on how DynamoDB APIs can be updated to make use of tagged unions. The SDK will automatically be updated once the API model is updated.
