### ISSUE TITLE
[S3][AccessPoints] Custom endpoints should not be modified when using accesspoints.

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#479]
The current implementation in the V2 SDK for support S3's AccessPoint feature will manipulate the resolved endpoint URL when an AccessPoint ARN is provided in a bucket parameter. This is not the intended behavior per the implementation in V1. This is due to the current endpoint resolver design preventing the ability to disambiguate an endpoint resolved from the default endpoint resolver in `aws/endpoint` from a custom endpoint provided by a user using a custom resolver such as `aws/endpoints.EndpointResolverFunc`

**Comment by jasdel** [comment]
This issue was resolved with https://github.com/aws/aws-sdk-go-v2/pull/848 that added an option to the Endpoint resolver for users to direct the SDK to not modify the custom endpoint.
