### ISSUE TITLE
Why does  GetBucketTaggingRequest return an error when there are no tags rather than an empty tagset

### ISSUE THREAD

**Issue by dre2004** [aws/aws-sdk-go-v2#489]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
v0.19.0

### Version of Go (`go version`)?
go1.13.7 linux/amd64

### What issue did you see?
When I use the GetBucketTaggingRequest method I get an error when there are no tags on a bucket.

NoSuchTagSet: The TagSet does not exist
        status code: 404, request id: 123948769000, host id: somehostidhash=

### Steps to reproduce

		request := svc.GetBucketTaggingRequest(
			&s3.GetBucketTaggingInput{
				Bucket: aws.String("somebucketwithnotags"),
			},
		)
		response, err := request.Send(context.Background())
		if err != nil {
			fmt.Println(err)
		}
If you have have an runnable example, please include it.

I've used similar methods for other services, and although there is no consistent way of getting tags across services (some are given as part of a describe call, while others are their own method) the S3 api is the only one which actually gives you an error when there are no tags. I was expecting just to see an empty tagset as is seen for EC2, RDS, EMR, ELB, etc, etc ...

**Comment by jasdel** [comment]
HI @dre2004 thanks for reaching out. Thanks for the feedback on the API behavior. In this case the best place to share this feedback will be the [S3 API forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).  This behavior is driven by the service API returning an error when the tags are not present.
