### ISSUE TITLE
InvalidClientTokenId: The security token included in the request is invalid... status code: 403

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#491]
Maybe this is the same issue as https://github.com/aws/aws-sdk-go-v2/issues/475 ?

I'm trying to do a:

`aws --profile mine sns subscribe --topic-arn arn:aws:sns:ap-southeast-1:407461997746:dabase --protocol email --notification-endpoint me@example.com`

### Version of AWS SDK for Go?

github.com/aws/aws-sdk-go-v2 v0.19.0

### Version of Go (`go version`)?

go version go1.13.8 linux/amd64

### What issue did you see?

InvalidClientTokenId: The security token included in the request is invalid.

### Steps to reproduce

http://play.golang.org/p/w1D8UZ1MYrQ

Workaround is downgrade to v1 https://github.com/kaihendry/sns-subscribe which is a pretty crazy DX.

**Comment by jasdel** [comment]
Hi @kaihendry are you still running into this issue? There were several improvements made to the SDK's external configuration loading package in v0.21.0. that might address this issue.
