### ISSUE TITLE
github.com/jmespath/go-jmespath is Unlicensed

### ISSUE THREAD

**Issue by MaerF0x0** [aws/aws-sdk-go-v2#497]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
`github.com/aws/aws-sdk-go-v2 v0.19.0`

### Version of Go (`go version`)?
```
go version
go version go1.13.8 darwin/amd64
```

### What issue did you see?
https://github.com/jmespath/go-jmespath does not have a license (ie is unlicensed)

### Steps to reproduce
https://github.com/jmespath/go-jmespath. --> no license file afaik 
see: https://github.com/jmespath/go-jmespath/issues/34

**Comment by skmcgrail** [comment]
The license file is available in the repository root [here](https://github.com/jmespath/go-jmespath/blob/master/LICENSE) and is licensed under Apache Version 2.0.

**Comment by MaerF0x0** [comment]
you are correct, not sure how i came to ^^ conclusion.  Thank you
