### ISSUE TITLE
apigatewaymanagementapi.PostToConnectionRequest uses invalid hostname

### ISSUE THREAD

**Issue by RaeesBhatti** [aws/aws-sdk-go-v2#513]
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
`apigatewaymanagementapi` service tries to connect to wrong endpoint and fails.

`apigatewaymanagementapi.PostToConnectionRequest` ends up sending the request to  `https://execute-api.us-west-2.amazonaws.com/@connections/<connectionId>`. Hostname is not correct, it should contain API ID before `execute-api`, like so, `https://<ApiGW-Api-Id>execute-api.us-west-2.amazonaws.com/@connections/<connectionId>`.

Or it should make use of `EndpointResolver` resolver specified in `aws.Config`.

**Version of AWS SDK for Go?**
```
github.com/aws/aws-sdk-go-v2 v0.9.0
```

**Version of Go (`go version`)?**
```
go version go1.14 darwin/amd64
```

**To Reproduce (observed behavior)**
Here is sample code:
```
awsCfg, err = external.LoadDefaultAWSConfig(aws.Config{
	Region: "us-east-2",
	EndpointResolver: aws.ResolveWithEndpointURL(event.RequestContext.DomainName + "/" + event.RequestContext.Stage),
})
if err != nil {
	log.Fatalln("unable to load SDK config", err)
}
var apigwClient = apigatewaymanagementapi.New(awsCfg)
_, err := apigwClient.PostToConnectionRequest(&apigatewaymanagementapi.PostToConnectionInput{
	ConnectionId: aws.String(req.RequestContext.ConnectionID),
	Data:         []byte(req.Body),
}).Send(ctx)
if err != nil {
	log.Fatalln("PostToConnectionRequest error", err)
}
```

**Expected behavior**
`PostToConnectionRequest` uses `EndpointResolver` specified in the `aws.Config`.

**Additional context**

**Comment by jasdel** [comment]
HI @RaeesBhatti thanks for reaching out. The issue you're running into is due to a complexity in the `LoadDefaultAWSConfig` function. The function takes a variadic argument of abstract configuration provider interfaces, that `aws.Config` does not satisfy. In order to specify the endpoint to be used for an apigateway API the following code will do what you're looking for.

```go
awsCfg, err := external.LoadDefaultAWSConfig(
     external.WithRegion("us-east-2"),
)
if err != nil {
	log.Fatalln("unable to load SDK config", err)
}
// Create a copy of the config before modifying it if there are other API clients
// created from this loaded config value.
apiGWCfg := cfg

// Set the configuraiton resolver on the api gateway specific config value.
apigwCfg.EndpointResolver = aws.ResolveWithEndpointURL(
    event.RequestContext.DomainName + "/" + event.RequestContext.Stage)

var apigwClient = apigatewaymanagementapi.New(apigwCfg)
_, err := apigwClient.PostToConnectionRequest(&apigatewaymanagementapi.PostToConnectionInput{
	ConnectionId: aws.String(req.RequestContext.ConnectionID),
	Data:         []byte(req.Body),
}).Send(ctx)
if err != nil {
	log.Fatalln("PostToConnectionRequest error", err)
}
```
