### ISSUE TITLE
Can not change ttl when record sets set weight.

### ISSUE THREAD

**Issue by deancn** [aws/aws-sdk-go-v2#518]
Confirm by changing [ ] to [x] below:
Question:
need to change TTL,   Which the record has weight setting.

**Describe the question**
go.mod:
	github.com/aws/aws-sdk-go-v2 v0.20.0

Type: InvalidChangeBatch
Error message: "[RRSet with DNS name <domain>  and type A, SetIdentifier <SetIdentifier> cannot be created as weighted sets must contain the same TTL.]"

- [x] I've checked  
if the record sets use geo,  It can be changed.

**Comment by jasdel** [comment]
HI @deancn are you still having an issue with this API? cloud you clarify which API and operation you're running into issue with?

**Comment by deancn** [comment]
yes
