### ISSUE TITLE
Credentials Setup

### ISSUE THREAD

**Issue by Buttered** [aws/aws-sdk-go-v2#522]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

Does anyone know how i could go about using IAM credentials to login to an external application I am developing?  I have it properly configured to read from the ~./aws/credentials file, but is there a way to load it based on credentials passed through?  Not sure if there is another AWS service for this or if using sessions would be the right way to go.

Thanks.

**Comment by jasdel** [comment]
Hi @Buttered are you still experiencing this issue?  The SDK recently released v0.21.0 which included improvements for using the SDK's `external` configuration loading package. This includes improvements for IAM credentials. Let us know if you're still having issues or questions.
