### ISSUE TITLE
Request: Create a V4 Signing function that takes just a *http.Request

### ISSUE THREAD

**Issue by veqryn** [aws/aws-sdk-go-v2#528]
**Is your feature request related to a problem? Please describe.**
It is very useful to be able to sign requests with an AWS v4 signer, by use of golang's "RoundTripper" interface.
The RoundTrip method only has access to the `*http.Request`.
An example of its usage in a popular library for ElasticSearch: https://github.com/olivere/elastic/blob/934bd89bb25b465998362ca1e1d908c6208f333d/aws/sign_v4.go#L28-L41

```go
func NewV4SigningClient(credentials awsauth.Credentials) *http.Client {
	return &http.Client{
		Transport: V4Transport{
			HTTPClient:  http.DefaultClient,
			Credentials: credentials,
		},
	}
}

// V4Transport is a RoundTripper that will sign requests with AWS V4 Signing
type V4Transport struct {
	HTTPClient  *http.Client
	Credentials awsauth.Credentials
}

// RoundTrip uses the underlying RoundTripper transport, but signs request first with AWS V4 Signing
func (st V4Transport) RoundTrip(req *http.Request) (*http.Response, error) {
	// Would like to use official aws sdk to sign the request right here, but instead am using a deprecated 3rd party library:
	return st.HTTPClient.Do(awsauth.Sign4(req, st.Credentials))
}
```

**Describe the solution you'd like**
I would like the v4 Signer to have a method that can sign an `*http.Request`, by figuring out everything it needs from the request object.

**Describe alternatives you've considered**
Right now we use some other v4 signing libraries, but they have been discontinued/deprecated, and we would prefer to use the official aws sdk.

**Comment by jasdel** [comment]
Thanks for reaching out @veqryn Take a look at the [v4#Signer.SignHTTP](https://github.com/aws/aws-sdk-go-v2/blob/master/aws/signer/v4/v4.go#L287) method. It takes an *http.Request along with a few other parameters, and will update the passed in request to include the signature.

The utility isn't able to derive all the metadata it needs from the http.Request, which is the reason for the additional fields.

You can use this like:

```go
signer := v4.NewSigner(creds)

err := signer.SignHTTP(ctx, req, reqBodySHA256, apiSigningName, signingRegion, time.Now())
```

**reqBodySHA256**: This is the hex encoded SHA256 hash of the request body. If the request does not have a body use an empty string to compute the hash on instead.

**apiSigningName**: This is the name the API uses to identify the service the request is scoped to.

**signingRegion**: is the AWS region the request was signed for by the client. All requests must be signed for a single region that the request will be sent to.

**Comment by veqryn** [comment]
Ya, I was hoping there would be a method without those fields, that could figure them out from the url and the body.
