### ISSUE TITLE
creating client fails with `unable to get 16 bytes for UUID, got 10`

### ISSUE THREAD

**Issue by sb2nov** [aws/aws-sdk-go-v2#534]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Creating a new aws client would sometimes fail with `unable to get 16 bytes for UUID, got 10` the number of bytes fetched is inconsistent.

**Version of AWS SDK for Go?**
Example: v0.20.0
* get SDK version by printing the output of `aws.SDKVersion` in your code after importing `"github.com/aws/aws-sdk-go-v2/aws"`

**Version of Go (`go version`)?**
1.14.2

**To Reproduce (observed behavior)**
Creating dynamodb clients again and again would fail with this once in a while.

**Expected behavior**
No error

**Comment by sb2nov** [comment]
This doesn't happen in v0.19 so most likely some side effect of pr #487

**Comment by jasdel** [comment]
Thanks for reporting this bug @sb2nov I've posted PR #536 that fixes the SDKs behavior when reading from a crypto source to ensure it gets all the bytes it needs.

**Comment by sb2nov** [comment]
Thanks for the quick fix @jasdel, appreciate the help :)

**Comment by jasdel** [comment]
We've released this fix as a tagged released, [v0.21.0](https://github.com/aws/aws-sdk-go-v2/releases/tag/v0.21.0). You should be able to update to pull in these fixes and updates.
