### ISSUE TITLE
Describe method to return both the payload and the error rather than just one

### ISSUE THREAD

**Issue by dre2004** [aws/aws-sdk-go-v2#546]
**Is your feature request related to a problem? Please describe.**
Currently, when we use a describe method such as ec2.DescribeInstances, and we pass a slice of instance ID's and we call the Send method we get either a result or an error. This feature request is to combine the response so each time the send method is called we get both.

The main use case here is if we are trying to do a describe request to get instance details based on the output from another service, in my case I'm using the output of computeoptimizer.GetEC2InstanceRecommendations specifically and feeding the instances into ec2.DescribeInstances to get additional details (tags). Right now if one of the instances no longer exists, I get an error from ec2.DescribeInstances and no data for the instances that do exist.

I would like to be able to get both the error and the payload, right now the only work around I can put in place is to do a ec2.DescribeInstances request with a single instance in each request which is not as efficient as sending a slice of instances.

**Describe the solution you'd like**
I think simply removing the if statement after the Send request could possibly achieve this, assuming that the backing API will provide both the response payload and an error if some of the instances exists

```
// Send marshals and sends the DescribeInstances API request.
func (r DescribeInstancesRequest) Send(ctx context.Context) (*DescribeInstancesResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()

	resp := &DescribeInstancesResponse{
		DescribeInstancesOutput: r.Request.Data.(*DescribeInstancesOutput),
		response:                &aws.Response{Request: r.Request},
	}

	return resp, err
}
```

**Describe alternatives you've considered**
I am currently doing a describe per instance, which is less than ideal and takes a lot longer than submitting a single request.

**Comment by jasdel** [comment]
Thanks for reaching out to us about this issue. The issue you're experiencing is due to the design of the API. The SDK won't have access the a result and error values at the same time.  The API only provides one or the other. With that said v0.25.0 of the SDK also added typed errors, so error messages that come back from a service can include additional information that previous version of the SDK did not deserialize, and ignored.

**Comment by dre2004** [comment]
Thanks for the update, I guess if the service API only provides either a response payload OR an error there is not a whole lot that can be done in the SDK. I guess unless you're 100% certain that all instances exist you are better off doing a describe call per instance.

**Comment by jasdel** [comment]
Thanks for the update @dre2004. The SDK will only be able to provide the information sent back to it by the API. It doesn't have any control over what data will or won't be sent back in the case of an error processing by the service.
