### ISSUE TITLE
[QLDB] QldbHash - BadRequestException: Digests don't match

### ISSUE THREAD

**Issue by MarinX** [aws/aws-sdk-go-v2#550]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

I have a following implementation of the qldb hash logic
```go
package qldb

import (
	"crypto/sha256"
	"hash"
)

type Hash struct {
	qldbHash hash.Hash
}

func NewQldbHash(qldbHash hash.Hash) *Hash {
	return &Hash{
		qldbHash: qldbHash,
	}
}

func ToQldbHash(buff []byte) *Hash {
	sh := sha256.New()
	sh.Write(buff)
	return NewQldbHash(sh)
}

func (q *Hash) Value() []byte {
	return q.qldbHash.Sum(nil)
}

func (q *Hash) Dot(h *Hash) *Hash {
	concatenated := joinHashesPairwise(q.qldbHash.Sum(nil), h.qldbHash.Sum(nil))
	sh := sha256.New()
	sh.Write(concatenated)
	return NewQldbHash(sh)
}

func joinHashesPairwise(h1 []byte, h2 []byte) []byte {
	diff := bytes.Compare(h1, h2)
	if diff < 0 {
		return append(h1[:], h2[:]...)
	}
	return append(h2[:], h1[:]...)
}

```

I also implemented a driver and session handling, so when I want to execute a statement, it will
- Create a transaction and transaction hash (``` ToQldbHash([]byte("transactionID") ``` )
- Execute the statement
- Commit the transaction

It always fail on `commit` and returns an error of `BadRequestException: Digests don't match`.

Consider the following `ExecuteStatement` function
```go
func (s *Session) ExecuteStatement(ctx context.Context, stmt string, params ...interface{}) error {
	if s.transactionID == nil {
                // here we create transactionHash = ToQldbHash([]byte("transactionID"))
		if err := s.StartTransaction(ctx); err != nil {
			return err
		}
	}

	stmtHash := ToQldbHash([]byte(stmt))

	var valueHolderList []qldbsession.ValueHolder
	for _, p := range params {
		ionBin, err := ion.MarshalBinary(p)
		if err != nil {
			return err
		}

		stmtHash = stmtHash.Dot(ToQldbHash(ionBin))
		valueHolderList = append(valueHolderList, qldbsession.ValueHolder{
			IonBinary: ionBin,
		})
	}

	s.transactionHash = s.transactionHash.Dot(stmtHash)

	_, err := s.client.SendCommandRequest(&qldbsession.SendCommandInput{
		SessionToken: s.id,
		ExecuteStatement: &qldbsession.ExecuteStatementRequest{
			TransactionId: s.transactionID,
			Parameters:    valueHolderList,
			Statement:     &stmt,
		},
	}).Send(ctx)

	if err != nil {
		return err
	}
         // here we add CommitDigest = transactionHash.Value() and returns error
	return s.CommitTransaction(ctx)
}
``` 

I looked at the nodejs, java and python implementation and follow the same pattern and it still fails on digest. My digest and aws digest does not match.
Looking for a help with the qldb SDK on why the digest hash is wrong on my side.

**Comment by jasdel** [comment]
Closing this issue due to staleness. The v2 SDK is now GA and has refactored several of its internal components since this issue was created. If you're still experiencing issues after updating to the latest version of the SDK, please open a new issue.
