### ISSUE TITLE
To fast subsquent (10) invocations (set to higher throughput limit) will give all as InvalidParameters - shouldn't it be HTTP 400?

### ISSUE THREAD

**Issue by mariotoffia** [aws/aws-sdk-go-v2#552]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

I'm doing a little [ssm decoder library](https://github.com/mariotoffia/ssm). However, when I do unit testing there are a few calls towards the Parameter Store (around 10 within a second). If it where to be throttled I would expect the _HTTP 400_ instead the HTTP code is 200 and response is that all parameters are set as invalid.

I've temporarily solved this using a for and sleep (see snippet below) - but it will cost me a lot in each lambda if this would hit after 10 invocations / s. I've set the "paid tier, higher throughput limit" and as per documentation I should be able to do 1.000 request / s.

Questions:
1) Shouldn't it be HTTP 400 returned if throttled?
2) I don't really see 10 request as a subject to be throttled since I should have 1,000 TPS since got "paid tier, higher throughput limit" - then why this behaviour?

Cheers,
 Mario

Steps to reproduce:
+ `git clone https://github.com/mariotoffia/ssm.git`
+ comment out sleep (see below)
+ `make testverbose`
+ Check the output for error testcase

from [internal/pms/serializer.go](https://github.com/mariotoffia/ssm/blob/master/internal/pms/serializer.go#L162):

```go
func (p *Serializer) getFromAws(params *ssm.GetParametersInput) (map[string]ssm.Parameter, []string, error) {
	client := ssm.New(p.config)

	var resp *ssm.GetParametersResponse
	var err error
	success := false
	for i := 0; i < 3 && !success; i++ {
		req := client.GetParametersRequest(params)

		resp, err = req.Send(context.TODO())
		if err != nil {
			return nil, nil, errors.Wrapf(err, "Failed fetch pms config entries %v", params)
		}

		if len(resp.Parameters) == 0 && len(resp.InvalidParameters) > 0 {
                       // HERE IS THE UGLY PART...
			time.Sleep(400 * time.Millisecond)
		} else {
			success = true
		}
	}
  // ...
}
```

**Comment by jasdel** [comment]
Thanks for reporting this issue @mariotoffia, The v2 SDK is now GA and has fixed, and refactored several of its internal components to improve its behavior with regard to how it interacts with API calls.  This issue was created with a version of the v2 SDK that has been significantly refactored since.

If you're still experiencing issues please open a new issue.
