### ISSUE TITLE
[bug] service/dynamodb/expression#Expression.returnExpression does not return nil if unset

### ISSUE THREAD

**Issue by alextbok** [aws/aws-sdk-go-v2#554]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
The code here is incorrect: https://github.com/aws/aws-sdk-go-v2/blob/241222ec3c705bcc2b729dfe8d0cc4e01bd70b80/service/dynamodb/expression/expression.go#L487-L492

It should be:
```
if e.expressionMap == nil {
  return nil
}
if _, ok := e.expressionMap[expressionType]; !ok {
  return nil
}
return aws.String(e.expressionMap[expressionType])
```
This will make the behavior consistent with the documentation. For example, `Filter()` docs specify that it returns null if the filter doesn't exist:
```
// Filter returns the *string corresponding to the Filter Expression of the
// argument Expression. This method is used to satisfy the members of DynamoDB
// input structs. If the Expression does not have a filter expression this
// method returns nil.
//
// Example:
//
//     // let expression be an instance of Expression{}
//
//     queryInput := dynamodb.QueryInput{
//       KeyConditionExpression:    expression.KeyCondition(),
//       FilterExpression:          expression.Filter(),
//       ExpressionAttributeNames:  expression.Names(),
//       ExpressionAttributeValues: expression.Values(),
//       TableName: aws.String("SomeTable"),
//     }
func (e Expression) Filter() *string {
	return e.returnExpression(filter)
}
```

With the way the code is currently written, calls to dynamo with an unset filter (but another set expression, e.g. projection) will fail with: `ValidationException: Invalid FilterExpression: The expression can not be empty`

**Version of AWS SDK for Go?**
Example: v1.29.22
* get SDK version by printing the output of `aws.SDKVersion` in your code after importing `"github.com/aws/aws-sdk-go-v2/aws"`

**Version of Go (`go version`)?**
go version go1.13.7 darwin/amd64

**To Reproduce (observed behavior)**
Described above

**Expected behavior**
Described above

**Additional context**

**Comment by jasdel** [comment]
Thanks for submitting this bug report. we've merged in the change, and it will be included in the SDK's next release.
