### ISSUE TITLE
Support a token cache in ~/.aws/cli/cache

### ISSUE THREAD

**Issue by int128** [aws/aws-sdk-go-v2#555]
**Is your feature request related to a problem? Please describe.**

When I create a command tool which supports IAM role switching with MFA, aws-sdk asks a MFA code every time. On the other hand, AWS CLI saves a token into `~/.aws/cli/cache` and reuses it if it is valid. It would be nice if aws-sdk supports the cache interoperable with AWS CLI.

Is there any plan to support a token cache in `~/.aws/cli/cache`?

**Describe the solution you'd like**

botocore library (python) implements cache as: https://github.com/boto/botocore/blob/9f5afe26cc4a2695dcb62db453f9db7c299f3ffc/botocore/credentials.py#L714

It may be possible to implement the same mechanism in Go.

**Describe alternatives you've considered**

Saving and reusing a token in an application may be workaround.

**Comment by jasdel** [comment]
Thanks for creating this feature request. The CLI's token cache is an internal implementation detail of the CLI. It would be introduce significant risk to the SDK if it were to depend on this cache.

With that said the SDK is looking at supporting SSO in conjunction with the CLI, https://github.com/aws/aws-sdk-go-v2/issues/705
