### ISSUE TITLE
Date header breaks AttemptClockSkewHandler

### ISSUE THREAD

**Issue by mrsufgi** [aws/aws-sdk-go-v2#556]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Noticed error logs since May 1st, checked and it didn't happen before.
Error logs:
```
2020/05/04 08:48:10 ERROR: unable to determine clock skew for Kinesis/PutRecord API response, invalid Date header value, Mon, 4 May 2020 08:48:10 GMT.

```
As you can tell the date header is ```Mon, 4 May 2020``` which is an invalid date, missing 0 before the 4.

What is the origin of the Date header? might it be a user error? Am I doing something wrong? 

```go
func (p *kinesisProducerRepository) Publish(b []byte) error {
	randomPartitionKey := utils.RandomString(PartitionKeyLength)
	input := &kinesis.PutRecordInput{
		Data:         b,
		StreamName:   p.streamName,
		PartitionKey: &randomPartitionKey,
	}

	req := p.kc.PutRecordRequest(input)
	resp, err := req.Send(context.TODO())
	return err
}
```

**Version of AWS SDK for Go?**
v0.20.0 

**Version of Go (`go version`)?**
1.14

**To Reproduce (observed behavior)**
https://play.golang.org/p/iWcVnT9MEhs

**Expected behavior**
No errors between 1-9 day of the month

**Comment by jasdel** [comment]
Thanks for reporting this bug @mrsufgi. Looks like the SDK's usage of the standard library default Date parsing isn't sufficient. It looks like PR #560 adds a fix for this behavior to allow the SDK to work more correctly with the additional format. We're review that PR and look for a fix from there.
