### ISSUE TITLE
s3's ListPartsOutput's PartNumberMarker not as documented

### ISSUE THREAD

**Issue by eikeon** [aws/aws-sdk-go-v2#565]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

s3's ListPartsOutput's PartNumberMarker field is documented the same as its NextPartNumberMarker field. But does not return the same ;) NextPartNumberMarker works as documented and PartNumberMarker does not.

See: https://github.com/aws/aws-sdk-go-v2/blob/40a22fcb842831dd1511cc4a79f9fdc3c308e407/service/s3/api_op_ListParts.go#L201

**Version of AWS SDK for Go?**

v0.21.0

**Version of Go (`go version`)?**

v1.14

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

make a ListPartsRequest

**Expected behavior**

expect a NextPartNumberMarker

**Additional context**

Instead get PartNumberMarker of 0 over and over :(

**Comment by jasdel** [comment]
Thanks for reporting this issue. It looks like this is an issue with the Amazon S3 API model definition that the SDK is built from. The best way to improve the visibility of this issue is to reach out directly to the S3 [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) to raise the issue.
