### ISSUE TITLE
Support Discovered Endpoints that don't specify Scheme

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#566]
Port https://github.com/aws/aws-sdk-go/pull/3137

**Comment by jasdel** [comment]
This issue has already [been address](https://github.com/aws/aws-sdk-go-v2/blob/40a800b6768bfb08ea9fce4d0e0786b24404f33d/service/timestreamwrite/api_client.go#L471-L526) when the v2 SDK added support for endpoint discovery.
