### ISSUE TITLE
route53: ResourceRecord's Value is a single string

### ISSUE THREAD

**Issue by amwolff-samsung** [aws/aws-sdk-go-v2#567]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I'm wondering whether `route53.ResourceRecord`'s `Value` shouldn't be a slice of strings (instead of a single string). From my research it looks like it should be. At least that's what I'm able to draw from the docs: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html

As one can see, Route53's API could return a response where value is listed multiple times (under one Resource Record).

**Version of AWS SDK for Go?**
`master`

**Version of Go (`go version`)?**
1.14.3

**To Reproduce (observed behavior)**
n/a

**Expected behavior**
`route53.ResourceRecord.Value` should be of `[]string` type.

cc @r-grodzki

**Comment by jasdel** [comment]
Thanks for reporting this issue @amwolff-samsung. This is potentially an issue with how the Amazon Route53 service models the `ResourceRecord.Value` member. The model for this member defines it as just a string. The best way to get additional details, and potentially raise the issue with the Route53 service directly is via their [AWS forms](https://forums.aws.amazon.com/forum.jspa?forumID=87).  Making a post on their describing the issue and the unexpected behavior would help investigate if the service's API could be updated or documentation improved.

**Comment by r-grodzki** [comment]
Thanks for clarifying! We've confirmed this to be an issue caused by somewhat misleading examples in the documentation ([as linked in the original comment](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html)), the SDK works as intended.
