### ISSUE TITLE
s3/manager:  Provide a mechanism to track upload progress (for real!)

### ISSUE THREAD

**Issue by oakad** [aws/aws-sdk-go-v2#571]
A similar issue was opened in the past (like 2016 past :-) against v1 version of this API, but never properly addressed.

Consider a situation, whereupon a device wants to upload a rather small amount of data (size not known in advance, but not exceeding few megabytes) over a slow network. We can use `s3manager.Uploader` for this, which handily accepts unbounded `io.Reader` as its "body" type.

The "customary" method of measuring progress on the read side will not be helpful outright: the `Uploader` will simply read the entirety of data into the "part" buffer and then will spend some long time writing this data onto the network, keeping the user in the dark regarding its progress.

It so happens, that in the "field device"/IOT world there is no alternative to directly measuring "network send" performance.

Also, python API does it properly: https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/s3/transfer.html

**Comment by goku321** [comment]
Can I try implementing this?

**Comment by harrison-seow-seagate** [comment]
Similar to [issue 941](https://github.com/aws/aws-sdk-go-v2/issues/941), please implement this feature.

**Comment by goku321** [comment]
I'll start on this soon!
