### ISSUE TITLE
ExampleWithSharedConfigProfile fails when AWS_DEFAULT_REGION is set

### ISSUE THREAD

**Issue by tlehn** [aws/aws-sdk-go-v2#572]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-go/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go/issues) and didn't find any solution
  
**Describe the bug**
Running _make unit_ fails when AWS_DEFAULT_REGION is set to something other than us-west-2 in the user's shell.

```text
--- FAIL: ExampleWithSharedConfigProfile (0.00s)
got:
Region: my-custom-region
want:
Region: us-west-2
FAIL
FAIL	github.com/aws/aws-sdk-go-v2/aws/external	0.820s
```

**Version of AWS SDK for Go?**
HEAD: 40a22fcb842831dd1511cc4a79f9fdc3c308e407

**Version of Go (`go version`)?**
go version go1.14.3 darwin/amd64

**To Reproduce (observed behavior)**
```bash
export AWS_DEFAULT_REGION=my-custom-region && make unit
```

**Expected behavior**
All unit tests and examples compile and pass regardless of the user's environment

**Comment by tlehn** [comment]
Same issue for the _unit-with-race-cover_ target as well

**Comment by tlehn** [comment]
The following change is a possible fix for the issue.
unit: verify build
	@echo "go test SDK and vendor packages"
	AWS_REGION="" AWS_DEFAULT_REGION="" go test -tags ${UNIT_TEST_TAGS} ${SDK_ALL_PKGS}

**Comment by jasdel** [comment]
Thanks for reporting this issue @tlehn. You're correct the SDK's makefile can be updated to squash the relevant environment variables before running unit tests. I think this will resolve issues with attempting to run the SDK's unit tests in environments where AWS_DEFAULT_REGION is set.
