### ISSUE TITLE
Custom Credential Caching Implementations

### ISSUE THREAD

**Issue by danieldooley** [aws/aws-sdk-go-v2#576]
**Is your feature request related to a problem? Please describe.**
With a project I'm working on we're foreseeing an issue with the way `credentials.Credentials` refreshes its cached `Value`. What we're implementing is performance sensitive and blocking requests during the refresh results in extra latency we'd like to avoid.

**Describe the solution you'd like**
Some way to implement our own `Credentials` so that we can do asynchronous refreshing. Currently we're limited because this isn't an Interface.

It'd also be convenient if we could hook the custom `Credentials` into session creation so we can make use of the automatic `session.resolveCredentials` behaviour so we don't have to manually specify the `Provider` we want to use. (This might be a seperate issue related to surfacing that logic, or I might be missing an obvious solution).

**Describe alternatives you've considered**
We're experimenting with a custom `credentials.Provider` that performs asynchronous refreshing, but this feels like an abuse of the intended behaviour considering there is a `Credentials` parenting the `Provider` doing caching as well.

**Additional context**
I'm happy to have a crack at contributing something to solve this but thought I'd reach out for communal brainstorming on the best way to achieve it first.

**Comment by danieldooley** [comment]
Thanks for clarifying that @diehlaws - I'm planning to get to this soon and begin to understand the credentials package here so I can brainstorm some solutions.

**Comment by jasdel** [comment]
The v2 SDK v0.25.0 update significantly refactored the SDK's [CredentialsProvider](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/#CredentialsProvider) and [config](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config)  module.

if you're still having issues with please let us know.

**Comment by danieldooley** [comment]
@jasdel - apologies; I only just got around to looking into this.

As I understand it `config.LoadDefaultConfig()` will attempt to resolve the credentials from the environment and will place them in a `aws.CredentialsCache`.

Based on what I can see, I would be able to implement our own Credential Caching using:
```go
        awsConfig, err := config.LoadDefaultConfig(aws_config_v2.WithRegion(cfg.AwsRegion))
	if err != nil {
		return nil, err
	}

	switch p := awsConfig.Credentials.(type) {
	case *aws.CredentialsCache:
		awsConfig.Credentials = NewCustomCredentialsCache(p.Provider)
	}

	dynamodb.NewFromConfig(awsV2Config)
```

Is it ok to extract the inner `CredentialProvider` from the `CredentialsCache`?
