### ISSUE TITLE
Static Credentials Issue

### ISSUE THREAD

**Issue by gkhnoisgtht** [aws/aws-sdk-go-v2#592]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**
I am attempting to use the Static Credentials, but continue to run into an error. I believe everything has been setup correctly. I am pulling credentials from Turbot and then using the resulting credentials as static credentials. Below is the code:

```
	config, err := external.LoadDefaultAWSConfig(
		// Hard coded credentials.
		external.WithCredentialsProvider{
			CredentialsProvider: aws.NewStaticCredentialsProvider(accessKeyID, secretAccessKey, ""),
		},
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load config, %v", err)
		os.Exit(1)
	}
	config.Region = *aws.String(os.Getenv("AWS_REGION"))
```

When I try to pass the resulting config into an sts.New(config) I get the following error:

```
InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id
```

If the code is run without the Turbot integration and just uses the regular `external.LoadDefaultAWSConfig()` then the code works as expected. Its only with the static credentials that I have an error.

**Comment by jasdel** [comment]
Thanks for reaching out @gkhnoisgtht. Do you have the same issue if your set the static credentials on the `config` value after the external config is loaded?

```go
config, err := external.LoadDefaultAWSConfig()
if err != nil { ... }

config.CredentialsProvider = aws.NewStaticCredentialsProvider(accessKeyID, secretAccessKey, "")
```

Also the setting of the AWS region can be simplified without the pointer via the following. The V2 SDK removed the need for pointers or aws.String to be used with the configuration fields.
```go
config.Region = os.Getenv("AWS_REGION")
```

**Comment by gkhnoisgtht** [comment]
@jasdel I attempted that setup by using this code:
```	
config.Credentials = aws.NewStaticCredentialsProvider(akid, secretAccessKey, "")
```
But I got the same 403 error. I attempted the `config.CredentialsProvider` just gives me an undefined error message.

**Comment by jasdel** [comment]
Thanks for the update @gkhnoisgtht This suggests that the static credentials may not be valid. Using the following example I'm able to use static credentials with STS's GetCallderIdentity operation using the method mentioned.

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/external"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)

var (
	accessKeyID     string
	secretAccessKey string
)

func init() {
	// TODO populate access keys
}

func main() {
	fmt.Println("vim-go")
	config, err := external.LoadDefaultAWSConfig()
	if err != nil {
		log.Fatalf("failed to load config, %v", err)
	}

	config.Credentials = aws.NewStaticCredentialsProvider(accessKeyID, secretAccessKey, "")

	client := sts.New(config)
	resp, err := client.GetCallerIdentityRequest(nil).Send(context.Background())
	fmt.Println(resp, err)

}
```
