### ISSUE TITLE
Improvements to SDK Logging and debug Facilities SDK middleware, API clients, and Config loading

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#594]
The Smithy based design changes to the SDK and the corresponding middleware design has highlighted the need to review our current approach to logging and log levels. Ideally each middleware should be able to produce sufficient logging at various levels of verbosity where necessary, and customers should be able to preferably target middleware by their identifiers to enable/disable and modify the verbosity of the logged statements. Most important is that we must not make assumptions about the underlying logging implementation provided, and allow users to plug into a minimal interface to satisfy with their own implementation or another community library.

**Comment by jasdel** [comment]
This issue should also ensure logging is captured by the SDK's `LoadDefaultClient` for credentials provider. 

https://github.com/aws/aws-sdk-go-v2/issues/355

**Comment by jasdel** [comment]
Thius issue was resolved with, https://github.com/aws/aws-sdk-go-v2/pull/872
