### ISSUE TITLE
service/s3: add ErrNotModified sentinel

### ISSUE THREAD

**Issue by carnott-snap** [aws/aws-sdk-go-v2#613]
> Migrated from aws/aws-sdk-go#3369:

**Is your feature request related to a problem? Please describe.**
When using s3.GetObject and s3.HeadObject's conditional parameters, `IfModifiedSince` and `IfNoneMatch`. It is non-trivial to check for a `304` status:
```go
if rf := awserr.RequestFailure(nil); errors.As(err, &rf) && rf.StatusCode() == 304 {
        // handle err
}
```

**Describe the solution you'd like**
With the advent of `errors.Is`, it would be nice to have a dedicated sentinel for this:
```go
if errors.Is(err, ErrNotModified) {
        // handle err
}
```
This could mean that err, as returned by `s3.GetObject`, could be an `s3.ErrNotModified`, but considering that we need to maintain compatibility, it seems imperative that we leave the type `awserr.RequestFailure`. As such, we can implement `interface{ Is(error) bool}`.

The simplest option is to have all `403`s be `ErrNotModified`, but then the symbol should probably live in `aws/request`:
```go
package awserr

func (r requestError) Is(target error) bool { return target == ErrNotModified && rf.StatusCode() == 304 }
```
```go
package request

var ErrNotModified = errors.New("Not Modified")
```

Unfortunately, this probably only applies to errors returned by `GetObject` and `HeadObject` in the `s3` package, so maybe a wrapper or more complex `Is` method are required?

**Describe alternatives you've considered**
See above:
- Have `s3.GetObject` and `s3.HeadObject` directly return `s3.ErrNotModified`.
- Have all `awserr.RequestFailure` with status `403` be `ErrNotModified`.

**Comment by jasdel** [comment]
This issue has been resolved with the SDK's v0.25.0 refactor which updated the SDK's error deserializaiton to wrap errors with metadata such as the HTTP request status.

See https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#error-handling for more information.
