### ISSUE TITLE
Does the SDK V2 could resolve #aws-sdk-go/3394

### ISSUE THREAD

**Issue by scorsi** [aws/aws-sdk-go-v2#624]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**
I'm asking if the SDK V2 could resolve that issue : https://github.com/aws/aws-sdk-go/issues/3394
Or if even it happens with it.

Thanks

**Comment by jasdel** [comment]
Thanks for reaching out. The issue, https://github.com/aws/aws-sdk-go-v2/issues/411 covers this feature request, and will be investigated when the SDK implements the DynamoDB attribute marshaler utilities.
