### ISSUE TITLE
Support for filering secrets from Secrets Manager

### ISSUE THREAD

**Issue by jay-dee7** [aws/aws-sdk-go-v2#639]
**Description**
aws-sdk-go v1 has a `ListSecrets` method, which supports an optional parameter Filter, a key value pair that i can use to filter my objects. It would be great to filter my secrets based on tags, secret keys, etc

**Solution**
While calling the ListSecretRequest method, i should have the option to provide an optional Filter object, using which i should only receive a subset of the secrets from aws secrets manager

**Alternative**
We can fetch all the secrets and then filter them but it has it's own security complications (like a developer should only fetch dev environment credentials, etc)

**Comment by jasdel** [comment]
Thanks for reaching out with this feature request. This issue would need to be a feature provided by the AWS Secrets Manager API directly. The SDK is based on the models provided by the service. The best way to reach out about this to the service is via the service's [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=296)
