### ISSUE TITLE
Go 1.15:  conversion from int to string yields a string of one rune

### ISSUE THREAD

**Issue by eclipseo** [aws/aws-sdk-go-v2#655]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [ x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
Go vet fails with:
```
github.com/aws/aws-sdk-go-v2/aws/signer/v2
# github.com/aws/aws-sdk-go-v2/aws/signer/v2
./v2_test.go:34:36: conversion from int to string yields a string of one rune
FAIL	github.com/aws/aws-sdk-go-v2/aws/signer/v2 [build failed]
error: Bad exit status from /var/tmp/rpm-tmp.igyBMC (%check)
```

**Version of AWS SDK for Go?**
0.24.0

**Version of Go (`go version`)?**
Go 1.15 beta 1

**To Reproduce (observed behavior)**
Run go test with vet enabled

**Expected behavior**
Test passes

**Additional context**
See https://github.com/golang/go/issues/32479

**Comment by venturaville** [comment]
This is related to a change in go 1.15 specifically: https://golang.org/doc/go1.15#vet
