### ISSUE TITLE
[dynamoDB] Acquire Cancellation Reasons from a TransactionCanceledException

### ISSUE THREAD

**Issue by dallbee** [aws/aws-sdk-go-v2#663]
**Version Information**
SDK: v0.23.1-0.20200714212036-c1ad81608c5c
Go: 1.14

**Is your feature request related to a problem? Please describe.**
It is difficult to disambiguate Transaction cancellation reasons. There's a [similar issue](https://github.com/aws/aws-sdk-go/issues/2318) in the AWS SDK v1, which appears to have been fixed in the [v1.28 release](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.0) but not mirrored to v2.

**Describe the solution you'd like**
I'd like to be able to unwrap the error from a transaction request to obtain the underlying reason for failure per-item in the transaction. It'd be great if there were a strongly typed approach to this.

I think the solution in the V1 SDK makes sense, so I'm really just hoping for a port of that functionality.

**Describe alternatives you've considered**
The [JS SDK has a similar issue](https://github.com/aws/aws-sdk-js/issues/2464). The current suggestion there is to use string parsing, which is what we're currently doing in our project to handle this.

**Comment by jasdel** [comment]
The latest version (+ v0.25.0) of the v2 preview SDK now generates typed errors for all APIs. This includes the DynamoDB's Cancellation reasons in TransactionCanceledException error response.

**Comment by proxy-hatch** [comment]
any example for this?
