### ISSUE TITLE
Client packages should not expose stack middleware helpers

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#696]
The AWS generated Smithy clients should not expose middleware helpers that are used for adding middleware to an operations Smithy stack.

Middleware helpers to be unexported:
* AddResolveEndpointMiddleware

**Comment by jasdel** [comment]
This issue has been resolved, and the SDK codegen no longer exposes the exported, AddResolveEndpointMiddleware
