### ISSUE TITLE
Middleware should be inittalizable by composite literals or constructors with explicit arguments.

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#697]
Middleware within the core SDK and generated clients should only follow one of the following patterns:
* Composite Literal Initialization
```
package foo

// SomeMiddleware is a type in package foo
type SomeMiddleware struct {
  SomeConfig bool
}
...
package client

func addSomeMiddleware(stack *middleware.Stack) {
  stack.Build.Add(foo.SomeMiddleware{SomeConfig: true}, middleware.After)
}
```
* Constructor function(s)
```
package foo

// SomeMiddleware is a type in package foo
type SomeMiddleware struct {
  SomeConfig bool
  privateDetail int
}

func NewSomeMiddleware(intValue int, fnArgs ...func(m *SomeMiddleware)) *SomeMiddleware {
  m := &SomeMiddleware{privateDetail: intValue}
  for _, f := range fnArgs {
    f(m)
  }
  return m
}
...
package client

// Options is the Client options type
type Options struct {
  MagicNumber int
}

func addSomeMiddleware(stack *middleware.Stack, o *Options) {
  stack.Build.Add(foo.NewSomeMiddleware(o.MagicNumber), middleware.After)
}
```

Clients that need to pass configuration from `Options` into the middleware must provide their own unexported helpers that will construct the middleware with the relevant properties.

Middleware **MUST NOT** expose interfaces that use property "Getters", as these are fragile constructs that breakdown when attempting to define "Getter" methods that return interface types. This is problematic when defining interfaces types within the Client, but are meant to satisfy an external interface. https://github.com/awslabs/smithy-go/issues/154 tracks removing these getter methods.

**Comment by jasdel** [comment]
This issue has been resolved. The SDK no longer uses an options interface for each middleware, and instead uses generated helper functions.
