### ISSUE TITLE
Should 429's be retried, after updating they produce SerializationError instead

### ISSUE THREAD

**Issue by laverboy** [aws/aws-sdk-go-v2#704]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
We have recently upgraded to using v0.24 from v0.19 and have seen new errors in the form of SerializationError status code 429 (see below). It is our understanding that these should trigger retries but instead they are erroring our Lambdas. Is this something that has changed with the refactor of the Retry handling?

```json
{
    "err": "SerializationError: 429 \n\tstatus code: 429, request id: ",
    "event": "cec.engine-switchboard.engine-new-task-announcer.process-record.failure",
    "jobId": "a076edfd-38ab-4f3d-8209-e21074982597",
    "level": "error",
    "msg": "breaking error occurred whilst processing dynamodb record",
    "time": "2020-09-03T10:24:22.354666697Z",
    "trace": "main.go:61"
}
```

**Version of AWS SDK for Go?**
v0.24.0

**Version of Go (`go version`)?**
1.14

**To Reproduce (observed behavior)**
Setup a lambda to heavily read from dynamo. 

**Expected behavior**
We expect the sdk to handle retries of a 429

**Comment by jasdel** [comment]
The v2 SDK retryer does not consider `429` as a retryable error. But depending on what serialization error the SDK received it is possible that the error should of been retried. For example a serialization error that was caused due to an unexpected connection reset, should of triggered a retry. Do you have any further details the rest of the `err` value? The SDK may include multiple lines of message within the `Error()` string

**Comment by laverboy** [comment]
Unforunately I can't get hold of the error, however we put a fix in place by adding 429's to the list of codes to retry, like it is in the v1 code and the errors have gone away.

Is there a reason why the sdk has changed to no longer class 429's as retryable? Is it because 429 covers both retryable and non-retryable situations?

**Comment by laverboy** [comment]
This was the code if you are interested

```go
awsConfig.Retryer = retry.NewStandard(func(options *retry.StandardOptions) {
		var codes = map[int]struct{}{
			429: {},
			500: {},
			502: {},
			503: {},
			504: {},
		}

		i := []retry.IsErrorRetryable{
			retry.NoRetryCanceledError{},
			retry.RetryableError{},
			retry.RetryableConnectionError{},
			retry.RetryableHTTPStatusCode{
				Codes: codes,
			},
			retry.RetryableErrorCode{
				Codes: retry.DefaultRetryableErrorCodes,
			},
		}
		options.Retryables = i
	})
```

**Comment by jasdel** [comment]
Thanks for the update. Are you still experiencing this issue with the updated v2 SDK to at least v0.25.0?  The SDK significantly refactored the way requests as made, and how they are retried after that update, and may improve the issue that you are seeing.
