### ISSUE TITLE
AWS SSO Credentials support

### ISSUE THREAD

**Issue by TheDanBlanco** [aws/aws-sdk-go-v2#705]
**Is your feature request related to a problem? Please describe.**
The `external.LoadDefaultAWSConfig()` call does not correctly load AWS SSO temporary credentials. Often what needs to happen is an external program needs to inject the credentials for the go v2 sdk to correctly function (`aws2-wrap [some-command-that-calls-the-go-v2-sdk]`)

**Describe the solution you'd like**
calling `external.LoadDefaultAWSConfig()` should consume AWS SSO credentials to make calls

**Describe alternatives you've considered**
`aws2-wrap` often solves this problem, but it becomes a burden to expect users of a cli using the go v2 sdk to have to wrap commands every time.

**Comment by andreacavagna01** [comment]
I could suggest [Leapp](https://github.com/Noovolari/leapp).
The application generates only plain credentials with `Access keys` and `secret key `from AWS Single Sign-On Access token.
By doing so, your credentials are fully compatible with all the projects, including the SDK

**Comment by jasdel** [comment]
Thanks for requesting this feature. The v2 SDK now has SSO credential support. for more information checkout the [AWS Single Sign-On Credentials](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#aws-single-sign-on-credentials) guide.
