### ISSUE TITLE
error=EC2RoleRequestError: no EC2 instance role found when deployed in a lambda

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#715]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)

**Describe the question**

When I upgade to 0.20.0 and beyond, e.g. `go get github.com/aws/aws-sdk-go-v2@v0.20.0` my [code](https://github.com/kaihendry/s3post/blob/master/main.go#L152) `cfg, err := external.LoadDefaultAWSConfig(external.WithSharedConfigProfile("mine"))` breaks with `error=EC2RoleRequestError: no EC2 instance role found` when deployed as a lambda.

Any ideas why? My workaround is to downgrade to `go get github.com/aws/aws-sdk-go-v2@v0.19.0`.

I've stared at https://github.com/aws/aws-sdk-go-v2/releases/tag/v0.20.0 and I can't see why this is happening.

**Comment by jasdel** [comment]
Thanks for reaching out with this issue @kaihendry are you still experiencing it with the latest version of the SDK (v0.29.0)? The SDK refactored its configuration loading in v0.25.0, which significantly improved how credentials are loaded.
