### ISSUE TITLE
Presigned URLs broken because query params are re-sorted

### ISSUE THREAD

**Issue by Naatan** [aws/aws-sdk-go-v2#719]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

When using `aws.ResolveWithEndpointURL()` the eventual URL used to create the request has the query parameters in a different order than was given. The offending line is here:

https://github.com/aws/aws-sdk-go-v2/blob/master/private/protocol/rest/encode.go#L55

This breaks pre-signed S3 URLs because the signature covers the order of the parameters.

A workaround can be seen here:

https://github.com/ActiveState/cli/blob/82999e3ab19a5066af837f00b83f245bad97b97a/internal/download/get.go#L83

**Version of AWS SDK for Go?**
0.24.0

**Version of Go (`go version`)?**

1.14.4

**To Reproduce (observed behavior)**

Feel free to create a test case out of https://github.com/ActiveState/cli/blob/82999e3ab19a5066af837f00b83f245bad97b97a/internal/download/get.go#L26

**Expected behavior**

Pre-signed URLs don't break

**Additional context**

This is an issue on v1 also, but v1 doesn't have the tools to get it right as there's no way to supply the query parameters in a valid order. v2 should be able to do this however.

For a v1 workaround see https://github.com/ActiveState/cli/blob/s3v1-174721786/internal/download/get.go#L70

**Comment by jasdel** [comment]
Thanks for reporting this issue @Naatan, the v2 SDK has removed presign URL behavior starting with v0.25.0 release. We plan to add this feature back into the SDK. The v0.25.0 uses a radically different method of serializing the request that may not be susceptible to this issue, but it would be good to keep this issue open to ensure the bug is not present in the v2 SDK once presign URL feature is added back in.

**Comment by jasdel** [comment]
Closing this issue in favor of #891 which tracks the SDK's implementation of presigned URL support for API operations.

The v2 SDK's implementation of presigned URLs will be significant different from the < v0.24.0 and v1 SDK. With presign behavior targeted to specific operations, and not generic. 

Lets use #891 to discuss this issue further.
