### ISSUE TITLE
stscreds does not provide way to specify session and transitive tags

### ISSUE THREAD

**Issue by excavador** [aws/aws-sdk-go-v2#723]
**Is your feature request related to a problem? Please describe.**

I need ability to specify session and transitive tags as options to `stscreds.NewAssumeRoleProvider`

**Describe the solution you'd like**

Struct `stscreds.AssumeRoleProviderOptions` should be extended by session and transitive tags fields
https://docs.aws.amazon.com/sdk-for-go/v2/api/aws/stscreds/#AssumeRoleProviderOptions

method `retrieveFn` should use these options to configure `sts.AssumeRoleInput`

**Comment by jasdel** [comment]
The SDK's configuration loading has been updated to improve support for passing in additional options when loading the configuration via `config.LoadDefaultConfig` vai, [WithAssumeRoleCredentialOptions](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config/#WithAssumeRoleCredentialOptions).

Though this does not provide access to options such as tagging and other AssumeRoleInput parameters.

**Comment by excavador** [comment]
@jasdel it's ok as well. We need these options somewhere. We can not migrate to AWS SDK GO v2 according to lack of these options

**Comment by excavador** [comment]
Any updates?

**Comment by jasdel** [comment]
Thanks for creating this issue @excavador PR #1375 was created adding this feature. The change will be merged in and included in the SDK's next release.

**Comment by excavador** [comment]
@jasdel thank you!
