### ISSUE TITLE
Request sendalexaoffertomaster interface using URL

### ISSUE THREAD

**Issue by pai-da-xin** [aws/aws-sdk-go-v2#728]
Hello,Sir,
* I would like to ask, can I use the URL request sendalexaoffertomaster interface?What host does it request.
Thanks.

**Comment by jasdel** [comment]
Thanks for reaching out @pai-da-xin could you provide more information about the issue that you're running into?

The SDK can be configured with a custom endpoint for each API client via the `EndpointResolver` option, or when loading the SDK's shared configuration.

**Comment by pai-da-xin** [comment]
Thank you, Sir, I have no problem.
