### ISSUE TITLE
Add context.Context to aws.Logger API

### ISSUE THREAD

**Issue by fsenart** [aws/aws-sdk-go-v2#729]
To not duplicate and scatter discussions around, I'm cross-posting this feature request initially introduced in https://github.com/aws/aws-sdk-go/issues/3398. 

_Let me know if there is any need to import details here._

**Comment by jasdel** [comment]
Thanks for letting us know about this feature request. The SDK update https://github.com/aws/aws-sdk-go-v2/pull/872 added support for a logger with context in the SDK.
