### ISSUE TITLE
Special error NoSuchTagSetError stated in docs but not defined anywhere

### ISSUE THREAD

**Issue by joaoferrao** [aws/aws-sdk-go-v2#740]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

master

### Version of Go (`go version`)?

Not relevant for the issue

### What issue did you see?

API call on S3 service from `service/s3/api_op_GetBucketTagging.go` states a special error `NoSuchTagSetError`. This error is nowhere to be found within aws-sdk-go-v2 so it cannot be asserted.

### Steps to reproduce

If you have have an runnable example, please include it.

**Comment by jasdel** [comment]
Thanks for reporting this issue. It looks like the `NotSuchTagSetError` is [documented](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketTagging.html), but not modeled by the Amazon S3 API.  The SDK is only aware of errors that are modeled for the services.

With version v0.25.0 and higher of the SDK, this error can be asserted by checking for the error code `NotSuchTagSetError`.

```go
result, err := client.GetBucketTagging(context.TODO(), params)
if err != nil {
     var apiErr smithy.APIError
     if errors.As(err, &apiErr) {
           switch apiErr.ErrorCode() {
                case "NotSuchTagSetError":
                     // handling of NotSuchTagSetError.

                // .. other error codes
           }
     }
     return err
}
```
