### ISSUE TITLE
Developer Guide: Migrating from v1 to v2 SDK with example

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#75]
It would be helpful to create usage examples for an application using v1 explaining how to migrate to specific changes in v2.

**Comment by Skarlso** [comment]
That indeed would be helpful. I had to search the code and look how I can mock the response to return an error. Although, to be honest, it wasn't rocket science. More like, I was able to delete some code. To be honest, the test changes were more than the actual code. :)

**Comment by kaihendry** [comment]
Doesn't @Doug-AWS maintain a v1 and v2 of examples somewhere? I'll try find some time to contribute given the platform to do so. 

Is this one? https://github.com/aws/aws-sdk-go/tree/master/example & the examples_ files? https://github.com/aws/aws-sdk-go-v2/tree/master/service/dynamodb/expression

**Comment by Skarlso** [comment]
For what it's worth, I have a PR with the changes which were needed to switch to v2. https://github.com/Skarlso/go-furnace/pull/19

**Comment by Doug-AWS** [comment]
We will have a migration guide with specific code examples. Not before release however.

**Comment by skmcgrail** [comment]
The migration guide content for the AWS SDK for Go V2 can be found at https://aws.github.io/aws-sdk-go-v2/docs/migrating/
