### ISSUE TITLE
aws/to_ptr  same address?

### ISSUE THREAD

**Issue by hacker65536** [aws/aws-sdk-go-v2#777]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
This code gives only one result.
```go
package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
)

func main() {

	cfg, err := config.LoadDefaultConfig()
	if err != nil {
		panic("unable to load SDK config, " + err.Error())
	}

	svc := ec2.NewFromConfig(cfg)

	ids := []string{
		"i-0a70c779ab9ea03b3",
		"i-06dde7896483e8f86",
	}

	params := &ec2.DescribeInstancesInput{
		InstanceIds: aws.StringSlice(ids),
	}
	resp, err := svc.DescribeInstances(context.Background(), params)
	if err != nil {
		panic("failed to describe instances, " + err.Error())
	}

	r, _ := json.Marshal(resp.Reservations)
	fmt.Println(string(r))
}
```

Is this correct?
https://github.com/aws/aws-sdk-go-v2/blob/4a1d0a5a322eda3296ed32a9fa7b811db5f6c684/aws/to_ptr.go#L66-L75

**Version of AWS SDK for Go?**
v0.25.0

**Version of Go (`go version`)?**
 go1.15.2 linux/amd64

**To Reproduce (observed behavior)**

https://play.golang.org/p/3P1K30uzW-W

**Expected behavior**

https://play.golang.org/p/FdZT_wMM0iR

**Additional context**

**Comment by skmcgrail** [comment]
Thanks for the report @hacker65536  this has been addressed and included in yesterdays [v0.26.0](https://github.com/aws/aws-sdk-go-v2/releases/tag/v0.26.0) release.
