### ISSUE TITLE
SDK V2 vs V1 Guidance for S3

### ISSUE THREAD

**Issue by shawnHartsell** [aws/aws-sdk-go-v2#780]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

Apologies if this has been covered, but I couldn't quite find the answers I was looking for in SO or the AWS forums. My team is working on migrating some of our services from https://github.com/minio/minio-go to the AWS SDK for S3 operations. I am assuming that we should start with V1 for stability reasons. However I had the following questions:

- In terms of bug fixes and performance improvements made in this version, are they back ported to V1?
- In terms of milestones, is there a timeline where V2 will be suitable for production use?
- Are there particular S3 operations that are better suited to use in V2 rather than V1? I'm particularly interested in use cases around streaming GET and PUT operations to clients (e.g. proxying API requests).

Thanks! 😊

**Comment by jasdel** [comment]
Hi @shawnHartsell thanks for reaching out, and wanted to let you know the v2 SDK is now GA and is ready for production. It supports the Amazon S3 API, along with an S3 transfer manager similar to the v1 SDK.

In general the SDK operations will logically be the same between v1 and v2. V2 Will have better experiences, less overhead, and more flexibility with how you use the API client and its operation calls.

**Comment by shawnHartsell** [comment]
Thanks for the response. Since opening this issue, we saw that V2 is now GA and look forward to migrating over to it. That being said, what is the status of v1? Is there an official EOL date or will bug fixes/improvements continue be continued to be made to it?

**Comment by jasdel** [comment]
The v1 SDK is still fully supported, and is not deprecated or EOF yet. Though v2 SDK is future direction of the SDK. When the v1 SDK is deprecated we'll announce an EOF plan with timing of the deprecation.
