### ISSUE TITLE
What is the suggested replacement for s3manager, including Uploader & Downloader in 0.25.0

### ISSUE THREAD

**Issue by zubinmadon** [aws/aws-sdk-go-v2#783]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

What is the suggested replacement for s3manager, including Uploader & Downloader in 0.25.0?

I see that the new 0.25.0 release no longer provides an `s3manager` package, including the `Uploader` and `Downloader` types.

- What are the suggested updates for code that relied on these? 
- Will this be reintroduced in a future release?

Thanks!

**Comment by oakad** [comment]
s3manager is a pretty popular thing, we use it a lot. For bucket region autodetection, beside other things.
