### ISSUE TITLE
Cannot find certain resources/links - Please help!

### ISSUE THREAD

**Issue by rkotangoor** [aws/aws-sdk-go-v2#784]
I am seeing these references are no longer working, please suggest the correct paths:

https://github.com/aws/aws-sdk-go-v2/aws/external
https://github.com/aws/aws-sdk-go-v2/aws/stscreds
https://github.com/aws/aws-sdk-go-v2/service/sts

**Comment by tjengland** [comment]
Same issue ^

The files have been moved / renamed to:
```
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials/stscreds"
	"github.com/aws/aws-sdk-go-v2/service/sts"
```

`GetCallerIdentityRequest` has been completely removed so I am wondering what the suggested flow is to replace this method if we need access to the request data (eg headers) itself instead of the result. Here is my use case: https://www.vaultproject.io/api-docs/auth/aws#iam_request_headers

**Comment by skmcgrail** [comment]
Thanks for reaching out @rkotangoor,

> I am seeing these references are no longer working, please suggest the correct paths:
>
> https://github.com/aws/aws-sdk-go-v2/aws/external

This is now moved to a separate module located at [github.com/aws/aws-sdk-go-v2/config](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config)

> https://github.com/aws/aws-sdk-go-v2/aws/stscreds

This can be found in the [credentials module](https://pkg.go.dev/mod/github.com/aws/aws-sdk-go-v2/credentials) at [/github.com/aws/aws-sdk-go-v2/credentials/stscreds](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds)

> https://github.com/aws/aws-sdk-go-v2/service/sts

All service clients have been moved into separate modules. The STS client module is located at [github.com/aws/aws-sdk-go-v2/service/sts](https://pkg.go.dev/mod/github.com/aws/aws-sdk-go-v2/service/sts)

@tjengland the operation invocation calling pattern has been simplified such that there are no longer `*Request` methods that then require a secondary `Send(context.Background())` invoke operation. Please see the [GetCallerIdentity](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sts#Client.GetCallerIdentity) documentation.

**Comment by rkotangoor** [comment]
Thank you so much @skmcgrail! I will review these new paths and will let here know if I see any issues.
