### ISSUE TITLE
Unit testing Error scenarios with `Send`

### ISSUE THREAD

**Issue by Skarlso** [aws/aws-sdk-go-v2#79]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

v2

### Version of Go (`go version`)?

1.9

### What issue did you see?

Hi. So I have a test like this: 

```go
func (fc *fakeCreateCFClient) DescribeStacksRequest(input *cloudformation.DescribeStacksInput) cloudformation.DescribeStacksRequest {
	if fc.stackname == "NotEmptyStack" || fc.stackname == "DescribeStackFailed" {
		return cloudformation.DescribeStacksRequest{
			Request: &aws.Request{
				Data:  &NotEmptyStack,
				Error: fc.err,
			},
		}
	}
	return cloudformation.DescribeStacksRequest{
		Request: &aws.Request{
			Data: &cloudformation.DescribeStacksOutput{},
		},
	}
}
```

I was expecting it to fail with a given error in the fake client which was working perfectly fine with v1 since that particular method was returning an error. Now, I don't have a perfect way to mock `Send` so I guessed, that maybe a request error like the above is the way to make errors propagate through to `Send`. Alas, that's not the case. 

Thus, my question is, how do I make error scenarios happen?

Thanks,
Gergely.

**Comment by Skarlso** [comment]
Never mind. It actually works like that. It was an error in my test case that let it fall through instead of failing.

Nice job on the API. Got more consistant with the use of gRPC.

**Comment by jasdel** [comment]
Thanks for the update @Skarlso, glad you were able to find how to integrate test your application with the v2 SDK.  In #80 we're looking at refactoring how the V2 SDK's Request type is structured. Any additional feedback you have on your experience mocking out the SDK would be helpful.

**Comment by Skarlso** [comment]
Thanks @jasdel! I'll check out that issue and leave my feedback. I had a nice time updating [furnace](https://github.com/Skarlso/go-furnace) to use v2. I was successful in mocking out the api and simulating communication. 

I'll make sure I have some constructive advice if I can. :-)
