### ISSUE TITLE
Missing replacement for dynamodb.MarshalMap and dynamodb.UnmarshalMap

### ISSUE THREAD

**Issue by ianchildress** [aws/aws-sdk-go-v2#790]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

The documentation didn't update with the v0.25.0 release when dynamodb.MarshalMap disappeared. There isn't an obvious replacement now that AttributeValue has moved from dynamodb to the types package.

**Comment by skmcgrail** [comment]
Thanks for reaching out @ianchildress we will be reintroducing support for the `dynamodbattribute` package for marshaling and unmarshaling in a later release. We are finalizing some details around the API model and the resulting client generation which will potentially change how these types are interacted with. As soon as that is complete we will be porting this feature back into the SDK.

**Comment by ianchildress** [comment]
Thank you for the reply @skmcgrail . What should we do in the meantime? It seems our option is either we don't use this version or we need to write our own Marshaller? 

With respect, I don't understand what the developer is expected to do with this release when basic functionality is unavailable. The heavy the lifting being passed to the developer. This is incredibly frustrating and has already taken a great deal of our time trying to find a solution.

**Comment by catpaladin** [comment]
> Thanks for reaching out @ianchildress, we will be reintroducing support for the `dynamodbattribute` package for marshaling and unmarshaling in a later release. We are still finalizing some details around the API model and the resulting client generation for the AttributeValue type, which would change how these types are interacted with. As soon as that is complete we will be porting this feature back into the SDK.

Would the port be backwards compatible with v0.24.0 and earlier?

In the meanwhile, are there any examples/resources on usage without previously mentioned MarshalMap and UnmarshalMap?

**Comment by jasdel** [comment]
Thanks for reaching out and voicing your support for the DynamoDB AttributeValue marshaler utilities.  I've created https://github.com/aws/aws-sdk-go-v2/issues/895 to track this feature being added back to the v2 SDK, along with associated features that need to be closed out.  Lets use that issue for tracking this feature.

**Comment by qfornaguera** [comment]
Just in case someone ends up here in the same coil of desperation...

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue#hdr-AttributeValue_Marshaling

```
import "github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
```

**Comment by frioux** [comment]
@qfornaguera thank you!

**Comment by IvanChernoborodov** [comment]
@qfornaguera Thanks a lot!!!!

**Comment by vishwanathsukumardh** [comment]
Thanks for the reference.
