### ISSUE TITLE
How to presign S3 upload URLs in v0.26.0

### ISSUE THREAD

**Issue by asterikx** [aws/aws-sdk-go-v2#794]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

**Describe the question**

How to create presigned URLs ([v1 docs](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-presigned-urls.html)) in v0.26.0? I cannot find any helpful references. Thanks.

**Comment by shvc** [comment]
per https://github.com/aws/aws-sdk-go-v2/issues/719

The v2 SDK has removed presign URL behavior starting with v0.25.0 release

**Comment by jasdel** [comment]
Closing this issue in favor of https://github.com/aws/aws-sdk-go-v2/issues/891 which tracks the SDK's implementation of presigned URL support for API operations.
