### ISSUE TITLE
S3: DeleteObjects: Missing required header for this request: Content-MD5

### ISSUE THREAD

**Issue by pwmcintyre** [aws/aws-sdk-go-v2#795]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
when using `s3.DeleteObjects(ctx, &request)` i get the following error:
```
operation error S3: DeleteObjects, api error InvalidRequest: Missing required header for this request: Content-MD5
```

related sdk v1 issue: https://github.com/aws/aws-sdk-go/issues/154

**Version of AWS SDK for Go?**

from go.mod:
```
	github.com/aws/aws-sdk-go-v2 v0.26.0
	github.com/aws/aws-sdk-go-v2/config v0.1.1
	github.com/aws/aws-sdk-go-v2/service/s3 v0.26.0
```

from `aws.SDKVersion`: 0.25.0

**Version of Go (`go version`)?**
1.14

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```Golang
package main

import (
	"context"
	"log"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
)

const BucketName = "example"

func main() {

	ctx := context.Background()

	// get AWS session
	cfg, err := config.LoadDefaultConfig()
	if err != nil {
		log.Fatalf("failed to get AWS session: %v", err)
	}

	// get clients
	client := s3.NewFromConfig(cfg)

	// begin
	if err := EmptyBucket(ctx, client, BucketName); err != nil {
		log.Fatalf("failed to empty bucket: %v", err)
	}

}

func EmptyBucket(ctx context.Context, client *s3.Client, bucket string) error {

	input := s3.ListObjectVersionsInput{
		Bucket:    &bucket,
		KeyMarker: nil,
	}

	// paginate
	for {

		// get page
		resp, err := client.ListObjectVersions(ctx, &input)
		if err != nil {
			return err
		}

		// set next page
		input.KeyMarker = resp.KeyMarker

		// convert "list objects response" to "delete objects request"
		request := s3.DeleteObjectsInput{
			Bucket: &bucket,
			Delete: &types.Delete{Objects: make([]*types.ObjectIdentifier, len(resp.Versions))},
		}
		for i, object := range resp.Versions {
			request.Delete.Objects[i] = &types.ObjectIdentifier{
				Key:       object.Key,
				VersionId: object.VersionId,
			}
		}

		// delete page
		_, err = client.DeleteObjects(ctx, &request)
		if err != nil {
			return err
		}

	}

	return nil

}
```

**Expected behavior**
No error

**Additional context**
None

**Comment by rossedman** [comment]
Same is happening to me, this header is also supposed to be deprecated the docs states.

**Comment by jasdel** [comment]
Thanks for reporting this issue. It has been fixed in https://github.com/aws/aws-sdk-go-v2/pull/812 and will be included in the SDK's next release.
