### ISSUE TITLE
service/s3: CreateBucket should populate the bucket LocationConstraint with the client region if not defined.

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#805]
V1 client had a customization so that CreateBucket requests that did not specify a bucket LocationConstraint would be auto-populated with the clients region value. This avoids users having to specify it, but this behavior is not consistent across other SDKs that require the user to populate this parameter.

**Comment by jasdel** [comment]
Example of AWS SDK for Java v2's customization, https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/CreateBucketInterceptor.java
