### ISSUE TITLE
Should the setters be kept in V2

### ISSUE THREAD

**Issue by xibz** [aws/aws-sdk-go-v2#81]
With V2, we are curious if people are using the setters in the service APIs. As this isn't too idiomatic to Go, we want to ensure that there is a benefit that people are getting other than just convinience. Should we keep setters in V2?

**Comment by harrisonhjones** [comment]
Are we talking about these kind of setters?

```
func (s *AddTagsToStreamInput) SetStreamName(v string) *AddTagsToStreamInput
```

**Comment by xibz** [comment]
@harrisonhjones - Yes, those are the setters in question

**Comment by itsjamie** [comment]
Removing the setters to make the API surface smaller if they are just doing an assignment to a public field is my vote.

A smaller API surface will make the documentation nicer to read and much of the cruft will be gone allowing you to focus on the important bits.

Thanks for asking!

**Comment by jasdel** [comment]
Thanks for the feedback. Correct these methods in question are only connivence methods to set API parameters without the need to use the `aws.String` or similar utilities. The additional noise these methods add to the docs is [quite significant](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/ec2#pkg-index). Given the size of the APIs for most services these additional methods can make it difficult to read the docs.

This is why we're interested in your feedback. If these utility methods don't provide any unique value or functionality, it may be a good idea to remove them from the v2 SDK.

**Comment by shawnsmithdev** [comment]
This seems to come down to two facts about Go:
* The Zero Value means one needs pointers and `nil` to represent the lack of a value (ex. in APIs, JSON parsing, etc). This is common and well understood in the larger Go community.
* [One cannot reference string literals or constants](https://play.golang.org/p/P2mb1gpkUT5)

Thus `aws.String()` and related util functions exist. Which are just:
```go
func String(value string) *string {
    return &string;
}
```

The idea behind these setters seems to be to let you avoid `aws.String()` and use your string literals or constants directly. But we pay quite a price in API surface area, and it encourages a code style that is not very idomatic Go (procedural mutation).

```go
// idiomatic
desc, err := client.DescribeStreamRequest(&kinesis.DescribeStreamInput{
        StreamName: aws.String(stream) // or &stream if stream is not a const or literal
}).Send()

// not idiomatic
var descStreamInput kinesis.DescribeStreamInput
descStreamInput.SetStreamName(stream)
desc, err := client.DescribeStreamRequest(&descStreamInput).Send()
```

The style thing comes down to personal preference, but IMHO even if you prefer the setter style, the resulting API ugliness is hard to justify.

**Comment by xibz** [comment]
We have decided to remove the setters based off the feedback here, see #101. Thank you all for providing us with your feedback in making the SDK better :).
