### ISSUE TITLE
package github.com/aws/aws-sdk-go-v2/aws/session: cannot find package "github.com/aws/aws-sdk-go-v2/aws/session"

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#83]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?

https://github.com/aws/aws-sdk-go-v2/commit/493e3ced184b77eff33393092e91fd3e1d0dbfd8

### Version of Go (`go version`)?
go version go1.9.2 linux/amd64

### What issue did you see?

```
main.go:13:2: cannot find package "github.com/aws/aws-sdk-go-v2/aws/session" in any of:
        /usr/lib/go/src/github.com/aws/aws-sdk-go-v2/aws/session (from $GOROOT)
        /home/hendry/go/src/github.com/aws/aws-sdk-go-v2/aws/session (from $GOPATH)
```

### Steps to reproduce

1. Copy the example from https://godoc.org/github.com/aws/aws-sdk-go-v2#hdr-Complete_SDK_Example

2. Paste it into a main.go somewhere inside $GOPATH/src

3. Run it

**Comment by Amitgb14** [comment]
session directory is missing in ```github.com/aws/aws-sdk-go-v2/aws/```

**Comment by Doug-AWS** [comment]
V2 does not use sessions. See the blog post https://aws.amazon.com/blogs/developer/category/go/. To see a typical use of the new style, see the DynamoDB example in https://github.com/aws/aws-sdk-go-v2.

**Comment by kaihendry** [comment]
Shouldn't https://godoc.org/github.com/aws/aws-sdk-go-v2#hdr-Complete_SDK_Example be fixed?

And any other example that uses sessions?

```
~/go/src/github.com/aws/aws-sdk-go-v2$ grep -r session . | wc -l
1188
```

**Comment by jasdel** [comment]
Thanks for pointing those out @kaihendry I've created #85 to address cleaning up the v2 SDK's examples.  As we move through the developer preview, and into the general availability we'll be adding more examples and documentation for the V2 SDK.
