### ISSUE TITLE
Trouble getting results back from the RDS Data API in a meaningful format

### ISSUE THREAD

**Issue by EwanValentine** [aws/aws-sdk-go-v2#834]
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

I'm attempting to use Aurora Serverless, as I'm dealing with a predominantly Lambda based stack, but we have an RDS instance/Postgres datastore. So I'm attempting to use the RDS Dataservice API. However, I can't seem to find any documentation or examples of how to marshal/process the results. There are no examples anywhere and it's not obvious from going through the code itself how to do this. 

The code I have for example:
```golang

func (r *AuroraRepository) generateStatement(query string) *rdsdata.ExecuteSqlInput {
	return &rdsdata.ExecuteSqlInput{
		Database:    aws.String(r.database),
		DbClusterOrInstanceArn: aws.String("<redacted>"),
		AwsSecretStoreArn:   aws.String("<redacted>"),
		SqlStatements:         aws.String(query),
	}
}


func (r *AuroraRepository) Create(ctx context.Context, venue, parent string, menu *models.Menu) (*models.Menu, error) {
	out, err := r.client.ExecuteSql(ctx, r.generateStatement("select * from menus"))
	if err != nil || out == nil {
		return nil, err
	}
	for _, v := range out.SqlStatementResults {
		for _, item := range v.ResultFrame.Records {
			??
		}
	}

	return nil, nil
}
```

I can drill down into the response and see that there's a Records map, Which contains a map of Values. Value being an interface. Am I missing something obvious? Do you have an example at all?

Thanks in advance, look forward to using Serverless Postgres!

**Comment by skmcgrail** [comment]
Hey @EwanValentine, I think is definitely something we could improve our documentation on, as it is very much unclear how to approach this data type with the default documentation.

Here is a small example of how you would type cast the `types.Value` type.
```go
for _, result := range output.SqlStatementResults {
	for _, record := range result.ResultFrame.Records {
		for _, value := range record.Values {
			switch v := value.(type) {
			case *types.ValueMemberArrayValues:
				_ = v.Value // []types.Value
			case *types.ValueMemberBigIntValue:
				_ = v.Value // int64
			case *types.ValueMemberBlobValue:
				_ = v.Value // []byte
			case *types.ValueMemberStringValue:
				_ = v.Value // string
			case *types.ValueMemberIsNull:
				_ = v.Value // bool
			}
		}
	}
}
```

The corresponding types compatible with [Value](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rdsdata@v0.27.0/types#Value) is the types prefixed as `ValueMember*`.

**Comment by EwanValentine** [comment]
Ahaaa, gotcha, I'll have a play around with this example. Thank you!

**Comment by EwanValentine** [comment]
Another quick one actually, I'm getting an error that ExecuteSql is deprecated and to use ExecuteStatement, but that returns something different entirely, am I way off the mark here? @skmcgrail appreciate your help!

**Comment by skmcgrail** [comment]
That deprecation notice comes from the RDS Data API Documentation similar to [here](https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteSql.html).

Looking at the API  outputyou would follow a similar pattern for the `ExecuteStatementOutput.Records` which is a `[][]type.Field`. [Field](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rdsdata@v0.27.0/types#Field) is also a Union interface that can be used like so:
```go
for _, record := range output.Records {
	for _, field := range record {
		switch v := field.(type) {
		case *types.FieldMemberStringValue:
			_ = v.Value // string
		case *types.FieldMemberBlobValue:
			_ = v.Value // []byte
			// fill in other FieldMember* types
		}
	}
}
```

**Comment by EwanValentine** [comment]
Ahhh gotcha, that makes sense, thanks again for your help, much appreciated!
