### ISSUE TITLE
Usage of Union types is unclear

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#835]
Due to limitations of the Go doc format, the usage of Union shapes is opaque without a clear example. For example `rds-data` model uses unions for `com.amazonaws.rdsdata#Value`. This interface should maybe have a code generated example on the type that shows a type assert of all the possible implementations. This will give users a proper example of how to use the type. Additionally we could explore generating the list of plugable shapes automatically as part of the documentation of the type itself.

Related #834

**Comment by jasdel** [comment]
Fixed in https://github.com/aws/aws-sdk-go-v2/pull/957
