### ISSUE TITLE
Inconsistent pagination

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#84]
### Version of AWS SDK for Go?

What's the command to determine this?
Else, going to assume https://github.com/aws/aws-sdk-go-v2/commit/493e3ced184b77eff33393092e91fd3e1d0dbfd8

### Version of Go (`go version`)?

go version go1.9.2 linux/amd64

### What issue did you see?

With medialive the way to test an empty token is `*next == ""`. on mediapackage it's `next == nil`. I'm puzzled why.

* https://godoc.org/github.com/aws/aws-sdk-go-v2/service/medialive#ListChannelsOutput
* https://godoc.org/github.com/aws/aws-sdk-go-v2/service/mediapackage#ListOriginEndpointsOutput

### Steps to reproduce

Compare

* https://s.natalian.org/2018-01-09/live.go
* https://s.natalian.org/2018-01-09/pkgs.go

Notice if live.go uses:

        if next == nil {
            break
        }

It just goes in an infinite loop.

**Comment by jasdel** [comment]
Thanks for pointing this issue out @kaihendry. This looks to be an inconsistency with the Elemental MediaLive and MediaPackage service. I don't think the MediaLive service should not be sending the `NextToken` field or sending it as JSON `null`.  I can forward this issue internally to the MediaLive service, but it would be helpful if you submit feedback to the service directly via their [API reference documentation](https://docs.aws.amazon.com/mediapackage/latest/apireference/channels.html). There is a [Feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=MediaPackage&topic_url=http://docs.aws.amazon.com/en_us/mediapackage/latest/apireference/channels.html&hidden_guide_name=API%20Reference&hidden_api_version=&hidden_file_name=channels) button in the bottom right corner of the page you can submit feedback directly to the service teams on an API.

**Comment by jasdel** [comment]
As a workaround the Service API issue you can use [aws.StringValue](https://godoc.org/github.com/aws/aws-sdk-go-v2/aws#StringValue) in both files and check against empty string to determine that the end of pagination has been reached.

This will also ensure your code is forward compatible if the MediaPackage service determine they are able to convert the empty string to a null value in the service response.  You can also use [ListChannelsPages](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/mediapackage#MediaPackage.ListChannelsPages) methods to perform the pagination automatically for you. 

The V2 SDK also has outstanding #36 to refactor how the v2 SDK will perform pagination.

**Comment by kaihendry** [comment]
Thanks, I struggled to find a regular "List*Pages" example. I ended up with something like:

    err = svc.ListInputsPages(&medialive.ListInputsInput{},
        func(page *medialive.ListInputsOutput, lastPage bool) bool {
            log.Println("Received", len(page.Inputs), "inputs in page")
            Inputs = append(Inputs, page.Inputs...)
            return lastPage
        })

Which worked. But I am not sure if `return lastPage` is right.

**Comment by jasdel** [comment]
That code should work, the `return lastPage` can be changed to just `return true`.   The `bool` return value of the pagination callback is to tell the SDK whether to continue paging or not. This is apart of the reason we want to refactor pagination in #36.

One of the design ideas we're considering for refactoring pagination to would be something similar to the following, using a similar pattern to the [bufio's scanner](https://godoc.org/bufio#Scanner).

```go
req := svc.ListInputsRequest(&medialive.ListInputsInput{})
pager := req.Paginate()

for pager.Next() {
    page := pager.Page()
    log.Println("Received", len(page.Inputs), "inputs in page")
    Inputs = append(Inputs, page.Inputs...)
}
if err := pager.Err(); err != nil {
   panic("paging failed, " + err.Error())
}
```

**Comment by kaihendry** [comment]
Thank you Jason. Sorry, little confused when you say I should write `return true` instead. I want it to stop paging when I have everything, and that should be when **lastPage** is true, no?

**Comment by jasdel** [comment]
@kaihendry returning "false" from the callback function will instruct the SDK's paginator to stop paginating. The callback function can return this on any page stating that your application no longer wants to continue to paginate the API. With that said, the SDK will also automatically stop paginating if it reaches the last page. The `lastPage` input parameter is there to let your application know that this will be the last page of the API's data.  Does that help clarify?

**Comment by kaihendry** [comment]
Hm... I'm still confused. Can you give me an example of code which gets all the data from every page? Trouble is, unless I am going crazy, I can't get a true from lastPage.

    err = svc.ListInputsPages(&medialive.ListInputsInput{},
        func(page *medialive.ListInputsOutput, lastPage bool) bool {
            log.Println("Received", len(page.Inputs), "inputs in page")
            Inputs = append(Inputs, page.Inputs...)
            log.Println(lastPage)
            return true
        })

**Comment by jasdel** [comment]
@kaihendry Here is an [example using S3](https://github.com/aws/aws-sdk-go-v2/blob/master/example/service/s3/listObjects/listObjects.go) list objects.

Is your callback function only being called once?  I'm curious if this issue is related to the testing failure found in #89.

Are you using Go's `dep` tool? If not could you try checking out `0b12d6b5` of github.com/jmespath/go-jmespath and see if that corrects the pagination issue.

```sh
cd $(go env GOPATH)/src/github.com/jmespath/go-jmespath
git checkout 0b12d6b5
```

**Comment by jasdel** [comment]
@kaihendry Also how many inputs do you expect to have? Any how many are being returned in the ListPages calls? Is it possible that all Inputs have been returned in a single callback?

**Comment by kaihendry** [comment]
Happy to use `dep`, perhaps you can show the `Gopkg.toml` and I'll use it by running `dep ensure` after?


Tbh I don't think I am hitting multiple pages with this API strangely. When using the aws cli, it definitely needs paging.

**Comment by jasdel** [comment]
Thanks for helping us with this issue @kaihendry. I've identified this issue as directly related to MediaLive's API sending a NextToken as an empty string. I created PR #94 as a workaround with this issue. I've reached out to the service team also to address this issue, as it may be preventing other SDKs from paginating the API response correctly.

**Comment by kaihendry** [comment]
Hope you go to the https://godoc.org/bufio#Scanner approach, since I am still struggling to comprehend `return true`, aka (continuePaging bool). I also would like a straightforward way of dropping in aws cli style `--query`, preferably in the Input object.

**Comment by jasdel** [comment]
Thanks for the feedback. The idea of the return true is a bit awkward and one reason we are looking at replacing the pagination pattern. I you don't mind please create a new feature request for the `query` concept. We can discuss more how this concept could be incorporated.
