### ISSUE TITLE
[documentation] example code is invalid (pricing.GetProductsInput)

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-go-v2#840]
**Describe the issue with documentation**

The example code is invalid in <https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.24.0/service/pricing#example-Client.GetProductsRequest-Shared00>

```go
input := &pricing.GetProductsInput{
	Filters: []pricing.Filter{
		{
			Field: aws.String("ServiceCode"),
			Type:  pricing.FilterTypeTermMatch,
			Value: aws.String("AmazonEC2"),
		},
		{
			Field: aws.String("volumeType"),
			Type:  pricing.FilterTypeTermMatch,
			Value: aws.String("Provisioned IOPS"),
		},
	},
	FormatVersion: aws.String("aws_v1"),
	MaxResults:    aws.Int64(1),
}
```

…should be…

```go
input := &pricing.GetProductsInput{
	ServiceCode: aws.String("AmazonEC2"),
	Filters: []pricing.Filter{
		{
			Field: aws.String("volumeType"),
			Type:  pricing.FilterTypeTermMatch,
			Value: aws.String("Provisioned IOPS"),
		},
	},
	FormatVersion: aws.String("aws_v1"),
	MaxResults:    aws.Int64(1),
}
```

----

Adding the following for the Google.

```json
{"__type":"InvalidParameterException","Message":"Input Parameters are invalid. serviceCode cannot be null or empty"}
```

```plain
Error: InvalidParameterException: Input Parameters are invalid. serviceCode cannot be null or empty
	status code: 400, request id: f779863d-d7c5-4797-991c-8c3efb93d237
```

**Comment by jasdel** [comment]
Thanks for reporting this issue with the documentation for the generated examples. The v0.25.0 of the SDK does not yet have generated documentation examples like this one. For this specific issue with the AWS Pricing List Service's model, I've notified the team owning those examples of the issue so they can update/clarify the example.

Lets track generated documentation examples feature in https://github.com/aws/aws-sdk-go-v2/issues/844
