### ISSUE TITLE
Where is the awserr package?

### ISSUE THREAD

**Issue by begetan** [aws/aws-sdk-go-v2#849]
**Describe the issue with documentation**
In the Api v2 documentation there is a document about [github.com/aws/aws-sdk-go-v2/aws/awserr
](github.com/aws/aws-sdk-go-v2/aws/awserr) package

This package is no longer exists in the repository? How to refactor code and validate an error?

It looks like the documentation page has no recent changes. Should we relay on this document at all?

**Comment by begetan** [comment]
There is also `external` package in the docs, moved to `config` with last changes. So I guess the whole documentation is not relevant to the current code base.

**Comment by jasdel** [comment]
Hi @begetan thanks for reaching out about the SDK's `awserr` and `external` packages.  Check out the SDK's `v0.25.0` [release's migration guide for v0.24.0 -> v0.25.0](https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#migrating-from-v2-preview-sdks-v0240-to-v0250)

In short the `external` package was moved to a module `config` at the root of the repo, and the `awserr` package was completely removed and replaced with a with a [refactored paradigm](https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#error-handling)
