### ISSUE TITLE
endpoint: internal'ization of package made it difficult to customize default resolver behavior

### ISSUE THREAD

**Issue by moriyoshi** [aws/aws-sdk-go-v2#857]
**Is your feature request related to a problem? Please describe.**

endpoint package used to be public and it offered an API to get the default behavior, but it's virtually impossible to do so because default endpoint resolvers are now implemented as service-specific internals.
 
The following snippet demonstrates such usage that used to be possible.
```
defaultResolver := endpoint.NewDefaultResolver()

aws.EndpointResolverFunc(
    func(service, region string) (aws.Endpoint, error) {
        ...
        // fallback
        return defaultResolver.ResolveEndpoint(service, region)
    },
)
```

**Describe the solution you'd like**

Please republicate the interface.

**Describe alternatives you've considered**

I wouldn't see any viable alternatives as long as it persists in the current API design.

**Comment by skmcgrail** [comment]
@moriyoshi thank you for reaching out us regarding your issue. I believe we can improve the documentation here to be clarify how the `aws.EndpointResolver` and the service client `service.EndpointResolver` compose together. Per the documentation on for [aws.EndpointResolver](https://github.com/aws/aws-sdk-go-v2/blob/v0.28.0/aws/endpoints.go#L48) your implementation of an AWS EndpointResolver may return a [aws.EndpointNotFoundError](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws#EndpointNotFoundError) sentinel if the resolver is not able resolve/provide an endpoint for the requested service or region. When this error type is received the requested will then be delegated to the service client's default resolver.

```go
var cfg aws.Config // normally created via config.LoadDefaultConfig()
cfg.EndpointResolver = aws.EndpointResolverFunc(
    func(service, region string) (aws.Endpoint, error) {
        ...
        // fallback
        return &aws.EndpointNotFoundError{}
    },
)

s3.NewFromConfig(cfg)
```

**Comment by moriyoshi** [comment]
@skmcgrail I was impressed by the quick response. Specifically in the above case, simply returning `EndpointNotFoundError` will suffice, but what if I

1. want the resolve to go no further and also want to just return the "NotFound" error to the initiator of the resolution.
2. want to inspect what the default resolver returns and do some filtering on the result.

**Comment by skmcgrail** [comment]
> @skmcgrail I was impressed by the quick response. Specifically in the above case, simply returning `EndpointNotFoundError` will suffice, but what if I
> 
>     1. want the resolver to go no further and also want to just return the "NotFound" error to the initiator of the resolution.
> 
>     2. want to inspect what the default resolver returns and do some filtering on the result.

1. In this case you can return any error other then `EndpointNotFoundError`, which will trigger to no fallback to occur and the error will be surfaced through the operation returning an error. We could explore renaming this sentinel if it causes confusion regarding the fallback behavior versus reporting an absolute/final error of endpoint could not be resolved.

2. We would be interested in better understanding your use case(s) in this instance. Could you provide more details around what type of data you are looking to query from endpoint resolver and how you are looking to use it within your applications?

Thank you.

**Comment by jasdel** [comment]
Developer guide for [Configuring Client Endpoints](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/) is now available.
