### ISSUE TITLE
Improve the aws.EndpointResolver and Client EndpointResolver Fallback Behavior Documentation With An Example

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#859]
The documentation of the interaction between `aws.EndpointResolver`, `service.EndpointResolver` and the associated fallback behavior via the `aws.EndpointNotFoundError` sentinel value could be further improved with an example that demonstrates said usage pattern.

Related #857

**Comment by jasdel** [comment]
Documentation for custom endpoint resolver behavior can be found at, [Configuring Client Endpoints](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/)
