### ISSUE TITLE
DynamoDB expression.Builder post-v0.25.0

### ISSUE THREAD

**Issue by zubinmadon** [aws/aws-sdk-go-v2#869]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

Just looking for guidance on whether there are plans to port the `expression` package for DynamoDB including the `Builder` class and the related helpers to the post-v0.25.0 world.

**Comment by jasdel** [comment]
Thanks for reaching out and voicing your support for the DynamoDB expression builder utilities. I've created https://github.com/aws/aws-sdk-go-v2/issues/894 that covers the reintroduction of this feature for the v2 SDK. Lets use that issue for tracking this feature.
