### ISSUE TITLE
An AttributeValue may not contain an empty string for key

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#87]
<img src=https://s.natalian.org/2018-01-10/1515557333_2548x1398.png>

[DynamoDB.UpdateItemRequest](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb#DynamoDB.UpdateItemRequest) is quite painful to work with.

If my struct property might be empty, I have to take dynamodb.UpdateItemInput out and create a condition that somehow updates *ExpressionAttributeNames*, *ExpressionAttributeValues* & let's not forget *UpdateExpression*.

I wish it was as easy as the example at https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbattribute when I can dynamodbattribute.MarshalMap my complete struct to **item** and UpdateItemRequest with simply the **Item:**. https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb#UpdateItemInput seems to require a very complex structure for an update. :/ Unless I am missing something?

**Comment by jasdel** [comment]
Thanks for the feedback @kaihendry. To help improve the usability of the DynamoDB expressions, we created the DynamoDB [expression](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb/expression) package. This package provides a lot of builders to construct these expressions so you don't have to do it by hand. The package takes care of the escaping, and reserved words.

This will address most of the issue that you're running into with the expression statement.  Here is an [example](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb/expression#example-Builder-WithUpdate) for building an Update expression.

**Comment by Doug-AWS** [comment]
The developer guide has an example: https://alpha-docs-aws.amazon.com/sdk-for-go/v1/developer-guide/dynamo-example-update-table-item.html

**Comment by kaihendry** [comment]
@Doug-AWS 

```
~$ curl https://alpha-docs-aws.amazon.com/sdk-for-go/v1/developer-guide/dynamo-example-update-table-item.html
curl: (6) Could not resolve host: alpha-docs-aws.amazon.com
```

**Comment by kaihendry** [comment]
Found a great example via Github search here: https://github.com/aws/aws-sdk-go-v2/blob/master/service/dynamodb/expression/examples_test.go

github.com/aws/aws-sdk-go-v2/service/dynamodb/expression is a godsend! However if my values are empty strings, boolean "true" seem to get set in my results. My workaround is to [check they are empty](https://s.natalian.org/2018-01-11/1515650621_1524x1398.png) atm.

**Comment by kaihendry** [comment]
Hmm, also noticed I don't have to dynamodbattribute.MarshalList my values when using this. Less code. I'm all for it.

**Comment by jasdel** [comment]
Thanks for the feedback @kaihendry. You can add the struct tag [`dynamodb:",omitempty"`](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbattribute#Marshal) to the fields that should be not be marshaled. This tag works similar to JSON's omitempty and will not marshal the field if it is a nil pointer or zero value.

**Comment by kaihendry** [comment]
Cool, will try. But the default "true" is a bit unexpected for an empty value, no?

**Comment by xibz** [comment]
@kaihendry - The `encoding/json` package works the same way. So we wanted to be consistent with what the standard library was already doing.

**Comment by kaihendry** [comment]
@xibz .. wait, in JSON strings are empty when empty. Not booleans!

```
cat Gopkg.toml
[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "2.0.0-preview.1"
```

https://play.golang.org/p/f7HC9x2iBNp

**Comment by jasdel** [comment]
Thanks for the sample code @kaihendry. I think what you're seeing here is a confusing aspect of the DynamoDB Console's UI.  If you click on `foobar` item and view its details in the console you'll see the `Title` field's value isn't `true`, but `null`.  I think the DynamoDB Console UI is showing the wrong value here. It should be showing `null` instead.

![screen shot 2018-01-15 at 9 54 35 am](https://user-images.githubusercontent.com/961963/34955675-67943e30-f9da-11e7-8f76-cdeb9c217259.png)

Here's what the text view of the item's value probably looks like.

![screen shot 2018-01-15 at 9 54 58 am](https://user-images.githubusercontent.com/961963/34955699-80278fa6-f9da-11e7-9f9b-c5c056d8dde0.png)

**Comment by kaihendry** [comment]
Argh, you're right. Sorry for the noise. :man_facepalming:
