### ISSUE TITLE
Inconsisent naming of No-op behavior and types in SDK.

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#878]
The SDK uses different patterns for naming no-op behavior, e.g. `smithyhttp.NopClient` vs `logging.Noop`. These SDK should use a single standard naming for consistency.

**Comment by skmcgrail** [comment]
This also includes `NoOpRetryer`, `TestingUsingNoOpSleep`.

**Comment by jasdel** [comment]
Fixed in https://github.com/aws/aws-sdk-go-v2/pull/987
