### ISSUE TITLE
dynamodb/expression: Add expressions utilities

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#894]
The DynamodB attribute value marshaler utilities in the v1 SDK's `/service/dynamodb/dynamoattributevalue` package were removed in the v0.25.0 update. These utilities need to be brought back, and reintroduced to the updated SDK, and refactored for the SDK's list, map, and union representations.

#### Blocking issues
* [x] Smithy model for DynamoDB's API needs to be updated to backfill [tagged union](https://awslabs.github.io/smithy/spec/core.html#union) to the API and similar types.
* [x] SDK use API model to render parameters as value instead of pointers types #896

#### Related issues
* [x] Value doesn't work as expected with dynamodb.AttributeValue #713

**Comment by zubinmadon** [comment]
Thanks for answering my question and filing this issue! I'd like to confirm whether this issue's requirements include the `expression.Builder` functionality, as that is a separate package from the marshaling functionality.

**Comment by jasdel** [comment]
Yes @zubinmadon this issue will cover all of the expression builder functionality the v1 and (<v0.24.0) v2 SDK included
