### ISSUE TITLE
SDK's smithy-go dependency should be stable before SDK's release.

### ISSUE THREAD

**Issue by jasdel** [aws/aws-sdk-go-v2#900]
The SDK's `github.com/awslabs/smithy-go` dependency provides the core middleware and protocol encoding behavior. This module is not yet releases as general availability (GA), and is still in flux. Before the SDK can have a GA release this module will need to be stabilized.

`smithy-go`'s path to GA: https://github.com/awslabs/smithy-go/milestone/1

**Comment by skmcgrail** [comment]
Smithy repository location has been transferred to AWS GitHub Organization. https://github.com/aws/smithy-go
