### ISSUE TITLE
LocationRestraint always empty on GetBucketLocation call

### ISSUE THREAD

**Issue by jcarter3** [aws/aws-sdk-go-v2#908]
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
`GetBucketLocation` returns empty LocationConstraint

**Version of AWS SDK for Go?**
Example: v0.29.0

**Version of Go (`go version`)?**
go version go1.15.5 linux/amd64

**To Reproduce (observed behavior)**
```go
cfg, err := config.LoadDefaultConfig()
// check err
svc := s3.NewFromConfig(cfg)
bucketLocation, err := svc.GetBucketLocation(context.Background(), &s3.GetBucketLocationInput{Bucket: aws.String("somebucket")})
// check err
fmt.Printf("bucket location: %v\n", bucketLocation.LocationConstraint)
// prints empty location for all buckets in all regions, (even those outside us-east-1)
```
**Expected behavior**
For the region that the bucket exists in to be returned (only nil/empty for buckets in us-east-1, per the documentation).

**Additional context**
I've validated that the proper region is returned via the aws cli

**Comment by LumpKim** [comment]
Is any solution for this? I had same issue about `s3.client.GetBucketLocationOutput.LocationCostraint` is empty.

**Comment by jasdel** [comment]
Thanks for reporting this issue @jcarter3  and @LumpKim  we're investigating what the cause of this issue is.

**Comment by Chandrian** [comment]
I'm having the same issue, I tried with an assume role using the assume role workaround and getting the same empty result.
This was working in older v2 version. I'm using RC now


ctx := context.TODO()
cfg, err = config.LoadDefaultConfig(ctx,
			//config.WithClientLogMode(aws.LogSigning|aws.LogRequestWithBody|aws.LogResponseWithBody),
			// This can be remove when the following bug has been fixed and dependencies updated to latest
			// https://github.com/aws/aws-sdk-go-v2/issues/914
			//config.WithClientLogMode(aws.LogSigning|aws.LogRequestWithBody|aws.LogResponseWithBody),
			config.WithAPIOptions([]func(stack *middleware.Stack) error{
				func(stack *middleware.Stack) error {
					return stack.Initialize.Add(clearContextContentSha256{}, middleware.Before)
				},
			}),
		)
		if err != nil {
			log.Fatal("failed to load config, %w", err)
		}
		cfg.Credentials = aws.NewCredentialsCache(stscreds.NewAssumeRoleProvider(
			sts.NewFromConfig(cfg),
			"arn:aws:iam::123456789012:role/RO"))

		s3Client := s3.NewFromConfig(cfg)

getBucketLocationResponse, err := s3Client.GetBucketLocation(context.Background(), 
     &s3.GetBucketLocationInput{Bucket: bucket.Name})
			if err != nil {
				log.Printf("failed to access the bucket: %s. Error message: %v", *bucket.Name, err.Error())
				continue
			}
