### ISSUE TITLE
DescribeInstanceTypes does not return VCpuInfo

### ISSUE THREAD

**Issue by r0kas** [aws/aws-sdk-go-v2#910]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
When describing an InstanceType like "t3a.large" or "t3a.xlarge" in returned 'InstanceTypeInfo' information about vCPUs is empty - `VCpuInfo` is nil.

In comparison `MemoryInfo` is fine and has all the details.

aws-sdk-go v1 does not have this issue and works as expected.

**Version of AWS SDK for Go?**
v0.29.0

**Version of Go (`go version`)?**
v1.15.2

**To Reproduce (observed behavior)**

	reqInput := &ec2.DescribeInstanceTypesInput{
		InstanceTypes: []types.InstanceType{types.InstanceType("t3a.large")},
	}

	info, err := p.ec2.DescribeInstanceTypes(ctx, reqInput)
	if err != nil {
		return nil, fmt.Errorf("describing instance type %q: %v", instanceType, err)
	}

	fmt.Println(info.InstanceTypes[0].VCpuInfo)

Output: nil

**Expected behavior**
Expected output:
{
  DefaultCores: 1,
  DefaultThreadsPerCore: 2,
  DefaultVCpus: 2,
  ValidCores: [1],
  ValidThreadsPerCore: [1,2]
}

**Additional context**
Tried this out on "t3a.large" and "t3a.xlarge" instance types. Same behavior on both.
aws-sdk-go v1 works as expected.

**Comment by skmcgrail** [comment]
Thanks for reporting this issue @r0kas, I can confirm this behavior and have narrowed it down to a deserialization bug. We will have this fixed in our next release.
