### ISSUE TITLE
CompleteMultipartUpload xml has a bad tag name "CompletedMultipartUpload" (need remove the 'd' letter)

### ISSUE THREAD

**Issue by nabbar** [aws/aws-sdk-go-v2#927]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/), direct bug aws docs reference : https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
The xml sent to complete a multipart upload has a bad tag name. The tag name sent is "CompletedMultipartUpload" (cf line 153 in the file : https://github.com/aws/aws-sdk-go-v2/blob/master/service/s3/serializers.go#L153) 
![image](https://user-images.githubusercontent.com/19818221/100108786-72f57780-2e6b-11eb-80b0-34fbb090548e.png)

The AWS API reference documentation report that the tag name must be "CompleteMultipartUpload" (not the 'd' at the end of Complete word). You can find it at this link https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html : 
![image](https://user-images.githubusercontent.com/19818221/100109120-cff12d80-2e6b-11eb-9650-163bd4e97bd7.png)

I think this bug was appear with the v0.26.0 release and later (as the v0.29.0 I use).

**Version of AWS SDK for Go: v0.29.0**

**Version of Go : go1.15.2**

**Comment by nabbar** [comment]
Strangely, when I looking for this bug into the smithy definition model json, I don't find it 

https://github.com/aws/aws-sdk-go-v2/blob/v0.29.0/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L1185
![image](https://user-images.githubusercontent.com/19818221/100209599-5e1bf100-2f0a-11eb-852a-9f4ff76b1d71.png)


Maybe a bug into the codegen ?

Or need defined the `xmlname` into the `traits` definition of the structure CompletedMultipartUpload at line 1208 ?https://github.com/aws/aws-sdk-go-v2/blob/v0.29.0/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L1208

![image](https://user-images.githubusercontent.com/19818221/100209880-aa673100-2f0a-11eb-8448-cc8097886594.png)

thanks in advance for helping :)

**Comment by skmcgrail** [comment]
Thank you for bringing this to our attention @nabbar and your detailed research into the issue. This appears to be an edge case in our code generation that is not correctly applying the [xmlName](https://awslabs.github.io/smithy/1.0/spec/core/xml-traits.html#xmlname-trait) trait. We will work on getting this fixed in our next release.

**Comment by jasdel** [comment]
This issue was fixed in https://github.com/aws/aws-sdk-go-v2/pull/965 and will be included in the SDK's tagged release.
