### ISSUE TITLE
CopySource can't use Chinese name when using copy object

### ISSUE THREAD

**Issue by Zstro** [aws/aws-sdk-go-v2#934]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
I used CopyObjectRequest to turn my object class to `StorageClassStandardIa`,and object name was `小狗.jpg`. SO S3 return err when CopySource was Chinese:
```
expect no error, got NoSuchKey: The specified key does not exist.
        	status code: 404, request id: 4V9G4TBMDK2TBV5W, host id: hagWPzEX1duUZ6qkP2IZFdPqay/xqao43cDg2guu+bZPamuiqVUod4UU2eRkXAq8qP1ASbjf80E=
```
And It's works when I encoded it.
```
	req := s.CopyObjectRequest(&s3.CopyObjectInput{
		Bucket:     aws.String("mybucket"),
		Key:        aws.String("小狗.jpg"),
		CopySource: aws.String("mybucket/%E5%B0%8F%E7%8B%97.jpg"),
		StorageClass: s3.StorageClassStandardIa,
	})

	resp, err := req.Send(context.Background())
	if err != nil {
		t.Fatalf("expect no error, got %v", err)
	}
	t.Log(resp)
```

**Version of AWS SDK for Go?**

v0.24.0

**Version of Go (`go version`)?**

1.14.4

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```
	req := s.CopyObjectRequest(&s3.CopyObjectInput{
		Bucket:     aws.String("mybucket"),
		Key:        aws.String("小狗.jpg"),
		CopySource: aws.String("mybucket/小狗.jpg"),
		StorageClass: s3.StorageClassStandardIa,
	})

	resp, err := req.Send(context.Background())
	if err != nil {
		t.Fatalf("expect no error, got %v", err)
	}
	t.Log(resp)
```

**Expected behavior**

**Additional context**

**Comment by skmcgrail** [comment]
Per the S3 CopyObject documentation, the value provided for the `CopySource` parameter must be URL encoded. You will need to encode your value before setting the member on the input structure.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html

**Comment by Doug-AWS** [comment]
Use: "net/url"
Then for Key and CopySource:
aws.String(url.PathEscape("小狗.jpg"))
and CopySource:
aws.String(url.PathEscape("mybucket/小狗.jpg"))

**Comment by Zstro** [comment]
Any other issues to encode it in the SDK?

**Comment by Zstro** [comment]
When I used `url.PathEscape("小狗.jpg")`,it's became:
![image](https://user-images.githubusercontent.com/49179307/100822891-2bd03d80-348e-11eb-80a4-17107380fb7f.png)
And it's not work when used `CopySource: aws.String(url.PathEscape("zztet/小狗.jpg?versionId=SFS7ADxiYqdCeipm3X27Zw6MyeSrtIVD"))`,it's coding special char like `/,?`
![image](https://user-images.githubusercontent.com/49179307/100823201-be70dc80-348e-11eb-9731-21d5a7d140b5.png)
and return err: 
![image](https://user-images.githubusercontent.com/49179307/100823743-c1200180-348f-11eb-89b5-13986c1c7469.png)

The right result: `CopySource: aws.String("zztet/%E5%B0%8F%E7%8B%97.jpg?versionId=SFS7ADxiYqdCeipm3X27Zw6MyeSrtIVD")`
![image](https://user-images.githubusercontent.com/49179307/100823383-127bc100-348f-11eb-8e94-241cf8cc09f9.png)
![image](https://user-images.githubusercontent.com/49179307/100823429-29221800-348f-11eb-8d1b-6d882c10f448.png)

![image](https://user-images.githubusercontent.com/49179307/100823532-58388980-348f-11eb-91f3-6e3c2a7d717d.png)

**Comment by skmcgrail** [comment]
Hello @Zstro thanks for reaching back out to us, I've gone ahead and done some testing and it appears the Amazon S3 API documentation is a bit vague in this situation. From my testing the `?versionId=<version-id>` portion of the value should not be URI escaped.

Testing with the following versions (latest release):
```
require (
	github.com/aws/aws-sdk-go-v2 v0.30.0
	github.com/aws/aws-sdk-go-v2/config v0.3.0
	github.com/aws/aws-sdk-go-v2/service/s3 v0.30.0
)
```

```go
func main() {
	cfg, err := config.LoadDefaultConfig()
	if err != nil {
		log.Fatal(err)
	}

	client := s3.NewFromConfig(cfg)

	sourceKey := "unicode/一つ"
	putObjectOutput, err := client.PutObject(context.Background(), &s3.PutObjectInput{
		Bucket: &bucket,
		Key:    aws.String(sourceKey),
		Body:   bytes.NewReader(data),
	})
	if err != nil {
		log.Fatal(err)
	}

	copyKey := "unicode/二つ"
	_, err = client.CopyObject(context.Background(), &s3.CopyObjectInput{
		Bucket: &bucket,
		Key:    &copyKey,
		CopySource: aws.String(fmt.Sprintf("%s?versionId=%s", url.PathEscape(bucket+"/"+sourceKey),
			*putObjectOutput.VersionId)),
	})
	if err != nil {
		log.Fatal(err)
	}
}
```

Console:
<img width="803" alt="Screen Shot 2020-12-02 at 12 26 28 PM" src="https://user-images.githubusercontent.com/549813/100927520-dac64680-3499-11eb-8fba-b2573adb7a55.png">
<img width="661" alt="Screen Shot 2020-12-02 at 12 26 39 PM" src="https://user-images.githubusercontent.com/549813/100927537-def26400-3499-11eb-90d2-9c771ffd847b.png">

Header Wire Capture:
<img width="830" alt="Screen Shot 2020-12-02 at 12 27 11 PM" src="https://user-images.githubusercontent.com/549813/100927578-edd91680-3499-11eb-9d62-0e47831503b3.png">

Let me know if this helps resolve your issue.

**Comment by Zstro** [comment]
OK，thanks for answers.But why not encode it in the SDK?

**Comment by skmcgrail** [comment]
This is a limitation of the current S3 model which does not have the ability to define a different encoding behavior for this specific field. We do not currently have plans to customize or change this behavior to work around the limitation of the model.
