### ISSUE TITLE
501 api error NotImplemented when calling PutObject with empty Body

### ISSUE THREAD

**Issue by mhart** [aws/aws-sdk-go-v2#937]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

When calling `s3.PutObject` with an empty Body, I always get a 501 response, even if I also manually set `ContentLength` to be `0`. This does not occur with v1 of the SDK.

The error is along the lines of:

```
operation error S3: PutObject, https response error StatusCode: 501, RequestID: X, HostID: Y,
api error NotImplemented: A header you provided implies functionality that is not implemented
```

**Version of AWS SDK for Go?**
v0.29.0

**Version of Go (`go version`)?**
go version go1.15.5 darwin/amd64

**To Reproduce (observed behavior)**

```go
svc.PutObject(ctx, &s3.PutObjectInput{
  Bucket: &myBucket,
  Key:    &myKey,
  Body:   aws.ReadSeekCloser(strings.NewReader("")),
})
```
Or:
```go
svc.PutObject(ctx, &s3.PutObjectInput{
  Bucket: &myBucket,
  Key:    &myKey,
  Body:   aws.ReadSeekCloser(bytes.NewReader([]byte{})),
})
```
Setting `ContentLength` manually doesn't help (as it appears to in other SDKs):
```go
svc.PutObject(ctx, &s3.PutObjectInput{
  Bucket: &myBucket,
  Key:    &myKey,
  Body:   aws.ReadSeekCloser(bytes.NewReader([]byte{})),
  ContentLength: aws.Int64(0),
})
```

**Comment by mhart** [comment]
FWIW, a workaround is to use `nil` for the Body – that seems to work correctly

**Comment by skotambkar** [comment]
Thanks for reaching out to us.  We've merged in #920 and awslabs/smithy-go#236 to fix the issue with empty body as input. A tagged release of the sdk will be released earlier next week for these changes.

**Comment by mhart** [comment]
Thanks @skotambkar . I should also mention that I couldn't get logging to work at all when trying to debug this. There's a guide over at https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/logging/ but I couldn't get it to work.

Maybe it's for an unreleased version? If so, I feel like documentation shouldn't be live unless it reflects the latest released version.

**Comment by skotambkar** [comment]
Thanks @mhart we have updated the SDK and tagged a release https://github.com/aws/aws-sdk-go-v2/releases/tag/v0.30.0
