### ISSUE TITLE
EC2 Waiters missing since v0.25.0

### ISSUE THREAD

**Issue by RyanJarv** [aws/aws-sdk-go-v2#938]
It seems like the waiters from the EC2 client have been removed but not yet added to the EC2 client.

Mostly just opening this ticket for either someone to correct me on this, or if not at least it should be helpful for anyone else that happens to run into this issue.

Info relating to changes in how waiters are handled since v0.25.0: https://github.com/aws/aws-sdk-go-v2/issues/442

**Comment by jasdel** [comment]
Thanks for reaching out @RyanJarv. correct, waiters were removed as apart of the v0.25.0 update, and have not been read yet due to the API client design change. Issue #442 tracks this, and will be the best place to discuss waiters being added back.
