### ISSUE TITLE
 Developer Guide: Unit-Testing

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-sdk-go-v2#947]
The Developer Guide should provide a section on how to write unit-tests for applications that use the AWS SDK for Go V2, and how to mock the SDK appropriately.

**Comment by Doug-AWS** [comment]
Have you seen any of the existing unit tests for the Go V2 code examples in our GitHub repo? Just look for *_test.go in any leaf of https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/gov2.
