### ISSUE TITLE
Pre-signed Get Uses Signed Payload Option

### ISSUE THREAD

**Issue by asterikx** [aws/aws-sdk-go-v2#950]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [API reference](https://github.com/aws/aws-sdk-go-v2/issues)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers

I'm using pre-signed URLs in a web app (cross-tenant SaaS product) to download objects from a private bucket. After upgrading from `aws-sdk-go-v1` to `aws-sdk-go-v2` (`v0.30.0`), I'm hitting `SignatureDoesNotMatch` errors using the generated pre-signed URLs in HTML links.

My scenario is: 

1. user clicks a button on a web page to download a specific file
2. button click handler calls a custom API endpoint
3. API handler calls `s3.PresignClient.PresignGetObject` and returns the pre-signed URL
4. button click handler sets the href attribute of an (invisible) HTML link element to the received URL
5. button click handler simulates click on the link element
6. browser initiates file download using the pre-signed URL set in 4.

In step 6, I get the `SignatureDoesNotMatch` error.

The request in step 6 has `X-Amz-SignedHeaders` set to `host;x-amz-content-sha256`, however, it does **not** include the `x-amz-content-sha256`header. That's likely causing the `SignatureDoesNotMatch` error. I can confirm that `s3.PresignClient.PresignGetObject` returns `host` and `x-amz-content-sha256` in the `SignedHeader` field.

I have two questions:

1.  Why should a pre-signed **get** request use payload signatures? For put operations, it makes sense to prevent malicious uploads, but I don't see why read operations should use them. Why was it added in v2?
2. How can I work around the error? E.g. how can I disable payload signatures for pre-signed get requests? Is there a better approach to browser-based downloads?

Thanks for any help.

**Comment by asterikx** [comment]
Interesting enough, payload signing is skipped by default for put operations:

https://github.com/aws/aws-sdk-go-v2/blob/8baa5f464a5dee3456ad62d9caa978e3c2572c8b/service/s3/api_op_PutObject.go#L449-L453

but not for get operations:

https://github.com/aws/aws-sdk-go-v2/blob/8baa5f464a5dee3456ad62d9caa978e3c2572c8b/service/s3/api_op_GetObject.go#L498-L501

Shouldn't it be the other way around? I.e. payload signing enabled by default for put operations and disabled for get operations.

Based on the pre-sign put operation implementations, I could work around my issue, by manually skipping payload signing for pre-sign get operations:

```go
req, err := c.PresignGetObject(
  ctx,
  &s3.GetObjectInput{Bucket: bucket, Key: key},
  s3.WithPresignExpires(expiresIn),
  withUnsignedPayload(),
)
```

```go
func withUnsignedPayload() func(*s3.PresignOptions) {
  return s3.WithPresignClientFromClientOptions(func(options *s3.Options) {
    options.APIOptions = append(options.APIOptions, func(stack *middleware.Stack) error {
      v4.RemoveContentSHA256HeaderMiddleware(stack)
      v4.RemoveComputePayloadSHA256Middleware(stack)
      return v4.AddUnsignedPayloadMiddleware(stack)
    })
  })
}
```

Still, I'm interested in knowing the reasons that motivated the current implementation. I wonder if I'm missing something.

**Comment by jasdel** [comment]
Thanks for reporting this issue, it has been fixed in https://github.com/aws/aws-sdk-go-v2/pull/967 and will be included in the SDK's next tagged release.
