### ISSUE TITLE
`Codegen`: Update `smithy-aws-traits` dep to latest 

### ISSUE THREAD

**Issue by skotambkar** [aws/aws-sdk-go-v2#971]
Update codegen/smithy-aws-go-codegen/build.gradle.kts  with latest  dependency

```api("software.amazon.smithy:smithy-aws-traits:[1.4.0,2.0.0[")```

Related to https://github.com/aws/aws-sdk-go-v2/pull/970

**Comment by jasdel** [comment]
Pending https://github.com/aws/aws-sdk-go-v2/issues/989 being resolved.
