### ISSUE TITLE
Context everywhere is stupid

### ISSUE THREAD

**Issue by haalcala** [aws/aws-sdk-go-v2#994]
Why don't you just return a cursor object similar to a cursor database.  And how the hell I should obtain an instance of a Context??  I just wanted to list the Stacks in cloudformation.

Golang was written with the objective of typing less codes.

**Comment by skmcgrail** [comment]
The following resources are available to you to better understand the context type and how to use it:
https://golang.org/pkg/context/
https://blog.golang.org/context
