### ISSUE TITLE
DescribeVpcEndpointConnections is returning empty reponse

### ISSUE THREAD

**Issue by gowrisankar22** [aws/aws-sdk-go-v2#995]
Hello All,

I am trying to use the DescribeVpcEndpointConnections[1][2] to list all the available vpc endpoints but it is not returning the values. Looks like an issue?

but aws cli is working fine using `aws ec2 describe-vpc-endpoints`

**Response:**
```
VPC endpoint: Details:
{
	"NextToken": null,
	"VpcEndpointConnections": [],
	"ResultMetadata": {}
}
```

**DescribeVpcEndpointConnections**

```
package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
)

func main() {
	cfg, err := config.LoadDefaultConfig(context.TODO(),
		config.WithRegion("eu-central-1"),
	)
	if err != nil {
		panic(fmt.Sprintf("failed loading config, %v", err))
	}

	client := ec2.NewFromConfig(cfg)

	input := &ec2.DescribeVpcEndpointConnectionsInput{}

	resp, err := client.DescribeVpcEndpointConnections(context.Background(), input)

	if err != nil {
		fmt.Println("Got an error retrieving information about your VPC endpoint:")
		fmt.Println(err)
		return
	}

	fmt.Println("VPC endpoint: Details:")
	respDecrypted, _ := json.MarshalIndent(resp, "", "\t")
	fmt.Println(string(respDecrypted))
}
```

[1] https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#DescribeVpcEndpointConnectionsInput
[2] https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#DescribeVpcEndpointConnections

**Comment by jasdel** [comment]
Thanks for reporting this issue @gowrisankar22 I think this is related to the fix in https://github.com/aws/aws-sdk-go-v2/pull/992 . The SDK was incorrectly deserializing XML document responses.

**Comment by gowrisankar22** [comment]
@jasdel what is the tentative timeline for the next release? our development blocked due to this issue.

**Comment by gowrisankar22** [comment]
@jasdel I have tried with v0.31 but still, the issue not yet fixed. 

the same was working fine with version v0.29

**Comment by skmcgrail** [comment]
I am not able to replicate this behavior on v0.31.0. I created an VPC Endpoint Service in the console, attached the endpoint to a VPC and was able to use the code you provided to attempt to reproduce the issue.

Can you please enable response logging following the  [logging guide](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/logging) to confirm that you are getting an expected response from the service?

**Comment by gowrisankar22** [comment]
@skmcgrail I have added the logger but I don't see any logs but it looks strange for me .. 

I am using **go version go1.15.6 darwin/amd64**.

```
var applicationLogger logging.Logger
cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithLogger(applicationLogger))
```

**Comment by skmcgrail** [comment]
You will also need to pass `config.WithClientLogMode(aws.LogResponseWithBody)` to `LoadDefaultConfig` to enable the logging of the response body.

**Comment by gowrisankar22** [comment]
@skmcgrail 
I have received the below response
```
SDK 2020/12/25 08:20:58 DEBUG Response
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Content-Type: text/xml;charset=UTF-8
Date: Fri, 25 Dec 2020 02:50:58 GMT
Server: AmazonEC2
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: accept-encoding
X-Amzn-Requestid: 889ec0b3-197f-4aff-8a62-8a7e9332e1f6

10a
<?xml version="1.0" encoding="UTF-8"?>
<DescribeVpcEndpointConnectionsResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
    <requestId>889ec0b3-197f-4aff-8a62-8a7e9332e1f6</requestId>
    <vpcEndpointConnectionSet/>
</DescribeVpcEndpointConnectionsResponse>
0

VPC endpoint: Details:
{
	"NextToken": null,
	"VpcEndpointConnections": [],
	"ResultMetadata": {}
}
```

**Comment by skmcgrail** [comment]
As indicated by the output of the raw HTTP response, the service is returning you no items as indicated by `<vpcEndpointConnectionSet/>`. Please confirm that you are using the correct API, from my testing and understanding, this API only returns connections details to VPC Endpoints (AWS PrivateLink) for services hosted by you in your account, or another AWS customer account. This API does not include details for PrivateLink connections provided by AWS services like EC2 or DynamoDB. See the [AWS PrivateLink and VPC endpoints](https://docs.aws.amazon.com/vpc/latest/userguide/endpoint-services-overview.html) user guide.

**Comment by gowrisankar22** [comment]
@skmcgrail Yes, it should return the vpcendpoints details that's what my expectation as well. The same code was working with SDK `0.30` but it is not working after updating to `0.31`

I am not exactly sure whats really wrong
