### ISSUE TITLE
DescribeVpcEndpointConnectionsInput not implemented with the filter using vpc-id

### ISSUE THREAD

**Issue by gowrisankar22** [aws/aws-sdk-go-v2#996]
Hello All,

I am trying to apply the filter for vpcendpoints based on the filter criteria **vpc-id** but currently, it is not implemented via golang SDK. 

This makes it harder if I have multiple vpcs under the same account to identify how many vpc endpoints created per specific vpc.

It would be great if you can help me with an alternative until this feature is there.

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#DescribeVpcEndpointConnectionsInput

BTW, this work with aws cli

```
aws ec2 describe-vpc-endpoints --filters Name=vpc-id,Values=vpc-xxxx
```

```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
	"github.com/aws/aws-sdk-go-v2/service/ec2/types"
)

var (
	vpcendpointidFilterType string = "vpc-id"
	vpcid string = "vxxxx"
)

func main() {
	cfg, err := config.LoadDefaultConfig(config.WithRegion("eu-central-1"))
	if err != nil {
		panic("configuration error, " + err.Error())
	}

	client := ec2.NewFromConfig(cfg)

	input := &ec2.DescribeVpcEndpointConnectionsInput{
		Filters: []types.Filter{
			{
				Name:   &vpcendpointidFilterType,
				Values: []string{vpcid},
			},
		},
	}
	
	resp, err := client.DescribeVpcEndpointConnections(context.Background(), input)

	if err != nil {
		fmt.Println("Got an error retrieving information about your VPC endpoint:")
		fmt.Println(err)
		return
	}

	fmt.Println("VPC endpoint: Details:")
	respDecrypted, _ := json.MarshalIndent(resp, "", "\t")
	fmt.Println(string(respDecrypted))

}
```

```
Got an error retrieving information about your VPC endpoint:
operation error EC2: DescribeVpcEndpointConnections, https response error StatusCode: 400, RequestID: d0e123fa-1b3b-4eb3-a7e4-fa8522633924, api error InvalidFilter: The filter 'vpc-id' is invalid
```

**Comment by skmcgrail** [comment]
The `DescribeVpcEndpoints` API call that you use in the AWS CLI command is not the same as the `DescribeVpcEndpointConnections` API call you are making in Go. Please see the supported filters for [DescribeVpcEndpointConnections](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpointConnections.html) in the Amazon EC2 API Reference Guide.

**Comment by gowrisankar22** [comment]
@skmcgrail sure .. but the request is to implement  the same ..

**Comment by skmcgrail** [comment]
As this is a service API limitation and not functionality that would be implemented on the SDK, I suggest opening a new thread in the service's AWS Forums or reaching out to the AWS Premium Support. When reaching out to Premium Support,  open a new technical support case under the Amazon EC2 service and select the Feature Request category to suggest the implementation of this filter condition.
